### ISSUE TITLE
any command 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1001]
Sir , is there anyway  to  acpi verson by cmd on windows 10 64bit 1803

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eea1fbb-7f7d-d32d-da26-07f6499b3336
* Version Independent ID: 3fed902a-fb51-cd76-29d1-3fdaa97d847f
* Content: [How to Identify the Windows Version in ACPI by Using _OSI - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/acpi/winacpi-osi)
* Content Source: [windows-driver-docs-pr/acpi/winacpi-osi.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/acpi/winacpi-osi.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@RAJU2529 - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
