### ISSUE TITLE
Just now i downloaded binscope

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1002]
Sir today i downloaded binscope binary analyzer which is  2014 old version , and i installed 64bit v on windows 10 64bit 1803 , installed location is "C:\Program Files\Microsoft BinScope 2014".
I want to check already installed  drivers , which are located under"C:\Windows\System32\drivers"

and then i  run command prompt 
cd /d C:\Program Files\Microsoft BinScope 2014
binscope.exe C:\Windows\System32\drivers\AsRadioControl.sys  /verbose /html /logfile C:\htmllogs\AsRadioControl.html

after that  i viewed report in .html , i wondered some of security checks are failed for  AsRadioControl.sys::

ATLVersionCheck (FAIL)
ATLVulnCheck (FAIL)
CompilerVersionCheck (FAIL)
GSCheck (FAIL)
GSFriendlyInitCheck (FAIL)
GSFunctionSafeBuffersCheck (FAIL)
RSA32Check (FAIL)
VB6Check (FAIL)
Passed Checks
DBCheck (PASS)
DefaultGSCookieCheck (PASS)
ExecutableImportsCheck (PASS)
HighEntropyVACheck (PASS)
NXCheck (PASS)
SafeSEHCheck (PASS)
SharedSectionCheck (PASS)
WXCheck (PASS)

in next step what should i do ,  should  i report about that AsRadioControl.sys  driver manufacturer with  report.html via email 

Please guide me
Thanks  for wonderfull  information about driver security  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6298d0a1-1f6b-6e00-5445-dfec501a4430
* Version Independent ID: 42f902a4-b1df-b863-7486-de26c54a205f
* Content: [Driver security checklist - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/driversecurity/driver-security-checklist#dgc)
* Content Source: [windows-driver-docs-pr/driversecurity/driver-security-checklist.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/driversecurity/driver-security-checklist.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@RAJU2529 - Thanks for reaching out to the Windows Driver Developer Documentation team. It would be difficult to say what the security goals are for any particular driver vendor and how this tool may work with their code. Beyond that, we unfortunately don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
