### ISSUE TITLE
Is it correct path for symbol

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1003]
just now added symbol  path like this , i run below commands on cmd 

md C:\Windows\Symbol
set _NT_SYMBOL_PATH=srv*C:\Windows\Symbol*https://msdl.microsoft.com/download/symbols

Is above commnds are correct , should i add further   symbol cache folder ?
if needed means , pleave tell me the command  to add symbol cache .

Thanking you sir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7231888-3d4f-3a7c-cae3-2038f34f31bb
* Version Independent ID: 9f100c05-e2f9-f3d2-c818-e9d977a25ef6
* Content: [Microsoft public symbol server - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/debugger/microsoft-public-symbols)
* Content Source: [windows-driver-docs-pr/debugger/microsoft-public-symbols.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/microsoft-public-symbols.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@RAJU2529 - Working with symbols can be a challenge. These topics can help you get started:

[Symbol Problems While Debugging](https://docs.microsoft.com/en-in/windows-hardware/drivers/debugger/symbol-problems-while-debugging)
[Introduction to Symbols](https://docs.microsoft.com/en-in/windows-hardware/drivers/debugger/introduction-to-symbols)

Beyond that guidance, unfortunately we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
