### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by SIISII** [MicrosoftDocs/windows-driver-docs#1004]
Link to DispatchClose isn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5e886a-4bde-6ba5-f5cb-1ad04e9c89be
* Version Independent ID: 94aa09f0-fae7-e087-b411-bd2d02d80c8f
* Content: [IRP_MJ_CLOSE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/irp-mj-close)
* Content Source: [windows-driver-docs-pr/kernel/irp-mj-close.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/irp-mj-close.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Fixed in source to [*DispatchClose*](separate-dispatchcreate-and-dispatchclose-routines.md). Should be live shortly. Thank you, @SIISII  for catching this!
