### ISSUE TITLE
WdfDeviceCreate return STATUS_INVALID_SECURITY_DESCR in this example

### ISSUE THREAD

**Issue by GreatFireWall** [MicrosoftDocs/windows-driver-docs#1005]
My code base on WDF in kernel mode, learn from "Specifying an Unload Function" and this section. 
WdfDeviceCreate return STATUS_INVALID_SECURITY_DESCR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 346f1ec1-7bc8-1eca-5621-244ce256f176
* Version Independent ID: 6dd4eab8-267e-4e14-74eb-e08471b3012e
* Content: [Creating a Device Object - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/creating-a-device-object)
* Content Source: [windows-driver-docs-pr/network/creating-a-device-object.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/creating-a-device-object.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @GreatFireWall, 

The first thing I'd recommend is to check out the WFP sample drivers in the [Windows Driver samples](https://github.com/Microsoft/Windows-driver-samples), especially the Inspect and WFPSampler drivers.

Aside from that, I'm sorry you're having an issue but unfortunately we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

• [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
• [NTDEV forum at OSR Online](https://community.osr.com/)

Again, thanks for reaching out. Best of luck with this issue.
