### ISSUE TITLE
Undefined symbol NET_BUFFER_LIST

### ISSUE THREAD

**Issue by GreatFireWall** [MicrosoftDocs/windows-driver-docs#1006]
these are my all header files included:
#include &lt;ntddk.h&gt;
#include &lt;wdf.h&gt;
#include &lt;fwpsk.h&gt;
#include &lt;fwpmk.h&gt;

Then build failed, Undefined symbol NET_BUFFER_LIST

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d23ce87-c3ae-4e2b-ce12-ecb66c8065c0
* Version Independent ID: 6b57dfbb-a5e7-c018-6770-446451c58c5a
* Content: [Registering Callouts with the Filter Engine - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/registering-callouts-with-the-filter-engine)
* Content Source: [windows-driver-docs-pr/network/registering-callouts-with-the-filter-engine.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/registering-callouts-with-the-filter-engine.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @GreatFireWall,

For this kind of error, I'd recommend that you not only make sure to include the correct headers in your project's include directories, but include the correct libraries in your project's lib directories.

Other than that, I'm sorry you're having an issue but unfortunately we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

• [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
• [NTDEV forum at OSR Online](https://community.osr.com/)

Again, thanks for reaching out. Best of luck with this issue.
