### ISSUE TITLE
"_DSM Interface for Byte Addressable Energy Backed Function Class (Function Interface 1)" How can i evaluate this APCI method based on the windows driver"scmdisk0101.sys"?"

### ISSUE THREAD

**Issue by MKingSWang** [MicrosoftDocs/windows-driver-docs#1011]
windows-driver-docs/windows-driver-docs-pr/storage/-dsm-interface-for-byte-addressable-energy-backed-function-class--function-interface-1-.md
 I want to manage the nvdimm by using this ACPI control method"_DSM Interface for Byte Addressable Energy Backed Function Class" witch defined by Microsoft, i have two questions:
1. Will i develop a stroage driver to handle this ACPI _DSM IO requst?
2. Can i use the "scmdisk0101.sys" driver to handle this ACPI _DSM IO request? If yes, then how?

**Comment by EliotSeattle** [comment]
Hi @MKingSWang.

Unfortunately, we don’t have the  resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft  engineers can be found. The community there is quite responsive.
[Windows Hardware WDK and driver development forum](https://social.msdn.microsoft.com/Forums/windowshardware/en-US/home?forum=wdk)
[OSR NTDEV forum](http://www.osronline.com/cf.cfm?PageURL=showlists.cfm?list=NTDEV)

Again, thanks for reaching out. Best of luck with this issue.
@EliotSeattle
