### ISSUE TITLE
Blue Screen Windows 10

### ISSUE THREAD

**Issue by PetrG68** [MicrosoftDocs/windows-driver-docs#1018]
On Thu 08.11.2018 14:26:53 your computer crashed or a problem was reported
crash dump file: C:\Windows\Minidump\110818-14062-01.dmp
This was probably caused by the following module: ntoskrnl.exe (nt+0x1A9490) 
Bugcheck code: 0x154 (0xFFFF838B24463000, 0xFFFFE88A92F516B0, 0x2, 0x0)
Error: UNEXPECTED_STORE_EXCEPTION
file path: C:\WINDOWS\system32\ntoskrnl.exe
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: NT Kernel & System
Bug check description: This indicates that the store component caught an unexpected exception. 
This appears to be a typical software driver bug and is not likely to be caused by a hardware problem. 
The crash took place in the Windows kernel. Possibly this problem is caused by another driver that cannot be identified at this time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05c732ce-fd6c-98e4-19ca-f52c6dd3e7b5
* Version Independent ID: 868b8c46-2096-9d10-2f6b-f015e6a57003
* Content: [Bug Check 0x154 UNEXPECTED_STORE_EXCEPTION - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x154--unexpected-store-exception)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x154--unexpected-store-exception.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x154--unexpected-store-exception.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@PetrG68 - I don't see a comment on the docs here, so closing this issue. If you are looking for developer guidance from the developer community, you might look at this forum:
- [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
