### ISSUE TITLE
SimpleMediaSource::GetEvent() wrong pointer is used

### ISSUE THREAD

**Issue by persskog** [MicrosoftDocs/windows-driver-docs#1034]
RETURN_IF_FAILED (_spEventQueue-&gt;GetEvent(dwFlags, ppEvent));

// correct one
RETURN_IF_FAILED ( spQueue -&gt;GetEvent(dwFlags, ppEvent) );

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d1d4e1-ff6e-58c9-4bd4-a6b61f226211
* Version Independent ID: a145a894-826c-edd2-7321-0bcc573e6a93
* Content: [Frame Server Custom Media Source - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/frame-server-custom-media-source)
* Content Source: [windows-driver-docs-pr/stream/frame-server-custom-media-source.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/stream/frame-server-custom-media-source.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
Thanks, @persskog! The sample code has been updated with the correct pointer per your comment above.
