### ISSUE TITLE
No WDK support for Visual Studio 2017 Build Tools

### ISSUE THREAD

**Issue by AlexAltea** [MicrosoftDocs/windows-driver-docs#1042]
Not sure if this is the best place to ask for this feature.

After installing Visual Studio 2017 Build Tools for C++ and the latest WDK, I get the following error when attempting to build a driver:
> MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. [...]

Which is unsurprising, considering that the documentation mentions:

> The following editions of Visual Studio 2017 support driver development:
> * Download Visual Studio Community 2017
> * Download Visual Studio Professional 2017
> * Download Visual Studio Enterprise 2017

But this seems an unnecessary restriction, I've managed to use the "*WDK for Windows 10, version 1809*" with just the Build Tools by installing the WDK as usual, and then doing the following:
1. Downloading https://download.microsoft.com/download/7/D/D/7DD48DE6-8BDA-47C0-854A-539A800FAA90/wdk/Installers/dea2aa4848bad1eb522decedb8742d0c.cab 
2. Extracting *fil44a1ccbc56b9821e5022d37895cd1448* and opening it as *ZIP*.
3. Extracting *$VCTargets*, renaming it to *VCTargets*, and merging it with:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets`.

I understand this type of installation is really hacky, and I'd rather avoid it, so here's my question: Has official support for Visual Studio 2017 Build Tools been considered?

It's the preferred (and sometimes only) tool available in some CI systems (e.g. TravisCI), and EWDK and full Visual Studio installations are comparatively too oversized.

**Comment by tedhudek** [comment]
Looks like this got resolved at https://social.msdn.microsoft.com/Forums/en-US/efe5f9f8-c32d-4a25-87e2-abbe711dadbb/no-wdk-support-for-visual-studio-2017-build-tools?forum=wdk
