### ISSUE TITLE
FWPS_CONNECT_REQUEST0->localRedirectContext unaccessible at Windows 7

### ISSUE THREAD

**Issue by GreatFireWall** [MicrosoftDocs/windows-driver-docs#1044]
FWPS_CONNECT_REQUEST0-&gt;localRedirectContext unaccessible at Windows 7, 
How can I pass the original destination to my local proxy service (user-mode) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a3e4808-0c6b-8848-6270-8f5e8b810223
* Version Independent ID: d38592f5-3ca4-3d2a-20fd-c8cfd28b58d6
* Content: [Using Bind or Connect Redirection - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/using-bind-or-connect-redirection)
* Content Source: [windows-driver-docs-pr/network/using-bind-or-connect-redirection.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/using-bind-or-connect-redirection.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @GreatFireWall, sorry you're having an issue. According to the documentation on this page, this feature is supported in Windows 7 and later. In addition, the documentation on the [FWPS_CONNECT_REQUEST0](https://docs.microsoft.com/windows-hardware/drivers/ddi/content/fwpsk/ns-fwpsk-_fwps_connect_request0) page mentions that it is supported in Windows 7 and later. There is a note saying that the memory allocated for the **localRedirectContext** field is controlled by WFP in Windows 8 and later, but the field itself is supported in Windows 7. The only difference in Windows 7 is that the driver would need to free the memory when the flow/redirection terminates.

So, if you're experiencing an issue with accessing that field when developing for Windows 7, I'm sorry but we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation. I'd recommend asking your question in one of the following places where other driver developers and Microsoft engineers can be found:

- [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
- [NTDEV forum at OSR Online](https://community.osr.com/)

Again, thanks for reaching out. Best of luck with your issue.

**Comment by GreatFireWall** [comment]
> There is a note saying that the memory allocated for the localRedirectContext field is controlled by WFP in Windows 8 and later, but the field itself is supported in Windows 7. The only difference in Windows 7 is that the driver would need to free the memory when the flow/redirection terminates.

Sorry, I think I should not ask individual technical question here, 
But the definition of `FWPS_CONNECT_REQUEST0` in `fwpsk.h` is:
<pre>
typedef struct _FWPS_CONNECT_REQUEST0
{
   //
   // Read-Write fields on a writable copy of the structure.
   //
   /* IN OUT */ SOCKADDR_STORAGE localAddressAndPort;
   /* IN OUT */ SOCKADDR_STORAGE remoteAddressAndPort;
   /* OUT */ UINT64 portReservationToken;

   //
   // When redirecting a connection to localhost, the callout must supply
   // the PID of the process that will be accepting the redirected connection.
   //

   /* OUT */ DWORD localRedirectTargetPID;

   //
   // Modification History. (Read-Only)
   //
   struct _FWPS_CONNECT_REQUEST0* previousVersion;
   UINT64 modifierFilterId;
<b>#if (NTDDI_VERSION >= NTDDI_WIN8)
   //
   // Handle created using the FwpsRedirectHandleCreate0 function.
   //
   /* OUT */ HANDLE localRedirectHandle;

   //
   // Arbitrary callout supplied context allocated using the
   // ExAllocatePoolWithTag function.
   //
   /* OUT */ void* localRedirectContext;
   /* OUT */ SIZE_T localRedirectContextSize;
#endif // NTDDI_VERSION >= NTDDI_WIN8</b>
} FWPS_CONNECT_REQUEST0;
</pre>

So, how can I access `localRedirectContext` when my Target OS is Win7 😄

**Comment by duncanmacmichael** [comment]
You're correct; I had interpreted the note on the doc as saying "this field is supported, but is different in Windows 7 compared to Windows 8." *But*, that is indeed the definition in the header and my interpretation was not correct. That field is not available in Windows 7 at all.

So, to answer your question, on Windows 7 you cannot access that field, no. But, unfortunately I still don't have the answer to achieve the same functionality on Windows 7 and my recommendation for asking on those forums is the same. :) Thanks for pointing that out, though.
