### ISSUE TITLE
Missing Param 1 Value. 43000

### ISSUE THREAD

**Issue by Phleam** [MicrosoftDocs/windows-driver-docs#1046]
Dump Follows:

Microsoft (R) Windows Debugger Version 10.0.18239.1000 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [\\e324td000300\c$\Windows\Minidump\102218-29765-01.dmp]
Mini Kernel Dump File: Only registers and stack trace are available

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
Windows 10 Kernel Version 17134 MP (2 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 17134.1.amd64fre.rs4_release.180410-1804
Machine Name:
Kernel base = 0xfffff803`4ea13000 PsLoadedModuleList = 0xfffff803`4edc1290
Debug session time: Mon Oct 22 06:16:12.555 2018 (UTC - 5:00)
System Uptime: 0 days 0:06:07.384
Loading Kernel Symbols
...............................................................
................................................................
..........................................
Loading User Symbols
Loading unloaded module list
.......
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

Use !analyze -v to get detailed debugging information.

BugCheck 1A, {43000, 4, 0, 0}

Probably caused by : rdbss.sys ( rdbss!RxCommonCleanup+b01 )

Followup:     MachineOwner
---------

nt!KeBugCheckEx:
fffff803`4ebbc490 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:fffffd83`55fcd3d0=000000000000001a
1: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

MEMORY_MANAGEMENT (1a)
    # Any other values for parameter 1 must be individually examined.
Arguments:
Arg1: 0000000000043000, The subtype of the bugcheck.
Arg2: 0000000000000004
Arg3: 0000000000000000
Arg4: 0000000000000000

Debugging Details:
------------------

KEY_VALUES_STRING: 1

STACKHASH_ANALYSIS: 1

TIMELINE_ANALYSIS: 1

DUMP_CLASS: 1

DUMP_QUALIFIER: 400

BUILD_VERSION_STRING:  17134.1.amd64fre.rs4_release.180410-1804

SYSTEM_MANUFACTURER:  Dell Inc.

SYSTEM_PRODUCT_NAME:  OptiPlex 780                 

BIOS_VENDOR:  Dell Inc.

BIOS_VERSION:  A15

BIOS_DATE:  08/06/2013

BASEBOARD_MANUFACTURER:  Dell Inc.

BASEBOARD_PRODUCT:  0200DY

BASEBOARD_VERSION:  A02

DUMP_TYPE:  2

BUGCHECK_P1: 43000

BUGCHECK_P2: 4

BUGCHECK_P3: 0

BUGCHECK_P4: 0

BUGCHECK_STR:  0x1a_43000

CPU_COUNT: 2

CPU_MHZ: b6e

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 17

CPU_STEPPING: a

CPU_MICROCODE: 6,17,a,0 (F,M,S,R)  SIG: A0C'00000000 (cache) A0C'00000000 (init)

BLACKBOXBSD: 1 (!blackboxbsd)

CUSTOMER_CRASH_COUNT:  1

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

PROCESS_NAME:  svchost.exe

CURRENT_IRQL:  0

ANALYSIS_SESSION_HOST:  A001EDTECHTK

ANALYSIS_SESSION_TIME:  11-14-2018 15:28:54.0319

ANALYSIS_VERSION: 10.0.18239.1000 amd64fre

LAST_CONTROL_TRANSFER:  from fffff8034ec63544 to fffff8034ebbc490

STACK_TEXT:  
fffffd83`55fcd3c8 fffff803`4ec63544 : 00000000`0000001a 00000000`00043000 00000000`00000004 00000000`00000000 : nt!KeBugCheckEx
fffffd83`55fcd3d0 fffff800`ddcc9ba1 : fffffd83`55fcd638 ffffc88e`9b664380 ffffc88e`9b664300 00000000`00000000 : nt!MmForceSectionClosedEx+0x94
fffffd83`55fcd410 fffff800`ddc82d88 : ffffde0a`acadd5c0 ffffde0a`b07fa260 ffffde0a`afb59000 ffffde0a`b07fa201 : rdbss!RxCommonCleanup+0xb01
fffffd83`55fcd530 fffff800`ddcbd2b6 : 00000000`c0000016 fffffd83`55fc8000 fffffd83`55fce000 ffffde0a`b04f2ab8 : rdbss!RxFsdCommonDispatch+0x588
fffffd83`55fcd6c0 fffff800`ddff3267 : 00000000`00000000 fffff803`4ea4943e ffffde0a`afb59040 00000000`00000000 : rdbss!RxFsdDispatch+0x86
fffffd83`55fcd710 fffff803`4ea4def9 : ffffde0a`ad178d00 ffffde0a`b07fa260 ffffc88e`94e6e3f0 00000000`00000000 : mrxsmb!MRxSmbFsdDispatch+0xe7
fffffd83`55fcd750 fffff800`dcdbf539 : 00000000`00000001 fffff800`dcdbf2e9 ffffde0a`ad178db0 ffffde0a`aef8e828 : nt!IofCallDriver+0x59
fffffd83`55fcd790 fffff800`dcdbf085 : ffffc88e`94e6e3f0 fffff800`dcdb8000 fffff800`dcdb8000 ffffde0a`b07fa260 : mup!MupiCallUncProvider+0xa9
fffffd83`55fcd800 fffff800`dcdc2fa2 : 00000000`00000000 ffffde0a`aef8e820 ffffde0a`aea4cef0 ffffde0a`b07fa260 : mup!MupStateMachine+0x55
fffffd83`55fcd830 fffff803`4ea4def9 : ffffde0a`b04f29d0 00000000`00000000 ffffde0a`ad178d00 00000000`00000000 : mup!MupCleanup+0xb2
fffffd83`55fcd880 fffff800`dba07207 : fffffd83`55fcd950 fffff800`dba053b4 ffffde0a`b07fa260 00000000`00000012 : nt!IofCallDriver+0x59
fffffd83`55fcd8c0 fffff800`dba051c6 : fffffd83`55fcd950 ffffde0a`afaec580 ffffde0a`adca2df0 ffffde0a`afaec580 : FLTMGR!FltpLegacyProcessingAfterPreCallbacksCompleted+0x157
fffffd83`55fcd930 fffff803`4ea4def9 : ffffde0a`aea4cef0 fffff803`4ea4e1c5 ffffde0a`adca2df0 ffff2df8`52e20c18 : FLTMGR!FltpDispatch+0xb6
fffffd83`55fcd990 fffff803`4ef9ee1e : ffffde0a`aea4cef0 00000000`00000000 00000000`00000000 fffff803`4eef882f : nt!IofCallDriver+0x59
fffffd83`55fcd9d0 fffff803`4eef0752 : ffffde0a`aea4cec0 00000000`00000001 ffffc88e`00000000 00000000`00007fff : nt!IopCloseFile+0x15e
fffffd83`55fcda60 fffff803`4eef80dd : ffffc88e`965c8910 00007ff9`dfa831f0 00000098`257fd510 00007ff9`001401f4 : nt!ObCloseHandleTableEntry+0x212
fffffd83`55fcdba0 fffff803`4ebccb43 : ffffde0a`afb59040 00000234`71466060 ffffde0a`afb59040 fffffd83`55fcdc80 : nt!NtClose+0xcd
fffffd83`55fcdc00 00007ff9`f370a0d4 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x13
00000098`257fd488 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x00007ff9`f370a0d4

THREAD_SHA1_HASH_MOD_FUNC:  de9e67b9c09e428d54ed7d9c65f7f3f030e899f3

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  a5ae546a6ae5800661220057ef72f3b191f5bce7

THREAD_SHA1_HASH_MOD:  3787ece113a8f5ad14c92d4f8906ee01e829c85b

FOLLOWUP_IP: 
rdbss!RxCommonCleanup+b01
fffff800`ddcc9ba1 488bcb          mov     rcx,rbx

FAULT_INSTR_CODE:  ffcb8b48

SYMBOL_STACK_INDEX:  2

SYMBOL_NAME:  rdbss!RxCommonCleanup+b01

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: rdbss

IMAGE_NAME:  rdbss.sys

DEBUG_FLR_IMAGE_TIMESTAMP:  6917575b

IMAGE_VERSION:  10.0.17134.319

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  b01

FAILURE_BUCKET_ID:  0x1a_43000_rdbss!RxCommonCleanup

BUCKET_ID:  0x1a_43000_rdbss!RxCommonCleanup

PRIMARY_PROBLEM_CLASS:  0x1a_43000_rdbss!RxCommonCleanup

TARGET_TIME:  2018-10-22T11:16:12.000Z

OSBUILD:  17134

OSSERVICEPACK:  345

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  272

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt TerminalServer SingleUserTS

OS_LOCALE:  

USER_LCID:  0

OSBUILD_TIMESTAMP:  2018-09-19 23:40:30

BUILDDATESTAMP_STR:  180410-1804

BUILDLAB_STR:  rs4_release

BUILDOSVER_STR:  10.0.17134.1.amd64fre.rs4_release.180410-1804

ANALYSIS_SESSION_ELAPSED_TIME:  2088

ANALYSIS_SOURCE:  KM

FAILURE_ID_HASH_STRING:  km:0x1a_43000_rdbss!rxcommoncleanup

FAILURE_ID_HASH:  {5105d3d9-3b02-e3da-cb8f-408a3a6bb88c}

Followup:     MachineOwner
---------

**Comment by DOMARS** [comment]
@Phleam - Thanks for the input that we should add additional information on 43000 for Bug Check 0x1A. We use customer input like this as well as data on how often the bug checks occur to determine how we allocate our documentation team resources. As you may know we provide general developer guidance in topics such as https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/blue-screen-data.  We will use your input and other data to determine if we can provide additional information on this stop code that is broadly applicable. Again, thanks for the input, and good luck with your issue.
