### ISSUE TITLE
WDK Version 1809, download link is broken again

### ISSUE THREAD

**Issue by PascalTNL** [MicrosoftDocs/windows-driver-docs#1052]
I know there has been an issue with the link before early in October. However that issue has been closed and the download problem occurred in a different way.
This is the result I get when I click on the "Download WDK for Windows 10, version 1809" link.

![capture](https://user-images.githubusercontent.com/43749772/48609874-6dafe900-e984-11e8-89ea-8336b05a2003.PNG)

What is going on?

**Comment by EliotSeattle** [comment]
Hi @PascalTNL. When I click the link, the download begins as it's supposed to. This is on https://docs.microsoft.com/windows-hardware/drivers/download-the-wdk, and the URL for the download for the WDK  for Windows 10, version 1809 is https://go.microsoft.com/fwlink/?linkid=2026156.

**Comment by PascalTNL** [comment]
Hello @EliotSeattle I already used that. I tried different devices and different browsers. But all of them didn't seem to work.

**Comment by EliotSeattle** [comment]
The link still seems to work on a number of different machines. Perhaps remove all kits, delete the folders, restart, and try again?
I'm sorry I can't be of more help, as I cannot reproduce your issue.
