### ISSUE TITLE
Can't reference the wpprecorder.h in a umdf project.

### ISSUE THREAD

**Issue by Jensensss** [MicrosoftDocs/windows-driver-docs#1067]
There is a DeviceMFT project i worked on, but can't reference the wpprecorder.h when i try to enable the IFR.
And that will get wired errors if add the DDK_INC_PATH in the "Additional Include Directories" by manual.
The error: "E0020 identifier "STATUS_BUFFER_OVERFLOW" is undefined in ntstrsafe.h".

anyone can kindly help on it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a71e4773-79fc-7733-464d-bfdca8823576
* Version Independent ID: a7cad97d-9b2e-4bb3-6f55-30ca5434505b
* Content: [Inflight Trace Recorder (IFR) for logging traces - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/using-wpp-recorder)
* Content Source: [windows-driver-docs-pr/devtest/using-wpp-recorder.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/using-wpp-recorder.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @Jensensss.

Unfortunately, we don’t have the  resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft  engineers can be found. The communities there are quite responsive.
[Windows Hardware WDK and driver development forum](https://social.msdn.microsoft.com/Forums/windowshardware/en-US/home?forum=wdk)
[OSR NTDEV forum](http://www.osronline.com/cf.cfm?PageURL=showlists.cfm?list=NTDEV)
All the best.
@EliotSeattle
