### ISSUE TITLE
can't generate PropPageExt.dll,

### ISSUE THREAD

**Issue by airwolf2026** [MicrosoftDocs/windows-driver-docs#1074]
in control panel can't see the WDM device node missing this dll?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9226c2e0-2c63-788b-5164-4856f66cc12b
* Version Independent ID: ba393947-45d1-935d-aba2-b776e163915b
* Content: [Debug Drivers - Step-by-Step Lab (Sysvad Kernel Mode) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers--kernel-mode-)
* Content Source: [windows-driver-docs-pr/debugger/debug-universal-drivers--kernel-mode-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debug-universal-drivers--kernel-mode-.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@airwolf2026 - I removed references to the PropPageExt, so closing this issue. Thanks for your interest in our docs and posting this issue.
