### ISSUE TITLE
how to get firmware.inf file 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1082]
all Oem manufacturers  will give.exe file or  .bios  or .firmware  , so that users could not be able to get .inf file and  cat file 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 373b65f8-f65c-e137-97c8-7a46d3436127
* Version Independent ID: 7ca44202-4f13-4996-dea0-19ae09bb3a31
* Content: [Authoring an update driver package - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/authoring-an-update-driver-package)
* Content Source: [windows-driver-docs-pr/bringup/authoring-an-update-driver-package.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/authoring-an-update-driver-package.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. 

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
