### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1084]
Today i learnt  abbrevations  in this article , thanks to the AUTHOR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c409363e-8fcb-9c0b-07f8-72ff1620385c
* Version Independent ID: 58241802-551c-edb0-f562-6aa2a7f34507
* Content: [Firmware Windows Engineering Guide (WEG) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/firmware-weg)
* Content Source: [windows-driver-docs-pr/bringup/firmware-weg.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/firmware-weg.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks @RAJU2529 for providing feedback that the Firmware WEG terminology guide was useful.
