### ISSUE TITLE
Where i can get Hardware Security Test Interface 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1085]
How do i test  my hardware as in laptop   for  security  purpose , i am end user 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c9d886-f326-ddca-309d-fde727ab0289
* Version Independent ID: 5be6b02c-bff3-5af3-5afa-ea92890afd30
* Content: [Hardware Security Test Interface (HSTI) 1.1a - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/hardware-security-test-interface-1-1a)
* Content Source: [windows-driver-docs-pr/bringup/hardware-security-test-interface-1-1a.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/hardware-security-test-interface-1-1a.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. 

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
