### ISSUE TITLE
Thanks for configuration information

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1087]
I am using Asus vivobook 15  R542UQ-DM153 with bios version X542UQ .305. Currently  enabled  secure boot without CSM, If  i enable  CSM means, Fast boot will be automatically  disabled in bios.
Thanks to the authors, Great work 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3104beb2-e766-f5e7-49f7-a6488592fb2e
* Version Independent ID: a016fbce-2bc7-c1bb-3035-053981676cac
* Content: [Switch from Legacy MBR disk to GPT disk with Windows 10 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/switch-from-legacy-mbr-disk-to-gpt-disk-with-windows-10)
* Content Source: [windows-driver-docs-pr/bringup/switch-from-legacy-mbr-disk-to-gpt-disk-with-windows-10.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/switch-from-legacy-mbr-disk-to-gpt-disk-with-windows-10.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@RAJU2529, thanks for letting us know that you found the configuration and upgrade path information to be correct and helpful.
