### ISSUE TITLE
Whats the minimum   SMBIOS version is  needed  to upgarded 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1088]
For successful upgrading to windows 10,  whats the minimum version of SMBIOS  is  needed  under windows 7  laptops.

Thanking you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762208e7-cc22-8e7b-b9d8-08448901c420
* Version Independent ID: 79433d5a-d130-a779-7bd2-063c216a71ad
* Content: [Configure system firmware for Windows 7 and enable for Windows 10 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/configure-system-firmware-for-windows-7-and-later-update-for-windows-10)
* Content Source: [windows-driver-docs-pr/bringup/configure-system-firmware-for-windows-7-and-later-update-for-windows-10.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/configure-system-firmware-for-windows-7-and-later-update-for-windows-10.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. 

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
