### ISSUE TITLE
some wrong command

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1089]
after selecting disk  or volume,  if  we enter  convert  GPT command means ,  
then volume data  will be deleted, so we cant boot windows further without reinstallation of windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de956993-5900-0237-abad-bbe394760319
* Version Independent ID: 4b932cfb-56aa-f71c-3993-c1f98989159a
* Content: [How to convert an installed x64 Windows 7 system - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/how-to-convert-an-installed-x64-windows-7)
* Content Source: [windows-driver-docs-pr/bringup/how-to-convert-an-installed-x64-windows-7.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/how-to-convert-an-installed-x64-windows-7.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. 

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
