### ISSUE TITLE
Thanks 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1090]
This  tool mbr2gpt.exe is much useful  when migrating existing windows  mbr  to gpt .

Thanks  a lot 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d00fbbc-244e-bd9b-c1d2-4dbe90c9c697
* Version Independent ID: 7430b900-ed6c-20c7-3c00-c70326bbe14d
* Content: [New method - Windows 10, version 1703 and later - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/new-method--windows-10--version-1703-and-later)
* Content Source: [windows-driver-docs-pr/bringup/new-method--windows-10--version-1703-and-later.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/new-method--windows-10--version-1703-and-later.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by EliotSeattle** [comment]
Thank you for the feedback, @RAJU2529. I will have the area writer, @barrygolden, pass this on to the product team!
