### ISSUE TITLE
Really technical article

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1091]
First of all thanks to author for details  , one more doubt i  have.

How to know  which type of architecture  32bit or 64bit UEFI is adopted on the motherboard  laptop ,  as a end user  how  to find , i have asus  vivobook 15 R542UQ-DM153 with bios X542UQ.305

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e9767bc-0b6c-aa92-3c03-8e4ac1f5af67
* Version Independent ID: 0702b3ac-b69a-bb1b-80b0-d79e7e94cdd0
* Content: [Firmware WEG FAQ - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/frequently-asked-questions)
* Content Source: [windows-driver-docs-pr/bringup/frequently-asked-questions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/frequently-asked-questions.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
