### ISSUE TITLE
someMore  firmware failure reasons 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1092]
1.firmware is incompatible with existing motherboard bios model.
2.existing bios firmware has been tempered.
3.existing bios firmware has been overclocked 
4.entering BIos has been protected by password 
5. Battery not charging 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef36eff5-f40d-7c67-ede1-479da8b6d54b
* Version Independent ID: 3aba5978-2f7b-529c-3598-61310997ea7b
* Content: [Seamless crisis prevention and recovery - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/seamless-crisis-prevention-and-recovery)
* Content Source: [windows-driver-docs-pr/bringup/seamless-crisis-prevention-and-recovery.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/seamless-crisis-prevention-and-recovery.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for your thoughtful comments @RAJU2529!

You have outlined several additional areas that could impact UEFI updates on a device.
