### ISSUE TITLE
Thanks for information 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1093]
Great article. I think this particular article is only for windows 10 smartphone devices.

I want to know, whether the user can add or edit registry keys in smartphone also 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1480d49c-988c-d1b3-232b-f9cb98350576
* Version Independent ID: e1ec3eb7-2f33-a55f-6426-8f80f4fcc5b2
* Content: [Battery charging in the boot environment for Windows 10 Mobile - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/battery-charging-in-the-boot-environment)
* Content Source: [windows-driver-docs-pr/bringup/battery-charging-in-the-boot-environment.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/battery-charging-in-the-boot-environment.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for your interest in Windows 10 Mobile. This product is no longer supported.
