### ISSUE TITLE
Examples mis-marked

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1100]
Why are the examples marked as C++? INF files have nothing to do with C++. They should be marked as "INF"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba708169-9e8f-f6fc-c0c8-8ba44874d96a
* Version Independent ID: b9304f44-194a-a275-38f4-9d3d4b3d32cb
* Content: [INF SignatureAttributes Section - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-signatureattributes-section)
* Content Source: [windows-driver-docs-pr/install/inf-signatureattributes-section.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-signatureattributes-section.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks, see resolution in #1099
