### ISSUE TITLE
Brightness Control Override does not work on a Mobile platform.

### ISSUE THREAD

**Issue by msgithubaccount** [MicrosoftDocs/windows-driver-docs#1110]
Brightness Control Override does not work on a mobile Intel based platform using this guide.
Test configuration as per requirements in this guide:
- ACPI firmware based and driver based brightness control is implemented and works without issues on the integrated display
- Modified monitor inf file is installed and "BrightnessControl" key is set to "1"
- External display is connected via HDMI
- External display is verified to support standard DDC based brightness control
- Windows versions tested = 1803 and 1809

Outcome:
- Brightness override does not take place = Brightness target remains set to the integrated display
- "Get-Ciminstance -Namespace root/WMI -ClassName WmiMonitorBrightness" confirms that brightness control is active and target is on the integrated display only

Please post in comments details of configuration used to verify operation of this function.
Which extra settings are required on Intel driver side?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44bb916a-763a-caf2-a5b1-51c70b009b74
* Version Independent ID: a2ee9c1e-ef87-4916-f244-2be8d541c323
* Content: [Supporting Brightness Controls For External Display Connectors - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/supporting-brightness-controls-for-external-display-connectors)
* Content Source: [windows-driver-docs-pr/display/supporting-brightness-controls-for-external-display-connectors.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/supporting-brightness-controls-for-external-display-connectors.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
Fixed with PR #1095
