### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by topcoder-mc** [MicrosoftDocs/windows-driver-docs#1111]
That was summary and useful thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba088928-98eb-72b4-45ad-e6da039e671c
* Version Independent ID: 26ffae7e-c9f7-e6a6-f661-cd58a7be7a04
* Content: [Introduction to WDM - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-wdm)
* Content Source: [windows-driver-docs-pr/kernel/introduction-to-wdm.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/introduction-to-wdm.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Thanks, @topcoder-mc!
We appreciate the comment and the praise.
Happy coding!
@EliotSeattle on behalf of @tedhudek
