### ISSUE TITLE
Missing supported NFC_BARCODE protocol

### ISSUE THREAD

**Issue by siddaram-khed** [MicrosoftDocs/windows-driver-docs#1112]
NFC also supports thinflim kovio tags NFC_BARCODE protocol, it looks like documentation is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 550205dd-4cd2-2f23-9b46-8f633ca123b2
* Version Independent ID: ae9de6b4-ed8a-2cc0-2fff-5df4d19f6afe
* Content: [NFP protocol support - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/nfc/protocol-support)
* Content Source: [windows-driver-docs-pr/nfc/protocol-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/nfc/protocol-support.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thinfilm is an NFC RF protocol. The RF protocols supported by the NFC CX driver are documented on [NFC Class Extensions](https://docs.microsoft.com/windows-hardware/drivers/nfc/nfc-class-extension-), which already mentions NFC Barcode (Kovio).
