### ISSUE TITLE
NBL Chain Example 

### ISSUE THREAD

**Issue by NoelStephens** [MicrosoftDocs/windows-driver-docs#1114]
It would be very helpful if someone could provide a working example of sending chained NBLs, as there seems to be scattered bread crumbs of information pertaining to this.  Based on the information provided, I am able to send out chained NBLs but end up with a strange "STATUS_FWP_TCPIP_NOT_READY" response after successfully sending an NBL Chain.  This includes releasing memory (context, nbls, mdls, etc).   So, from the various pages (including this one) that briefly discuss sending a Chained set of NBLS, I can get all the way up to a strange TCPIP error.  I call this "strange" because I am sending from the NATIVE MAC frame layer, and outbound sends from this layer *should* (??) only pass through the filter platform's LWF NDIS region and not be sent back up to the top of the TCPIP stack (is this right?).  Some form (doesn't even have to compile) of page that generally discusses this topic with things like how to manually craft an NBL chain properly (is there more than just using pNBL-&gt;next) and other such recommendations would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec28b87-7678-26e4-f9d6-a98d101c7515
* Version Independent ID: 17522f36-5eba-763c-f110-bbc1d7987a31
* Content: [Using Layer 2 Filtering - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/using-layer-2-filtering)
* Content Source: [windows-driver-docs-pr/network/using-layer-2-filtering.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/using-layer-2-filtering.md)
* Product: **windows-hardware**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @NoelStephens, since I haven't heard back yet I'll go ahead and close this issue. Hopefully my answer above helped clarify things. If you need anything else, please feel free to either reopen this issue or open a new one. Thanks!
