### ISSUE TITLE
How to verify driver , that not  built by me 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1116]
Recently i  received UWD graphics  driver  suite , i have already installed Visual studio community edition uptodate , now how to  verify that driver belongs  to  UWD 

please  add  command line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58045b53-c3f3-acc3-3432-d31d78bfb3c1
* Version Independent ID: 0e67ba20-f4e1-dbaf-97a6-cd7ce8565e28
* Content: [Validating Universal Windows drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/validating-universal-drivers)
* Content Source: [windows-driver-docs-pr/develop/validating-universal-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/validating-universal-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @RAJU2529 - in the properties for the driver project in Visual Studio, you can see if the driver is universal or not by navigating to **Driver Settings->General->Target Platform**.  Hope this helps!
