### ISSUE TITLE
Registry key?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1121]
Can I find using registry key, if possible means, could you tell, root of the key is located 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eea1fbb-7f7d-d32d-da26-07f6499b3336
* Version Independent ID: 3fed902a-fb51-cd76-29d1-3fdaa97d847f
* Content: [How to Identify the Windows Version in ACPI by Using _OSI - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/acpi/winacpi-osi)
* Content Source: [windows-driver-docs-pr/acpi/winacpi-osi.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/acpi/winacpi-osi.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
