### ISSUE TITLE
Hot links in downloaded PDF

### ISSUE THREAD

**Issue by mfstanton** [MicrosoftDocs/windows-driver-docs#1122]
The Hot links in the index of the  PDF I just downloaded reference the Web copy and not the downloaded copy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0bbd369-01db-92f6-e190-d34e5f824418
* Version Independent ID: 130f38ba-dab1-ebc9-9196-519c75076e41
* Content: [Introduction - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/)
* Content Source: [windows-driver-docs-pr/storage/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/index.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by EliotSeattle** [comment]
Hi @mfstanton.
This is by design. The pdf is a snapshot of the web content and contains the same links that the web version does. Because the content is updated frequently, we grab the latest bits from the web rather than trying to update offline versions of >40,000 topics.
