### ISSUE TITLE
Missing Code Reference for Error 0x0000001df

### ISSUE THREAD

**Issue by daevem** [MicrosoftDocs/windows-driver-docs#1123]
I ran into a blue screen error while waking up my pc from sleep mode. 
The error code which showed up was 0x000001df, however I cannot seem to find any reference to it anywere, not even on the  [__Bug Check Code Reference__](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-code-reference2) page.
Could you please provide me and the docs with some references to it?

**Comment by DOMARS** [comment]
@daevem - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

It is possible that the bugcheck code is being called by another software vendor, if there is a specific code module mentioned you might investigate that. You could also look in the event logs to see if anything is logged there, right before the failure occurs.

You may have success posting your question in the forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

Again, thanks for reaching out. Best of luck with this issue.
