### ISSUE TITLE
wrong example commands 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1129]
commands should be like those below

pwrtest.exe /monitor /t:3
or 
pwrtest.exe /monitor /t:30 /lf:C:\PWRtestlog  

Log output file correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eae1a1bf-a214-f189-7a92-21fe59f8b0bd
* Version Independent ID: 4e85dd2c-5464-28bf-b9c1-5d40a9e43d11
* Content: [PwrTest Monitor Scenario - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/pwrtest-monitor-scenario)
* Content Source: [windows-driver-docs-pr/devtest/pwrtest-monitor-scenario.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pwrtest-monitor-scenario.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Got them fixed in the private branch. Should show up in master later today. Thanks!
