### ISSUE TITLE
Drivers Scanner For System

### ISSUE THREAD

**Issue by AlexluthorD** [MicrosoftDocs/windows-driver-docs#1133]
how to create computer drivers scanner which can scan the complete system and provide the information regarding system drivers using vb.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bd0eaa7-6ba9-a326-97d3-24c33315426d
* Version Independent ID: 00cbdbfe-1115-ae93-29c8-50def85c6da5
* Content: [Creating a New Software Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/creating-a-new-software-driver)
* Content Source: [windows-driver-docs-pr/develop/creating-a-new-software-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/creating-a-new-software-driver.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
* [OSR's ntdev List](http://www.osronline.com/showlists.cfm?list=ntdev)

Again, thanks for reaching out. Best of luck with this issue.
