### ISSUE TITLE
commitStatus field of Submission resource is undocumented

### ISSUE THREAD

**Issue by winter3angle** [MicrosoftDocs/windows-driver-docs#1134]
Subj, there is no documentation on possible values for commitStatus enumeration.
For now I know that there are at least `commitPending` and `commitReceived` members exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6788ab0-e8c3-b5c2-c127-6528e4b4231d
* Version Independent ID: 4a618589-7215-89cb-8bc1-330ba9131ddd
* Content: [Get product data - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-product-data#submission-resource)
* Content Source: [windows-driver-docs-pr/dashboard/get-product-data.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-product-data.md)
* Product: **windows-hardware**
* GitHub Login: @balapv
* Microsoft Alias: **balapv**

**Comment by winter3angle** [comment]
Also `commitStarted`, it's mentioned on the page on product submission committing

**Comment by tedhudek** [comment]
Related to #839

**Comment by tedhudek** [comment]
Thanks for the feedback and apologies for the delay.  I've updated these values in 7f72cade9.
