### ISSUE TITLE
KMDF Package

### ISSUE THREAD

**Issue by MarioFarrugia** [MicrosoftDocs/windows-driver-docs#1135]
Where did the KMDFHelloWorld Package project come from (after the Driver.c was added)? 
There is a similar issue in the previous section (https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-umdf-driver-based-on-a-template) where if one is working with a VM, one is linked to another tutorial to download the driver samples. But the example driver sample (Echo... https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-#section-3-download-and-build-the-kmdf-universal-echo-driver) contains 3 projects (including an exe) which is not mentioned in these tutorials. 
thanks
M

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ec6622b-e8a9-0ae3-aee4-b233559a6c58
* Version Independent ID: 4c4ed5a3-117f-7f6f-45e1-63ba67c08f8e
* Content: [Write a universal Hello World driver (KMDF) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-very-small-kmdf--driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-very-small-kmdf--driver.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by tedhudek** [comment]
Thanks @MarioFarrugia I repro this behavior.  I made some updates to https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver that will be live soon, basically just updated the screen shot and removed reference to the package project. Was this issue preventing you from doing something, or were you just reporting the UI mismatch?
