### ISSUE TITLE
Related topics : Device Power Management Reference

### ISSUE THREAD

**Issue by pankajbharti** [MicrosoftDocs/windows-driver-docs#1149]
The link is broken. It takes you to WDK general reference. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7b988d-6293-b11a-c94b-ec4d5d1c442f
* Version Independent ID: 61095a73-3241-1208-3c8f-0090b9d3775c
* Content: [Component-Level Power Management - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/component-level-power-management)
* Content Source: [windows-driver-docs-pr/kernel/component-level-power-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/component-level-power-management.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks to @EliotSeattle for doing this one.

@pankajbharti the link from https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/component-level-power-management#related-topics now has a new target.

Thanks for the feedback, and happy holidays.
