### ISSUE TITLE
Missing entry for parameter 1 = 0000000000009696

### ISSUE THREAD

**Issue by cf5146** [MicrosoftDocs/windows-driver-docs#1151]
Microsoft (R) Windows Debugger Version 10.0.18272.1001 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\WINDOWS\MEMORY.DMP]
Kernel Bitmap Dump File: Kernel address space is available, User address space may not be available.

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*d:\symbols*https://msdl.microsoft.com/download/symbols
Symbol search path is: srv*d:\symbols*https://msdl.microsoft.com/download/symbols
Executable search path is: 
Windows 10 Kernel Version 17763 MP (8 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 17763.1.amd64fre.rs5_release.180914-1434
Machine Name:
Kernel base = 0xfffff802`53800000 PsLoadedModuleList = 0xfffff802`53c1f990
Debug session time: Tue Dec 18 10:39:02.334 2018 (UTC + 8:00)
System Uptime: 3 days 23:43:07.653
Loading Kernel Symbols
...............................................................
................................................................
................................................................
..........................
Loading User Symbols
PEB is paged out (Peb.Ldr = 00000014`68562018).  Type ".hh dbgerr001" for details
Loading unloaded module list
..................................................
For analysis of this file, run !analyze -v
nt!KeBugCheckEx:
fffff802`539b1040 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:fffff306`c582e1f0=000000000000001a
1: kd&gt; !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

MEMORY_MANAGEMENT (1a)
    # Any other values for parameter 1 must be individually examined.
Arguments:
Arg1: 0000000000009696, The subtype of the bugcheck.
Arg2: ffffbc000544fbf0
Arg3: 0000000000000000
Arg4: 0000000000000000

Debugging Details:
------------------

KEY_VALUES_STRING: 1

STACKHASH_ANALYSIS: 1

TIMELINE_ANALYSIS: 1

DUMP_CLASS: 1

DUMP_QUALIFIER: 401

BUILD_VERSION_STRING:  17763.1.amd64fre.rs5_release.180914-1434

SYSTEM_MANUFACTURER:  Dell Inc.

SYSTEM_PRODUCT_NAME:  Inspiron 7570

SYSTEM_SKU:  07EA

BIOS_VENDOR:  Dell Inc.

BIOS_VERSION:  1.11.0

BIOS_DATE:  07/19/2018

BASEBOARD_MANUFACTURER:  Dell Inc.

BASEBOARD_PRODUCT:        

BASEBOARD_VERSION:     

DUMP_TYPE:  1

BUGCHECK_P1: 9696

BUGCHECK_P2: ffffbc000544fbf0

BUGCHECK_P3: 0

BUGCHECK_P4: 0

BUGCHECK_STR:  0x1a_9696

CPU_COUNT: 8

CPU_MHZ: 7c8

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 8e

CPU_STEPPING: a

CPU_MICROCODE: 6,8e,a,0 (F,M,S,R)  SIG: 96'00000000 (cache) 96'00000000 (init)

BLACKBOXBSD: 1 (!blackboxbsd)

BLACKBOXPNP: 1 (!blackboxpnp)

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

PROCESS_NAME:  chrome.exe

CURRENT_IRQL:  2

ANALYSIS_SESSION_HOST:  TPEA90068596

ANALYSIS_SESSION_TIME:  12-18-2018 10:41:31.0443

ANALYSIS_VERSION: 10.0.18272.1001 amd64fre

LAST_CONTROL_TRANSFER:  from fffff802539db458 to fffff802539b1040

STACK_TEXT:  
fffff306`c582e1e8 fffff802`539db458 : 00000000`0000001a 00000000`00009696 ffffbc00`0544fbf0 00000000`00000000 : nt!KeBugCheckEx
fffff306`c582e1f0 fffff802`5381045b : 00000000`00000000 00000000`00000001 ffffbc00`0544fbf0 00000000`00000000 : nt!MiGetTopLevelPfn+0x1b9e18
fffff306`c582e280 fffff802`53812989 : 00000000`00000088 00000000`00000001 ffffff00`e63e3f80 fffff306`c582e460 : nt!MiLockStealUserVm+0x8f
fffff306`c582e330 fffff802`538982ab : 00000000`00000000 fffff306`c582e6d0 00000000`00000001 00000000`00000000 : nt!MiStealPage+0x195
fffff306`c582e5f0 fffff802`53897efd : 00000000`40020000 00000000`ffffffff ffff8ffd`00000000 fffff802`00000001 : nt!MiTradePage+0x2ab
fffff306`c582e6b0 fffff802`538976ce : 00000000`001c1a95 fffff306`c582e850 00000000`00000000 00000000`00000001 : nt!MiClaimPhysicalRun+0xcd
fffff306`c582e750 fffff802`53ac6211 : ffffbc00`00fcabf0 fffff306`c582e9f0 fffff802`53c41940 00000000`001c1a95 : nt!MiFindContiguousPages+0x33e
fffff306`c582e8f0 fffff802`539e20da : 00000120`00000000 00000000`00000000 fffff306`00000001 00000000`00000000 : nt!MiIdealClusterPage+0x691
fffff306`c582eb40 fffff802`5382efde : fffff306`c582ed70 ffffff00`ad015128 ffffff7f`bfdfe000 00002000`54395880 : nt!MiHandleTransitionFault+0x1b279a
fffff306`c582ebb0 fffff802`538385bb : 00002000`00000000 fffff306`c582efa0 00000000`00000000 00000000`00000002 : nt!MiResolveTransitionFault+0x11e
fffff306`c582ec70 fffff802`538367fa : 00000000`00000004 00000000`00000000 00000000`c0000016 ffff9109`7c315080 : nt!MiDispatchFault+0x56b
fffff306`c582edd0 fffff802`53907790 : ffff9109`7c315580 00001800`000001fe ffffff7f`bfdfeff0 00000000`00000000 : nt!MmAccessFault+0x15a
fffff306`c582ef70 fffff802`53834949 : 00000000`00000000 0000015a`02a03000 ffffff00`ad015018 fffff802`6d2b0f61 : nt!MiFaultInProbeAddress+0xa4
fffff306`c582f020 fffff802`53833c74 : 80000001`4b771811 00000000`00000000 fffff306`c582f190 0000015a`02a03000 : nt!MiLockPageLeafPageTable+0x279
fffff306`c582f090 fffff802`53832039 : 00000000`000000a3 ffff9109`75ec9de0 ffffa881`c3bb4320 00000000`00000000 : nt!MiProbeAndLockPages+0x154
fffff306`c582f1e0 fffff802`56924593 : 00000000`00610000 ffffa881`c522f1e8 00000000`00000000 ffffa881`ccfb8160 : nt!MmProbeAndLockPages+0x29
fffff306`c582f210 fffff802`56924469 : ffffa881`ccfb8160 ffffa881`ccfb8160 00000000`00000f00 0000015a`02960000 : dxgmms2!VIDMM_MDL_RANGE::Lock+0x67
fffff306`c582f270 fffff802`569214bb : ffffa881`ea230590 ffffa881`e0845c90 fffff306`00000000 ffff9109`75ec9de0 : dxgmms2!VIDMM_RECYCLE_HEAP_PHYSICAL_VIEW::LockRange+0xfd
fffff306`c582f2f0 fffff802`569213a4 : ffffa882`091ff5f0 00000000`00610000 00000000`00000000 ffff9109`75e92000 : dxgmms2!VIDMM_RECYCLE_RANGE::Lock+0x7b
fffff306`c582f350 fffff802`569212eb : ffffa881`c81f18d0 ffffa881`e0845c90 00000000`00000000 00000000`00610000 : dxgmms2!VIDMM_RECYCLE_MULTIRANGE::Lock+0x78
fffff306`c582f3b0 fffff802`5692729e : ffffa881`c81f18d0 ffffa881`e0845c00 00000000`00000000 00000000`00000000 : dxgmms2!VIDMM_RECYCLE_HEAP_MGR::ProbeAndLockAllocation+0x7b
fffff306`c582f430 fffff802`56927085 : ffffa881`e0845c00 ffff9109`75ec9de0 00000000`00000000 00000000`00000001 : dxgmms2!VIDMM_GLOBAL::ProbeAndLockAllocation+0x56
fffff306`c582f480 fffff802`56928c1a : ffffa881`e0845c90 00000000`00000000 ffffa881`e0845c90 00000000`00000000 : dxgmms2!VIDMM_SEGMENT::LockAllocationBackingStore+0xb1
fffff306`c582f540 fffff802`5692b60d : ffff9109`84c62950 ffffa881`e0845c90 00000000`00000000 ffff9109`75e92000 : dxgmms2!VIDMM_SYSMEM_SEGMENT::CommitResource+0x7a
fffff306`c582f580 fffff802`56935107 : ffff8001`00000000 fffff306`c582f790 ffff9109`00000000 fffff306`c582f790 : dxgmms2!VIDMM_GLOBAL::PageInOneAllocation+0x1cd
fffff306`c582f690 fffff802`56943b64 : 00000000`00000001 00000000`00989680 fffff306`c582f9f0 00000000`00000001 : dxgmms2!VIDMM_GLOBAL::ProcessDeferredCommand+0x837
fffff306`c582f8f0 fffff802`56943219 : ffffa881`ade38250 00000000`00000001 ffffa881`ade38200 00000000`00000000 : dxgmms2!VIDMM_WORKER_THREAD::Run+0x934
fffff306`c582fae0 fffff802`539216c5 : ffff9109`75e3a680 fffff802`56943210 ffffa881`ade38250 000025ed`bd9bbfff : dxgmms2!VidMmWorkerThreadProc+0x9
fffff306`c582fb10 fffff802`539b849c : ffff8001`e97a5180 ffff9109`75e3a680 fffff802`53921670 00003233`72657672 : nt!PspSystemThreadStartup+0x55
fffff306`c582fb60 00000000`00000000 : fffff306`c5830000 fffff306`c5829000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x1c

THREAD_SHA1_HASH_MOD_FUNC:  16d5ad216684ba7dfe394b01878fd080adf43264

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  efcfe2dd30aa34b5b557903b3b11794357698ca0

THREAD_SHA1_HASH_MOD:  0023ef3a4972afff8204e173eefdfa8c4d8e72c5

FOLLOWUP_IP: 
dxgmms2!VIDMM_MDL_RANGE::Lock+67
fffff802`56924593 0f1f440000      nop     dword ptr [rax+rax]

FAULT_INSTR_CODE:  441f0f

SYMBOL_STACK_INDEX:  10

SYMBOL_NAME:  dxgmms2!VIDMM_MDL_RANGE::Lock+67

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: dxgmms2

IMAGE_NAME:  dxgmms2.sys

DEBUG_FLR_IMAGE_TIMESTAMP:  0

IMAGE_VERSION:  10.0.17763.55

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  67

FAILURE_BUCKET_ID:  0x1a_9696_dxgmms2!VIDMM_MDL_RANGE::Lock

BUCKET_ID:  0x1a_9696_dxgmms2!VIDMM_MDL_RANGE::Lock

PRIMARY_PROBLEM_CLASS:  0x1a_9696_dxgmms2!VIDMM_MDL_RANGE::Lock

TARGET_TIME:  2018-12-18T02:39:02.000Z

OSBUILD:  17763

OSSERVICEPACK:  0

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  272

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt TerminalServer SingleUserTS

OS_LOCALE:  

USER_LCID:  0

OSBUILD_TIMESTAMP:  2003-06-14 13:03:37

BUILDDATESTAMP_STR:  180914-1434

BUILDLAB_STR:  rs5_release

BUILDOSVER_STR:  10.0.17763.1.amd64fre.rs5_release.180914-1434

ANALYSIS_SESSION_ELAPSED_TIME:  120a

ANALYSIS_SOURCE:  KM

FAILURE_ID_HASH_STRING:  km:0x1a_9696_dxgmms2!vidmm_mdl_range::lock

FAILURE_ID_HASH:  {9554787c-3c01-bbb7-fe83-420620b1e367}

Followup:     MachineOwner
---------

1: kd&gt; lmvm dxgmms2
Browse full module list
start             end                 module name
fffff802`568c0000 fffff802`56998000   dxgmms2    (pdb symbols)          d:\symbols\dxgmms2.pdb\0F49BFE4A8F5A7ED68B2EE3ABA831B181\dxgmms2.pdb
    Loaded symbol image file: dxgmms2.sys
    Image path: \SystemRoot\System32\drivers\dxgmms2.sys
    Image name: dxgmms2.sys
    Browse all global symbols  functions  data
    Image was built with /Brepro flag.
    Timestamp:        DE16C166 (This is a reproducible build file hash, not a timestamp)
    CheckSum:         000E1F5B
    ImageSize:        000D8000
    File version:     10.0.17763.55
    Product version:  10.0.17763.55
    File flags:       0 (Mask 3F)
    File OS:          40004 NT Win32
    File type:        3.7 Driver
    File date:        00000000.00000000
    Translations:     0409.04b0
    Information from resource tables:
        CompanyName:      Microsoft Corporation
        ProductName:      Microsoft® Windows® Operating System
        InternalName:     dxgmms2.sys
        OriginalFilename: dxgmms2.sys
        ProductVersion:   10.0.17763.55
        FileVersion:      10.0.17763.55 (WinBuild.160101.0800)
        FileDescription:  DirectX Graphics MMS
        LegalCopyright:   © Microsoft Corporation. All rights reserved.
1: kd&gt; !thread ffffbc000544fbf0
ffffbc000544fbf0 is not a thread object, interpreting as stack value...
TYPE mismatch for thread object at ffffbc000544fbf0
1: kd&gt; !address ffffbc000544fbf0
Mapping user range ...
Mapping system range ...
Mapping non addressable range ...
Mapping page tables...
Mapping hyperspace...
Mapping HAL reserved range...
Mapping User Probe Area...
Mapping system shared page...
Mapping system cache working set...
Mapping loader mappings...
Mapping system PTEs...
Mapping system paged pool...
Mapping session space...
Mapping dynamic system space...
Mapping PFN database...
Mapping non paged pool...
Mapping VAD regions...
Mapping module regions...
Mapping process, thread, and stack regions...
Mapping system cache regions...

Usage:                  
Base Address:           ffffbc00`00000000
End Address:            ffffbc00`07400000
Region Size:            00000000`07400000
VA Type:                PFNDatabase

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de955911-dfbf-33b3-778a-767a5a578a0d
* Version Independent ID: 23fb5cbd-5f7d-f7ca-1622-5885020966c2
* Content: [Bug Check 0x1A MEMORY_MANAGEMENT - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x1a--memory-management)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@cf5146 - Thanks for this issue. Because we have not documented information on this parameter, I would need to check with the dev team to be able to do that. We use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, it is likely that we will only be able to do this work for a small sub set of all of the possible stop codes.
Right now I'm working on the new stop codes that we have not documented at all.
Thank you for your interest in improving our stop code docs.

**Comment by DOMARS** [comment]
@cf5146 - I'm checking with the dev team to see if we can document the 9696 parameter 1.

**Comment by DOMARS** [comment]
@cf5146 - I worked with the dev team to document 9696. Thanks for your input on the bug check topics.
