### ISSUE TITLE
Debugging bug check 0x124

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#1174]
How to use this extension when analyzing the dump file for a 0x124 bug check?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64dd3285-381e-f10a-31df-f079dfaa7370
* Version Independent ID: 976b2253-3f5f-a0f0-8821-866cffad31c7
* Content: [errpkt - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-errpkt)
* Content Source: [windows-driver-docs-pr/debugger/-errpkt.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-errpkt.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - With our limited documentation team resources, at this point, I will not be able to add more information to bug check 124.  Internals Chapter 3 has additional information on WER and how the bug check is created. Also see the echo lab resources list for additional books such as "Inside Windows Debugging" https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-#section-11-windows-debugging-resources
