### ISSUE TITLE
Sections documentation

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#1175]
Is there any documentation/reference that clearly describes the meaning of each section displayed by this command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3eafb41-8449-7e44-bf74-98e5d9b442ea
* Version Independent ID: f4da5229-c0c1-0f92-c81b-19cc1e5ca29b
* Content: [errrec - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-errrec)
* Content Source: [windows-driver-docs-pr/debugger/-errrec.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-errrec.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - In the linked  "Windows Hardware Error Architecture (WHEA)" topics is the error records topic which describes the fairly complex structure. https://docs.microsoft.com/en-us/windows-hardware/drivers/whea/error-records

For many users looking at the events in the events log, associated with the hardware errors, would be much easier then attempting to parse the raw structures. 

These debug extensions could be of use, if you are creating a WHEA plugin. In that case you would have spent the time to understand the error record stuctures.
