### ISSUE TITLE
EWDK 1809 does not work within batch (BAT) file

### ISSUE THREAD

**Issue by baget** [MicrosoftDocs/windows-driver-docs#1177]
I'm using a batch file to call EWDK\LaunchBuildEnv.cmd:

```
pushd %EDWK_DIR%
call LaunchBuildEnv.cmd
popd
```

when I run the batch script, the script stop in the middle after the call for LaunchBuildEnv.cmd
in prev build (1703) it worked.

If I change the call LaunchBuildEnv.cmd to call "BuildEnv\SetupBuildEnv.cmd"
it's work. but it does not documented anywhere.

**Comment by EliotSeattle** [comment]
I'm afraid that we were unable to reproduce this. I am closing this issue as stale, but please create another Issue if this is something that you are running into still.
Apologies.
Eliot
