### ISSUE TITLE
Using USBView Doesn't Tell Me How To Use Using USBView

### ISSUE THREAD

**Issue by MelbourneDeveloper** [MicrosoftDocs/windows-driver-docs#1180]
I installed the debugging feature as the article told me to. Now how do I run the app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94f202cf-716f-b82b-1eba-31e4226cbb4f
* Version Independent ID: c8ee74d1-b7f8-4807-b36f-1071ee68a30a
* Content: [USBView - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/usbview)
* Content Source: [windows-driver-docs-pr/debugger/usbview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/usbview.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@MelbourneDeveloper - If I understand your question correctly, see step 4.

*Navigate to the kits debugger directory for the processor type you are running and click on usbview.exe to start the utility.*
