### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/windows-driver-docs#1185]
The "software key" link in the first paragraph is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 114512ca-af19-a574-de09-542fc9170ccf
* Version Independent ID: c83e501f-4d59-6919-4851-825b1f794f76
* Content: [Opening a Device's Software Key - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/opening-a-device-s-software-key)
* Content Source: [windows-driver-docs-pr/install/opening-a-device-s-software-key.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/opening-a-device-s-software-key.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
THanks for reminding me about this, @EddieLotter these glossary targets went away some time ago. I took the opportunity to remove the link formatting from 345 affected files in 64b63c208, so now the string remains but the text is no longer hot. Sorry that we do not currently have a replacement for these. Thanks again for your interest in the docs.
