### ISSUE TITLE
Problem with UI refreshing during trace

### ISSUE THREAD

**Issue by kozera2137** [MicrosoftDocs/windows-driver-docs#1188]
Hi. I often use ta/t commands and I've noticed really annoying thing about UI refreshing during tracing large functions. What I mean is that 'proper tracing' (code executing) finishes, let's say in 20 seconds. After that I have to wait about 2 minutes until the whole trace is printed to WinDbg command window. Attached log files are ready in 20 seconds also but I still have to wait for UI. The best option would be something like bash redirections that wouldn't involve command window:
ta address > file.txt
Is there any way around it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e2a1e95-266d-9425-4e21-edf33654fdf4
* Version Independent ID: d03987c4-aef4-144e-a088-bc4e72586fdb
* Content: [ta (Trace to Address) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/ta--trace-to-address-)
* Content Source: [windows-driver-docs-pr/debugger/ta--trace-to-address-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/ta--trace-to-address-.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@kozera2137 - Thanks for reaching out to the Windows Driver Developer Documentation team. For product input on the debuggers follow this link to file product feedback using the Windows Feedback Hub: 
http://aka.ms/dexex 
The Feedback Hub allows customers to file and up vote product issues. The link automatically sets the product category to Debugging Tools for Windows.
Another option is to consider trying the next gen of the debugger, WinDbg preview. As it uses the same underlying engine, it may exhibit the same behavior. 
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-using-windbg-preview
Thanks again for reaching out to the Windows Driver Developer Documentation team.
