### ISSUE TITLE
Dead Link to TechNet

### ISSUE THREAD

**Issue by carmencrincoli** [MicrosoftDocs/windows-driver-docs#1195]
"For more information about EMS, search for Emergency Management Services on the Microsoft TechNet website."  Microsoft Technet links to here: https://go.microsoft.com/fwlink/p/?linkid=10111

**Comment by EliotSeattle** [comment]
Thanks for pointing this out, @carmencrincoli. Removed the link and cleaned up some formatting. PR is submitted, but I don't think we have anyone administering the repo today. Should be live early Monday, PST.
