### ISSUE TITLE
Universal Drivers and Windows 10 LTSC?

### ISSUE THREAD

**Issue by jwckauman** [MicrosoftDocs/windows-driver-docs#1196]
Do Universal Drivers work with Windows 10 LTSC 2019 (and earlier versions like LTSB 2016/2015)?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3764139-c203-f295-1591-e8c67ee0eb94
* Version Independent ID: 8128169c-8bab-008b-a7e4-bd647f4c02d2
* Content: [Target platform on driver reference pages - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/windows-10-editions-for-universal-drivers)
* Content Source: [windows-driver-docs-pr/develop/windows-10-editions-for-universal-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/windows-10-editions-for-universal-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the question @jwckauman. Yes, universal drivers work on these releases.
