### ISSUE TITLE
SANITIZE on non WinPE

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs#1199]
This article is very useful and talks a lot about how to send an ATA Secure Erase via WinPE. Though it also mentions Sanitize. Is Sanitize/CRYPTO SCRAMBLE EXT only supported on WinPE like Secure Erase, or is it also available in regular Windows (8/10)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73412c88-b107-dfc2-ba95-5ae78947d0bd
* Version Independent ID: a25f4158-3ad2-9e8a-5afe-c42820578426
* Content: [Security Group Commands - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/security-group-commands)
* Content Source: [windows-driver-docs-pr/storage/security-group-commands.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/security-group-commands.md)
* Product: **windows-hardware**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@csm10495 , glad you find this page useful. To answer your question, SANITIZE/CRYPTO is only supported on WinPE like SECURE ERASE. I've edited the page to make this more clear. Apologies for our slow response!
