### ISSUE TITLE
Inheritance of local computer certificate store to current user certificate store

### ISSUE THREAD

**Issue by h28669** [MicrosoftDocs/windows-driver-docs#1204]
You write:
"Be aware that all current user certificate stores inherit the contents of the local machine certificate stores. For example, if a certificate is added to the local machine "
This is at least not true for Personal folder: if you add a certificate to Local Computer/Personal it will not be displayed in Current User/Personal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56db178-78e9-9564-e2d0-8d4dc5a0068d
* Version Independent ID: e31df79f-b30a-75f2-335c-637a9eeaca25
* Content: [Local Machine and Current User Certificate Stores - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/local-machine-and-current-user-certificate-stores)
* Content Source: [windows-driver-docs-pr/install/local-machine-and-current-user-certificate-stores.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/local-machine-and-current-user-certificate-stores.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the report @h28669 and apologies for the delay.  I just updated the doc source.  The change will appear on docs.ms within the hour
