### ISSUE TITLE
NatVis format specifiers

### ISSUE THREAD

**Issue by zyndor** [MicrosoftDocs/windows-driver-docs#1215]
I'm glad I've eventually managed to find the NatVis format specifiers here, though I can't shake the feeling that it'd be great to have them somewhere more prominent, and maybe just refer to that resource in the dx section.

On the note for specifiers, ",na" seems to be missing from the list (its purpose is to suppress showing the memory address when the expression is a pointer) and the dot in ".s" might be a typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35974886-fcd8-e30b-2bcb-48ac4c32753d
* Version Independent ID: a73b8ba3-6096-74bf-3124-32a077ced9c7
* Content: [dx (Display Debugger Object Model Expression) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/dx--display-visualizer-variables-)
* Content Source: [windows-driver-docs-pr/debugger/dx--display-visualizer-variables-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/dx--display-visualizer-variables-.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@zyndor - Thanks for the comments. The dot in .s was a typo and is now ,s. I don't see the ,na in the command line help for dx so until it is an official option, I will hold off adding it for now.
