### ISSUE TITLE
Registry value check

### ISSUE THREAD

**Issue by dpugazhendhi** [MicrosoftDocs/windows-driver-docs#1217]
Hi All

Could you please share the screenshot to check my configuration in the registry.
I found my value in the registry as below.
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\kbdhid\Parameters]
"WorkNicely"=dword:00000000
"CrashOnCtrlScroll"=dword:00004101

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b225392c-a057-a2b6-28be-a0939f4834ba
* Version Independent ID: d94f25da-8679-f2b0-ed24-4b40712bf695
* Content: [Forcing a System Crash from the Keyboard - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/forcing-a-system-crash-from-the-keyboard)
* Content Source: [windows-driver-docs-pr/debugger/forcing-a-system-crash-from-the-keyboard.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/forcing-a-system-crash-from-the-keyboard.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@dpugazhendhi - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
For information on  this part of the registry see [HKLM\SYSTEM\CurrentControlSet\Services Registry Tree](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/hklm-system-currentcontrolset-services-registry-tree)

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•             [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
•             [OSR's ntdev List](https://community.osr.com/categories/ntdev)

Again, thanks for reaching out. Best of luck with this issue.
