### ISSUE TITLE
Flow contexts are not indicated at the INBOUND_IPPACKET Layers.

### ISSUE THREAD

**Issue by GreatFireWall** [MicrosoftDocs/windows-driver-docs#1218]
In my experiments:
1. Call `FwpsFlowAssociateContext(inMetaValues->flowHandle, FWPS_LAYER_INBOUND_IPPACKET_V4orV6, calloutIdV4orV6) ` at FLOW_ESTABLISHED layer (first UDP packet outbound).

2. Check `flowContext` in my INBOUND_IPPACKET_ClassifyFn, it's always be `zero`

### The docs descriptions can be misleading:
![image](https://user-images.githubusercontent.com/4510984/51107052-ace5a380-1828-11e9-9d9e-d7736c6fbd00.png)

### Relevant information I found
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/58a339ab-4fd3-46aa-8ccc-e4d1f6ab5a13/how-to-associate-packets-at-the-ippacket-layer-with-a-condition-on-the-aleauthrecvaccept-or?forum=wfp
![image](https://user-images.githubusercontent.com/4510984/51106982-77d95100-1828-11e9-9cf5-733b4b9598c9.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d6838d52-e499-8df4-37c9-5db0abe65379
* Version Independent ID: d6640d08-296a-25ed-7343-7ec4729b3c9b
* Content: [Associating Context with a Data Flow - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/network/associating-context-with-a-data-flow)
* Content Source: [windows-driver-docs-pr/network/associating-context-with-a-data-flow.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/associating-context-with-a-data-flow.md)
* Product: **windows-hardware**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @GreatFireWall, thanks for pointing this out. After taking a look at the thread to which you linked, and at the StreamEdit.c module in the [stmedit](https://github.com/Microsoft/Windows-driver-samples/tree/master/network/trans/stmedit) sample, I've updated the examples on this page to use the FWPS_LAYER_STREAM_V4 layer ID. Those changes should be live soon. Thanks again for helping to improve the docs!
