### ISSUE TITLE
ooss1199@yahoo.com

### ISSUE THREAD

**Issue by eyes8570** [MicrosoftDocs/windows-driver-docs#1221]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf25e7c-d235-0658-8624-f416ab0b01db
* Version Independent ID: edf92d0a-aa54-8784-1f38-e4c2e1dbd037
* Content: [DeviceOverrides Registry Key - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deviceoverrides-registry-key)
* Content Source: [windows-driver-docs-pr/install/deviceoverrides-registry-key.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/deviceoverrides-registry-key.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @eyes8570 I'm closing this one out because it's empty.  Please feel free to re-open with a comment
