### ISSUE TITLE
Code Signing Best Practices link is broken

### ISSUE THREAD

**Issue by SDWenzel** [MicrosoftDocs/windows-driver-docs#1222]
The Code Signing Best Practices link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716c22a0-7fc1-56a9-a0de-aca1f5b42d1d
* Version Independent ID: 493cc896-d2a5-4d9e-74c4-274cd9227612
* Content: [Trusted Root Certification Authorities Certificate Store - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/trusted-root-certification-authorities-certificate-store)
* Content Source: [windows-driver-docs-pr/install/trusted-root-certification-authorities-certificate-store.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/trusted-root-certification-authorities-certificate-store.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @SDWenzel I've updated the links. The change will prop to the live site overnight tonight Redmond time. See 1160253a94fe82c12d34aa3a3330455a0a1231fc for the changes
