### ISSUE TITLE
Need to specify contract around workitems and device object teardown.

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs#1227]
If a workitem has a parent object which is a wdfdevice, can the work item run after the wdfdevice object cleanup callback has been invoked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9abaa26-752a-0549-5db5-2e3ab286e2c8
* Version Independent ID: 1d5f78fe-0f45-e533-2014-af4517e1de3a
* Content: [Using Framework Work Items - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/using-framework-work-items)
* Content Source: [windows-driver-docs-pr/wdf/using-framework-work-items.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/using-framework-work-items.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @jakeoshins, apologies but I have been unable to get an answer from the feature team on this one, despite multiple queries.  I will still make a doc update if an answer comes in after this point, but I'm going to close this out for now.  We always appreciate your interest in the docs :)

**Comment by tedhudek** [comment]
Thanks for the feedback @jakeoshins.  This is now updated in https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/using-framework-work-items.
