### ISSUE TITLE
Need to specify contract on work item deletion

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs#1228]
What happens if a workitem is deleted while the workitem is enqueued?  Does it run?  Does it flush?  Does it get deleted without ever running?  This page should say.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9abaa26-752a-0549-5db5-2e3ab286e2c8
* Version Independent ID: 1d5f78fe-0f45-e533-2014-af4517e1de3a
* Content: [Using Framework Work Items - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/using-framework-work-items)
* Content Source: [windows-driver-docs-pr/wdf/using-framework-work-items.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/using-framework-work-items.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @jakeoshins sorry for the delay on this one.  I just added a table to the bottom of https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/using-framework-work-items that has this info.
