### ISSUE TITLE
MultiOS sample availability

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs#1231]
MultiOS sample has been removed for some reason from the Win10 WDK yet it is still being referenced by https://docs.microsoft.com/en-us/windows-hardware/drivers/install/sample-inf-file-for-device-installation-on-multiple-versions-of-windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f8fa576-2f26-521a-9e7b-83445ade6ffc
* Version Independent ID: dbe5c660-010f-4225-8aee-0991367d1e3d
* Content: [Sample INF File for Device Installation on Multiple Versions of Windows - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/sample-inf-file-for-device-installation-on-multiple-versions-of-windows)
* Content Source: [windows-driver-docs-pr/install/sample-inf-file-for-device-installation-on-multiple-versions-of-windows.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/sample-inf-file-for-device-installation-on-multiple-versions-of-windows.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the tip @I-gor-C see the change in the above commit.  Should be live soon
