### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by eliyasy** [MicrosoftDocs/windows-driver-docs#1235]
Please provide link to these samples on github

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81890736-b866-80d5-947e-04ddbb43e2e7
* Version Independent ID: 7b75ed42-23ae-fea3-941d-14bbf7cb75d6
* Content: [Sample Kernel-Mode Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/sample-kernel-mode-drivers)
* Content Source: [windows-driver-docs-pr/kernel/sample-kernel-mode-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/sample-kernel-mode-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @eliyasy check out the new links at https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/sample-kernel-mode-drivers
