### ISSUE TITLE
Is there any registry key ? 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1236]
I want to see the video memory manager on desktop, so where i can download  video memory manager and  how i  add  the  registry key  for Debug Output for the Video Memory Manager.
Thanks for the information , I knew from this article . Thanks to  authors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d55f42-798d-62fd-082b-4e06591821bb
* Version Independent ID: 467b2a7e-2a45-bafe-1732-7927ca088198
* Content: [Enabling Debug Output for the Video Memory Manager - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/enabling-debug-output-for-the-video-memory-manager)
* Content Source: [windows-driver-docs-pr/display/enabling-debug-output-for-the-video-memory-manager.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/enabling-debug-output-for-the-video-memory-manager.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@RAJU2529 The topic Enabling Debug Output for the Video Memory Manager is out of date, and unfortunately, the command is no longer available. I have removed this topic, and updated the topic [Video Memory Manager and GPU Scheduling](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/video-memory-management-and-gpu-scheduling) to describe where the video memory manager is found.
