### ISSUE TITLE
Thanks for the registry key

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1239]
today i added both the keys  on windows 10 1809 64bit , i will watch what will  happen.

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Watchdog\Logging]
"BreakOnError"=dword:00000001
"BreakOnAssertion "=dword:00000001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b13acc-fd68-670b-7f7d-2e209218a1d9
* Version Independent ID: 212dfd6a-1db8-d5d4-dc95-8b7ad85a57f2
* Content: [Logging Driver Errors - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/logging-driver-errors)
* Content Source: [windows-driver-docs-pr/display/logging-driver-errors.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/logging-driver-errors.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@RAJU2529  You're very welcome.
