### ISSUE TITLE
Is there any registry key ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1240]
Please add the registry key to enable User-mode driver logging

Thanks to authors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7799b7e2-df90-0775-3c7a-3334f179ea96
* Version Independent ID: c2cf037b-0b2a-0d13-d518-19cc5e8d91e6
* Content: [User-mode driver logging - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/user-mode-driver-logging)
* Content Source: [windows-driver-docs-pr/display/user-mode-driver-logging.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/user-mode-driver-logging.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@RAJU2529 Thank you for your question! I am currently investigating an answer for you.
