### ISSUE TITLE
What about for  WDDM 2.0 drivers

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1241]
almost all graphics  card producers are building using  wddm 2.0   , so  please  include the  details  about  WDDM 2.0 , and  give the registry key  to prove the ability to diagnose performance problems.

All the windows  users need the suitable  drivers  for  the  graphics  cards without degrading graphics performance without  hanging .  And  we  are  windows os  users  needs  long life battery in laptops .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 426e3ded-d908-0334-5e12-8b26a19b16cb
* Version Independent ID: f9f59851-aad8-6fe2-cf02-359709e9b9c9
* Content: [Disabling Frame Pointer Omission (FPO) optimization - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/disabling-frame-pointer-omission--fpo--optimization)
* Content Source: [windows-driver-docs-pr/display/disabling-frame-pointer-omission--fpo--optimization.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/disabling-frame-pointer-omission--fpo--optimization.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@RAJU2529 The requirements for WDDM 2.0 remains the same here.
