### ISSUE TITLE
How to find  wddm 2.5 is included in graphics driver 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1243]
Sir /madam , could you tell me  how to find wddm 2.5 in which graphics driver are  embedded 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8edc9d76-d1ed-6bb4-7a67-423ee38909f3
* Version Independent ID: ad5aa42c-ce12-31bc-8280-7fc4fd047a09
* Content: [What's new for Windows 10 display drivers (WDDM 2.x) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/what-s-new-for-windows-threshold-display-drivers--wddm-2-0-)
* Content Source: [windows-driver-docs-pr/display/what-s-new-for-windows-threshold-display-drivers--wddm-2-0-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/what-s-new-for-windows-threshold-display-drivers--wddm-2-0-.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@RAJU2529 Could you please clarify the question? Information about new features can also be found here: https://docs.microsoft.com/en-us/windows-hardware/drivers/what-s-new-in-driver-development#display-1809
