### ISSUE TITLE
How to find  how much  virtual memory  using ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1244]
I want to know  how  to  find  to how much of  virtual memory is  using  by  graphics card
1. Intel HD graphics 620, maximum  video memory 1GB  as per  intel website
2.Nvidia GeForce 940MX GDDR5 maximum video memory 2GB  as per nvidia  website 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dba80576-7bdf-5b27-30ed-f33022e368af
* Version Independent ID: 3116e737-dbb3-2588-f003-45fee8619a3f
* Content: [GPU virtual memory in WDDM 2.0 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/gpu-virtual-memory-in-wddm-2-0)
* Content Source: [windows-driver-docs-pr/display/gpu-virtual-memory-in-wddm-2-0.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/gpu-virtual-memory-in-wddm-2-0.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
Hello @RAJU2529 Unfortunately, I do not have an answer to your question. I suggest posting your question on the Windows Hardware WDK and Driver Development forum here: https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk&sort=relevancedesc&brandIgnore=True&searchTerm=display
You can also try the NTDEV forum at OSR Online here: https://www.osronline.com/showlists.cfm?list=ntdev
