### ISSUE TITLE
Thanks for hidden secret .

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1245]
[Xxx_SoftwareDeviceSettings]
...
 HKR,, UserModeDriverNameWow, %REG_MULTI_SZ%, Xxx.dll

above two  lines are  the real secret , today i knew from your article.
Thanks  a lot to  all authors 
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3152f8e-e46e-60b8-ffb2-b44544288d25
* Version Independent ID: 21832f56-454f-95cf-169f-fcd2de9e59d0
* Content: [Windows Display Driver Model (WDDM) 64-Bit Issues - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/microsoft-windows-vista-display-driver-64-bit-issues)
* Content Source: [windows-driver-docs-pr/display/microsoft-windows-vista-display-driver-64-bit-issues.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/microsoft-windows-vista-display-driver-64-bit-issues.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@RAJU2529 I am glad you found this information useful!
