### ISSUE TITLE
Please give the  registry key

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1247]
Please give the registry key to optimized screen rotation .
Thanks a lot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b20ceb32-6e4d-fb5e-e481-aa9aabded94f
* Version Independent ID: fa51d150-53c1-8ab6-0fbe-506bb9b52825
* Content: [Optimized screen rotation support - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/optimized-screen-rotation-support)
* Content Source: [windows-driver-docs-pr/display/optimized-screen-rotation-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/optimized-screen-rotation-support.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@RAJU2529 Thank you for your question! I am currently investigating an answer for you.
