### ISSUE TITLE
what about directX12

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1248]
please give the version numbers of  wddm 2.0 and directx12.

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ca7a91-0d99-c5bc-2eca-33811cc87673
* Version Independent ID: 2ac213a7-3e70-7350-c4db-acf22ec21ea1
* Content: [Version Numbers for WDDM Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/version-numbers-for-windows-vista-display-drivers)
* Content Source: [windows-driver-docs-pr/display/version-numbers-for-windows-vista-display-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/version-numbers-for-windows-vista-display-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
Hello @RAJU2529  Please view the topic https://docs.microsoft.com/en-us/windows-hardware/drivers/display/wddm-2-1-features#driver-versioning for the driver versioning for WDDM versions up to 2.1. I will add a link to that in this topic. Thank you!
