### ISSUE TITLE
What will happen ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1249]
What will happen if  i set  4  to MinimumStepPercentage, 
Please  reply sir /madam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a138f9a6-8db1-6ed3-2612-65878d47d278
* Version Independent ID: 8b8d1bb9-afa6-df99-e56a-37e5bf5413ea
* Content: [Supporting Brightness Controls on Integrated Display Panels - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/supporting-brightness-controls-on-integrated-display-panels)
* Content Source: [windows-driver-docs-pr/display/supporting-brightness-controls-on-integrated-display-panels.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/supporting-brightness-controls-on-integrated-display-panels.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by mimisasouvanh** [comment]
@RAJU2529 Thank you for the question. It will be incremented (or decremented) in brightness by at least 5 percent more (or less) than the previous brightness level, until the next available 5-percent step level is reached:
4, 10, 15, … 95, 100
