### ISSUE TITLE
windbg -? does not open debugger.chm

### ISSUE THREAD

**Issue by blabberer** [MicrosoftDocs/windows-driver-docs#1258]
the -? option that pops up the windbg command_line options help page is broken in windbg 17763     
the chm file does not contain the #IVB or ALIAS section    
so that mapids do not work as intended     

windbg!SpawnHelp() Creates the process with this commandline    
**hh.exe -mapid 9  debugger.chm**      
and fails to pop up the chm     
copy pasting an old chm (say build 14951 's debugger.chm ) in place properly pops up the commandline help    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6506daea-2fd3-a84d-0ba3-33439ff6df82
* Version Independent ID: 276c8458-4d3b-c04c-39c4-b3f1dc02c13f
* Content: [WinDbg Command-Line Options - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-command-line-options)
* Content Source: [windows-driver-docs-pr/debugger/windbg-command-line-options.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/windbg-command-line-options.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@aluhrs13 - More detail on the /? Help command line failure load issue.

**Comment by DOMARS** [comment]
@blabberer - Thanks for the additional information. The dev team is aware of this issue and working on a fix.

**Comment by DOMARS** [comment]
@blabberer - As the debugger team is tracking this, I will close this docs issue. 

 For product input follow this link to file product feedback using the Windows Feedback Hub: 
http://aka.ms/dexex 
The Feedback Hub allows customers to file and up vote product issues. The link automatically sets the product category to Debugging Tools for Windows.
Thanks again for reaching out to the Windows Driver Developer Documentation team.
