### ISSUE TITLE
How do we do this programmatically?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1276]
How do we do the same thing from within a driver? If I'm given the address of a shadow DEVICE_OBJECT in a WDM callback, how can I get the WDFDEVICE context, like !wdfdevext does? Given the address of a DEVICE_OBJECT, it would be nice to be able to programmatically get the addresses of all the DEVICE_OBJECTs in its DevStack, like !devstack does

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 903d0c3d-d021-43a8-123e-20838e2452ca
* Version Independent ID: af7fe752-8795-7ced-0ddb-7d648b36b088
* Content: [wdfkd.wdfdevext - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-wdfkd-wdfdevext)
* Content Source: [windows-driver-docs-pr/debugger/-wdfkd-wdfdevext.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-wdfkd-wdfdevext.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@BrianCatlin - Thanks for this interesting question. I don't know if there is a way to do this programmatically. As that would be more of a general kernel programming technique, you might see if someone on the OSR forums has determined a good way to do this.
[OSR's ntdev List](https://community.osr.com/categories/ntdev)
Thanks again for reaching out to the docs team.
