### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/windows-driver-docs#1283]
The "Testing a Driver" link is broken.
Consider using: https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/testing-a-kmdf-driver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c767c562-30ff-2f16-6584-33bbf2bf4781
* Version Independent ID: 9253ef49-c19f-7dd9-2a06-035a9fc132a1
* Content: [Testing a WDF Driver (KMDF or UMDF) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/testing-a-kmdf-driver)
* Content Source: [windows-driver-docs-pr/wdf/testing-a-kmdf-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/testing-a-kmdf-driver.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @EddieLotter for the suggestion.  I just updated the .md source in 9594cd56f59127fb0a795f9a4ba431b7203e67a3.  This change will be reflected on the live site during our next overnight refresh PST
