### ISSUE TITLE
Not helpful.

### ISSUE THREAD

**Issue by errgin** [MicrosoftDocs/windows-driver-docs#1289]
This document is not helpful. Regardless of how rare the error is, if you see it you're going to want to fix it. I have seen this error several times and I would love to know how to fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7517561d-0cb7-2732-b6ed-78fce1216948
* Version Independent ID: 2dd40107-b54b-bae9-3c34-75adfe7aee4d
* Content: [Bug Check 0x5A CRITICAL_SERVICE_FAILED - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x5a--critical-service-failed)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x5a--critical-service-failed.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x5a--critical-service-failed.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@errgin  - Thanks for this issue. And sorry that you are hitting this bug check. We use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, it is likely that we will only be able to do this work for a small sub set of all of the possible stop codes. Right now I'm working on the new stop codes that we have not documented at all. But we use input like this to determine which ones to work on, so thanks for your interest in improving our stop code docs.
