### ISSUE TITLE
Double definition of *RssMaxProcNumber

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs#1290]
The *RssMaxProcNumber registry key is defined twice. It's either a redundancy or some other registry key should have been described instead of the second definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b99aa941-27c4-c5cd-386c-fa1f64ab828f
* Version Independent ID: 23ccb092-56e8-8165-65f4-25bd2e3a983d
* Content: [Standardized INF Keywords for RSS - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/standardized-inf-keywords-for-rss)
* Content Source: [windows-driver-docs-pr/network/standardized-inf-keywords-for-rss.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/standardized-inf-keywords-for-rss.md)
* Product: **windows-hardware**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Ah, you have a keen eye @I-gor-C. Judging by the table below, it looks like that second definition is supposed to be for **\*NumRSSQueues**. I've updated that, and the changes should be live later today. Thanks!
