### ISSUE TITLE
Additional content proposal

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#1295]
I wrote an article about bugcheck analysis: it is published at https://social.technet.microsoft.com/wiki/contents/articles/6302.windows-bugcheck-analysis.aspx.
Do you think its content (or part of it) could be useful as an addition to the information provided in this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9622183-7c0c-93fe-17f5-e9d3748c9ff5
* Version Independent ID: e57c6029-3e5d-3989-90ab-280c31e0acbd
* Content: [Blue Screen Data - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/blue-screen-data)
* Content Source: [windows-driver-docs-pr/debugger/blue-screen-data.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/blue-screen-data.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - Thanks for the offer of this content, but I don't think it is match for the driver developer audience that this content is written for. 
In general the stop code content is written to our targeted driver developer audience. This is the C/C++ developer that owns the source code that is calling the BugCheckEx that is then creating the blue screen. The driver developer's code may call a function that allocates memory at the wrong IRQL level or does something else that causes Windows to blue screen. This developer is typically employed full time in driver development and is familiar with the tools and topics such as https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/analyzing-a-kernel-mode-dump-file-with-windbg that describe this process.
I know that IT professionals and other users read this content, but that is not our focus. My understanding is that the IT community uses forums and wiki's to exchange information. And in previous years, there were KB articles and such on TechNet authored by customer support. I'm not very familiar with the IT Pro content, but there may be channels to share information of interest to non kernel driver developers.  My recommendation would be to pursue those channels for general blue screen troubleshooting guidance for those that are not working to fix the source code that is actually causing the blue screen.
