### ISSUE TITLE
Link to github

### ISSUE THREAD

**Issue by JonAxtell** [MicrosoftDocs/windows-driver-docs#1303]
Link to source for localmon on github please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5565ed7d-1877-dc7c-f9cc-3a540a893199
* Version Independent ID: b409b773-8858-abad-e413-917f68a76048
* Content: [Sample Port Monitor - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/sample-port-monitor)
* Content Source: [windows-driver-docs-pr/print/sample-port-monitor.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/sample-port-monitor.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks @JonAxtell for filing an issue on this topic.

The LOCALMON print monitor sample has been archived and is not available in the [Windows Driver Kit (WDK) 10 samples](https://github.com/microsoft/Windows-driver-samples) repo on GitHub. 

It is still available in the [Windows Driver Kit (WDK) 8.0 samples](https://go.microsoft.com/fwlink/p/?LinkId=616509) archive and the [Windows Driver Kit (WDK) 8.1 samples](https://go.microsoft.com/fwlink/p/?LinkId=618052) archive.

I've updated the [Sample Port Monitor](https://docs.microsoft.com/windows-hardware/drivers/print/sample-port-monitor) topic with the archive links and the location of the LOCALMON sample within the archive.
