### ISSUE TITLE
Security isn't even mentioned??

### ISSUE THREAD

**Issue by DRNadler** [MicrosoftDocs/windows-driver-docs#1304]
Really??
Why don't you START with security required and why, and signing procedures.
Also, state up front if two separate computers are required for development.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c516129-2576-8860-173c-2157273e24a5
* Version Independent ID: 5d4dafdf-0f66-6f77-55b5-05387a7cb8b5
* Content: [Concepts for all driver developers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/concepts-and-knowledge-for-all-driver-developers)
* Content Source: [windows-driver-docs-pr/gettingstarted/concepts-and-knowledge-for-all-driver-developers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/concepts-and-knowledge-for-all-driver-developers.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @DRNadler, for the feedback.

The three topics that describe how to write your first driver (One for UMDF2 and two for KMDF) have sentences like this at the opening:

"This topic describes how to write a Universal Windows driver using User-Mode Driver Framework (UMDF) 2. You'll start with a Microsoft Visual Studio template and then deploy and install your driver on a separate computer."

I did add a link to the [Driver Security Guidance](https://docs.microsoft.com/windows-hardware/drivers/driversecurity/) to the topic, [Getting started with Windows drivers](https://docs.microsoft.com/windows-hardware/drivers/gettingstarted/).

 All the best.
Eliot
