### ISSUE TITLE
Dead HID link

### ISSUE THREAD

**Issue by cjbrowne** [MicrosoftDocs/windows-driver-docs#1307]
The link to the HID section points to an old msdn article and therefore redirects to a generic landing page now.

**Comment by EliotSeattle** [comment]
Hi @cjbrowne.
Since you created this issue as a general GitHub issue, it's not tied to a page. Can you tell me what page you found the broken link on? I'm happy to fix that. Or you can edit the page and send a pull request. Either way.
Thanks,
Eliot

**Comment by cjbrowne** [comment]
https://docs.microsoft.com/en-gb/windows-hardware/drivers/device-and-driver-technologies

I created the issue using the form on that page, I assumed it would automatically link to the page. Sorry!

**Comment by EliotSeattle** [comment]
Fixed it so the link points to https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/. Should be live shortly. Thanks for the heads up, @cjbrowne
