### ISSUE TITLE
THIS IS THE  BEST DOCUMENTATION ONLINE BY FAR... BUT

### ISSUE THREAD

**Issue by cdeaneGit** [MicrosoftDocs/windows-driver-docs#1310]
I am looking for a way to delete the NAT switches I made by mistake.   I made them on the  commandline of Powershell following their directions on https://win32.io/posts/Vagrant-Install-HyperV.   I would like to delete them using the powershell commandline.  I am a newbee and learned how to use the Get-Help command yesterday.   I have gone through 13 pages of links to topics here and I am still looking.  
----------------------
The other problem is you are using too much in-house slang for your Release Identification.
On page: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine
You have 3 link choices for Create a Virtual Machine with Hyper-V
    Windows 10 Fall Creators Update and later-----------click3- use this
    Windows 10 Creators Update--------------------------click2 -beta
    Windows 10 Anniversary Update and earlier-----------click on this one- screenshots for Hyper-V Manager are out of date

I Have Windows10 v18.09 .  I had to click on each of the 3 links and figure out which screenshots of Hyper-V Manager matched 
best matched the Hyper-V Manager I was seeing on my screen.   You can do better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23cacc17-bc2c-b801-6ec7-91a0759efb01
* Version Independent ID: 21fc5c40-0104-d3d5-d67f-6bd3ed3caf03
* Content: [Deleting a NIC Switch - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/deleting-a-nic-switch)
* Content Source: [windows-driver-docs-pr/network/deleting-a-nic-switch.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/deleting-a-nic-switch.md)
* Product: **windows-hardware**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @cdeaneGit, thanks for opening this issue. Glad you think the doc is great overall. :) However, this documentation is intended for network driver developers; in other words, the network card manufacturers who are programming a driver for their hardware work with Windows. This is not intended for IT support or troubleshooting.

I think what you're looking for is the PowerShell documentation. For example, the New-NetNat command referenced in your link is documented [here](https://docs.microsoft.com/en-us/powershell/module/netnat/new-netnat?view=win10-ps) and the corresponding command to remove a NAT object, Remove-NetNat, is [here](https://docs.microsoft.com/en-us/powershell/module/netnat/remove-netnat?view=win10-ps). 

As for Windows version naming conventions, here in the developer documentation we use the release version as the name, e.g. Windows 10, version 1809. Names like "Fall Creators Update" are more consumer branding names as opposed to the actual version names, which are typically based on the release year and month (so 1809 is September 2018).

Hope this helps. Best of luck with working with Hyper-V.

**Comment by cdeaneGit** [comment]
Thank you!
