### ISSUE TITLE
For others' reference...

### ISSUE THREAD

**Issue by szalkerous** [MicrosoftDocs/windows-driver-docs#1313]
If migrating VERY old code dependent on usbioctl.h, you need to now reference the mentioned usbiodef.h instead. I spent hours trying to figure out why I couldn't get old USB code to work in the newer environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8915580d-8e2f-2921-f713-dbb11501401e
* Version Independent ID: 272e2379-52cf-efd3-90e4-1eccd1084008
* Content: [GUID_CLASS_USB_DEVICE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-class-usb-device)
* Content Source: [windows-driver-docs-pr/install/guid-class-usb-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/guid-class-usb-device.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @szalkerous and apologies for the delay.  I've just checked in this fix, and it should appear on the live site within half an hour.
