### ISSUE TITLE
Bcdedit /create doesn’t work

### ISSUE THREAD

**Issue by Oschly** [MicrosoftDocs/windows-driver-docs#1316]
Hi! I am doing homework and I have to create new Bcdedit entry, so I am inserting command:
Bcdedit /create /d “Windows Vista” /application osloader
And then there is written that it has been completed successfully, but when I am trying to read Bcdedit there is no new entry on my list.

**Comment by DOMARS** [comment]
@Oschly - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. 
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
