### ISSUE TITLE
not work on vmware (set windbg in guest)

### ISSUE THREAD

**Issue by salgilbarana** [MicrosoftDocs/windows-driver-docs#1322]
as you know most use serial port way on vmware  but  i cant find ethernet way

so i try to do however not work 

i want ask for dont have set windbg ethernet on vmware

how to solve to not work on vmware

**Comment by DOMARS** [comment]
@salgilbarana - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. 
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
Again, thanks for reaching out. Best of luck with this issue.
