### ISSUE TITLE
Call out that 'attestation signatures' are valid for S mode

### ISSUE THREAD

**Issue by swinston** [MicrosoftDocs/windows-driver-docs#1324]
Append 'Valid signatures can be obtained by either Hardware Certification or Attestation.' to first bullet under 'Driver Requirements'. The text comes from the note here: https://docs.microsoft.com/en-us/windows-hardware/drivers/install/kernel-mode-code-signing-requirements--windows-vista-and-later-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 138a9602-43a6-1b8a-7159-dc3cd7e62f5a
* Version Independent ID: dbf5e2e6-51e1-a43b-becb-3919dc51cde3
* Content: [Windows 10 in S mode Driver Requirements - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/windows10sdriverrequirements)
* Content Source: [windows-driver-docs-pr/install/Windows10SDriverRequirements.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/Windows10SDriverRequirements.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @swinston we'd actually prefer that folks not do this on Windows 10 in S Mode, but I really appreciate the suggestion.  Thanks for caring about the docs!
