### ISSUE TITLE
More info on the "other switches"

### ISSUE THREAD

**Issue by JonAxtell** [MicrosoftDocs/windows-driver-docs#1325]
Currently says "other switches
Configures Inf2Cat to add a DRM level catalog attribute or a PE catalog attribute to files, or to add page hashes to files. For more information, use the /? switch."

Would be more useful if this documentation details and describes the usages of the other switches and the consequences of using them. Just the basic that /drm and /pe are deprecated would save having to open up a command window to run the program to find out when normally the command is run as part of a build process so never run manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0afbc04b-349a-57ed-eeb0-3d2cd28e359c
* Version Independent ID: de61f684-31d7-2de5-d66c-a3319f5198d9
* Content: [Inf2Cat - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/inf2cat)
* Content Source: [windows-driver-docs-pr/devtest/inf2cat.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/inf2cat.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thank you, @JonAxtell, for pointing this out. I've added three switches that were not documented and removed the vague note about "other switches". It should go live later today. Appreciate that you took the time to let me know.
