### ISSUE TITLE
Benefits of single-tier vs. two-tier

### ISSUE THREAD

**Issue by russbearl** [MicrosoftDocs/windows-driver-docs#1329]
Is there a performance benefit of having symbol store as a single-tier vs. two-tier structure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 330a3dee-501f-0ded-1757-425031a5f4a7
* Version Independent ID: cf39d189-5c63-951f-4215-42bbf0a04bfa
* Content: [Symbol Store Folder Tree - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symbol-store-folder-tree#symbol-store-single-tier-or-two-tier-structure)
* Content Source: [windows-driver-docs-pr/debugger/symbol-store-folder-tree.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/symbol-store-folder-tree.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@russbearl - I would say the difference in file system access would be minimal with either single or two tier structure, but have not tested this and of course factors such as using a SSD would change your results. If you want to investigate this further, the you may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[OSR's ntdev List](https://community.osr.com/categories/windbg)
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
