### ISSUE TITLE
Document "the client is not using same version of remoting protocol as the server" error message for WinDbg

### ISSUE THREAD

**Issue by aluhrs13** [MicrosoftDocs/windows-driver-docs#1330]

**Comment by aluhrs13** [comment]
@DOMARS I have a rough write-up of this internally I'll share with you.

**Comment by DOMARS** [comment]
@aluhrs13 - Feel free to send a PR.

**Comment by DOMARS** [comment]
Following up on this with Andy.

**Comment by DOMARS** [comment]
@aluhrs13 - The new troubleshooting step about the version mismatch is now live. So closing this issue.
