### ISSUE TITLE
Great Content

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1331]
Thanks for the hidden secrets , I hope these regsitry keys  will help to the windows users. Thanks to all authors 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32122b55-0ed3-e2df-4bc4-f37c52d5af65
* Version Independent ID: d24d5892-5cb7-05aa-f54a-db06d4f3b7d9
* Content: [USB Device Registry Entries - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-device-specific-registry-settings)
* Content Source: [windows-driver-docs-pr/usbcon/usb-device-specific-registry-settings.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-device-specific-registry-settings.md)
* Product: **windows-hardware**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Thanks, @RAJU2529! Although these registry keys are detailed for USB driver developers, I'm glad you got some good knowledge out of the doc. :)
