### ISSUE TITLE
Example 3: Using an extension INF to install a filter driver

### ISSUE THREAD

**Issue by CKroid** [MicrosoftDocs/windows-driver-docs#1335]
We submitted a driver based on "Example 3: Using an extension INF to install a filter driver" but the creation of the shipping label was rejected by MS with the following error:

"Bad Submission data: Bad driver INF configuration VSO bugId: 20385599. Comment: Extensions should not contain sys, dll or exe files. Contains: .cat: 1, .inf: 1, .sys: 2"

So is Example 3 a valid driver? Are we allow to install filter driver through extension inf?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e5e417-647c-0c3a-9c25-83a7be9efe3a
* Version Independent ID: 6ccb6634-97cb-b66f-3ca5-0e58218abdc0
* Content: [Using an Extension INF File - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-an-extension-inf-file)
* Content Source: [windows-driver-docs-pr/install/using-an-extension-inf-file.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/using-an-extension-inf-file.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thank you @CKroid for reporting this!  This was a mistake on the Microsoft side.  It was fixed this morning Redmond time.  Filter driver Extension packages should now pass through validation as expected.
