### ISSUE TITLE
adding boot entry tutorial only specifies how to add a newer os than windows vista

### ISSUE THREAD

**Issue by kevincrans** [MicrosoftDocs/windows-driver-docs#1336]
I want to add an older os to my boot entry than windows vista in my virtual machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e888de-16af-86ce-3844-b55b519aea27
* Version Independent ID: 97cbb0fb-8c60-afe6-5170-0bfcc75a8613
* Content: [Adding Boot Entries - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/adding-boot-entries)
* Content Source: [windows-driver-docs-pr/devtest/adding-boot-entries.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/adding-boot-entries.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by DOMARS** [comment]
@kevincrans - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

 Best of luck with this issue.
