### ISSUE TITLE
Feature Request: Joint Memory Dump, and other features

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [MicrosoftDocs/windows-driver-docs#1340]
First off: I sincerely apologize for putting my request in the documentation section, but I couldn't find any other Microsoft Github repositories involving crash dumps, and I don't have access to the Feedback Hub from my current device (runs iOS)... So, really sorry about that. If you could somehow move these to the appropriate section, I'd appreciate that.

Without further ado...

# Summary of the Main Requested Feature, Joint Memory Dump:
Simply put, I would like to see an option for crash dumps where both an Active Memory Dump and a Minidump are created at the same time. The pagefile would also use automatic sizing the same way that it would when using the Automatic Memory Dump option.

# Related Work:
**1) Keep Multiple Full Dumps: **Instead of just an option to overwrite existing files, I would like to see the problem foul play existing complete memory dump get renamed and a new one generated, using a "Max Full Dumps" option to specify the maximum number of full dumps of which to keep a local copy, the oldest ones being uploaded (if applicable) to a secure server, and then deleted locally. 
** 2) Separated User-Space Dumps: **With this option, the Userspace data will be dumped in a separate file, stored in the account folder of the user who was logged in at the time of the crash. It would be encrypted with their Account Passcode, if they have one set up.
** 3) TEMP Snapshot: **This option would attach additional data to a dump file, containing a list of all files that were in the located TEMP directory at the time of the crash, as well as a list of any files that were open, which processes/users were accessing those files, and whether the access was a Read Operation or a Write operation. All of these could prove very helpful in troubleshooting.
** 4) Registry Snapshot: **With this last option, the dump file would also contain a copy of the Registry as it was at the time of a crash.
** 5) User-Initiated Dump: **These could be performed by the user at any time, using either CMD.exe, PowerShell, or the Task Scheduler. User-Initiated Dumps would not produce a bugcheck, and would be saved to the user's own directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d702ca89-9f49-3e7d-6c0c-53a882de7944
* Version Independent ID: a484aef5-f015-fe1c-49d7-99d06391a498
* Content: [Debugging OCA minidump files - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-oca-minidump-files)
* Content Source: [windows-driver-docs-pr/debugger/debugging-oca-minidump-files.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugging-oca-minidump-files.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Amaroq-Clearwater - I'd recommend taking this input and using the Product Feedback button on the left side on the bottom of the page. 
As another option you can use this link on a Windows PC: http://aka.ms/dexex to open the debugger teams input page in the feedback hub app.  I looks like we do require this to come from a PC running Windows. So you may need to borrow one to send your input. You might want to provide input on supporting the feedback hub on a broader range of operating systems as well.
