### ISSUE TITLE
WDK forces /Qspectre for new projects.  Uninstall of extension prevents VS2017 uninstall or repair!

### ISSUE THREAD

**Issue by gilgm12** [MicrosoftDocs/windows-driver-docs#1342]
![d51a3b863bb445a97905c44dc3d24c64](https://user-images.githubusercontent.com/622590/53289455-59357680-3753-11e9-9606-be41edbd87ba.png)
![3444487fd3bdd8f6a21830c703aa87a8](https://user-images.githubusercontent.com/622590/53289458-5c306700-3753-11e9-9a29-64d9e72226e5.png)

My VS2017 workspaces are hosed now. :(

**Comment by EliotSeattle** [comment]
Hi @gilgm12 
Sorry that you're having this happen. I have not seen this occur before. Do you have any more repo details?
Also, my team handles feedback about the documentation. Is there an error in the docs? If this is really about the product, you'll have better success submitting feedback through Feedback Hub (Click **Start**, and then type **Feedback Hub**).

**Comment by EliotSeattle** [comment]
Closing without a response to question and b/c this is product feedback.
