### ISSUE TITLE
Incorrect autodetection and set the target bitness if params of exe file are using

### ISSUE THREAD

**Issue by goodandrewsoft** [MicrosoftDocs/windows-driver-docs#1348]
Example:
`WinDbgX.exe C:\Windows\SysWOW64\notepad.exe`
task manager:
![image](https://user-images.githubusercontent.com/2471892/53367294-6cf8fc80-394e-11e9-951e-cec730a83fbf.png)
EngHost.exe - is 32 bit (good)

Example:
`WinDbgX.exe C:\Windows\SysWOW64\notepad.exe someparam`
task manager:
![image](https://user-images.githubusercontent.com/2471892/53367349-97e35080-394e-11e9-807d-a0d089a70aaa.png)
EngHost.exe - is 64 bit (wrong detection)

Incorrect detection leads to inconsistencies when opening an exe file with parameters.
For example, the command line combination does not work:
`-c "bu notepad!WinMain;g"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8353dbe7-846a-f902-0f6c-f7e75ad846d8
* Version Independent ID: 6ec7d01f-69f9-5f7b-582b-0d63d9c40a06
* Content: [WinDbg Preview - Command line startup options - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-command-line-preview)
* Content Source: [windows-driver-docs-pr/debugger/windbg-command-line-preview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/windbg-command-line-preview.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@goodandrewsoft - As described in this topic, you can use the debugArch param to specify bitness.

-debugArch x86 -or- amd64 | Override the autodetect behavior and set the target bitness for the debugger.
-- | --

For product behavior input follow this link to file product feedback using the Windows Feedback Hub: 
http://aka.ms/dexex 
The Feedback Hub allows customers to file and up vote product issues. The link automatically sets the product category to Debugging Tools for Windows.

For further questions on working with the debugger, your best bet is the debugger forums, for example: 

•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
