### ISSUE TITLE
The driver kepps coming back after restart

### ISSUE THREAD

**Issue by designdust** [MicrosoftDocs/windows-driver-docs#1349]
This is annoying as I want to get rid of the faulty drivers. The problem the drivers just keep coming back after restart. Tried the pnputil but said drivers didn't exist. Anyone? Solution? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963a0877-81d6-57b1-2922-459c9077c76c
* Version Independent ID: 49998df1-e7fd-6ce7-eb49-aa9c37f13cd8
* Content: [Using Device Manager to Uninstall Devices and Driver Packages - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-device-manager-to-uninstall-devices-and-driver-packages)
* Content Source: [windows-driver-docs-pr/install/using-device-manager-to-uninstall-devices-and-driver-packages.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/using-device-manager-to-uninstall-devices-and-driver-packages.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback, @designdust, and apologies for the delay getting back to you.  That type of issue can happen for a variety of reasons that aren't within the scope of this documentation to cover (these docs are aimed at commercial driver developers).

If it's still a problem, you may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
* [OSR's ntdev List](http://www.osronline.com/showlists.cfm?list=ntdev)

Again, thanks for reaching out. Best of luck with this issue.
