### ISSUE TITLE
OS Version for Both Host and Target Machines

### ISSUE THREAD

**Issue by Ammarhassan48** [MicrosoftDocs/windows-driver-docs#1351]
Is it necessary to have exactly same to same OS on both Host and Target machine.
Like I'm running Windows 10 on both machines but Host running Windows 10 ( Build 1809 ) and Target running Windows 10 ( Build 1803 )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce050ea3-d61e-830c-3038-f725eb4c29e1
* Version Independent ID: eb7fc65e-bcfe-dc86-3f8c-336d20eb0c86
* Content: [Provision a computer for driver deployment and testing (WDK 10) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/provision-a-target-computer-wdk-8-1)
* Content Source: [windows-driver-docs-pr/gettingstarted/provision-a-target-computer-wdk-8-1.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/provision-a-target-computer-wdk-8-1.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @Ammarhassan48.
From my perspective, you should try to match versions as closely as possible. If the versions are different, they *might* work, but they might not. It really kind of depends on the differences between them. For a little more detail about setting up the environment, see [Preparing a Computer for Manual Driver Deployment](https://docs.microsoft.com/windows-hardware/drivers/develop/preparing-a-computer-for-manual-driver-deployment) and [Installing the KMDF echo driver sample on the target system](https://docs.microsoft.com/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-#section-4-install-the-kmdf-echo-driver-sample-on-the-target-system).

You might also want to ask those on the [Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=wdk) to see what their experience is.

Hope this helps.
