### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by chjone** [MicrosoftDocs/windows-driver-docs#1358]
The URL at the bottom 'https://docs.microsoft.com/ewindows/desktop/Services/protecting-anti-malware-services-' does not resolve.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cb04a99-d20e-4b9b-9c25-bbeaaed52b8d
* Version Independent ID: 80858d16-aa19-4992-1767-4c1bc365f297
* Content: [Early Launch AntiMalware - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/early-launch-antimalware)
* Content Source: [windows-driver-docs-pr/install/early-launch-antimalware.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/early-launch-antimalware.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Thanks, @chjone, for catching this. I've made the fix (just removed the "e" in front of windows in the url. Should be published later today.
