### ISSUE TITLE
A mistaken statement

### ISSUE THREAD

**Issue by TanakaYasen** [MicrosoftDocs/windows-driver-docs#1359]
"The driver can register an InterruptService routine to handle line-based or message-signaled interrupts. (This is the only type available prior to Windows Vista.) "

According to the statement above, an InterruptService routine is only to handle line-based interrupts rather than the message-signaled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4383b686-d65c-4a8e-167a-46f60ddf760b
* Version Independent ID: 0a7a5bcb-c805-4954-dbb2-7a3918a167c9
* Content: [Introduction to Interrupt Service Routines - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-interrupt-service-routines)
* Content Source: [windows-driver-docs-pr/kernel/introduction-to-interrupt-service-routines.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/introduction-to-interrupt-service-routines.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback, @TanakaYasen, and apologies for the delay.  The documentation is correct, but is missing some info that is elsewhere.  Specifically, the InterruptService routine can be used for both line-based or message-signaled, depending on how it was connected. See point 3 on this page:: 

https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-message-signaled-interrupts

I have added a link to this intro page to the page you opened this issue on.  The link should appear on the live site within 15 min or so.

Thanks again for contacting us!
