### ISSUE TITLE
Can you post also the Microsoft Code Verification Root certificate.

### ISSUE THREAD

**Issue by RobG-MSFT** [MicrosoftDocs/windows-driver-docs#1360]
I have a customer that does not have the ability to get the Microsoft Code Verification Root certificate via the Root Update program (if it is even available via that method).   They do not allow systems to access the internet.  I would be helpful to have the Root CA certificate available to be downloaded just as you have made the intermediate Cross CA Certificates available from 3rd parties here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c19d51-a948-b3ff-65c2-d8c54291b42f
* Version Independent ID: b5654182-fdcb-72c0-e5ae-536992731e98
* Content: [Cross-Certificates for Kernel Mode Code Signing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/cross-certificates-for-kernel-mode-code-signing)
* Content Source: [windows-driver-docs-pr/install/cross-certificates-for-kernel-mode-code-signing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/cross-certificates-for-kernel-mode-code-signing.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by JemmyLoveJenny** [comment]
You can download it from [www.microsoft.com](http://www.microsoft.com/pki/certs/MicrosoftCodeVerifRoot.crt) or [crt.sh](https://crt.sh/?id=162461728) (Press "Download Certificate: PEM" in the left column)
