### ISSUE TITLE
Missing entry for 0x3453

### ISSUE THREAD

**Issue by arilou** [MicrosoftDocs/windows-driver-docs#1364]
Arg 1 for this bugcheck can be `0x3453`, but it is not listed in the table. Anyone know what it means?

Arg2 seems to be the EPROCESS
Arg3 seems to be a PFN index?

**Comment by DOMARS** [comment]
@arilou - Can you open this issue against a specific topic or a content area?

**Comment by tedhudek** [comment]
Please reopen if still needed and provide a URL of the page where you are seeing the problem.
