### ISSUE TITLE
could missing drivers be uploaded 

### ISSUE THREAD

**Issue by acontrario52** [MicrosoftDocs/windows-driver-docs#1365]
I had to do a clean install after W10 1809 update on a Sony Vaio laptop (defunct brand), fully functional i7 SSD 1TB.  Only 2 drivers missing.
I had to search. I had in store the 2 drivers, immediately recognised. Others may not have them. Could I upload them somewhere? (1. Finger scanner  AuthenTec Inc. AES1660 ATSwpWDF.sys
& 2. Extension parser on LTC controller ACPI\SNY5001 SFEP.sys). Nothings serious preventing to work but still, a nice to have.  Better than using tools from unknown sources to automate the matching & update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd3829b-c6c5-2ee2-5741-86714cff2345
* Version Independent ID: ad072ec7-1388-0499-0e88-ea8074abb8cf
* Content: [Find and manage your hardware submission - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/find-hardware-submission#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/find-hardware-submission.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/find-hardware-submission.md)
* Product: **windows-hardware**
* GitHub Login: @dimanjar
* Microsoft Alias: **dimanjar**

**Comment by EliotSeattle** [comment]
Hi @acontrario52.
Sorry to hear that you went through that trouble.
The registered owner for the drivers would have to upload the them to the Partner Center. As you mention, both are available on Sony's website.
Thanks for reaching out.
@EliotSeattle
