### ISSUE TITLE
Link to Certification Test Reference works but target is obsolete

### ISSUE THREAD

**Issue by jurva** [MicrosoftDocs/windows-driver-docs#1368]
The link is to:
https://docs.microsoft.com/en-us/previous-versions/windows/hardware/hck/hh998741(v=vs.85)
which says:

"We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported.". The link on the target page contains a "Recommended Version" link to a top-level, very generic page. I suggest you change the original link to point to the page which is relevant to the issue of Certification Test Reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebbf0ccc-8b48-7764-9d3c-9bcf03c65748
* Version Independent ID: 0e071fcb-d089-e3c0-c18e-4ec769a24654
* Content: [Authenticode Digital Signatures - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/authenticode)
* Content Source: [windows-driver-docs-pr/install/authenticode.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/authenticode.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback, @jurva, and apologies for the delay getting back to you.  The correct link is https://docs.microsoft.com/en-us/windows-hardware/test/hlk/api/hlk-api-reference.  I've just updated the doc page with that link, and the fix should be live within 15 min.  Thanks again!
