### ISSUE TITLE
Incorrect character escaping in code samples

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/windows-driver-docs#1370]
It looks like a number of HTML characters have been incorrectly escaped in code samples in this repository.

For example: apostrophe's showing as `&#39;` in the code comments here:
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/checking-for-in-progress-installations

And `&quot;` in the code samples here:
https://github.com/MicrosoftDocs/windows-driver-docs/blob/b9be32d9e5217219dee224527d32979d396a9027/windows-driver-docs-pr/develop/debugging-a-universal-driver.md

**Comment by EliotSeattle** [comment]
Thanks, @ChrisMaddock.
I avow, once more, that I never met a migration tool I didn't like.
Got these. They'll be live shortly.  In the future, please feel free to create a pull request if you see anything like this.
Cheers,
Eliot

**Comment by ChrisMaddock** [comment]
Hey @EliotSeattle - sorry, my bug report wasn't clear.

The above were just two examples - this same problem happens in 100s of places across this repo. That's one of the reasons I didn't pull request, was more than I was able to commit to.

Would you be able to reopen this issue, for the remaining problems? Here's a search showing problems with the apostrophe escaping - the same can be found for other HTML escaping characters too.

https://github.com/MicrosoftDocs/windows-driver-docs/search?q=%22%26%2339%3B%22&unscoped_q=%22%26%2339%3B%22

**Comment by EliotSeattle** [comment]
Oh, you mean like real work? Got it. :-(
Do you happen to have a list of the other escape characters you've seen? It'd be helpful. If not, we can come up with some regular expression searches.

**Comment by ChrisMaddock** [comment]
Ikr. 😞 

I can see pretty broken cases of much everything common... `&amp; &gt; &lt; &quot;` etc. I haven't searched much for other numeric escapes.

**Comment by tedhudek** [comment]
Not repro'ing this problem now.  I do see instances of `&gt;`, for instance, but they render fine, as the greater than symbol.

Appreciate the report.
