### ISSUE TITLE
A link is broken

### ISSUE THREAD

**Issue by jurva** [MicrosoftDocs/windows-driver-docs#1376]
The link to "Microsoft Cross-Certificates for Windows Vista Kernel Mode Code Signing" is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b82e43ef-8477-f0cf-a15b-393d13bd99a7
* Version Independent ID: c8c45d60-5f06-519f-77d1-ee5a522a396b
* Content: [Software Publisher Certificate - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/software-publisher-certificate)
* Content Source: [windows-driver-docs-pr/install/software-publisher-certificate.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/software-publisher-certificate.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Fixed this in the source. That text now points to https://docs.microsoft.com/windows-hardware/drivers/install/cross-certificates-for-kernel-mode-code-signing. Should be live later today.
