### ISSUE TITLE
Unhelpful link

### ISSUE THREAD

**Issue by jurva** [MicrosoftDocs/windows-driver-docs#1377]
Link in "see Test Signing a Driver" goes to the top level document (https://docs.microsoft.com/en-us/windows-hardware/drivers/), which is not very useful, considering the written topic of the link. It is almost as useless as linking to "goole.com" to search for ore info about different types of fruit flies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26b5537-027d-6253-2d92-cd0bb230bfd8
* Version Independent ID: 6a7fdcc8-2c94-4aa2-94a7-8289946b63bf
* Content: [Release-Signing Driver Packages - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/release-signing-driver-packages)
* Content Source: [windows-driver-docs-pr/install/release-signing-driver-packages.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/release-signing-driver-packages.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Fixed in source. Should be live shortly.
