### ISSUE TITLE
The list of Codes

### ISSUE THREAD

**Issue by jurva** [MicrosoftDocs/windows-driver-docs#1378]
A link to a relevant list of error codes as shown in the arcticle's screenshot in "Code 39" might be handy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3139a-27f1-d868-b971-2255ffe4dcc2
* Version Independent ID: 2ba8b67a-ee31-2fce-7143-48df43bfc3ce
* Content: [Detecting Driver Load Errors - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/detecting-driver-load-errors)
* Content Source: [windows-driver-docs-pr/install/detecting-driver-load-errors.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/detecting-driver-load-errors.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Again, thanks @jurva for the suggestion and apologies it took us a while.  The link you want is https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-manager-error-messages.  I've added that to the doc page above, fix should be live in 15 min or so
