### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs#1379]
Links to details about the IOCTLs IOCTL_SPB_EXECUTE_SEQUENCE, IOCTL_SPB_LOCK_CONTROLLER, and IOCTL_SPB_UNLOCK_CONTROLLER are dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30bbb5eb-e38a-d1ce-4522-bfb3b098e087
* Version Independent ID: aee67d84-4d63-4966-7484-3e63c36d48f2
* Content: [Using the SPB I/O Request Interface - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/spb/using-the-spb-i-o-request-interface)
* Content Source: [windows-driver-docs-pr/spb/using-the-spb-i-o-request-interface.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/spb/using-the-spb-i-o-request-interface.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @druske 
A small artifact of a content migration we went through. I've made these updates, and they'll be live later today.
