### ISSUE TITLE
For my issue involving graphics timeout, you recommend increasing the value of TdrDelay in my registry. however no such entry exists in my registry (Windows 7)

### ISSUE THREAD

**Issue by acclivity2** [MicrosoftDocs/windows-driver-docs#1382]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652e03eb-a834-6c30-44c1-e9c917a94926
* Version Independent ID: bca54aa8-2da8-e389-aa74-f66bf3ab65ab
* Content: [Timeout Detection and Recovery (TDR) Registry Keys - Windows drivers](https://docs.microsoft.com/en-gb/windows-hardware/drivers/display/tdr-registry-keys#feedback)
* Content Source: [windows-driver-docs-pr/display/tdr-registry-keys.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/tdr-registry-keys.md)
* Product: **windows-hardware**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by RAJU2529** [comment]
hello sir , normally  those  regsitry may or not esists , so you add it manually 
here is the registry keys , that i have added and  applied to windows 10 .
Before  modifying the registry keys , take a backup of registry.
copy and paste all the lines in notepad  save as  TDRFIX.reg  and then merge 

Windows Registry Editor Version 5.00

; fix video time detected by nvidia
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrLevel"=dword:00000003
"TdrDelay"=dword:00000078
"TdrDdiDelay"=dword:0000003c
"TdrTestMode"=dword:00000000
"TdrDebugMode"=dword:00000002
"TdrLimitTime"=dword:00000078
"TdrLimitCount"=dword:00000005
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\BasicDisplay]
"BasicDisplayUserNotified"=dword:00000001
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\DCI]
"Timeout"=dword:00000078
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\TdrWatch]
"TDR_RECOVERY"=dword:00000001



and restart the windows
