### ISSUE TITLE
How can I call _DSM  method in a UMDF USB driver? 

### ISSUE THREAD

**Issue by wangyanhui0614** [MicrosoftDocs/windows-driver-docs#1383]
I want to call _DSM method in a USB driver(UMDF driver),  but I set  UMDFDispatcher = WinUSB in inf file, when I call _DSM method, the program crashed.   If I delete UMDFDispatcher = WinUSB,  call _DSM method is successful.   Is there a way call _DSM method in a USB driver with UMDFDispatcher = WinUSB ???

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8c3650d3-b014-9dfa-9cd9-431829f63a44
* Version Independent ID: 7878124f-5c3e-0f43-12f1-33964b2f5e93
* Content: [USB Device-Specific Method (_DSM) - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/bringup/usb-device-specific-method---dsm-#feedback)
* Content Source: [windows-driver-docs-pr/bringup/usb-device-specific-method---dsm-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/usb-device-specific-method---dsm-.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
