### ISSUE TITLE
get-a-code-signing-certificate Comodo link points to InstantSSL

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/windows-driver-docs#1384]
The 'Comodo' link has been tampered with!

The ["Microsoft link"](https://go.microsoft.com/fwlink/?linkid=863208) currently points to InstantSSL "https://www.instantssl.com/code-signing-certificates"

instead of the new owners of Comodo, Sectigo: https://sectigo.com/products/signing-certificates/code-signing

I would create a pull request myself and correct the Docs, but do not know how to create a new Microsoft shorturl.

**Comment by EliotSeattle** [comment]
@SillyKeith, can you please look at this and Issue #1010

**Comment by tedhudek** [comment]
Feedback applies to the Sectigo link on https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate

**Comment by tedhudek** [comment]
Issue if fixed
