### ISSUE TITLE
Unsupported driver architecture AMD64 found in driver

### ISSUE THREAD

**Issue by rubu** [MicrosoftDocs/windows-driver-docs#1385]
There seem to be changes in the attestation process which is not described here. We have a driver which signed successfully until October 2017, but now fails (only the x64 version). Everything was done according to this documentation. The "UniversalLog" contains the line "Unsupported driver architecture AMD64 found in driver" even though we have not changed anything. For the previously signed builds (before October 2017) the "Declarative" and "Universal" are grayed out - but now for the new submissions the "Universal" check fails and the signed driver does not install on Windows 8.

To verify if the issue is on our side, I tried to again follow this document - I took the Echo sample, built it and signed it with our EV and again the x64 submission failed with the same error. So definitely something has changed - but there is no information/documentation on this. Can anyone please either provide a suggestion or update the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed287852-04b7-1569-fd51-2640cfa24f57
* Version Independent ID: a8ce732f-5b41-f1ce-e37d-a7c2794546a4
* Content: [Attestation signing a kernel driver for public release - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/attestation-signing-a-kernel-driver-for-public-release#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/attestation-signing-a-kernel-driver-for-public-release.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/attestation-signing-a-kernel-driver-for-public-release.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @rubu.

Sorry you're having problems with this. Please: 
1.	Sign into your hardware dev center account.
2.	Then, open a Hardware Dev Center support case for investigation via the support link you'll find at 
[https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-dashboard-faq). It's in this passage (sign in first):

How do I contact Partner Center Support?
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown.

Hope this helps.
Eliot
