### ISSUE TITLE
List of valid /os parameters is out of date

### ISSUE THREAD

**Issue by spbrogan** [MicrosoftDocs/windows-driver-docs#1386]
Newer tool versions show values like: 10_RS4_X64  The list here is out of date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0afbc04b-349a-57ed-eeb0-3d2cd28e359c
* Version Independent ID: de61f684-31d7-2de5-d66c-a3319f5198d9
* Content: [Inf2Cat - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/inf2cat)
* Content Source: [windows-driver-docs-pr/devtest/inf2cat.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/inf2cat.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by crobinso** [comment]
This can be closed, it was fixed by https://github.com/MicrosoftDocs/windows-driver-docs/commit/50b7b4b674aaecd2a3eaaf113e85660d5c1a1dc3
