### ISSUE TITLE
How to set Verifier Start / Verifier End isn't mentioned? 

### ISSUE THREAD

**Issue by bgianfo** [MicrosoftDocs/windows-driver-docs#1391]
The article talks about what Verifier Start / Verifier End does, but it doesn't mention how to set the different values.
I don't see it mentioned in the command line or the UI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78a51ad-e10b-0e20-5eca-35795b78c3e0
* Version Independent ID: 5c48aefd-ba8b-c3cc-8c3e-ff00f53ba005
* Content: [Special Pool - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/special-pool)
* Content Source: [windows-driver-docs-pr/devtest/special-pool.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/special-pool.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by lorihollasch** [comment]
@bgianfo , thanks for your issue - apologies for being so slow to respond! I've added a link that takes you to a page describing how to use DV Verifier Start / Verifier End.
