### ISSUE TITLE
Documentation of || (System Syntax)

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [MicrosoftDocs/windows-driver-docs#140]
The documentation of || (System Syntax) hardly explains how a new system is created or attached to. Even the topic "Debugging Multiple Targets" does not give an example.

One way of creating a new system is the `.opendump` command. Maybe this could be mentioned at least.

Using `.opendump` in a live debugging session has some consequences [I described on StackOverflow](https://stackoverflow.com/questions/44318299/switching-the-system-does-not-work), especially because `.opendump` requires `g` which runs the live system. Thus it needs freezing of threads first, then opening the dump, run, then unfreeze.

**Comment by tedhudek** [comment]
@DOMARS please take a look

**Comment by DOMARS** [comment]
Thanks for this input. I will take a look at the topics and do some testing with WinDbg multiple targets.

**Comment by DOMARS** [comment]
I updated these topics to include more information.
- || (System Syntax) 
- ||s (Set Current System)
- Debugging Multiple Targets
As I worked on this, I see how not running the go command can lead to a confusing situation, so I worked to highlight that.  
I added a simple example to the "Debugging Multiple Targets".  
Thanks again for the input.

**Comment by thomasw-mitutoyo-ctl** [comment]
Thanks for the updated documentation. I appreciate this new way of providing feedback via Github. I was not informed about the progress of the emails I sent to wsddocfb@microsoft.com. This way is so transparent.

**Comment by tedhudek** [comment]
So glad! We really like it too, it's great to hear from everyone and know what people care about

**Comment by DOMARS** [comment]
Closing issue, thanks again for the input.
