### ISSUE TITLE
"Cross-signed using a SHA-1 certificate issued prior to July 29, 2015"

### ISSUE THREAD

**Issue by GabeSJones** [MicrosoftDocs/windows-driver-docs#1402]
In the OS Support Summary table, under the "Cross-signed using a SHA-1 certificate issued prior to July 29, 2015" column and the "Windows 10" row, the entry is "No (as of Windows 10 1809)."  I have installed our entire 2015 driver stack on a clean, non-upgrade install of Windows 10 1809 x64 with Secure Boot enabled.  These drivers were all cross-signed with a SHA-1 certificate issued in 2013.  They all load and run with no problems.  There are no relevant notations in the Event Viewer.  Is the information presented in this table incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d3f097-d81b-66c2-4835-d63758687d34
* Version Independent ID: fe9d1cdd-966e-89b5-c66b-60531b0ec655
* Content: [Get a code signing certificate - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#windows-10-earlier-certificate-transition-signing)
* Content Source: [windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @GabeSJones.

Sorry that this sat. 

Yes, I believe the table is correct. For specific questions about your particular submission, Hardware Dev Center Support can investigate. To contact support and open a Hardware Dev Center support case for investigation, **first**, sign into your hardware dev center account, and **then** go to [https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq).

Find: 
 
**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). 

Once there, select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

Hopes this helps with future issues.
Eliot
