### ISSUE TITLE
updated?

### ISSUE THREAD

**Issue by berger4son** [MicrosoftDocs/windows-driver-docs#1406]
Is this still the current process/tools that are used to publish a driver in Windows Update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f1feac8-9136-7152-6e06-4b7f0576c79c
* Version Independent ID: 218a3f87-5632-8327-cb7a-44345095db75
* Content: [Manage driver distribution with shipping labels - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/manage-driver-distribution-by-submission#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/manage-driver-distribution-by-submission.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/manage-driver-distribution-by-submission.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @berger4son 
Yes, the documentation is current.  If you are experiencing failures on specific Shipping Labels during publishing, the Hardware Dev Center Support folks can help investigate.
1. **First**, sign into your hardware dev center account, and then 
2. Open a Hardware Dev Center support case for investigation. 
3. Go to 
[https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq)
and look for: 

**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.
