### ISSUE TITLE
The sequence is missing EvtDeviceSelfManagedIoFlush and purging of power-managed queues

### ISSUE THREAD

**Issue by rahul-ramadas** [MicrosoftDocs/windows-driver-docs#1409]
After EvtDeviceReleaseHardware and before EvtIoStop for non-power-managed queues, I believe there should be a call to EvtDeviceSelfManagedIoFlush and purging of power-managed queueues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3367207-d31a-2c58-332c-8e50cb89f73b
* Version Independent ID: 42d8fee2-41ce-b9db-99a4-c34c536ae8ab
* Content: [Surprise-Removal Sequence - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/surprise-removal-sequence#feedback)
* Content Source: [windows-driver-docs-pr/wdf/surprise-removal-sequence.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/surprise-removal-sequence.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
This is fixed.  Thanks @rahul-ramadas for calling this out, and thanks to @Shyamal-V for the screen grab of how it should look https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/surprise-removal-sequence
