### ISSUE TITLE
Optimizing registry keys

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1411]
This article is particularly for  windows driver developer, But i am end user , If possible  please give optimizing registry keys.
Thanks to  authors  for this article with clear explanation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08f32f67-6763-c51a-a20f-6077303faae5
* Version Independent ID: 9cfbf7d8-178f-669e-b869-15bcd232d03a
* Content: [Using Framework Registry-Key Objects - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/using-framework-registry-key-objects)
* Content Source: [windows-driver-docs-pr/wdf/using-framework-registry-key-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/using-framework-registry-key-objects.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the question @RAJU2529 and apologies for the delay.

This documentation is for commercial driver devs and people who are deploying drivers. For consumer driver issues, your best bet is to look at the Microsoft Help topics that are on support.microsoft.com.

Sorry that I can’t offer you something more specific than that.  Best of luck with your issue.
