### ISSUE TITLE
Why driver test  done on remote computer

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1413]
I use  standardalone computer , is it possible  to test drivers  which are  already  installed by me?  . drivers  inf files  are located in C:\Windows\INF\  and  system .sys  files  are located in 
C:\Windows\System32\Drivers\

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4847662f-f333-d230-2a3a-192400d7ee0a
* Version Independent ID: a452721c-59aa-1cd9-98e3-afdbe4dbd4c6
* Content: [Testing a Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/testing-a-driver)
* Content Source: [windows-driver-docs-pr/develop/testing-a-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/testing-a-driver.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by DOMARS** [comment]
@RAJU2529 - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

This feedback mechanism is for requests about the documentation. Thanks!
