### ISSUE TITLE
Allow the  users to download  Video  demonstations  .mp4 format

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1414]
I watched  that video , voice  in video is  excellent and  author explained only one test . 
I am requesting all the authors , if  possible  add  the  all most  all videos in .mp4 format.

Thanks for the article . Good luck to all authors   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4847662f-f333-d230-2a3a-192400d7ee0a
* Version Independent ID: a452721c-59aa-1cd9-98e3-afdbe4dbd4c6
* Content: [Testing a Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/testing-a-driver)
* Content Source: [windows-driver-docs-pr/develop/testing-a-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/testing-a-driver.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the suggestion @RAJU2529 but we don't currently have resources to modify or transcode these videos.
