### ISSUE TITLE
Create shipping label get error.

### ISSUE THREAD

**Issue by hatasum** [MicrosoftDocs/windows-driver-docs#1417]
https://docs.microsoft.com/zh-tw/windows-hardware/drivers/dashboard/create-a-new-shipping-label
We cannot create shipping label by API.
Return error : readOnlyProduct, Not allowed to create the shipping labels on a read only product.
But the product's permission is "Publisher", not "Read-only".

How to create shipping label which product's permission is "Publisher"?
Thanks for your help.

**Comment by EliotSeattle** [comment]
Hi @hatasum.
I am sorry that you're having this problem. While I handle documentation issues, I do know the folks who can give you support with the tools. To get some help: 

1.	Sign into your hardware dev center account, and **_then_** 
2.	Open a Hardware Dev Center support case for investigation. On the support link, [https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq),
Find

**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). 

On the support page, select **Contact us**, --> **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown.
