### ISSUE TITLE
Incorrect claim that Express edition of VS can be used

### ISSUE THREAD

**Issue by JensMertelmeyer** [MicrosoftDocs/windows-driver-docs#1420]
This document states
> you can use Microsoft Visual Studio Express for Windows to create UWP device app

I believe this is not true, you can not develop for UWP with Visual Studio **Express**.

https://visualstudio.microsoft.com/de/vs/express/
clearly states:
> there will not be a UWP or Web offering of Visual Studio Express 2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a424abf-1112-f9dc-1973-a35363d261ee
* Version Independent ID: 523c8d5b-114c-a916-3992-0e364187db5a
* Content: [Getting started with UWP device apps - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/getting-started#feedback)
* Content Source: [windows-driver-docs-pr/devapps/getting-started.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/getting-started.md)
* Product: **windows-hardware**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks @JensMertelmeyer 
Looks like someone made a general upgrade edit changing 2015-->2017. That didn't apply in this case. I've made the correction.
