### ISSUE TITLE
1A bugcheck ,paramter 1=0x3f

### ISSUE THREAD

**Issue by jammgit** [MicrosoftDocs/windows-driver-docs#1422]
An inpage operation failed with a CRC error. Parameter 2 contains the pagefile offset. Parameter 3 contains the page CRC value. Parameter 4 contains the expected CRC value.

The question is:

Does the Parameter 2 indicate byte or sector? offset from MBR or DBR or file header ?

**Comment by jammgit** [comment]
Is anybody there ?

**Comment by DOMARS** [comment]
@jammgit - Sorry you are having this issue. Can you open this issue against a specific docs topic?
