### ISSUE TITLE
PsGetCurrentProcess link is broken

### ISSUE THREAD

**Issue by snowkoan** [MicrosoftDocs/windows-driver-docs#1424]
Hello,

There are two links to PsGetCurrentProcess on this page, and both are broken.

Broken link:
https://msdn.microsoft.com/library/windows/hardware/ff559933

Working link (from other pages):
https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/mm-bad-pointer#psgetcurrentprocess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349ffd5c-3a01-7f70-0d66-662e8b998fbe
* Version Independent ID: f75e1f93-b0ca-2975-64b7-9b6dc79ef88b
* Content: [Windows kernel opaque structures - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/eprocess)
* Content Source: [windows-driver-docs-pr/kernel/eprocess.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/eprocess.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Fixed in the source. Will be live shortly.
Thanks for the catch, @snowkoan!!
