### ISSUE TITLE
WPP_CLEANUP的问题

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/windows-driver-docs#1425]
在开启驱动程序校验器的情况下，在驱动入口加载驱动失败而没有调用WPP_CLEANUP，反而说是在驱动卸载的时候没有调用WPP_CLEANUP。

这个说法有点坑人啊！

**Comment by EliotSeattle** [comment]
Hello @kouzhudong 
What page are you referencing here? I'm don't understand what you're saying without knowing the page.

Thanks,
@EliotSeattle

**Comment by kouzhudong** [comment]
应该是提交给windbg的帮助文档。

**Comment by kouzhudong** [comment]
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xc4--driver-verifier-detected-violation

应该提交到这里。

**Comment by EliotSeattle** [comment]
I see that this was opened as #1623 in that topic, so I am going to close this as a duplicate Issue.
