### ISSUE TITLE
"COMPort Database Support Routines." link is broken

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#1427]
"COMPort Database Support Routines." link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d90238f-192a-9b79-996d-78c15adee0ec
* Version Independent ID: 7199df26-ea66-cff5-1487-db0263d207dc
* Content: [COM Port Database - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/serports/com-port-database)
* Content Source: [windows-driver-docs-pr/serports/com-port-database.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/serports/com-port-database.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Thanks, @Shyamal-V 
This is fixed in PR #97, Added COMPort database support routines, per Issue #1427
