### ISSUE TITLE
How to start the GpioClx driver?

### ISSUE THREAD

**Issue by wanglei1355** [MicrosoftDocs/windows-driver-docs#1436]
Since I failed to run the sample drivers in "simgpio" project on Win10, I examined the drivers already loaded in to kernel. But I cannot find the GpioClx driver "msgpioclx.sys" in the running kernel. I suppose there would be some configurations for GpioClx. So how to start the GpioClx? Could anyone give me some suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b3adf7f-14f1-28f3-b7f8-5f33e82e52cc
* Version Independent ID: 48ad43d7-cc64-0594-75ec-47cb876c95fc
* Content: [General-Purpose I/O (GPIO) Driver Design Guide - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gpio/)
* Content Source: [windows-driver-docs-pr/gpio/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gpio/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @wanglei1355 

Have you looked at [Driver Support Methods in the GpioClx DDI](https://docs.microsoft.com/windows-hardware/drivers/gpio/driver-support-methods-in-the-gpioclx-ddi)? I think what you're looking for may be in that topic.
Eliot
