### ISSUE TITLE
Missing atls.lib when building V4 printer driver

### ISSUE THREAD

**Issue by ChrisBlood** [MicrosoftDocs/windows-driver-docs#1437]
Following the instructions to build the V4 Printer Driver and it fails to link because it cannot open atls.lib. I have updated Visual Studio, re-installed it but it still fails to fins the file. The file does exist in the install directory but the liker cannot locate it

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. You may have success posting your questions about linking **atls.lib** when building a v4 printer driver in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
