### ISSUE TITLE
HID specification link broken

### ISSUE THREAD

**Issue by dpmm99** [MicrosoftDocs/windows-driver-docs#1439]
Maybe it should point to https://www.usb.org/hid rather than directly to a PDF, but the PDF's URL is https://www.usb.org/sites/default/files/documents/hid1_11.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36318bc-76cd-c372-d676-4a0c20b60dcf
* Version Independent ID: b02eaae7-3cb2-25d1-6dc4-d90e99385ebb
* Content: [HID drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/#feedback)
* Content Source: [windows-driver-docs-pr/hid/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @dpmm99.
I changed the link to usb.org rather than the specific spec. Should be live later today. 
In the future, it'd be great if you make the change and submit a PR for it. ;-)
I appreciate your help and interest in the docs!!
Eliot
