### ISSUE TITLE
link to referenced videos

### ISSUE THREAD

**Issue by rickfleischer** [MicrosoftDocs/windows-driver-docs#1440]
This video mentions at least two other videos covering specific topics.  I don't see any links to them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f09a03ab-3e37-3bcb-9727-b300ae82c15e
* Version Independent ID: b7142a24-32b2-166d-3427-b87a8c69c0e3
* Content: [Developing, Testing, and Deploying Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/)
* Content Source: [windows-driver-docs-pr/develop/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback, @rickfleischer, and apologies for the delay.  I watched the video and heard two, code analysis w drivers and provisioning a target computer.  But my searches did not turn up video for these two.

I did, however, go ahead and create a list of the other 7 pages in the driver docs that *do* contain videos, and I added the list in 6651107e86ddbbdeffe085ed6c5edd93ded65812.  You can now see on the live site at https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/.

Hope this helps!
