### ISSUE TITLE
Cannot install WDK extension

### ISSUE THREAD

**Issue by Furqan136** [MicrosoftDocs/windows-driver-docs#1444]
It says my currently installed applications are unsupported. I have Visual Studio 2019. It should be supported by now since its the stable version. Is there a workaround or I need to remove my VS 2019 and go back to VS 2017?

**Comment by EliotSeattle** [comment]
Hi @Furqan136,
Yes, VS 2019 is stable and works well, but there are some braking changes in the IDE in regard to working with the WDK. VS 2019 works well with the WDK for Windows 10 version 1903 (releasing soon) but not with earlier versions. See the blog post, [Windows Driver Kit (WDK) to support Visual Studio 2019](https://social.msdn.microsoft.com/Forums/en-US/b116571d-d5b2-4c1c-a43e-4b57171c8c41/windows-driver-kit-wdk-to-support-visual-studio-2019?forum=wdk) for some more information. 
Eliot
