### ISSUE TITLE
Please fix the date on this page

### ISSUE THREAD

**Issue by BKlamik-MSFT** [MicrosoftDocs/windows-driver-docs#1455]
This content arrived about a week ago, not on 4-19-2017. I'm away from the ability to sign-in & update this. Let's work on a better pull-request process that highlights such an inaccuracy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46117d19-5003-f697-e266-9404754fc134
* Version Independent ID: b6be0cc8-dd53-fc7a-0ffb-a06881e58428
* Content: [Container Support for non-DX APIs - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/container-non-dx)
* Content Source: [windows-driver-docs-pr/display/container-non-dx.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/container-non-dx.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **misaso**

**Comment by EliotSeattle** [comment]
Date changfed to 4/3/19
