### ISSUE TITLE
Typo: "Highlightighting"

### ISSUE THREAD

**Issue by malcolms** [MicrosoftDocs/windows-driver-docs#1460]
Looks like a stray "tight" has crept into "Highlighting" in the section title for https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-using-windbg-preview#highlightighting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1e093f9-7df0-17ab-71ae-8af9003ee041
* Version Independent ID: 55ed6fd3-a7a6-f7d5-2a8e-fbf6cc6e2c7b
* Content: [Debugging Using WinDbg Preview - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-using-windbg-preview#feedback)
* Content Source: [windows-driver-docs-pr/debugger/debugging-using-windbg-preview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugging-using-windbg-preview.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Thanks, @malcolms 
Highlightighting is a new feature in which the dominant color is reinforced by water mark and washed in a batik pattern.
Just kidding. Thanks for the catch. I've made the change. Should be live shortly. We're examining if we should scrap our spellchecker for a newer model. </ok-end-humor>
But it's really fixed. Thanks!
Eliot
