### ISSUE TITLE
WDK download and VS2019

### ISSUE THREAD

**Issue by billziss-gh** [MicrosoftDocs/windows-driver-docs#1461]
The WDK download [page](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) still points to Visual Studio 2017. This page needs to be updated to point to latest WDK with Visual Studio 2019 support.

(VS2019 has been out for well over a week now.)

**Comment by EliotSeattle** [comment]
Hi @billziss-gh.
Thanks for the feedback. The changes are part of the [insider build versions](https://docs.microsoft.com/windows-hardware/drivers/installing-preview-versions-wdk) and will be incorporated into the page for the released versions very soon.
Eliot
