### ISSUE TITLE
Needs more information regarding drivers and detection

### ISSUE THREAD

**Issue by metalpizza123** [MicrosoftDocs/windows-driver-docs#1464]
Default APO doesn't have documentation about whether it only applies to stereo ONLY output i.e. if I listen to 5.1 output with speaker fill, does the speaker fill matrix also work on that? What if I'm listening to multiple sources, from mono to stereo to 5.1? Since most consumer PCs use Realtek drivers, prerequisite software links would helpful, as well as backwards support for older motherboard manufacturers who have since out-of-life old drivers. This is also (as far as I know, tested 14/04/2019 build 17763.437) inaccessible directly from the new settings panel and only through legacy control panel and device manager (which is linked in related settings).  OS doesn't auto-detect 5.1 setup and query user to check/run setup, resulting in content all running in 2.1 with speaker fill off. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62f1e240-524c-5cf3-0172-daa57ba2bf65
* Version Independent ID: 44e9d17d-03ca-f4ee-9f49-1a86379b849f
* Content: [Speaker Fill - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/speaker-fill#feedback)
* Content Source: [windows-driver-docs-pr/audio/speaker-fill.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/speaker-fill.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@metalpizza123 - The docs team is limited in size, so at this point we do not have the resources to describe more detail about the default APO that is shipped in the different versions of Windows. 

If you have product feedback on the changes to the audio UI, use the product feedback tool ("Feedback Hub" in apps) in Windows to provide input there.

Thank you for your interest in the Windows audio driver development documentation and good luck with your work.
