### ISSUE TITLE
Could you please finish the get_PropertyRange() function?

### ISSUE THREAD

**Issue by sun-xm** [MicrosoftDocs/windows-driver-docs#1465]
Could you please finish the get_PropertyRange() function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f66b118d-0ac1-19cf-7287-627a40246f47
* Version Independent ID: aba19245-f30c-3593-f086-2e14ced65e6d
* Content: [Sample Extension Unit Plug-in DLL - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/sample-extension-unit-plug-in-dll#feedback)
* Content Source: [windows-driver-docs-pr/stream/sample-extension-unit-plug-in-dll.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/stream/sample-extension-unit-plug-in-dll.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question about what additional code the IHV can add to the get_PropertyRange() function in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
