### ISSUE TITLE
I  have  little  confusion 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1470]
I  don't know  whats  the  image  and  image path .
I don't  have  image 

I have  symbolpath   C:\Symbols
I have  dump file path   D:\dump\memory.dmp
But I could not  find  the image path , and I don't know where to download  image .

Please  guide  me in this  case . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d057c4-e0cf-9c28-cf81-68d89abf76fe
* Version Independent ID: 268f1bb7-14b2-7c50-bc00-c216be8711b5
* Content: [Analyzing a Kernel-Mode Dump File with WinDbg - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/analyzing-a-kernel-mode-dump-file-with-windbg#feedback)
* Content Source: [windows-driver-docs-pr/debugger/analyzing-a-kernel-mode-dump-file-with-windbg.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/analyzing-a-kernel-mode-dump-file-with-windbg.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@RAJU2529 - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

Image path is described in the linked WinDbg command line topic.

-i ImagePath
Specifies the location of the executables that generated the fault. If the path contains spaces, it should be enclosed in quotation marks.
