### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rusinghmsft** [MicrosoftDocs/windows-driver-docs#1471]
The miniport driver routines explained has a typo. HW_UNIT_CONTRO should be HW_UNIT_CONTROL.

https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/storport-driver-miniport-routines

**Comment by EliotSeattle** [comment]
Fixed and live. Thanks, @rusinghmsft

**Comment by rusinghmsft** [comment]
No problem. Lori showed us how to create a PR ourselves. I'll do that the nest time.
