### ISSUE TITLE
Uninstall with INF file?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1473]
How, EXACTLY is a minifilter's DefaultUninstall section called? Right-clicking on an INF in Explorer does NOT provide an Uninstall option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae58da8-5649-102b-5241-cd247f48e310
* Version Independent ID: 051d9945-7e4b-1d88-f043-73d9a67b8352
* Content: [Creating an INF File for a File System Filter Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/creating-an-inf-file-for-a-file-system-filter-driver)
* Content Source: [windows-driver-docs-pr/ifs/creating-an-inf-file-for-a-file-system-filter-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/creating-an-inf-file-for-a-file-system-filter-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@briancatlin, you are correct that Windows Explorer does not provide a right-click option for Uninstall. You'll find uninstall information documented on "[Using an INF File to Uninstall a File System Filter Driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/using-an-inf-file-to-uninstall-a-file-system-filter-driver)" (the no-right-click-for-uninstall is mentioned there).
