### ISSUE TITLE
Extension driver inf targets on Windows update for Windows 10 in S mode. But extension driver inf can be downloaded on non-Win10 S OS.

### ISSUE THREAD

**Issue by LiaoMichelle** [MicrosoftDocs/windows-driver-docs#1477]

**Comment by LiaoMichelle** [comment]
Base and Extension driver inf are target on Windows update for Windows 10 in S mode.
But only extension driver inf can be downloaded on non-Win10 S OS.
Is that behavior correct?

**Comment by tedhudek** [comment]
Hi @LiaoMichelle thanks for the feedback and apologies for the delay.

Can you please clarify your question?  You have a base INF and extension INF, both targeting Windows 10 in S mode.  Are you asking if the extension INF will be installed on 10 S machines?

**Comment by LiaoMichelle** [comment]
Hi Ted,
I am asking why extension INF was installed  on "Non" win10 S machines?
Thanks

**Comment by tedhudek** [comment]
So you are targeting Windows 10 S, and base and extension INF are installed on 10 S successfully, and in addition, extension INF (but not base INF) is installed on Win10 desktop?

**Comment by LiaoMichelle** [comment]
Yes, in addition, extension INF (but not base INF) is installed on Win10 desktop.

**Comment by tedhudek** [comment]
What is your desired result?  Do you want both base and extension installed on Win10 desktop?  Or neither?

**Comment by tedhudek** [comment]
@LiaoMichelle I've added two sections to https://docs.microsoft.com/en-us/windows-hardware/drivers/install/windows10sdriverrequirements that should help with your problem.  Please see **Installation** and **Troubleshooting installation** on that page.  Closing the issue for now, please reopen if needed.
