### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1479]
The link under Applications and Services is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121aa225-1cb9-deec-58c0-48dcb226edfe
* Version Independent ID: 8f308c6b-52b5-08b8-6ea1-b29b6d343aa7
* Content: [USB device-side drivers in Windows - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-device-side-drivers-in-windows)
* Content Source: [windows-driver-docs-pr/usbcon/usb-device-side-drivers-in-windows.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-device-side-drivers-in-windows.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by billlattimer** [comment]
@BrianCatlin, thank you for catching this; links corrected.
