### ISSUE TITLE
Unclear on what this is

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1480]
I've taught and written USB drivers for 20 years, and this page is completely unclear on what UFX is. Just stating that UFX is a "function controller driver" is meaningless, because all those words are heavily overloaded. What is really needed is an end-to-end diagram showing a standard Windows host DevStack communicating over USB to a "device" (running Windows) with a UFX driver.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f086a79-594a-46de-cafe-3d72b102eaf9
* Version Independent ID: 0c76afb9-c6d1-3f69-5a45-a44e0b6878b6
* Content: [Developing Windows drivers for USB function controllers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/developing-windows-drivers-for-usb-function-controllers)
* Content Source: [windows-driver-docs-pr/usbcon/developing-windows-drivers-for-usb-function-controllers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/developing-windows-drivers-for-usb-function-controllers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by Shyamal-V** [comment]
The "Architecture of UFX" section of the page provides a link to the architectural block diagram and components of the function stack. @duncanmacmichael  it may help to add a short introduction to clarify what UFx means/enables and a note under "Architecture of UFX" that an architectural block diagram is available at https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-device-side-drivers-in-windows

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
