### ISSUE TITLE
Nearly useless

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1481]
This is pretty much useless for writing an application that uses GenericUSBFn. There are more than a dozen IOCTLs for GenericUSBFn. Why aren't they covered? Why isn't there a sample application that implements a simple device function? Should some of these IOCTLs be sent synchronously? Some asynchronously? 

Why should the application writer have to flail about to figure out how this works? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab78a743-0b21-6fcb-259c-f7124a5103a1
* Version Independent ID: 4c6e4bd7-e781-dc1a-c9d1-57ca5fcb8b51
* Content: [Communicating with GenericUSBFn.sys from a user-mode service - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/user-mode-services-ufx)
* Content Source: [windows-driver-docs-pr/usbcon/user-mode-services-ufx.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/user-mode-services-ufx.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
