### ISSUE TITLE
drivers must be signed by the Windows Hardware Dev Center Dashboard

### ISSUE THREAD

**Issue by tesonwang** [MicrosoftDocs/windows-driver-docs#1483]
Does it mean we need to submit the driver to be signed every time if we rebuild the driver or release new version of the driver?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ca4e93-a34c-abbc-0ebc-9b5195378b20
* Version Independent ID: f2e19c4f-44cf-e0d4-2143-1e2129c582c9
* Content: [Driver Signing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/driver-signing#feedback)
* Content Source: [windows-driver-docs-pr/install/driver-signing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/driver-signing.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback @tesonwang, apologies for the delay.  To release a new version of your driver, yes, you need to get the new version signed.  For testing, you can use test signing, as described on https://docs.microsoft.com/en-us/windows-hardware/drivers/install/how-to-test-sign-a-driver-package.
