### ISSUE TITLE
The example of [Strings] section is wrong.

### ISSUE THREAD

**Issue by GreatFireWall** [MicrosoftDocs/windows-driver-docs#1484]
![image](https://user-images.githubusercontent.com/4510984/56633982-e7b26f80-6692-11e9-9677-20500129f9ab.png)

**If I remove the `%` around the string, it build success.**

![image](https://user-images.githubusercontent.com/4510984/56634077-2e07ce80-6693-11e9-8ea1-a3f852e358af.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d8a8e3-6cfb-a81c-667a-fa46bfab90ef
* Version Independent ID: 7d95e50a-ea7e-39e7-2740-410d82cc2054
* Content: [INF Files for Callout Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/inf-files-for-callout-drivers)
* Content Source: [windows-driver-docs-pr/network/inf-files-for-callout-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/inf-files-for-callout-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by billlattimer** [comment]
@GreatFireWall thank you for catching this; updated to correct section.
