### ISSUE TITLE
Advantage of using IoMmu over GpuMmu

### ISSUE THREAD

**Issue by xavierajith** [MicrosoftDocs/windows-driver-docs#1487]
I understand IoMmu shares page table but GpuMmu has its own page tables. Is there any other advantage of one virtual model over other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202d9023-34b6-cad5-9be6-84a686847d12
* Version Independent ID: e344ce52-7f36-605d-6208-25c1a2627854
* Content: [Per-process GPU virtual address spaces - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/per-process-gpu-virtual-address-spaces#feedback)
* Content Source: [windows-driver-docs-pr/display/per-process-gpu-virtual-address-spaces.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/per-process-gpu-virtual-address-spaces.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@xavierajith , I ran your question past the dev team and have provided additional information regarding advantages/disadvantages to this page: [GPU virtual memory in WDDM 2.0](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/gpu-virtual-memory-in-wddm-2-0
). Thanks for asking!
