### ISSUE TITLE
16425

### ISSUE THREAD

**Issue by vrbear** [MicrosoftDocs/windows-driver-docs#1488]
16425 should mean %SystemRoot%\SysWOW64
16426 should mean %ProgramFiles(x86)%
16428 should mean %ProgramFiles(x86)%\Common

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26eb7202-d5c4-fb53-a652-6f2c320e3463
* Version Independent ID: ec9ba408-ffea-e0d2-bbca-067cadbd433d
* Content: [Using Dirids - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-dirids#feedback)
* Content Source: [windows-driver-docs-pr/install/using-dirids.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/using-dirids.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the suggestion @vrbear and apologies for the delay.  This will be updated within a few minutes. Next time note that you can click Edit on the original doc page and propose a PR, if you like.
