### ISSUE TITLE
Problem with certificate's CA root cert (Comodo) is not in the approved list of root certs

### ISSUE THREAD

**Issue by haicon232** [MicrosoftDocs/windows-driver-docs#1489]
Hi there, I want to register your Hardware Program for our drivers.
However, when submitting our certificate on your system, I received the error : "Your certificate's CA root cert is not in the approved list of root certs
Your code signing certificate's CA is not in the approved list of root certs. Please get a certificate from one of the certificate authorities listed on the code signing registration page.""

We use the Comodo certificate (Sectigo at the moment) 
In this link,  https://docs.microsoft.com/vi-vn/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#extended-validation-code-signing-certificates , I see that your list contains Sectigo.

Please answer why my submission is unsuccessful. 

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 93d3f097-d81b-66c2-4835-d63758687d34
* Version Independent ID: fe9d1cdd-966e-89b5-c66b-60531b0ec655
* Content: [Get a code signing certificate - Windows drivers](https://docs.microsoft.com/vi-vn/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @haicon232.

Sorry that you're having trouble with your certificate. The Hardware Dev Center Support folks can help you investigate the cause.

1. **First**, sign into your hardware dev center account, and then 
2. Open a Hardware Dev Center support case for investigation. 
3. Go to 
[https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq)
and look for: 

**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

Best of luck,
Eliot
