### ISSUE TITLE
Parameter error for Locals

### ISSUE THREAD

**Issue by bahuwang** [MicrosoftDocs/windows-driver-docs#1491]
When I use  WinDbg Preview ,the locals show information parameter error 0x80070057. 
os : win10 home 17763.437
debugger client version :1.0.1902.07001
debugger engine version :10.0.18317.1001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1e093f9-7df0-17ab-71ae-8af9003ee041
* Version Independent ID: 55ed6fd3-a7a6-f7d5-2a8e-fbf6cc6e2c7b
* Content: [Debugging Using WinDbg Preview - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-using-windbg-preview)
* Content Source: [windows-driver-docs-pr/debugger/debugging-using-windbg-preview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugging-using-windbg-preview.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
This feedback mechanism is for requests about the documentation. Thanks!
