### ISSUE TITLE
syntax error in example

### ISSUE THREAD

**Issue by clouds56** [MicrosoftDocs/windows-driver-docs#1496]
* missing comma in parameter list
* missing definition of config

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3929d57-7b4a-998e-a208-8c6deacbb7be
* Version Independent ID: d78360b6-4be2-7c8f-8f28-b8d7f49f5830
* Content: [Porting DriverEntry - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/porting-driver-entry)
* Content Source: [windows-driver-docs-pr/wdf/porting-driver-entry.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/porting-driver-entry.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the suggestion @clouds56 this will be updated within a few minutes.  Next time note that you can click Edit on the original doc page and propose a PR, if you like
