### ISSUE TITLE
Driver Attestation Signing failure

### ISSUE THREAD

**Issue by CKroid** [MicrosoftDocs/windows-driver-docs#1503]
We tried to submit our extension driver for Attestation Signing but hit into the following error:
InfVerif failed for Driver. Partial Log:Error 1384 in XXX.inf, line 557 : Cannot specify filters with registry or property in extension INFs, use [DDInstall.Filters] section

The error led me to this article.
If I understand this article correctly, the change will involve both base driver and extension driver and cannot be achieve through extension driver alone?

Another question is if we use this new approach, will the driver still work on Windows 10 version prior to 1903? Our driver still need to support older versions of Windows 10.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beda320d-335b-af60-68ae-06572e880948
* Version Independent ID: 7f930510-0f6d-d114-8d4d-364de97963bd
* Content: [Device filter driver ordering - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/device-filter-driver-ordering)
* Content Source: [windows-driver-docs-pr/develop/device-filter-driver-ordering.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/device-filter-driver-ordering.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @CKroid yes, you'll need to make changes to both Extension and Base INF.  Base INF needs to specify what to do with the levels.

See info at the bottom of the doc page for the older ("legacy") Windows versions.  Use that method to target version of Windows before 1903.

cc @selerner
