### ISSUE TITLE
[LOC] "アプリ & 機能" needs to be replaced with "アプリと機能"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-driver-docs#1504]
https://docs.microsoft.com/ja-jp/windows-hardware/drivers/debugger/debugger-download-tools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162fe2fe-9216-f4c5-9f91-3df8776bb99e
* Version Independent ID: 013dbf6b-0790-9c11-24f4-dbf24d64401e
* Content: [Download Debugging Tools for Windows - WinDbg - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
* Content Source: [windows-driver-docs-pr/debugger/debugger-download-tools.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugger-download-tools.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@EliotSeattle - I think this is a localization issue. Can you provide guidance on how to best direct this request if we are setup to handle this?

**Comment by EliotSeattle** [comment]
Reached out to the loc team to see how we handle this process. We have steps in place for the loc team to reach out to the core doc team, but not the other way around. Will add comments as I learn more.

**Comment by EliotSeattle** [comment]
@v-nidolc 
Can you please route this to the right person?

**Comment by v-nidolc** [comment]
@EliotSeattle can you assign the issue to davidprio? Then our vendor will process it. Thanks!

**Comment by EliotSeattle** [comment]
@DavidPrio has this been taken care of?
Thanks,
Eliot

**Comment by hyoshioka0128** [comment]
@EliotSeattle - Thanks.
Fixd.
Close #1504
