### ISSUE TITLE
Example response body has duplicated key

### ISSUE THREAD

**Issue by rosamariaramirez** [MicrosoftDocs/windows-driver-docs#1507]
The given example of response body has duplicated "productName" key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24518ab0-bd10-1a04-f3a0-1ba754409841
* Version Independent ID: ad632005-a43b-8d81-c4ef-8730d59b4363
* Content: [Create a new product - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/create-a-new-product#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/create-a-new-product.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/create-a-new-product.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @balapv
* Microsoft Alias: **balapv**

**Comment by tedhudek** [comment]
Looks like this one was fixed.  Thanks for the report @rosamariaramirez and apologies for the delay.
