### ISSUE TITLE
Unable to install WDK with VisualStudio 20019

### ISSUE THREAD

**Issue by tyszja** [MicrosoftDocs/windows-driver-docs#1511]
According to the [instructions](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#feedback) it should be enough to install VS2019 with C++ support for Windows desktop apps before installing the WDK, but the installer refuses to continue due to missing compatible SDK and points me to the SDK installer. Visual Studio installer shows that I already have the Windows 10 SDK installed. What am I missing? Do I need to download additioanal ~3gigs of SDK in a different location to get the WDK installer to work or is this a different Windows SDK than the VS2019 has? Do I need any other SDKs to get the driver examples to compile?

Regards.

**Comment by tedhudek** [comment]
Feedback pertains to https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#feedback.

**Comment by EliotSeattle** [comment]
We've updated the download process to avoid troubles like this. Sorry about the delay.
