### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by richardhendricks** [MicrosoftDocs/windows-driver-docs#1513]
Update Rate is by default 5 seconds and cannot be updated.

But you can force an immediate update by pressing some keys. This can be a problem since it means you can't screenclip just the window - ALT forces an update, but PrintScreen does not. If you defocus the screen first, it does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9798970e-6e11-18f9-2070-94aa65475d83
* Version Independent ID: eec1848b-3da8-4b18-a581-e4d6030535e2
* Content: [PoolMon Display - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/poolmon-display#feedback)
* Content Source: [windows-driver-docs-pr/devtest/poolmon-display.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/poolmon-display.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @richardhendricks, for the info.
I'll update the topic today, and the change will be live on Monday.
