### ISSUE TITLE
IoT supported?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1518]
Are dual-role stacks supported on Win IoT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f9a763d-3e64-04a6-c3a1-8e353106d0d6
* Version Independent ID: d95fe8df-f3c5-eebd-c324-7940a12fe954
* Content: [USB Dual Role Driver Stack Architecture - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-dual-role-driver-stack-architecture#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/usb-dual-role-driver-stack-architecture.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-dual-role-driver-stack-architecture.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Good question, @BrianCatlin. I believe that the APIs involved with dual-role stacks are Universal, implying they would work on an IoT device, but let me get confirmation from the USB team on that.

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
