### ISSUE TITLE
Needs LOTS more detail

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1519]
1. Please explain why a WDFDEVICE and a UFXDEVICE is needed?
2. When I create a WDFDEVICE is it the FDO, or a filter? The docs (https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/developing-windows-drivers-for-usb-function-controllers) indicate that Ufx010000.sys creates the FDO.
3. Please describe the rationale for having a UFXDEVICE and a WDFDEVICE, and what data would typically be in each object's context area
4. The Initialization section needs LOTS more detail! For example, where would a driver call UfxDeviceNotifyHardwareReady? From DeviceAdd, PrepareHardware, D0Entry, etc?
5. Will our driver get IOCTLs from applications, or just internal IOCTLs from the class library?
6. There really needs to be a SIMPLE minimal functioning sample for a software-only device that implements a few endpoints that works (unlike the current sample), to demonstrate how to write a UFX driver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4458225b-56bb-77f0-2378-97e8dd442ef9
* Version Independent ID: a5ed7881-cace-9b0e-ff8c-b356e8969feb
* Content: [Write a function controller client driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/function-client-driver)
* Content Source: [windows-driver-docs-pr/usbcon/function-client-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/function-client-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
