### ISSUE TITLE
*.msu not found, the doc description incorrect

### ISSUE THREAD

**Issue by GreatFireWall** [MicrosoftDocs/windows-driver-docs#1520]
No any `.msu`

![image](https://user-images.githubusercontent.com/4510984/57150923-2c13dd00-6e02-11e9-9536-2fc5db3c0d0e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad07ea10-b00f-48cd-534d-b1ad1bfaa44b
* Version Independent ID: 41c511f9-54b4-07df-d0a5-c2f547fdf293
* Content: [Redistributable Framework Components - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/installation-components-for-kmdf-drivers)
* Content Source: [windows-driver-docs-pr/wdf/installation-components-for-kmdf-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/installation-components-for-kmdf-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @GreatFireWall thanks for the feedback and apologies for the delay.  Your question caused us to revise two doc pages significantly, to include the info you request, and to clarify other versioning scenarios.  So thank you for starting this process!

Please see the updates here:

https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/installation-components-for-kmdf-drivers

https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/building-and-loading-a-kmdf-driver
