### ISSUE TITLE
Not helpful

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1524]
1. If these values are required, why doesn't the .INF for the sample UfxClientSample driver set them?
2. This is far too complex and has too many possible interpretations. It desperately needs several examples!
3. Why are there "&lt;strong&gt;" tags in the text?
4. How do we know whether we need the various values put in the registry? There isn't anything that describes the decision making process.
5. What are the minimum required values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d77bb000-e08d-2d41-5b0a-26ec068f67d5
* Version Independent ID: a09fcd64-2254-6a81-4200-727456cc90c2
* Content: [USB registry settings for a function controller driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-registry-settings-for-a-function-controller-driver)
* Content Source: [windows-driver-docs-pr/usbcon/usb-registry-settings-for-a-function-controller-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-registry-settings-for-a-function-controller-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
