### ISSUE TITLE
Class Driver Notification?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1525]
This page is ostensibly about writing a UFX client driver. What exactly is the section Class Driver Notification about? It doesn't make any sense in its current location. What "class driver" is it describing? How does this relate to the client driver?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4458225b-56bb-77f0-2378-97e8dd442ef9
* Version Independent ID: a5ed7881-cace-9b0e-ff8c-b356e8969feb
* Content: [Write a function controller client driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/function-client-driver)
* Content Source: [windows-driver-docs-pr/usbcon/function-client-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/function-client-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
