### ISSUE TITLE
Standard Control Transfers

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1527]
This section does not fully describe how the client driver is supposed to process setup packets. It reads "If there is data associated with the control transfer, UFX reads from and writes to the default control endpoint as appropriate." How exactly is this done? What must the client driver do to implement this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4458225b-56bb-77f0-2378-97e8dd442ef9
* Version Independent ID: a5ed7881-cace-9b0e-ff8c-b356e8969feb
* Content: [Write a function controller client driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/function-client-driver)
* Content Source: [windows-driver-docs-pr/usbcon/function-client-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/function-client-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
