### ISSUE TITLE
18362.1 WDK sesnsordiagnostic.exe Deprecated

### ISSUE THREAD

**Issue by NeoBeum** [MicrosoftDocs/windows-driver-docs#1535]
WDK SensorDiagnosticTool.exe Deprecated.
[https://docs.microsoft.com/en-us/windows-hardware/drivers/sensors/test-your-universal-sensor-driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/sensors/test-your-universal-sensor-driver)

18362.1 WDK executable does not create test window.
Tool replaced by the following Microsoft Store Appx as per linked page above.
[SensorInfo.appx](https://www.microsoft.com/en-us/p/sensorinfo/9wzdncrfjqwf?activetab=pivot:overviewtab)
PackageFullName: 26830TonyLin.SensorInfo_3.0.0.12_neutral__xzh44wb246sn4.appx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56d6beb9-e637-72df-4cae-a0d9a7275026
* Version Independent ID: e76d49c6-6a6d-1328-afdc-cdc77f05c92d
* Content: [Testing sensor functionality with the Sensor Diagnostic Tool - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/sensors/the-sensor-diagnostic-tool#feedback)
* Content Source: [windows-driver-docs-pr/sensors/the-sensor-diagnostic-tool.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/sensors/the-sensor-diagnostic-tool.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by billlattimer** [comment]
@NeoBeum thank you for calling this out; note added for the tool change, this content has been moved to "Previous Versions" and future updates to the topic area will be completed.
