### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by eliyasy** [MicrosoftDocs/windows-driver-docs#1537]
https://msdn.microsoft.com/windows-drivers/develop/how_to_select_and_configure_the_device_fundamental_tests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a158d639-25d2-9722-6862-abec4a682806
* Version Independent ID: cebe2e66-1f3c-ca20-82d5-387a08779225
* Content: [PnP Tests (Device Fundamentals) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/pnp-tests--device-fundamentals-#feedback)
* Content Source: [windows-driver-docs-pr/devtest/pnp-tests--device-fundamentals-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pnp-tests--device-fundamentals-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Fixed. Now points to https://docs.microsoft.com/windows-hardware/drivers/develop/how-to-select-and-configure-the-device-fundamental-tests. Should be live in a few minutes.

**Comment by eliyasy** [comment]
Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
