### ISSUE TITLE
Hardware for an emulated device?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1546]
I could be dead wrong, but isn't the point of emulating a device when there isn't any device hardware? This page doesn't make sense

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68a8677d-125b-fc2c-df08-94ade960fe90
* Version Independent ID: 1d6760fd-8f1e-cc09-651b-55134062e423
* Content: [Architecture of USB Device Emulation (UDE) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-emulated-device--ude--architecture)
* Content Source: [windows-driver-docs-pr/usbcon/usb-emulated-device--ude--architecture.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-emulated-device--ude--architecture.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
