### ISSUE TITLE
What is "client driver" in this context?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1547]
Is a client driver a USBFX driver? Is that the only "client driver"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306c96f2-d5cc-7327-b422-550b36be6d4a
* Version Independent ID: 3aabd82c-b4e3-fac6-6b98-b0220d7ee9c2
* Content: [USB client driver verifier - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/how-to-send-a-usb-device-to-select-suspend)
* Content Source: [windows-driver-docs-pr/usbcon/how-to-send-a-usb-device-to-select-suspend.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/how-to-send-a-usb-device-to-select-suspend.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @BrianCatlin,

I’ve created an internal work item for myself to investigate this with the USB team, and I’ll make a note here when I complete the changes. In the meantime, I’m closing the GitHub issue while it’s tracked in the bug. Thanks again for helping to improve the docs.
