### ISSUE TITLE
Latest details

### ISSUE THREAD

**Issue by eswarpabolu** [MicrosoftDocs/windows-driver-docs#1548]
Please provide link for the latest details... For win10 plus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5084d582-2aa6-6f44-5124-6138e41033d4
* Version Independent ID: f6a17419-252f-1e7f-1a77-853ca8013d9b
* Content: [Monitor Hot Plug Detection - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/monitor-hot-plug-detection#feedback)
* Content Source: [windows-driver-docs-pr/display/monitor-hot-plug-detection.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/monitor-hot-plug-detection.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@eswarpabolu , thanks for reporting this and sorry for the slow response. I have added a sentence clarifying the WDDM versions to which this info applies, and have filed an internal work item to provide updated information at a future time.
