### ISSUE TITLE
Step 4 Can't Add Key due to error "Please enter a unique URI no greater than 256 characters."

### ISSUE THREAD

**Issue by soul4soul** [MicrosoftDocs/windows-driver-docs#1549]
I am unable to complete step 4 which is to "Add new key". When I pressed "Add New Key" an error pops up under the "App ID URI" field that reads "Please enter a unique URI no greater than 256 characters."

I used the same "App ID URI"  for step 3 since it was needed to create the Azure AD App user.

In general this article was fairly confusing. I only have basic familiarity with Azure. It wasn't until I did a Bing search that I realized I had to log into the Azure Portal to make an Azure AD App first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ead14b61-61e5-d45f-d5c9-d3d4c0bcf93d
* Version Independent ID: 31c51703-a968-0a6a-bba0-bdb47619b018
* Content: [Hardware dashboard API - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/dashboard-api)
* Content Source: [windows-driver-docs-pr/dashboard/dashboard-api.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/dashboard-api.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @soul4soul 
For the failures you're experiencing, the Hardware Dev Center Support folks can help investigate.
1. **First**, sign into your hardware dev center account, and then 
2. Open a Hardware Dev Center support case for investigation. 
3. Go to 
[https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq)
and look for: 

**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

I hope they can get you straightened out quickly.

All the best.
Eliot
