### ISSUE TITLE
Add information to mention SDK and WDK must be the same version

### ISSUE THREAD

**Issue by soul4soul** [MicrosoftDocs/windows-driver-docs#1550]
VS2019 installer doesn't necessarily give a version of the SDK which is the same version as the WDK. I just went though the install process. VS2019 installer defaulted to give me version 10.0.17763.132. The WDK download link on this page provides version 10.0.18362.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@soul4soul - We have added information about having to select the WDK supported version of the SDK as part of the VS 2019 installation. Thank you for highlighting this issue that you were seeing.
