### ISSUE TITLE
Path of devcon.exe is incorrect

### ISSUE THREAD

**Issue by rajnishc8** [MicrosoftDocs/windows-driver-docs#1556]
at following link 
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-

change  C:\Program Files (x86)\Windows Kits\10.0\Tools\x64\devcon.exe
to          C:\Program Files (x86)\Windows Kits\10\Tools\x64\devcon.exe

Thanks,
--Rajnish

**Comment by EliotSeattle** [comment]
Got it! Thanks, @rajnishc8 !!
