### ISSUE TITLE
PageProtection

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1558]
If PageProtection is PAGE_EXECUTE, does that include all the various types of executable pages, such as PAGE_EXECUTE_WRITE, PAGE_EXECUTE_READ, etc.? If I want to detect all sections mapped with any form of EXECUTE, then do I need to test them all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20a64a62-c8b8-d3f7-942a-145b8d8907c9
* Version Independent ID: 3ecdda0f-ef9b-5bde-431e-81a7af013f64
* Content: [FLT_PARAMETERS for IRP_MJ_ACQUIRE_FOR_SECTION_SYNCHRONIZATION union - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/flt-parameters-for-irp-mj-acquire-for-section-synchronization)
* Content Source: [windows-driver-docs-pr/ifs/flt-parameters-for-irp-mj-acquire-for-section-synchronization.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/flt-parameters-for-irp-mj-acquire-for-section-synchronization.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@BrianCatlin , thanks for pointing this out - the table was VERY old and out of date! I've updated the page to link to a complete list of PageProtection options. You do indeed need to test for each form of EXECUTE.
