### ISSUE TITLE
ทำให้ให้ใหม่เลย

### ISSUE THREAD

**Issue by yang980** [MicrosoftDocs/windows-driver-docs#1559]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 2b9ee674-39b1-659a-fd60-8f60e8e6f660
* Version Independent ID: 2d1cb1cf-538a-27a9-19a5-0795bf28943b
* Content: [INF File Sections and Directives - Windows drivers](https://docs.microsoft.com/th-th/windows-hardware/drivers/install/inf-file-sections-and-directives)
* Content Source: [windows-driver-docs-pr/install/inf-file-sections-and-directives.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-file-sections-and-directives.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Sorry, at this time, we can only process requests in English.
