### ISSUE TITLE
Git merge text present in article body

### ISSUE THREAD

**Issue by olegvs** [MicrosoftDocs/windows-driver-docs#1564]
The article contains text "&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD" and other which is remnants of left over bad merge resolve..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a05e45-339b-d94e-f337-e802afd56b79
* Version Independent ID: 8db6253e-eb0c-e88b-bf1e-7270a56096ca
* Content: [Bug Check 0x9F DRIVER_POWER_STATE_FAILURE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x9f--driver-power-state-failure#feedback)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x9f--driver-power-state-failure.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x9f--driver-power-state-failure.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@olegvs - The merge text should not be left in a topic, thanks for catching this! The merge text is removed. You are always welcome to create PRs for doc fixes.
