### ISSUE TITLE
2 duplicate doc pages describing AppVerifier

### ISSUE THREAD

**Issue by metathinker** [MicrosoftDocs/windows-driver-docs#1567]
The doc page this issue is filed against, [Windows Hardware / Windows Drivers / Windows Debugging Tools / ... / Application Verifier](https://docs.microsoft.com/windows-hardware/drivers/debugger/application-verifier) ([source](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/application-verifier.md)) appears to be nearly a duplicate of another doc page, namely [Windows Hardware / Windows Drivers / Device and Driver Technologies / Tools for Testing Drivers / ... / Application Verifier](https://docs.microsoft.com/windows-hardware/drivers/devtest/application-verifier) ([source](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/application-verifier.md)).

The pages have slight differences. Please consider combining the two pages into one, incorporating the merged content from both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01df443-4274-1459-ec50-b1383d42933f
* Version Independent ID: 04cb8e05-6883-703c-d934-05c2f114dc9b
* Content: [Application Verifier - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/application-verifier)
* Content Source: [windows-driver-docs-pr/debugger/application-verifier.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/application-verifier.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@metathinker - In the driver realm, the primary use of app verifier is to help validate UMDF drivers. So the devtest version that mentions that is retained and the other version in debugger is being removed. Thanks for pointing this out.
