### ISSUE TITLE
Unclear which DDI version document refers to.

### ISSUE THREAD

**Issue by Ocasio-J** [MicrosoftDocs/windows-driver-docs#1571]
For example, similar pages exists for D3d10 and D3d11:
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/initializing-communication-with-the-direct3d-version-10-ddi
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/initializing-communication-with-the-direct3d-version-11-ddi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d497b78-babc-8b00-de3d-d37b3a4f5d6a
* Version Independent ID: 54a399cb-2731-6eff-49ad-f4f6883d3ac0
* Content: [Initializing D3D User-Mode Display Driver Communications - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/initializing-communication-with-the-direct3d-user-mode-display-driver#feedback)
* Content Source: [windows-driver-docs-pr/display/initializing-communication-with-the-direct3d-user-mode-display-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/initializing-communication-with-the-direct3d-user-mode-display-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@Ocasio-J , good catch! I've added the version info (it's version 11).
