### ISSUE TITLE
Code integrity check

### ISSUE THREAD

**Issue by eliyasy** [MicrosoftDocs/windows-driver-docs#1572]
Decimal id is incorrect. It's 26 - not 22.

22 is NDIS/WIFI verification (**)

              3 - Randomized low resources simulation
                  10 - Force pending I/O requests (*)
                  11 - IRP logging (*)
                  14 - Invariant MDL checking for stack (*)
                  15 - Invariant MDL checking for driver (*)
                  16 - Power framework delay fuzzing
                  17 - Port/miniport interface checking
                  19 - Systematic low resources simulation
                  20 - DDI compliance checking (additional)
                  22 - NDIS/WIFI verification (**)
                  24 - Kernel synchronization delay fuzzing
                  25 - VM switch verification
                  26 - Code integrity checks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c32f5e59-2a1f-e9ee-aa34-9dba3b8c7852
* Version Independent ID: f0785c02-7313-f255-0cf3-6078f7947dcc
* Content: [Driver Verifier Options - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/driver-verifier-options)
* Content Source: [windows-driver-docs-pr/devtest/driver-verifier-options.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/driver-verifier-options.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
All done. Will be live in a few minutes. Thanks, @eliyasy
