### ISSUE TITLE
Explain how to use DMF on this page

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/windows-driver-docs#1573]
Since [DMF](https://github.com/Microsoft/DMF) is meant to make writing drivers simpler (by reducing the amount of code that developers need to write), it would be nice if this page could explain how to get started with it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287160ad-f2a5-789a-2d7d-ff336514c11e
* Version Independent ID: a138162d-2b80-725b-212b-277bae8f177d
* Content: [Write a Universal Windows driver (UMDF 2) based on a template - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-umdf-driver-based-on-a-template#feedback)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-umdf-driver-based-on-a-template.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-umdf-driver-based-on-a-template.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @hansmbakker 
Great idea. I added a section in the topic here as well as in the one for KMDF based on a template.
Cheers,
Eliot

**Comment by hansmbakker** [comment]
Thank you!
