### ISSUE TITLE
Document dx -id

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-driver-docs#1577]
When I clicked a hyperlink in the output of `dt Wdf01000!_FX_DRIVER_GLOBALS 0xffff8c8876831de0`, WinDbg 10.0.17763.132 ran the following command:

```
dx -id 0,0,ffff8c88728b4300 -r1 ((Wdf01000!FxDriver *)0xffff8c88765fbe20)
```

This command uses the `-id` option, which is not documented. Please document it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35974886-fcd8-e30b-2bcb-48ac4c32753d
* Version Independent ID: a73b8ba3-6096-74bf-3124-32a077ced9c7
* Content: [dx (Display Debugger Object Model Expression) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/dx--display-visualizer-variables-)
* Content Source: [windows-driver-docs-pr/debugger/dx--display-visualizer-variables-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/dx--display-visualizer-variables-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@KalleOlaviNiemitalo - I worked with the dev team to document the -id option. It is used to support the rendering of links in command output. 

dx {-id}
Microsoft internal use only. Used to follow data model links in command output.

Thanks for making this request, and good luck using the dx command and the debugger.
