### ISSUE TITLE
Thanks for nice great information

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1580]
I thought of updating firmware using by setup.exe and  other third party provided by the OEM .
But after reading this article , i wondered how the windows os  updates particular unique  firmware to respective unique device . I am totally  wondered how the windows was designed to update the uefi firmware. Last 25-05-2017 , i received  bios uefi firmware via device manager , this windows 10 updated without problems . I say thanks to  asus  development team for released bios v 307 and  the windows os development team for provided  correct bios.
Moreover i like to humble thanks to  all authors who are all contributed to this article with their practical knowledge.
I wish all the best to all the authors. Keep  updating new articles with more attractive  video lecturers if possible 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4320a0-085e-4ca1-e83a-1b030b480100
* Version Independent ID: 5e474f7e-998e-1d76-49e7-fbc67ca1071d
* Content: [Windows UEFI firmware update platform - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/windows-uefi-firmware-update-platform#feedback)
* Content Source: [windows-driver-docs-pr/bringup/windows-uefi-firmware-update-platform.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/windows-uefi-firmware-update-platform.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks @RAJU2529!

Happy to hear that your ASUS device firmware updated successfully under Windows 10.
