### ISSUE TITLE
same thing i experienced 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1581]
On 25-05-2019 , i experienced same  exp while updating system uefi firmware .
We must follow certains steps or conditions before  updating or checking new firmwares.
01. Close all running applications
02. Disable otr turn off  windows defender 
03. Disable or turn off windows firewall
04. Disable any other third party antiviruses softwares and firewalls
05. Connect the AC power adapter to the laptop or  UPS connected to desktop
06. Clean the windows  by using diskcleanup tool
07. Use sfc /scannow tool 
08. If possible  repair corrupted image with dism restorehealth tool
09. Check for new firmware , if available, then click ti update , then restart the windows.
10. Once completed new firmware, then you must boot the windows into normal mode and then shutdown.
11. Go to bios , reset or restore default settings  for every major or minor update for optimizing with connected hardwares with new bios 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fce932d-f6f9-fa84-077f-1e3df3859800
* Version Independent ID: 050ee34d-d82c-9d4e-4df8-18235bb4ccb3
* Content: [User experience for UEFI firmware updates - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/user-experience-for-uefi-firmware-updates)
* Content Source: [windows-driver-docs-pr/bringup/user-experience-for-uefi-firmware-updates.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/user-experience-for-uefi-firmware-updates.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks @RAJU2529 for the comments on your experience updating your UEFI firmware. Although this topic is focused on providing guidance to OEMs and IHVs, I'm glad to know that it was useful.
