### ISSUE TITLE
Whether End user can able to modify ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1582]
I am using asus vivobook 15 r542uq-dm153 with bios x542uq.307  .
I was trying to modify the bios with .307 format . Its more complicated to modify , Because  codes and other things are  beyond my knowledge .
Then how can oem can modify the bios firmware.
Is there any common tools to modify bios as per customer needs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b19d94-b32a-7358-0419-97e0ed285cbb
* Version Independent ID: a7f0973e-6d35-b579-e8e8-682892a8037d
* Content: [System and device firmware updates via a firmware driver package - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/system-and-device-firmware-updates-via-a-firmware-driver-package)
* Content Source: [windows-driver-docs-pr/bringup/system-and-device-firmware-updates-via-a-firmware-driver-package.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/system-and-device-firmware-updates-via-a-firmware-driver-package.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
