### ISSUE TITLE
I have read the contains of the .inf  files

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1583]
I totally  wondered how  the  normal  text file becames  valid  driver in the form of .inf extension.
I wish the  notepad  development team for awesome  tool.
I would  request to microcoft , dont  remove  notepad  in coming  windows os .
Add more  features   must be added to notepad software.

Thanks to all the authors who are all contributed their knowledge to this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d25e12-2213-9c84-2fe9-ee2f32e82a27
* Version Independent ID: 6ff8eec2-25d4-f1af-a155-74cfa99ad7df
* Content: [Updating Device Firmware using Windows Update - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/updating-device-firmware-using-windows-update#feedback)
* Content Source: [windows-driver-docs-pr/install/updating-device-firmware-using-windows-update.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/updating-device-firmware-using-windows-update.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback, @RAJU2529
