### ISSUE TITLE
Suggested addition for "Testing" section on this page

### ISSUE THREAD

**Issue by tzimmer1** [MicrosoftDocs/windows-driver-docs#1590]
Intel has discovered while implementing DFx on non-WDF drivers that several drivers perform incorrect PoFx D-State accounting across S4 transitions. 
I would suggest a line item in the "Testing" section to strongly suggest testing DFx after an S4 transition has been performed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53456e5d-2f98-0b55-dfb0-dcb25c4eb7f9
* Version Independent ID: 3ca90a7c-0bf7-7711-9235-cb423cc11764
* Content: [Introduction to the Directed Power Management Framework - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-the-directed-power-management-framework)
* Content Source: [windows-driver-docs-pr/kernel/introduction-to-the-directed-power-management-framework.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/introduction-to-the-directed-power-management-framework.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @tzimmer1 for the suggestion and apologies for the delay.  I pushed a99803a324 to address your feedback.
