### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windows-driver-docs#1594]
The link to changes in driver signing for Windows 10 is broken. 
The intended page is:
https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/07/26/driver-signing-changes-in-windows-10-version-1607/

But you end up here:
https://techcommunity.microsoft.com/t5/Windows-Hardware-Certification/bg-p/WindowsHardwareCertification

You really should stop referring to blogs, especially Microsoft blogs since a lot of them are being deleted.
Also, a blog is not documentation, a blog article is most of the time one individuals personal opinion, and there's no way for a reader to know if it is officially sanctioned by Microsoft and/or whether what is described is supported by Microsoft.
Also, if there are any changes, the blog won't be updated, and the guy who wrote it might not even work for Microsoft any longer. 
The same goes for references to StackOverflow, info there is not persistent, if a user removes his account his info might go too, also, any user might update the info after the link was created, so it might now contain completely different info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716c22a0-7fc1-56a9-a0de-aca1f5b42d1d
* Version Independent ID: 493cc896-d2a5-4d9e-74c4-274cd9227612
* Content: [Trusted Root Certification Authorities Certificate Store - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/trusted-root-certification-authorities-certificate-store)
* Content Source: [windows-driver-docs-pr/install/trusted-root-certification-authorities-certificate-store.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/trusted-root-certification-authorities-certificate-store.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thankss for the suggestion @Bartolomeus-649.  I completely agree with your points about non-persistent link targets.  All of the info from that blog is consolidated on https://docs.microsoft.com/en-us/windows-hardware/drivers/install/kernel-mode-code-signing-policy--windows-vista-and-later-, so I removed the link to the blog article.  Changes should be live in 15 min or so.
