### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by RonaldAi** [MicrosoftDocs/windows-driver-docs#1599]
The links in this page point to something like https://msdn.microsoft.com/library/windows/desktop/ms683580, which get redirected to https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-interlockeddecrement, which is the wrong location for the content. It actually is at https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-interlockeddecrement
Looks like the redirects should be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 063d2620-fc61-28df-96cb-a6f8df4a8c6a
* Version Independent ID: 55db760b-1219-0b88-2726-ca123b6a62c4
* Content: [Interlocked Operations in Storport Miniport Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/interlocked-operations-in-storport-miniport-drivers)
* Content Source: [windows-driver-docs-pr/storage/interlocked-operations-in-storport-miniport-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/interlocked-operations-in-storport-miniport-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@ronaldai, thanks for reporting these broken links! The InterlockedXxx function list was incomplete, so I deleted it. I've filed an internal task for myself to look at all Interlocked functions to ensure they are docced, and will add a pointer to them at a future date.
