### ISSUE TITLE
Undocumented error code

### ISSUE THREAD

**Issue by alexfeinman** [MicrosoftDocs/windows-driver-docs#1608]
I am seeing ACPI_BIOS_ERROR with Paramter 1 set to 0x1000D. This specific value is not documented here. Can it be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e709d9c-e611-ab5b-232f-1c53f1c3c4e8
* Version Independent ID: 366cae43-1103-8f11-3fac-ad25d799e508
* Content: [Bug Check 0xA5 ACPI_BIOS_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xa5--acpi-bios-error#feedback)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0xa5--acpi-bios-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0xa5--acpi-bios-error.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@alexfeinman - This sub code is now documented. Thanks for your interest in the stop code documentation.
