### ISSUE TITLE
Add WDM based PoFx samples (including DFx)

### ISSUE THREAD

**Issue by tzimmer1** [MicrosoftDocs/windows-driver-docs#1609]
Can WDM-based PoFx and DFx implementation details be added to this source base?
Intel has some driver using a WDM-based PoFx approach due to some Microsoft port drivers not implementing PoFx.

Can DFx information (via https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-the-directed-power-management-framework) be added to the WDM (non-WDF) based PoFx samples?
Particularly samples on how the DFx PoFx callbacks work (PO_FX_DIRECTED_POWER_DOWN_CALLBACK and PO_FX_DIRECTED_POWER_UP_CALLBACK)?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71930d8-98eb-1e76-d08f-3d7b5a46c7ec
* Version Independent ID: 01b2dad1-2cb1-14a9-da96-15404b4578d9
* Content: [Power framework (PoFx) driver samples - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/samples/power-framework--pofx--driver-samples)
* Content Source: [windows-driver-docs-pr/samples/power-framework--pofx--driver-samples.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/samples/power-framework--pofx--driver-samples.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. 

I would recommend that you open an issue in the [Windows-driver-samples](https://github.com/microsoft/Windows-driver-samples) repo to request a driver sample for WDM-based PoFx and DFx.

You may also have success posting your questions on WDM-based PoFx and DFx implementation details in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
