### ISSUE TITLE
Give some examples for the .load command

### ISSUE THREAD

**Issue by agvardha** [MicrosoftDocs/windows-driver-docs#1611]
Ok I did .load C:\Windows\system32\abcd.dll. Nothing happened. Then you say we can force it by doing !DLLName.ExtensionCommand syntax. Couple of example would have been useful. 

Thanks 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5f87e7c-87f4-ac0a-e6a2-4076f43e64a5
* Version Independent ID: 8624a834-9133-7f81-7687-1b1a46862bbb
* Content: [.load, .loadby (Load Extension DLL) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-load---loadby--load-extension-dll-)
* Content Source: [windows-driver-docs-pr/debugger/-load---loadby--load-extension-dll-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-load---loadby--load-extension-dll-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@agvardha - Thanks for this input. I added an example use of the .load command. The .chain command displays what is loaded, where .load doesn't report on a successful load. I added an example use of .chain command was well to show this. Thanks for this feedback and good luck in your work with the debugger.
