### ISSUE TITLE
File Version vs Product Version

### ISSUE THREAD

**Issue by tonysepia** [MicrosoftDocs/windows-driver-docs#1612]
In section 'Loading mscordacwks.dll and sos.dll (live debugging)' it is worth noting that 'CLR version' is NOT referring to File Version, but to Product Version:
    File version:     4.6.1590.0
    Product version:  4.0.30319.0

It can be confusing, as SOS.dll 4.0.30319.0 is apparently used to debug .NET Framework 4.6 application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2bcbf2-e178-6a63-e960-bae862cbaee5
* Version Independent ID: 1a105ee9-2596-3563-8241-882bca17f316
* Content: [Debugging Managed Code Using the Windows Debugger - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-managed-code#feedback)
* Content Source: [windows-driver-docs-pr/debugger/debugging-managed-code.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugging-managed-code.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@tonysepia - Thanks for this input, I specified "product version" for the mscordacwks.dll to help clarify this.
