### ISSUE TITLE
I have updated uefi 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1614]
I trust microsoft windows os  for delivered correct firmware to my asus  laptop. No problems while updated . BIOs=UEFI firmware/
Thanks for the article with  diagrams . It clearly explains  everything with hidden knowledge .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d25e12-2213-9c84-2fe9-ee2f32e82a27
* Version Independent ID: 6ff8eec2-25d4-f1af-a155-74cfa99ad7df
* Content: [Updating Device Firmware using Windows Update - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/updating-device-firmware-using-windows-update#feedback)
* Content Source: [windows-driver-docs-pr/install/updating-device-firmware-using-windows-update.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/updating-device-firmware-using-windows-update.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback, @RAJU2529
