### ISSUE TITLE
Great content.

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1618]
01. So many protocals  are embedded in uefi .  Thanks  to all authors  for getting mentioned in this article and giving good circuit diagram based on current article.
02. Really  colorful diagram are  most suitable for  article.
03. I am little sad , because  many of the  windows users are  not giving feedback or comments .Eventhough  authors   are giving good example with their continuous efforts. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b71bc68-55a4-256d-5f2d-75cf2477b7fc
* Version Independent ID: d0830cb2-8897-ab2d-a03d-212d8cd31ae2
* Content: [UEFI in Windows - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/uefi-in-windows)
* Content Source: [windows-driver-docs-pr/bringup/uefi-in-windows.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/uefi-in-windows.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for your comment @RAJU2529, we appreciate knowing that this content is correct and useful for driver developers. 

We welcome and encourage developers to open issues and submit pull requests to help us improve the bring up and driver documentation.
