### ISSUE TITLE
Please add the screenshot .

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1621]
Sir please add the device hardware Id screenshots, so that users can easily identify 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29e581e-02a0-dab0-83db-25ae1ca1aebb
* Version Independent ID: 21141809-e821-8e58-dcf2-be1d1bb9be87
* Content: [Step 1 The New Device is Identified - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/step-1--the-new-device-is-identified)
* Content Source: [windows-driver-docs-pr/install/step-1--the-new-device-is-identified.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/step-1--the-new-device-is-identified.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Sorry, @RAJU2529, but we can't add user-specific screenshots to this documentation.  The docs contain high-level generic examples only.
