### ISSUE TITLE
0xDD 

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/windows-driver-docs#1623]
[Enter feedback here]

An attempt was made to unload a driver without calling EtwUnregister.

在开启驱动程序校验器的情况下，在驱动入口加载驱动失败而没有调用WPP_CLEANUP，反而说是在驱动卸载的时候没有调用WPP_CLEANUP。

这个说法有点坑人啊！

DRIVER_VERIFIER_DETECTED_VIOLATION (c4)
A device driver attempting to corrupt the system has been caught. This is
because the driver was specified in the registry as being suspect (by the
administrator) and the kernel has enabled substantial checking of this driver.
If the driver attempts to corrupt the system, bugchecks 0xC4, 0xC1 and 0xA will
be among the most commonly seen crashes.
Arguments:
Arg1: 00000000000000dd, Unloading driver that forgot to call EtwUnregister.
Arg2: fffff880046a76d0, Address where the culprit driver called EtwRegister.
Arg3: fffff88004665000, Start address of the culprit driver.
Arg4: 0000000000000000, Address of the leaked ETW_REG_ENTRY structure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48d16a94-9fc7-672c-ed1b-e0cae695d05b
* Version Independent ID: 4965db7f-5008-23f5-eba8-040f9236c4cf
* Content: [Bug Check 0xC4 DRIVER_VERIFIER_DETECTED_VIOLATION - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xc4--driver-verifier-detected-violation)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0xc4--driver-verifier-detected-violation.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0xc4--driver-verifier-detected-violation.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@kouzhudong - This does not seem to be documentation related, so closing this issue.
