### ISSUE TITLE
Does CONNECT_MESSAGE_BASED creates a spinlock for each interrupt message or all interrupt messages in the group

### ISSUE THREAD

**Issue by russli1993** [MicrosoftDocs/windows-driver-docs#1631]
"If the driver uses the CONNECT_LINE_BASED or CONNECT_MESSAGE_BASED versions of IoConnectInterruptEx, and specifies a NULL spin lock, the system will allocate a spin lock to be shared across all of the device's interrupts. The system also determines the value for the synchronization IRQL (drivers can optionally specify a higher value). All of the driver's interrupts will share the same critical section. " suggests that if a device has 512 interrupt vectors, all interrupt vectors will share the same spinlock when interrupt messages arrives and before calling the interrupt service routine.

Comments in wdm.h for the CONNECT_MESSAGE_BASED struct. "//
    // SpinLock - Supplies an optional pointer to a spin lock that will be
    //     acquired before every call to the IMSR.  After providing a spin
    //     lock, the driver can synchronize with the IMSR by acquiring the
    //     spin lock at the synchronization IRQL associated with the IMSR.
    //     Note that providing a spin lock will serialize processing of all of
    //     the interrupt messages being connected.  In other words, providing
    //     a spin lock implies that no two interrupt messages out of the set
    //     being connected can ever be serviced in parallel by the IMSR.
    //
    //     If this parameter is not provided, then an internal spin lock will
    //     be acquired before each call to the IMSR.  This internal spin lock
    //     is associated with the interrupt object corresponding to the actual
    //     message that caused us to execute the IMSR, meaning that the IMSR
    //     can run on multiple processors and potentially at multiple IRQLs in
    //     this case.  KeSynchronizeExecution can be used to acquire this
    //     internal spin lock at the appropriate IRQL, thus synchronizing with
    //     IMSR execution associated with a specific interrupt message while
    //     still allowing all other messages to be serviced as they are
    //     signaled.
    //
" This implies there will be a spinlock created for each interrupt vector. And when a message arrives, HAL will acquire the spinlock for that interrupt vector before calling the service routine. If messages arrive on different interrupt vectors on different CPUs, the service routine will run concurrently.

Which one of this is true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7bde6f7-72bf-fb62-bd33-9675a4646104
* Version Independent ID: 62d6b639-5bfe-9984-3c79-84e3a8d4a8c7
* Content: [Synchronizing Access to Device Data - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/synchronizing-access-to-device-data)
* Content Source: [windows-driver-docs-pr/kernel/synchronizing-access-to-device-data.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/synchronizing-access-to-device-data.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @russli1993, thanks for the feedback.  Apologies it took a while to get back to you.  See the above change - should appear on the live site within 20 min
