### ISSUE TITLE
'4:2:2 Video Pixel Formats' broken link

### ISSUE THREAD

**Issue by Kojoley** [MicrosoftDocs/windows-driver-docs#1633]
'4:2:2 Video Pixel Formats' link points to `vscode-resource://c:/drivers/drivers/windows-driver-docs-pr/display/4-2-2-video-pixel-formats.md`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 062f8724-08fa-0dca-a2b8-0b9509fef6af
* Version Independent ID: db5beab6-db27-44e0-c25f-73ca5c5bcb04
* Content: [4 2 0 Video Pixel Formats - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/4-2-0-video-pixel-formats#feedback)
* Content Source: [windows-driver-docs-pr/display/4-2-0-video-pixel-formats.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/4-2-0-video-pixel-formats.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@Kojoley , thanks for reporting these broken links - they are now fixed!
