### ISSUE TITLE
Can there be a link to the sample included?

### ISSUE THREAD

**Issue by mitulsuthar** [MicrosoftDocs/windows-driver-docs#1637]
There is no way to figure out how to make an app support this lock feature. The documentation is not sufficient and it is confusing. I am trying to make my app available for kiosk user under assigned access but it requires Lock and background task feature. Is there a way to have a complete sample that demonstrates this functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82735562-385b-1ac5-b0a5-1caa2b400d87
* Version Independent ID: dafdf1b8-d884-2074-7d25-ad387bcf7850
* Content: [Kiosk apps for assigned access Best practices - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/partnerapps/create-a-kiosk-app-for-assigned-access)
* Content Source: [windows-driver-docs-pr/partnerapps/create-a-kiosk-app-for-assigned-access.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/partnerapps/create-a-kiosk-app-for-assigned-access.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @mitulsuthar 
I'm afraid that the only sample we currently have for partner apps is **Partner-app-development** in [Samples for partner application development (OEM, MO, IHV) for Windows](https://github.com/microsoft/Partner-app-development).

Eliot
