### ISSUE TITLE
Link to Regstr.h

### ISSUE THREAD

**Issue by JonAxtell** [MicrosoftDocs/windows-driver-docs#1639]
To make it easier to use this property it would be nice to have a link to a copy of the regstr.h header. Or alternatively, the part of regstr.h related to this property should be listed on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae9a626c-439a-0f73-27d1-40333c7fcc94
* Version Independent ID: ec922c15-d2e3-9f9f-4b57-f3ad20759414
* Content: [DEVPKEY_Device_ConfigFlags - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/devpkey-device-configflags)
* Content Source: [windows-driver-docs-pr/install/devpkey-device-configflags.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/devpkey-device-configflags.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @JonAxtell and apologies for the delay.  It turns out that those configuration flags are really just for internal use only.  I just updated the docs to reflect that.  That change should be live within the hour.
