### ISSUE TITLE
Flag names on this page are incorrect

### ISSUE THREAD

**Issue by rahul-ramadas** [MicrosoftDocs/windows-driver-docs#1640]
The flags that are documented as `WDF_FORWARD_*` are incorrect. They are supposed to be `WDF_DISPATCH_*`, as documented correctly in the page for [WDF_DISPATCH_IRP_TO_IO_QUEUE_FLAGS](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdfdevice/ne-wdfdevice-_wdf_dispatch_irp_to_io_queue_flags).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72552dca-17ae-7450-f99a-5e74f9719c54
* Version Independent ID: 367381da-9000-00ec-02fd-6498befa30a4
* Content: [Dispatching IRPs to I/O Queues - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/dispatching-irps-to-i-o-queues)
* Content Source: [windows-driver-docs-pr/wdf/dispatching-irps-to-i-o-queues.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/dispatching-irps-to-i-o-queues.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @rahul-ramadas these kind of suggestions are very helpful.  Apologies for the delay getting the fix in.  Just pushed the commit above, should be live in 10 min or so
