### ISSUE TITLE
Powershell command

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1642]
How about a simple Powershell command: 
Get-CimInstance Win32_SystemDriver -Filter "name='your_driver_name'" |  
Invoke-CimMethod -MethodName Delete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c05d6a6d-434c-538a-d000-3a96236e6bff
* Version Independent ID: 3314e31f-5c06-4694-f40a-c29692681c4e
* Content: [Using an INF File to Uninstall a File System Filter Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/using-an-inf-file-to-uninstall-a-file-system-filter-driver)
* Content Source: [windows-driver-docs-pr/ifs/using-an-inf-file-to-uninstall-a-file-system-filter-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/using-an-inf-file-to-uninstall-a-file-system-filter-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@briancatlin, I added your PowerShell option - thank you!
