### ISSUE TITLE
seemingly missing log files when using as administrator

### ISSUE THREAD

**Issue by Aaaul** [MicrosoftDocs/windows-driver-docs#1649]
I'm using the Application Verifier 10.0 (x64) to check my executables. If I'm running my code the Verifier creates the log-files at %USERPROFILE%\AppVerifierLogs as described in the help. But when I try to read the log-files via "View\Logs" the Verifier doesn't show any.
However when I start the Verifier without admin-privileges, I'm able to read the log-files that were produced and save them as XML. 
Regarding to the fact that I personaly have no admin-privileges on my PC, could it be that the logs are saves also (if existing) in the "%USERPROFILE%\AppVerifierLogs" directory of my supervisor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01df443-4274-1459-ec50-b1383d42933f
* Version Independent ID: 04cb8e05-6883-703c-d934-05c2f114dc9b
* Content: [Application Verifier - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/application-verifier#feedback)
* Content Source: [windows-driver-docs-pr/debugger/application-verifier.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/application-verifier.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Aaaul - Thanks for reaching out to the Windows Driver Developer Documentation team. It is possible that Admin rights are required, this is pretty common for many code utilities. 
Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation. You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk) 
Thanks for reaching out to the docs team. Best of luck with this issue.
