### ISSUE TITLE
VLAN should be WLAN

### ISSUE THREAD

**Issue by SasStu** [MicrosoftDocs/windows-driver-docs#1650]
I think VLAN should be WLAN in the following sentence: When the user is connected to a VLAN or Ethernet connection, no Internet traffic is routed over the cellular connection. 
This would make sense in combination with the paragraph after that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 007029d8-c597-7a41-ecf9-577078ada719
* Version Independent ID: 3e097f5a-0353-71b5-7932-9d5ac4cba772
* Content: [Understanding and configuring Windows Connection Manager - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/mobilebroadband/understanding-and-configuring-windows-connection-manager)
* Content Source: [windows-driver-docs-pr/mobilebroadband/understanding-and-configuring-windows-connection-manager.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/mobilebroadband/understanding-and-configuring-windows-connection-manager.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @SasStu, thanks for pointing this out. This does look like a typo, so I've gone ahead and fixed it. Those changes should be live in the next few minutes. 

Also, for small changes like this in the future you can feel free to edit the page directly using the "Edit" button in the upper right corner, then submit a pull request. :) 

Thanks!
