### ISSUE TITLE
403

### ISSUE THREAD

**Issue by kkoeman** [MicrosoftDocs/windows-driver-docs#1654]
When attempting to access this page: http://blogs.windows.com/windows/b/buildingapps/archive/2014/04/04/windows-compatible-hardware-development-boards-available-soon.aspx

I get a 403 Forbidden

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd8e53ee-4f67-ccdf-c0dd-bed9278d59a4
* Version Independent ID: f1aa756a-cdac-c83c-16e6-30a52b0b108f
* Content: [Windows compatible hardware development boards - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/windows-compatible-hardware-development-boards#feedback)
* Content Source: [windows-driver-docs-pr/gettingstarted/windows-compatible-hardware-development-boards.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/windows-compatible-hardware-development-boards.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @kkoeman. I get the same results.

Luckily, there's https://blogs.windows.com/windowsdeveloper/2014/04/04/windows-compatible-hardware-development-boards-available-soon/#V762kL2jCQwuiIiU.97

I see the full content there. I've changed the lin in the topic. Should be live shortly.

Cheers,
Eliot
