### ISSUE TITLE
It seems that PPM notification document contains the wrong information.

### ISSUE THREAD

**Issue by chanwoochoi** [MicrosoftDocs/windows-driver-docs#1662]
Dear all,

I tried to develop the PEP driver with DPM and PPM notifications.
I completed the implementation of PEP for handling DPM notifications
such as F-state, P-state. After that, I tried to analyze the PPM notifications
in order to control the Processor on PEP driver.

But, I found out the some issue of PPM notification document.
I explain the detailed issue as following:

[Summary description of issue]
In the PPM notification document, Data A pointer of both PEP_NOTIFY_PPM_PERF_SET
and PERF_SET_STATE specifies as followng: But, Data A pointer doesn't have any PEPHANDLE for target processor. I want to catch the device handle of target processor through PPM notifications.
- "Handle A PEPHANDLE structure containing the device handle of the PEP for the target processor."

[Detailed description of issue]
PEP_NOTIFY_PPM_PERF_SET[1] used the 'PEP_PPM_PERF_SET' structure as the Data A pointer.
Even if the description of PEP_NOTIFY_PPM_PERF_SET[1] contains following comments,
Data A pointer doesn't have the any PEPHANDLE for target processor.
- Handle A PEPHANDLE structure containing the device handle of the PEP for the target processor. If the notification does not target a specific processor, this will be NULL.
Data A pointer to a PEP_PPM_PERF_SET[2] structure.

PEP_NOTIFY_PPM_PERF_SET_STATE[3] has the same issue with PEP_NOTIFY_PPM_PERF_SET[1]

[1] https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/ppm-notifications#pep_notify_ppm_perf_set
[2] https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/pep_x/ns-pep_x-_pep_ppm_perf_set
[3] https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/ppm-notifications#pep_notify_ppm_perf_set_state

**Comment by tedhudek** [comment]
Thanks @chanwoochoi and apologies for the delay.  Sorry about the format of the page, this is a known problem that I am working on.  I did reformat the sections you mention, for example https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/ppm-notifications#pep_notify_ppm_perf_set.

Note that the handle you want is actually an explicit parameter called *Handle* that comes when your *PEPCALLBACKNOTIFYPPM* callback function (called *AcceptProcessorNotification* in the docs) receives a **PEP_NOTIFY_PPM_PERF_SET** notification.
