### ISSUE TITLE
Visual Studio new projects has not looked like any of the screengrabs for many years now. 

### ISSUE THREAD

**Issue by studleylee** [MicrosoftDocs/windows-driver-docs#1667]
Visual Studio new projects has not looked like any of the screengrabs for many years now. The options shown are not given.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5852b021-94d2-1a19-17f3-7dc54d4cb409
* Version Independent ID: 031f5cb8-db62-4a2d-9ea4-939eb0fd0ade
* Content: [Write a Windows desktop app based on the WinUSB template - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/how-to-write-a-windows-desktop-app-that-communicates-with-a-usb-device)
* Content Source: [windows-driver-docs-pr/usbcon/how-to-write-a-windows-desktop-app-that-communicates-with-a-usb-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/how-to-write-a-windows-desktop-app-that-communicates-with-a-usb-device.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @studleylee, thanks for pointing this out. I recently updated the driver-focused USB template topics for Visual Studio 2019, but hadn't gotten to this one yet. I've updated this page for VS 2019 now, so please take a look and let me know if you see any issues. Thanks for helping to improve the docs!
