### ISSUE TITLE
Test issue 3

### ISSUE THREAD

**Issue by tedhudek** [MicrosoftDocs/windows-driver-docs#1670]
Another issue for label testing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2473c12-0d72-4437-dcd7-ca85ca28ee95
* Version Independent ID: d809e109-bed8-876a-c455-ed230f5a9bb5
* Content: [Evaluating a Control Method Without Input Arguments - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/acpi/evaluating-a-control-method-without-input-arguments)
* Content Source: [windows-driver-docs-pr/acpi/evaluating-a-control-method-without-input-arguments.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/acpi/evaluating-a-control-method-without-input-arguments.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
#please-close

**Comment by barrygolden** [comment]
Closing
