### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#1671]
This page should provide a link to https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/building-a-wdf-driver-for-multiple-versions-of-windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e18cc5f-4209-29f7-5b11-64bb9d32f09b
* Version Independent ID: 873e0c27-e96b-24a2-06e5-52f0c833ed0b
* Content: [Framework Library Versioning - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/framework-library-versioning)
* Content Source: [windows-driver-docs-pr/wdf/framework-library-versioning.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/framework-library-versioning.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Added to https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/framework-library-versioning, thanks for the suggestion
