### ISSUE TITLE
Wrong Regsitry key

### ISSUE THREAD

**Issue by akshay-dysonics** [MicrosoftDocs/windows-driver-docs#1680]
Page: https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/user-mode-services-ufx

The sentence: 

> declared in the registry under the OEM-defined subkey of HKEY_LOCAL_MACHINE\CurrentControlSet\Control\USBFN\Interfaces. 

The registry key should read: 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\USBFN\Interfaces

Note the missing "SYSTEM" after HKEY_LOCAL_MACHINE

Edit: Sorry, I posted the wrong link, the link is correct now

**Comment by duncanmacmichael** [comment]
Hi @akshay-dysonics, thanks for pointing this out. I've corrected the registry key path, and the update should be live shortly. Also, in the future, if you submit feedback at the bottom of the page where it says "Feedback > This page", then the link to the page in question will be automatically appended to the issue. Just for your info. :) Thanks!
