### ISSUE TITLE
[windows10_driver_publishing_workflow.docx] How Windows update server selects proper driver when multiple CHIDs match?

### ISSUE THREAD

**Issue by ybendito** [MicrosoftDocs/windows-driver-docs#1682]
We have a driver distribution 1 targeting CHID1 (HardwareID-4, which is Manufacturer + Family + Product Name + SKU Number)
We have a driver distribution 2 targeting CHID2 (HardwareID-5, which is Manufacturer + Family + Product Name)
Which one will be selected by the Windows Update Server for system where both CHID match?
Common sense say that driver 1 should be selected.
But this is not documented anywhere, the document just mention CHID 'hierarchy',

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 531ef6ee-7a29-e6d0-56d6-e08a923b0aa4
Version Independent ID: d00f4b65-2ae6-643f-d67a-c04f916a7058
Content: Publish a driver to Windows Update - Windows drivers
Content Source: windows-driver-docs-pr/dashboard/publish-a-driver-to-windows-update.md
Product: windows-hardware
GitHub Login: @EliotSeattle
Microsoft Alias: eliotgra

**Comment by EliotSeattle** [comment]
Hi @ybendito 

Thanks for the issue and pointing out the missing information. We'll get that added to the content as soon as possible, but in the meantime, here is what I hope is the answer to your question.

The Windows Update service uses CHID to "reduce the number of systems that a driver is applicable to".  This reduction is the first thing that happens before PnP ranking is done.

The Windows Update service treats CHID differently depending on which Windows 10 OS is installed. 

<table>
<colgroup>
<col width="25%" />
<col width="75%" />
</colgroup>
<thead>
<tr class="header">
<th>Windows 10 version</th>
<th>Windows Update behavior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>1507 through 1703</p></td>
<td><p>Windows Update ranks each CHID from CHID-0 to CHID-14 where CHID-0 outranks CHID-14</p></td>
</tr>
<tr class="even">
<td><p>1709 and above</p></td>
<td><p>CHID level is no longer ranked. All applicable CHID targeted drivers from CHID-0 through CHID-14 are lumped together then PnP ranking occurs.</p></td>
</tr> 
</tbody>
</table>


Consider the following example:
Contoso has the following two drivers published as Automatic that target the same HWID but with different CHID.

Distribution 1 - targeting CHID-4 (Manufacturer + Family + Product Name + SKU Number)

Distribution 2 - targeting CHID-5 (Manufacturer + Family + Product Name)

Which one will be selected by the Windows Update Service for systems that match CHID-5?

<table>
<thead>
<tr class="header">
<th>Contoso System</th>
<th>Windows OS level</th>
<th>Offered Driver</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CHID-5 match but not a CHID-4 match</td>
<td>Windows 10 1703 or lower</td>
<td>Distribution 2</td>
</tr>
<tr class="even">
<td>CHID-5 match but not a CHID-4 match</td>
<td>Windows 10 1709 or greater</td>
<td>Both. PnP ranking would then select the best match of these two for installation.</td>
</tr> 
<tr class="odd">
<td>CHID-5 match and a CHID-4 match</td>
<td>Windows 10 1703 or lower</td>
<td>Distribution 1</td>
</tr>
<tr class="even">
<td>CHID-5 match and a CHID-4 match</td>
<td>Windows 10 1709 or greater</td>
<td>Both. PnP ranking would then select the best match of these two for installation.</td>
</tr> 
</tbody>
</table>

All the best.

Eliot
