### ISSUE TITLE
The "List of Operating System Codes" is not up to date. 

### ISSUE THREAD

**Issue by puffelyang** [MicrosoftDocs/windows-driver-docs#1686]
For example, Windows 10 19H1 Client is missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c20769b-d969-a51a-4eb3-f9cc27875f28
* Version Independent ID: 853fe2a9-d654-98a3-7635-c30a450cdbdc
* Content: [Get product data - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-product-data#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/get-product-data.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-product-data.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @puffelyang for pointing this out. Sorry about the oversight.

I've made the changes and they should be live shortly. In the meantime, they are:
Family                              Description
| Windows_v100_19H1 | Windows 10 19H1 Update |
OS Code                                                Description
|WINDOWS_v100_19H1_FULL              |Windows 19H1 Client x86 |
|WINDOWS_v100_X64_19H1_FULL       |Windows 19H1 Client x64 |
|WINDOWS_v100_ARM64_19H1_FULL | Windows 19H1 Client ARM64 |

Eliot
