### ISSUE TITLE
Please check if it is a issue (source of flags)

### ISSUE THREAD

**Issue by rbsriobr** [MicrosoftDocs/windows-driver-docs#1690]
It could even be FILE_DEVICE_SECURE_OPEN, but this is defined as FILE_Xxx, not FILE_DEVICE_Xxx in  wdm.h file:
...
#define FILE_AUTOGENERATED_DEVICE_NAME              0x00000080
#define FILE_DEVICE_SECURE_OPEN                     0x00000100
#define FILE_CHARACTERISTIC_PNP_DEVICE              0x00000800
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001856dc-4924-978e-8226-849dbcc88fe2
* Version Independent ID: 67b81e46-21ed-cb62-adb6-84332fe8b8ac
* Content: [DEVPKEY_DeviceClass_Characteristics - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/devpkey-deviceclass-characteristics#feedback)
* Content Source: [windows-driver-docs-pr/install/devpkey-deviceclass-characteristics.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/devpkey-deviceclass-characteristics.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @rbsriobr, I've updated the doc source for the page in question, give it 20 min to propagate to the live site.  **FILE_DEVICE_SECURE_OPEN** is the only one of the values you list that you should see as flags for the property DEVPKEY_DeviceClass_Characteristics.  See the **DeviceCharacteristics** list on https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-addreg-directive#remarks.  Thanks for the feedback!
