### ISSUE TITLE
URL points to old WDK HCK

### ISSUE THREAD

**Issue by Ron-Hu** [MicrosoftDocs/windows-driver-docs#1699]
This line has embeded URL.  It should possibly be updated to HLK Win10 &lt;latest&gt; or Win10 and another HCK line for the HCK test kit for downlevel. "found &lt;here&gt;" is a URL

These are additions to the normal behavior of Hardware Certification, and the corresponding Certification Requirements for Elam, HalExt, PETrust, and DRM can be found here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba708169-9e8f-f6fc-c0c8-8ba44874d96a
* Version Independent ID: b9304f44-194a-a275-38f4-9d3d4b3d32cb
* Content: [INF SignatureAttributes Section - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-signatureattributes-section#feedback)
* Content Source: [windows-driver-docs-pr/install/inf-signatureattributes-section.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-signatureattributes-section.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @ron-hu, apologies for the delay.  I just updated the link.  Should be live on the site within half an hour.  Thanks for the report.
