### ISSUE TITLE
The format of Device Identification Strings

### ISSUE THREAD

**Issue by AlexKoshulyan** [MicrosoftDocs/windows-driver-docs#1701]
Could you please clarify the format of a device identification string. Is it documented enough to parse it in third-party applications?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d12a22f-cf0a-53e1-e276-ac12ad5e0da9
* Version Independent ID: d42e71ea-3561-bbb3-5041-3d69136540fb
* Content: [Device identification strings - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-identification-strings#feedback)
* Content Source: [windows-driver-docs-pr/install/device-identification-strings.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/device-identification-strings.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @AlexKoshulyan,

Thanks for the feedback and apologies for the delay.

Device identification strings should not be parsed.  They are meant only for exact (usually case insensitive) string comparisons and should be treated as opaque strings.
