### ISSUE TITLE
Power Management  tab is not shown on device properties(BLuetooth)

### ISSUE THREAD

**Issue by liaowawk** [MicrosoftDocs/windows-driver-docs#1702]
I have a bluetooth usb filter driver and can run on many vendor's controller but there is no Power Management tab on device properties for some vendor's controller. And filter driver do not get set power irp after enable device. But for some controller which have power management tab, it can receive set power irp after enable device.
Could you describe when power management tab will show on device properties

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6460b308-f23c-965b-1982-ff4ddaafa21d
* Version Independent ID: c1294874-62b1-5808-f4c6-60747e67bce0
* Content: [Power Management for Windows Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/implementing-power-management#feedback)
* Content Source: [windows-driver-docs-pr/kernel/implementing-power-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/implementing-power-management.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @liaowawk, apologies for the delay.  I do not know the answer to your question, but I did find this page that addresses a similar question:

https://answers.microsoft.com/en-us/surface/forum/all/power-management-tab-is-missing-from-device/0a3c563a-5ec7-4809-9609-4bc257444590

If you are still experiencing the problem and that does not help, you could try one of these forums:

* [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
* [ntdev](http://www.osronline.com/showlists.cfm?list=ntdev)

Best of luck with this issue!
