### ISSUE TITLE
IRQL?

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#1704]
What IRQL is this IRP sent at?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6474f6a-b915-1e0d-eae1-eb86d16f58df
* Version Independent ID: 2edc375b-916f-b7a9-9b7b-16fa61ed0049
* Content: [IRP_MJ_SHUTDOWN - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/irp-mj-shutdown)
* Content Source: [windows-driver-docs-pr/kernel/irp-mj-shutdown.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/irp-mj-shutdown.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the question, Brian.

The PnP manager sends this IRP at IRQL<=APC_LEVEL in an arbitrary thread context.

I added that to the doc page, should be live soon.
