### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Atrious** [MicrosoftDocs/windows-driver-docs#1705]
The link to Download the kits and tools for windows is broken. https://go.microsoft.com/fwlink/p/?linkid=619491

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cbad219-645b-4478-e284-8136cb65f210
* Version Independent ID: b8628dca-0242-92c3-5830-b0c965c89438
* Content: [Universal Serial Bus (USB) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by EliotSeattle** [comment]
Thanks for pointing this out, @Atrious. 

I've updated that link with https://docs.microsoft.com/windows-hardware/drivers/download-the-wdk

Eliot
