### ISSUE TITLE
Need help on interpreting output

### ISSUE THREAD

**Issue by randomascii** [MicrosoftDocs/windows-driver-docs#1706]
I just ran heap -f and got a nice verbose report filled with very technical information. However without more documentation (or at least column headers) it is very difficult to interpret it, and impossible to draw any direct conclusions. For instance, what do *any* of the fields in this line mean:

0000014634a20540: 075f0 . 00020 [100] - free

What does "Total Free Size:      001c358b" mean - in my case I have a 380,000 KiB discrepancy between allocated bytes and heap private WS bytes (and another 42,000 KiB between private WS bytes and committed bytes) and the total free size doesn't come close to explaining that. Documentation and labels please. Thanks!

0:038&gt; !heap -f 00000145a3fd0000
Failed to read heap keySEGMENT HEAP ERROR: failed to initialize the extention
Index   Address  Name      Debugging options enabled
  6:   145a3fd0000 
    Segment at 00000145a3fd0000 to 00000145a3fdf000 (0000f000 bytes committed)
    Segment at 00000145a4340000 to 00000145a443f000 (000ff000 bytes committed)
    Segment at 00000145a4e30000 to 00000145a502f000 (001ff000 bytes committed)
    Segment at 00000145a5030000 to 00000145a542f000 (003ff000 bytes committed)
    Segment at 00000145a5800000 to 00000145a5fff000 (007ff000 bytes committed)
    Segment at 00000145aac00000 to 00000145abbcf000 (00fcf000 bytes committed)
    Segment at 00000145ac200000 to 00000145ad1cf000 (00fcf000 bytes committed)
    Segment at 00000145b0df0000 to 00000145b1dbf000 (00fcf000 bytes committed)
    Segment at 00000145b4460000 to 00000145b542f000 (00fcf000 bytes committed)
    Segment at 00000145b6c60000 to 00000145b7c2f000 (00fcf000 bytes committed)
    Segment at 00000145bbc00000 to 00000145bcbcf000 (00fcf000 bytes committed)
    Segment at 00000145bcbd0000 to 00000145bdb9f000 (00fcf000 bytes committed)
    Segment at 00000145c1790000 to 00000145c275f000 (00fcf000 bytes committed)
    Segment at 00000145c2e00000 to 00000145c3dcf000 (00fcf000 bytes committed)
    Segment at 00000145c5500000 to 00000145c64cf000 (00fcf000 bytes committed)
    Segment at 00000145c9200000 to 00000145ca1cf000 (00fc7000 bytes committed)
    Segment at 00000145cc900000 to 00000145cd8cf000 (00fc8000 bytes committed)
    Segment at 00000145cff80000 to 00000145d0f4f000 (00fc9000 bytes committed)
    Segment at 00000145d0f50000 to 00000145d1f1f000 (00fca000 bytes committed)
    Segment at 00000145d5360000 to 00000145d632f000 (00fc2000 bytes committed)
    Segment at 00000145d6330000 to 00000145d72ff000 (00fca000 bytes committed)
    Segment at 00000145d98b0000 to 00000145da87f000 (00fcf000 bytes committed)
    Segment at 00000145d7aa0000 to 00000145d8a6f000 (00fc1000 bytes committed)
    Segment at 00000145e3e70000 to 00000145e4e3f000 (00fca000 bytes committed)
    Segment at 00000145e5200000 to 00000145e61cf000 (00fcf000 bytes committed)
    Segment at 00000145ebff0000 to 00000145ecfbf000 (00fc7000 bytes committed)
    Segment at 00000145f3bd0000 to 00000145f4b9f000 (00fc8000 bytes committed)
    Segment at 0000014588a00000 to 00000145899cf000 (00fcf000 bytes committed)
    Segment at 0000014593600000 to 00000145945cf000 (00fbd000 bytes committed)
    Segment at 0000014599ce0000 to 000001459acaf000 (00fcf000 bytes committed)
    Segment at 00000145ef000000 to 00000145effcf000 (00fc2000 bytes committed)
    Segment at 00000145fdd70000 to 00000145fed3f000 (00fc1000 bytes committed)
    Segment at 00000145f15d0000 to 00000145f259f000 (00fc7000 bytes committed)
    Segment at 000001461a3a0000 to 000001461b36f000 (00fcf000 bytes committed)
    Segment at 000001461ce10000 to 000001461dddf000 (00fc1000 bytes committed)
    Segment at 000001462fa90000 to 0000014630a5f000 (00fc1000 bytes committed)
    Segment at 0000014633ba0000 to 0000014634b6f000 (00faf000 bytes committed)
    Segment at 000001463b760000 to 000001463c72f000 (00fb5000 bytes committed)
    Segment at 000001463dd50000 to 000001463ed1f000 (00fbd000 bytes committed)
    Segment at 0000014641eb0000 to 0000014642e7f000 (00fcf000 bytes committed)
    Segment at 000001464df10000 to 000001464eedf000 (00fba000 bytes committed)
    Segment at 0000014654020000 to 0000014654fef000 (00aca000 bytes committed)
    Flags:                00001002
    ForceFlags:           00000000
    Granularity:          16 bytes
    Segment Reserve:      25910000
    Segment Commit:       00002000
    DeCommit Block Thres: 00000400
    DeCommit Total Thres: 00001000
    Total Free Size:      001c358b
    Max. Allocation Size: 00007ffffffdefff
    Lock Variable at:     00000145a3fd02c0
    Next TagIndex:        0000
    Maximum TagIndex:     0000
    Tag Entries:          00000000
    PsuedoTag Entries:    00000000
    Virtual Alloc List:   145a3fd0110
    Uncommitted ranges:   145a3fd00f0
    FreeList[ 00 ] at 00000145a3fd0150: 00000146546c9210 . 0000014634a20550  
        0000014634a20540: 075f0 . 00020 [100] - free
        000001459404ed00: 06cf0 . 00020 [100] - free
        00000145e54ec590: 40530 . 00020 [100] - free
        0000014642605000: 06810 . 00020 [100] - free
        00000145f1978640: 00400 . 00020 [100] - free

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9e90c35-9fc6-4b94-1ddd-73539af3a86d
* Version Independent ID: fa14c946-421a-e1f2-1a56-9777b14a4bde
* Content: [heap - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-heap)
* Content Source: [windows-driver-docs-pr/debugger/-heap.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-heap.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@randomascii - I agree that parsing the output for !heap is a challenge. For specific guidance on the area of heap that you are looking at, I would look to the community forums:

•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

•	[OSR's ntdev List](https://community.osr.com/categories/ntdev)

•	[OSR's windbg List](https://community.osr.com/categories/windbg)

The docs point to and assume the "Windows Internals" book series as a pre-requisite knowledge. For better or worse we don't include that information in the docs. The memory chapter covers heap structures in detail.

If you think that the output for the !heap command should be changed and/or include additional labels consider filing product feedback using this channel: 

http://aka.ms/dexex 

Thanks for your interest in improving the debugger docs and good luck with your Windows memory research.
