### ISSUE TITLE
Application Verifier link is broken

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#1707]
It should point to this link since AppVerif is available with the debugger tools.

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c767c562-30ff-2f16-6584-33bbf2bf4781
* Version Independent ID: 9253ef49-c19f-7dd9-2a06-035a9fc132a1
* Content: [Testing a WDF Driver (KMDF or UMDF) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/testing-a-kmdf-driver)
* Content Source: [windows-driver-docs-pr/wdf/testing-a-kmdf-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/testing-a-kmdf-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @Shyamal-V I just pushed the fix.  Should be live in ~10 min
