### ISSUE TITLE
Broken Link, "Memory Allocation and Buffer Management"

### ISSUE THREAD

**Issue by dwkaiser** [MicrosoftDocs/windows-driver-docs#1708]
Should the link to "Memory Allocation and Buffer Management" on this page go to:

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/_kernel/#memory-allocation-and-buffer-management

This is the link accessed by the "Memory Allocation and Buffer Management" link on the "Windows Kernel-Mode Memory Manager" page at "https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/windows-kernel-mode-memory-manager".

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce947218-bd81-58a8-d89f-c3eba71c94b3
* Version Independent ID: 9fc8c805-69f1-a8f5-0d38-7e6e56dfff69
* Content: [Memory Management for Windows Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/managing-memory-for-drivers)
* Content Source: [windows-driver-docs-pr/kernel/managing-memory-for-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/managing-memory-for-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @dwkaiser and apologies for the delay.  You are exactly right, that's what that link was supposed to be.  I just pushed the change, and it should be reflected on the live site within 10-15 min.  Thanks for the feedback!
