### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by GregoryLand** [MicrosoftDocs/windows-driver-docs#1710]
The link "Boot Configuration Data" under related topics of this page https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-options-in-windows is broken.

Date: 2019-08-07

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf43d908-3c09-9ef2-2998-2b8d115a4967
* Version Independent ID: 25c9c362-8c20-bcf7-43ab-258249569bab
* Content: [Overview of Boot Options in Windows - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-options-in-windows#feedback)
* Content Source: [windows-driver-docs-pr/devtest/boot-options-in-windows.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/boot-options-in-windows.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @GregoryLand for pointing this out.

I removed the link. That topic has been migrated to our previous versions repo and is not supported any longer. For historic purposes, you can find it at https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bcd/boot-configuration-data-portal

Thanks,

Eliot
