### ISSUE TITLE
Multiple Versions of .pdb

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/windows-driver-docs#1716]
With reference to the line:
```
Note that multiple versions of .pdb symbol files (for example, public and private versions) cannot be stored on the same server, because they each contain the same signature and age.
```

Do we need a different location for Debug/Release/Architecture combinations? I thought that we wouldn't need that since the PDB would use a GUID that wouldn't stomp each other. (As in Debug/x86 would have a different GUID than Release/x64, etc.)

Is the line in the doc 100% correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c066ba05-c44b-60d2-0910-22de78448bc5
* Version Independent ID: 3aa09560-626c-874b-9f2c-363790c4987d
* Content: [SymStore - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symstore)
* Content Source: [windows-driver-docs-pr/debugger/symstore.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/symstore.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
Sorry for the length delay @csm10495. I was unable to track down any definitive information about having symbols in the same location or better test with a current build. My experience is that the symbols consumption code is pretty good about matching the signature where ever they are located. But as there are multiple tools, this statement may be for a sub set of the tooling.

If it's still an issue, you may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
•	[OSR's ntdev List](https://community.osr.com/categories/ntdev)
•	[OSR's windbg List](https://community.osr.com/categories/windbg)

Thanks again for reaching out and good luck with your work.
