### ISSUE TITLE
code should show how to do it in a KM driver

### ISSUE THREAD

**Issue by smadasam** [MicrosoftDocs/windows-driver-docs#1719]
How to set the property only shows the UM version, please show the KM version too:

this is from the code sample
#if defined(NTDDI_WIN10_RS2) && (NTDDI_VERSION &gt;= NTDDI_WIN10_RS2)

        //
        // Adding Custom Capability:
        //
        // Adds a custom capability to device interface instance that allows a Windows
        // Store device app to access this interface using Windows.Devices.Custom namespace.
        // This capability can be defined either in INF or here as shown below. In order
        // to define it from the INF, uncomment the section "OsrUsb Interface installation"
        // from the INF and remove the block of code below.
        //

        static const wchar_t customCapabilities[] = L"microsoft.hsaTestCustomCapability_q536wpkpf5cy2\0";

        status = g_pIoSetDeviceInterfacePropertyData(&symbolicLinkName,
                                                     &DEVPKEY_DeviceInterface_UnrestrictedAppCapabilities,
                                                     0,
                                                     0,
                                                     DEVPROP_TYPE_STRING_LIST,
                                                     sizeof(customCapabilities),
                                                     (PVOID)&customCapabilities);

        if (!NT_SUCCESS(status)) {
            TraceEvents(TRACE_LEVEL_ERROR, DBG_PNP,
                        "IoSetDeviceInterfacePropertyData failed to set custom capability property  %!STATUS!\n", status);
            goto Error;
        }

#endif

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218c9e10-b033-379d-f40e-be9655bcf41b
* Version Independent ID: bb44d042-ff6b-f155-98e5-e823994ebab3
* Content: [Hardware Support App (HSA) Steps for Driver Developers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/hardware-support-app--hsa--steps-for-driver-developers#feedback)
* Content Source: [windows-driver-docs-pr/devapps/hardware-support-app--hsa--steps-for-driver-developers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/hardware-support-app--hsa--steps-for-driver-developers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by tedhudek** [comment]
Thanks Sam and apologies for the delay.  I just pushed the fix.  It should appear on the live site this evening.
