### ISSUE TITLE
Broken Link "Code-signing for Protected Media Components in Windows Vista"

### ISSUE THREAD

**Issue by cow613** [MicrosoftDocs/windows-driver-docs#1720]
This is the correct link
http://download.microsoft.com/download/a/f/7/af7777e5-7dcd-4800-8a0a-b18336565f5b/pmp-sign.doc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93540672-755a-ad5e-e226-f8b1ce61ff80
* Version Independent ID: 99be7ed0-83a3-e8ef-b20b-865ebca374e8
* Content: [Introduction to Test-Signing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/introduction-to-test-signing#feedback)
* Content Source: [windows-driver-docs-pr/install/introduction-to-test-signing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/introduction-to-test-signing.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @cow613 and apologies for the delay.  I just pushed this change, should appear on the live site within half an hour.  Appreciate the feedback!
