### ISSUE TITLE
The DOCUMENTEVENT_XPS_xxx values in winddiui.h are different to the ones documented on this page

### ISSUE THREAD

**Issue by KutanaDev** [MicrosoftDocs/windows-driver-docs#1722]
The web page is out of sync with winddiui.h

The web page mentions DOCUMENTEVENT_XPS_COMMITJOB but there is no #define for DOCUMENTEVENT_XPS_COMMITJOB in winddiui.h

Likewise, winddiui.h #defines DOCUMENTEVENT_XPS_ADDFIXEDPAGEEPRE but there is no mention of DOCUMENTEVENT_XPS_ADDFIXEDPAGEEPRE on the web page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ea2ba0-e8b1-64ba-3506-b349ec7e2404
* Version Independent ID: 5bdce32d-2f29-c8d7-8b80-ee05302735bf
* Content: [XPS Driver Document Events - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/xps-driver-document-events)
* Content Source: [windows-driver-docs-pr/print/xps-driver-document-events.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/xps-driver-document-events.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@KutanaDev, thanks for pointing out the discontinuity of the information provided in the topic with the code in the winddiui.h header.

I'm adding the feedback you've provided to an internal work item to correct and update the XPS Driver Document Events topic.
