### ISSUE TITLE
C28118 - Wrong Summary in Description

### ISSUE THREAD

**Issue by dwkaiser** [MicrosoftDocs/windows-driver-docs#1724]
Currently, the Summary states:

warning: C28118: Copying a whole IRP stack entry leaves certain fields initialized that should be cleared or updated.

However, the actual description presented by Visual Studio 2017 is:

Warning C28118:  The current function is permitted to run at an IRQ level above the maximum permitted for '%func%' (%level%)…

It appears that the "Copying a whole IRP... cleared or updated." text was copied inadvertently into the start of this description from the summary description associated with the previous warning description (C28114).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0734674-d9d9-69f3-9e5a-f869097bd882
* Version Independent ID: b51cf4fd-a2e9-7b5c-0f86-e14b1d619891
* Content: [C28118 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/28118-irq-exceeds-caller?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C28118)%26rd%3Dtrue)
* Content Source: [windows-driver-docs-pr/devtest/28118-irq-exceeds-caller.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/28118-irq-exceeds-caller.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Eagle-eye catch, @dwkaiser 

Thanks for submitting the issue!

Eliot
