### ISSUE TITLE
Support win10?

### ISSUE THREAD

**Issue by thomasfuk** [MicrosoftDocs/windows-driver-docs#1729]
The msplot is support win10 32/64? I cannot find the sample in the latest wdk, thanks for help.
If not support, any sample for replacement? 
Any sample printer driver that is designed to support all Hewlett-Packard Graphics Language (HPGL/2) for win10 ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6554605-600d-3ff1-2f1f-9c327f91a7fa
* Version Independent ID: 37e1baa0-8c61-2616-e52e-a4907b074f90
* Content: [Plotter Driver Components - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/plotter-driver-components#feedback)
* Content Source: [windows-driver-docs-pr/print/plotter-driver-components.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/plotter-driver-components.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@thomasfuk, the MSPLOT driver sample was removed and is not available in the Windows 10 driver sample repo on GitHub.

Earlier versions of the MSPLOT Windows driver sample are archived at Microsoft Archive on GitHub:

- [Windows 8.1 driver samples](https://go.microsoft.com/fwlink/p/?LinkId=618052)

- [Windows 8 driver samples](https://go.microsoft.com/fwlink/p/?LinkId=616509)

For Windows 7, The MSPLOT sample was included in the [Windows Driver Kit Version 7.1.0](https://www.microsoft.com/download/details.aspx?id=11800).
