### ISSUE TITLE
Examples for everything would be really useful

### ISSUE THREAD

**Issue by M-Hamilton** [MicrosoftDocs/windows-driver-docs#1730]
There's nothing for Join, Intersect or Union (just for example). What is a "key selector method" exactly? And so on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a06a3c75-fe34-acfa-51ef-4296795e8f70
* Version Independent ID: 5c3bdaf5-eec2-3ea2-3c5b-f53f7b80b41b
* Content: [Using LINQ With the debugger objects - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/using-linq-with-the-debugger-objects#feedback)
* Content Source: [windows-driver-docs-pr/debugger/using-linq-with-the-debugger-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/using-linq-with-the-debugger-objects.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@M-Hamilton - Sorry for the delay here and thanks for your request. It's a great idea, but unfortunately, I continue to be tasked with high-priority tasks for the foreseeable future. You might want to ask for examples on the Windows Hardware WDK and Driver Development forum and OSR.
 
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
•	[OSR's windbg List](https://community.osr.com/categories/windbg)

Or if you do create any samples, feel free to submit it to the docs for consideration, using a commit.
Sorry I can't be of more help. Good luck in your work with LINQ and the debugger objects.
