### ISSUE TITLE
Incorrect statement

### ISSUE THREAD

**Issue by adipuscasu** [MicrosoftDocs/windows-driver-docs#1737]
This is the original phrase:
"This creates a new symbol file, C:\dir2\mysymbols.pdb, which does not contain any private symbols and does not contain the two global variables you listed in listfile.txt."
Since the issued command is 
"pdbcopy c:\dir1\mysymbols.pdb c:\dir3\mysymbols.pdb -p -f:@c:\temp\listfile.txt",
 the resulted pdb file will be located in c:\dir3 folder, hence the correct phrase is:
"This creates a new symbol file, C:\dir3\mysymbols.pdb, which does not contain any private symbols and does not contain the two global variables you listed in listfile.txt."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efb85109-af57-61f2-89d5-56b992c45dfd
* Version Independent ID: 5eca5171-e4f7-bf6d-3d6c-bc0c53643709
* Content: [Using PDBCopy - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/using-pdbcopy#feedback)
* Content Source: [windows-driver-docs-pr/debugger/using-pdbcopy.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/using-pdbcopy.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@adipuscasu - Thanks for catching this mistake, the topic has been updated.
