### ISSUE TITLE
Typo and possibly outdated info for Bug Check 0x12B

### ISSUE THREAD

**Issue by DarkDaskin** [MicrosoftDocs/windows-driver-docs#174]
[The corresponding docs page](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x12b---faulty-hardware-corrupted-page).

The header says that the bug check code is 0x12B, but the content says 0x00000128.

Also I got this bug check recently and all 4 parameters were non-zero while documentation says the last 2 are reserved and should be zero. Possibly the documentation was not updated when new values were added.

**Comment by barrygolden** [comment]
Thanks for filing the issue @DarkDaskin we'll review the information you've provided

**Comment by barrygolden** [comment]
@DarkDaskin the topic has been updated. Thanks for filing the issue.
