### ISSUE TITLE
Content is not correct..

### ISSUE THREAD

**Issue by vijaycognore** [MicrosoftDocs/windows-driver-docs#1740]
"When the Plug and Play) for the device to the device tree. The approach that you use to determine the parent of a device depends on how the device is currently configured in the system, as follows:"

See first sentence of above paragraph. Its wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39aec0d1-e043-1363-ac29-672edcf94a38
* Version Independent ID: f11c7551-56ee-deaa-b1b3-e616ea97f894
* Content: [Determining the Parent of a Device - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/determining-the-parent-of-a-device#feedback)
* Content Source: [windows-driver-docs-pr/install/determining-the-parent-of-a-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/determining-the-parent-of-a-device.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for spotting this @vijaycognore, and apologies in the delay getting back to you.  I've just fixed this problem.  You can see the fix at https://docs.microsoft.com/en-us/windows-hardware/drivers/install/determining-the-parent-of-a-device.
