### ISSUE TITLE
The material is quite complex and lacks any diagrams to help explain it

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/windows-driver-docs#1747]
This set of pages desperately needs some diagrams. Is there a description which is so, and/or that explains this material in a more understandable way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3edde2b4-b806-3772-b0e1-125908c4b28b
* Version Independent ID: 84677d18-20e0-cdc4-9cc4-a3a397b3fe58
* Content: [WDMAud Topology Parsing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/wdmaud-topology-parsing#feedback)
* Content Source: [windows-driver-docs-pr/audio/wdmaud-topology-parsing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/wdmaud-topology-parsing.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ericleigh - I agree that audio drivers are complex and a diagram could help here. Because of resource constraints it is not likely we will be able to do the work to improve this legacy content. The SYSVAD audio driver sample code can be the best path to learn about current day audio driver topology.

**Comment by ericleigh007** [comment]
Thanks, Don.

Don’t you think it is sort of a cop-out to agree that the content isn’t understandable but then say “resources are constrained”, but then close the problem report?  Why not leave it open so it can remain in the backlog?

Perhaps someone from OSR or other driver org could do a PR with a diagram?   If I learn enough to take a crack at it, I will do a PR myself, but that would require a lot of time.  My resources are more limited than yours!

-thanks for the overall excellent work on documentation.
-e

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
