### ISSUE TITLE
Value "0x5" for parameter 1

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#1750]
Please provide information about the meaning of the value "0x5" for parameter 1.
A dump file I've just analyzed had that value for the first parameter as well as the following information

FAILURE_BUCKET_ID:  0x119_5_DRIVER_FAULTED_SYSTEM_COMMAND_nvlddmkm!unknown_function
BUCKET_ID:  0x119_5_DRIVER_FAULTED_SYSTEM_COMMAND_nvlddmkm!unknown_function
PRIMARY_PROBLEM_CLASS:  0x119_5_DRIVER_FAULTED_SYSTEM_COMMAND_nvlddmkm!unknown_function

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7917857b-97bc-efec-67ab-5e3af061524c
* Version Independent ID: 8c00d20e-9b21-7bb0-a041-220aca9d2487
* Content: [Bug Check 0x119 VIDEO_SCHEDULER_INTERNAL_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x119---video-scheduler-internal-error#feedback)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - I worked with the dev team to document the 0x5 parameter. The 0x5 can be caused by the video driver code, so I as I now mention in the topic - checking for updated video card drivers, would be one thing to try.
