### ISSUE TITLE
A bit more feedback on what should happen

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/windows-driver-docs#1755]
I was confused by the output I got from WinDbg and WinDbg preview in the "Connection" step here: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-automatically#-restarting-the-target-pc
I was thinking that before this step, there should be some sort of indication of "correct" output from the debugger, like:

At this point, WinDbg output should look something like this, indicating that you've successfully initiated the connection:

'''
Microsoft (R) Windows Debugger Version 10.0.18914.1001 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.
Using NET for debugging
Opened WinSock 2.0
Using IPv4 only.
Waiting to reconnect...
'''

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e51b628-bb73-f32f-5a81-fefce12a4b49
* Version Independent ID: e07e2607-fd13-5517-510c-77bf717125c8
* Content: [Setting Up KDNET Network Kernel Debugging Automatically - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-automatically#-restarting-the-target-pc)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ericleigh007  - Thanks for this and the related issue. I added the output showing that the debugger is ready to connect and a few links to the getting started with debugger topics at the bottom of the topic.
