### ISSUE TITLE
What to do next

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/windows-driver-docs#1756]
It would be helpful to include information on what should be/can be done before this content, and after the previous step:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-automatically#troubleshooting-tips

Thinking like:
At this point, your kernel debug session is connected, and you can ....  {maybe link to next article talking about how to use the kernel debugging session}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e51b628-bb73-f32f-5a81-fefce12a4b49
* Version Independent ID: e07e2607-fd13-5517-510c-77bf717125c8
* Content: [Setting Up KDNET Network Kernel Debugging Automatically - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-automatically#-restarting-the-target-pc)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ericleigh007  - Thanks for this and the related issue. I added the output showing that the debugger is ready to connect and a few links to the getting started with debugger topics at the bottom of the topic.
