### ISSUE TITLE
This heading is more appropriately somewhere under 'File System Filter Drivers'

### ISSUE THREAD

**Issue by kyanha** [MicrosoftDocs/windows-driver-docs#1759]
This document should be moved under the 'File System Filter Drivers' heading, to simplify where someone implementing a filter driver should look.  (Either that, or a "see also" link should be added under that heading to ensure that people look here as well.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb3aee6c-10fa-7833-79f2-d7eec03e73c5
* Version Independent ID: 5c45a552-2cf3-13ba-8f9f-b76ceb580292
* Content: [Using ECPs to Process IRP_MJ_CREATE in File System Filter Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/using-ecps-to-process-irp-mj-create-operations-in-a-file-system-filter)
* Content Source: [windows-driver-docs-pr/ifs/using-ecps-to-process-irp-mj-create-operations-in-a-file-system-filter.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/using-ecps-to-process-irp-mj-create-operations-in-a-file-system-filter.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@kyanha, thanks for reporting this, and apologies that I was only now able to act on it. I've reorganized the entire File Systems table of contents, and have moved ECP info under the minifilter section, starting at [Introduction to Extra Create Parameters](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/introduction-to-extra-create-parameters).
