### ISSUE TITLE
Minor:  Should say WDF instead of KMDF

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#1761]
Instead of KMDF it should say "WDF (KMDF and UMDF V2) " so it is clear that it applies to both.

"framework calls a KMDF function or filter driver's event callback function"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e10578f-45fa-4666-15b9-67942520cd6a
* Version Independent ID: 779e15f8-0987-d4d2-b31c-c906f4830729
* Content: [Power-Up Sequence for a Function or Filter Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/power-up-sequence-for-a-function-or-filter-driver)
* Content Source: [windows-driver-docs-pr/wdf/power-up-sequence-for-a-function-or-filter-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/power-up-sequence-for-a-function-or-filter-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Just pushed a fix, should be live soon.
