### ISSUE TITLE
Clarification on MSISupported registry key

### ISSUE THREAD

**Issue by tzimmer1** [MicrosoftDocs/windows-driver-docs#1765]
https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/enabling-message-signaled-interrupts-in-the-registry

Hello.
Regarding the above documentation, in regards to Windows 10 we are seeing that the absence or presence of the MSISupported registry value seems to affect MSI programming.    We see MSI programming happening if MSISupported is both 0 and 1.

Can this be verified and updated in the above pages documentation?  Thanks.

**Comment by tedhudek** [comment]
Apologies for the delay.

If MSISupported is set to 0, the driver running on it will not be able to start with any MSI resource.

Do you mean something else (like MSI or MSI-X registers being touched in the PCI config space, from hardware perspective?)

Please reopen if necessary.
