### ISSUE TITLE
Certification

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [MicrosoftDocs/windows-driver-docs#1766]
i know it may not be the very correct place to that... but in lack of a better place i would say... that since those rules will change... it would be a good opportunity... for Microsoft to reviews its polices about signing drivers... for example... NVIDIA and AMD drivers.... are BUGGY on x86... (for example... not being PAE compatible) and even then they are getting WHQL certification... that should not be allowed in future...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e326d3e-833a-e312-d35d-11569690c7e6
* Version Independent ID: 7a9795cf-093e-a67f-8162-b832e1161ba8
* Content: [Deprecation of Software Publisher Certificates, Commercial Release Certificates, and Commercial Test Certificates - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates#feedback)
* Content Source: [windows-driver-docs-pr/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback and apologies for the delay.  Because this is a product/policy question rather than a doc issue, I'd recommend trying one of these forums:

* [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
* [ntdev](http://www.osronline.com/showlists.cfm?list=ntdev)
