### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mhatipovic** [MicrosoftDocs/windows-driver-docs#1767]
this sentence - INF fie:

Doing so can cause an inconsistency between the INF fie, the driver store catalog, and the driver in the driver store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d24db618-87b1-9fb6-42f5-d2c7072ac2e1
* Version Independent ID: f95ad7fe-3495-2ed7-4421-804f3c1c5013
* Content: [How Devices and Driver Packages are Uninstalled - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/how-devices-and-driver-packages-are-uninstalled#feedback)
* Content Source: [windows-driver-docs-pr/install/how-devices-and-driver-packages-are-uninstalled.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/how-devices-and-driver-packages-are-uninstalled.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Updated the note, thanks for the heads-up!
