### ISSUE TITLE
Values for REG_BINARY

### ISSUE THREAD

**Issue by pavel-a** [MicrosoftDocs/windows-driver-docs#1768]
It should be noted that the values for IgnoreHWSerNum should be one byte only, e.g. not 0x0000, 0x0001 but 0x01 or 0x00.
Maybe newer Windows versions can handle values of multiple bytes gracefully, but older versions may crash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32122b55-0ed3-e2df-4bc4-f37c52d5af65
* Version Independent ID: d24d5892-5cb7-05aa-f54a-db06d4f3b7d9
* Content: [USB Device Registry Entries - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-device-specific-registry-settings#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/usb-device-specific-registry-settings.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-device-specific-registry-settings.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Great observation @pavel-a, thanks for pointing that out. Little subtleties like that can make a difference during development. :) I'll go ahead and update the value for that key, and it should be live shortly. Thanks!
