### ISSUE TITLE
The page not found in this link

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windows-driver-docs#1770]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/issues/2
The links doesn't work in the en-us page either

@lindexi commented 10 hours ago — with docs.microsoft.com
https://www.usb.org/developers/hidpage/HID1_11.pdf page not found

https://www.usb.org/developers/hidpage/Hut1_12v2.pdf page not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba1cf2aa-effc-7b31-2540-470205e840f3
* Version Independent ID: 8b1f865f-a19e-0e96-1c1f-5c0206afe797
* Content: [Resources for HID over USB - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/reference-and-additional-details)
* Content Source: [windows-driver-docs-pr/hid/reference-and-additional-details.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/reference-and-additional-details.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @CeciAc, good eye. I've corrected the links to point to the new URLs on the USB website; those changes should be live shortly. Thanks for pointing this out!
