### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by Marmical** [MicrosoftDocs/windows-driver-docs#1775]
Address Mappings and MDLs link redirects to "Programming reference for WDK" index probably instead of the article that was intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29cf2a30-3b4d-4cec-33ff-1ed18e05c1e5
* Version Independent ID: 4c5683f8-157c-0a26-19d4-c65556e0e26b
* Content: [Using MDLs - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/using-mdls#feedback)
* Content Source: [windows-driver-docs-pr/kernel/using-mdls.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/using-mdls.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @Marmical for the report.  It's true there used to be a page by that name but apparently it went away.  I didn't see anything like it, so I removed the link.  The update should appear on the live site within a few minutes.
