### ISSUE TITLE
ACPI-table-load fail

### ISSUE THREAD

**Issue by star0716** [MicrosoftDocs/windows-driver-docs#1779]
Now many ACPI BIOS(BIOS vendor Insyde) have several SSDT tables, with same OEM ID and OEM Table ID, at this case, how to overload SSDT table?

In AMI ACPI BIOS, each SSDT table has different OEM ID and OEM Table ID, I can overload SSDT table successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146c2e57-a40b-33e0-c108-37f7555eda8a
* Version Independent ID: 81b0b392-c18a-f083-17fa-7e6dca629a52
* Content: [Microsoft ASL compiler - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/microsoft-asl-compiler#feedback)
* Content Source: [windows-driver-docs-pr/bringup/microsoft-asl-compiler.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/microsoft-asl-compiler.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. You may have success posting your question about ACPI SSDT tables in the following forums, where other hardware developers and Microsoft engineers can be found. The community there is quite responsive.

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
