### ISSUE TITLE
Error when attempting to install and start the debug USB driver

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/windows-driver-docs#1783]
Running into an error when the USB debug driver is installed and started, here:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-usb-3-0-debug-cable-connection#starting-a-debugging-session-for-the-first-time

To me, this documentation would be much improved if the NAME of the USB debug driver was listed here, so that any problems with it could be more easily understood, and/or worked around.

After snooping with procmon and deciding the name of the driver package is likely usb2dbg.inf, the error I'm getting in trying to get the USB 3.0 kernel debugger working is: 
Device USB\VID_3495&PID_00E0\123456789 had a problem starting.

Driver Name: oem92.inf
Class Guid: {36fc9e60-c465-11cf-8056-444553540000}
Service: USB2DBG
Lower Filters: 
Upper Filters: 
Problem: 0x34
Problem Status: 0xC0000428

...and I'm not able to make a connection with the target.

So is my snooping right?  Is that the proper name of the driver package?  Other than administrator priv, which is already required here, are there other possible failure points?

After doing a few more things, I wanted to add that it "appears" to be necessary to restart the host computer after the first-time debug session (where the driver gets installed), here:
[https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-usb-3-0-debug-cable-connection#starting-a-debugging-session](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-usb-3-0-debug-cable-connection#starting-a-debugging-session
))
-thanks
-e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeeb75fe-9c66-7d5b-ae4f-0fe9b6745300
* Version Independent ID: bee2ac4a-b55a-5691-3773-c87d5bd3c9b2
* Content: [Setting Up Kernel-Mode Debugging over a USB 3.0 Cable Manually - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-usb-3-0-debug-cable-connection#starting-a-debugging-session-for-the-first-time)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-usb-3-0-debug-cable-connection.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-usb-3-0-debug-cable-connection.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ericleigh007 - Thank you for this an the other issue. I worked with the debugger team to make updates to this topic. As it seems that the power issue comes up so often, we moved the guidance to disable the sleep for the associated USB devices to the regular setup steps. I also worked to better call out that a reboot of the target device is required. With some transports, sometimes it will connect on the fly, but the recommended work flow is to restart the target. The goal is that you shouldn't have to debug the transport itself, so at this point we won't be adding information on implementation of debugging transport code itself. "Inside Windows Debugging: A Practical Guide to Debugging and Tracing Strategies in Windows" by Tarik Soulami and the Windows Internals books may have some general  information on the debugger transport implementation details.  Thanks for your interest in improving the debugger documentation and good luck with your debugging work.
