### ISSUE TITLE
HyperLink broken

### ISSUE THREAD

**Issue by David-Zhiyuan-Zhu** [MicrosoftDocs/windows-driver-docs#1784]
The hyperlinks to XLATEOBJ and DEVINFO in this page are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 015a2e2e-8022-8582-0528-34509fa500c4
* Version Independent ID: 7c0deffe-225a-762c-860b-c8ef86ce5257
* Content: [Managing Display Palettes - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/managing-display-palettes#feedback)
* Content Source: [windows-driver-docs-pr/display/managing-display-palettes.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/managing-display-palettes.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@David-Zhiyuan-Zhu , thanks for reporting these broken links - they are now fixed!
