### ISSUE TITLE
Suggest moving the content from the "Troubleshooting" section into the main line, since things won't work without turning off power controls

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/windows-driver-docs#1786]
I strongly suggest moving the troubleshooting section content from here:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-usb-3-0-debug-cable-connection#troubleshooting-tips-for-debugging-over-usb-30

To just before here:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-usb-3-0-debug-cable-connection#starting-a-debugging-session-for-the-first-time

Reason: this isn't optional:  Things just won't work without doing this, so it makes more sense to just make them steps in the same section that deals with USBView.

-thanks
-e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeeb75fe-9c66-7d5b-ae4f-0fe9b6745300
* Version Independent ID: bee2ac4a-b55a-5691-3773-c87d5bd3c9b2
* Content: [Setting Up Kernel-Mode Debugging over a USB 3.0 Cable Manually - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-usb-3-0-debug-cable-connection)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-usb-3-0-debug-cable-connection.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-usb-3-0-debug-cable-connection.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ericleigh007 -  Thanks for this input. From what I understand is that there may be situations where a connection will work with out having to change this specific power setting. So I understand this is something you needed to do, but don't believe that it is a strict requirement.

There are certainly reasons to use USB debugging, but for future reference, the easiest path to connect a debugger is to use the kdnet utility that configures the KDNET transport as described in: [Setting Up KDNET Network Kernel Debugging Automatically](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-automatically).
