### ISSUE TITLE
CAPABILITIES does not exist

### ISSUE THREAD

**Issue by legendddhgf** [MicrosoftDocs/windows-driver-docs#1795]
The current JEDEC spec has CAPABILITIES0 at (0, 0x10) and CAPABILITIES1 at (0, 0x11), and both should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b18cc48-caf5-cca0-1755-4c9c7e157364
* Version Independent ID: bda4b071-14e8-cf46-9226-ed315905848d
* Content: [Get NVDIMM-N Identification (Function Index 1) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/get-nvdimm-n-identification--function-index-1-#feedback)
* Content Source: [windows-driver-docs-pr/storage/get-nvdimm-n-identification--function-index-1-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/get-nvdimm-n-identification--function-index-1-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@legendddhgf , thanks for catching and reporting this. I've updated the page accordingly.
