### ISSUE TITLE
Please update listed Windows 10 operating system for In Service Publish Information

### ISSUE THREAD

**Issue by hatasum** [MicrosoftDocs/windows-driver-docs#1797]
Please update listed Windows 10 operating system for In Service Publish Information.
In Parter center Web site, 19H1 is called NineteenH1. How to set from api? 19H1 or NineteenH1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bc8605-acf7-615b-3821-2f509d2a1e63
* Version Independent ID: 626ad255-cdba-6eb3-9f35-f3f688e343b4
* Content: [Get shipping label data - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-shipping-labels#in-service-publish-information-object)
* Content Source: [windows-driver-docs-pr/dashboard/get-shipping-labels.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-shipping-labels.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @balapv
* Microsoft Alias: **balapv**

**Comment by EliotSeattle** [comment]
Thanks, @hatasum 

Oops. Thanks for catching this. They are now updated with 19H1.

Eliot
