### ISSUE TITLE
Code example problem

### ISSUE THREAD

**Issue by alextechcc** [MicrosoftDocs/windows-driver-docs#1799]
Does the code in the second block check the opposite condition that it should?

IE
NameLength > InputBufferLength - FIELD_OFFSET
instead of
InputBufferLength - FIELD_OFFSET > NameLength

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c9648c0-e775-0338-4150-3c1e7329abe8
* Version Independent ID: d955e6cd-d2c3-cabf-4ec3-b17a693ce473
* Content: [Failure to Validate Variable-Length Buffers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/failure-to-validate-variable-length-buffers#feedback)
* Content Source: [windows-driver-docs-pr/kernel/failure-to-validate-variable-length-buffers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/failure-to-validate-variable-length-buffers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Absolutely right @alextechcc! Thanks for the sharp eye, and apologies for the delay making the fix. I corrected the direction of the greater than operator, and added some parenthetical remarks around the example to help make it less of a brain twister, hopefully. The update should appear on the live site within a few minutes.
