### ISSUE TITLE
USB-IF certification page has broken links to USB.org resources

### ISSUE THREAD

**Issue by PFroese** [MicrosoftDocs/windows-driver-docs#1809]
usb.org website was revamped earlier this year.  Most of the resource links to official usb-if pages are broken in the docs.microsoft.com page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9dc15f3-a1f1-5e87-cfe9-f8b235c7d369
* Version Independent ID: cac18c72-ef30-9a0a-2c0f-acab85ab7b23
* Content: [USB-IF Certification Tests - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-if-certification-tests)
* Content Source: [windows-driver-docs-pr/usbcon/usb-if-certification-tests.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-if-certification-tests.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by billlattimer** [comment]
@PFroese thanks for calling this out; links updated and planning further page updates.
