### ISSUE TITLE
The log file name cannot be customized

### ISSUE THREAD

**Issue by wanglei1355** [MicrosoftDocs/windows-driver-docs#1814]
I failed to change the log file name from default value to my own with command:
traceview -start mydriver -f c:\mydriver.etl
After this command executed, the log file name didn't change but the default value c:\logfile.etl
My traceview version is 2.1.1.
Is this a bug of the tool or my mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e400448d-0848-ef95-f9ed-cba41fc4b974
* Version Independent ID: 9f8e9458-bb9b-0292-0a85-97875e06e3a3
* Content: [TraceView Control Commands - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/traceview-control-commands)
* Content Source: [windows-driver-docs-pr/devtest/traceview-control-commands.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/traceview-control-commands.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @wanglei1355 
Thanks for the question. You are correct, that is a bug in TraceView; however, TraceView is deprecated. You should use [TraceLog](https://docs.microsoft.com/windows-hardware/drivers/devtest/tracelog) for this action.
Hope this helps.
Eliot
