### ISSUE TITLE
Missing Parameter 1 0x3470

### ISSUE THREAD

**Issue by MALEMization** [MicrosoftDocs/windows-driver-docs#1815]
I have seen many parameter reports regarding Memory Management however I haven't seen this one on your list! Please update and thanks! Sorry for many edits: Completely new to GitHub! Hopefully I'm doing this correctly...

    <Provider Name="Microsoft-Windows-Kernel-Power" Guid="{331c3b3a-2005-44c2-ac5e-77220c37d6b4}" />
    <EventID>41</EventID>
    <Version>6</Version>
    <Level>1</Level>
    <Task>63</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000400000000002</Keywords>
    <TimeCreated SystemTime="2019-10-15T01:14:02.498048100Z" />
    <EventRecordID>4730</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="8" />
    <Channel>System</Channel>
    <Computer>DESKTOP-G8IIL19</Computer>
    <Security UserID="S-1-5-18" />
    <EventData>
    <Data Name="BugcheckCode">26</Data>
    <Data Name="BugcheckParameter1">0x3470</Data>
    <Data Name="BugcheckParameter2">0xffffa603e09df000</Data>
    <Data Name="BugcheckParameter3">0xa6e9fbc8a2515bb0</Data>
    <Data Name="BugcheckParameter4">0xa669fbc8a2515bb0</Data>
    <Data Name="SleepInProgress">0</Data>
    <Data Name="PowerButtonTimestamp">0</Data>
    <Data Name="BootAppStatus">0</Data>
    <Data Name="Checkpoint">0</Data>
    <Data Name="ConnectedStandbyInProgress">false</Data>
    <Data Name="SystemSleepTransitionsToOn">0</Data>
    <Data Name="CsEntryScenarioInstanceId">0</Data>
    <Data Name="BugcheckInfoFromEFI">false</Data>
    <Data Name="CheckpointStatus">0</Data>

**Comment by DOMARS** [comment]
@MALEMization - As I look at this debug output, I think this is for bug check code 0x26 -  CDFS_FILE_SYSTEM. If this is for adding 0x3470 to 0x1A memory management, I have issue 1994 tracking that. 

In the future, what works best is to open an issue against the specific bug check topic. 

For general information on working with bug checks, this forum is useful and recommended.

• [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

Good luck with your debugging work.
