### ISSUE TITLE
Driver publish to Catalog

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs#1820]
If I don't check the Limit Public Disclosure of this Shipping Label information. box in New Shipping Label page, is the driver by default going to show up in list pf Windows Update Catalog and WSUS catalog regardless the driver is Optional or Critical?

**Comment by EliotSeattle** [comment]
Hi @guliteb 
I checked with the dashboard team, and they said yes, it will show up.
Thanks for your patience.
Eliot
