### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by karora23** [MicrosoftDocs/windows-driver-docs#1822]
The first line of page should read "Set up a W..... not ......h as" instead of "Set up a W..... note ......h as".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 268c2886-a171-3d0a-120c-7ebb00baf625
* Version Independent ID: fde18a37-043a-a863-4a14-12da5345af06
* Content: [Setting Up the Web Site - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-the-web-site#feedback)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-the-web-site.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-the-web-site.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
What a difference an "e" makes! Fixed and pushed live. Should be visible in a few minutes.

Thanks for the help, @karora23
