### ISSUE TITLE
stuck at windbg reconnect

### ISSUE THREAD

**Issue by Umamaheshallenki** [MicrosoftDocs/windows-driver-docs#1824]
While preparing the test set up to debug windows kernel driver StorNVMe, windbg window is stuck at reconnect. I have rebooted the target system and then checked windbdg connection, still showing as reconnect...

Pinged host ip address on target system and it is working.

I have installed windbg preview.  May I know what`s the wrong? what else I can check to progress?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e51b628-bb73-f32f-5a81-fefce12a4b49
* Version Independent ID: e07e2607-fd13-5517-510c-77bf717125c8
* Content: [Setting Up KDNET Network Kernel Debugging Automatically - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-automatically#feedback)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Umamaheshallenki - Thanks for reaching out to the Windows Driver Developer Documentation team.  Sorry that the debugger is not connecting for you. You can double check the firewall settings, confirm you are using a supported adapter and perhaps confirm with Ping that the network settings you are using are still correct.
 Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
Good luck with getting connected.
