### ISSUE TITLE
Missing documentation for KeShouldYieldProcessor 

### ISSUE THREAD

**Issue by jtippet** [MicrosoftDocs/windows-driver-docs#1825]
The function `KeShouldYieldProcessor` is in the WDK's header wdm.h, but it is missing a reference page.  You can mail me at microsoft.com if you need a developer contact to provide or review the spec.

**Comment by tedhudek** [comment]
Verified, I'll work on this.

**Comment by oxfordmk** [comment]
KeShouldYieldProcessor() sounds like a useful function, but unless it is documented it's not something we can rely on using.

**Comment by tedhudek** [comment]
Just added https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-keshouldyieldprocessor.  Thanks for the suggestion @jtippet
