### ISSUE TITLE
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-engine-and-extension-apis

### ISSUE THREAD

**Issue by BrianCatlin** [MicrosoftDocs/windows-driver-docs#183]
The Build tool hasn't been used or distributed with the WDK for many years. Everything must be built using Visual Studio

**Comment by tedhudek** [comment]
@DOMARS please review

**Comment by DOMARS** [comment]
I will investigate.

**Comment by DOMARS** [comment]
I have a docs fix on the way. Thanks for catching this.

**Comment by DOMARS** [comment]
Docs fix was posted, thanks again for calling out this issue.
