### ISSUE TITLE
sign using Certum Standard Code Signing Certificate in the Cloud

### ISSUE THREAD

**Issue by kdkaushik** [MicrosoftDocs/windows-driver-docs#1831]
can I use [Certum Standard Code Signing Certificate in the Cloud](https://sslretail.com/certum-standard-code-signing-certificate/) to sign exe file?

**Comment by EliotSeattle** [comment]
Hi @kdkaushik 
Is this in regard to driver distribution or something else?
Thanks,
Eliot

**Comment by EliotSeattle** [comment]
No response.
