### ISSUE TITLE
Thanks to All authors

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1832]
I am able  enable or disable driver verifier  commands  successfully.
I did various types of  test uisng different commands for  different  system drivers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e566c865-f476-1ffa-242a-b7679b0b6115
* Version Independent ID: 4f6e4b0e-cf22-99d6-f00d-0442b137afb2
* Content: [Driver Verifier - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/driver-verifier#feedback)
* Content Source: [windows-driver-docs-pr/devtest/driver-verifier.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/driver-verifier.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Excellent, @RAJU2529 
Thanks for the shout out. Glad things are working for you.
Eliot
