### ISSUE TITLE
Typo in help command.

### ISSUE THREAD

**Issue by Temppus** [MicrosoftDocs/windows-driver-docs#1833]
glags /? instead of gflags /?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a2a343-17bf-477c-4ec3-c1b3baf7528d
* Version Independent ID: 89340c44-adea-9d15-d60a-b2864d1dbc1b
* Content: [GFlags Commands - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags-commands#feedback)
* Content Source: [windows-driver-docs-pr/debugger/gflags-commands.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/gflags-commands.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Thanks, @Temppus 
While I'd like to make a joke about how glags /?  gives you the version of help from the prior release, I'll just avoid the overt dad joke and stick to saying Thanks!!
Eliot
