### ISSUE TITLE
WDK for Visual2015

### ISSUE THREAD

**Issue by v34integration** [MicrosoftDocs/windows-driver-docs#1834]
Can't find SDK and WDK for visual 2015.

**Comment by EliotSeattle** [comment]
Hi @v34integration 

The WDK and SDK releases are optimized for the latest versions of Visual Studio, though they are compatible with some earlier versions. Take a look at [Other WDK downloads](https://docs.microsoft.com/windows-hardware/drivers/other-wdk-downloads) to see where current kits can be used with Visual Studio 2015.

Thanks,
Eliot
