### ISSUE TITLE
USB topic link

### ISSUE THREAD

**Issue by turkycat** [MicrosoftDocs/windows-driver-docs#1837]
The USB link under "related topics" on this page links to windows-hardware/drivers main page. should this be:

https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/universal-serial-bus--usb-
or 
https://docs.microsoft.com/en-us/windows-hardware/drivers/image/usb-driver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 539443c3-e464-bfc9-db85-3331ff2ab645
* Version Independent ID: e0defe40-221c-982a-0629-e2df395c48c4
* Content: [Overview of developing Windows drivers for emulated USB devices (UDE) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/developing-windows-drivers-for-emulated-usb-host-controllers-and-devices)
* Content Source: [windows-driver-docs-pr/usbcon/developing-windows-drivers-for-emulated-usb-host-controllers-and-devices.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/developing-windows-drivers-for-emulated-usb-host-controllers-and-devices.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @duncanmacmichael
* Microsoft Alias: **dumacmic**

**Comment by duncanmacmichael** [comment]
Hi @turkycat, good eye finding this. The link should be pointing here, to the main USB programming guide: https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/

I've updated the link, and the fix should be live within a few minutes. Thanks!
