### ISSUE TITLE
Suitable WDK version for Windows 7 service pack 1 and visual studio Prof. 2015

### ISSUE THREAD

**Issue by grfadaei** [MicrosoftDocs/windows-driver-docs#1850]
Hi everybody!
I have Visual studio 2015 prof. on Windows 7 service pack 1, What version of WDK is suitable for this combination?
B.R

**Comment by EliotSeattle** [comment]
Hi @grfadaei 
For information about earlier versions of the Windows Driver Kit (WDK), Enterprise WDK (EWDK), and additional downloads for support purposes, see [https://docs.microsoft.com/windows-hardware/drivers/other-wdk-downloads](https://docs.microsoft.com/windows-hardware/drivers/other-wdk-downloads).

You may also have success posting your question in the following forums, where other driver developers and Microsoft  engineers can be found. The communities there are quite responsive.
- [Windows Hardware WDK and driver development forum](https://social.msdn.microsoft.com/Forums/windowshardware/en-US/home?forum=wdk)
- [OSR NTDEV forum](http://www.osronline.com/cf.cfm?PageURL=showlists.cfm?list=NTDEV)
