### ISSUE TITLE
Virtfile.sys company

### ISSUE THREAD

**Issue by cerus-dhc** [MicrosoftDocs/windows-driver-docs#1856]
Virtfile.sys belongs to Veritas, not Symantec

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a2d558e-1073-85d5-f863-5bdbf6e3ddc6
* Version Independent ID: 62e4d735-803f-7608-154b-7032dc1ceb3d
* Content: [Allocated Altitudes - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/allocated-altitudes#feedback)
* Content Source: [windows-driver-docs-pr/ifs/allocated-altitudes.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/allocated-altitudes.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@cerus-dhc, thanks for reporting this - I've updated the page!
