### ISSUE TITLE
Missing IRP_MJ_CREATE_NAMED_PIPE

### ISSUE THREAD

**Issue by jamesmcguirepro** [MicrosoftDocs/windows-driver-docs#1857]
IRP_MJ_CREATE_NAMED_PIPE is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6922703-f07d-1e23-a47e-c9a5acb53c9c
* Version Independent ID: a3c38b35-df72-56a7-a2b3-21af82476d48
* Content: [IRP_MJ_INTERNAL_DEVICE_CONTROL - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-internal-device-control)
* Content Source: [windows-driver-docs-pr/ifs/irp-mj-internal-device-control.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/irp-mj-internal-device-control.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@jamesmcguirepro , thanks for reporting this. I've created pages for both [IRP_MJ_CREATE_NAMED_PIPE](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-create-named-pipe) and [IRP_MJ_CREATE_MAILSLOT](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-create-mailslot), along with FLT_PARAMETERS equivalents for minifilters ([FLT_PARAMETERS for IRP_MJ_CREATE_MAILSLOT](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/flt-parameters-for-irp-mj-create-mailslot) and [FLT_PARAMETERS for IRP_MJ_CREATE_NAMED_PIPE](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/flt-parameters-for-irp-mj-create-named-pipe)).
