### ISSUE TITLE
More accurate info

### ISSUE THREAD

**Issue by laishiekai** [MicrosoftDocs/windows-driver-docs#1860]
The example is marked as c++ but it's actually not.
No explanation for 1.3.6.1.5.5.7.3.3, what does that mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b25f0f-6898-0e7a-ae15-cf609e167a77
* Version Independent ID: b0907ff5-7e18-5dfa-72d5-02c9be59691b
* Content: [Creating Test Certificates - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/creating-test-certificates)
* Content Source: [windows-driver-docs-pr/install/creating-test-certificates.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/creating-test-certificates.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Just pushed a fix - sorry for the delay!
