### ISSUE TITLE
Bổ sung các dòng lệnh DBH

### ISSUE THREAD

**Issue by Dinhhai94** [MicrosoftDocs/windows-driver-docs#1867]
DBH=d+h+b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e01c1f-c5bb-08d6-60e9-efadf50f02e6
* Version Independent ID: f70951f4-57e5-b5e5-32e3-a5a105390f8c
* Content: [DBH - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/dbh)
* Content Source: [windows-driver-docs-pr/debugger/dbh.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/dbh.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
Xin chào @Dinhhai94 - I'm not able to determine what specific issue you are seeing with this topic, using translated text strings. The comments may indicate command line samples, but we have a topic that provides DBH command line samples - https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/additional-dbh-examples

As we have many users of these tools, the best option for general questions, is to post a specific question on the forums.

•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

Good luck with your debugging.
