### ISSUE TITLE
Broken outbound link ("Buy an Entrust EV code signing cert")

### ISSUE THREAD

**Issue by darianmiller** [MicrosoftDocs/windows-driver-docs#1870]
Current outbound link results in a "Page Not Found" error
https://www.entrustdatacard.com/products/categories/digital-signing-certificates/compare-entrust-code-signing-certificates#ev-code-signing-certificates

Suggested new link:
https://www.entrustdatacard.com/products/digital-signing-certificates/code-signing-certificates

**Comment by darianmiller** [comment]
Source: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#feedback

**Comment by EliotSeattle** [comment]
Thanks for the catch, @darianmiller 
Fixed in commit 1b62776
