### ISSUE TITLE
Broken MS link ("Add or Update a code signing certificate.")

### ISSUE THREAD

**Issue by darianmiller** [MicrosoftDocs/windows-driver-docs#1871]
In the Next Steps section, the link in this line is broken:  "If you’ve already set up a Partner Center account and need to renew a certificate, follow the steps in Add or Update a code signing certificate."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d3f097-d81b-66c2-4835-d63758687d34
* Version Independent ID: fe9d1cdd-966e-89b5-c66b-60531b0ec655
* Content: [Get a code signing certificate - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks for the catch, @darianmiller 
Fixed in commit 1b62776
