### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by KappaRan** [MicrosoftDocs/windows-driver-docs#1882]
https://go.microsoft.com/fwlink/p/?linkid=62651

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88adfdea-1e88-ef02-d639-4d44b65730fc
* Version Independent ID: 65bf0f14-bd82-d72d-be80-49948d0e83ea
* Content: [Windows Metadata and Internet Services - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/windows-metadata-and-internet-services#feedback)
* Content Source: [windows-driver-docs-pr/install/windows-metadata-and-internet-services.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/windows-metadata-and-internet-services.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by RAJU2529** [comment]
@wdkbot. This issue is  duplicate, same user already created another request #1883, so close
