### ISSUE TITLE
Typo in the policy name throughout, should be AllSigningEqual

### ISSUE THREAD

**Issue by happybear88** [MicrosoftDocs/windows-driver-docs#1886]
[Enter feedback here]
The page repeatedly refers to AllSign**ers**Equal, while the actual policy is AllSign**ing**Equal.

Refer to https://www.microsoft.com/en-us/download/details.aspx?id=57464 and search for the correct policy name. 

> HKLM\Software\Policies\Microsoft\Windows\DeviceInstall\Settings!AllSigningEqual

--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229274ee-21fe-ffe1-ea81-c4c42c1c4195
* Version Independent ID: 824f3f1f-129c-7127-03cf-d5fe1ecba309
* Content: [AllSignersEqual Group Policy - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/allsignersequal-group-policy--windows-vista-and-later-#feedback)
* Content Source: [windows-driver-docs-pr/install/allsignersequal-group-policy--windows-vista-and-later-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/allsignersequal-group-policy--windows-vista-and-later-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by aviviano** [comment]
Thanks @happybear88. The fix is now up.
