### ISSUE TITLE
Simple and Clear- Thanks to all Authors

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1891]
This article is simple and clear, I have experienced same pop up message came in windows 7. 
Now i am using windows 10 and moreover, i modified TDR registry keys as my consideration.
Keep writing new articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183014ea-33ba-2cc6-631d-e66f467e4eae
* Version Independent ID: 3d5b60be-2d04-289f-636d-6b5c53f745aa
* Content: [TDR Error Messaging - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-error-messaging)
* Content Source: [windows-driver-docs-pr/display/tdr-error-messaging.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/tdr-error-messaging.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@raju2529, thanks for your feedback! I'm closing this issue, and will follow up on your other issue (#1892) when I am able (we're in the midst of a release, so I might not get to it until January, sorry).
