### ISSUE TITLE
Is there any TDR changes in windows 10-Article is good.

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1892]
Nowadays many computers are running Windows 10 OS with UEFI enabled. And windows 8 is entirely different than windows 10. Is there any TDR  chances in windows 10.
I think this article is mainly for the driver development designer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c843e3a-49bf-48d5-74a3-025288c80521
* Version Independent ID: 54c49fb9-150c-dc1a-366c-409cbe76f0b3
* Content: [TDR changes in Windows 8 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-changes-in-windows-8)
* Content Source: [windows-driver-docs-pr/display/tdr-changes-in-windows-8.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/tdr-changes-in-windows-8.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@RAJU2529 , I was finally able to spend some time on this issue - apologies for the delay! I've updated this page to reflect that it applies to Windows 8 and later versions of the OS. You are correct that this article is for driver developers (and not for end users) - I've reworked the TDR pages to make this more clear. Thanks for filing the issue.
