### ISSUE TITLE
Simple and Clear

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1893]
Till now, I learned the definition of the driver is different. But after reading this article with graphical diagrams. I learned new things, I wondered there are many drivers are available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09bf2768-65ed-dbbd-a5ce-e3cd5ab58aa6
* Version Independent ID: 1169dfa4-e2c0-62e4-0bfa-42bab3ed1ade
* Content: [What is a driver - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/gettingstarted/what-is-a-driver-)
* Content Source: [windows-driver-docs-pr/gettingstarted/what-is-a-driver-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/what-is-a-driver-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks so much, @RAJU2529 
Appreciate the message!
Eliot
