### ISSUE TITLE
Does InfVerif support Recursive mode?

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs#1895]
Does InfVerif support Recursive mode to automatically go through INFs under all sub-folders?

**Comment by RAJU2529** [comment]
@guliteb. today I will  check on my system

**Comment by RAJU2529** [comment]
I have checked recursive mode does not support

**Comment by guliteb** [comment]
@RAJU2529 , Thanks for reply. Is it going to be added to backlog as new feature?

**Comment by RAJU2529** [comment]
@guliteb. Sorry I dont know that, I think infverif application desinger must and should consider this feature to add.

**Comment by EliotSeattle** [comment]
Added description for the /recurse parameter. It's been in the tool for a while, but it got left out of the list in *infverif /?*
Added to master branch and should be live shortly.
Eliot
