### ISSUE TITLE
Auto-table rendering is not helping legibility

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs#1899]
Hey Lori,

In order to fully grock what this pages was saying I had to read the markup, which is never a good sign.

There is no doubt that the information is invaluable (I hate the "read oplocks are advisory" by the way, but that's not your fault), but I feel sure that there is a better way to present it.

In particular 
* The `<hline/>`s  which sort of divide the rows confuse - particularly the ones which have a `rowspan="2"` in the left hand column. (ie between `<td><p>If the oplock is broken</p>` and `<td><p>Broken on IRP_MJ_WRITE when:</p>`
* The words "Request Type", whilst accurate misled me.  "Oplock type" might be easier.  And "Conditions" isn't really helpful either.  "Description?" maybe?
* Maybe if the whole table was rendered with a border things would be clearer (so the 
```<p>Level 1</p>
<p>Batch</p>
<p>Filter</p>;
<p>;Read-Handle</p>
<p>Read-Write</p>;
<p>Read-Write-Handle</p>
```
things would all be more obviously grouped.

I am not a writer (I'm a software engineer which is often quite the opposite) so I have no real guidance and I'm sorry because this sort of renders this as "This page sucks, fix it", which isn't the motivation here.

The good news though is it looks like this is a leitmotif for all 7 pages.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1bcbad7-4baa-eeac-ef5f-f99bc5dcc90c
* Version Independent ID: 4bcde48e-f7f2-82c2-6ec0-ed0adeb90fbe
* Content: [Checking the Oplock State of an IRP_MJ_WRITE operation - Windows drivers](https://docs.microsoft.com/en-gb/windows-hardware/drivers/ifs/irp-mj-write2)
* Content Source: [windows-driver-docs-pr/ifs/irp-mj-write2.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/irp-mj-write2.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , thanks for pointing out the parsing difficulty on this page, and for working with me behind the scenes on optimizing readability! I've updated this page, along with all other IRP_MJ_xxx oplock pages (except for IRP_MJ_CREATE, which seems to have a special case for every single oplock type).
