### ISSUE TITLE
Link to MBIM specs is broken

### ISSUE THREAD

**Issue by hiepkhuuMS** [MicrosoftDocs/windows-driver-docs#1916]
Please update with correct the MBIM 1.0 specs link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bb57675-1890-5529-2e52-be19aeabe221
* Version Independent ID: caee0f97-a9b4-fdf5-c3c2-f3474786e4d0
* Content: [Developing apps using multiple PDP contexts - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/mobilebroadband/developing-apps-using-multiple-pdp-contexts#feedback)
* Content Source: [windows-driver-docs-pr/mobilebroadband/developing-apps-using-multiple-pdp-contexts.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/mobilebroadband/developing-apps-using-multiple-pdp-contexts.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by aviviano** [comment]
Thanks @hiepkhuuMS for letting us know about this issue. These links have been updated.
