### ISSUE TITLE
"NDIS 6.0 and later and later and later versions"

### ISSUE THREAD

**Issue by elieux** [MicrosoftDocs/windows-driver-docs#1921]
Seems like some global substitution gone wrong. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b322dc25-6801-f71f-e2a1-952545db3c09
* Version Independent ID: bfd7c6d3-ef58-9e93-e9f8-f55cb08a02bd
* Content: [OID_GEN_PHYSICAL_MEDIUM - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-physical-medium#feedback)
* Content Source: [windows-driver-docs-pr/network/oid-gen-physical-medium.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/oid-gen-physical-medium.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by billlattimer** [comment]
@elieux thanks for the catch on this; I've corrected.
