### ISSUE TITLE
Does UAC2.0 inbox driver support USB selective suspend?

### ISSUE THREAD

**Issue by lixiaogangkkk** [MicrosoftDocs/windows-driver-docs#1922]
Does UAC2.0 inbox driver support USB selective suspend? I have my USB audio codec support UAC2.0 and Jack sense. But the USB audio device on the thunderbolt (type-c) dock can not enter into selective suspend (D2) while there is no Jack or no audio stream (both playback and recording), the device keep in D0 state which costs more power and block the device pass thunderbolt certification.

Thanks,
Steven

**Comment by DOMARS** [comment]
@lixiaogangkkk - On your questions, unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
Windows Hardware WDK and Driver Development
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk
OSR's ntdev List
https://www.osronline.com/showlists.cfm?list=ntdev

If you are able to attach a debugger there are some power specific commands that may provide additional information for example !powertriage.

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-powertriage

If you believe there is a power management issue with the driver not associated with a specific OEM's implementation of audio, you can follow the guidance here to file Windows feedback, using the feedback hub.

https://matthewvaneerde.wordpress.com/2016/09/26/report-problems-with-logs-and-suggest-features-with-the-feedback-hub/

Best of luck with your work.
