### ISSUE TITLE
Is article only for OEM vendors or for endusers

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#1923]
Many components explained in this article i cant understand, so i think this article for OEM vendors.

Is there any special tool is  available to get all the required details from the BIos or motherboard 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddd8d0d4-08cf-039d-25cd-5f32cd45797f
* Version Independent ID: 9d8e6ed9-ce8b-2e70-fac2-1b56017a34a4
* Content: [ACPI system description tables - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/acpi-system-description-tables)
* Content Source: [windows-driver-docs-pr/bringup/acpi-system-description-tables.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/acpi-system-description-tables.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
The content in this section is targeted to OEMs and IHVs that are building Windows devices.

You may have success posting additional questions in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
