### ISSUE TITLE
Outdated for 1903

### ISSUE THREAD

**Issue by corytodd** [MicrosoftDocs/windows-driver-docs#1924]
As of Windows 10 1903 build, the DDK on VS 2019 will reject this INF. This is outlined at https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/creating-a-primitive-driver 

This page should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5200881-5453-18a7-c029-6fc86b3e15b5
* Version Independent ID: ed634626-5d11-fdd3-b2a4-ea9c8b04fcdd
* Content: [Creating an INF File for a Minifilter Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/creating-an-inf-file-for-a-minifilter-driver)
* Content Source: [windows-driver-docs-pr/ifs/creating-an-inf-file-for-a-minifilter-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/creating-an-inf-file-for-a-minifilter-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for flagging this important change, @corytodd ! I've overhauled the page accordingly.
