### ISSUE TITLE
Parameters and description

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#1935]
Add the list of parameters (along with their values and meanings) and a description of this bug check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eef7617-6134-5e78-1ad2-1d31e32e6cad
* Version Independent ID: ddb479fc-0d81-79e0-eea2-fdf1da2398dd
* Content: [Bug Check 0x2C PORT_DRIVER_INTERNAL - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x2c--port-driver-internal#feedback)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x2c--port-driver-internal.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x2c--port-driver-internal.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - I have opened an internal work item to track this work, so closing this issue for now.

As I have mentioned before, we use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, it is likely that we will only be able to do this work for a small sub set of all of the possible stop codes.

This one seems a bit less active then some others. And right now there are new ones that need to be documented first.

Thank you for your interest in improving our stop code docs.
