### ISSUE TITLE
Parameters and description

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#1936]
Add the list of parameters (along with their values and meanings) and a description of this bug check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89528440-5961-f27b-521b-b32eecafdbdd
* Version Independent ID: bf00dd21-07e6-b890-0132-693b0cb78c4a
* Content: [Bug Check 0x42 ATDISK_DRIVER_INTERNAL - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x42--atdisk-driver-internal#feedback)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x42--atdisk-driver-internal.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x42--atdisk-driver-internal.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - Best I can tell, this is not an active stop code in any supported version of Windows, so I don't think that it makes sense to add any additional descriptions at this point in time.

Thank you for your interest in improving our stop code docs.
