### ISSUE TITLE
“Driver promotions boxes checked”选择的是both，WU上传的版本和已有的版本是同一个，使用WIndows update check的时候还是能看到提示设备驱动有更新

### ISSUE THREAD

**Issue by john17024918** [MicrosoftDocs/windows-driver-docs#1938]
“Driver promotions boxes checked”选择的是both，WU上传的版本和已有的版本是同一个，试过上传WU时device manager下是不会更新的，但是上传完WU，使用WIndows update check的时候还是能看到提示设备驱动有更新，但其实是同一个版本。请问这是正常的吗？若不是，大概会是什么原因，还是需要我提供一下上传的inf档配置？

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 29080e2d-20c7-d0a1-efe4-6ac46b808738
* Version Independent ID: 7c4d982d-d7d5-4e13-1c19-7b1be65dee57
* Content: [Using Windows Update to Install Drivers - Windows drivers](https://docs.microsoft.com/zh-tw/windows-hardware/drivers/dashboard/understanding-windows-update-automatic-and-optional-rules-for-driver-distribution)
* Content Source: [windows-driver-docs-pr/dashboard/understanding-windows-update-automatic-and-optional-rules-for-driver-distribution.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/understanding-windows-update-automatic-and-optional-rules-for-driver-distribution.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @john17024918 

the Hardware Dev Center Support folks can help investigate.
1. **First**, sign into your hardware dev center account, and then 
2. Open a Hardware Dev Center support case for investigation. 
3. Go to 
[https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq)
and look for: 

**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

Machine translation:

硬件开发人员中心支持人员可以帮助调查。
1. [首先]，登录到您的硬件开发中心帐户，然后
2. 打开硬件开发中心支持案例进行调查。
3. 转到
[https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq]（https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq）
并查找：

{如何联系合作伙伴中心支持人员？
如果您在访问仪表板时遇到问题或需要仪表板支持，请在此处打开支持票证：[https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support).。从下拉菜单中选择 [联系我们]、[仪表板问题]，然后 [硬件提交 + 签名（所有操作系统版本）]。

I hope that this helps.
Eliot
