### ISSUE TITLE
How can I configure a Symbol Server over HTTPS

### ISSUE THREAD

**Issue by dhqiao** [MicrosoftDocs/windows-driver-docs#1944]
[Enter feedback here]

I have read the document: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/http-symbol-stores
This document is about HTTP, I want to configure a Symbol Server over HTTPS, but I have not retrieve a document about HTTPS.
Could you give me some suggestion.

Thanks.
---------------------------------------------------
Best Regards,
felix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aee83f5-cc48-e14b-d6ce-d3bff1153134
* Version Independent ID: 77e424c8-4e01-9b44-82fe-07b9f3d4c59d
* Content: [HTTP Symbol Stores - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/http-symbol-stores#feedback)
* Content Source: [windows-driver-docs-pr/debugger/http-symbol-stores.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/http-symbol-stores.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@dhqiao - Thanks for this issue, and apologies for the delay. I have created a work item for the dev team for this work and we will be tracking this request there, so I will close this issue. I don't have an ETA for that work right now. 

If you need information on this task, these newsgroups can be helpful.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
•	[OSR's ntdev List](https://community.osr.com/categories/ntdev)
•	[OSR's windbg List](https://community.osr.com/categories/windbg)

Thanks again for your interest in the debugger docs.
