### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by mtomarov** [MicrosoftDocs/windows-driver-docs#1945]
I would put link to code example if such code exists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 982e9811-2231-b22b-cd93-3f77d8361832
* Version Independent ID: d5e398fe-8fe2-75da-637d-2aac0ea91173
* Content: [Sample Custom Property Page - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/sample-custom-property-page#feedback)
* Content Source: [windows-driver-docs-pr/install/sample-custom-property-page.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/sample-custom-property-page.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @mtomarov 

Thanks for the feedback, and apologies for the delay.  You can register the property pages by adding an **EnumPropPages32** registry entry.  I just pushed an update to the doc page above that adds a Related info section with links to two pages that might help.  The update should be live in a few minutes.  Again, sorry it took so long!
