### ISSUE TITLE
The links to 'SDEL Tokens' are broken

### ISSUE THREAD

**Issue by oxfordmk** [MicrosoftDocs/windows-driver-docs#1948]
All the links to 'SDEL Tokens' on this and other pages just go to https://docs.microsoft.com/windows-hardware/drivers/ddi/index

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d87975db-4d2d-8ec4-8d18-fd6751c1b4b8
* Version Independent ID: 56d486a3-369a-db10-5646-dccfad6f3aa6
* Content: [Simple Data Evaluation Language Overview - Windows drivers](https://docs.microsoft.com/en-gb/windows-hardware/drivers/wdtf/simple-data-evaluation-language-overview#feedback)
* Content Source: [windows-driver-docs-pr/wdtf/simple-data-evaluation-language-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdtf/simple-data-evaluation-language-overview.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Fixed these in September but didn't remember to close this issue.
Sorry
Eliot
