### ISSUE TITLE
what about the /compress option

### ISSUE THREAD

**Issue by tyotypic** [MicrosoftDocs/windows-driver-docs#1949]
which does everything for you? Neither option 1 nor option 2 apply when using /compress. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 539166bc-cb8c-eb1a-da90-5679aa7aeb03
* Version Independent ID: f66ec639-272b-7de1-0af0-e5e0bf4ce2c3
* Content: [SymStore Compressed Files - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symstore-compressed-files#feedback)
* Content Source: [windows-driver-docs-pr/debugger/symstore-compressed-files.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/symstore-compressed-files.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@tyotypic - Thanks for reaching out to the Windows Driver Developer Documentation team and passing on what you see can be improved in the symbol compression documentation. We are a small team and we are not likely to be able to prioritize the work that this issue requires anytime soon. You may find better luck posting to the driver community on driver developer forums. These communities are often of great assistance. I recommend the following forums:

•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

•	[OSR's windbg List](https://community.osr.com/categories/windbg)
