### ISSUE TITLE
Invalid flag place 

### ISSUE THREAD

**Issue by bazuka5801** [MicrosoftDocs/windows-driver-docs#1950]
[Enter feedback here]
In the sample flag '-f' placed after 'oem0.inf', should be after devcon as in command definition 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9f37b92-708c-e826-fcf4-e663d35759d3
* Version Independent ID: 0cf2a07f-f355-08bf-d912-d7ace4be3d75
* Content: [DevCon Dp_delete - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/devcon-dp-delete)
* Content Source: [windows-driver-docs-pr/devtest/devcon-dp-delete.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/devcon-dp-delete.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks so much for catching this, @bazuka5801 
I made the fix and checked it in. Should be live momentarily.
Cheers,
Eliot
