### ISSUE TITLE
Caller's IRQL is different from fact

### ISSUE THREAD

**Issue by damochiz** [MicrosoftDocs/windows-driver-docs#1953]
Caller's IRQL in this table seems to indicate the maximum possible IRQL, but it's hard to understand. For example, paging I/O path is APC_LEVEL, but it may actually be processed with PASSIVE_LEVEL.
I want you to change the description a little more clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e348dcaf-bf47-9139-bf30-c3ed609ddaa0
* Version Independent ID: 51a6141a-36ac-fc35-1a47-d57f0f217fda
* Content: [Dispatch Routine IRQL and Thread Context - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/dispatch-routine-irql-and-thread-context)
* Content Source: [windows-driver-docs-pr/ifs/dispatch-routine-irql-and-thread-context.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/dispatch-routine-irql-and-thread-context.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@damochiz, thanks for reporting this - you are right that it was not clear! I have updated the page to say "Caller's Maximum IRQL", so that readers aren't confused about whether the stated IRQL is the specific level versus max level.
