### ISSUE TITLE
URL not valid.

### ISSUE THREAD

**Issue by ivangan-cpl** [MicrosoftDocs/windows-driver-docs#1954]
Under this section: 
https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/accessing-umdf-metadata-in-wer-reports#wudfunhandledexception-fields.

The link of EXCEPTION_RECORD is not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7111c17-937a-6da3-c4f3-1627d4a3e131
* Version Independent ID: 057b3ac8-0ddf-abb6-6312-132aac418566
* Content: [Accessing UMDF Metadata in WER Reports - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/accessing-umdf-metadata-in-wer-reports#wudfunhandledexception-fields)
* Content Source: [windows-driver-docs-pr/wdf/accessing-umdf-metadata-in-wer-reports.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/accessing-umdf-metadata-in-wer-reports.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Thanks for reporting this, @ivangan-cpl 
And thanks for the PR with the fix, @RAJU2529 
Eliot
