### ISSUE TITLE
messed-up tables here

### ISSUE THREAD

**Issue by landondyer** [MicrosoftDocs/windows-driver-docs#1958]
Looks like there are three messed-up tables here (the ones starting with "HANDLE Event", and the one with "POINTER_32 Event" near the bottom).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb0c1e81-8302-c76d-e2dc-add82d5e7eac
* Version Independent ID: 59e7f747-627c-edea-bedd-de4681971972
* Content: [Why Thunking Is Necessary - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/why-thunking-is-necessary#feedback)
* Content Source: [windows-driver-docs-pr/kernel/why-thunking-is-necessary.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/why-thunking-is-necessary.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Wow, THAT was fun with markdown. ;-)

Thanks for spotting this @landondyer and submitting the Issue. I've made the fix and create the PR. Should be live within 24 hours.

Eliot

**Comment by landondyer** [comment]
Thanks for fixing it. Loved your comment, my cow-orkers were amused :-)

**Comment by tedhudek** [comment]
Completed PR in the private, should be live in a couple minutes

**Comment by EliotSeattle** [comment]
Looks perfect on "review." Can go live. Thanks @tedhudek 

Glad to brighten up the workplace, @landondyer
