### ISSUE TITLE
Typo in STAMPINF_VERSION description.

### ISSUE THREAD

**Issue by grimbeaver** [MicrosoftDocs/windows-driver-docs#1969]
In the following statement on the page "Ntverp.h" is stated twice, as a single word:

If the STAMPINF_VERSION environment variable is not specified, Stampinf extracts the version number from the Ntverp.hNtverp.h file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3935d457-0fe1-098e-8f11-b763102282f1
* Version Independent ID: bda7011c-c691-6da0-55c0-db5f81d0415e
* Content: [Stampinf Command Options - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/stampinf-command-options#feedback)
* Content Source: [windows-driver-docs-pr/devtest/stampinf-command-options.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/stampinf-command-options.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Fixed. Thanks for catching this, @grimbeaver
