### ISSUE TITLE
link to RegisterNamedModel will jump to wrong page.

### ISSUE THREAD

**Issue by unsccaptain** [MicrosoftDocs/windows-driver-docs#1983]
[data-model-cpp-objects](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/data-model-cpp-objects.md)
the link in heading 'RegisterNamedModel'  is wrong.The page will jump to the page which introduces the GetRootNamespace.

**Comment by DOMARS** [comment]
@unsccaptain - Thanks for noticing this and filing this issue. The link is now fixed, so closing this issue.
