### ISSUE TITLE
Missing value 1 0xe00

### ISSUE THREAD

**Issue by MrPepka** [MicrosoftDocs/windows-driver-docs#1986]
I was able to debug the blue screen 0x119 with the first parameter 0xe00 whose meaning I do not see on this page. Can you add a description of this first parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7917857b-97bc-efec-67ab-5e3af061524c
* Version Independent ID: 8c00d20e-9b21-7bb0-a041-220aca9d2487
* Content: [Bug Check 0x119 VIDEO_SCHEDULER_INTERNAL_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x119---video-scheduler-internal-error?redirectedfrom=MSDN)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@MrPepka - I added a description for the 0xE00 parameter. Thank for this issue and your interest in the debugger stop code documentation for driver developers.
