### ISSUE TITLE
Page needs to be updated for Windows Server 2019

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windows-driver-docs#1987]
This page needs to be updated for Windows Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fd9ac7b-b86a-2c8a-e984-1bcfedf94225
* Version Independent ID: 1c63e4a8-b99f-99fa-2e02-9f54585be392
* Content: [Bring up - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/)
* Content Source: [windows-driver-docs-pr/bringup/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@rossmpersonal, thanks for pointing out the outdated references to Windows Server 2012 and 2016.

I'm adding the feedback you've provided to an internal work item to update the Bring up guide topic.
