### ISSUE TITLE
Seems to be reversed 

### ISSUE THREAD

**Issue by dantower** [MicrosoftDocs/windows-driver-docs#1990]
For fast startup it seems that effective state == PowerSystemHibernate and target state == PowerSystemShutdown instead of the other way around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10167325-2086-129e-2936-4fd35bd86d5b
* Version Independent ID: 8785a8a9-16d6-7dfb-83c6-13a2d7f2d9c7
* Content: [Distinguishing Fast Startup from Wake-from-Hibernation - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/distinguishing-fast-startup-from-wake-from-hibernation#feedback)
* Content Source: [windows-driver-docs-pr/kernel/distinguishing-fast-startup-from-wake-from-hibernation.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/distinguishing-fast-startup-from-wake-from-hibernation.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @dantower 

Thanks for the feedback and apologies for the delay. You are correct! I just pushed an update to the doc page above, should be live within a few minutes. Again, appreciate your taking the time to send this to us. Have a great weekend!
