### ISSUE TITLE
Typo in samples

### ISSUE THREAD

**Issue by P4mplemousse** [MicrosoftDocs/windows-driver-docs#1992]
Hello,

Please note that there is a typo in the sample. 
In the lines *PKEY_AudioDevice_EnableEndpointByDefault="{F3E80BEF-1723-4FF2-BCC4-7F83DC5E46D4},4”*
the ending quotes are not valid, nor corresponding to the opening quotes. In such case, the instruction is not readed correctly and so not applied.

The lines *KSCATEGORY_AUDIO=” {6994AD04-93EF-11D0-A3CC-00A0C9223196}”* and *AddInterface=%KSCATEGORY_AUDIO%,”GLOBAL”,USBAudio.Interface* have the same quotes problem.

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de927b37-9e5b-2378-33c4-f999880652d2
* Version Independent ID: 3cf74ce2-95d0-c48e-d49d-d0c8499eb4f7
* Content: [PKEY\_AudioDevice\_EnableEndpointByDefault - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/pkey-audiodevice-enableendpointbydefault#feedback)
* Content Source: [windows-driver-docs-pr/audio/pkey-audiodevice-enableendpointbydefault.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/pkey-audiodevice-enableendpointbydefault.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@P4mplemousse - Thanks for seeing this and filing this git issue. I fixed the curly quotes, so closing this issue.
