### ISSUE TITLE
Aclaration

### ISSUE THREAD

**Issue by isperezg** [MicrosoftDocs/windows-driver-docs#1996]
USB spec 3.2 states the following on section 9.2.5.1:
Note that placing all functions in the device into Function Suspend does not suspend the
device. A device is suspended only when its upstream link is placed in U3.

but this document contradict it:
"The entire composite device transitions into suspend state when all the individual functions are in suspend state"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9b73537-43d2-6d71-38f9-eb73f913c0f4
* Version Independent ID: 6dc277af-dd85-8ba1-a8dd-baea30185206
* Content: [How to Implement Function Suspend in a Composite Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/how-to--implement-remote-and-function-wake-support#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/how-to--implement-remote-and-function-wake-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/how-to--implement-remote-and-function-wake-support.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Thanks for the feedback @isperezg and apologies for the delay.  You are correct, the sentence you quoted from the documentation was incorrect.  I have removed it in d70f0de8d6.
