### ISSUE TITLE
Is the UUID the CHID?

### ISSUE THREAD

**Issue by PropelledDog** [MicrosoftDocs/windows-driver-docs#2000]
Is the Universally Unique Identifier (UUID) here the Computer Hardware ID (CHID)?

Reference: https://docs.microsoft.com/en-us/windows-hardware/drivers/install/specifying-hardware-ids-for-a-computer#specifying-hardware-ids-for-a-computer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 475b3180-a54d-d82e-c9a2-f92224094130
* Version Independent ID: ba58d79c-cbec-b20e-f2ef-988bc2a08163
* Content: [Sample PowerShell script to query SMBIOS locally - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/sample-powershell-script-to-query-smbios-locally#feedback)
* Content Source: [windows-driver-docs-pr/bringup/sample-powershell-script-to-query-smbios-locally.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/sample-powershell-script-to-query-smbios-locally.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. You may have success posting your question about the Universally Unique Identifier (UUID) and the Computer Hardware ID (CHID) in the following forums, where other driver developers and Microsoft engineers can be found. 

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
