### ISSUE TITLE
This is useless

### ISSUE THREAD

**Issue by Coldberg** [MicrosoftDocs/windows-driver-docs#2003]
It says nothing about where to find the checked build and how to install it.
This article is equivalent of saying "to install a checked build you should install a checked build"

**Comment by DOMARS** [comment]
@Coldberg - Can you please open an issue on the docs topic that is not providing the information on checked builds that you would like? I will close this one and look for the new issues on a specific docs topic. Thank you for the feedback and the interest in our docs.
