### ISSUE TITLE
Additional Include Directory necessary for #include <ntddk.h>

### ISSUE THREAD

**Issue by SpraylnlPray** [MicrosoftDocs/windows-driver-docs#2004]
[Enter feedback here]
In "Write your first driver code" step number one "In Driver.c, start by including these headers:" I couldn't include ntddk.h - I first had to add a path to C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\km in Configuration -> C/C++ -> General -> Additional Include Directories to fix the error.
I don't know if I missed the part where this is mentioned, but if it is missing it'd be nice if you could add this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81568a12-c39e-a18f-8f33-c54545f14bac
* Version Independent ID: 73217b22-1795-b5d0-65cb-1984f38dc661
* Content: [Write a universal Hello World driver (KMDF) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver#feedback)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-very-small-kmdf--driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-very-small-kmdf--driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by tedhudek** [comment]
Hi Daniel, thanks for mentioning this - exactly the type of gotcha that we love to include.  I've added it - it should appear on our live site later tonight.  Next time if you like, try a PR - you can start one by clicking the **Edit** button in the upper right of most pages on docs.microsoft.com.

Thanks again and apologies for the delay!
