### ISSUE TITLE
Pretty sure that EaBuffer can be null...

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs#2005]
In which case MdlAddress will be non-null.

It might also be useful to have some guidance about all these "Buffer/MDL" pairs (read and write are obvious examples, but there are others).
For instance
* EaBuffer is only guaranteed to be valid in the process of a calling process (or if a system address)
* What do I do if I want to return FLT_PENDING?  
* Can I grab the MDL and slam it into MDLAddress?  
* If so what do I do about MDL tear down?

My habit is to grab the MDL and keep it separate before pending the request, then I explicitly tear it down but I'm sure that there is a trick in there about letting the Io Manager do the tear down/.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7be35d47-f7af-b7e9-e1a6-4205255aca5c
* Version Independent ID: f805c411-659b-541f-b59b-2a3fcee7be17
* Content: [FLT_PARAMETERS for IRP_MJ_QUERY_EA union - Windows drivers](https://docs.microsoft.com/en-gb/windows-hardware/drivers/ifs/flt-parameters-for-irp-mj-query-ea)
* Content Source: [windows-driver-docs-pr/ifs/flt-parameters-for-irp-mj-query-ea.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/flt-parameters-for-irp-mj-query-ea.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@rodwiddowson , EaBuffer can indeed be NULL. I've updated this page, and other pages with MDL/Buffer pairs, to reflect this, and to provide the guidance that you requested. Thank you as always for reporting this, and for your thoughtful insights!
