### ISSUE TITLE
Virtual device driver signing requirement

### ISSUE THREAD

**Issue by extcon** [MicrosoftDocs/windows-driver-docs#2007]
Hello,
I got a question regarding driver signing. A partner developed a virtual device and developed a driver. Does virtual devices' device drivers require the same process to get the driver WHQL signed ie do you need to enroll in the Windows Hardware Developer Program when developing virtual devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8beddf5-9266-c5ee-12b3-d33252182126
* Version Independent ID: eb24d797-7294-154a-65e6-9d632fce796a
* Content: [WHQL Release Signature - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/whql-release-signature#feedback)
* Content Source: [windows-driver-docs-pr/install/whql-release-signature.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/whql-release-signature.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @extcon, my understanding is that all drivers, whether for a virtual device or a real device, need to be WHQL-signed in order to load.  Hope that helps!
