### ISSUE TITLE
Missing closing brace

### ISSUE THREAD

**Issue by wumb0** [MicrosoftDocs/windows-driver-docs#2008]
if (SUCCEEDED(hr) {
should be
if (SUCCEEDED(hr)) {

Right above the "Retrieve enumerator for interfaces of the binding path." comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53a3f100-6c13-4bb4-2e20-277dfc6f625d
* Version Independent ID: 8ccd7c9f-95d8-9c54-1be3-7e1526570914
* Content: [Changing Bindings for a Component - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/changing-bindings-for-a-component)
* Content Source: [windows-driver-docs-pr/network/changing-bindings-for-a-component.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/changing-bindings-for-a-component.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by RAJU2529** [comment]
@illfated. Please review this PR #2042.

**Comment by billlattimer** [comment]
@wumb0 , @RAJU2529 thank you for finding this on this issue and #2042. Fixed and merged.

**Comment by illfated** [comment]
interesting to see that you commit the fixes manually without merging the Pull Requests, in contrast to most other repositories here on GitHub.

**Comment by billlattimer** [comment]
@illfated I already had fixes for the article, so I combined those and pushed. 

In terms of the duplicate GitHub issue on this, I marked that as a dupe and closed it out. 

Thanks!

**Comment by illfated** [comment]
Very well, thanks for enlightening me on the situation. Fair enough, that's good enough for me. :)
