### ISSUE TITLE
IoRegisterBootDriverCallback

### ISSUE THREAD

**Issue by SJKU** [MicrosoftDocs/windows-driver-docs#2010]
Does the registration call IoRegisterBootDriverCallback() is mandatory? In case if don't want to participate in the boot drivers validation, can i skip this registration in my ELAM driver. I couldn't get any clarity on this from the doc, Can anyone answer? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da63a995-c445-b722-73d7-2379d00ad1d5
* Version Independent ID: eef47bcf-ed60-ee4b-9341-fef0c8d1eb1d
* Content: [ELAM Driver Requirements - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/elam-driver-requirements#feedback)
* Content Source: [windows-driver-docs-pr/install/elam-driver-requirements.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/elam-driver-requirements.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @SJKU technically you don't need to call it.
