### ISSUE TITLE
1st parameter 0x11 missing

### ISSUE THREAD

**Issue by claui** [MicrosoftDocs/windows-driver-docs#2015]
Similar, but not identical to #1980 reported by @MrPepka, I came across the first parameter 0x11 in a 0x13a bug check. Please add a description for this parameter as well. Thanks in advance!

**Comment by DOMARS** [comment]
@claui - I worked with the dev team to add information on additional parameters for 0x13A KERNEL_MODE_HEAP_CORRUPTION including 0x11. Thanks for your interest in improving the stop code documentation.

**Comment by claui** [comment]
Thanks @DOMARS!
