### ISSUE TITLE
What /sleep options internally do?

### ISSUE THREAD

**Issue by hlodwig** [MicrosoftDocs/windows-driver-docs#2024]
Hello,

I am a software developer involved in Power management testing. I would like to know if there is a techincal document with what the options do internally when executed. I am most interested in the /p scenarios as when I am testing, the system behaves differently with a value of /p:50 (fail) than with a value of /p:100 (good).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aff8a86-8549-bb27-effc-34d05b05fa06
* Version Independent ID: aa42165e-1a7f-5c1c-c19b-65e41754b318
* Content: [PwrTest Sleep Scenario - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/pwrtest-sleep-scenario#feedback)
* Content Source: [windows-driver-docs-pr/devtest/pwrtest-sleep-scenario.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pwrtest-sleep-scenario.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @hlodwig 

I spoke with one of the senior developers on the feature, and I learned that what you have *should* work but at 50s you’re likely start to impinge on the capabilities of the platform.  It leverages the hardware timer (Real time clock or ACPI time and alarm device) to wake the system from S3, and if it has issues or it takes the system somewhat longer to enter S3, the timer may have already expired. If that's the case the system remains asleep. 

Moving forward, you might want to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is the Windows Hardware WDK and Driver Development forum: [https://social.msdn.microsoft.com/Forums/windowshardware/](https://social.msdn.microsoft.com/Forums/windowshardware/).
 
The other is the NTDEV forum from OSR Online: [https://community.osr.com/](https://community.osr.com/).
 
You can post your question there, and like-minded developers usually give feedback fairly quickly.
 
Thanks for reaching out. Hope this helps.
Eliot
