### ISSUE TITLE
Info about the Power Management tab needs to be updated for 20H1

### ISSUE THREAD

**Issue by rahul-ramadas** [MicrosoftDocs/windows-driver-docs#2030]
As of 20H1, the Bluetooth radio property page will no longer show a Power Management tab, regardless of the ability of the radio to wake the system from Sx states. The registry keys are still relevant for controlling that capability (assuming it is actually capable). If the user wants to control the ability of certain Bluetooth devices, like a paired Bluetooth keyboard, to wake the system, they should control that setting from the Power Management tab of the relevant device (like the HID keyboard).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba52c2b-00d2-86fd-6923-9e6e3d4cd9d3
* Version Independent ID: 8aa7d813-7742-3c40-f902-4a6fbc89c74e
* Content: [Bluetooth FAQ - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bluetooth/bluetooth-faq#how-do-i-enable-remote-wake-in-windows)
* Content Source: [windows-driver-docs-pr/bluetooth/bluetooth-faq.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bluetooth/bluetooth-faq.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by billlattimer** [comment]
Resolving internally.
