### ISSUE TITLE
Source indexing for git and subversion repos

### ISSUE THREAD

**Issue by NilssonOpel** [MicrosoftDocs/windows-driver-docs#2035]
If you are interested I have made python scripts that handles mixed git and subversion repos, please look here: https://github.com/NilssonOpel/SIMuR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02518b75-bf11-272f-ca30-b076db1c6aa9
* Version Independent ID: 0466a6c4-cbba-bab1-2dfb-716ee9c54355
* Content: [Source Indexing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/source-indexing#feedback)
* Content Source: [windows-driver-docs-pr/debugger/source-indexing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/source-indexing.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@NilssonOpel - This looks like interesting code work that you are doing. A good channel to share this would be on the driver code related forums.

•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

•	[OSR's ntdev List](https://community.osr.com/categories/ntdev)

•	[OSR's windbg List](https://community.osr.com/categories/windbg)

Good luck with your coding efforts.
