### ISSUE TITLE
please provide accurate target build number

### ISSUE THREAD

**Issue by kevinf28** [MicrosoftDocs/windows-driver-docs#2036]
vertarget command outputs the following:
-----
15: kd&gt; vertarget
Windows 10 Kernel Version 18362 MP (16 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 18362.1.amd64fre.19h1_release.190318-1202
Machine Name:
Kernel base = 0xfffff804`1b400000 PsLoadedModuleList = 0xfffff804`1b843290
Debug session time: Tue Feb 11 14:13:03.503 2020 (UTC - 5:00)
System Uptime: 0 days 18:42:41.262
------
But the important detail, this system is 18362.30, as OS updates come, the build number changes, and that is important to discover the symbols needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6347d0e8-415b-b6fe-601b-03d6b024bb39
* Version Independent ID: 755fe1ea-b16b-fd2a-443f-36f8754b6fc9
* Content: [vertarget (Show Target Computer Version) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/vertarget--show-target-computer-version-)
* Content Source: [windows-driver-docs-pr/debugger/vertarget--show-target-computer-version-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/vertarget--show-target-computer-version-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@kevinf28 - The type of information displayed in vertarget is different from what is display using "System" on the target PC. If you think the vertarget command should behave differently, you can provide product feedback using this the product feedback tool for the debugger.

http://aka.ms/dexex 

The Feedback Hub allows customers to file and up vote product issues. The link automatically sets the product category to Debugging Tools for Windows.
