### ISSUE TITLE
Veeam filter Drivers

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/windows-driver-docs#2037]
Did Veeam not register there Minifilter drivers or is this list out of date?

That driver was signed ‎Freitag, ‎6. ‎Juli ‎2018 11:57:41 by Microsoft Windows Hardware Compatibility Publisher.

```
[Strings]
Veeam                   = "Veeam Software AG"
ServiceDescription      = "Veeam CTK Mini-Filter Driver"
ServiceName             = "VeeamFCT"
DriverName              = "VeeamFCT"
DiskId                  = "Veeam CT Mini-Filter Driver Installation Disk"

; Instances

DefaultInstance         = "TopInstance"

Instance1.Name          = "TopInstance"
Instance1.Altitude      = "405100"
Instance1.Flags         = 0x0              ; allow auto attachments

Instance2.Name          = "LowInstance"
Instance2.Altitude      = "201900"
Instance2.Flags         = 0x1              ; don't allow auto attachments

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a2d558e-1073-85d5-f863-5bdbf6e3ddc6
* Version Independent ID: 62e4d735-803f-7608-154b-7032dc1ceb3d
* Content: [Allocated Altitudes - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/allocated-altitudes#feedback)
* Content Source: [windows-driver-docs-pr/ifs/allocated-altitudes.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/allocated-altitudes.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@agowa338 , I've updated the table to include your filter and altitude allocation. We update the table only 1-2 times per year should you register another filter (although it's odd that yours was missing since it was allocated in 2018). All good now!
