### ISSUE TITLE
Few Clarificatiosn that will hep

### ISSUE THREAD

**Issue by pankajbharti** [MicrosoftDocs/windows-driver-docs#2046]
contextInheritor - Examples for how to use this will help. 

host.getModuleSymbol - Example will help

What is the difference between : createPointerObject and createTypedObject ? 

I got lost on what  is Named Model and apis related to it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f96d161-85bb-9402-d748-a33598beeef9
* Version Independent ID: 01a3c179-7fa1-14b3-2bbc-86d254e176bb
* Content: [Native Debugger Objects in JavaScript Extensions - Debugger Object Details - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/native-objects-in-javascript-extensions-debugger-objects)
* Content Source: [windows-driver-docs-pr/debugger/native-objects-in-javascript-extensions-debugger-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/native-objects-in-javascript-extensions-debugger-objects.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@pankajbharti - Thanks for this docs input on the Debug Model JavaScript extensions. I added a code snip that shows the use of APIs that you mentioned. And also have worked to better highlight the new JavaScript code samples now available in https://github.com/microsoft/WinDbg-Samples/. Thanks for this input and good luck with your Debug Model JavaScript development.
