### ISSUE TITLE
Data Filtering: Plug and Play Device Tree in KD (Kernel Mode)  --> Example not working. 

### ISSUE THREAD

**Issue by pankajbharti** [MicrosoftDocs/windows-driver-docs#2047]
Issue1 : 
 DeviceTree is not populated. I have a kernel dump 
0: kd&gt; dx -v Debugger.Sessions.First().Devices
Debugger.Sessions.First().Devices                
    LogicalProcessors
0: kd&gt; ||
.  0 64-bit Kernel bitmap dump: .........MEMORY.DMP

Issue 2 : This is a simple typo: Name of script is deviceFilter however when using it the text suggests it is PlugAndPlayDeviceTree

0: kd&gt; .scriptload c:\WinDbg\Scripts\deviceFilter.js
JavaScript script successfully loaded from 'c:\WinDbg\Scripts\deviceFilter.js'

vs 

dx Debugger.State.Scripts.PlugAndPlayDeviceTree.Contents.filterAllDevices()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e185d6-e8c5-5063-eba1-7c63e3c3e198
* Version Independent ID: cd913396-ce95-bd85-d742-f7bf43779b86
* Content: [JavaScript Debugger Example Scripts - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/javascript-debugger-example-scripts#filter)
* Content Source: [windows-driver-docs-pr/debugger/javascript-debugger-example-scripts.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/javascript-debugger-example-scripts.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@pankajbharti - Thanks for the feedback. I updated the document to indicate that a live connection could be used. So full dump files or certain mini dump file types may contain enough information for the object model, but I think the safest approach is to use a live connection. The !devnode 0 1 command should display device information. I also fixed the inconsistency in the sample script file name. Thanks for pointing that out, and the interest in improving the debugger automation documentation.
