### ISSUE TITLE
Sentence cut off

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/windows-driver-docs#2049]
The middle paragraph just ends before it gets to the part of what resources to see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fc6a544-050e-3b34-595e-509b2e712cce
* Version Independent ID: 66a0055d-66b9-28c6-70e7-79fbba07b155
* Content: [The dbgeng.h Header File - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/the-dbgeng-h-header-file)
* Content Source: [windows-driver-docs-pr/debugger/the-dbgeng-h-header-file.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/the-dbgeng-h-header-file.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@henke37 - I added repaired the paragraph.  Thanks for this issue.

@RAJU2529 - Thanks for the PR, but I had created this fix last week, before your PR came in.
