### ISSUE TITLE
Wrong section name

### ISSUE THREAD

**Issue by arsu-leo** [MicrosoftDocs/windows-driver-docs#2054]
Section 3 states a wrong name, I just searched and realized it's missing a "s":
SourceDiskFiles should be SourceDisksFiles, note the "s" after disk

https://docs.microsoft.com/en-us/windows-hardware/drivers/print/building-a-basic-v4-printer-driver#3-configure-the-sourcediskfiles-section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227ceb38-396a-aa19-6304-be3df9b0ca08
* Version Independent ID: 2f34593f-aa20-384a-b1bb-c8a962ec4706
* Content: [Building a Basic v4 Printer Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/building-a-basic-v4-printer-driver#3-configure-the-sourcediskfiles-section)
* Content Source: [windows-driver-docs-pr/print/building-a-basic-v4-printer-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/building-a-basic-v4-printer-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for catching this incorrect INF section name, @arsu-leo!

The section name has been updated to **[SourceDisksFiles]**.
