### ISSUE TITLE
FMonitor.sys minifilter not listed

### ISSUE THREAD

**Issue by jan-safetica** [MicrosoftDocs/windows-driver-docs#2057]
Hi, our request for allocating our minifilter was successfully approved some time ago, however, the minifilter is still not listed on the site.

The allocation's confirmation arrived on November 1, 2019, 21:43 CET:

&gt; The Microsoft File System Filter team has allocated the altitude 100490 for your FMonitor.sys minifilter.

The simplified details are:
- **Minifilter:** FMonitor.sys
- **Altitude:** 100490
- **Company:** Safetica Technologies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a2d558e-1073-85d5-f863-5bdbf6e3ddc6
* Version Independent ID: 62e4d735-803f-7608-154b-7032dc1ceb3d
* Content: [Allocated Altitudes - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/allocated-altitudes#feedback)
* Content Source: [windows-driver-docs-pr/ifs/allocated-altitudes.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/allocated-altitudes.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@jan-safetica , I've updated the table to include your filter and altitude allocation. Just fyi that we update the table only 1-2 times per year should you register another filter.
