### ISSUE TITLE
Windows 2019 /1903 / 1909  Antivirus Recommendation Updates

### ISSUE THREAD

**Issue by nileshkumar01** [MicrosoftDocs/windows-driver-docs#2061]
Just wanted to check the recommendations made on this page https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/anti-virus-optimization-for-windows-containers regarding antivirus does anything need to be updated for Windows 2019 /1903 / 1909

**Comment by lorihollasch** [comment]
@nileshkumar01 , the recommendations are still the same. I've updated the page to indicate "and later versions" to reflect this. Thanks for alerting us to this!
