### ISSUE TITLE
VhfSubmitReadReport() -> VhfReadReportSubmit()

### ISSUE THREAD

**Issue by moolwalk** [MicrosoftDocs/windows-driver-docs#2064]
There's a typo in sample code. VhfSubmitReadReport() in MY_SubmitReadReport() must be fixed.

From : VhfSubmitReadReport()
To : VhfReadReportSubmit()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88f27d9f-121d-b3f5-1671-73eb319f680e
* Version Independent ID: 0c61c804-1f2b-e62f-8d45-3322404905d3
* Content: [Write a HID source driver by using Virtual HID Framework (VHF) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/virtual-hid-framework--vhf-?source=docs#feedback)
* Content Source: [windows-driver-docs-pr/hid/virtual-hid-framework--vhf-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/virtual-hid-framework--vhf-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Thanks, I just pushed the fix - sorry for the delay!
