### ISSUE TITLE
The "Root Level" section is not fully display

### ISSUE THREAD

**Issue by xinglonghe** [MicrosoftDocs/windows-driver-docs#2066]
The "Root Level" section is not fully display

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f96d161-85bb-9402-d748-a33598beeef9
* Version Independent ID: 01a3c179-7fa1-14b3-2bbc-86d254e176bb
* Content: [Native Debugger Objects in JavaScript Extensions - Debugger Object Details - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/native-objects-in-javascript-extensions-debugger-objects#feedback)
* Content Source: [windows-driver-docs-pr/debugger/native-objects-in-javascript-extensions-debugger-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/native-objects-in-javascript-extensions-debugger-objects.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@xinglonghe - Thanks for this input. For the large multi column tables, you need to locate the scroll bar at the bottom of the table and use that to view the entire table. This is less then ideal, so I will investigate if there is anything that can be done with our current publishing system to better render large tables like this. Thanks for pointing out this issue.
