### ISSUE TITLE
SrcSrv Language Specification 1 typo

### ISSUE THREAD

**Issue by manison** [MicrosoftDocs/windows-driver-docs#2068]
There is probably typo in the section describing the variables:

```diff
---SRCSRV
+++SRCSRVTRG
Describes how to build the target path for the extracted file. This is a required variable.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6e0df1-4638-9133-3315-23352641b625
* Version Independent ID: 314c937e-aad2-90c0-4eef-5bb557c7c8e3
* Content: [Language Specification 1 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/language-specification-1)
* Content Source: [windows-driver-docs-pr/debugger/language-specification-1.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/language-specification-1.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@manison - Yes this was a typo and it is now fixed. Thanks for seeing this and filing this issue.
