### ISSUE TITLE
A short list of common Pool tags would help

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs#2073]
Given that `!pool` mostly doesn't work these days it would be nice to know common tags.

I 'happen to know' that `File` is good for file objects and I'd guess that `Thre` works for threads, but what about sections?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 669a1f00-b2c2-7874-e23e-5e716bdfacdc
* Version Independent ID: 4ed43723-18f9-3c60-38f0-60853dea757a
* Content: [Configuring Object Reference Tracing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/configuring-object-reference-tracing)
* Content Source: [windows-driver-docs-pr/debugger/configuring-object-reference-tracing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/configuring-object-reference-tracing.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@rodwiddowson - One way to find pool tags is to look in the pooltag.txt file. This file is located in the Debugging Tools for Windows installation and is mentioned in the !pool command remarks. To make that information easier to find, I added links to !pool and !poolfind, to make that easier for other readers. Thanks for the input on this topic.
