### ISSUE TITLE
Sentence doesn't make sense  

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/windows-driver-docs#2077]
Each driver-specific I/O stack location (IO_STACK_LOCATION for the major function codes that it must support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28acb89e-4c69-1bf9-4e50-7e299aae5670
* Version Independent ID: ee36df90-e80d-4963-aba2-4422bfc8ae56
* Content: [IRP Major Function Codes - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/irp-major-function-codes#feedback)
* Content Source: [windows-driver-docs-pr/kernel/irp-major-function-codes.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/irp-major-function-codes.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the sharp eye @aguptadel!  I've updated the first paragraph of the page.
