### ISSUE TITLE
Need more parameter 1 code and definition of parameter 2 & 4

### ISSUE THREAD

**Issue by vtsou** [MicrosoftDocs/windows-driver-docs#2078]
Can you please add P1 code 0x100000? 
Also the definition of parameter 2 & 4, thanks. 

0: kd&gt; !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

VIDEO_SCHEDULER_INTERNAL_ERROR (119)
The video scheduler has detected that fatal violation has occurred. This resulted
in a condition that video scheduler can no longer progress. Any other values after
parameter 1 must be individually examined according to the subtype.
Arguments:
Arg1: 0000000000100000, The subtype of the bugcheck:
Arg2: 0000000000000002
Arg3: 0000000000000000
Arg4: ffff9e00188d6000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7917857b-97bc-efec-67ab-5e3af061524c
* Version Independent ID: 8c00d20e-9b21-7bb0-a041-220aca9d2487
* Content: [Bug Check 0x119 VIDEO_SCHEDULER_INTERNAL_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x119---video-scheduler-internal-error#feedback)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@vtsou - Thanks for the input that on the additional parameter for the VIDEO_SCHEDULER_INTERNAL_ERROR (119) bug check topic. I have created and internal work item to track the work for this, so will close this issue. As we have limited resources, we use data like this to help guide our work. Good luck with your efforts in blue screen troubleshooting, and thanks for your interest in the bug check documentation.
