### ISSUE TITLE
Availability of WHEA Platform Design Guide

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/windows-driver-docs#2079]
This statement is no more valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1786c649-e59c-fb54-fb14-7da19f126efb
* Version Independent ID: 84e03e95-3726-4383-a5d4-d6817a33c2ab
* Content: [Windows Hardware Error Architecture (WHEA) design guide - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/whea/)
* Content Source: [windows-driver-docs-pr/whea/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/whea/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Erroneous statement and the dead mail link removed.
Thanks!
