### ISSUE TITLE
The Capability Store for the UcmTcpci class extension is incomplete

### ISSUE THREAD

**Issue by neilsh-msft** [MicrosoftDocs/windows-driver-docs#2080]
I have a customer attempting to write a UcmTcpci class extension and they commented that the [ACPI sample](https://github.com/microsoft/Windows-driver-samples/blob/master/usb/UcmTcpciCxClientSample/Sample.asl) _DSD section has types and values which are not explained.  These correspond to the Capability Store section in this document, but neither MSDN nor the code sample clearly indicate what are legal values.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5894e364-b4f6-7e16-7f76-36668969d0bd
* Version Independent ID: 6ecd6d26-0f40-1ef1-801e-c2fde834066b
* Content: [Write a USB Type-C port controller driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/write-a-usb-type-c-port-controller-driver)
* Content Source: [windows-driver-docs-pr/usbcon/write-a-usb-type-c-port-controller-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/write-a-usb-type-c-port-controller-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Hi @neilsh-msft thanks for the feedback and sorry it took so long to get back to you.  I just took a quick look at the `Name(_DSD, Package()` section in https://github.com/microsoft/Windows-driver-samples/blob/master/usb/UcmTcpciCxClientSample/Sample.asl and I see code comments that look pretty descriptive - maybe those were added in the interim.

If this is still an issue please feel free to reopen
