### ISSUE TITLE
Handlle is misspelled.

### ISSUE THREAD

**Issue by neilsh-msft** [MicrosoftDocs/windows-driver-docs#2081]
The word "Handle" is misspelled here in the section name and the document itself: https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/write-a-usb-type-c-port-controller-driver#5-handlle-alerts-from-the-port-controller-hardware

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5894e364-b4f6-7e16-7f76-36668969d0bd
* Version Independent ID: 6ecd6d26-0f40-1ef1-801e-c2fde834066b
* Content: [Write a USB Type-C port controller driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/write-a-usb-type-c-port-controller-driver)
* Content Source: [windows-driver-docs-pr/usbcon/write-a-usb-type-c-port-controller-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/write-a-usb-type-c-port-controller-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by billlattimer** [comment]
@neilsh-msft thanks for pointing this out; addressed on #2085.
