### ISSUE TITLE
Need some explaination

### ISSUE THREAD

**Issue by zeltrax00** [MicrosoftDocs/windows-driver-docs#2083]
What is trailing names? Please give me some example. Thank you.

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 11269278-125b-a9b8-19eb-b52aa94d2389
* Version Independent ID: 15369254-5b5e-75b0-0ef0-6015dde04648
* Content: [Bug Check 0xF9 DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN - Windows drivers](https://docs.microsoft.com/vi-vn/windows-hardware/drivers/debugger/bug-check-0xf9--driver-returned-status-reparse-for-volume-open#feedback)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0xf9--driver-returned-status-reparse-for-volume-open.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0xf9--driver-returned-status-reparse-for-volume-open.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@zeltrax00 - I added additional links to this bug code to point to the related driver docs for IFS drivers including the design guide - [File systems driver design guide](https://docs.microsoft.com/windows-hardware/drivers/ifs/) and the IRP\_MJ\_CREATE - [IRP_MJ_CREATE (IFS)](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-create).

You may be able to use the debugger !irp extension to display information about an I/O request packet (IRP) in question.

For additional questions about working with file system drivers, the OSR forum is a great resource for developers. For example this thread discussed Status_Reparse.

https://community.osr.com/discussion/6623/status-reparse

Good luck in solving your stop code issue.
