### ISSUE TITLE
What is the classId, winUsbId? Is it made up of Classs + SubClass?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windows-driver-docs#2084]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/windows-driver-docs.zh-cn/issues/12

The comments below were machine-translated

@SuperDcer commented 1 hour ago — with docs.microsoft.com
What is the classId, winUsbId? Is it made up of Classs + SubClass? What happens if Device capabilities are not specified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b843acc8-3fa9-5f3a-a89b-9c8149914020
* Version Independent ID: 1c3e8047-ad68-29a0-d3e7-9bf842c27885
* Content: [How to add USB device capabilities to the app manifest - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/updating-the-app-manifest-with-usb-device-capabilities#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/updating-the-app-manifest-with-usb-device-capabilities.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/updating-the-app-manifest-with-usb-device-capabilities.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Hi @SuperDcer, thanks for the feedback and apologies for the delay.  The classId is the device class code, and the, winUsbId
is the device interface GUID.  Note that to edit these you need to right-click the Package.appxmanifest file in Solution Explorer and select Open With, and then XML (Text) Editor.
