### ISSUE TITLE
execute "asl.exe /d dsdt.bin" output error-asl_ERROR:failed to open LST file -DSDT.TXT

### ISSUE THREAD

**Issue by XPZEndlesscode** [MicrosoftDocs/windows-driver-docs#2093]
[Enter feedback here]

C:\Desktop\temp>asl.exe /d dsdt.dat
Microsoft ACPI Source Language Assembler Version 5.0.0NT
Copyright (c) 1996,2014 Microsoft Corporation
Compliant with the ACPI 5.0 Specification

asl_ERR: failed to open LST file - DSDT.TXT
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146c2e57-a40b-33e0-c108-37f7555eda8a
* Version Independent ID: 81b0b392-c18a-f083-17fa-7e6dca629a52
* Content: [Microsoft ASL compiler - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/microsoft-asl-compiler)
* Content Source: [windows-driver-docs-pr/bringup/microsoft-asl-compiler.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/microsoft-asl-compiler.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. You may have success posting your question about the **asl_ERR: failed to open LST file** error message in the following forums, where other driver developers and Microsoft engineers can be found.

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
