### ISSUE TITLE
How to analyze the ErrorSourceArray?

### ISSUE THREAD

**Issue by ericurse** [MicrosoftDocs/windows-driver-docs#2099]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6240fce0-8e15-df75-95af-74b456efe080
* Version Independent ID: 9d070c09-384c-f380-24fd-88102ce08db1
* Content: [Getting Error Source Information for All Error Sources - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/whea/getting-error-source-information-for-all-error-sources)
* Content Source: [windows-driver-docs-pr/whea/getting-error-source-information-for-all-error-sources.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/whea/getting-error-source-information-for-all-error-sources.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @ericurse  
Thanks for reaching out to our team. This particular email alias is monitored by the men and women who write the  driver **documentation** posted on MSDN. Unfortunately, we don’t have the resources to help troubleshoot driver development or testing code or provide samples. 
 
Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is the MSDN Windows Hardware WDK and Driver Development forum: [https://social.msdn.microsoft.com/Forums/windowshardware/](https://social.msdn.microsoft.com/Forums/windowshardware/).

The other is the NTDEV forum from OSR Online: [https://community.osr.com/](https://community.osr.com/).
 
You can post your question there, and like-minded developers usually give feedback fairly quickly.
 
Again, thanks for reaching out. Best of luck with this issue.
Eliot
