### ISSUE TITLE
This does not seem to work for serial ports

### ISSUE THREAD

**Issue by cinderbdt** [MicrosoftDocs/windows-driver-docs#2104]
This does not seem to work for COM ports in Windows 10?
`rundll32.exe devmgr.dll,DeviceProperties_RunDLL /MachineID "" /DeviceID "ACPI\VEN_PNP&DEV_0501"`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c5c7b52-24c3-5eb2-bd5e-ebb639590c48
* Version Independent ID: c1670409-850f-86d0-03ad-18fe3997820b
* Content: [Device Instance ID - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-instance-ids)
* Content Source: [windows-driver-docs-pr/install/device-instance-ids.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/device-instance-ids.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Sorry for the delay! Looks like this feedback might be better suited to the doc page for rundll32.exe, which is https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/rundll32
