### ISSUE TITLE
0x9 parameter missing

### ISSUE THREAD

**Issue by MrPepka** [MicrosoftDocs/windows-driver-docs#2107]
I came across the blue screen 0x7F where the first parameter is 0x9, WinDbg describes it as EXCEPTION_NPX_OVERRUN. Can you add a more detailed description on this page to what this exception means?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab369b7-1a0e-e2f8-9d9b-d4bc3710ca57
* Version Independent ID: eac532fd-fece-247e-8b12-7cc6b6a3906e
* Content: [Bug Check 0x7F UNEXPECTED_KERNEL_MODE_TRAP - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x7f--unexpected-kernel-mode-trap?redirectedfrom=MSDN)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x7f--unexpected-kernel-mode-trap.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x7f--unexpected-kernel-mode-trap.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@MrPepka -  EXCEPTION_NPX_OVERRUN is specific to the Intel x86 processor, so I would refer to their docs and X86 assembler programming guides for more information. For example: https://software.intel.com/content/www/us/en/develop/articles/intel-sdm.html. Good luck with your debugging work and thanks for your interest in the bug check documentation.
