### ISSUE TITLE
Compatibility of FWPM_LAYER_STREAM_PACKET_V* layers

### ISSUE THREAD

**Issue by jamesmistry** [MicrosoftDocs/windows-driver-docs#2108]
Are there any special considerations required for FWPM_LAYER_STREAM_PACKET_V* layers to make callouts using them IPsec compatible?

If these are counted as "stream layers", it would be useful to include them in that list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca3dce9-1135-c54c-2c97-eba858502ca8
* Version Independent ID: 5f26cad0-a3e4-8d39-f1ad-5a51b6ae94e5
* Content: [Developing IPsec-Compatible Callout Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/developing-ipsec-compatible-callout-drivers#feedback)
* Content Source: [windows-driver-docs-pr/network/developing-ipsec-compatible-callout-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/developing-ipsec-compatible-callout-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Hi @jamesmistry thanks for the feedback and apologies for the delay.

STREAM is unique.  STREAM_PACKET more closely resemble DATAGRAM_DATA layers operation.  IPsec rules would be the same as Inbound / outbound transport.

Hope this helps!
