### ISSUE TITLE
Not enough information

### ISSUE THREAD

**Issue by sovamind** [MicrosoftDocs/windows-driver-docs#2126]
This page lacks any sort of helpful information.  What does "setting up the class configuration" mean?  What do you need to do to help it finish this process?  How do you troubleshoot it and correct it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37316832-6c23-793d-f978-160e4fac78bf
* Version Independent ID: 3a4adb3f-ede6-4f8d-1c8f-1a0231431d49
* Content: [CM_PROB_NEED_CLASS_CONFIG - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/cm-prob-need-class-config#feedback)
* Content Source: [windows-driver-docs-pr/install/cm-prob-need-class-config.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/cm-prob-need-class-config.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @sovamind 

Sorry for the delay and thank you for the feedback.  I just updated the "For driver developers" section of https://docs.microsoft.com/en-us/windows-hardware/drivers/install/cm-prob-need-class-config.  Hope this helps!
