### ISSUE TITLE
uefi fw rollbck failed with pnputil -i -a bios_previous_version.inf

### ISSUE THREAD

**Issue by btian1** [MicrosoftDocs/windows-driver-docs#2135]
upgrade is fine, rollback is failed, I did following guided by:

To allow a firmware rollback, create a REG_DWORD value called Policy and set the value to 1
Question
You cannot vote on your own post
0
however, still observed:

fail to install the driver on any of the devices on the system : no more data is available

total attempted : 1

number successfully imported : 0

error log:

Question
You cannot vote on your own post
0
[Boot Session: 2020/03/30 10:06:18.500]

>>>  [SetupCopyOEMInf - C:\Bios\TglSystemFwBios_252714.inf]
>>>  Section start 2020/03/30 10:10:14.439
      cmd: pnputil  -i -a TglSystemFwBios_252714.inf
     inf: Copy style: 0x00000000
!    inf: Driver package is already in driver store
     sto: {Setup Import Driver Package: C:\Bios\TglSystemFwBios_252714.inf} 10:10:14.455
     sto:      Driver package already imported as 'oem32.inf'.
     sto: {Setup Import Driver Package - exit (0x00000000)} 10:10:14.455
     inf: Driver Store Path: C:\windows\System32\DriverStore\FileRepository\tglsystemfwbios_252714.inf_amd64_b39e76a79dd0f7e8\tglsystemfwbios_252714.inf
     inf: Published Inf Path: C:\windows\INF\oem32.inf
<<<  Section end 2020/03/30 10:10:14.455
<<<  [Exit status: SUCCESS]

>>>  [Device Install (DiInstallDriver) - C:\windows\System32\DriverStore\FileRepository\tglsystemfwbios_252714.inf_amd64_b39e76a79dd0f7e8\tglsystemfwbios_252714.inf]
>>>  Section start 2020/03/30 10:10:14.455
      cmd: pnputil  -i -a TglSystemFwBios_252714.inf
     ndv: Flags: 0x00000000
     ndv: INF path: C:\windows\System32\DriverStore\FileRepository\tglsystemfwbios_252714.inf_amd64_b39e76a79dd0f7e8\tglsystemfwbios_252714.inf
     inf: {SetupCopyOEMInf: C:\windows\System32\DriverStore\FileRepository\tglsystemfwbios_252714.inf_amd64_b39e76a79dd0f7e8\tglsystemfwbios_252714.inf} 10:10:14.455
     inf:      Copy style: 0x00000000
     inf:      Driver Store Path: C:\windows\System32\DriverStore\FileRepository\tglsystemfwbios_252714.inf_amd64_b39e76a79dd0f7e8\tglsystemfwbios_252714.inf
     inf:      Published Inf Path: C:\windows\INF\oem32.inf
     inf: {SetupCopyOEMInf exit (0x00000000)} 10:10:14.470
     ndv: {Update Device Driver - UEFI\RES_{6C8E136F-D3E6-4131-AC32-4687CB4ABD27}\0}
     ndv:      Search options: 0x00000081
     ndv:      Searching single INF 'C:\windows\System32\DriverStore\FileRepository\tglsystemfwbios_252714.inf_amd64_b39e76a79dd0f7e8\tglsystemfwbios_252714.inf'
     dvi:      {Build Driver List} 10:10:14.470
     dvi:           Searching for hardware ID(s):
     dvi:                uefi\res_{6c8e136f-d3e6-4131-ac32-4687cb4abd27}&rev_3db2d
     dvi:                uefi\res_{6c8e136f-d3e6-4131-ac32-4687cb4abd27}
     dvi:           Searching for compatible ID(s):
     dvi:                uefi\cc_00010002
     dvi:                genfirmwareresource
     dvi:           Created Driver Node:
     dvi:                HardwareID   - UEFI\RES_{6C8E136F-D3E6-4131-AC32-4687CB4ABD27}
     dvi:                InfName      - c:\windows\system32\driverstore\filerepository\tglsystemfwbios_252714.inf_amd64_b39e76a79dd0f7e8\tglsystemfwbios_252714.inf
     dvi:                DevDesc      - Intel TigerLake BIOS 0.0.2527.14
     dvi:                Section      - Firmware_Install.NT
     dvi:                Rank         - 0x00ff0001
     dvi:                Signer Score - Authenticode
     dvi:                DrvDate      - 02/24/2020
     dvi:                Version      - 0.0.2527.14
     dvi:      {Build Driver List - exit(0x00000000)} 10:10:14.486
     ndv:      Searching currently installed INF
     dvi:      {Build Driver List} 10:10:14.502
     dvi:           Searching for hardware ID(s):
     dvi:                uefi\res_{6c8e136f-d3e6-4131-ac32-4687cb4abd27}&rev_3db2d
     dvi:                uefi\res_{6c8e136f-d3e6-4131-ac32-4687cb4abd27}
     dvi:           Searching for compatible ID(s):
     dvi:                uefi\cc_00010002
     dvi:                genfirmwareresource
     dvi:           Created Driver Node:
     dvi:                HardwareID   - UEFI\RES_{6C8E136F-D3E6-4131-AC32-4687CB4ABD27}
     dvi:                InfName      - C:\windows\System32\DriverStore\FileRepository\tglsystemfwbios_252717.inf_amd64_4731d25c91ba89f2\tglsystemfwbios_252717.inf
     dvi:                DevDesc      - Intel TigerLake BIOS 0.0.2527.17
     dvi:                Section      - Firmware_Install.NT
     dvi:                Rank         - 0x00ff0001
     dvi:                Signer Score - Authenticode
     dvi:                DrvDate      - 03/03/2020
     dvi:                Version      - 0.0.2527.17
     dvi:      {Build Driver List - exit(0x00000000)} 10:10:14.502
     dvi:      {DIF_SELECTBESTCOMPATDRV} 10:10:14.502
     dvi:           Default installer: Enter 10:10:14.517
     dvi:                {Select Best Driver}
     dvi:                     Class GUID of device changed to: {f2e7dd72-6468-4e36-b6f1-6488f42c1b52}.
     dvi:                     Selected Driver:
     dvi:                          Description - Intel TigerLake BIOS 0.0.2527.17
     dvi:                          InfFile     - c:\windows\system32\driverstore\filerepository\tglsystemfwbios_252717.inf_amd64_4731d25c91ba89f2\tglsystemfwbios_252717.inf
     dvi:                          Section     - Firmware_Install
     dvi:                {Select Best Driver - exit(0x00000000)}
     dvi:           Default installer: Exit
     dvi:      {DIF_SELECTBESTCOMPATDRV - exit(0x00000000)} 10:10:14.517
     ndv:      Currently Installed Driver:
     ndv:           Inf Name       - oem54.inf
     ndv:           Driver Date    - 03/03/2020
     ndv:           Driver Version - 0.0.2527.17
     ndv: {Update Device Driver - exit(00000103)}
<<<  Section end 2020/03/30 10:10:14.517
<<<  [Exit status: FAILURE(0x00000103)]

**Comment by EliotSeattle** [comment]
@barrygolden can you see if there are any doc implications in this request?
Thanks,
Eliot
