### ISSUE TITLE
Table formatting broken for Single Button section

### ISSUE THREAD

**Issue by grahamm78** [MicrosoftDocs/windows-driver-docs#2137]
The table formatting is broken for the Single Button Behavior section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b390a0-606b-4c7a-5de8-17cec0428090
* Version Independent ID: a0bb23d2-75bc-ac3f-df9e-da1184c66b05
* Content: [Button behavior - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gpiobtn/button-behavior#feedback)
* Content Source: [windows-driver-docs-pr/gpiobtn/button-behavior.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gpiobtn/button-behavior.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @grahamm78, for pointing this out.
I've fixed the tables, updated the content, and merged to master. It should show in the live branch shortly.
Appreciate your help.
Eliot
