### ISSUE TITLE
NetDeviceInitConfig broken link?

### ISSUE THREAD

**Issue by woreno** [MicrosoftDocs/windows-driver-docs#2138]
NetDeviceInitConfig. https://docs.microsoft.com/windows-hardware/drivers/ddi/netdevice/nf-netdevice-netdeviceinitconfig
link appears broken; last version of RtEthAdapter refers to it as NetDeviceInitConfig (for version 2004) but previous versions refers them as NetAdapterDeviceInitConfig 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da9153f-d876-5a50-85f0-141340c301cd
* Version Independent ID: 6170bfef-a88d-a4a1-4068-02879e550e49
* Content: [Device and adapter initialization - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/netcx/device-and-adapter-initialization)
* Content Source: [windows-driver-docs-pr/netcx/device-and-adapter-initialization.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/netcx/device-and-adapter-initialization.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by aviviano** [comment]
Thanks @woreno for opening this issue. This link has been fixed.
