### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Thermi** [MicrosoftDocs/windows-driver-docs#2144]
Several broken links on this page.
Specifically the ones to:
* SP_DEVINFO_DATA
* SP_DEVICE_INTERFACE_DATA
* SP_DEVICE_INTERFACE_DETAIL_DATA 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd319d4e-ea42-605a-a0e0-fdd69a28f19f
* Version Independent ID: 1a319325-cb42-c359-cc67-f95a7f38ad8c
* Content: [Device Information Sets - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-information-sets)
* Content Source: [windows-driver-docs-pr/install/device-information-sets.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/device-information-sets.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Sorry for the delay, this is fixed! Thanks for spotting it
