### ISSUE TITLE
A bug in the example codes

### ISSUE THREAD

**Issue by PeiBruceWdf** [MicrosoftDocs/windows-driver-docs#2146]
Hi, 

I'm writing UDECX client driver for a virtual audio device, it seems there is a bug in the example codes in the function UsbCreateControlEndpoint():
    UDECX_USB_ENDPOINT_CALLBACKS_INIT(&callbacks, UsbEndpointReset);
    UdecxUsbEndpointInitSetCallbacks(endpointInit, &callbacks);

    callbacks.EvtUsbEndpointStart = UsbEndpointEvtStart;
    callbacks.EvtUsbEndpointPurge = UsEndpointEvtPurge;

The pointers assignments are in vain after initialization call.
Ideas?

And for Audio Isochronous endpoint, I have a question is that how the UDECX client driver receives and sends the packets into the Io Queue?

Thanks
-Bruce Pei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9771a49-256b-7067-34e8-cdc0c24e4b5c
* Version Independent ID: 2648d38b-43ff-7b0a-14a4-baa34cead9fa
* Content: [Write a UDE client driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/writing-a-ude-client-driver#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/writing-a-ude-client-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/writing-a-ude-client-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by DOMARS** [comment]
PeiBruceWdf - A few ideas here. I would look at the DMF code base as it tends to be more robust then the illustrative code snips that are described in the docs. If that code meets yours needs. it is often closer to production usable code. For general information: https://github.com/Microsoft/DMF/wiki/DMF-Overview 

This code seems to be UDE related, but I have not looked in depth at what DMF offers in this area:  https://github.com/microsoft/DMF/blob/225c72d5434400409487db3803328a0e51c3a7cf/Dmf/Modules.Library/Dmf_UdeClient.c

Like WDF, when DMF can be used, it is very helpful to driver development.

I would also double check that there is not code in the 17 USB related driver samples that may do some part of what you need to do. 
https://docs.microsoft.com/en-us/samples/browse/?products=windows-wdk&terms=USB

The other option to consider is reaching out to the driver community, with a complete sample of your code, your goal and the issues that you are encountering.  You can post your request for additional information in the following forums, where other driver developers and Microsoft engineers can be found.

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html) 

NTDEV forum at the [OSR Online Community](https://community.osr.com/) 

Good luck with your UDE development work.
