### ISSUE TITLE
leben

### ISSUE THREAD

**Issue by christian7877** [MicrosoftDocs/windows-driver-docs#2148]
:
// include system headers here such as wdm.h

#include &lt;initguid.h&gt;

// include system and driver-specific header files here that contain
// GUID definitions

...

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c4ebc5e6-58bd-af90-ecf5-05cda749c65c
* Version Independent ID: 8e07f7ce-c191-fe12-a7cc-b575338a907e
* Content: [Including GUIDs in Driver Code - Windows drivers](https://docs.microsoft.com/de-de/windows-hardware/drivers/kernel/including-guids-in-driver-code)
* Content Source: [windows-driver-docs-pr/kernel/including-guids-in-driver-code.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/including-guids-in-driver-code.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Hi @christian7877 
Is there a question or a comment about the documentation here? Since I don't see one, I'm going to go ahead and close this issue. If you do have a question, please either reopen this issue or create a new one.
Thanks so much,
Eliot
