### ISSUE TITLE
EWDK for Windows 10, version 1909

### ISSUE THREAD

**Issue by pprivately** [MicrosoftDocs/windows-driver-docs#2150]
Where it is? I will check Visual Studio Community in minutes, but looking at this article I am really in doubt where EWDK for Windows 10, version 1909 (version 18363) is located.
I am looking for "devcon.exe" apriopriate to my system.

**Comment by EliotSeattle** [comment]
Hi @pprivately.  
The last released version of the EWDK is version 1903. For later versions, see the [Windows Insider Preview program](https://www.microsoft.com/software-download/windowsinsiderpreviewWDK).

For version 1903, on the [WDK Downloads page](https://docs.microsoft.com/windows-hardware/drivers/download-the-wdk), in the section [Enterprise WDK (EWDK) for Windows 10, version 1903](https://docs.microsoft.com/windows-hardware/drivers/download-the-wdk#enterprise-wdk-ewdk-for-windows-10-version-1903), click [Download the EWDK for Windows 10, version 1903](https://docs.microsoft.com/legal/windows/hardware/enterprise-wdk-license-2019). When you read and accept the license terms, the download is available.
Hope this helps.
Eliot
