### ISSUE TITLE
Update "initial" driver package

### ISSUE THREAD

**Issue by sychevathotmail** [MicrosoftDocs/windows-driver-docs#2152]
After the driver is published to windows update, I can't find a way to update it with newer package.
![image](https://user-images.githubusercontent.com/63258674/78600339-69ee6200-7818-11ea-889a-850aa9d7d714.png)
image implies that there should be a way, but clicking "here" just takes me to existing driver form.

I followed guide https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/create-a-new-hardware-submission to create "initial" package. Then I log in with my company's credentials at https://partner.microsoft.com/en-us/dashboard/hardware/Search, then pick the previously uploaded (and now signed and published) driver package. Supposedly this page has some ways of uploading new CAB file, such that when I create new "label", I can pick new version.

**Comment by EliotSeattle** [comment]
Hi @sychevathotmail 
This is still a report about the docs. Please follow these instructions in the dashboard itself:

1. **First**, sign into your hardware dev center account.
2. To open a Hardware Dev Center support case for investigation, go to 
[How do I contact Partner Center Support?](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq#how-do-i-contact-partner-center-support)
and click: 
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: **[https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support).** Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

This will take you to the support site. Live Chat and Email support hours are 8am-8pm CST Monday-Friday. SLA for an initial response is 24-48 hours for email support.

All the best.
Eliot
