### ISSUE TITLE
Is it possible 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#2154]
Only few  users are getting  **CLOCK_WATCHDOG_TIMEOUT** error ,  but what i am thinking ,if we increase the timeout value in registry, above error  might not got , i am not sure, but hardware developer or software can consider this value . 

I have  already the TDR  and  TDRdelay values in registry from 60 seconds to 120 seconds

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc91461-b421-7916-14d5-9d078ce7e2f9
* Version Independent ID: f70edd69-ad6f-99df-281b-cb5da9263dd7
* Content: [Bug Check 0x101 CLOCK_WATCHDOG_TIMEOUT - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x101---clock-watchdog-timeout#feedback)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x101---clock-watchdog-timeout.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x101---clock-watchdog-timeout.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@RAJU2529  - Per this topic, the changing of these values is not recommended beyond developer testing.

https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys

I have not spent time looking at these values, but there are situations, where timeout values are coordinated. So changing one set of timers will impact another, which will impact another. 

For these type of support discussions, the forums are often the best place to discuss these things.  
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
