### ISSUE TITLE
where is the BDA drivers sample

### ISSUE THREAD

**Issue by Davin622** [MicrosoftDocs/windows-driver-docs#2155]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa3c473-f945-cb2b-850f-7a8d8cab2c2f
* Version Independent ID: 97271940-0a63-b041-2a37-85cac96ed036
* Content: [Building BDA Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/building-bda-drivers)
* Content Source: [windows-driver-docs-pr/stream/building-bda-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/stream/building-bda-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@Davin622 you can download the WDK 7.1.0 here:

https://www.microsoft.com/download/confirmation.aspx?id=11800

Select the samples in the setup dialog. 

The BDA samples can be found in src\swtuner\MergedDevice.

For example:

C:\WinDDK\7600.16385.1\src\swtuner\MergedDevice

The BDA samples are not included in the Windows 8, 8.1, and 10 driver samples.
