### ISSUE TITLE
Content not updated for windows 10 and for server 2019

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#2156]
I read the below content from this page 
**https://docs.microsoft.com/en-us/previous-versions/windows/hardware/design/dn640535(v=vs.85)?redirectedfrom=MSDN#X-201104111922342**

Authors are more talented, i read all the FAQ, from the article, i come to know unknown things  But only the article is not updated to the modern operating system details.

I request all the authors to consider to update, also make to allow  edit options .
Add screenshots if possible.

Thanking you.

**Comment by EliotSeattle** [comment]
Hi @RAJU2529 
Thanks for submitting this. The content you're pointing to is in the Previous Versions area. Generally, that means that there has been no engineering changes in that area and the feature is supported but not actively. There should be no changes in the feature or its behavior for  later versions of Windows.
All the best.
Eliot
