### ISSUE TITLE
Developer content

### ISSUE THREAD

**Issue by MrPepka** [MicrosoftDocs/windows-driver-docs#2157]
It is said that this topic is only for programmers, but there is only a description of bugcheck without any information on how to debug it. And the problem is that the meaning of bugcheck describes the first parameter, and here there is no description what the first parameter means. Can you ask for a description of at least a few parameters such as 0x7?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07ee21a7-bbd5-a1fd-fe3d-ed30c18e3aad
* Version Independent ID: bfc5146c-928e-7032-f2ad-034e1aa1a135
* Content: [Bug Check 0x11D EVENT_TRACING_FATAL_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x11d---event-tracing-fatal-error?redirectedfrom=MSDN)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x11d---event-tracing-fatal-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x11d---event-tracing-fatal-error.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@MrPepka - Thanks for this input. I added a descriptions of the parameter 1 values including 0x7. Using !analyze to see what code it considers faulting is always a good first step. I added a link to !analyze as well. Good luck in tracking down the failure you are working on.
