### ISSUE TITLE
Can I use a "Generate Debug Information (/DEBUG)" pdb to analyze "Generate Debug Info: No" executable?

### ISSUE THREAD

**Issue by ZjhHopesHakuna** [MicrosoftDocs/windows-driver-docs#2158]
For some history reasons, our release software is always built with setting "Generate Debug Info: No"(vs2017), so we do not have any pdb files.  Recently our release software crashed, I get the minidump file, "Generate Debug Info: No" executable and the source code.  Can I build a new pdb with the same code but different debug settings, and use it to analyze the minidump file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27192a67-5e49-b426-a882-430f8ad7bdd2
* Version Independent ID: 97527268-9a76-b04c-9ead-95e1e1d39a2b
* Content: [Analyze crash dump files by using WinDbg - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/crash-dump-files)
* Content Source: [windows-driver-docs-pr/debugger/crash-dump-files.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/crash-dump-files.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ZjhHopesHakuna - Building the exact same code with different settings to generate symbols may be possible. The challenge is that even small differences can cause the symbols to be rejected as not matching. The debugger doesn't want to mis-map values to variables, as that would confuse what you think you are seeing in the debugger.  You can use the !sym noisy command to see how the debugger is parsing the symbols.

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-sym


The focus for these Git issues is for documentation errors.  For questions and issues the development forums are a better route.

•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

Good luck with your work.
