### ISSUE TITLE
How to setup iso transfer in UDE examples

### ISSUE THREAD

**Issue by HamiguaLu** [MicrosoftDocs/windows-driver-docs#2162]
Hi, In "Write a UDE client driver",  I want to know how to handle the URB to support ISO transfer
For example I need to setup following parameters for ISO transfer
offset / length /status
Thanks in advance

**Comment by EliotSeattle** [comment]
This is for Write a UDE client driver](https://docs.microsoft.com/windows-hardware/drivers/usbcon/writing-a-ude-client-driver).

Hi @HamiguaLu 

Thanks for reaching out to our team. This particular channel is monitored by the men and women who write the  driver *documentation* posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to help you with your code. 
 
Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is the MSDN Windows Hardware WDK and Driver Development forum: [https://social.msdn.microsoft.com/Forums/windowshardware/](https://social.msdn.microsoft.com/Forums/windowshardware/).

The other is the NTDEV forum from OSR Online: [https://community.osr.com/](https://community.osr.com/).
 
You can post your question in those locations, and the community of developers usually give feedback fairly quickly.
 
Again, thanks for reaching out. Best of luck with this issue.
Eliot
