### ISSUE TITLE
rgb to yuv

### ISSUE THREAD

**Issue by qlianghit** [MicrosoftDocs/windows-driver-docs#2163]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb54046-ad59-cf4e-f100-86a11df1f4b0
* Version Independent ID: 396e42a5-5866-313d-861f-a5fe7b5ec104
* Content: [YUV-RGB data range conversions - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/yuv-rgb-data-range-conversions)
* Content Source: [windows-driver-docs-pr/display/yuv-rgb-data-range-conversions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/yuv-rgb-data-range-conversions.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by EliotSeattle** [comment]
Hi @qlianghit 
Did you have a question or a comment about this topic? I don't see one. I am going to close this Issue. If you have something you'd like us to look into, please reopen this issue or create another one.
Thanks,
Eliot
