### ISSUE TITLE
windows 10 driver

### ISSUE THREAD

**Issue by lilikkustanto** [MicrosoftDocs/windows-driver-docs#2164]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7021c5-410c-608f-d5d3-7a9c0e7e25a4
* Version Independent ID: 4b520306-646f-6047-fe7a-1b42a20e1054
* Content: [Overview of INF Files - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/overview-of-inf-files)
* Content Source: [windows-driver-docs-pr/install/overview-of-inf-files.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/overview-of-inf-files.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Please reopen with feedback if still needed.  Thanks!
