### ISSUE TITLE
kernel pnp

### ISSUE THREAD

**Issue by MZakiraihan** [MicrosoftDocs/windows-driver-docs#2168]
Log Name:      Microsoft-Windows-Kernel-PnP/Configuration
Source:        Microsoft-Windows-Kernel-PnP
Date:          13/04/2020 02.46.10
Event ID:      411
Task Category: None
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      DESKTOP-679BUMT
Description:
Device PCI\VEN_1B6F&DEV_7052&SUBSYS_70521849&REV_00\4&11e7f7e8&0&0048 had a problem starting.

Driver Name: usbxhci.inf
Class Guid: {36fc9e60-c465-11cf-8056-444553540000}
Service: USBXHCI
Lower Filters: 
Upper Filters: 
Problem: 0x15
Problem Status: 0x0
Event Xml:
&lt;Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"&gt;
  &lt;System&gt;
    &lt;Provider Name="Microsoft-Windows-Kernel-PnP" Guid="{9c205a39-1250-487d-abd7-e831c6290539}" /&gt;
    &lt;EventID&gt;411&lt;/EventID&gt;
    &lt;Version&gt;0&lt;/Version&gt;
    &lt;Level&gt;2&lt;/Level&gt;
    &lt;Task&gt;0&lt;/Task&gt;
    &lt;Opcode&gt;0&lt;/Opcode&gt;
    &lt;Keywords&gt;0x4000000000000000&lt;/Keywords&gt;
    &lt;TimeCreated SystemTime="2020-04-12T19:46:10.628204800Z" /&gt;
    &lt;EventRecordID&gt;1463&lt;/EventRecordID&gt;
    &lt;Correlation /&gt;
    &lt;Execution ProcessID="4" ThreadID="5168" /&gt;
    &lt;Channel&gt;Microsoft-Windows-Kernel-PnP/Configuration&lt;/Channel&gt;
    &lt;Computer&gt;DESKTOP-679BUMT&lt;/Computer&gt;
    &lt;Security UserID="S-1-5-18" /&gt;
  &lt;/System&gt;
  &lt;EventData&gt;
    &lt;Data Name="DeviceInstanceId"&gt;PCI\VEN_1B6F&amp;DEV_7052&amp;SUBSYS_70521849&amp;REV_00\4&amp;11e7f7e8&amp;0&amp;0048&lt;/Data&gt;
    &lt;Data Name="DriverName"&gt;usbxhci.inf&lt;/Data&gt;
    &lt;Data Name="ClassGuid"&gt;{36fc9e60-c465-11cf-8056-444553540000}&lt;/Data&gt;
    &lt;Data Name="ServiceName"&gt;USBXHCI&lt;/Data&gt;
    &lt;Data Name="LowerFilters"&gt;
    &lt;/Data&gt;
    &lt;Data Name="UpperFilters"&gt;
    &lt;/Data&gt;
    &lt;Data Name="Problem"&gt;0x15&lt;/Data&gt;
    &lt;Data Name="Status"&gt;0x0&lt;/Data&gt;
  &lt;/EventData&gt;
&lt;/Event&gt;

---
#### Detail Dokumen

⚠ *Jangan edit bagian ini. Diperlukan untuk masalah penautan docs.microsoft.com ➟ GitHub.*

* ID: 4fcc7b2a-1023-be98-dbab-6db4b54699e1
* Version Independent ID: e34a939c-d3ef-cc6c-dcc2-a1444acb800a
* Content: [Starting a Device in a Filter Driver - Windows drivers](https://docs.microsoft.com/id-id/windows-hardware/drivers/kernel/starting-a-device-in-a-filter-driver#feedback)
* Content Source: [windows-driver-docs-pr/kernel/starting-a-device-in-a-filter-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/starting-a-device-in-a-filter-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback. Because this is more a product question than a doc issue, I'd recommend trying one of these forums:

* [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
* [ntdev](http://www.osronline.com/showlists.cfm?list=ntdev)

Best of luck with this issue!
