### ISSUE TITLE
iSerialNumber problem

### ISSUE THREAD

**Issue by github-ap-keys** [MicrosoftDocs/windows-driver-docs#2169]
iSerialNumber should be settable to an arbitrary string. Not a Microsoft uniquely generated string. At my company we want to assign a SerialNumber string at manufacturing time and embed it into the product. This is a show-stopper for us. Please advise on whether a work-around is available that lets us have full control of the Serial Number. Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d77bb000-e08d-2d41-5b0a-26ec068f67d5
* Version Independent ID: a09fcd64-2254-6a81-4200-727456cc90c2
* Content: [USB registry settings for a function controller driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-registry-settings-for-a-function-controller-driver#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/usb-registry-settings-for-a-function-controller-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-registry-settings-for-a-function-controller-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Hi @github-ap-keys, thanks for the feedback and apologies for the delay.  I am not aware of a workaround that would allow you to generate your own serial number. You can optionally set iSerialNumber to zero (in the **HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\USBFN** registry key) if the device does not have a serial number. If this value is non-zero or does not exist, then the serial number is generated uniquely per device.
