### ISSUE TITLE
Duplicate word

### ISSUE THREAD

**Issue by chcurlet-msft** [MicrosoftDocs/windows-driver-docs#2170]
In one of the examples, pwrtest is written twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aff8a86-8549-bb27-effc-34d05b05fa06
* Version Independent ID: aa42165e-1a7f-5c1c-c19b-65e41754b318
* Content: [PwrTest Sleep Scenario - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/pwrtest-sleep-scenario)
* Content Source: [windows-driver-docs-pr/devtest/pwrtest-sleep-scenario.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pwrtest-sleep-scenario.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @chcurlet-msft for spotting this.
Fixed in source. Committed to master. Will be live shortly.
Eliot
