### ISSUE TITLE
0x5150a missing

### ISSUE THREAD

**Issue by PhoebeZi** [MicrosoftDocs/windows-driver-docs#2172]
I came across the blue screen 0x1A where the first parameter is 0x5150a. Can you add a description for this parameter?

MEMORY_MANAGEMENT (1a)
    # Any other values for parameter 1 must be individually examined.
Arguments:
Arg1: 000000000005150a, The subtype of the bugcheck.
Arg2: 000000000017897f
Arg3: 0000000000020d7f
Arg4: ffffffffc00000a0

**Comment by DOMARS** [comment]
@PhoebeZi - Thanks for passing on what you are seeing. We use input like this to guide the work that we do. For bug checks we use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, we focus on a sub set of the active stop codes. It does not look like the sub type 5150A occurs frequently, so will not cover it at this point. But if it becomes more frequent in the future, that work may be done. Thank you for your interest in improving our stop code docs.
