### ISSUE TITLE
DTrace doesn't see any probes

### ISSUE THREAD

**Issue by nawrot2137** [MicrosoftDocs/windows-driver-docs#2175]
I've encountered some problem, DTrace doesn't see any probes. VBS is enabled, bcdedit dtrace set, KD disabled, runned as admin, OS Build 19603.1000, DTrace version Sun D 1.13.1. What is wrong?
That's the output:
https://gist.githubusercontent.com/nawrot2137/19b638a83f8fee4974babc57b6a103b4/raw/fd3e1718991389f37032102e6d117874a4740d45/gistfile1.txt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98821045-8daa-85c6-37d0-001de9c1f79b
* Version Independent ID: 1956cfe8-6650-62c7-2388-584af7de2d96
* Content: [DTrace on Windows - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/dtrace#installing-dtrace-under-windows)
* Content Source: [windows-driver-docs-pr/devtest/dtrace.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/dtrace.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @nawrot2137 

Thanks for reaching out to our team. This particular channel is monitored by the men and women who write the driver *documentation* posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to help you with your code. 
 
Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is the MSDN Windows Hardware WDK and Driver Development forum: [https://social.msdn.microsoft.com/Forums/windowshardware/](https://social.msdn.microsoft.com/Forums/windowshardware/).

The other is the NTDEV forum from OSR Online: [https://community.osr.com/](https://community.osr.com/).
 
You can post your question in those locations, and the community of developers usually give feedback fairly quickly.
 
Again, thanks for reaching out. Best of luck with this issue, and sorry I can't do more.
Eliot
