### ISSUE TITLE
Publish to Windows update

### ISSUE THREAD

**Issue by UrosDakskobler** [MicrosoftDocs/windows-driver-docs#2177]
Our company is rarely publishing drivers to Windows update and every time the procedure is a little bit different.

This time there are three required fields that we don`t know how to fill.

We opened a ticket at Microsoft but didn`t get all answers.

These are the questions.

1. Provide the email address of the Microsoft sponsor working with you on this request. 

From Microsoft support we got an answer that the current workaround where you put Sysdev@microsoft.com as that field is being removed in the next portal update. What should we put here after the workaround is removed?

2. Describe how you validated the quality of this driver.

What to write here? We ran HCK and HLK tests on 13 different OS. Is this good enough?

3. The following OEMs are affected by this publication.

What to write here?

Regards

**Comment by EliotSeattle** [comment]
Hi @UrosDakskobler 
I'm so sorry that you have had trouble publishing your driver. Here are the answers to your three questions:

1.	"Provide the email address of the Microsoft sponsor working with you on this request."
If you aren’t working with someone at Microsoft, then entering **sysdev@microsoft.com** is perfectly fine. If you have worked with someone at Microsoft, it is helpful if you provide the contact.

2.	"Describe how you validated the quality of this driver."
Briefly describe the validation you performed. Your example is perfectly fine. This information is collected to help us understand what partners are--and are not--doing. Ultimately the health, and performance telemetry and associated measures guide us.

3.	"The following OEMs are affected by this publication."
If an OEM is affected please list which ones. If no OEM is affected enter **None**.

I hope that this helps.
All the best,
Eliot
