### ISSUE TITLE
KMDF version settings

### ISSUE THREAD

**Issue by woreno** [MicrosoftDocs/windows-driver-docs#2179]
i think that's usefull to inform which version of KMDF should be used with NetAdapter.
if not so, certain flags wouldn't work and queues advance can crash with pte corruptions (ex. using KMDF 1.15 with NetAdapter 1.4).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2616c6f5-e6fd-fbf3-8e1c-c3c11cb18558
* Version Independent ID: f75eb509-1e6d-029b-ee0c-d7525d2beed9
* Content: [Building a NetAdapterCx client driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/netcx/building-a-netadaptercx-client-driver#feedback)
* Content Source: [windows-driver-docs-pr/netcx/building-a-netadaptercx-client-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/netcx/building-a-netadaptercx-client-driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by aviviano** [comment]
Thanks @woreno for taking the time to open this issue. We've added the recommended KMDF version to the table on the [NetAdapterCx version overview](https://docs.microsoft.com/en-us/windows-hardware/drivers/netcx/netadaptercx-version-overview) page.
