### ISSUE TITLE
Problem signing up to Hardware Dev Centre: Your certificate's CA root cert is not in the approved list of root certs

### ISSUE THREAD

**Issue by JanCharler** [MicrosoftDocs/windows-driver-docs#2180]
Hello,

I have received my SSL.com EVCS certificate and have been successfully signing files using the signtool (successfully meaning not getting errors and receiving a success message).

However, my Kernel mode driver does not load with my Win 10 machines.

So I am now looking to sign up for the Hardware Dev Center, however I after I sign the file SignableFile.bin, I get the error: Your certificate's CA root cert is not in the approved list of root certs

I purchased SSL.com certificate after seeing them listed on the following link:

https://docs.microsoft.com/en-gb/windows-hardware/drivers/dashboard/get-a-code-signing-certificate

Why do you think I am getting this error? Have MSFT changed their trusted CA's list? Is that docs page not accurate? 

I have contacted the live chat but they were not sure of the answer to this.

If I could get some support it would be highly appreciated.

Thanks!

**Comment by EliotSeattle** [comment]
Hi @JanCharler 

This feedback mechanism sends queries to the Windows driver documentation team. We use it to track ***documentation*** issues. **The Hardware Dev Center Support** folks are the right people to help investigate a customer problem with submissions, like yours. To open a ticket with the support team:

1. **First**, sign into your hardware dev center account, and *then*...
2. Go to [Hardware Dashboard FAQ](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq), where you'll find this passage: 
 
**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

It's important that you sign into your account first.

If support, working with the dashboard developers, finds that something needs to change in the docs, we'll then update that here. I hope this helps you move toward a resolution for the CA root cert.

Eliot
