### ISSUE TITLE
Incorrectly references "port/miniport interface"

### ISSUE THREAD

**Issue by john-soklaski** [MicrosoftDocs/windows-driver-docs#2182]
This page is with regards to "WDF verification" but in several spots refers to "port/miniport interface". Likely a copy/paste error from https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/port-miniport-interface-checking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d91eb5d6-a784-45b4-97af-894148d2b091
* Version Independent ID: a6dc290c-1368-6706-1027-be1fae4718f0
* Content: [WDF verification - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/wdf-verification)
* Content Source: [windows-driver-docs-pr/devtest/wdf-verification.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/wdf-verification.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @john-soklaski for pointing this out.
Fixed in source. Should be live shortly.
Cheers,
Eliot
