### ISSUE TITLE
Meanings of the first parameter

### ISSUE THREAD

**Issue by MrPepka** [MicrosoftDocs/windows-driver-docs#2184]
Can you add descriptions what the first parameter means? This bugcheck depends on the first parameter, and no such parameter is described here. To begin with, I propose the first parameter 0x10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9519985f-edb9-d653-0f95-8449aa72efba
* Version Independent ID: f0c86b15-a870-c39c-4e03-4164ad3f304c
* Content: [Bug Check 0x113 VIDEO_DXGKRNL_FATAL_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x113---video-dxgkrnl-fatal-error?redirectedfrom=MSDN)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x113---video-dxgkrnl-fatal-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x113---video-dxgkrnl-fatal-error.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@MrPepka - Thanks for the input that on the additional parameter for the VIDEO_DXGKRNL_FATAL_ERROR bug check topic. I have created and internal work item to track the work for this, so will close this issue. As we have limited resources, we use data like this to help guide our work. Good luck with your efforts in blue screen troubleshooting, and thanks for your interest in the bug check documentation.
