### ISSUE TITLE
Confusingly worded:

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2185]
> The IddCx provides an interface to the Indirect Display driver to interact
> with the Windows graphics sub-system in the following ways:

### X provides an interface to Y to interact with Z

Is X providing an interface-to-Y so that Z can interact with X, or is X providing Y with an interface, so that Y can interact with Z?

### I would suggest something like the following:

> The IddCx provides the Indirect Display driver with an interface that it can use to interact
> with the Windows graphics sub-system in the following ways:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d294cf2c-339d-15ac-0170-9142903e772a
* Version Independent ID: aaf94242-9e91-9b8e-9ecc-9e40e855d95d
* Content: [Indirect Display Driver Model Overview - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/indirect-display-driver-model-overview?redirectedfrom=MSDN#feedback)
* Content Source: [windows-driver-docs-pr/display/indirect-display-driver-model-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/indirect-display-driver-model-overview.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mr-intj , thanks for your many insightful questions and suggestions regarding the IDD pages. I've updated the IDD docs accordingly. For this issue, I have updated the language to make the interaction clear.
