### ISSUE TITLE
A diagram would really help here

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2186]
&gt; The Indirect Display driver model is implemented as a UMDF class extension.

Is this referring to the Microsoft-provided portion of a display minidriver, or to the component that a developer would build? Sounds like the latter, but it says "...the _model_ is implemented", which implies the Microsoft-provided portion...

A diagram (e.g. showing UM components above and KM below) would clear up a lot of the ambiguity here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d294cf2c-339d-15ac-0170-9142903e772a
* Version Independent ID: aaf94242-9e91-9b8e-9ecc-9e40e855d95d
* Content: [Indirect Display Driver Model Overview - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/indirect-display-driver-model-overview?redirectedfrom=MSDN)
* Content Source: [windows-driver-docs-pr/display/indirect-display-driver-model-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/indirect-display-driver-model-overview.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mr-intj , I've updated the language to make clear that the IDD is to be provided by the developer, and have added a diagram with associated components.
