### ISSUE TITLE
Warning or ... ?

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2187]
&gt; The Indirect Display driver is a user mode only model with _no support for kernel mode
&gt; components_, hence the driver is _able to use any DirectX API's_ in order to process the
&gt; desktop image. In fact, the IddCx provides the desktop image to encode in a DirectX
&gt; surface.

(emphasis mine)

It's not clear whether this implies that such a user-mode driver is excluded from interacting with, say, OpenGL or Vulcan (thus making it incompatible)? Is this meant to be a warning (i.e. "a driver of this type can only use DirectX"), or is it just informational?

A sentence could be added to mention alternatives to DirectX and how the aforementioned paragraph relates to them, if at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d294cf2c-339d-15ac-0170-9142903e772a
* Version Independent ID: aaf94242-9e91-9b8e-9ecc-9e40e855d95d
* Content: [Indirect Display Driver Model Overview - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/indirect-display-driver-model-overview?redirectedfrom=MSDN)
* Content Source: [windows-driver-docs-pr/display/indirect-display-driver-model-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/indirect-display-driver-model-overview.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mr-intj , you raise a very important point here. I've added clarification that libraries such as OpenGL and Vulkan are not appropriate for driver use.
