### ISSUE TITLE
Pretend I'm new to this...

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2188]
&gt; IddCx uses the extensible UMDF object model to represent _graphics objects_,
&gt; they are covered in following sections.

An example in parentheses would be good here. "Graphics objects" is so vague as to be nearly meaningless (e.g. icons, bitmaps, vector graphics, bitmasks, screen buffers, shaders, etc).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4acd9d50-9d09-8ffb-6f3f-68988f232a06
* Version Independent ID: 685ee4b1-3b5c-5647-8953-0aae812cc36f
* Content: [IddCx Objects - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/iddcx-objects)
* Content Source: [windows-driver-docs-pr/display/iddcx-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/iddcx-objects.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mr-intj , I agree that graphics objects was a bad term. I've updated this page to better describe which components are represented by IddCx's objects. I also added info regarding order of object creation.
