### ISSUE TITLE
The devicingest devices that ever deviced

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2189]
&gt; The IDDCX_ADAPTER should only be created once all the _devices that
&gt; make up the Indirect Display solution_ have been started successfully

For an IddCx driver, _adapter_ would refer to some non-videocard kind of adapter, like a USB dongle.

If "devices that make up the indirect display solution" is referring to the monitors, then this essentially says "Don't create the adapter object until the monitor(s) have all started". But the way the IddCx callback interface is structured, it seems that the adapter gets created first, then we get callbacks for monitors on that adapter.

I've found the driver documentation tends to overload lots of terms like _driver_, _device_, _object_, _class_, etc. It can be ambiguous and very difficult to follow at times. A few examples in the text or a diagram would help immensely.

&gt; ..should only be created once all the devices that make up the Indirect
&gt; Display solution **(e.g. Blort, Snarf, or FizzBuzz)** have been started...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4acd9d50-9d09-8ffb-6f3f-68988f232a06
* Version Independent ID: 685ee4b1-3b5c-5647-8953-0aae812cc36f
* Content: [IddCx Objects - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/iddcx-objects)
* Content Source: [windows-driver-docs-pr/display/iddcx-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/iddcx-objects.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mr-intj , another great clarification ask. I pulled this information into its own "Handling multifunction devices" section because it is for a niche scenario. I also added clarifying language about which device is which, and provided an example.
