### ISSUE TITLE
Definitions or links would be helpful

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2190]
&gt; This object represents a swapchain that will provide...

Swapchain? Had to Google this the first time I read it.

&gt; This object represents an active OPM context from...

OPM? Took more Googling. Don't recall ever hearing this abbreviation before.

Links and/or footnotes or hover-text-definitions would be good for first occurrences of terms like these.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4acd9d50-9d09-8ffb-6f3f-68988f232a06
* Version Independent ID: 685ee4b1-3b5c-5647-8953-0aae812cc36f
* Content: [IddCx Objects - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/iddcx-objects)
* Content Source: [windows-driver-docs-pr/display/iddcx-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/iddcx-objects.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@mr-intj , I've added links to the swapchain and OPM docs, and also added links to all function refpages. THANK YOU again for your several IDD-related issues!
