### ISSUE TITLE
Is there any notification system in place that we can subscribe to?

### ISSUE THREAD

**Issue by NileshMali1** [MicrosoftDocs/windows-driver-docs#2191]
Is there any notification system in place we can subscribe to, to get notifications on submissions state changes, updates and/or details etc., instead of polling using the APIs?

Also, while associating application with active directory in order to be able to use the APIs, I recall of two URL fields, something like "ReplyTo URL" & "Submit URL". Could someone please let us know what are those for and provide us the use cases of those URLs?

Best,
NM

**Comment by EliotSeattle** [comment]
Hi @NileshMali1 

Thanks so much for reaching out. Sadly, I am not going to be able to help you directly. Sorry.

For the first question about notifications, we do not have a system like that in place, currently. The team who engineers the dashboard is aware of the request and will consider the idea in their planning.

For your second question, this feedback forum gets sent to the Windows driver documentation team, which I manage. We use it to track ***documentation*** issues. The Hardware Dev Center Support folks are the right people to help investigate a customer problem with API. To open a ticket with the support team:

1. **First**, sign into your hardware dev center account, and *then*...
2. Go to [Hardware Dashboard FAQ](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq), where you'll find this passage: 
 
**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). Select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

It's important that you sign into your account first.

If support, working with the dashboard developers, finds that something needs to change in the docs, we'll then update that here. I hope this helps.

Eliot
