### ISSUE TITLE
link  to NET_IF_MEDIA_CONNECT_STATE   is dead

### ISSUE THREAD

**Issue by cstraessner** [MicrosoftDocs/windows-driver-docs#2192]
link  to NET_IF_MEDIA_CONNECT_STATE   is dead

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ec565c4a-4bd9-d123-0ee1-b5fba04ae8fa
* Version Independent ID: 7effbdf0-2a98-6b4b-50b9-a715dabb455d
* Content: [OID_GEN_MEDIA_CONNECT_STATUS_EX - Windows drivers](https://docs.microsoft.com/de-de/windows-hardware/drivers/network/oid-gen-media-connect-status-ex#feedback)
* Content Source: [windows-driver-docs-pr/network/oid-gen-media-connect-status-ex.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/oid-gen-media-connect-status-ex.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by EliotSeattle** [comment]
Hi @cstraessner 

Thanks for finding this and creating the Issue. I've fixed it in the source and it should be live very shortly. It will now point to [https://docs.microsoft.com/windows/win32/api/ifdef/ne-ifdef-net_if_media_connect_state](https://docs.microsoft.com/windows/win32/api/ifdef/ne-ifdef-net_if_media_connect_state)

Thanks for your help.
Eliot
