### ISSUE TITLE
InfVerif replaces the ChkINF tool

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2193]
&gt; Use the ChkINF tool to validate the driver's INF file.

[InfVerif replaces the ChkINF tool](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/infverif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43f22036-4051-4231-2205-54067fe63077
* Version Independent ID: a78deb67-4bdb-0712-bb6f-89adf87d6396
* Content: [Determine Why UMDF Driver Fails to Load or Device Fails to Start - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/determining-why-the-umdf-driver-fails-to-load-or-the-umdf-device-fails)
* Content Source: [windows-driver-docs-pr/wdf/determining-why-the-umdf-driver-fails-to-load-or-the-umdf-device-fails.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/determining-why-the-umdf-driver-fails-to-load-or-the-umdf-device-fails.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Fixed. Thanks for the report.
