### ISSUE TITLE
Incorrect text in "Activating this option"

### ISSUE THREAD

**Issue by GabeSJones** [MicrosoftDocs/windows-driver-docs#2194]
In a couple of places, you need to do 

   port/miniport interface checking =&gt; code integrity checking 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac8c046-9589-f66b-721d-5cc03c81cf33
* Version Independent ID: 8abb75ea-ee90-e8ca-4d89-0414056be501
* Content: [Code integrity checks - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/code-integrity-checking#feedback)
* Content Source: [windows-driver-docs-pr/devtest/code-integrity-checking.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/code-integrity-checking.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks very much, @GabeSJones 
I was looking for a good phrase to replace port/miniport driver interface with.
Appreciate the suggestion.
Eliot
