### ISSUE TITLE
Note refers to non-existent C++ code example

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2197]
&gt; Note: In the C++ code above...

There is no C++ code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9445c977-9f8c-00c6-68fa-b575ab325fcf
* Version Independent ID: 58963a0b-6f4b-b6ee-f454-7e72e68d7bef
* Content: [INF Manufacturer Section - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-manufacturer-section)
* Content Source: [windows-driver-docs-pr/install/inf-manufacturer-section.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-manufacturer-section.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Great eye @mr-intj.  I just pushed the fix, should be on the live site momentarily
