### ISSUE TITLE
Link to "WDK Insider Preview builds" returns 404

### ISSUE THREAD

**Issue by brussee** [MicrosoftDocs/windows-driver-docs#2198]
The link to the "WDK Insider Preview builds" at the top of this page is broken and also at the bottom of this page the "Download the WDK Insider Preview" link also returns 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#feedback)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks so much, @brussee for bringing this to my attention.

Both those links work for me, HOWEVER, I am already a member of the Windows Insider program. I've made the first phrase in that sentence a link to [https://insider.windows.com/](https://insider.windows.com/), where you can quickly sign up. THEN, you can download the Windows Insider kits all day long!

Appreciate that you found this, told us about it, and I apologize for any inconvenience.
Eliot
