### ISSUE TITLE
Confusing phrasing

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2199]
&gt; **Note** This directive is available in UMDF versions 1.11 _and earlier_.

When I read this, I do a kind of mental double-take, because I'm expecting "and later". This phrasing is used in multiple places to describe features that only apply to UMDF version 1.x.

When something is only available in a range of earlier versions, it's usually phrased differently, e.g. 

> This directive is _only used_ in 1.x versions of UMDF.
> UDMF 2.x versions use &lt;blah&gt; instead...

Also, these notes often appear after the listing of a term and its definition. I think it might be more efficient for the reader to do something like:

> **SomeEntry** = *blah,[blah],blah*
> (UMDF 1.x only)
>  
> This directive references an INF-writer-defined component blah blah blah...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd0d4c0-7cfd-278b-12e4-a6532269db54
* Version Independent ID: 660209eb-539f-6ad5-dc93-7879d84308a1
* Content: [Specifying WDF Directives in INF Files - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/specifying-wdf-directives-in-inf-files)
* Content Source: [windows-driver-docs-pr/wdf/specifying-wdf-directives-in-inf-files.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/specifying-wdf-directives-in-inf-files.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
In addition to addressing your suggestions, I gave https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/specifying-wdf-directives-in-inf-files an overhaul to improve navigation.  Now you can use the "In this section" nav pane on the right to see and jump between sections. Let me know if you find it more useful. I may do the same with https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/registry-values-for-debugging-kmdf-drivers.
