### ISSUE TITLE
What about device icons?

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2202]
> A driver package can also contain other files, such as a device installation application,
>_a device icon), device property pages, and so forth. For more information, see the
> following topics:
>  
> * Providing Device Property Pages
> * Installing a Boot-Start Driver

If a driver developer wants to install icon(s) with their driver, neither of the two options/links above seem relevant.

**Context:**

In my case, I was reading this page for guidance about the recommended folder (on the target system) to install my .ico file(s).

During install, my `my-driver.dll` gets copied into `%SystemRoot%\System32\drivers\UMDF`, and on my PC that folder _only_ contains DLLs. Most other INF files I found online copy their icon files either to `%SystemRoot%` or `%SystemRoot%\System32`, but I don't like just dumping files there and hoping to avoid name collisions...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d596ea2c-dee5-42eb-c5c3-87d74a9047b3
* Version Independent ID: 697d75cc-69f7-6790-194f-8c9478cff3c4
* Content: [Components of a Driver Package - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/components-of-a-driver-package)
* Content Source: [windows-driver-docs-pr/install/components-of-a-driver-package.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/components-of-a-driver-package.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @mr-intj, I just updated https://docs.microsoft.com/en-us/windows-hardware/drivers/install/providing-vendor-icons-for-the-shell-and-autoplay. Let me know if it does not answer your question here and in #2204. 

Good luck!

**Comment by mr-intj** [comment]
Nice. Much better  :-)
