### ISSUE TITLE
What about icon resources (vs files)?

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2204]
If a UMDF driver developer is installing a driver DLL, it's natural to wonder whether they can embed the device icon(s) as resources in the DLL, rather than installing separate .ico files.

This page doesn't seem to acknowledge any method other than .ico files, but [this docs.microsoft.com page](https://docs.microsoft.com/en-us/windows/win32/shell/how-to-specify-an-icon--label--or-device-handler-for-a-device-using-a-device-group) explains how to manually configure the registry to refer to icon resources. If it _is_ actually possible to do it that way from install, it'd be good if that was covered here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425585e9-47d1-24e8-df6e-d6081db77e63
* Version Independent ID: ec35f491-0229-c592-a04b-08e86966cfa3
* Content: [Providing Vendor Icons for the Shell and AutoPlay - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/install/providing-vendor-icons-for-the-shell-and-autoplay)
* Content Source: [windows-driver-docs-pr/install/providing-vendor-icons-for-the-shell-and-autoplay.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/providing-vendor-icons-for-the-shell-and-autoplay.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
See #2202 for resolution
