### ISSUE TITLE
Notes boxes incomplete

### ISSUE THREAD

**Issue by TimPeterson** [MicrosoftDocs/windows-driver-docs#2217]
The contents of the two purple Notes boxes on this page need to be fleshed out into complete sentences.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 149712ed-bfe4-9255-5121-b8d105cc9898
* Version Independent ID: b51a9f6c-d0c0-fb16-e409-0e59e8c4717b
* Content: [DShow Bridge implementation guidance for UVC devices - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/dshow-bridge-implementation-guidance-for-usb-video-class-devices#feedback)
* Content Source: [windows-driver-docs-pr/stream/dshow-bridge-implementation-guidance-for-usb-video-class-devices.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/stream/dshow-bridge-implementation-guidance-for-usb-video-class-devices.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Updated the first note to clarify that the MJPEG  is only decompressed once in FrameServer and then the uncompressed translated media formats are offered to multiple possible applications.

The second note was removed and inserted as a comment in the sample code.
