### ISSUE TITLE
Link to SDK pages?

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-driver-docs#2218]
It should be added, instead of just a note to search the SDK docs sbout oplocks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48134e13-c8c3-555f-93ad-505f74550e9f
* Version Independent ID: 3c450b44-f3e7-fda6-a036-598013086a99
* Content: [FSCTL_REQUEST_OPLOCK_LEVEL_2 control code - Windows drivers](https://docs.microsoft.com/en-gb/windows-hardware/drivers/ifs/fsctl-request-oplock-level-2)
* Content Source: [windows-driver-docs-pr/ifs/fsctl-request-oplock-level-2.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/fsctl-request-oplock-level-2.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by EliotSeattle** [comment]
Thanks so much, @alfaunits for pointing this out. Added the links in Issue #2223. Should be live shortly.
