### ISSUE TITLE
Analyzer Logs Events

### ISSUE THREAD

**Issue by tecnodados** [MicrosoftDocs/windows-driver-docs#2231]
[ManagerLogs]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b231b5a-b4d3-12ee-4682-e66806dcafa6
* Version Independent ID: 70227f78-0710-18d8-4b68-61b1143cb625
* Content: [Video Debugging your driver with WDF source code - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/video--debugging-your-driver-with-wdf-source-code#feedback)
* Content Source: [windows-driver-docs-pr/wdf/video--debugging-your-driver-with-wdf-source-code.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/video--debugging-your-driver-with-wdf-source-code.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Sorry, I'm not sure what this means. If you have specific feedback on the documentation, please feel free to re-open with more detail.
