### ISSUE TITLE
Microsoft Store Certification Requirements - broken link

### ISSUE THREAD

**Issue by tewarid** [MicrosoftDocs/windows-driver-docs#2241]
Link Microsoft Store Certification Requirements seems to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7158cba-8395-64d1-9c63-442bfff28801
* Version Independent ID: 8ccb3ef7-39ab-024f-2121-c08b94e12786
* Content: [Step 5 Submit the Microsoft Store device app - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/step-5--submit-the-app)
* Content Source: [windows-driver-docs-pr/devapps/step-5--submit-the-app.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/step-5--submit-the-app.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Fixed link to point to [https://docs.microsoft.com/windows/uwp/publish/the-app-certification-process](https://docs.microsoft.com/windows/uwp/publish/the-app-certification-process)
