### ISSUE TITLE
where is the implement of function GetDeviceHandle  and GetWinUSBHandle ?

### ISSUE THREAD

**Issue by wenqf11** [MicrosoftDocs/windows-driver-docs#2246]
where is the implement of function GetDeviceHandle  and GetWinUSBHandle ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab9a2103-b49a-305b-674d-eeb241944822
* Version Independent ID: 6f7d87a9-126e-6a3f-3087-0005482a5f60
* Content: [How to Access a USB Device by Using WinUSB Functions - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/using-winusb-api-to-communicate-with-a-usb-device#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/using-winusb-api-to-communicate-with-a-usb-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/using-winusb-api-to-communicate-with-a-usb-device.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Thanks for the feedback @wenqf11 and apologies for the delay.  I've added a link to a code example you can use in step 6 of the page in question.  That change should appear on the live site within a few moments.
