### ISSUE TITLE
Path to DeviceMetadataWizard.exe

### ISSUE THREAD

**Issue by tewarid** [MicrosoftDocs/windows-driver-docs#2250]
For Windows 10, I tried "%ProgramFiles(x86)%\Windows Kits\10\bin\x86", but didn't find DeviceMetadataWizard.exe either. It looks like DeviceMetadataWizard.exe has been moved to a SDK version specific location such as "%ProgramFiles(x86)%\Windows Kits\10\bin\10.0.18362.0\x86".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36aa8656-cbd2-59d4-6449-51b8085a307e
* Version Independent ID: 48bbb0f2-9b1e-9695-902c-403f53f803a1
* Content: [Step 2 Create device metadata for your UWP device app - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/step-2--create-device-metadata)
* Content Source: [windows-driver-docs-pr/devapps/step-2--create-device-metadata.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/step-2--create-device-metadata.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by RAJU2529** [comment]
@tewarid ,  it was moved to  this location 
**C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\**

**C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64**
