### ISSUE TITLE
Example text described as being "in bold" isn't

### ISSUE THREAD

**Issue by dofzin** [MicrosoftDocs/windows-driver-docs#2256]
On this page the text makes several references to parts of examples shown *in bold* but I'm not seeing any text in the examples shown in bold face. After the second snippet, the text reads "Notice that the section in bold is an interrupt dispatch." But no section of the referenced example text--any any example text on this page-- is bold.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3096645-f471-68d7-25b4-003ef57340a3
* Version Independent ID: bee865f9-f6da-335b-8f5a-fef4ffc36278
* Content: [Debugging an Interrupt Storm - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-an-interrupt-storm#feedback)
* Content Source: [windows-driver-docs-pr/debugger/debugging-an-interrupt-storm.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugging-an-interrupt-storm.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@dofzin -  I updated the topic to describe the elements in words, replacing the incorrect reference to "bold". Thanks for filing this issue and the help in improving the debugger docs.
