### ISSUE TITLE
wonderful

### ISSUE THREAD

**Issue by radimscholly** [MicrosoftDocs/windows-driver-docs#2259]
in kmdf hello world is no mention about tracing!!!
would be great to adopt tutorial for beginners!!!

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: b5cbaa70-d06d-bd5b-6a54-d668ecc5a913
* Version Independent ID: 2ef80a3b-4852-33cb-19f4-90aa731ebe7a
* Content: [DCH Design Principles and Best Practices - Windows drivers](https://docs.microsoft.com/cs-cz/windows-hardware/drivers/develop/dch-principles-best-practices#feedback)
* Content Source: [windows-driver-docs-pr/develop/dch-principles-best-practices.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/dch-principles-best-practices.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @radimscholly 

Thanks for the feedback and apologies for the delay.  Have you tried looking at https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver?  The page you mention above (https://docs.microsoft.com/cs-cz/windows-hardware/drivers/develop/dch-principles-best-practices) does not have any KMDF Hello World info.

For an intro to tracing, try https://docs.microsoft.com/windows-hardware/drivers/devtest/wpp-software-tracing.

After you review these articles, please let me know if you have specific questions about tracing and I'll do my best to help.
