### ISSUE TITLE
Invalid grammar in "resolution"

### ISSUE THREAD

**Issue by acepace** [MicrosoftDocs/windows-driver-docs#2260]
The !analyze debug extension displays information about the bug check and can be very in determining the root cause.

Probably meant to be "can be very helpful" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8f80f5-7104-5fe9-8f10-adf04f6c6a8c
* Version Independent ID: c087aec7-b173-a4d0-4b23-742982c736e7
* Content: [Bug Check 0x20001 HYPERVISOR_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x20001--hypervisor-error#feedback)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x20001--hypervisor-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x20001--hypervisor-error.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Thanks, @acepace.  we prefer "very" on its own, but I fixed it for you anyway. ;-)

Appreciate the feedback!
Eliot
