### ISSUE TITLE
Problem with virtual serial

### ISSUE THREAD

**Issue by ehsankh88** [MicrosoftDocs/windows-driver-docs#2261]
Virtual Serial samples do not work correctly with Qt Serial port driver. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb43eea-a294-cbed-f814-3b360eae105c
* Version Independent ID: cf56188a-15a5-0f77-6da4-8d3309c0a828
* Content: [Serial driver samples - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/samples/serial-driver-samples#feedback)
* Content Source: [windows-driver-docs-pr/samples/serial-driver-samples.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/samples/serial-driver-samples.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. 

I would recommend that you open an issue in the [Windows-driver-samples](https://github.com/microsoft/Windows-driver-samples) repo on the virtual serial samples implementation in your scenario.

You may also have success posting your questions in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
