### ISSUE TITLE
Is firmware is tested?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#2262]
If these firmwares will you under go testing by Microsoft windows drivers testing lab computers.
Some times incompatible firmwares made the PC in unbootabe condition. I Heard some cases. Microsoft forums

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a033497-facc-1035-3597-dd2e84157bcc
* Version Independent ID: 2ddb2a36-f16a-333e-a273-25922167ba00
* Content: [Firmware measures - Windows drivers](https://docs.microsoft.com/en-au/windows-hardware/drivers/dashboard/firmware-measures)
* Content Source: [windows-driver-docs-pr/dashboard/firmware-measures.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/firmware-measures.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @RAJU2529 

I'm not sure that I understand your question, but more information about firmware testing can be found at [https://docs.microsoft.com/windows-hardware/drivers/bringup/windows-uefi-firmware-update-platform](https://docs.microsoft.com/windows-hardware/drivers/bringup/windows-uefi-firmware-update-platform).

Hope this helps.
Eliot
