### ISSUE TITLE
0xC8 UniqueValue 2

### ISSUE THREAD

**Issue by HollisTech** [MicrosoftDocs/windows-driver-docs#2264]
The documentation here for parameter 1 UniqueValue 2 is wrong.  UniqueValue  2 indicates that Arg2 is a callout routine and Arg3 is the first parameter of the callout routine. See the debugger documentation in !analyze, that appears to be correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d57fa9a-847d-93c8-428f-8aef1098108b
* Version Independent ID: c9eff23f-2a3f-0be0-fe49-3e5e62c4a7b6
* Content: [Bug Check 0xC8 IRQL_UNEXPECTED_VALUE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xc8--irql-unexpected-value)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0xc8--irql-unexpected-value.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0xc8--irql-unexpected-value.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@HollisTech Thanks for this request. I updated the topic to show the correct values that are also shown in !analyze show. Thanks for seeing this issue and thanks for providing feedback on the stop code docs.
