### ISSUE TITLE
What does the sleep button do?

### ISSUE THREAD

**Issue by PoolloverNathan** [MicrosoftDocs/windows-driver-docs#2265]
I know that the sleep button puts your computer in S{1..3}, but which one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e17d9b3-9e6b-df00-e249-38a0cd5e1099
* Version Independent ID: 83d9bce2-8b16-812f-d587-61527d4eba50
* Content: [System Sleeping States - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/system-sleeping-states#feedback)
* Content Source: [windows-driver-docs-pr/kernel/system-sleeping-states.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/system-sleeping-states.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by RAJU2529** [comment]
@tedhudek .  We can't give real answer without  practical knowledge.  I knew that some desktop motherboards have sleep button policies are enabled like S1 or S2 or S3 or S4.
Without testing in all modes, real solution is not possible.
Keep waiting for experienced users replies.

**Comment by PoolloverNathan** [comment]
Okay.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tedhudek** [comment]
Thanks for the question.

Typically the answer is S3.  I've just added some detail to https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/system-sleeping-states that should be live in a few minutes. You'll also see a link to the commit above if you want to see what changed.

Hope this helps!
