### ISSUE TITLE
The COM port number is wrong in the description

### ISSUE THREAD

**Issue by Therena** [MicrosoftDocs/windows-driver-docs#2266]
Currently there is:
---------------------------------------------------------------------------------------------------
The following command configures the target computer to use a serial connection for debugging. The command also specifies that the debugging connection will use **COM2** and a baud rate of 115,200.

bcdedit /dbgsettings serial debugport:1 baudrate:115200

How it should be:
---------------------------------------------------------------------------------------------------
The following command configures the target computer to use a serial connection for debugging. The command also specifies that the debugging connection will use **COM1** and a baud rate of 115,200.

bcdedit /dbgsettings serial debugport:1 baudrate:115200

On this page:
---------------------------------------------------------------------------------------------------
https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/CONTRIBUTING.md

**Comment by DOMARS** [comment]
@Therena - Thanks for the PR you provided to fix this issue.
