### ISSUE TITLE
Use of page-file-backed vs file-backed sections

### ISSUE THREAD

**Issue by plcruise** [MicrosoftDocs/windows-driver-docs#2269]
I wonder whether I understood correctly, that a possible scenario for page-file backed section objects is to link two different threads of seperate processes to the same page-file backed object and  store the altered data temporarily. When one of the threads finishes the page-file backed object is kept alive by the second thread which can have a view to a file-backed section object to store some of the data from the page-file-backed section object to permanent memory. Or did I get the concept all wrong?

Kind Regards
Paul Kruse
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a11b2ddd-3e1b-c7c9-024b-dd5f990ecbea
* Version Independent ID: 100658f1-18b5-eacd-59e9-12925971ee07
* Content: [File-Backed and Page-File-Backed Sections - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/file-backed-and-page-file-backed-sections)
* Content Source: [windows-driver-docs-pr/kernel/file-backed-and-page-file-backed-sections.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/file-backed-and-page-file-backed-sections.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @plcruise 

Thanks for the feedback and apologies for the delay. Your scenario sounds entirely plausible to me, upon reading the article in question. I was learning by reading it just as you were, though, so I can't say for sure. 

If it's still an issue, I'd recommend asking in one of the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
* [OSR's ntdev List](http://www.osronline.com/showlists.cfm?list=ntdev)

Please let me know if your investigation results in changes you'd like to make to https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/file-backed-and-page-file-backed-sections -- or just click **Edit** on that page and spin up a PR.

Good luck!
