### ISSUE TITLE
SL_IGNORE_READONLY_ATTRIBUTE

### ISSUE THREAD

**Issue by maharmstone** [MicrosoftDocs/windows-driver-docs#2279]
This page doesn't mention the flag SL_IGNORE_READONLY_ATTRIBUTE, which appears to have been introduced with Windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd5bbdd7-26e8-d090-e5cb-39a08df73689
* Version Independent ID: 5e7eebfc-3a1c-8979-02df-42a0cbcbc177
* Content: [IRP_MJ_CREATE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-create)
* Content Source: [windows-driver-docs-pr/ifs/irp-mj-create.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/irp-mj-create.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks, @maharmstone , I've added the missing SL_xxx flags!
