### ISSUE TITLE
Diagrams are excellent. 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#2283]
Diagrams are look like a Anatomy of Human body.
I am not a developer, But it explains the contents of the parts.
My suggestion is indicate screenshot number in each diagram or screenshots

---
#### Document DetailsqK⁰s

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e5e417-647c-0c3a-9c25-83a7be9efe3a
* Version Independent ID: 6ccb6634-97cb-b66f-3ca5-0e58218abdc0
* Content: [Using an Extension INF File - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-an-extension-inf-file)
* Content Source: [windows-driver-docs-pr/install/using-an-extension-inf-file.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/using-an-extension-inf-file.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @RAJU2529 for the feedback. I looked at the page, and there are only 2 diagrams. Each one is prefaced with something like "in the following diagram..."
