### ISSUE TITLE
useless

### ISSUE THREAD

**Issue by deep2002n** [MicrosoftDocs/windows-driver-docs#2286]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aff8a86-8549-bb27-effc-34d05b05fa06
* Version Independent ID: aa42165e-1a7f-5c1c-c19b-65e41754b318
* Content: [PwrTest Sleep Scenario - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/pwrtest-sleep-scenario)
* Content Source: [windows-driver-docs-pr/devtest/pwrtest-sleep-scenario.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pwrtest-sleep-scenario.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @deep2002n 
Appreciate that you took the time to create the feedback. Can you give me something to go on in order to see if I can make the content better? What was missing that you expected to find? What is the in that topic that isn't working for you?
Thanks,
Eliot

**Comment by RAJU2529** [comment]
@EliotSeattle . Could you tell me why this is useless. I found those are useful. Commamds for testing laptop battery how much time giving life to work.

**Comment by deep2002n** [comment]
Hi,I am not related to this work (or any other work) on GitHub, it seems the comment was put by mistake
Please delete it, I checked but could not find option to delete.
I regret the in-convenience .
Deep Narayan
    On Thursday, 28 May, 2020, 01:02:56 am IST, VARADHARAJAN K <notifications@github.com> wrote:  
 
 


@EliotSeattle . Could you tell me why this is useless. I found those are useful. Commamds for testing laptop battery how much time giving life to work.

**Comment by RAJU2529** [comment]
@deep2002n . Click three dots, rename the title and click save

**Comment by EliotSeattle** [comment]
This issue is closed. No need for further action.
And no worries, @deep2002n. I just expect to see actionable feedback from you next time. ;-)
Thanks,
Eliot
