### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs#2287]
Under the "Related topics" link near the bottom, the "Developing, Testing, and Deploying Drivers" is invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287160ad-f2a5-789a-2d7d-ff336514c11e
* Version Independent ID: a138162d-2b80-725b-212b-277bae8f177d
* Content: [Write a Universal Windows driver (UMDF 2) based on a template - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-umdf-driver-based-on-a-template)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-umdf-driver-based-on-a-template.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-umdf-driver-based-on-a-template.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks for the heads up, @druske 
I fixed that link and pushed it to the master branch. Should be live soon and may be live already.
I hope my day continues like this, with small issues that are easily resolved. :-)
Thanks for the feedback!
Eliot
