### ISSUE TITLE
typo - Human Interface Devices (HID) cients are drivers

### ISSUE THREAD

**Issue by RJdot** [MicrosoftDocs/windows-driver-docs#2291]
typo - Human Interface Devices (HID) cients are drivers
"cients" should be "clients"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171adc53-73dc-3c06-3afb-492beb9b66e0
* Version Independent ID: 22948247-5c63-a513-6276-f27ce81705a6
* Content: [HID Clients Overview - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/hid-clients)
* Content Source: [windows-driver-docs-pr/hid/hid-clients.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/hid-clients.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by EliotSeattle** [comment]
Oopsies.
Thanks, @RJdot for spotting this typo. I made the fix and posted it.
Eliot
