### ISSUE TITLE
Missing note about network configuration

### ISSUE THREAD

**Issue by petrutlucian94** [MicrosoftDocs/windows-driver-docs#2293]
After running ``kdnet`` in the target vm and rebooting, a new interface shows up:
``Ethernet adapter Ethernet (Kernel Debugger)``.

It won't preserve the previous static IP configuration, which is likely going to be used along with an internal NAT-ed network. This means that the instance will become unreachable.

While easy to spot, it would probably be a good idea to add a note about this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564a660-e978-17e0-b1ab-885eb9345046
* Version Independent ID: 97c67bc0-5e7d-01ff-f4ba-1c626820614c
* Content: [Setting Up Network Debugging of a Virtual Machine with KDNET - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-network-debugging-of-a-virtual-machine-host)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-network-debugging-of-a-virtual-machine-host.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-network-debugging-of-a-virtual-machine-host.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@petrutlucian94 - Thanks for this suggestion. Yes a special type of kernel debug adapter is created to allow debugging. I added a note to the topic to mention this. Good luck with your VM debugging work!
