### ISSUE TITLE
Are you sure install Visual Studio 2015 not 2019?

### ISSUE THREAD

**Issue by huhuang03** [MicrosoftDocs/windows-driver-docs#2295]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ebf2732-040f-8496-4583-11d341a25dbb
* Version Independent ID: c685bd0a-8f1a-9697-2ae9-425023ef8a47
* Content: [Write a Universal Windows driver (KMDF) based on a template - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-kmdf-driver-based-on-a-template)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-kmdf-driver-based-on-a-template.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-kmdf-driver-based-on-a-template.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Oops!
Thanks for spotting this, @huhuang03! I've changed the link to point to the latest version of Visual Studio.
Eliot
