### ISSUE TITLE
References to ACPI 5.0 are out of date

### ISSUE THREAD

**Issue by rgough71** [MicrosoftDocs/windows-driver-docs#2299]
This article should be updated to reference sections in the current version of the ACPI spec (6.3), or the next version, when available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56616c2f-4bea-de5c-323a-94b87dbd71f7
* Version Independent ID: b602f633-58e1-7b17-390a-f5e4e7851826
* Content: [Summary of ACPI support in Windows - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/summary-of-acpi-support-in-windows)
* Content Source: [windows-driver-docs-pr/bringup/summary-of-acpi-support-in-windows.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/summary-of-acpi-support-in-windows.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team with your comments about the ACPI specification references. 

Currently, version 5.0 of the Microsoft ACPI source language (ASL) compiler supports the features in the Advanced Configuration and Power Interface Specification, Revision 5.0 (ACPI 5.0 specification).  

You can check the version in your WDK installation at the following location with this command:

```
C:\Program Files (x86)\Windows Kits\10\Tools\x86\ACPIVerify>asl.exe /?
```

The first three lines of the command output should return the supported ACPI specification, for example:

```
Microsoft ACPI Source Language Assembler Version 5.0.0NT
Copyright (c) 1996,2014 Microsoft Corporation
Compliant with the ACPI 5.0 Specification
```
