### ISSUE TITLE
Missing Troubleshooting Documentation on 0x515e4

### ISSUE THREAD

**Issue by iHeartWaffles** [MicrosoftDocs/windows-driver-docs#2304]
MEMORY_MANAGEMENT (1a)
    # Any other values for parameter 1 must be individually examined.
Arguments:
Arg1: 00000000000515e4, The subtype of the bugcheck.
Arg2: ffffa5800cc65610
Arg3: ffffffffc0000005
Arg4: 0000000000000000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de955911-dfbf-33b3-778a-767a5a578a0d
* Version Independent ID: 23fb5cbd-5f7d-f7ca-1622-5885020966c2
* Content: [Bug Check 0x1A MEMORY_MANAGEMENT - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x1a--memory-management)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@iHeartWaffles - Thanks for passing on what you are seeing with the bug check 0x1A. We use input like this and other data to determine where to direct our limited doc resources. I have added this mentioned sub code to and internal work item to investigate  if this is something we can add to the docs. Good luck in resolving the issue you ran into.
