### ISSUE TITLE
Driver testing support in Visual Studio 2019 missing documentation

### ISSUE THREAD

**Issue by DepthDeluxe** [MicrosoftDocs/windows-driver-docs#2313]
This article provides useful instructions for old versions of Visual Studio.  It is really unclear how to test drivers in Visual Studio 2019, especially since the new Windows Driver Kit VS Extension doesn't include driver test templates.

How are we able to add new driver tests in "Driver Test Group Explorer"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9c14aa-06ab-bacb-7b10-ff184858d1d1
* Version Independent ID: 0cb2cc28-6e79-1732-722d-b903a82e2046
* Content: [How to write a driver test using a Driver Test template - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/how-to-write-a-driver-test-)
* Content Source: [windows-driver-docs-pr/develop/how-to-write-a-driver-test-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/how-to-write-a-driver-test-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @DepthDeluxe 

I appreciate the question.  Currently we have no supported feature for writing driver tests with VS 2019.  As it sounds like you saw, the article you were looking at only applies to VS 2013.  Sorry I couldn't be of more help!
