### ISSUE TITLE
Link in local help points to online resource while local documentation available

### ISSUE THREAD

**Issue by PisarevSergey** [MicrosoftDocs/windows-driver-docs#2315]
Link in Help Viewer for Visual Studio 2019 leads to msdn site and not to local help.

<img width="1727" alt="1" src="https://user-images.githubusercontent.com/11599134/84200415-6e9cf400-aaaf-11ea-8508-19652da4bfad.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22c52276-e038-f039-f545-14904bb354f0
* Version Independent ID: 2c2afbdc-85d6-d396-ed3c-a9ae0a638ca7
* Content: [Creating the Filter Device Object - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/creating-the-filter-device-object)
* Content Source: [windows-driver-docs-pr/ifs/creating-the-filter-device-object.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/creating-the-filter-device-object.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@PisarevSergey , apologies again that we don't currently have a way to cross-link between different books (conceptual to reference and vice versa). Hopefully our engineering team will role out a solution in the not too distant future!
