### ISSUE TITLE
DP WLK - Hot-replace - Device Test - Verify driver support for d3 power state

### ISSUE THREAD

**Issue by UrosDakskobler** [MicrosoftDocs/windows-driver-docs#2318]
Hi,

After latest windows updates (10.6.2020) on Windows 2012, "DP WLK - Hot-replace - Device Test - Verify driver support for d3 power state" test stucks.
Windows 2012 machine doesn`t respond any more and needs to be restarted.
Updates before were done in first half of March.

Anyone experience the same problems?

**Comment by EliotSeattle** [comment]
Hi @UrosDakskobler 

Thanks for reaching out to our team. This particular channel is monitored by the men and women who write the  driver *documentation* posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to help you with coding questions. 
 
Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is the MSDN Windows Hardware WDK and Driver Development forum: [https://social.msdn.microsoft.com/Forums/windowshardware/](https://social.msdn.microsoft.com/Forums/windowshardware/).

The other is the NTDEV forum from OSR Online: [https://community.osr.com/](https://community.osr.com/).
 
You can post your question in those locations, and the community of developers usually give feedback fairly quickly.
 
Again, thanks for reaching out. Best of luck with this issue.
Eliot
