### ISSUE TITLE
Include Visual Studio Build Configuration Setup Instructions

### ISSUE THREAD

**Issue by DepthDeluxe** [MicrosoftDocs/windows-driver-docs#2319]
In addition to adding the include directory, it looks like you need to include `C:\Program Files (x86)\Windows Kits\10\Testing\Development\lib\x64` in the linker folder configuration.

It would be good to cover high-level setup instructions for C++ tests in this document as it is unclear if other steps are necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19dbeee9-fda6-b1bf-6973-7f07d3b69b0e
* Version Independent ID: 3e5b4cd6-c034-33a0-13dd-bff67840f24f
* Content: [Authoring Tests in C++ - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/taef/authoring-tests-in-c--)
* Content Source: [windows-driver-docs-pr/taef/authoring-tests-in-c--.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/taef/authoring-tests-in-c--.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by tedhudek** [comment]
Hi @DepthDeluxe thanks for the feedback and apologies for the delay getting back to you.

Would you be interested in opening a PR with your proposed change?  Just go to https://docs.microsoft.com/en-us/windows-hardware/drivers/taef/authoring-tests-in-c-- and click the **Edit** button in the upper right.

I took a quick look but I'm not an expert in TAEF.

**Comment by tedhudek** [comment]
Closing out for now but if you get a chance we'd love a PR.  Thanks again for reaching out!
