### ISSUE TITLE
Where is tc.exe installed?

### ISSUE THREAD

**Issue by DepthDeluxe** [MicrosoftDocs/windows-driver-docs#2320]
This article doesn't explain where to find `tc.exe`.  What VC package do you need to have installed to include tc.exe and where is the binary path at to run from the command line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9be943-ed18-8583-ff54-288b4e4dd908
* Version Independent ID: 3b8dada1-bdff-3981-2b97-40a751a6e978
* Content: [Overview of Executing Tests - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/taef/overview-of-executing-tests)
* Content Source: [windows-driver-docs-pr/taef/overview-of-executing-tests.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/taef/overview-of-executing-tests.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Added the path info to the topic page.

Thanks, @DepthDeluxe for both the issue and the solution!

Eliot
