### ISSUE TITLE
More than one VirtualSerial COM-ports installed -> driver reponse on wrong COM port

### ISSUE THREAD

**Issue by codeDevel-2020** [MicrosoftDocs/windows-driver-docs#2324]
I use the "Virtual Serial" driver example as base project for my own driver.
https://docs.microsoft.com/en-us/samples/microsoft/windows-driver-samples/virtual-serial-driver-sample/

The driver itsself has been adapeted with a TCP-Socket-Connection (Client). The driver acts as "COM to TCP Adapter.

I install more than one driver (in this case two):
![DeviceManager-VirtualSerial](https://user-images.githubusercontent.com/66767751/84351899-9168fe80-abbc-11ea-8005-0c032854fe96.PNG)

When I connect with a Serial-Tool (RealTerm) to the COM-Ports (24 and 25) an request some data from the driver, the response from the driver is visualized in the wrong terminal.

It's seems that this problem only occur on Windows10 (I currently use Version 1803).
We use this driver on Windows7, Windows8 without any problems.

Are there any known issues concering this problem?
What can cause this behaviour?

Are there any improvements done in the sample project "Virtual serial driver sample 2"?
https://docs.microsoft.com/en-us/samples/microsoft/windows-driver-samples/virtual-serial-driver-sample-v2/

Thanks!

**Comment by DOMARS** [comment]
@codeDevel-2020 - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
This feedback mechanism is for requests about the documentation. 

My understanding is that the serial driver sample code has been pretty stable as this is fairly mature technology. Good luck with your serial port work.
