### ISSUE TITLE
0x80073cf3 UWP Kiosk app won't run

### ISSUE THREAD

**Issue by myokeeh** [MicrosoftDocs/windows-driver-docs#2325]
Can we have a page for the errors that may occur with this kiosk feature?

In particular, I have a UWP app that I've assigned for a kiosk, however it doesn't start and gives me error code 0x80073cf3.

The UWP app needs "File system" app permission enabled. In a normal Administrator account, when the app is first run, it brings up the "App permissions" settings page to allow the user to enable file system access. Next time it is run, it runs normally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82735562-385b-1ac5-b0a5-1caa2b400d87
* Version Independent ID: dafdf1b8-d884-2074-7d25-ad387bcf7850
* Content: [Kiosk apps for assigned access Best practices - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/partnerapps/create-a-kiosk-app-for-assigned-access)
* Content Source: [windows-driver-docs-pr/partnerapps/create-a-kiosk-app-for-assigned-access.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/partnerapps/create-a-kiosk-app-for-assigned-access.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by tedhudek** [comment]
Hi @myokeeh, thanks for the feedback and apologies for the delay.  Have you checked the manifest to make sure the app is requesting the correct permission?   You could also try this page -- https://docs.microsoft.com/en-us/windows/configuration/kiosk-troubleshoot
