### ISSUE TITLE
Copy-paste mistake in documentation that tries to help you avoiding copy-paste mistakes

### ISSUE THREAD

**Issue by ColinFinck** [MicrosoftDocs/windows-driver-docs#2329]
The page precisely describes how to modify the INF file in order to not make any copy-paste mistakes. However, it looks like a copy-paste mistake slipped in :)

An excerpt from the "Before" file:
```
[ECHO_Device_CoInstaller_AddReg]
[ECHO_Device_CoInstaller_CopyFiles]
[ECHO_Device.NT.Wdf]
```

... and the "After" file:
```
[MyDevice_CoInstaller_AddReg]
[MyDevice_CoInstaller_CopyFiles]
[MyDevice_Device.NT.Wdf]
```

Looks like the last section after modification should rather be called `[MyDevice.NT.Wdf]`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25cc35e8-045f-b920-a6b1-400d1169b28b
* Version Independent ID: 83008dd8-bcd8-3fe8-4891-de3797800c61
* Content: [Specifying the KMDF Co-installer in an INF File - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/installing-the-framework-s-co-installer)
* Content Source: [windows-driver-docs-pr/wdf/installing-the-framework-s-co-installer.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/installing-the-framework-s-co-installer.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @ColinFinck
