### ISSUE TITLE
lost link

### ISSUE THREAD

**Issue by mrmsbarnes** [MicrosoftDocs/windows-driver-docs#2333]
first paragraph on page, first link https://docs.microsoft.com/en-us/windows/desktop/api/mmreg/ns-mmreg-twaveformatex is not found.

page is https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/wave-and-directsound-components.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdfa300c-011a-75dc-2a8a-8d896f794f30
* Version Independent ID: 11d4fdcf-43a2-853d-e9c3-a8f8234f51f5
* Content: [Wave and DirectSound Components - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/wave-and-directsound-components)
* Content Source: [windows-driver-docs-pr/audio/wave-and-directsound-components.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/wave-and-directsound-components.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by RAJU2529** [comment]
@DOMARS , Issue is conformed by me also, after checking the link.

**Comment by EliotSeattle** [comment]
Fixed in PR #2334.
