### ISSUE TITLE
The `/u` option is missing from the documentation for the WinDBG .dump command

### ISSUE THREAD

**Issue by cshung** [MicrosoftDocs/windows-driver-docs#2339]
The `/u` option is missing from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61da6e87-3208-df3d-58f5-73a6a1d49be7
* Version Independent ID: 7bf9a169-76d8-aa0a-f019-42983af0d42d
* Content: [.dump (Create Dump File) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-dump--create-dump-file-)
* Content Source: [windows-driver-docs-pr/debugger/-dump--create-dump-file-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-dump--create-dump-file-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@cshung - Yes the /u option was missing as well as a few other things. The .dump topic should be up to date now. Thanks for filing this git issue.
