### ISSUE TITLE
Incorrect handler name in docs: "SynchronousOidRequestHandlerComplete"

### ISSUE THREAD

**Issue by dmiller-nmap** [MicrosoftDocs/windows-driver-docs#2340]
[`Ndis.h` documentation for `NDIS_FILTER_DRIVER_CHARACTERISTICS` structure](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/ns-ndis-_ndis_filter_driver_characteristics) contains this sentence:

> Added the SynchronousOidRequestHandler and SynchronousOidRequestHandlerComplete members for NDIS 6.80.

But the structure above shows the name is `SynchronousOidRequestCompleteHandler` instead.

**Comment by aviviano** [comment]
Thanks very much for letting us know about this issue @dmiller-nmap. The fix is up now.
