### ISSUE TITLE
Network_Camera GUID

### ISSUE THREAD

**Issue by SMailman** [MicrosoftDocs/windows-driver-docs#2344]
The GUID for Network_Camera is invalid. Appears to be missing a character from last grouping of characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5122881-e5b4-69e5-3ea9-4d89baf6d014
* Version Independent ID: e0547f0c-ec2e-2b88-9792-f01e3884bb23
* Content: [KSCATEGORY_NETWORK_CAMERA - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/kscategory-network-camera)
* Content Source: [windows-driver-docs-pr/install/kscategory-network-camera.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/kscategory-network-camera.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the report @SMailman, I've just pushed a fix.  There was a missing 9 at the end.

**Comment by SMailman** [comment]
Thank you.
