### ISSUE TITLE
Thread waits for semaphore be set to signaled state, NOT to be set to non signaled state.

### ISSUE THREAD

**Issue by samalexander620** [MicrosoftDocs/windows-driver-docs#2346]
[Enter feedback here]
>>>>>When this semaphore is set to the Signaled state, a single thread waiting for the semaphore to be reset to the Not->>>>>Signaled state becomes eligible for execution
Modification: Thread is waiting for the semaphore to be set to the Signaled state become eligible for execution.
Reason: Thread waits for semaphore be set to signaled state, NOT to be set to non signaled state.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ead1f82-a442-2853-6aca-25f04e2bbee8
* Version Independent ID: 9a4a93ff-fe07-78d3-81c5-2f06d18bd68a
* Content: [Semaphore Objects - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/semaphore-objects)
* Content Source: [windows-driver-docs-pr/kernel/semaphore-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/semaphore-objects.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Many thanks @samalexander620 

Right you are.  I just pushed the fix, should be live in a few minutes.

If you like, next time, note that you can open a pull request by clicking Edit on the docs page (upper-right).

We appreciate your sharp eye!
