### ISSUE TITLE
'M' emoji showing in some descriptions

### ISSUE THREAD

**Issue by djmitchella** [MicrosoftDocs/windows-driver-docs#2353]
In the 'Description' column for `%!delta!`, `%!WAITTIME!`, and `%!due!`, it says:

    It is a LONGLONG value that is displayed in day~hⓂ️s format.

The Ⓜ️ should just be a normal "m", I think what's happening is that the original text contains `day~h:m:s` and the `:m:` is being automatically turned into that emoji.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0872087-ae89-e1ef-9868-20d25431b1e8
* Version Independent ID: c19ff217-5900-43a0-98fa-0ef9f8a30163
* Content: [What are the WPP extended format specification strings - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/what-are-the-wpp-extended-format-specification-strings-)
* Content Source: [windows-driver-docs-pr/devtest/what-are-the-wpp-extended-format-specification-strings-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/what-are-the-wpp-extended-format-specification-strings-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @djmitchella 
That is definitely the weirdest doc bug I've seen today!
Appreciate you pointing this out. All fixed and verified in the live branch.
Cheers,
Eliot
