### ISSUE TITLE
Virtual printers use hardware IDs

### ISSUE THREAD

**Issue by tmontney** [MicrosoftDocs/windows-driver-docs#2354]
Microsoft virtual printer drivers do not seem to conform. Examples below of what I've found by running `Get-PrinterDriver | Select-Object Name, HardwareID`:
- {GUID}
- microsoftmicrosoft_s7d14

Without this, I am unable to distinguish virtual printers from physical ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f22e2f-2f83-a819-ac2a-5cb25207652b
* Version Independent ID: 3d32f7c0-7e08-819c-f957-43891059bd41
* Content: [Virtual Printers in Printer INF Files - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/virtual-printers-in-printer-inf-files)
* Content Source: [windows-driver-docs-pr/print/virtual-printers-in-printer-inf-files.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/virtual-printers-in-printer-inf-files.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@tmontney, thanks for reaching out to the Windows Driver Developer Documentation team. You may have success posting your question about how Microsoft virtual printer drivers use Hardware IDs in the following forums, where other driver developers and Microsoft engineers can be found.

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
