### ISSUE TITLE
A sample of how to search all writable memory would be nice

### ISSUE THREAD

**Issue by Jayronimo** [MicrosoftDocs/windows-driver-docs#2355]
[Enter feedback here]

I fired up windbg to hunt down a leaked 64bit pointer and figured that would be a common enough example that it should be shown. I'm not finding it trivially. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06458e32-ceb9-fd5f-1f4e-ca58a26bcbcf
* Version Independent ID: 70edf55e-9ad2-4511-1665-6b28ced2f311
* Content: [Address and Address Range Syntax - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/address-and-address-range-syntax)
* Content Source: [windows-driver-docs-pr/debugger/address-and-address-range-syntax.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/address-and-address-range-syntax.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Jayronimo - I agree that working with memory can be complex. As other readers may end up in this topic and wonder what there next steps would be as well, I added a new "See also" section to this topic. It points to commands that can be helpful, for example the  [s (Search Memory)](s--search-memory-.md) command. For specific scenarios, the OSR web site can be a good resource. For example this topic provides a walkthrough of searching memory: https://www.osronline.com/article.cfm%5earticle=608.htm
Good luck in your work with the debugger.
