### ISSUE TITLE
!pool page is corrupted

### ISSUE THREAD

**Issue by nitoyon** [MicrosoftDocs/windows-driver-docs#236]
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-pool

YAML Front matter is not parsed.

![image](https://user-images.githubusercontent.com/39562/30774610-4dac3ab8-a0c0-11e7-89e6-0f9a80c889bb.png)

**Comment by tedhudek** [comment]
Thanks again, @nitoyon, for your eagle eye.  This is fixed, and we have identified ~10 other instances of this problem that will be fixed soon.

**Comment by nitoyon** [comment]
Thank you for the quick fix!
