### ISSUE TITLE
Screenshot is  better 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#2361]
I like to add screenshots of system firmware updated with related registry key path. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d644fa9d-d986-55d1-b9e7-cba9020b5553
* Version Independent ID: 342bd7c0-9e7a-5d5a-6f1e-50ba7a5d968f
* Content: [ESRT table definition - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/esrt-table-definition)
* Content Source: [windows-driver-docs-pr/bringup/esrt-table-definition.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/esrt-table-definition.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by RAJU2529** [comment]
here are the screenshots.
![devicemanagersystemfirmware1](https://user-images.githubusercontent.com/3296790/87345066-1d2fcb00-c56d-11ea-99bb-b8a2bf831cbe.PNG)
![devicemanagersystemfirmware2](https://user-images.githubusercontent.com/3296790/87345080-21f47f00-c56d-11ea-90e3-bda7791770ca.PNG)
![hardwareesrt1](https://user-images.githubusercontent.com/3296790/87345092-24ef6f80-c56d-11ea-9612-ce0d7175fe46.PNG)
![hardwareesrt2](https://user-images.githubusercontent.com/3296790/87345096-26209c80-c56d-11ea-827b-957be2f66b4f.PNG)
![Locationfirmware](https://user-images.githubusercontent.com/3296790/87345103-2751c980-c56d-11ea-8061-a168697d43f8.PNG)

**Comment by barrygolden** [comment]
Thanks for submitting these screenshots, @RAJU2529.  However I'm not sure of the context for these and how they would fit into this reference focused topic. These seem to be oriented more towards a walkthrough article and would need additional text explaining each step you are showing in the images. Also, for future reference, screenshots are limited to 1200 pixels in height and width.
