### ISSUE TITLE
Unclear buffer information on Method Direct

### ISSUE THREAD

**Issue by hjarmstrong** [MicrosoftDocs/windows-driver-docs#2366]
In this paragraph:

BEGIN

METHOD_IN_DIRECT or METHOD_OUT_DIRECT
For these transfer types, IRPs supply a pointer to a buffer at Irp->AssociatedIrp.SystemBuffer. 

This represents the input buffer that is specified in calls to 

DeviceIoControl and IoBuildDeviceIoControlRequest. The buffer size is specified by Parameters.DeviceIoControl.InputBufferLength in the driver's IO_STACK_LOCATION structure.

END

the line in the middle(linbreaks added for readability) seems to imply that the SystemBuffer is always an input buffer, rather than being an output buffer when METHOD_IN_DIRECT is selected.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b8bfd5a-3ee5-e6c3-c77a-e80a20368690
* Version Independent ID: 1c7efd79-13fe-a5a1-49c9-30554d84d7ad
* Content: [Buffer Descriptions for I/O Control Codes - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/buffer-descriptions-for-i-o-control-codes)
* Content Source: [windows-driver-docs-pr/kernel/buffer-descriptions-for-i-o-control-codes.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/buffer-descriptions-for-i-o-control-codes.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks, just pushed an update!
