### ISSUE TITLE
infverif.exe does not work (WDK_10.0.14393.795)

### ISSUE THREAD

**Issue by mbussjaeg** [MicrosoftDocs/windows-driver-docs#2370]
Hi, 

I need to use infverif.exe for windows 10, but there's no way that I get other output than the help.
Also copying all files together and using it according to your example 
`infverif.exe /w test1.inf test2.inf`
does not show another output.
It seems to me this tool is currently broken or the documentation is completely wrong.

Can you please check this and clarify?

Thanks,
Matthias

**Comment by EliotSeattle** [comment]
Hi @mbussjaeg 

Thanks for the feedback. I believe that the information contained in [Running InfVerif from the command line](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/running-infverif-from-the-command-line) is correct. We haven't heard anything about malfunctions from other customers. If you continue to experience issues, please let me know what specific documentation you find in error. Alternatively, you may have success posting your question in the following forums, where other driver developers and Microsoft  engineers can be found. The communities there are quite responsive.

[Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/)

[OSR NTDEV forum](http://www.osronline.com/cf.cfm?PageURL=showlists.cfm?list=NTDEV)

Again, thanks for reaching out. Best of luck with this issue.

Eliot
