### ISSUE TITLE
Update step-by-step instructions for KMDF Echo Driver Sample

### ISSUE THREAD

**Issue by stryker2k2** [MicrosoftDocs/windows-driver-docs#2371]
In section 4, "Section 4: Install the KMDF echo driver sample on the target system", of the "Debug Windows Drivers - Step by Step Lab (Echo Kernel-Mode)" page found at "https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-" does not specifically state that you need to copy devcon.exe to the target machine; one must read between the lines to extract that info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5abd01e-3c7e-11a8-a6c6-62bfba0ef8b6
* Version Independent ID: dceb81b3-b20f-91d1-85d0-fa68c762482b
* Content: [Debug Windows Drivers - Step-by-Step Lab (Echo Kernel Mode) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-)
* Content Source: [windows-driver-docs-pr/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by tedhudek** [comment]
#2363 claims that provisioning auto-installs devcon now. Need to reconcile these two

**Comment by DOMARS** [comment]
I don't think the echo lab uses auto install provisioning via Visual Studio that hello world does. This topic covers that style of driver deployment. https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/provision-a-target-computer-wdk-8-1

**Comment by DOMARS** [comment]
@stryker2k2 - I updated the topic to better describe copying over the devcon.exe utility over to the target machine. There was some information about this in linked topic, but not a bad idea to include in the lab directions directly. Thanks for pointing this out and good luck in your debugging work.
