### ISSUE TITLE
LNK2005

### ISSUE THREAD

**Issue by judah-b2** [MicrosoftDocs/windows-driver-docs#2373]
Do anybody know how to solve that problem DriverEntry already defined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81568a12-c39e-a18f-8f33-c54545f14bac
* Version Independent ID: 73217b22-1795-b5d0-65cb-1984f38dc661
* Content: [Write a Hello World Windows Driver (KMDF) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-very-small-kmdf--driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-very-small-kmdf--driver.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @judah-b2 

Thanks for reaching out to our team. This particular channel is monitored by the men and women who write the  driver *documentation* posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to help you with your code. 
 
Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is Microsoft Q&A: [https://docs.microsoft.com/answers/products/](https://docs.microsoft.com/answers/products/).

The other is the NTDEV forum from OSR Online: [https://community.osr.com/](https://community.osr.com/).
 
You can post your question in those locations, and the community of developers usually give feedback fairly quickly.
 
Again, thanks for reaching out. Best of luck with this issue.
Eliot
