### ISSUE TITLE
described project properties path for WPP Tracing doesn't match actual (probably changed in VS and doc not updated)

### ISSUE THREAD

**Issue by JHentges** [MicrosoftDocs/windows-driver-docs#2375]
[Enter feedback here]
The text says "click Configuration Properties, and then Wpp." but "Wpp" is (now) "Wpp Tracing"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d308a33a-5f5f-e666-7639-0340e727535a
* Version Independent ID: c1ce0dc6-c59f-3f45-97dd-14d7b5157772
* Content: [Using WPP Software Tracing in KMDF Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/using-wpp-software-tracing-in-kmdf-drivers)
* Content Source: [windows-driver-docs-pr/wdf/using-wpp-software-tracing-in-kmdf-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/using-wpp-software-tracing-in-kmdf-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Just pushed a fix - thanks for the report!
