### ISSUE TITLE
bad links - dead links - 404 errors

### ISSUE THREAD

**Issue by joshieecs** [MicrosoftDocs/windows-driver-docs#2379]
Three links under heading "[In This Section](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/driver-signing.md#in-this-section)" lead to 404 errors.

1. Overview of Digital Signatures for Driver Installation
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/overview-of-digital-signatures-for-driver-installation.md

2. Signing Drivers during Development and Test
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/signing-drivers-during-development-and-test.md

3. Troubleshooting Install and Load Problems with Signed Driver Packages
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/troubleshooting-install-and-load-problems-with-signed-driver-packages.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ca4e93-a34c-abbc-0ebc-9b5195378b20
* Version Independent ID: f2e19c4f-44cf-e0d4-2143-1e2129c582c9
* Content: [Driver Signing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/driver-signing)
* Content Source: [windows-driver-docs-pr/install/driver-signing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/driver-signing.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for spotting these. I just pushed a fix, should be live in a few minutes
