### ISSUE TITLE
Recommend to use code block for the example code

### ISSUE THREAD

**Issue by petercoin** [MicrosoftDocs/windows-driver-docs#2381]
I think it is better to use `code block` to show the example code more clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8870d00-07f2-913b-480c-b765c387451b
* Version Independent ID: 2cecb371-6074-0a36-20a0-a9a5ba6975eb
* Content: [MOF Syntax for WMI Data and Event Blocks - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/mof-syntax-for-wmi-data-and-event-blocks)
* Content Source: [windows-driver-docs-pr/kernel/mof-syntax-for-wmi-data-and-event-blocks.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/mof-syntax-for-wmi-data-and-event-blocks.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @petercoin I just updated the page to use code fencing. The update should be live within a few minutes.

We appreciate the feedback!
