### ISSUE TITLE
Should have bias comms warning on documentation

### ISSUE THREAD

**Issue by GossiTheDog** [MicrosoftDocs/windows-driver-docs#2382]
Example:
https://docs.microsoft.com/en-us/azure/databricks/administration-guide/clusters/policies

Important

Bias-free communication
Microsoft supports a diverse and inclusionary environment. This article contains references to the word blacklist. The Microsoft style guide for bias-free communication recognizes this as an exclusionary word. The word is used in this article for consistency because it’s currently the word that appears in the software. When the software is updated to remove the word, this article will be updated to be in alignment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 199a05b2-82c8-ea4f-962a-f3c8e14d4703
* Version Independent ID: 6878502f-e58d-789d-5317-2f6b5332a548
* Content: [MB Network Blacklist Operations - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/mb-network-blacklist-operations#feedback)
* Content Source: [windows-driver-docs-pr/network/mb-network-blacklist-operations.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/mb-network-blacklist-operations.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks so much @GossiTheDog for opening this issue. We've added a bias warning and the fix is now live. Thanks again.
