### ISSUE TITLE
Description of parameters are wrong.

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/windows-driver-docs#2387]
It seems like to be mixed with other fsctl descriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42afd0e1-e27d-c332-d82f-e7ea401649cf
* Version Independent ID: 17ac0426-8cb9-7691-df22-d907d4c11a4d
* Content: [FSCTL_FILE_LEVEL_TRIM control code - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/fsctl-file-level-trim)
* Content Source: [windows-driver-docs-pr/ifs/fsctl-file-level-trim.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/fsctl-file-level-trim.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@hsebs , thanks again for PR to fix this!
