### ISSUE TITLE
Bad link, 404 error

### ISSUE THREAD

**Issue by julianathan** [MicrosoftDocs/windows-driver-docs#2392]
[Enter feedback here]
Link for "Hardware Dev Center FAQ" is formatted incorrectly and results in 404 error. Current entry is : https://docs.microsoft.com/en-us/windows-hardware/drivers/install/(https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb19d33-8f4c-f379-b645-938a746c5615
* Version Independent ID: 8efb9fb4-1e9a-1a8a-994b-450495449e15
* Content: [Driver Signing Policy - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/kernel-mode-code-signing-policy--windows-vista-and-later-)
* Content Source: [windows-driver-docs-pr/install/kernel-mode-code-signing-policy--windows-vista-and-later-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/kernel-mode-code-signing-policy--windows-vista-and-later-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by EliotSeattle** [comment]
Thanks for pointing this out, @julianathan.
We want all our links working, but we definitely want  the ones going to the Partner Portal enabled. 
This is fixed and merged into the main branch. Should be live shortly.
Eliot
