### ISSUE TITLE
CHID Object DistributionState | Required or Default

### ISSUE THREAD

**Issue by Ben-Carpenter** [MicrosoftDocs/windows-driver-docs#2394]
Recently I migrated code to use the v2 of your API. I noticed that we started getting 422 response errors. I had the distributionState set to 'notSet' thinking this might be a default. After doing some debugging I found if I used 'unknown' I didn't get any errors. Although, 'unknown' is not one of the four options listed in the documentation. https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-shipping-labels#chids-object

Is there a default value when the state is not known? i.e. 'unknown', empty string, or is the property even required?
How does one determine what the actual distributionState of a CHID is so a new label can be created?

It would be nice to see which properties are required or what default values could be in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bc8605-acf7-615b-3821-2f509d2a1e63
* Version Independent ID: 626ad255-cdba-6eb3-9f35-f3f688e343b4
* Content: [Get shipping label data - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-shipping-labels#chids-object)
* Content Source: [windows-driver-docs-pr/dashboard/get-shipping-labels.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-shipping-labels.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by tedhudek** [comment]
Thanks for the feedback and apologies for the delay.  I've just updated https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-shipping-labels#chids-object.
