### ISSUE TITLE
Shipping Label | CurrentStep | Cancel a Shipping Label

### ISSUE THREAD

**Issue by Ben-Carpenter** [MicrosoftDocs/windows-driver-docs#2395]
Using v2 API:
According to the https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/cancel-a-shipping-label.
In order to cancel a shipping label the workflow status object property 'currentStep' must be in Microsoft Approval or Gradual Rollout. However, Gradual Rollout is not listed in the available options for shipping labels that are published to windows update.
Do any of the other options listed map to Gradual Rollout?

For shipping labels that are shared with other partners, what value does the currentStep need to be, in order to cancel a shipping label?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bc8605-acf7-615b-3821-2f509d2a1e63
* Version Independent ID: 626ad255-cdba-6eb3-9f35-f3f688e343b4
* Content: [Get shipping label data - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-shipping-labels#shipping-label-workflow-status-object)
* Content Source: [windows-driver-docs-pr/dashboard/get-shipping-labels.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-shipping-labels.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by tedhudek** [comment]
Again, thanks for the feedback, sorry it took us so long.  I just pushed 6f56144de, and the pages on Docs are now updated.
