### ISSUE TITLE
Remove UsbReadOptions.IgnoreShortPacket from this tutorial's configured readPipe.ReadOptions

### ISSUE THREAD

**Issue by NateVolt** [MicrosoftDocs/windows-driver-docs#2428]
For the love of anyone's sanity, please remove IgnoreShortPacket from this tutorial's configured readPipe.ReadOptions. This causes LoadAsync to block until you receive a number of packets >= readPipe.EndpointDescriptor.MaxPacketSize. I can't even imagine why you would want to ignore messages less than the max transfer size. This cost me about a day of troubleshooting when trying to set up communications with a device.

For context, I am trying to communicate with a USBTMC device. Communicating with a device of this class usually involves very short, < 100 bytes, per command and response. I would never want to ignore a response in this case. Maybe this setting makes sense for some other USB applications. If this setting really needs to stay, please make a comment about how impactful this setting it.

``` csharp
private async void BulkRead()
    {
        UInt32 bytesRead = 0;

        UsbBulkInPipe readPipe = usbDevice.DefaultInterface.BulkInPipes[0];
        readPipe.ReadOptions |= UsbReadOptions.IgnoreShortPacket;

        var stream = readPipe.InputStream;
        DataReader reader = new DataReader(stream);

        try
        {
            bytesRead = await reader.LoadAsync(readPipe.EndpointDescriptor.MaxPacketSize);
        }
        catch (Exception exception)
        {
            ShowStatus(exception.Message.ToString());
        }
        finally
        {
            ShowStatus("Number of bytes: " + bytesRead);

            IBuffer buffer = reader.ReadBuffer(bytesRead);

            ShowData (buffer.ToString());

        }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c11f0477-438f-5b76-784a-ea4284d1c756
* Version Independent ID: 8ddc42c9-a9f8-945b-8e3a-c26d6ea78496
* Content: [How to send a USB bulk transfer request (UWP app) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/how-to-send-a-usb-bulk-transfer--uwp-app-)
* Content Source: [windows-driver-docs-pr/usbcon/how-to-send-a-usb-bulk-transfer--uwp-app-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/how-to-send-a-usb-bulk-transfer--uwp-app-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Thanks for the detailed write-up, @NateVolt, and apologies it took us so long.  I just pushed a fix that adds a code comment above the line in question on that doc page.  Appreciate the assist!
