### ISSUE TITLE
Referring to two different version of Windows 10 SDK

### ISSUE THREAD

**Issue by sindrh** [MicrosoftDocs/windows-driver-docs#2433]
The following line is confusing. It says "search for Windows 10 SDK (10.0.19041.0)" and then "install the Windows 10 SDK (10.0.19041.1)". That is, the number at the end is different. I cannot find the version ending at .1 in my VS2019 installation.

"In Visual Studio Installer, on the Individual components tab, search for Windows 10 SDK (10.0.19041.0), select this version and continue with install.

If you already have Visual Studio 2019 installed, you can install the Windows 10 SDK (10.0.19041.1) by using the Modify button in Visual Studio install."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for this Issue, @sindrh  
After a little research, it looks like everything is correct, but it's better to be overt about what's going on. I added ***this text***:

In Visual Studio Installer, on the Individual components tab, search for Windows 10 SDK (10.0.19041.0), select this version and continue with install. ***Note that Visual Studio will automatically install Windows 10 SDK (10.0.19041.1) on your machine.***

I'm not sure why this is happening, but after several colleagues tested with me, it seems this is the case.

Thanks.
Eliot
