### ISSUE TITLE
Image Color Management - Missing link to userspace docs

### ISSUE THREAD

**Issue by SamB** [MicrosoftDocs/windows-driver-docs#2440]
The page says:

> For a general discussion about Image Color Management, see the Microsoft Windows SDK documentation.

... but there's no link. That was probably less of a problem when the SDK documentation used an offline HTML Help system so you could look it up in the index or something ...

All I can seem to find are:
  * The https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wcs tree
  * https://docs.microsoft.com/en-us/previous-versions//dd372446 (which looks like it should redirect to https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wcs/windows-color-system; it looks like the only difference between these two pages is that one of them uses opaque page IDs and the other uses human-chosen paths, and all the linked pages redirect to the human-chosen paths)

The "previous-versions" bit doesn't really inspire confidence, though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66c3c003-71bd-0d57-91f6-a29718c90560
* Version Independent ID: 74ade7b7-0d53-ac6e-d199-090aa54024ad
* Content: [Image Color Management - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/image-color-management#feedback)
* Content Source: [windows-driver-docs-pr/display/image-color-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/image-color-management.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@SamB , thanks for your issue and apologies for my slow response. I did add a link to the SDK docs. I'm guessing you've figured out by now that this material is for the older XDDM display driver (ICM was used by GDI).
