### ISSUE TITLE
Add additional examples for ignoring user mode breakpoints

### ISSUE THREAD

**Issue by gilp456** [MicrosoftDocs/windows-driver-docs#2441]
Would be great if there were additional practical examples for how to ignore certain conditions when trying to use Windbg.  For example, the page referencing how to use sx commands doesn't really explain what the difference is between bpe vs bpec, or how to even use it.  Additional content for the user in case they want to ignore user mode application breakpoints and focus on BSOD or kernel hangs would be helpful.  Thanks.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3f376d-0425-ba3a-6afc-669604b351b0
* Version Independent ID: 5439ed2b-4eec-6bd1-10f0-277542f06831
* Content: [sx, sxd, sxe, sxi, sxn, sxr, sx- (Set Exceptions) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/sx--sxd--sxe--sxi--sxn--sxr--sx---set-exceptions-)
* Content Source: [windows-driver-docs-pr/debugger/sx--sxd--sxe--sxi--sxn--sxr--sx---set-exceptions-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/sx--sxd--sxe--sxi--sxn--sxr--sx---set-exceptions-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@gilp456 - Thanks for this input. I'm working to  add some additional resources to the topic to provide pointers to the content that may be helpful. 

[Using Breakpoints - Debugging Techniques](using-breakpoints.md)

[Conditional breakpoints in WinDbg](setting-a-conditional-breakpoint.md)

[Executing Until a Specified State is Reached](executing-until-a-specified-state-is-reached.md)

But there is a point for advanced techniques, the external books may contain information that is not in the docs.

*Inside Windows Debugging: Practical Debugging and Tracing Strategies by Tarik Soulami*

*Advanced Windows Debugging by Mario Hewardt and Daniel Pravat*

And the "Defrag Tools" shows on Channel 9.

If there are techniques you have found useful, you can send a docs pull request to pass those on to the community. If you are looking for specific debugging techniques, another resources is the OSR Debugging Forum:  [OSR's windbg List](https://community.osr.com/categories/windbg)

Thanks again for this input, and good luck with your debugging work.
