### ISSUE TITLE
Eltan BV | Altitude MiniFilter Request

### ISSUE THREAD

**Issue by wvervoorn** [MicrosoftDocs/windows-driver-docs#2442]
[Enter feedback here]

Hello,

I am trying to get an altitude allocation made. The first request I sent was in april.

I am sending these requests from my wvervoorn@eltan.com email.

I have also contacted support about this with no results other than the suggesting to issue feedback on this page.

Can you help me out here to get this done.

I added my communication with support:

Hello Wim,

We are not receiving any replies from the alias, I would suggest submitting feedback on the Minifilter Altitude Request doc as the owner of the document generally responds fairly quickly. You can aslo submit feedback via your HDC Dashboard. I understand this is not ideal and I appreciate your understanding.

As this issue is out scope for my team, I will proceed in archiving this service request. Shoud you encounter any future issues, please do not hesitate to contact support. 

Thank You,

Tinishia 
--- Original Message ---
Hi Wim,

I have not received a response from fsfcomm@microsoft.com neither via chat or email, neither has my manager. I will provide an update by this time next week.

Thank You,

Tinishia
--- Original Message ---
Hi Wim,

I have yet to receive a response from fsfcomm@microsoft.com neither via chat or email. I have requested manager asisstance. I will provide an update by this time next week.

Thank You,

Tinishia
--- Original Message ---
Thank Wim, I have reached out to fsfcomm@microsoft.com via chat and email. I will provide any feedback or updates upon receipt.

Thank You,

Tinishia
--- Original Message ---
Hello, 

I added a long screenshot. It contains my first request and a more recent reminder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f62aea8-127c-317f-07d8-6f6d93df7bb1
* Version Independent ID: e85bfe16-3267-7aee-65c8-46c59bae4a6f
* Content: [Minifilter Altitude Request - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/minifilter-altitude-request)
* Content Source: [windows-driver-docs-pr/ifs/minifilter-altitude-request.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/minifilter-altitude-request.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@wvervoorn , thanks for reaching out via GitHub and apologies for the difficulties you've experienced in obtaining an altitude ID. I sent you email with your altitude allocation information, and you might also hear from the fsfcomm alias as well. They processed your request several weeks ago and believe they sent you email, so you might want to make sure that your company spam filter isn't blocking email from Microsoft? Let me know if you need anything else!
