### ISSUE TITLE
Additional Thoughts to Security on INF files

### ISSUE THREAD

**Issue by markem** [MicrosoftDocs/windows-driver-docs#2447]
Microsoft should include something like an MD5 or ShA256 encryption information for the INF file. This encryption information should reside on Microsoft servers and the same mechanism used to register with Microsoft should be sued (in other words - don't trust the system the program is run on - use the backdoor to get the MD5/SHA info so it can be trusted). In this way, all device drivers can be checked periodically to ensure they are right. Incorrect MD5/SHA encryption codes should cause a device to reload the default driver for that device. If, after three tries, the device can not be loaded for unknown reasons - then default to disable the device, display a message dialog, and direct the person to look at the device and/or contact the dealer of the device in order to ask them what the problem is and/or download a new device driver.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6563342-7aa5-3a02-b758-5a53dd7eca39
* Version Independent ID: a54a4ad3-5eaa-c387-cd91-32e76c6af277
* Content: [Driver Store - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/driver-store)
* Content Source: [windows-driver-docs-pr/install/driver-store.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/driver-store.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks, @markem.

Appreciate the feedback. This feedback mechanism is monitored for improvements to the documentation. For bugs and suggestions for features, please use the **Feedback Hub**, which is a part of Windows 10. 

Type `Feedback` in the Windows search box in **Taskbar**, and then select **Feedback Hub**. Follow the instructions in the tool, and submit your idea. The product teams take this input very seriously and monitor the traffic constantly.

Thanks so much!
