### ISSUE TITLE
Unable to add from Store for Business

### ISSUE THREAD

**Issue by jespinoza84** [MicrosoftDocs/windows-driver-docs#2448]
The Store for Business is returning a "We can't find the page you requested"

https://businessstore.microsoft.com/en-us/store/details/windbg-preview/9pgjgd53tn86

**Comment by DOMARS** [comment]
@jespinoza84 - A few questions, so that I can route this request.
Your goal is to make this available only through the business store, so that your orginization can acess it there?

**Comment by jespinoza84** [comment]
Hi @DOMARS - Yes, I was looking to add to our org for techs. When I tried this on Friday, the app was accessible on 'consumer' Microsoft Store but not the business store for our org. Looks like it's working now. Thanks for the quick turnaround.
