### ISSUE TITLE
\_ in title

### ISSUE THREAD

**Issue by nitoyon** [MicrosoftDocs/windows-driver-docs#245]
example: https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/irp-mn-cancel-remove-device

![image](https://user-images.githubusercontent.com/39562/31084650-ec896c4e-a7cf-11e7-8b89-65ad48cd4725.png)

Over 500 pages have this problem. 

```sh
> git grep -G "title:.*\\_"
windows-driver-docs-pr/kernel/irp-mj-cleanup.md:title: IRP\_MJ\_CLEANUP
windows-driver-docs-pr/kernel/irp-mj-close.md:title: IRP\_MJ\_CLOSE
windows-driver-docs-pr/kernel/irp-mj-create.md:title: IRP\_MJ\_CREATE
windows-driver-docs-pr/kernel/irp-mj-device-control.md:title: IRP\_MJ\_DEVICE\_CONTROL
   :
> git grep -G "title:.*\\_" | wc -l
589
```

**Comment by tedhudek** [comment]
Thank you again @nitoyon this should be fixed now!

**Comment by nitoyon** [comment]
thx! 😄
