### ISSUE TITLE
Web search for this KSPROPERTY_AUDIO_CPURESOURCES unsuccessful due to backslashes

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2454]
Google-searching for the literal string **KSPROPERTY_AUDIO_CPURESOURCES** yields only three instances from source code in github.

The reason appears to be backslashes before the underscores in this page, e.g. `KSPROPERTY\_AUDIO\_CPU\_RESOURCES - Windows ...`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b516ab12-1b77-4195-bf1c-22d30c930297
* Version Independent ID: 4bfd04a6-faba-c458-ddbb-c080dc91b23e
* Content: [KSPROPERTY\_AUDIO\_CPU\_RESOURCES - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/ksproperty-audio-cpu-resources)
* Content Source: [windows-driver-docs-pr/audio/ksproperty-audio-cpu-resources.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/ksproperty-audio-cpu-resources.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - Thanks for this input. It appears to be a by product of the topics using markdown. I hope over time, more search engines become aware of this type of escaping in API names. And of course Google is very popular, but a few other options to consider. Bing returns this topic, and you can use the "Filter by title" on the left TOC. This is of course assuming you know to look in the driver audio content to start with.  Most users use Google to find our content, so I will pass this input on to our search discoverability people. Thanks for the input and good luck with your audio driver WDM work.
