### ISSUE TITLE
Dead link in Using a Universal INF File section

### ISSUE THREAD

**Issue by luisalves05** [MicrosoftDocs/windows-driver-docs#2455]
In the section "[Using a Universal INF File](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-a-universal-inf-file#which-inf-sections-are-invalid-in-a-universal-inf-file)" the link to "[INF Syntax](
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-file-sections-and-directives.md)" is broken (404), I think the reason is because the docs have two section now, one for "Sections" and other for "Directives".

**Comment by RAJU2529** [comment]
@PRMerger6 I am creating PR now.

**Comment by RAJU2529** [comment]
@PRMerger6, verify and merge pr #2465.

**Comment by EliotSeattle** [comment]
Fixed and merged
