### ISSUE TITLE
no indication about other parameters 

### ISSUE THREAD

**Issue by grandriz** [MicrosoftDocs/windows-driver-docs#2459]
Hi, 

Just had a BSOD with a 7F error. I looked at your doc and couldn't find what the second, third and forth parameters meant. Could  you fix that or tell me what it is ? 

I do think that the 2 and 4 are serial numbers or something like that but I don't know 

Regards, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ab369b7-1a0e-e2f8-9d9b-d4bc3710ca57
* Version Independent ID: eac532fd-fece-247e-8b12-7cc6b6a3906e
* Content: [Bug Check 0x7F UNEXPECTED_KERNEL_MODE_TRAP - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x7f--unexpected-kernel-mode-trap)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x7f--unexpected-kernel-mode-trap.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x7f--unexpected-kernel-mode-trap.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@grandriz - Thanks for this request. I have filed a work item to see if we can provide more information on the parameters that are returned by UNEXPECTED_KERNEL_MODE_TRAP. It will be different for 32/64 bit processors, but typically the contents of register values are returned. The register command describes the registers - https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/r--registers-. The registers hold values that control the flow of code execution on the processor. They can be used with the source code to investigate the cause of the failure.  Good luck with resolving the issue you encountered, and thanks for providing feedback on the stop code docs.
