### ISSUE TITLE
The Windows 10 SDK (10.0.19041.0) Install notice is missing

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/windows-driver-docs#2460]
To install WDK version 2004, it is needed to install Windows 10 SDK (10.0.19041.0) from https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/ before WDK separately.

The manual installation is mandatory needed but it is not described clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @ahidaka 
Thanks for reaching out to us. In the instructions for installing Visual Studio, we say:

"In **Visual Studio Installer**, on the **Individual components** tab, search for Windows 10 SDK (10.0.19041.0), select this version and continue with install. Note that Visual Studio will automatically install Windows 10 SDK (10.0.19041.1) on your machine.

If you already have Visual Studio 2019 installed, you can install the **Windows 10 SDK (10.0.19041.1)** by using the Modify button in Visual Studio install."

Is there something else that you feel would make that more clear?
Thanks so much,
Eliot
