### ISSUE TITLE
Missing 0x10

### ISSUE THREAD

**Issue by scotepi** [MicrosoftDocs/windows-driver-docs#2463]
Parameter 1, 0x10 is missing from the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45b35e68-8c01-c14f-40b2-0eef5412b402
* Version Independent ID: 141f44a5-d816-60be-18c9-710aad6b1cbb
* Content: [Bug Check 0x124 WHEA_UNCORRECTABLE_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x124---whea-uncorrectable-error)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x124---whea-uncorrectable-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x124---whea-uncorrectable-error.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@scotepi - Thanks for this issue. We use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, it is likely that we will only be able to do the work to create and validate a universal description for a small sub set of all of the possible stop codes and their associate parameters. In my experience for the 0x10 sub code for the  WHEA_UNCORRECTABLE_ERROR stop code, it does not appear to be one that occurs frequently. Thank you for your interest in improving our stop code docs and good luck with issue that you encountered.
