### ISSUE TITLE
Link to SDEL Language is broken

### ISSUE THREAD

**Issue by rahul-ramadas** [MicrosoftDocs/windows-driver-docs#2471]
The link to SDEL Language in "Configuring the SDEL query" section is broken. Perhaps it should go here: https://docs.microsoft.com/en-us/windows-hardware/drivers/wdtf/simple-data-evaluation-language-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8475c3b-1a33-76c6-fbb2-c3d05214c830
* Version Independent ID: 1beb2abd-f4bb-41eb-da63-a810cb94cfcd
* Content: [Run the tests - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/run-the-tests)
* Content Source: [windows-driver-docs-pr/devtest/run-the-tests.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/run-the-tests.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks for bringing this to my attention, @rahul-ramadas.
That link is the perfect one. I've made the fix and checked it into our main branch. Should be live shortly.
Appreciate the help.
Eliot
