### ISSUE TITLE
DigiCert is Symantec

### ISSUE THREAD

**Issue by Albert-Straub-CardinalPeak** [MicrosoftDocs/windows-driver-docs#2474]
The page lists Symantec as a source for the certs.  That being said, when you go there and click to open an account it sends you to DigiCert.  Apparently, after a Bing search, DigiCert bought Symantec's certificate business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d3f097-d81b-66c2-4835-d63758687d34
* Version Independent ID: fe9d1cdd-966e-89b5-c66b-60531b0ec655
* Content: [Get a code signing certificate - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate)
* Content Source: [windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks for pointing this out, @Albert-Straub-CardinalPeak 
I fixed the link and updated the instructions to match Symantec's actual site.
Pushed into our Main branch and should be live soon.
Eliot
