### ISSUE TITLE
Missing {d94ee5d8-d189-4994-83d2-f68d7d41b0e6} (SecurityDevices class)

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/windows-driver-docs#2484]
This page seems to be missing {d94ee5d8-d189-4994-83d2-f68d7d41b0e6}, which is the SecurityDevices device class. On all the devices that I have checked, this is the class for Trusted Platform Modules (TPMs).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c231a8b4-24a8-c339-8660-52a2b9d28226
* Version Independent ID: 093b0d00-46ae-b685-760c-c04e10b27595
* Content: [Class and ClassGuid entries for INF Version Section - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/system-defined-device-setup-classes-available-to-vendors)
* Content Source: [windows-driver-docs-pr/install/system-defined-device-setup-classes-available-to-vendors.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/system-defined-device-setup-classes-available-to-vendors.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by RAJU2529** [comment]
@franklesniak.  Thanks for pointing out. I am trying to fixing now

**Comment by RAJU2529** [comment]
@tedhudek , i will  create  more PR in the coming week, for this purpose, I am collecting information through windows 10 registry keys.

**Comment by tedhudek** [comment]
Fixed in #2485.  Thanks for the report.
