### ISSUE TITLE
All 3 links on page are broken and produce 404 not found

### ISSUE THREAD

**Issue by exedor** [MicrosoftDocs/windows-driver-docs#2486]
All the links on the page, specifically the following:
"OEMForceFeedback Registry Settings"
"Driver Interface"
"User-Mode Functions"

produce a 404 Not Found page when followed/clicked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7231b7cd-29bb-6501-c0ca-acdd5c9d4a70
* Version Independent ID: fdbbf990-6adc-9b66-3714-c2173f8b13f9
* Content: [Force Feedback Device Driver Interface - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/force-feedback-device-driver-interface)
* Content Source: [windows-driver-docs-pr/hid/force-feedback-device-driver-interface.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/force-feedback-device-driver-interface.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by EliotSeattle** [comment]
Dropped in migration.

**Comment by exedor** [comment]
Not sure how to interpret that. It contains extremely little info. Was that intentional? If so, you should probably remove the links. Was it not intentional, i.e. accidentally dropped in migration? Will they be restored and corrected?

**Comment by billlattimer** [comment]
@exedor that was a comment to me as the topic owner regarding the source of the missing docs; I'll be making this a priority over the next few days to restore.

**Comment by exedor** [comment]
Ahh, much appreciated. Thank you!

**Comment by billlattimer** [comment]
@exedor thanks again for calling this out - the content that was in the linked articles was moved into the main article and is now available. 

https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/force-feedback-device-driver-interface

**Comment by cyberluke** [comment]
Lol guys half of internet reference that URL. At least learn to code website and provide HTTP 302 redirect, damn!
