### ISSUE TITLE
The "Using the Registry in a Driver" link is 404

### ISSUE THREAD

**Issue by rhymu8354** [MicrosoftDocs/windows-driver-docs#2488]
The "Using the Registry in a Driver" link (https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/using-the-registry-in-a-driver) at the bottom of this page is broken (404 Not Found).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 723a0e7d-fbea-f79c-38b4-d6d6f5dd3265
* Version Independent ID: db8ebd12-22bc-67e7-8204-dd07361abb61
* Content: [Introduction to Registry Keys for Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/introduction-to-registry-keys-for-drivers)
* Content Source: [windows-driver-docs-pr/wdf/introduction-to-registry-keys-for-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/introduction-to-registry-keys-for-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
The fix for the Zw* page cover this too, thanks again!
