### ISSUE TITLE
Escaping of % is not explained.

### ISSUE THREAD

**Issue by markovandooren** [MicrosoftDocs/windows-driver-docs#2489]
If you need to use a % sign in the variables you can use %% to escape it. That is not explained in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6e0df1-4638-9133-3315-23352641b625
* Version Independent ID: 314c937e-aad2-90c0-4eef-5bb557c7c8e3
* Content: [Language Specification 1 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/language-specification-1)
* Content Source: [windows-driver-docs-pr/debugger/language-specification-1.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/language-specification-1.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@markovandooren - Thanks for providing this input. I could imagine a usage scenario where the parsing engines could require a %%. And of course other options, for example setting the scrpath on the command line may not. I think the topic intent here is to provide a general overview of SrcSrv. For a simpler example of setting the srcpath for the sample echo driver, that is covered in [Debug Windows Drivers - Step by Step Lab (Echo Kernel-Mode)](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-). In that scenario, there are no spaces, so you can set it like this: `.srcpath+ C:\DriverSamples\KMDF_Echo_Sample\driver\AutoSync`. I know in some PowerShell scenarios  you need to use (non angled) double quotes to enclose the path.  But thanks for this input, I will consider adding more information to address various automation scripting and more complex use of these commands in the future.
