### ISSUE TITLE
Small error ?

### ISSUE THREAD

**Issue by sagoswa** [MicrosoftDocs/windows-driver-docs#2492]
[Enter feedback here]
Hi,

I was going through this page and just noticed the below lines. Should not the field names be used in opposite way ?

TraceLoggingFileTime(ft, "Current Time (SYSTEMTIME)"), // Should be Current Time (FILETIME) ??
TraceLoggingSystemTime(st, "Current Time (FILETIME)"),  // Should be Current Time (SYSTEMTIME) ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43bd2be3-d344-5125-af89-c8d92920af97
* Version Independent ID: fcc2e952-1ac6-797c-b0b5-874cd55abb35
* Content: [TraceLogging Examples - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/tracelogging-examples)
* Content Source: [windows-driver-docs-pr/devtest/tracelogging-examples.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/tracelogging-examples.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks, @sagoswa!
I believe that you are spot on!! I've made that change and pushed the updated topic to the main branch. It should be live shortly.
Appreciate the PR.
Eliot
