### ISSUE TITLE
PFA for Memory

### ISSUE THREAD

**Issue by philc43** [MicrosoftDocs/windows-driver-docs#2495]
This document makes it clear that the badmemory entries relate to ECC memory.  However, I am very often seeing these entries created for non-ECC memory.  What does this mean - it is an error or a genuine indication that memory regions are being excluded.  Why pay for ECC memory if this works?

Thanks for any help you can provide on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8e6339-454d-e83e-f336-77ca95eb8d09
* Version Independent ID: 61effe15-9990-c238-5edc-8c25e889566c
* Content: [Persistence of PFA Results - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/whea/persistence-of-pfa-results)
* Content Source: [windows-driver-docs-pr/whea/persistence-of-pfa-results.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/whea/persistence-of-pfa-results.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by tedhudek** [comment]
Best guess is that errors are occurring in cache, which Windows will treat as a memory error.  This could lead to PFA, but it’s still obviously weaker than ECC since you have no on DIMM error correction.

I don't see a doc impact here, so I'm going to close this out.  Hope this helps!
