### ISSUE TITLE
How to add user-defined papersize into xps printer

### ISSUE THREAD

**Issue by XiaoPengProsper** [MicrosoftDocs/windows-driver-docs#2503]
[Enter feedback here]

I want to add a papersize named 'ABC', 50mm x 50mm. Anyone knows how to make it?
Thanks a lot.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13fb4fd5-4e3e-14a4-e48f-caf8312bdf19
* Version Independent ID: c5283e76-911d-255c-872b-1768c33ff707
* Content: [Option Attributes for the PaperSize Feature - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/option-attributes-for-the-papersize-feature)
* Content Source: [windows-driver-docs-pr/print/option-attributes-for-the-papersize-feature.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/option-attributes-for-the-papersize-feature.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
