### ISSUE TITLE
Page claims that source is always fetched from source server.

### ISSUE THREAD

**Issue by markovandooren** [MicrosoftDocs/windows-driver-docs#2509]
When the specified source file already exists on the local system and the checksum matches, then the source server mechanism is bypassed completely. This page, however, states that the source is always fetched from the source server. You can easily confirm that this is not true in the scenario described in the first sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6e0df1-4638-9133-3315-23352641b625
* Version Independent ID: 314c937e-aad2-90c0-4eef-5bb557c7c8e3
* Content: [Language Specification 1 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/language-specification-1)
* Content Source: [windows-driver-docs-pr/debugger/language-specification-1.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/language-specification-1.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@markovandooren - Thanks for your interest in the debugging source server documentation. I believe the topic is working through a scenario where files can be both found local or requested remotely. My understanding is that SrcSrv is involved in either case. And how your source path is set – the order of remote and local directories - will determine the sequence and order of what is checked from local directories and remote file shares.  I added a reference to describe the use of .srcnoisy and to the source path topic that provide more detail. The .srcnoisy command can be used to track the order of the remote and local file access based on all of the source path settings on a current system.  Good luck with your debugging work and thanks for passing on this feedback.
