### ISSUE TITLE
Switching printer from using "Universal Print Class Driver" to vendor driver.

### ISSUE THREAD

**Issue by Mailmansgotmail** [MicrosoftDocs/windows-driver-docs#2513]
Hello.

I need to switch a printer driver (Dymo Labelwritor 450 Turbo) that is deployed using the Universal Print Connector from "Universal Print Class Driver" to the vendor's driver because I need to use their paper size "30336". 
On the print server, it is using the Dymo's driver.

When I do this, it breaks the printer and it isn't able to print anymore.

Do I need to create a custom driver or is there something else I can do?

![image](https://user-images.githubusercontent.com/71532290/93652742-05405180-f9cb-11ea-80e9-b015f0283edd.png)

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
