### ISSUE TITLE
Question on newer versions of WDDM 

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/windows-driver-docs#2519]
This doc mentions INF requirements for WDDM 1.2. WDDM 2.0 or higher doesn’t have any such documentation that specifically calls out INF related things. Is it safe to assume there are no other requirements that a driver’s INF needs for newer versions of WDDM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e98c7b90-1508-a4f2-cda8-818d3528b4a2
* Version Independent ID: 1ddfebbf-424a-3241-fafb-f7a4f136bdc4
* Content: [Graphics INF requirements in WDDM 1.2 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/graphics-inf-requirements)
* Content Source: [windows-driver-docs-pr/display/graphics-inf-requirements.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/graphics-inf-requirements.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Closing this issue as @aguptadel 's question was answered via email. We will prioritize WDDM doc updates in the future as we are able to.
