### ISSUE TITLE
Is there supposed to be a download link for Signablefile.bin?

### ISSUE THREAD

**Issue by evan-morris** [MicrosoftDocs/windows-driver-docs#2527]
Is there supposed to be a download link for Signablefile.bin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e0918f1-17f6-9f9c-30a7-47e75e14c257
* Version Independent ID: de7a4ab1-a17e-889a-16bf-d973023a2c88
* Content: [Add or Update a code signing certificate - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/update-a-code-signing-certificate)
* Content Source: [windows-driver-docs-pr/dashboard/update-a-code-signing-certificate.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/update-a-code-signing-certificate.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks for the question, @evan-morris.

“Sign and upload your file” is the title of the page in partner center that the link points at. On that page you download the signablefile.bin, and also upload it back to partner center after it has been signed. 

Hope this helps.

Eliot
