### ISSUE TITLE
Spectre error even after i DISABLED spectre Mitigation in options.. : Spectre-mitigated libraries are required for this project. Install them..

### ISSUE THREAD

**Issue by LusKrew** [MicrosoftDocs/windows-driver-docs#2533]
WHY am i getting Spectre mitigation and VS asking me to install them when i DISABLED the spectre mitigation in the options and just want to compile a SIMPLE HELLO WORLD? 

`Spectre-mitigated libraries are required for this project. Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https://aka.ms/Ofhn4c`

**Comment by RAJU2529** [comment]
@LusKrew , I would recommend you to post your question on https://developercommunity.visualstudio.com/spaces/8/index.html
so that experienced developers can answer your questions.

**Comment by EliotSeattle** [comment]
Hi @LusKrew.

The [WDK download page](https://docs.microsoft.com/windows-hardware/drivers/download-the-wdk) has this info:

"WDK has Spectre mitigation enabled by default but requires spectre mitigated libraries to be installed with Visual Studio for each architecture you are developing for. Additionally, developing drivers for ARM/ARM64 require the build tools for these architectures to also be installed with Visual Studio. To locate these items you will need to know the latest version of MSVC installed on your system." 

Does that help?
Eliot
