### ISSUE TITLE
Where is WDK for Windows 10, version 1909 ?

### ISSUE THREAD

**Issue by sonic74** [MicrosoftDocs/windows-driver-docs#2535]
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f5d6d55-cb35-6b9e-f8ca-e75f70826dc3
* Version Independent ID: 1d913516-b1e0-e872-c337-e30ed5dffce8
* Content: [Previous WDK versions and other downloads - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads)
* Content Source: [windows-driver-docs-pr/other-wdk-downloads.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/other-wdk-downloads.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @sonic74.

There was  no Windows 10, version 1909 of the WDK that was released. The last publicly released version was Windows 10, version 2004. Before that was Windows 10, version 1903.

You can find other test builds of the WDK by joining the [Windows Insider Program](https://insider.windows.com/), including [WDK Insider Preview builds](https://www.microsoft.com/software-download/windowsinsiderpreviewWDK).

Hope this helps.
Eliot
