### ISSUE TITLE
Phrasing on the first pharagraph

### ISSUE THREAD

**Issue by darugeri** [MicrosoftDocs/windows-driver-docs#2536]
I think there should be more clarification around the phrase "Unlike a system in the shutdown state (S5), however, a sleeping system retains memory state, either in the hardware or on disk" on the part of "hardware or on disk".

I understand the disk as hardware, so I am wondering if the phrase tried to refer to RAM memory as "hardware".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e17d9b3-9e6b-df00-e249-38a0cd5e1099
* Version Independent ID: 83d9bce2-8b16-812f-d587-61527d4eba50
* Content: [System Sleeping States - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/system-sleeping-states#feedback)
* Content Source: [windows-driver-docs-pr/kernel/system-sleeping-states.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/system-sleeping-states.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks Daniel, good catch.  I just pushed an update to the page - should be live within 10 min
