### ISSUE TITLE
State Separation folders privilege

### ISSUE THREAD

**Issue by taotal** [MicrosoftDocs/windows-driver-docs#2539]
[Enter feedback here]
Hi, what are the privileges of the %DriverData% and %ProgramData% content? is it Admin and System or All?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7896ae4-439c-cf13-a457-56ec30f623de
* Version Independent ID: f0bd0b30-74a6-0eb7-b8f1-787541161a69
* Content: [Driver Package Isolation - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/driver-isolation#driverdata-and-programdata)
* Content Source: [windows-driver-docs-pr/develop/driver-isolation.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/driver-isolation.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @taotal 

Thanks for the question.  For `%DriverData%`, access is admin and UMDF drivers.  For `%ProgramData%`, I'm not really sure. My specialty is drivers and that's a directory that applies across Windows.

I updated the page with the info above.
