### ISSUE TITLE
Incomplete Node type list + property value type confirmation

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2542]
Two things on this page:

1. This page says the property value type is **ULONG** (UI4). I've seen conflicting sample code that uses **LONG** (I4). Can you confirm that ULONG/UI4 is correct?
2. The Remarks section states that:

> This property is used to determine whether the following node types are implemented in hardware or software:
> 
> - AEC node (KSNODETYPE_ACOUSTIC_ECHO_CANCEL)
> - Noise-suppression node (KSNODETYPE_NOISE_SUPPRESS)
> - Peakmeter node (KSNODETYPE_PEAKMETER)

...but multiple MS samples implements this property on VOLUME and MUTE nodes (at least), suggesting that the list above is incomplete(?)

-Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b516ab12-1b77-4195-bf1c-22d30c930297
* Version Independent ID: 4bfd04a6-faba-c458-ddbb-c080dc91b23e
* Content: [KSPROPERTY\_AUDIO\_CPU\_RESOURCES - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/ksproperty-audio-cpu-resources)
* Content Source: [windows-driver-docs-pr/audio/ksproperty-audio-cpu-resources.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/ksproperty-audio-cpu-resources.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - Thanks for your interest in developing WDM audio drivers. For most all current day audio work, the the Sysvad sample, which is discussed in Sample Audio Drivers would be the sample to look at. I have made updates to remove references to the older SB16, which was for sound blaster audio 16 bit PC cards.  I believe that the ULONG is correct. For an example of its implementation look at kshelper.cpp in the Sysvad sample.

```cpp
    if (PropertyRequest->Verb & KSPROPERTY_TYPE_GET)
    {
        ntStatus = ValidatePropertyParams(PropertyRequest, sizeof(ULONG));
        if (NT_SUCCESS(ntStatus))
        {
            *(PULONG(PropertyRequest->Value)) = KSAUDIO_CPU_RESOURCES_NOT_HOST_CPU;
            PropertyRequest->ValueSize = sizeof(ULONG);
        }
    }
```
Kshelper.cpp also contains sample code to show the handling of a KSPROPERTY_TYPE_BASICSUPPORT that references a UI4, which is discussed in [KS Properties](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/ks-properties).

```cpp
        ntStatus = 
            PropertyHandler_BasicSupport
            ( 
                PropertyRequest, 
                KSPROPERTY_TYPE_GET | KSPROPERTY_TYPE_BASICSUPPORT,
                VT_UI4
            );
```

For additional questions, I would recommend these two resources, The OSR dev forums at https://community.osr.com/ and we recently moved the MSDN Forums to this location for Windows development. https://docs.microsoft.com/answers/products/windows.
