### ISSUE TITLE
Where can we find the less common values that PnPutil returns?

### ISSUE THREAD

**Issue by andykn** [MicrosoftDocs/windows-driver-docs#2543]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f814824-8b1b-766f-8fbb-86a16996eff6
* Version Independent ID: 144f5337-ec84-3587-8caf-cfae4635dc42
* Content: [PnPUtil Return Values - Windows drivers](https://docs.microsoft.com/en-gb/windows-hardware/drivers/devtest/pnputil-return-values)
* Content Source: [windows-driver-docs-pr/devtest/pnputil-return-values.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pnputil-return-values.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Hi @andykn.

Thanks for opening the issue. We did update the description on the page. I hope it's a little more helpful. We try to document the few return values of note that are specific to PnPUtil use. Documenting very generic error codes (e.g. out of memory) doesn't add a lot of value. You can get descriptions of those from the standard win32 error codes, and we rely on that documentation to do so. 

Eliot
