### ISSUE TITLE
Code sample has a typo - AdditonalOptions instead of AdditionalOptions

### ISSUE THREAD

**Issue by WilliamsJason** [MicrosoftDocs/windows-driver-docs#2544]
One of the code samples has a typo where the end tag for 'AdditionalOptions' is misspelled as 'AdditonalOptions'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d408578-140a-fdbe-f385-8309c3f7a565
* Version Independent ID: cda01d6c-e26e-e753-79e0-fd2c46cb0275
* Content: [Converting a WDK sources file to a Visual Studio project - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/converting-a-wdk-sources-file-to-a-visual-studio-project)
* Content Source: [windows-driver-docs-pr/devtest/converting-a-wdk-sources-file-to-a-visual-studio-project.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/converting-a-wdk-sources-file-to-a-visual-studio-project.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks for catching that, @WilliamsJason 

I made the change and pushed to our main branch. Should be live shortly.
Cheers,
Eliot
