### ISSUE TITLE
nothing is wrong

### ISSUE THREAD

**Issue by chilleryzz** [MicrosoftDocs/windows-driver-docs#2546]
[Enter feedback here]

nothing wrong.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e08bde9f-652d-9e48-cd2a-4fb58d368642
* Version Independent ID: 23f4f562-cdcb-6c04-3ea3-fb8653cec22b
* Content: [Bug Check 0xEF CRITICAL_PROCESS_DIED - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xef--critical-process-died)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0xef--critical-process-died.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0xef--critical-process-died.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@chilleryzz - Not seeing any specific doc comment, that we can use to improve this topic, so closing this docs issue.
