### ISSUE TITLE
watchdog.sys

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/windows-driver-docs#2550]
"The Microsoft DirectX graphics kernel subsystem (Dxgkrnl.sys) records display driver-related errors, assertions, warnings, and events to a log in memory (in Watchdog.sys).”

I can’t find any documentation anywhere on how to actually extract the logs from Watchdog.sys

Is there a documentation available some where on watchdog.sys

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b13acc-fd68-670b-7f7d-2e209218a1d9
* Version Independent ID: 212dfd6a-1db8-d5d4-dc95-8b7ad85a57f2
* Content: [Logging Driver Errors - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/logging-driver-errors)
* Content Source: [windows-driver-docs-pr/display/logging-driver-errors.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/logging-driver-errors.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@aguptadel , thanks for the PR. Watchdog.sys is for internal use. I've updated the page accordingly.
