### ISSUE TITLE
how to copy and paste on Instagram to gmail

### ISSUE THREAD

**Issue by 16926** [MicrosoftDocs/windows-driver-docs#2556]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c86514-b920-b8d4-705b-7a6a82399864
* Version Independent ID: bfbea0db-c177-0664-57e7-4dd2f6cc152d
* Content: [Edit Paste - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/edit---paste)
* Content Source: [windows-driver-docs-pr/debugger/edit---paste.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/edit---paste.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@16926 - We use this space to discuss the documentation for the Windows Debugger that is used by software developers to debug Windows internals. So not everything related to copy and paste. As I don't think your question is related to the Windows Debugger, I will close this issue. Good luck in finding out how to copy between the applications you are using.
