### ISSUE TITLE
Why!?!

### ISSUE THREAD

**Issue by minecraftchest1** [MicrosoftDocs/windows-driver-docs#2563]
[Enter feedback here]
Why!?!
"this is insane
MSFT is going to be able to modify any new windows driver at will in this scheme"
[https://chat.reactos.org/reactos/pl/wxmc9w5bdj88xfayqz6f5898wh](https://chat.reactos.org/reactos/pl/wxmc9w5bdj88xfayqz6f5898wh) 

I agree. I think that this is 100% stupid. Tell us what the point of this nonsense is. Either get rid of this nonsense, or risk loosing driver devlopers.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e326d3e-833a-e312-d35d-11569690c7e6
* Version Independent ID: 7a9795cf-093e-a67f-8162-b832e1161ba8
* Content: [Deprecation of Software Publisher Certificates, Commercial Release Certificates, and Commercial Test Certificates - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates)
* Content Source: [windows-driver-docs-pr/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @minecraftchest1 thanks for reaching out.

We've added some info to the page in question on how to report WHQL issues if you experience any.  You can find it here --

https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates#how-do-production-signing-options-differ-by-windows-version

Happy to try and help if you have specific feedback on the docs.
