### ISSUE TITLE
Possible phrasing change

### ISSUE THREAD

**Issue by darugeri** [MicrosoftDocs/windows-driver-docs#2572]
Could you check the phrase "Read and write requests to a child device are handled by the child device's function driver does the parent bus driver handle reads and writes for the device"?

It seems a little weird to me on the part about "child device's function driver does the parent bus driver handle".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f73aa243-f244-7e19-c630-bcc3161a3149
* Version Independent ID: c646e407-db97-b778-9a07-8be942c544c3
* Content: [Bus Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/bus-drivers)
* Content Source: [windows-driver-docs-pr/kernel/bus-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/bus-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks a million @darugeri this was due to an overeager regex that I ran in Jan 2019.  It caused content loss in other pages as well.  I'll address that soon but for now I restored this page.  Should be updated on the live site within a few minutes.
