### ISSUE TITLE
Create shipping label API cannot fill "Critical Incident ID"

### ISSUE THREAD

**Issue by hatasum** [MicrosoftDocs/windows-driver-docs#2573]
We have to fill Incident ID when we're creating a shipping label to follow MDA requirement if needed, but we can't achieve this due to there has no API related.
Does someone help us to get that API or have any method to achieve it? Thanks!

**Comment by EliotSeattle** [comment]
Hi, @hatasum   

For specific implementation questions, Hardware Dev Center Support can help. To contact support and open a Hardware Dev Center support case for investigation, **first**, sign into your hardware dev center account, and **then** go to [https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq).

Find: 
 
**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). 

Once there, select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

Hopes this helps.
Eliot
