### ISSUE TITLE
Broken link in "collecting and decoding wpp logs"

### ISSUE THREAD

**Issue by shsh999** [MicrosoftDocs/windows-driver-docs#2577]
There is a broken link in the "Decoding ETL logs" section, near the end of the page:
`[Test your universal sensor driver](test-your-universal-sensor-driver.md`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfec00c-8859-cca9-5f39-3ca65a09c852
* Version Independent ID: 55a1692b-ae3e-c16d-55be-9fbda035ebae
* Content: [Collecting and decoding WPP logs - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/sensors/collecting-and-decoding-wpp-logs)
* Content Source: [windows-driver-docs-pr/sensors/collecting-and-decoding-wpp-logs.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/sensors/collecting-and-decoding-wpp-logs.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by EliotSeattle** [comment]
Thanks, @shsh999 & @RAJU2529
