### ISSUE TITLE
Please document case of P4=0 for bugcheck C1

### ISSUE THREAD

**Issue by pavel-a** [MicrosoftDocs/windows-driver-docs#2579]
[Enter feedback here]
People [report cases of  bugcheck C1 with P4=0](https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/hardware-error-livekernelevent-193/9f2d74e0-c23e-4db5-b65e-2898a23c3db5), but this is not documented. If possible, please add the case of P4=0.

More general, please provide official documentation on "KernelLiveEvent" codes. Are these same as bugcheck codes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9052f9b0-2c6c-6b4b-653a-c42dbe98bd17
* Version Independent ID: 6e6b5056-3ea0-2428-3052-c000052d79fe
* Content: [Bug Check 0xC1 SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xc1--special-pool-detected-memory-corruption)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0xc1--special-pool-detected-memory-corruption.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0xc1--special-pool-detected-memory-corruption.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@pavel-a - Thanks for providing this input. I think in this case the live kernel event is not a blue screen, but rather a live dump.  Perhaps a Bug Check 0x193: VIDEO_DXGKRNL_LIVEDUMP, but I would have to look further. I'm working to better breakout the live dump stop codes and talk more about them as they are a bit different from traditional blue screen bug checks. I don't think that  0xC1 SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION would have a param 4 =0. Thanks for passing on what you are seeing.
