### ISSUE TITLE
Can SymStore support simultaneous transactions from a single user?

### ISSUE THREAD

**Issue by russbearl** [MicrosoftDocs/windows-driver-docs#2581]
[Enter feedback here]
The document indicates "SymStore does not support simultaneous transactions from multiple users. It is recommended that one user be designated "administrator" of the symbol store and be responsible for all add and del transactions."  Is it possible to update SymStore so that it supports simultaneous transactions from a single user?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5194438-a750-a987-6f4f-5a99e69ba679
* Version Independent ID: d2cd4c40-c290-99c8-ce35-ce66a2e75e59
* Content: [SymStore Transactions - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symstore-transactions)
* Content Source: [windows-driver-docs-pr/debugger/symstore-transactions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/symstore-transactions.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@russbearl - Thanks for reaching out to the Windows Driver Developer Documentation team. For product input on adding transactional support to SymStore follow this link to file product feedback using the debugger team product issue git hub:  

http://aka.ms/dexex 

Thanks again for reaching out to the Windows Driver Developer Documentation team.
