### ISSUE TITLE
What to do when WPP preprocessor isn't available in Visual Studio properties?

### ISSUE THREAD

**Issue by kyanha** [MicrosoftDocs/windows-driver-docs#2600]
![image](https://user-images.githubusercontent.com/181781/100866465-4ee2f900-345e-11eb-9488-3ff73493a4e4.png)

This is the Properties window for https://github.com/microsoft/Windows-driver-samples/tree/master/filesys/miniFilter/delete/delete.vcxproj on Visual Studio Community 16.8.2.  There is no "Run WPP" option as specified in Step 6.

What is needed to make it happen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240a28ab-1fa1-6209-aca6-8f06f7c95d05
* Version Independent ID: 721e0d85-cb7b-0f49-3482-44cfcf162235
* Content: [WPP Preprocessor - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/wpp-preprocessor)
* Content Source: [windows-driver-docs-pr/devtest/wpp-preprocessor.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/wpp-preprocessor.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by DOMARS** [comment]
@kyanha - I see all of the WPP options under project properties for the delete mini filter driver, so I think the docs are OK. It may be something with your VS install and the WDK. For help on that, I would head over to the driver dev forums and see if this issue has been seen there.

[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

Good luck in working with WPP and file system drivers.
