### ISSUE TITLE
Undocumented minor function code

### ISSUE THREAD

**Issue by scottnoone** [MicrosoftDocs/windows-driver-docs#2608]
We have discovered that IRP_MJ_SET_INFORMATION now has an undocumented minor function code of "4" (IRP_MN_KERNEL_CALL?). At a minimum this is used to by the Cloud Filter (cldflt) to bypass some access checking in NTFS' handling of FileValidDataLengthInformation. 

The documentation needs to be updated to define this value and its usage. It would also be beneficial to have a way to set this value via FltSetInformationFile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 867cd56d-6821-775f-b042-b3d1bfe9f763
* Version Independent ID: ef4ac478-8e43-3616-54c0-891f358bd762
* Content: [IRP_MJ_SET_INFORMATION (IFS) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-set-information)
* Content Source: [windows-driver-docs-pr/ifs/irp-mj-set-information.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/irp-mj-set-information.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for bringing this to our attention, @scottnoone . I've added info about the minor code (you are right that it is IRP_MN_KERNEL_CALL), and I've forwarded your feedback regarding FltSetInformationFile to the filter manager dev team.
