### ISSUE TITLE
Values list incorrectly formatted as code & other issues

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/windows-driver-docs#2609]
The values list is incorrectly formatted as code.

Also, half of the descriptions in it fail to explain what the actual source is.

Should probably link this "RHS" thing to a page explaining what it stands for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dc30bfa-c762-4ca5-4940-fd12c4224d63
* Version Independent ID: 532e4612-c864-a03c-7a08-8045ea97cc56
* Content: [Bug Check 0x9E USER_MODE_HEALTH_MONITOR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x9e--user-mode-health-monitor)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x9e--user-mode-health-monitor.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x9e--user-mode-health-monitor.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@henke37 - Thanks for the input on Bug Check 0x9E. We use customer input like this as well as data on how often the bug checks occur to determine how we allocate our documentation team resources. I changed the formatting to not be code. With markdown we have limited options that allow us to publish list content like this. I also defined RHS on first mention. I added links at the bottom of the topic that point to the related error reporting and logging. The log may contain information preceding the stop code that may identify the cause that led to the failure. Without being attached to the source code in a debugger during a failure, it can be difficult to use the parameter information. Good luck with your work in cluster troubleshooting, and thanks again for this input.
