### ISSUE TITLE
Consider removing SSL.com from recommended vendors

### ISSUE THREAD

**Issue by Bathlamos** [MicrosoftDocs/windows-driver-docs#2617]
I followed the instructions on this [page](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate) and decided to use SSL.com to purchase an SSL signing certificate, as it was recommended by Microsoft and had competitive prices.

I made a purchase on Dec 1st for a single code signing certificate and uploaded proper documentation. I won't go into details about my experience, suffices to say that it was atrocious and I'm now of the opinion that SSL.com is a scam, especially as no one ever "called me back" as the customer reps kept telling me and I still don't have my certificate, but I'm out $129.

After this, I looked at reviews online and it appears I'm not the only one in this predicament, and people are either rating the service 5/5 stars, or 1/5 stars, which is telling in and of itself. It's not my place to recommend anything, but it might be worth investigating the quality of the vendors listed on the page and update the list. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d3f097-d81b-66c2-4835-d63758687d34
* Version Independent ID: fe9d1cdd-966e-89b5-c66b-60531b0ec655
* Content: [Get a code signing certificate - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate)
* Content Source: [windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by EliotSeattle** [comment]
Thanks for the heads up, @Bathlamos, and sorry that you had such a bad experience. I have forwarded this info to the people who run the Partner Center and the dashboard administration.
All the best.
Eliot
