### ISSUE TITLE
Availability of CFU inbox driver (hidcfu.dll)

### ISSUE THREAD

**Issue by karthikpandelu** [MicrosoftDocs/windows-driver-docs#2618]
The sample INF configures the CFU inbox driver (hidcfu.dll) to enable the firmware update scenario for a virtual CFU Hid device.
Query: Is hidcfu.dll available in latest Windows 10? 
Unable to find it on Windows 10 Version 1909 (OS Build 18363.1256)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c8be335-f68e-4ace-6bd2-194e125927b6
* Version Independent ID: 2c93d359-3d30-61b9-6184-963e314c6d77
* Content: [Component Firmware Update (CFU) INF configuration - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/cfu/cfu-inf-configuration)
* Content Source: [windows-driver-docs-pr/cfu/cfu-inf-configuration.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/cfu/cfu-inf-configuration.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Added a note that CFU is available in Windows 10, version 2004 (Windows 10 May 2020 Update) and later versions.
