### ISSUE TITLE
Question about UWP device requirement

### ISSUE THREAD

**Issue by frankylin680620** [MicrosoftDocs/windows-driver-docs#2626]
[Enter feedback here]
Dear Sir

"There are four components to a UWP device app: a device, an app, a device metadata package, and a device driver. "

Is it necessary for a UWP device app to bind with a real hardware device?
I want to implement UWP app, it will modify some registry to control my effect of Audio Processing Object (APO); but APO just a software component, do not have a real device.

BR.
Franky Lin 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7e56d63-cf9a-0166-64f2-8780e5154c8a
* Version Independent ID: ebb34e44-1721-1bc6-48f9-f28615938a80
* Content: [Building UWP device apps - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/the-workflow#uwp-device-app-limits)
* Content Source: [windows-driver-docs-pr/devapps/the-workflow.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/the-workflow.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by DOMARS** [comment]
@frankylin680620 - Normally the APOs are affiliated with specific hardware. This allows the APO to benefit from an understanding of the capabilities and limitations of the hardware that it is running on. This topic describes APOs:

https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/implementing-audio-processing-objects

*When you develop your own audio driver and wrap or replace the system-supplied APOs, you must provide a driver package for installing the driver and APOs. For Windows 10, please see Universal Windows Drivers for Audio. Your audio related driver packages should follow the policies and packaging model detailed there.*

For additional support on your development efforts, the new Microsoft Windows audio hardware forum would be the recommended resource. https://docs.microsoft.com/answers/products/windows
Good luck in finding a way to accomplish what you would like to with the Windows audio driver stack.
