### ISSUE TITLE
No information on header/lib requirements.

### ISSUE THREAD

**Issue by coolhandle01** [MicrosoftDocs/windows-driver-docs#2640]
There's no information on includes here. Hitting F1 with `EvtNext` told me about  `#include <winevt.h>`, yet yields nothing for `ProcessHwErrorEvent(EventHandle);`.

Where is `ProcessHwErrorEvent(EventHandle);`  or some superceding function defined?

Actually trying to diagnose a hardware problem and I have to compile code. Awesome.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 759a7b35-c5ac-8ead-d483-3417ab3c01ed
* Version Independent ID: 72f27974-7da4-0154-f9c8-e37eacf337ce
* Content: [Registering for Notification of Hardware Error Events - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/whea/registering-for-notification-of-hardware-error-events)
* Content Source: [windows-driver-docs-pr/whea/registering-for-notification-of-hardware-error-events.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/whea/registering-for-notification-of-hardware-error-events.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by coolhandle01** [comment]
https://docs.microsoft.com/en-us/search/?terms=ProcessHwErrorEvent = No Results.

**Comment by tedhudek** [comment]
Thanks for the feedback.

In that example, `ProcessHwErrorEvent` is just an example function that the driver would implement.

To debug a hardware problem, you probably want to look for the WHEA-Logger event in the system event log. This appears in a human readable format and should not require any code. 

Best of luck!

**Comment by coolhandle01** [comment]
Cheers! AMD Drivers.. unreal the trouble they cause me!

**Comment by tedhudek** [comment]
Try this --

![image](https://user-images.githubusercontent.com/14337110/105390253-b0595580-5bcd-11eb-80c3-20c28decf5f1.png)
