### ISSUE TITLE
Deal link to Microsoft Connect

### ISSUE THREAD

**Issue by matt1va** [MicrosoftDocs/windows-driver-docs#2641]
This section references the Microsoft COnnect website which no longer exists. Please update to more current document pointers:

**For more information about MTL, see the document titled "Thermal Management in Windows" on the Microsoft Connect website.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e178346-75c1-69a4-b0ef-f428faea73e0
* Version Independent ID: 5e06be8c-f69a-9277-275d-fc6a55630dab
* Content: [Device-Specific Method for Microsoft thermal extensions - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/device-specific-method-for-microsoft-thermal-extensions)
* Content Source: [windows-driver-docs-pr/bringup/device-specific-method-for-microsoft-thermal-extensions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/device-specific-method-for-microsoft-thermal-extensions.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Updated link to point to [Thermal management in Windows](https://docs.microsoft.com/windows-hardware/design/device-experiences/thermal-management-in-windows).
