### ISSUE TITLE
Missing/ambiguous information related to the WPP extended format specification strings

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2642]
> **%!bool!** | Displays TRUE or FALSE
- Not clear what the expected parameter type is, e.g. `BOOL`, `bool`, `BOOLEAN`, etc.

> **%!delta!** | Displays the difference between two time values, in milliseconds. It is a `LONGLONG` value ...  
> **%!WAITTIME!** | Displays the time that was spent waiting for something to be  completed, in milliseconds. It is a `LONGLONG` value ...  
> **%!due!** | Displays the time that something is expected to be completed, in milliseconds. It is a `LONGLONG` value ...
- There are so many different time & date types and functions. Where would I get a time value of this (`LONGLONG`) type? With all the conversions between all the types, this becomes a tedious Google search for _something_ that eventually results in a `LONGLONG`

> **%!TIMESTAMP!**  **%!datetime!**  **%!time!** | Displays the value of system time at a particular moment. These are `LARGE_INTEGER` values that are displayed in `SYSTEMTIME` format.
- Where would I get a time value of this (`LARGE_INTEGER`) type? _(PerfCounter is probably the answer, but an example that showed that would be helpful.)_
- Not clear what the difference is (in terms of display) between these three. Example output for each would be nice.

> **%!WINERROR!** | Represents a Windows error code and displays the string associated with the error.  
> **%!NTerror!** | Represents a Windows error and displays the error message string.
- **%!STATUS!** and **%!HRESULT!** are pretty obvious, but what types/sources correspond to the above two format strings? I'm guessing that WINERROR refers to the `DWORD` that's returned by `GetLastError()`, but that's not spelled out here.
- Examples showing an sample source from which each type of code could be acquired, and example for each would be useful.

Some of these formats don't require arguments, others do. It would be good to call that out in the table as well.

**EDIT:**

Just noticed another hiccup. Docs _say_ these must be a `LARGE_INTEGER` type...
```
LARGE_INTEGER ts{};
    . . .
TraceInfo("datetime: %!datetime!", ts);
TraceInfo("time: %!TIME!", ts);
TraceInfo("TIMESTAMP: %!TIMESTAMP!", ts);
```
...but compiler complains that it's not `__int64`:
```
c:\...\foo.cpp(108): error C2664: 'void WPP_RECORDER_SF_i(PVOID,UCHAR,ULONG,USHORT,LPCGUID,__int64)': cannot convert argument 6 from 'LARGE_INTEGER' to '__int64'
c:\...\foo.cpp(108): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\...\foo.cpp(109): error C2664: 'void WPP_RECORDER_SF_i(PVOID,UCHAR,ULONG,USHORT,LPCGUID,__int64)': cannot convert argument 6 from 'LARGE_INTEGER' to '__int64'
c:\...\foo.cpp(109): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\...\foo.cpp(110): error C2664: 'void WPP_RECORDER_SF_i(PVOID,UCHAR,ULONG,USHORT,LPCGUID,__int64)': cannot convert argument 6 from 'LARGE_INTEGER' to '__int64'
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0872087-ae89-e1ef-9868-20d25431b1e8
* Version Independent ID: c19ff217-5900-43a0-98fa-0ef9f8a30163
* Content: [What are the WPP extended format specification strings - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/what-are-the-wpp-extended-format-specification-strings-)
* Content Source: [windows-driver-docs-pr/devtest/what-are-the-wpp-extended-format-specification-strings-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/what-are-the-wpp-extended-format-specification-strings-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @EliotSeattle
* Microsoft Alias: **eliotgra**

**Comment by DOMARS** [comment]
@mr-intj - Thanks for providing input on the Windows WPP documentation. I have an internal work item to investigate the issues raised here and make updates to this topic. 

From what my initial investigation shows, it looks like %!TIMESTAMP! %!datetime! and %!TIME! can be defined as a long long.

I'm investigating the current status of %!NTerror!. I would consider the use of %!WINERROR! instead.

On your other ideas, there maybe more that we can add here, but often the best way to understand the use of WPP, is to look at the sample drivers. Both the larger toaster driver sample as well as the tracedrv sample described in [Where are the tracing samples?](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/where-are-the-tracing-samples-). One approach is to use those samples as a starting point, and add any additional desired trace information to that code, using the framework that they provide as a starting point.

Thanks for the input and good luck with your WPP driver code development.
