### ISSUE TITLE
WPP extended format specification string issues...

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2645]
These special tokens are documented in different cases, e.g.: **`%!TIMESTAMP!`** vs. **`%!time!`**, and it appears that they are case-sensitive, but testing these in a UMDF project, there are some differences from the documentation:

- **`%!time!`** doesn't compile (but **`%!TIME!`** does):  
`EntryPoint.cpp(109): error wpp: Type 'time' not found. "time: %!time!"`

- No variation of **`%!FLAGS!`** that I tried would compile:  
`EntryPoint.cpp(86): error wpp: Type 'FLAGS' not found. "Trace flags: %!FLAGS!"`

- No variation of **`%!NTerror!`** that I tried would compile:  
`EntryPoint.cpp(96): error wpp: Type 'NTerror' not found. "NTerror: %!NTerror!"`

There may be others; I haven't tested them all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0872087-ae89-e1ef-9868-20d25431b1e8
* Version Independent ID: c19ff217-5900-43a0-98fa-0ef9f8a30163
* Content: [What are the WPP extended format specification strings - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/what-are-the-wpp-extended-format-specification-strings-)
* Content Source: [windows-driver-docs-pr/devtest/what-are-the-wpp-extended-format-specification-strings-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/what-are-the-wpp-extended-format-specification-strings-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - Thanks for providing input on the Windows WPP documentation. I have an internal work item to investigate the issues raised here and make updates to this topic. 

From what my initial investigation shows, it looks like %!TIME! is upper case as you indicated, and can be defined as a long long.

 The usage of %!FLAGS! is a bit more complex. I do see some use of flags that are defined in WPP_CONTROL_GUIDS, in tracedrv.c in the tracedrv sample. The tracing samples would a good resource in developing custom code, as well as the toaster driver sample. The trace samples are described in: [Where are the tracing samples?](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/where-are-the-tracing-samples-).

I'm investigating the current status of %!NTerror!. I would consider the use of %!WINERROR! instead.

Thanks for the input and good luck with your WPP driver code development.
