### ISSUE TITLE
Explain term MDA

### ISSUE THREAD

**Issue by mfriedrich74** [MicrosoftDocs/windows-driver-docs#2646]
What is MDA? Web search leads to no useful result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fbf1a53-0b5e-0d7f-378d-dfb30a6456a0
* Version Independent ID: de73a252-231a-7e3b-d000-41c8743e5036
* Content: [Managing User Roles - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/managing-user-roles)
* Content Source: [windows-driver-docs-pr/dashboard/managing-user-roles.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/managing-user-roles.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi Mike - thanks for the feedback. MDA is one of the programs Microsoft has for partners.  It doesn't affect the text on that doc page, though, so I just pushed a change that removes both instances.

Hope that helps!
