### ISSUE TITLE
Deprecation of Software Publisher Certificates and No Driver Updates Allowed for Win7/8 : Microsoft is playing with fire and will lose many customers if it continues this path.

### ISSUE THREAD

**Issue by ynsdamobb** [MicrosoftDocs/windows-driver-docs#2651]
I just received the horrible news that Microsoft is pushing for some horrendous policies : 

https://www.osr.com/blog/2020/10/15/microsoft-driver-updates-allowed-win7-win8/

https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates

If Microsoft continues on the same direction, many companies will be starting to move their infrastructure toward Linux. so we suggest that Microsoft gives a second thought on these policies because these horrendous policies will benefit no one.

And if the decision is final let us know **immediately** so we can transition as soon as possible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e326d3e-833a-e312-d35d-11569690c7e6
* Version Independent ID: 7a9795cf-093e-a67f-8162-b832e1161ba8
* Content: [Deprecation of Software Publisher Certificates, Commercial Release Certificates, and Commercial Test Certificates - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates)
* Content Source: [windows-driver-docs-pr/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi Valerio, we appreciate your feedback.  If you have challenges signing your driver with WHQL, please report the specifics using one of the two options listed in https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates#how-do-production-signing-options-differ-by-windows-version.

Thanks again for reaching out!
