### ISSUE TITLE
The diagram, "Vendor Cryptographic Storage Provider" should be "Vendor Cryptographic Service Provider" instead.

### ISSUE THREAD

**Issue by oscarso** [MicrosoftDocs/windows-driver-docs#2667]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73feeed-82a3-de8a-ccff-03031597f0b7
* Version Independent ID: 8b63af20-5da2-22ca-b073-db0c7dec1511
* Content: [Smart Card Minidrivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/smartcard/smart-card-minidrivers)
* Content Source: [windows-driver-docs-pr/smartcard/smart-card-minidrivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/smartcard/smart-card-minidrivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the heads-up!  This is fixed now
