### ISSUE TITLE
Stuck at step4

### ISSUE THREAD

**Issue by hawaiixuan** [MicrosoftDocs/windows-driver-docs#2670]
I was stuck at step 4 of "Launch devenv.exe from the same environment, using the full file path. Example: C:\Program Files (x86)\Microsoft Visual Studio\2019\\%Community|Professionial|Enterprise%\Common7\IDE\devenv.exe" 

The steps shows 
1. Mount the EWDK ISO.
2. Run LaunchBuildEnv.cmd.
3. In the environment created in step 2, type SetupVSEnv, and then press Enter.
4. Launch devenv.exe from the same environment, using the full file path. Example: C:\Program Files (x86)\Microsoft Visual Studio\2019\\%Community|Professionial|Enterprise%\Common7\IDE\devenv.exe
[Enter feedback here]

It showed 'c:\program' is not recognized as an internal or external command, operable program or bath files. Any suggesiton?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @hawaiixuan, thanks for reaching out. Can you try putting double quotes around the path? The space in "Program Files" might be causing the problem.  I just pushed an update to the doc page adding these. Let us know if you're still stuck.
