### ISSUE TITLE
DevCon sethwid for USB devices

### ISSUE THREAD

**Issue by electrongeek** [MicrosoftDocs/windows-driver-docs#2672]
Hi team, I appreciate you maintaining this helpful documentation. I need help updating a USB device's HWID name (ex: ABC-123), but I'm unsure how to get the root-enumerated ID and whether this will accomplish what I'm trying to do.

I'm completely new to devcon, so I'm providing my steps. In this example, I'm trying to update ABC-123 to DEF-234

D:\Downloads>devcon hwids "USB\VID_04DA&PID_2374&REV_0100"
USB\VID_04DA&PID_2374\0000000000000000000XER0804160005
    Name: ABC-123
    Hardware IDs:
        USB\VID_04DA&PID_2374&REV_0100
        USB\VID_04DA&PID_2374
    Compatible IDs:
        USB\Class_06&SubClass_01&Prot_01
        USB\Class_06&SubClass_01
        USB\Class_06
1 matching device(s) found.

**Commands I've tried:**

D:\Downloads>devcon sethwid "USB\VID_04DA&PID_2374&REV_0100" := ="DEF-234"
USB\VID_04DA&PID_2374\0000000000000000000XER0804160005      : Skipping (Not root-enumerated).
Skipped 1 non-root device(s), modified the hardware ID on 0 device(s).

D:\Downloads>devcon sethwid "ROOT\USB\VID_04DA&PID_2374&REV_0100" := ="DEF-234"
No hardware ID's modified.

D:\Downloads>devcon sethwid "@ROOT\USB\VID_04DA&PID_2374&REV_0100" := ="DEF-234"
No hardware ID's modified.

D:\Downloads>devcon sethwid @ROOT\USB\VID_04DA&PID_2374&REV_0100 := ="DEF-234"
devcon: Invalid use of sethwid.
For more information, type: devcon help sethwid
'PID_2374' is not recognized as an internal or external command,
operable program or batch file.
'REV_0100' is not recognized as an internal or external command,
operable program or batch file.

**What am I doing wrong here? What is the correct root-enumerated name? And will this update the HW ID name?**

**Comment by DOMARS** [comment]
@electrongeek - Thanks for your interest in our devcon docs. You may want to look at "Example 43: Add, delete, and replace hardware IDs" in the [Device Console (DevCon.exe) Examples](https://docs.microsoft.com/windows-hardware/drivers/devtest/devcon-examples) topic. 

This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. Good luck with your use of the devcon command.
