### ISSUE TITLE
Access condition

### ISSUE THREAD

**Issue by sri4kgithub** [MicrosoftDocs/windows-driver-docs#2673]
MBIMPinTypeNev key refers to Access is never allowed ?

**Comment by tedhudek** [comment]
Is there a specific doc page that you're asking about?

**Comment by aviviano** [comment]
Hi @sri4kgithub. Since we haven't heard a response from you, I'm going to close this issue. Please feel free to reopen an issue on a specific doc page. This will help us understand your comments/questions. Thanks.
