### ISSUE TITLE
In the seventh point, Microsoft Cross-Certificates for Windows Vista Kernel Mode Code Signing URL link is pointing to incorrect location

### ISSUE THREAD

**Issue by BhaskarUday** [MicrosoftDocs/windows-driver-docs#2674]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53aaa60d-e469-f26a-bc3b-8f559947559b
* Version Independent ID: 164e8e13-c649-ffb6-6b2f-31ebc95f3b5f
* Content: [Determining an SPC's Cross-Certificate - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/determining-an-spc-s-cross-certificate)
* Content Source: [windows-driver-docs-pr/install/determining-an-spc-s-cross-certificate.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/determining-an-spc-s-cross-certificate.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @BhaskarUday for letting us know.

I just pushed an updated link - should be on the live site within 10 minutes.
