### ISSUE TITLE
Obsolete false info about cross-sign option with attestation signing

### ISSUE THREAD

**Issue by ys05** [MicrosoftDocs/windows-driver-docs#2688]
Article says: "As an alternative to HLK and HCK testing, you can cross-sign your driver yourself and submit it to the dashboard for attestation signing so that it also works on Windows 10. This is more complicated, but still a valid option." 
That probably worked sometime before but seems to be wrong now. Attestation signing recreates the new cat file, so all previous cross-signing for other Windows versions is lost. So that isn't an alternative to HLK and HCK testing for a driver to be compatible with older Windows versions, and shame on Microsoft because of this. Although sys file itself can be cross-signed, that is nothing without cross-signed cat file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ba4c28c-fc37-3f02-e5a1-c52e0f3ed915
* Version Independent ID: 73a53aa7-46db-3ed1-0ecd-022eece214b8
* Content: [Get drivers signed by Microsoft for multiple Windows versions - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions)
* Content Source: [windows-driver-docs-pr/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the heads-up @ys05.  I removed the cross-signing reference in ae71829.
