### ISSUE TITLE
Default volume levels for Windows 10

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs#2691]
Hi,
The table in the page does not provide default volume levels for Windows 10. Please update.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8a38021-98c1-f7a4-50d1-231230d460d0
* Version Independent ID: 1d277dd0-454f-7069-2763-2bf4797417ad
* Content: [Default Audio Volume Settings - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/default-audio-volume-settings)
* Content Source: [windows-driver-docs-pr/audio/default-audio-volume-settings.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/default-audio-volume-settings.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@guliteb - Thanks for pointing out this gap in our docs. The db and level volume settings remain the same from Windows 8. I added a new row to document these settings for Windows 10 in this topic. Thanks for your interest in improving the Windows driver documentation!
