### ISSUE TITLE
How does software volume control APO determine the default volume level?

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs#2692]
Hi,
The page does not explain how the software volume APO component perform Volume attenuation and gain. And how does it determine default volume level?

There is a table in the link [Default Audio Volume Settings](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/default-audio-volume-settings). Does the APO follow the table to set default volume level?

Is there any way to customize the default volume level when it is controlled by the APO software volume support component?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf6ca6e-9dcd-817c-b14d-d10c0f512afb
* Version Independent ID: e7ac3a17-b17b-3aa1-b0a6-d4edb7572bb3
* Content: [Software Volume Control Support - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/software-volume-control-support)
* Content Source: [windows-driver-docs-pr/audio/software-volume-control-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/software-volume-control-support.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@guliteb - Thanks for reaching out to the Windows Driver Developer Documentation team. This is an interesting question about the interaction between APO and system level volume settings. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html)

I do see this volume related code in DelayAPOMFX.cpp in the sysvad driver sample, the you may want to look at that for one APO example.

```cpp
   // Set scalars to decrease volume from 1.0 to 1.0/N where N is the number of channels
    // starting with the first channel.
    f32InverseChannelCount = 1.0f/m_u32SamplesPerFrame;
    for (UINT16 u16Index=0; u16Index<m_u32SamplesPerFrame; u16Index++)
    {
        m_pf32Coefficients[u16Index] = 1.0f - (FLOAT32)(f32InverseChannelCount)*u16Index;
    }
```
My understanding is that there are multiple places that volume levels can be set. The presence of OEM specific APOs, Bluetooth audio and specific hardware configuration such as amplifiers can influence how the volume levels are set, and that would of course vary with each OEM.  Good luck with your work in audio driver development.
