### ISSUE TITLE
How does the bus driver set the power state of the device?

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs#2695]
Hi,
I am looking for more details on how a bus driver sets the power state of a child device of the bus. Is there any reference link?

_> The bus driver is the driver in the stack that is called last. When the framework calls the bus driver's EvtDeviceD0Exit callback function, the callback function sets the power state of the device (a child device of the bus) to a low-power state._

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885be8a-bfe7-e8d2-6e98-907a10ecb514
* Version Independent ID: 41dc5b7f-ffb6-7019-0a94-bf00b3e1566b
* Content: [A Device Enters a Low-Power State - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/a-device-enters-a-low-power-state)
* Content Source: [windows-driver-docs-pr/wdf/a-device-enters-a-low-power-state.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/a-device-enters-a-low-power-state.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @guliteb thanks for the feedback and sorry it took us so long.  I just pushed the above commit to update the doc with an answer to your question.  The fix should appear on the live docs website momentarily.  Hope this helps!
