### ISSUE TITLE
How does the bus driver set the power state of a child device?

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs#2696]
Hi,
I am looking for more details on how a bus driver sets the power state of a child device of the bus. Is there any reference link?

> _By default, whenever the system enters a system sleeping state, the framework asks the driver for your device's bus to lower the device power state to D3. When the system power returns to its working (S0) state, the framework requests the bus driver to restore your device to its working (D0) state._

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885be8a-bfe7-e8d2-6e98-907a10ecb514
* Version Independent ID: 41dc5b7f-ffb6-7019-0a94-bf00b3e1566b
* Content: [A Device Enters a Low-Power State - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/a-device-enters-a-low-power-state)
* Content Source: [windows-driver-docs-pr/wdf/a-device-enters-a-low-power-state.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/a-device-enters-a-low-power-state.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
See https://github.com/MicrosoftDocs/windows-driver-docs/issues/2695
