### ISSUE TITLE
When can we expect refreshed cross-certs for those that expired 2021.02.22?

### ISSUE THREAD

**Issue by rogerstewart** [MicrosoftDocs/windows-driver-docs#2701]
When can we expect refreshed cross-certs for those that expired 2021.02.22?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c19d51-a948-b3ff-65c2-d8c54291b42f
* Version Independent ID: b5654182-fdcb-72c0-e5ae-536992731e98
* Content: [Cross-Certificates for Kernel Mode Code Signing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/cross-certificates-for-kernel-mode-code-signing)
* Content Source: [windows-driver-docs-pr/install/cross-certificates-for-kernel-mode-code-signing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/cross-certificates-for-kernel-mode-code-signing.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @rogerstewart, thanks for the feedback.

The Microsoft Trusted Root Program no longer supports root certificates that have kernel mode signing capabilities.

There will be no renewals of these cross-certs, as issuance of cross-certs have ceased since 2017.
