### ISSUE TITLE
Download the Windows Driver Kit (WDK): I don't need answers.

### ISSUE THREAD

**Issue by seacock** [MicrosoftDocs/windows-driver-docs#2702]
![Windows Software Development Kit - Windows 10 0 19041 685 24_02_2021 22_03_03](https://user-images.githubusercontent.com/23142803/109071327-e077a500-76f3-11eb-9617-bb087143e24a.png)
![Windows Driver Kit - Windows 10 0 19041 685 24_02_2021 22_20_14](https://user-images.githubusercontent.com/23142803/109071360-ea010d00-76f3-11eb-8051-807039b7d05a.png)
![VSIX Installer 24_02_2021 22_23_58](https://user-images.githubusercontent.com/23142803/109071393-f2f1de80-76f3-11eb-9127-b3c9caaaf016.png)
![Microsoft Visual Studio 24_02_2021 22_48_03_LI](https://user-images.githubusercontent.com/23142803/109071421-fdac7380-76f3-11eb-859f-de60180cd96a.jpg)

After reading something like this doc and similar and after some unuseful installations, I applied the steps stated in this doc. With that I was able to get to the mask shown in Write a Windows desktop app based on the WinUSB template. I don't know if
I'll be able to follow it. For now good.
![Windows Software Development Kit - Windows 10 0 19041 685 24_02_2021 22_03_03](https://user-images.githubusercontent.com/23142803/109069953-32b7c680-76f2-11eb-8686-91f2d930ce15.png)
![Windows Driver Kit - Windows 10 0 19041 685 24_02_2021 22_20_14](https://user-images.githubusercontent.com/23142803/109069980-3c412e80-76f2-11eb-8998-855776ebdba9.png)
![VSIX Installer 24_02_2021 22_23_58](https://user-images.githubusercontent.com/23142803/109069995-406d4c00-76f2-11eb-9a63-92b28ebe97cd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @seacock, thanks for reaching out.  I don't see a question or doc issue, so I'm going to close this out.  If you do have a question, please feel free to reactivate as needed.  Good luck with your kit installation.
