### ISSUE TITLE
Altitude MiniFilter Request unanswered request

### ISSUE THREAD

**Issue by Hlab-tech-team** [MicrosoftDocs/windows-driver-docs#2704]
Hi,

we've been trying for many months  to get an altitude allocation made (12/2019, 01/2020, 03/2020, 01/2021 at least) but never got any response from the fsfcomm alias.

We've seen somebody else reaching out to you using the issue tracker from here (https://github.com/MicrosoftDocs/windows-driver-docs/issues/2442) so we're giving it a shot too.

Our requests came from "contact @ harfanglab.fr" and  "tech.team @ harfanglab.fr"

Can you help us out here too?

Thanks in advance

BR

(P.S: we're using outlook 365 and checked our spam folder, no email here whatsoever)

**Comment by lorihollasch** [comment]
@Hlab-tech-team , sorry to hear this! I've reached out to the fsfcomm alias, and they have your 01/2021 email. They are processing a batch of requests right now, so you should hear from them soon. Feel free to reopen this issue if you don't get a response within the next couple of weeks.
