### ISSUE TITLE
Write a Windows desktop app based on the WinUSB template 2

### ISSUE THREAD

**Issue by seacock** [MicrosoftDocs/windows-driver-docs#2705]
I'm an hobbyist and don't know if I'll be able to reach my goal. I anyway don't need answers.
![morning](https://user-images.githubusercontent.com/23142803/109145324-a4c7f400-7762-11eb-9199-120ded455f5f.png)
![Dettagli file del driver 25_02_2021 12_01_05](https://user-images.githubusercontent.com/23142803/109145396-bc06e180-7762-11eb-80f3-c08d281f8906.png)
![Screenshot 25_02_2021 12_01_35](https://user-images.githubusercontent.com/23142803/109145440-c628e000-7762-11eb-9a61-99728023c1d9.png)
![USB Application1 (Debugging) - Microsoft Visual Studio 25_02_2021 12_03_01](https://user-images.githubusercontent.com/23142803/109145465-cc1ec100-7762-11eb-87b5-29c73185782c.png)
![USB Application1 (Debugging) - Microsoft Visual Studio 25_02_2021 12_04_13](https://user-images.githubusercontent.com/23142803/109145494-d3de6580-7762-11eb-87f7-c548b92af780.png)
![USB Application1 (Debugging) - Microsoft Visual Studio 25_02_2021 12_05_46](https://user-images.githubusercontent.com/23142803/109145508-d771ec80-7762-11eb-96f4-6807bb1cdd5c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5852b021-94d2-1a19-17f3-7dc54d4cb409
* Version Independent ID: 031f5cb8-db62-4a2d-9ea4-939eb0fd0ade
* Content: [Write a Windows desktop app based on the WinUSB template - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/how-to-write-a-windows-desktop-app-that-communicates-with-a-usb-device)
* Content Source: [windows-driver-docs-pr/usbcon/how-to-write-a-windows-desktop-app-that-communicates-with-a-usb-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/how-to-write-a-windows-desktop-app-that-communicates-with-a-usb-device.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @billlattimer
* Microsoft Alias: **billla**

**Comment by tedhudek** [comment]
Hi @seacock, thanks for the feedback.  Closing this out since it doesn't look like you have any questions - please re-open if we can help in any way!
