### ISSUE TITLE
CA list in Deprecation of Software Publisher Certificates page is not complete? what is the full list?

### ISSUE THREAD

**Issue by JohnSmith1968** [MicrosoftDocs/windows-driver-docs#2713]
Why some of the CAs are not listed in : 

https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates#what-is-the-expiration-schedule-of-the-trusted-cross-certificates

There seems to be some CAs that don't get expired in 2021 : 
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/cross-certificates-for-kernel-mode-code-signing

does this mean that CAs that are listed in the second link that are not getting expired soon, can still be used to issue EV certificates to sign kernel drivers in 2022,2033? 

The enitre page is just a big question mark and a lot of questions are not answered there.. does this update mean that after 3-4 months, no one can develop new windows 7 drivers??

https://www.osr.com/blog/2020/10/15/microsoft-driver-updates-allowed-win7-win8/

how can we opt out of this "update" ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e326d3e-833a-e312-d35d-11569690c7e6
* Version Independent ID: 7a9795cf-093e-a67f-8162-b832e1161ba8
* Content: [Deprecation of Software Publisher Certificates, Commercial Release Certificates, and Commercial Test Certificates - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates)
* Content Source: [windows-driver-docs-pr/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for their input @JohnSmith1968. We've added a section to the bottom of the FAQ to address your concerns regarding CA's that expire after 2021.

As far as how this affects Windows 7, see the following section: 

https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates#how-do-production-signing-options-differ-by-windows-version

If you have specific blockers with WHQL, use one of the feedback mechanisms listed in that section to report them.

Hope this helps!
