### ISSUE TITLE
Default Sample Rate for USB Devices

### ISSUE THREAD

**Issue by wimyxconfig** [MicrosoftDocs/windows-driver-docs#2714]
Hello,

My issues is quite similar to [#376](https://github.com/MicrosoftDocs/windows-driver-docs/issues/376)

When negotiating with an external audio device, I have witnessed Windows behaving as outlined in the issue 376 -- default input sample rate always negotiates to 44.1. Since popular video conferencing software (Zoom, Teams, Vmix call) is hardcoded to run at 48k and WDM does not SRC this causes a sample rate mismatch that effectively pitches down the input signal. 

I'm perfectly capable of navigating to the preferences and defining the sample-rate, but I work regularly with radio/tv guests that are not technically inclined/particularly patient with troubleshooting. I would really love the ability to edit the default value so that the audio device runs at 48k every time it boots/negotiates. Is this possible?

**Comment by DOMARS** [comment]
@wimyxconfig - This is an interesting question on how the sample rate is set. In general this forum is for feedback on specific docs topics. So I recommend that post your request for additional information in the following forums, where other driver developers and Microsoft engineers can be found.

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

NTDEV forum at the [OSR Online Community](https://community.osr.com/)

From what I can remember, the OEM and sound hardware provider, may be able to customize this setting, so I'm not sure there is a single answer for all of the possible hardware and streaming software. But not sure on USB connected audio.

If you think Windows should behave differently, you can use the Feedback Hub app in Windows,  to see if similar feedback exists, and to file new feedback. 

Thanks for your interest in creating a better streaming experience for less technical Windows users.
