### ISSUE TITLE
Typo in the NdisGetDataBuffer documentation

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs#273]
In the https://msdn.microsoft.com/en-us/library/windows/hardware/ff562631(v=vs.85).aspx

Instead of:
> If the requested data in the buffer is contiguous, this return value is a pointer to a location that NDIS provides.

it should be:

> If the requested data in the buffer is contiguous, the return value is a pointer to a location that NDIS provides.

**Comment by duncanmacmichael** [comment]
Thanks @I-gor-C , I've updated the wording. This should go live a week from today when the network driver reference gets published next.
