### ISSUE TITLE
Command to enable testsigning is wrong

### ISSUE THREAD

**Issue by rahul-ramadas** [MicrosoftDocs/windows-driver-docs#2735]
The command to enable testsigning is listed as:

`Bcdedit /set GUID_DEVICE_RESET_INTERFACE_STANDARD testsigning on`

I don't know why there is a random GUID in there. The command should be:

`Bcdedit /set testsigning on`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b37fb8bf-f9ed-8080-dc90-9bcc1a73e486
* Version Independent ID: 2e7f17aa-1890-ae04-f82e-c456f831463f
* Content: [Resetting and recovering a device - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/resetting-and-recovering-a-device#verifying-acpi-firmware-on-the-test-system)
* Content Source: [windows-driver-docs-pr/kernel/resetting-and-recovering-a-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/resetting-and-recovering-a-device.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Just pushed the fix, thanks for the heads-up @rahul-ramadas
