### ISSUE TITLE
Create a signed catalog file for the package.

### ISSUE THREAD

**Issue by Zer0cul** [MicrosoftDocs/windows-driver-docs#2736]
There is no reference or guide on how to create the signed catalog file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd1c106b-9499-4f15-f479-92537b5e4bed
* Version Independent ID: a10bfa35-ff3e-b169-0314-750dc5a28794
* Content: [WinUSB (Winusb.sys) Installation - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/winusb-installation)
* Content Source: [windows-driver-docs-pr/usbcon/winusb-installation.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/winusb-installation.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @Zer0cul for the feedback.  I've just added a link to the doc page in question with related info.  See the link to my commit above.
