### ISSUE TITLE
Doesn't mention where extension binaries go.

### ISSUE THREAD

**Issue by Dano7** [MicrosoftDocs/windows-driver-docs#2740]
Great to see new love for an old trusty tool!

We used to drop extensions in the binaries folder such as [SOSEX](http://www.stevestechspot.com/SOSEXANewDebuggingExtensionForManagedCode.aspx)  (which helps make better sense of .NET code in process dumps.) 

Now that it's Windows Store App is there a place to indicate a path for such extensions or do we have to hack up the filesystem ACLs so we can drop them next to the debug engine binaries?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1e093f9-7df0-17ab-71ae-8af9003ee041
* Version Independent ID: 55ed6fd3-a7a6-f7d5-2a8e-fbf6cc6e2c7b
* Content: [Debugging Using WinDbg Preview - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-using-windbg-preview)
* Content Source: [windows-driver-docs-pr/debugger/debugging-using-windbg-preview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugging-using-windbg-preview.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Dano7 - Thanks for reaching out to the Windows Driver Developer Documentation team.  And thanks for the nice words for the work being done on WinDbg Preview. 

For product input on adding support for managed code extensions, use this link to file product feedback using the debugger team product issue git hub:  

http://aka.ms/dexex 

On the loading of extensions, there is an existing product feedback issue related to this here: 
https://github.com/microsoftfeedback/WinDbg-Feedback/issues/32

And the idea of a visual .chain command, that would show which are active and be able to unload the ones that you don't need.
https://github.com/microsoftfeedback/WinDbg-Feedback/issues/16

You can decide if you want to upvote any of the existing product issues, or create a new one.

As a modern alternative to extensions many developers are looking at JavaScript that can make use of the new debugger object model. The new debugger has a built in scripting UI. You can read more about it here: https://docs.microsoft.com/windows-hardware/drivers/debugger/native-objects-in-javascript-extensions 

Good luck with your debugging.
