### ISSUE TITLE
Order of includes in Header section should be the the opposite 

### ISSUE THREAD

**Issue by tzuriel-spearuav** [MicrosoftDocs/windows-driver-docs#2742]
As noted in this file, for include you need both `Usbiodef.h `and `initguid.h`
Notice the order matters, and it should actually be first `initguid.h` and only then `Usbiodef.h` (as pointed out [here](https://stackoverflow.com/questions/48548540/which-library-guid-devinterface-usb-hub-is-defined/48550614))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc07324f-bf4f-8857-2ea3-3539a586fb27
* Version Independent ID: 63179fd5-2bd5-ef2c-b180-419340116d29
* Content: [GUID_DEVINTERFACE_USB_DEVICE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-devinterface-usb-device)
* Content Source: [windows-driver-docs-pr/install/guid-devinterface-usb-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/guid-devinterface-usb-device.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thank you, @tzuriel-spearuav, that is a subtle but crucial distinction. There is a sentence higher on the page that I think makes the point ("You must include initguid.h before including...") but I just took the liberty of making it more explicit in the Requirements table.  See what you think.
