### ISSUE TITLE
Looks like the WindowsVersionList is out of date again.

### ISSUE THREAD

**Issue by zjzhex** [MicrosoftDocs/windows-driver-docs#2745]
https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/inf2cat

What's the version identifier of Windows Server 2019 (1809)?

**Comment by tedhudek** [comment]
Hi @zjzhex, thanks for reaching out.  I believe 1809 is RS5, which does appear in the table with version identifier ServerRS5_X64.

**Comment by zjzhex** [comment]
Hi @tedhudek, thank you for the clarification!

**Comment by zjzhex** [comment]
Hi @tedhudek, thank you for the clarification!
