### ISSUE TITLE
`notepad!WinMain` is outdated?

### ISSUE THREAD

**Issue by SamZhangQingChuan** [MicrosoftDocs/windows-driver-docs#2747]
In section *6*, the instruction is:
```
To put a breakpoint at notepad!WinMain, enter this command:

bu notepad!WinMain
```
However, on my workstation, the correct symbol seems to be `notepad!wWinMain`.

Evidence:
```
0:000> x notepad!*main*
00007ff7`83d03c30 notepad!__scrt_common_main_seh (void)
00007ff7`83d05788 notepad!`__scrt_common_main_seh'::`1'::filt$0 (void)
00007ff7`83ceb0a0 notepad!wWinMain (wWinMain)
00007ff7`83d06f80 notepad!_imp__get_wide_winmain_command_line = <no type information>
00007ff7`83d03db0 notepad!wWinMainCRTStartup (wWinMainCRTStartup)
00007ff7`83d06f80 notepad!_imp__o__get_wide_winmain_command_line = <no type information>
00007ff7`83d05020 notepad!get_wide_winmain_command_line (_get_wide_winmain_command_line)
00007ff7`83d05020 notepad!o__get_wide_winmain_command_line (_o__get_wide_winmain_command_line)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142adea7-b7b8-4a5a-5e19-83a202ab04b2
* Version Independent ID: 489c0c22-908c-aa93-520c-836c941b5b4e
* Content: [Getting Started with WinDbg (User-Mode) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/getting-started-with-windbg)
* Content Source: [windows-driver-docs-pr/debugger/getting-started-with-windbg.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/getting-started-with-windbg.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@SamZhangQingChuan - Right you are. It does look like some of the pieces of NotePad have changed. So I updated the topic to match the current notepad modules. Thanks for seeing these differences, that could be confusing to new debugger folks. Good luck with your debugging, and thanks for filing this issue.
