### ISSUE TITLE
Trace events in Event Viewer?

### ISSUE THREAD

**Issue by joebauman-atvi** [MicrosoftDocs/windows-driver-docs#2752]
In the last section, "Test the driver...", it says to:
"Install the driver. Exercise the driver to generate trace activity. View the results in the Event Viewer. "
I've followed the instructions and am able to see and record events in, for example, TraceView.exe, but haven't been able to get them to appear in the Event Viewer.  Is this a mistake in the documentation or have I missed something?
It looks like Event Viewer can be used to open trace logs recorded by manual trace sessions, but I would like to be able to see events recorded automatically and viewed in the event viewer after they occur.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f93c1d9-ccc3-bc8a-14d9-7b23df2773c0
* Version Independent ID: 50326231-07f4-0f95-3dec-76fc49a75612
* Content: [Adding Event Tracing to Kernel-Mode Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/adding-event-tracing-to-kernel-mode-drivers)
* Content Source: [windows-driver-docs-pr/devtest/adding-event-tracing-to-kernel-mode-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/adding-event-tracing-to-kernel-mode-drivers.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@joebauman-atvi - - Thanks for your interest in our devtest docs. 

This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios.  Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. 

It is possible that the event viewer configuration or the driver install has placed the events somewhere unexpected or they are being filtered out. I typically clear (and possibly save) the event logs to make it easier to search what I'm looking for. 

Two possible resources for exploring your event flow configuration. Raymond Chen has a good end to end blog which shows creating and view events.   https://www.raymond.cc/blog/create-an-event-in-event-viewer/ You can also write code to extract the events and search through that. For example that is described here: https://docs.microsoft.com/en-us/windows/win32/eventlog/querying-for-event-source-messages

Good luck with adding events to your driver and viewing the in event viewer.
