### ISSUE TITLE
device error code 53 (USB EEM)

### ISSUE THREAD

**Issue by p692584k** [MicrosoftDocs/windows-driver-docs#2754]
Hi,
My host have Windows KDNET-USB-EMM Network Adapter under Network Adapters in Windows Device Manager.
But my target's device is error.
(Code 53 - This Device Has Been Reserved for Use by the Windows Kernel Debugger for the Duration of This Boot Session)
How can i solve it?
Thanks.

**Comment by DOMARS** [comment]
@p692584k - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. 

My recollection is this message can indicate that the network card has been reserved for debugging, but it is still operative. The debugging option selected in using bcdedit. You can learn how to disable this via the links in [Code 53 - CM_PROB_USED_BY_DEBUGGER](https://docs.microsoft.com/windows-hardware/drivers/install/cm-prob-used-by-debugger)
Good luck with your debugging.
