### ISSUE TITLE
As the name sugests ---should be---> As the name suggests

### ISSUE THREAD

**Issue by Alegriabaile** [MicrosoftDocs/windows-driver-docs#2757]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec056ed-4c76-7c0a-82bc-3ddd3ae049d3
* Version Independent ID: f1fe3ac9-0314-47f4-24e7-134d2845426e
* Content: [Getting Started with Windows Debugging - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/getting-started-with-windows-debugging)
* Content Source: [windows-driver-docs-pr/debugger/getting-started-with-windows-debugging.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/getting-started-with-windows-debugging.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Alegriabaile - Thanks for this input. Windows debugging does assume a good degree of knowledge on Windows Internals and other topics. The Defrag Tools, episodes 13 through 29 video series from Channel 9, may be of help - https://channel9.msdn.com/Shows/Defrag-Tools. And the  the Windows Internals book. The other hands on lab topics may be of help as well. There is one for kernel and one for user mode -  https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/getting-started-with-windbg. I continue to think about what we can do to make Windows Debugging more accessible to a broader set of developers, thanks for this input.
