### ISSUE TITLE
AMLITraceEnable: Could not find NT!Kd_AMLI_Mask

### ISSUE THREAD

**Issue by p692584k** [MicrosoftDocs/windows-driver-docs#2759]
My symbol path is srv\*D:\symbol\*https://msdl.microsoft.com/download/symbols 
I have entered 
!sym noise
.reload /f acpi.sys
but when I entered !amli set spewon
![image](https://user-images.githubusercontent.com/42517679/114677202-a8c4cb00-9d3c-11eb-9192-1bb33bab3796.png)

How can I solve? 
Thanks.

**Comment by DOMARS** [comment]
@p692584k - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 

Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [OSR's windbg List](https://community.osr.com/categories/windbg). You can post your question there, and the community of developers usually give feedback fairly quickly. 

For example here is a previous thread on ACPI debugging.
https://community.osr.com/discussion/151522/running-acpi-methods-using-amli-run

A few ideas that you might consider. You may want to confirm that you can use the dt command to see the AMLI mask.

```
0: kd> dt nt!KD_AMLI_Mask
0xffffffff
```

For older versions of Windows checked builds were used, but that is a while back.

If you happen to be using an Intel JTAG connection, be aware of the limitations of that environment described here. 

https://software.intel.com/content/www/us/en/develop/documentation/debug-extensions-windbg-aml-user-guide/top/debugging-the-advanced-configuration-and-power-interface-acpi.html

Good luck with your ACPI debugging.
