### ISSUE TITLE
Syntax error in MITT ACPI code for device at end of TP3

### ISSUE THREAD

**Issue by jcbottorff-ampere** [MicrosoftDocs/windows-driver-docs#2761]
The device TP3 has an extra right curly bracket, so the sample I2C MITT ACPI code does not compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09394a3d-9e07-9591-2588-f2d9ca0934da
* Version Independent ID: 716cd7b5-3888-8afa-f2fc-01843afe91dd
* Content: [I2C controller tests in MITT - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/spb/run-mitt-tests-for-an-i2c-controller-)
* Content Source: [windows-driver-docs-pr/spb/run-mitt-tests-for-an-i2c-controller-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/spb/run-mitt-tests-for-an-i2c-controller-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by mhopkins-msft** [comment]
Hi @jcbottorff-ampere,

Thank you for reporting this. The topic has been updated.

 ~ *Mark*
