### ISSUE TITLE
Scope of various path variables when debugging remotely?

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/windows-driver-docs#2762]
When debugging remotely, does `.exepath` refer to the path on the host or test machine?

This question also comes up with `.srcpath` and `.sympath`. I assume they all refer to local (host) paths, but it's not specifically mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e082fc9-6325-815b-b798-5ccad651cf75
* Version Independent ID: ddf4f6c4-0f47-af1f-114e-efcdddeb7fa1
* Content: [.exepath (Set Executable Path) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-exepath--set-executable-path-)
* Content Source: [windows-driver-docs-pr/debugger/-exepath--set-executable-path-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-exepath--set-executable-path-.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mr-intj - Thanks for this issue on .exepath. I added information and a link to [Setting Symbol and Executable Image Paths in WinDbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-symbol-and-source-paths-in-windbg) to better clarify the usage of exe path.  

In general it is used for local (non remote) dump files that don't contain all of the information that the debugger needs to find module information. So there is a not a local and remote version of this path setting. I also added a link and some other information in the _NT_EXECUTABLE_IMAGE_PATH environment and related topics to try and better connect that information. 

Thanks again for this issue, and good luck with your Windows Debugging.
