### ISSUE TITLE
How to: View certificates with the MMC snap-in

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/windows-driver-docs#2766]
Does [How to: View certificates with the MMC snap-in](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in) apply? If so, should this link be added. I don't think it's WCF specific content. I'd be happy to add the link if it's appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba54b0a8-839a-d7c6-a2af-aeb299888153
* Version Independent ID: 34376596-4ba6-a425-0c3a-46a4457c76e8
* Content: [Certificate Stores - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/certificate-stores)
* Content Source: [windows-driver-docs-pr/install/certificate-stores.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/certificate-stores.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Good call, Rick, thanks for the suggestion.  I added the link in the commit above.

Appreciate your reaching out.
