### ISSUE TITLE
NET_ADAPTER_TX_CAPABILITIES_INIT_FOR_DMA does not match documentation

### ISSUE THREAD

**Issue by grimbeaver** [MicrosoftDocs/windows-driver-docs#2769]
The example code calls NET_ADAPTER_TX_CAPABILITIES_INIT_FOR_DMA with 4 parameters and the following page shows it only takes 3 parameters:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/netadapter/nf-netadapter-net_adapter_tx_capabilities_init_for_dma

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62ca2ce-1379-7407-17be-2b31183f5d41
* Version Independent ID: 1801c09e-8004-34aa-490f-6c594d5a52e5
* Content: [Network data buffer management - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/netcx/network-data-buffer-management)
* Content Source: [windows-driver-docs-pr/netcx/network-data-buffer-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/netcx/network-data-buffer-management.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @grimbeaver. Thanks very much for taking the time to let us know about this bug! The page is updated now.
