### ISSUE TITLE
Raw markdown on "Update a code sigining certificate"

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/windows-driver-docs#277]
Some raw markdown has slipped through half way down the page. Sorry, I'd submit a PR to fix myself, but I'm not familiar with what the formatting should be.

https://docs.microsoft.com/en-gb/windows-hardware/drivers/dashboard/update-a-code-signing-certificate
![image](https://user-images.githubusercontent.com/4837132/32788593-8eab1b2e-c951-11e7-842e-27b3479d0052.png)

**Comment by EliotSeattle** [comment]
Thanks for bringing this to our attention, Chris.

I made the fix and committed it to master. It will go live later today.

Eliot

**Comment by ChrisMaddock** [comment]
Great - thanks for the speedy fix!
