### ISSUE TITLE
Text references wrong API calls from example.

### ISSUE THREAD

**Issue by grimbeaver** [MicrosoftDocs/windows-driver-docs#2770]
The text and/or links reference the wrong API calls made by the example code.

NetAdapterCx requires the client driver to set the following capabilities:

* Data path capabilities. The driver calls NetAdapterSetDataPathCapabilities to set these capabilities. For more information, see Network data buffer management.

* Link layer capabilities. The driver calls ~~NetAdapterSetDataPathCapabilities~~ __NetAdapterSetLinkLayerCapabilities__ to set these capabilities.

* Link layer maximum transfer unit (MTU) size. The driver calls ~~NetAdapterSetDataPathCapabilities~~ __NetAdapterSetLinkLayerMtuSize__ to set the MTU size.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06dbac05-7cce-0362-4665-1ce20afdf09a
* Version Independent ID: 37b84f23-9f4e-b841-4af0-9d4ecbbcef57
* Content: [Device and adapter initialization - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/netcx/device-and-adapter-initialization)
* Content Source: [windows-driver-docs-pr/netcx/device-and-adapter-initialization.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/netcx/device-and-adapter-initialization.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
@grimbeaver These links are updated now. Thanks again!
