### ISSUE TITLE
"Full Packet Logging" and "Debug Mode"

### ISSUE THREAD

**Issue by XavierBoniface** [MicrosoftDocs/windows-driver-docs#2781]
### Context
There are a couple of buttons in the BTVS Window:
- Full Packet Logging
- Set or Extend Debug Mode

### Problem
It is neither explained in the documentation of btvs:
- what those buttons do
- if and how those options can be enabled from the command line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 984326a3-c5d3-ab9a-7e8f-f46f3c3ebeb6
* Version Independent ID: 648015d4-26ab-9338-5df6-e47a4e714ee5
* Content: [Microsoft Bluetooth Test Platform - BTVS - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bluetooth/testing-btp-tools-btvs)
* Content Source: [windows-driver-docs-pr/bluetooth/testing-BTP-tools-btvs.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bluetooth/testing-BTP-tools-btvs.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @XavierBoniface,

Thank you for reporting this. I've created a work item to document these buttons and added the work item to our backlog for future updates.

Thanks!
 ~ *Mark*
