### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by groovyf** [MicrosoftDocs/windows-driver-docs#2783]
[Enter feedback here]
Spelling mistake in the line: For specific registry locations of certicate stores, see System Store Locations.

Should be "certificate", not "certicate"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56db178-78e9-9564-e2d0-8d4dc5a0068d
* Version Independent ID: e31df79f-b30a-75f2-335c-637a9eeaca25
* Content: [Local Machine and Current User Certificate Stores - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/local-machine-and-current-user-certificate-stores)
* Content Source: [windows-driver-docs-pr/install/local-machine-and-current-user-certificate-stores.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/local-machine-and-current-user-certificate-stores.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by mhopkins-msft** [comment]
Hi @groovyf,

Thank you for reporting this typo. The topic has been updated. It will be republished later today.

 ~ *Mark*
