### ISSUE TITLE
HP Reverb G2 tracks but goes black

### ISSUE THREAD

**Issue by tini11** [MicrosoftDocs/windows-driver-docs#2788]
[Enter feedback here]
My HP Reverb G2 tracks all right - as is visible on the monitor - but the headset goes black after some use and headband adjusting, then it cannot be reset without disconnecting cables.
Can anybody plz help? But spare me the reinstall  Windows or drivers story ... my rig is up to date, powerful and working fine
Cheers Otto 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaf34fc4-46dc-9997-3a9b-8240df843fc0
* Version Independent ID: d0e1c003-1133-d811-5c71-47ce6a3c68f7
* Content: [USB Selective Suspend - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-selective-suspend)
* Content Source: [windows-driver-docs-pr/usbcon/usb-selective-suspend.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-selective-suspend.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @tini11,

I'm sorry for the troubles you’re going through. We create this documentation for companies that undertake driver development and deployment from a commercial perspective, and we’re staffed to solve issues with the supporting documentation. The topic you created the issue from is for commercial use in developing USB drivers. For consumer driver issues, your best bet is to look at the Microsoft Help topics that are on https://support.microsoft.com. After poking around a little, you may be able to directly find a solution or use the help agent on the site.
 
Sorry that I can’t offer you anything more specific than that. 

Best wishes,
 ~ *Mark*
