### ISSUE TITLE
IDK what is this!!

### ISSUE THREAD

**Issue by KanishkRanjan** [MicrosoftDocs/windows-driver-docs#2789]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4182137-b5a9-ad78-af6b-1687bac83338
* Version Independent ID: fc5712a9-c6be-110d-0c51-d925dddec901
* Content: [Creating a camera driver MFT for a UWP device app - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/creating-a-camera-driver-mft)
* Content Source: [windows-driver-docs-pr/devapps/creating-a-camera-driver-mft.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/creating-a-camera-driver-mft.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Closing as there is no feedback text in issue.
