### ISSUE TITLE
Invalid Link - Driver Development Page

### ISSUE THREAD

**Issue by computeronix** [MicrosoftDocs/windows-driver-docs#279]
On page: https://github.com/MicrosoftDocs/windows-driver-docs/edit/staging/windows-driver-docs-pr/what-s-new-in-driver-development.md

There is an invalid link: https://msdn.microsoft.com/en-us/library/windows/desktop/mt826481  

I am not entirely sure what the correct link should be

**Comment by tedhudek** [comment]
Assigning to @PageWriter-MSFT.  Verified that the link in line 318 fails:
An app can send requests to the controller driver by sending [PWM IOCTLs](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826481) requests.

**Comment by tedhudek** [comment]
Thanks @computeronix this is fixed now.
