### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windows-driver-docs#2801]
The Windows HLK, version 2004 link produces 
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

https://docs.microsoft.com/en-us/windows-hardware/test/hlk/

**Comment by EliotSeattle** [comment]
Hi @DSPatrick.

On the page https://docs.microsoft.com/en-us/windows-hardware/test/hlk/, the link to **Windows HLK, version 2004**, which points to [https://go.microsoft.com/fwlink/?linkid=2128655](https://go.microsoft.com/fwlink/?linkid=2128655), works for me, and it kicks off the download for the kit. 

Does that link still fail for you?

**Comment by DSPatrick** [comment]
No, it appears to be working now. Thank you

**Comment by EliotSeattle** [comment]
My work here is done!  :-)

Thanks!

**Comment by DSPatrick** [comment]
Yes, thank you!
