### ISSUE TITLE
Add example for managed code for parallel

### ISSUE THREAD

**Issue by akharit** [MicrosoftDocs/windows-driver-docs#2802]
Add example for managed code for parallel attribute. Current example is only for C++ code and I can't find if similar feature exists for C# code for taef.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97a717a1-cf17-ce5d-c755-efa7bb852b9e
* Version Independent ID: d15eeb94-fb83-dd3d-f6e3-7ffef59e5f8a
* Content: [Parallel - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/taef/parallel#markingtestsasparallelizable)
* Content Source: [windows-driver-docs-pr/taef/parallel.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/taef/parallel.md)
* Product: **windows-hardware**
* Technology: **taef**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@akharit - Thank you for this input on providing additional C# samples for TAEF. We use input like this to help direct our limited doc resources. In general, the properties such as Parallel, are set as shown in [Authoring Tests in C#](https://docs.microsoft.com/en-us/windows-hardware/drivers/taef/authoring-tests-in-c-). So a code snip could look like this in C#.  

```
       [TestMethod]
        [TestProperty("Parallel", "true")]
        public void ParallelTestOne()
        {
        	for (int i = 0; i < 10; i++)
        	{
        		Log.Comment(String.Format("Test One: {0}", i));
        		System.Threading.Thread.Sleep(250);
        	}
        }
```

Good luck with your TAEF C# development.
