### ISSUE TITLE
OpenAdater of Umd driver is never be called,unless disable OpenAdater10-12. (D3D9->EnumAdapter()  Only find MSBDD Adapter ） DXGI->EnumAdapter Can find New Wddm Adapter 

### ISSUE THREAD

**Issue by 404517981** [MicrosoftDocs/windows-driver-docs#2805]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7938c677-9152-8055-45e5-57ef0e9a6a9f
* Version Independent ID: db35793a-8f83-5d2d-9aff-f7102320f44a
* Content: [D3D Runtime Functions called by User-Mode Display Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/direct3d-runtime-functions-called-by-user-mode)
* Content Source: [windows-driver-docs-pr/display/direct3d-runtime-functions-called-by-user-mode.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/direct3d-runtime-functions-called-by-user-mode.md)
* Product: **windows-hardware**
* Technology: **display**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@404517981 , thanks for submitting an issue. We are uncertain what you want updated on the page. Can you provide me with the specifics of what documentation you think needs to be updated, or submit a PR? I'm going to close this issue for now - feel free to reopen it with your specific documentation request.
