### ISSUE TITLE
Information needed to interpret parameter 1

### ISSUE THREAD

**Issue by niderost** [MicrosoftDocs/windows-driver-docs#2806]
This page describes the WIN32K_CALLOUT_WATCHDOG_LIVEDUMP bug check 0x1A1 which is not an actual bug check but an identifier for a kernel live dump event. This pages also describes the parameter set, e.g., parameter 1 indicates the thread blocking prompt return from the Win32k callout.

This page lacks information on how to proceed with debugging this issue. I.e., how should one interpret parameter 1 as a thread. Is this a memory address where a data structure can be found that contains more information on the thread? If so, how should one interpret this data structure? And how can one capture (or where can one find) a memory (mini) dump containing this structure? Or should this number be decoded into a thread id that one then can look up? Or even something else?

Regards, Beat Nideröst

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 808b2103-81f8-3383-62fa-8b7c508d017e
* Version Independent ID: 0f62bdee-6756-5cfa-61fe-8a4cd800fcdd
* Content: [Bug Check 1A1 WIN32K_CALLOUT_WATCHDOG_LIVEDUMP - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x1a1--win32k-callout-watchdog-livedump)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x1a1--win32k-callout-watchdog-livedump.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x1a1--win32k-callout-watchdog-livedump.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@niderost - I added links for more information about working with threads and the thread information block (TEB) to this topic.  For general developer questions on working with bug checks, you may have success posting your question in the following forum, where other driver developers and Microsoft engineers can be found. 
•	[Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html)
Good luck with your debugging, and thanks for this input on the 1A1 live dump bug check code.
