### ISSUE TITLE
there is no Configuration Properties > Driver Install > Deployment 

### ISSUE THREAD

**Issue by xspeed1989** [MicrosoftDocs/windows-driver-docs#2807]
I have a KMDF driver project and a driver package in a solution, but  there is  no _Configuration Properties > Driver Install > Deployment_ 

My vs information:
![image](https://user-images.githubusercontent.com/5162926/119863249-f3488280-bf4b-11eb-8be6-d9744071f6d5.png)

**Comment by tedhudek** [comment]
Thanks @xspeed1989 - can you please provide a link for the doc page you are referencing?

**Comment by xspeed1989** [comment]
> Thanks @xspeed1989 - can you please provide a link for the doc page you are referencing?

@tedhudek 
doc page:https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver

**Comment by tedhudek** [comment]
@mhopkins-msft: looks like the above page needs at least one refreshed screenshot, similar to what you did for #2751

**Comment by mhopkins-msft** [comment]
Hi @xspeed1989

Thank you for reporting this. I've updated the screenshots and directions to match Visual Studio 2019. The article should be republished later today.

 ~ *Mark*
