### ISSUE TITLE
AudioProcessingObject setup class?

### ISSUE THREAD

**Issue by thxkiwi** [MicrosoftDocs/windows-driver-docs#2812]
Why is the AudioProcessingObject setup class excluded here? This is the setup class used by the sysvad example code and recommended in the documentation for implementing APOs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c231a8b4-24a8-c339-8660-52a2b9d28226
* Version Independent ID: 093b0d00-46ae-b685-760c-c04e10b27595
* Content: [System-Defined Device Setup Classes Available to Vendors - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/system-defined-device-setup-classes-available-to-vendors)
* Content Source: [windows-driver-docs-pr/install/system-defined-device-setup-classes-available-to-vendors.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/system-defined-device-setup-classes-available-to-vendors.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @thxkiwi thanks for the feedback.  I've added APOs to the page.  Appreciate the heads-up!
