### ISSUE TITLE
Componentized APOs; AddDevice or AddComponent?

### ISSUE THREAD

**Issue by thxkiwi** [MicrosoftDocs/windows-driver-docs#2813]
An inconsistency here between documentation and sample code. The documentation page uses examples of AddDevice in the device extension INF where as the sysvad example (to which the documentation refers developers) uses AddComponent. 

Which is the correct/preferred method for referring to AudioProcecssingObject components?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb10a40-2e9b-3808-20e2-86c829f94d17
* Version Independent ID: 1dfbc27f-f46f-21cf-bbe2-89010bdaf202
* Content: [Implementing Audio Processing Objects - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/implementing-audio-processing-objects#componentized-apo-installation)
* Content Source: [windows-driver-docs-pr/audio/implementing-audio-processing-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/implementing-audio-processing-objects.md)
* Product: **windows-hardware**
* Technology: **audio**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@thxkiwi - Thanks for seeing this in the APO docs. They docs were behind the changes made to the sample INF file to use AddComponent. I updated the docs INF snip to use AddComponent. Thanks for filing this issue to point this out, and good luck with your APO audio work.
