### ISSUE TITLE
Is !time really obsolete

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#2814]
.time does not seem to show the same information as !time. If the !time command is truly obsolete what is a good replacement to see unbiased interrupt time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe9974bc-013f-7bd5-6ea2-186629d7d019
* Version Independent ID: 5c27329f-1099-6578-d969-16d775406c01
* Content: [time - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-time)
* Content Source: [windows-driver-docs-pr/debugger/-time.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-time.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Shyamal-V - Thanks for your interest in our debugger docs. This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
  
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. 

If you have debugger product input, you can provide that using public github issues here: http://aka.ms/dexex 

Depending on your goals with tracking time, you may wish to to investigate enabling time stamps using .echotimestamps, !runaway, event logging or even user mode time travel tracing. Good luck with your debugging.
