### ISSUE TITLE
Microsoft SDK and Driver kit versions

### ISSUE THREAD

**Issue by radimscholly** [MicrosoftDocs/windows-driver-docs#2815]
Dear sir,
after creating the first steps I got mistakes in output window that compatible version of WDK is not available. I downloaded SDK and WDK today. I need asap to learn to write the drivers so will you help me? Before inst of WDK I got warning that SDK version is not compatible with WDK vers.
Thank you very much in advance, have a nice day!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287160ad-f2a5-789a-2d7d-ff336514c11e
* Version Independent ID: a138162d-2b80-725b-212b-277bae8f177d
* Content: [Write a Universal Windows driver (UMDF 2) based on a template - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-umdf-driver-based-on-a-template)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-umdf-driver-based-on-a-template.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-umdf-driver-based-on-a-template.md)
* Product: **windows-hardware**
* Technology: **gettingstarted**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks @radimscholly for letting us know about this issue. We updated the SDK download link on this page: [Download the Windows Driver Kit (WDK)](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
Please try the SDK download link under "Step 1.5 Install Windows SDK, version 2104 (Build 10.0.20348.0)".
I hope this solves your problem. Please open another issue if you have further trouble.
