### ISSUE TITLE
Bad sample descriptions

### ISSUE THREAD

**Issue by eezstreet** [MicrosoftDocs/windows-driver-docs#2817]
The descriptions on the samples are labelled wrong. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec53381-3da5-e974-770d-fcdc6eed087e
* Version Independent ID: 2187723f-31b4-032d-0ceb-1023fecfed13
* Content: [AVStream Samples - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/avstream-samples)
* Content Source: [windows-driver-docs-pr/stream/avstream-samples.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/stream/avstream-samples.md)
* Product: **windows-hardware**
* Technology: **stream**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@eezstreet, thanks for catching this error. The sample descriptions are now updated.
