### ISSUE TITLE
Broken feedback in "Supported smart card attributes"

### ISSUE THREAD

**Issue by martingalloar** [MicrosoftDocs/windows-driver-docs#2818]
Feedback overlay is broken and even not allowing to report feedback in the "Supported smart card attributes" page.

![image](https://user-images.githubusercontent.com/3941628/121113003-b00dcf80-c7e7-11eb-8852-ab06a4e87034.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88dce81-382f-e39b-aa65-f877a82dc879
* Version Independent ID: 5c8c3450-8ce5-4a86-7260-931cd939dd51
* Content: [Supported smart card attributes](https://docs.microsoft.com/en-us/windows-hardware/drivers/nfc/smart-card-attributes)
* Content Source: [windows-driver-docs-pr/nfc/smart-card-attributes.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/nfc/smart-card-attributes.md)
* Product: **windows-hardware**
* Technology: **nfc**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for letting us know @martingalloar.  This is fixed now.
