### ISSUE TITLE
Test Signing is required

### ISSUE THREAD

**Issue by neilsikka** [MicrosoftDocs/windows-driver-docs#2823]
Test Signing is required to be enabled in order for kdnet setup to work. I spent 12 hours trying to troubleshoot this. It should be documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e51b628-bb73-f32f-5a81-fefce12a4b49
* Version Independent ID: e07e2607-fd13-5517-510c-77bf717125c8
* Content: [Setting Up KDNET Network Kernel Debugging Automatically - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-automatically)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-automatically.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@neilsikka - Thanks for this input and passing on your experiences with the debugger. I confirmed that I can debug against a target  PC that doesn't have test signing enabled, so I don't think that is something we can add to the docs as a general statement. But it is possible that in a specific environment, enabling test signing may do something such as disable secure boot, that was required to allow the debugging connection to be allowed. And it would of course make sense that if you are trying to deploy a driver that is test signed, and debug that driver, test signing needs to be enabled. Enabling test signing for this purpose is covered in:  https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode- .  The general process for enabling debugger is to first disable secure boot and bitlocker using the setup menus in Windows, rebooting, and then running KDNET to set the rest of the BCDEdit values, and rebooting again to allow the debugger to connect. For further questions about working with enabling the debugger, I would look at [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your experiences there, and the community of developers usually give feedback fairly quickly. Good luck with your use of the debugger.
