### ISSUE TITLE
query the RNDIS multipacket  message encapsulate  strategy 

### ISSUE THREAD

**Issue by cyril1984** [MicrosoftDocs/windows-driver-docs#2826]
[Enter feedback here]
we made a test, WIN10 RNDIS could encapsulate 2 1500 packets into a single  multipacket  message, but it did not encapsulate 2 small packets to a single  multipacket  message, such as 40 bytes TCP ACK message.
Query:
1 where to get the detail information for  strategy of how WIN10 RNDIS make a  multipacket message 
2 could user make configuration for the multipacket message strategy ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4a24c9-6aff-4206-9798-823818fd9486
* Version Independent ID: 73d7f0ba-6bd1-810a-b0c5-9ef03fe61cba
* Content: [Multipacket Messages - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/multipacket-messages)
* Content Source: [windows-driver-docs-pr/network/multipacket-messages.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/multipacket-messages.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Closing duplicate issue.
