### ISSUE TITLE
Missing supported Windows SDK versions.

### ISSUE THREAD

**Issue by zhit-microsoft** [MicrosoftDocs/windows-driver-docs#2828]
It's not mentioned which versions of Windows supports PSA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d38003a1-8fba-7709-b130-57493ec9475b
* Version Independent ID: 67f50a05-3916-244c-9eb4-3a259e79bc6d
* Content: [Print support app design guide - Windows drivers](https://review.docs.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-design-guide?branch=master#see-also)
* Content Source: [windows-driver-docs-pr/devapps/print-support-app-design-guide.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/print-support-app-design-guide.md)
* Product: **windows-hardware**
* Technology: **devapps**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Added note to topic:
"Starting with the release of Windows 11 SDK (22000.1), Print Support Apps (PSA) are the recommended method of developing UWP apps for printers. To develop a Print Support App for your print device, download and install the Windows 11 SDK (22000.1)."
