### ISSUE TITLE
Screenshot shows "Lexmark" brand name.

### ISSUE THREAD

**Issue by zhit-microsoft** [MicrosoftDocs/windows-driver-docs#2829]
1. I don't think we have received CELA permissions to user their brand name.
2. We can easily rename the printer, to avoid branding issues.
3. We worked with many print partners during PSA development, it's unfair to the other partners.
4. Screenshot is low resolution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cce233db-310f-5eda-3f9a-676a6b7c60af
* Version Independent ID: 42521d92-86d5-1fc5-2049-8abd741db835
* Content: [Print support app association - Windows drivers](https://review.docs.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-association?branch=master)
* Content Source: [windows-driver-docs-pr/devapps/print-support-app-association.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/print-support-app-association.md)
* Product: **windows-hardware**
* Technology: **devapps**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Removed brand names from screenshots.
