### ISSUE TITLE
Terminalogy Incorrect/Awkward

### ISSUE THREAD

**Issue by zhit-microsoft** [MicrosoftDocs/windows-driver-docs#2830]
`Print Support Associated Printer - Physical IPP Printer that is linked to PSA.`
- "Physical IPP" should be removed.

`Associated PSA Printer - Every PSA is associated with a Physical IPP Printer.`
- This is entry is confusing and feels redundant with previous entries.

`Printer Preferences UI	Dialog where user can change the preferences related to a printer that would be applied at print time. Ex: orientation, paper size, color, print on both sides, etc.`
- Printer Preferences UI options sets the **defaults**, which is a critical detail that is missing.

`PrintDeviceCapabilities	XML document format for defining printer capabilities.`
- Should have a link to existing documentation https://docs.microsoft.com/en-us/windows-hardware/drivers/print/print-ticket-and-print-capabilities-technologies

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d38003a1-8fba-7709-b130-57493ec9475b
* Version Independent ID: 67f50a05-3916-244c-9eb4-3a259e79bc6d
* Content: [Print support app design guide - Windows drivers](https://review.docs.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-design-guide?branch=master)
* Content Source: [windows-driver-docs-pr/devapps/print-support-app-design-guide.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/print-support-app-design-guide.md)
* Product: **windows-hardware**
* Technology: **devapps**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@zhit-microsoft, the terminology has been updated per your feedback.

https://github.com/MicrosoftDocs/windows-driver-docs-pr/pull/1176
