### ISSUE TITLE
PSA is available, but there is no mention of it on this UWP device app page.

### ISSUE THREAD

**Issue by zhit-microsoft** [MicrosoftDocs/windows-driver-docs#2831]
Now that there is multiple UWP app that can be developed for printer devices. This page should clarify what the differences are and link to appropriate documentation. We should be promoting PSA over workflow.

- Print support app: https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-design-guide
- Workflow App: https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/print-workflow-customize#:~:text=Your%20workflow%20app%20is%20associated%20with%20a%20printer,corresponding%20WSDA%20steps%20for%20creating%20the%20metadata%20association.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41269d44-99b3-f290-42f8-b32b3ef26b47
* Version Independent ID: 887adda4-a8ea-3c8c-4458-d4735cb3f4a7
* Content: [UWP device apps for printers - Windows drivers](https://review.docs.microsoft.com/en-us/windows-hardware/drivers/devapps/uwp-device-apps-for-printers?branch=master)
* Content Source: [windows-driver-docs-pr/devapps/uwp-device-apps-for-printers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/uwp-device-apps-for-printers.md)
* Product: **windows-hardware**
* Technology: **devapps**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Added a note to inform print device app developers that with the release of the Windows 11 SDK (22000.1), Print Support Apps (PSA) are the recommended method of developing UWP apps for printers.
