### ISSUE TITLE
Add information on what the "Attached Process" parameter means

### ISSUE THREAD

**Issue by niderost** [MicrosoftDocs/windows-driver-docs#2840]
Next to information on the owning process, !thread also displays information on the "attached process". What is the attached process? Is this the debugger? Please add information on this to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dffb15e-1398-c43f-9c6d-4da7b0f6d4f2
* Version Independent ID: 15db6baa-e051-546b-cadc-e3ceaaed1546
* Content: [thread - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-thread)
* Content Source: [windows-driver-docs-pr/debugger/-thread.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-thread.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@niderost - I added a link to some additional information to threads and process in this topic. The concept of attaching to a process is defined on page 310 of the referenced  "Windows Internals" book, version 7.  General information on threads is the topic for all of chapter 4. The example of KeStackAttachProcess, that @KalleOlaviNiemitalo provided (Thanks!), is a specific example of this type of cross process memory access.
