### ISSUE TITLE
This page hasn't been updated since '17 and we have changed how OS deals with signing

### ISSUE THREAD

**Issue by Ron-Hu** [MicrosoftDocs/windows-driver-docs#2842]
[Enter feedback here]
We have changed how the OS loads drivers and we should add Credential Guard/DMA Guard/HVCI and any others and how it changes what we do to driver and the cab file on return to the CX

We MUST spell out in baby steps what EXACTLY needs to be done to prepare a driver package for submission via DEV Portal.

I am getting many requests from CX confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ba4c28c-fc37-3f02-e5a1-c52e0f3ed915
* Version Independent ID: 73a53aa7-46db-3ed1-0ecd-022eece214b8
* Content: [Get drivers signed by Microsoft for multiple Windows versions - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions)
* Content Source: [windows-driver-docs-pr/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-drivers-signed-by-microsoft-for-multiple-windows-versions.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @Ron-Hu 

Thank you for submitting this feedback. I'm closing this issue and contacting you directly over email. We can work on this offline.

Thanks!
 ~ *Mark*
