### ISSUE TITLE
Please add Read feature in MicrosoftDocs

### ISSUE THREAD

**Issue by turekhe** [MicrosoftDocs/windows-driver-docs#2843]
New feature request on Microsoft Docs. Please redirect it to right path.
Docs are very good but then I have to read it and it consumes all my attention. Let's add Read feature which will read that doc for user.

Thank you,
Tushar Rekhe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68be4f3a-a792-45da-3c43-533aed0f89b1
* Version Independent ID: 2cc4d72a-3053-6f06-8613-61e7a144e094
* Content: [Debugging Tools for Windows (WinDbg, KD, CDB, NTSD) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/)
* Content Source: [windows-driver-docs-pr/debugger/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/index.md)
* Product: **windows-hardware**
* Technology: **windows-devices**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@turekhe - Thanks for this input on the docs. If I'm following, you may be suggesting a narration feature, where the topic is read out loud.  If that is the case, we do our best to create content that works with existing screen readers. For example for Windows, the narrator feature can be turned on using the Windows Key + CTRL + ENTER . See this link for more information --> https://support.microsoft.com/en-us/windows/chapter-1-introducing-narrator-7fe8fd72-541f-4536-7658-bfc37ddaf9c6 
Thanks for the interest in our documentation.
