### ISSUE TITLE
Mobile Broadband Class Driver Logs: Event Trace Log Tracing for win10?

### ISSUE THREAD

**Issue by ksh1ng** [MicrosoftDocs/windows-driver-docs#2847]
[Enter feedback here]
Is there any updated document about Mobile Broadband Class Driver Logs: Event Trace Log Tracing for win10??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa951726-0a27-6ef7-aa68-e46fd8af22bc
* Version Independent ID: 4de07f98-bb72-e234-41bd-a4c25527f600
* Content: [Mobile Broadband Class Driver Logs Event Trace Log Tracing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/mobile-broadband-class-driver-logs--event-trace-log-tracing#feedback)
* Content Source: [windows-driver-docs-pr/network/mobile-broadband-class-driver-logs--event-trace-log-tracing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/mobile-broadband-class-driver-logs--event-trace-log-tracing.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks @ksh1ng for letting us know about this issue. The instructions on [Mobile Broadband Class Driver Logs Event Trace Log Tracing](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/mobile-broadband-class-driver-logs--event-trace-log-tracing) will also work for Windows 10. However, we will be taking this page down soon and you can find instructions on [MobileBroadband Collecting Logs](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/mb-collecting-logs). Thanks again.
