### ISSUE TITLE
Command window occluded

### ISSUE THREAD

**Issue by rcurry2** [MicrosoftDocs/windows-driver-docs#2849]
The playback controls for the video window occlude the command prompt where all the commands are being typed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b231b5a-b4d3-12ee-4682-e66806dcafa6
* Version Independent ID: 70227f78-0710-18d8-4b68-61b1143cb625
* Content: [Video Debugging your driver with WDF source code - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/video--debugging-your-driver-with-wdf-source-code)
* Content Source: [windows-driver-docs-pr/wdf/video--debugging-your-driver-with-wdf-source-code.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/video--debugging-your-driver-with-wdf-source-code.md)
* Product: **windows-hardware**
* Technology: **wdf**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for watching @rcurry2!  So for this one I'd recommend using the button in the lower right of the video window to make the image full screen.  I just tested it out and with full screen, I could see the entire frame, including the commands being typed.

If that doesn't work for you, please reopen and tell me what browser you're using.  I was using (Chromium based) Edge.

Again, thanks for reaching out!
