### ISSUE TITLE
Missing entries for NUp and JobPasscode features

### ISSUE THREAD

**Issue by zhit-microsoft** [MicrosoftDocs/windows-driver-docs#2851]
Missing entries for NUp and JobPasscode features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1862538-d703-0205-a6b7-ba573cdda406
* Version Independent ID: d0137e1a-80b1-ddfc-3a52-447832ab629b
* Content: [Standard Features - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/standard-features)
* Content Source: [windows-driver-docs-pr/print/standard-features.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/standard-features.md)
* Product: **windows-hardware**
* Technology: **print**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Topic has been updated per PR 2852. Closing issue as completed.
