### ISSUE TITLE
Link to forwarding extensions page is wrong

### ISSUE THREAD

**Issue by ophirharpazg** [MicrosoftDocs/windows-driver-docs#2858]
The link to the forwarding extensions page should be fixed to [this](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/forwarding-extensions).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f72ca42-901d-53b2-cd43-7a78e2e2c15b
* Version Independent ID: 67589b4f-7bed-a55f-45bc-ca4cb3dbdf0b
* Content: [Overview of the Hyper-V Extensible Switch - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/overview-of-the-hyper-v-extensible-switch)
* Content Source: [windows-driver-docs-pr/network/overview-of-the-hyper-v-extensible-switch.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/overview-of-the-hyper-v-extensible-switch.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks for letting us know @ophirharpazg! This link is now fixed.
