### ISSUE TITLE
Visual Studio 22 Preview

### ISSUE THREAD

**Issue by MrDimarik** [MicrosoftDocs/windows-driver-docs#2861]
Where can i get WDK for win 11 which works with VS 22?

**Comment by tedhudek** [comment]
Hi @MrDimarik thanks for the question.  We don't currently support using the WDK with Visual Studio 2022 Preview. You can always check https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk for the latest recommended configuration - right now that's using Visual Studio 2019.
