### ISSUE TITLE
Windows 11 WDK runtime requirements documentation

### ISSUE THREAD

**Issue by shaibran** [MicrosoftDocs/windows-driver-docs#2863]
in section: **Windows 11 WDK runtime requirements** there exists a table where Windows Server 2022 appears in the same table entry as Windows Server 2019, Windows Server 2016, which are the server OS versions compatible with Windows 10 Client OS.
Is this correct? I was under the impression that Windows Server 2022 is the server OS compatible with Windows 11 Client OS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#feedback)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **windows-drivers-conceptual-docs**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for pointing this out @shaibran -- I've corrected this on the doc page.  Appreciate the heads-up!
