### ISSUE TITLE
Please support a 10_ARM64 OS parameter

### ISSUE THREAD

**Issue by andyraf** [MicrosoftDocs/windows-driver-docs#2866]
It's already hard getting people to port their code to ARM64, and I hit an issue that makes it incrementally harder.
I was rebuilding some open source code in VS to ARM64, and the only issue I hit was that they had a post-build step to run inf2cat that formatted the OS parameter as "10_$(DDKPlatform)". On X64 platforms this resolved to 10_X64, which inf2cat supports, but on ARM64 it generated an error that took me an hour to hunt down because 10_ARM64 is not supported by inf2cat. Once I figured it out, the fix was simply to change the param to "10_VB_$(DDKPlatform)", but we should try to eliminate bits of friction like this by adding support for a 10_ARM64 os param to inf2cat. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0afbc04b-349a-57ed-eeb0-3d2cd28e359c
* Version Independent ID: de61f684-31d7-2de5-d66c-a3319f5198d9
* Content: [Inf2Cat - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/inf2cat)
* Content Source: [windows-driver-docs-pr/devtest/inf2cat.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/inf2cat.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@andyraf - Thanks for sharing what you are hitting with the use of Inf2Cat. I know many of the sample driver VS projects have In2Cat as a post build event, so this would seem like a common thing to run into. I followed up offline in email on some ideas on how to provide this input to the dev team. Thanks again for passing on what you are seeing with the ARM64 driver dev workflow.
