### ISSUE TITLE
where is ecmangen.exe?

### ISSUE THREAD

**Issue by limulidae** [MicrosoftDocs/windows-driver-docs#2876]
[Enter feedback here]
ecmangen.exe is removed in newer sdk.
What is the replacement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c644605-a088-2559-f11f-5afa168e1e20
* Version Independent ID: e19385cd-b7cf-58a9-6276-0ebd4596e185
* Content: [Index of Windows Driver Kit Tools - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/index-of-windows-driver-kit-tools)
* Content Source: [windows-driver-docs-pr/devtest/index-of-windows-driver-kit-tools.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/index-of-windows-driver-kit-tools.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@limulidae - Thanks for this PR and pointing out that ECManGen is no longer in the kits. I have removed the reference to this utility in the list of included tools. According to this blog entry, it sounds like the recommendation is to download an older kit to acquire the utility: 
https://blogs.windows.com/windowsdeveloper/2017/08/22/windows-10-sdk-preview-build-16267-mobile-emulator-build-15240-released/ 

This forum post provides more information on downloading a version of the SDK that contains this utility.  
https://social.msdn.microsoft.com/Forums/en-US/1666c0ef-fc03-4dbc-9068-df98e1e886b9/where-can-i-download-ecmangenexe
