### ISSUE TITLE
The information in this page is outdated. Please update the information.

### ISSUE THREAD

**Issue by rbhard1x** [MicrosoftDocs/windows-driver-docs#2877]
The information in this page is outdated. Please update the information.

**Comment by rbhard1x** [comment]
The information in this page is outdated. Please update the information.

**Comment by tedhudek** [comment]
Hi @rbhard1x - what page are you talking about and what information is missing?

**Comment by tedhudek** [comment]
Closing out due to no actionable info. Please re-open with specifics if still needed
