### ISSUE TITLE
SR-IOV operating system support

### ISSUE THREAD

**Issue by MrDavid949** [MicrosoftDocs/windows-driver-docs#2884]
[Enter feedback here]
Hi, can you please comment on what operating systems support SR-IOV?  Server 2012, 2016, Windows 10 Pro, Windows 10 Workstation...

Without the OS support informaiton I'm not sure when I need to have the needs=PciSriovSupported in my device INF file.

thank
you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a6c5118-4fc7-27f2-99ce-28561ef3d465
* Version Independent ID: 2fc6c35b-22c3-b75e-850b-cb94d7efe93a
* Content: [Single Root I/O Virtualization (SR-IOV) Interface - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/single-root-i-o-virtualization--sr-iov--interface)
* Content Source: [windows-driver-docs-pr/network/single-root-i-o-virtualization--sr-iov--interface.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/single-root-i-o-virtualization--sr-iov--interface.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @MrDavid949, please see https://docs.microsoft.com/en-us/windows-hardware/drivers/network/single-root-i-o-virtualization--sr-iov-. [Introduction to Single Root I/O Virtualization (SR-IOV)](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/single-root-i-o-virtualization--sr-iov-).  Starting with NDIS 6.30, the SR-IOV interface supports Microsoft Hyper-V performance improvements for virtualized networks on Windows Server 2012 and later versions of Windows Server.
