### ISSUE TITLE
*RssOnHostVPorts default - Test-NetHLK expects default to be enable

### ISSUE THREAD

**Issue by sandilyabhagi** [MicrosoftDocs/windows-driver-docs#2885]
[Enter feedback here]
Test-NetHLK expects *RssOnHostVPorts default to be enable. The documentation needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a141ea8d-027c-d1cb-5c70-72e9d79b4586
* Version Independent ID: 86f3b413-31ef-346f-edcb-0b379ac6d87c
* Content: [Standardized INF keywords for VMMQ - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/standardized-inf-keywords-for-vmmq#feedback)
* Content Source: [windows-driver-docs-pr/network/standardized-inf-keywords-for-vmmq.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/standardized-inf-keywords-for-vmmq.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks @sandilyabhagi for opening this issue. This value is now updated on the site.
