### ISSUE TITLE
While  in the Gradual Rollout phase, how to identify the failure ? Could you shared the more info about TDR or BSOD to IHV(such as intel/ Nvidia/AMD)?  W/O duplicate steps/ evt logs/ dmp files, it's difficult to analysis the failure

### ISSUE THREAD

**Issue by JK-Ke** [MicrosoftDocs/windows-driver-docs#2886]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e8e797-c5cc-2d97-6d3e-9e5bba34d814
* Version Independent ID: dc58305e-0a52-bb9f-5131-38e0b0113d76
* Content: [Gradual rollout - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/gradual-rollout)
* Content Source: [windows-driver-docs-pr/dashboard/gradual-rollout.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/gradual-rollout.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **webreidi**

**Comment by mhopkins-msft** [comment]
Hi  @JK-Ke

For ideas about how to troubleshoot your issues, you could post your questions in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive. 
- [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) 
- [OSR NTDEV forum](https://community.osr.com/categories/ntdev)

For specific questions, Hardware Dev Center Support can investigate. To contact support and open a Hardware Dev Center support case for investigation, **first**, sign into your hardware dev center account, and **then** go to [https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq](https://docs.microsoft.com/windows-hardware/drivers/dashboard/hardware-dashboard-faq).

Find: 
 
**How do I contact Partner Center Support?**
If you are having problems accessing the Dashboard or need Dashboard Support please open a support ticket here: [https://developer.microsoft.com/windows/support](https://developer.microsoft.com/windows/support). 

Once there, select **Contact us**, **Dashboard issue**, and then **Hardware submissions & signing (all OS version)** from the dropdown menu.

Hopes this helps.
 ~ *Mark*
