### ISSUE TITLE
NumRSSQueues default is expected as 16 in Test-NetHLK

### ISSUE THREAD

**Issue by sandilyabhagi** [MicrosoftDocs/windows-driver-docs#2887]
The Test-NetHLK is expecting NumRSSQueues default value as 16 and not device-specific.
https://github.com/microsoft/Test-NetHLK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b99aa941-27c4-c5cd-386c-fa1f64ab828f
* Version Independent ID: 23ccb092-56e8-8165-65f4-25bd2e3a983d
* Content: [Standardized INF Keywords for RSS - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/standardized-inf-keywords-for-rss)
* Content Source: [windows-driver-docs-pr/network/standardized-inf-keywords-for-rss.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/standardized-inf-keywords-for-rss.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks @sandilyabhagi. This value is now updated on the site.
