### ISSUE TITLE
Cross-Certificate List

### ISSUE THREAD

**Issue by Tarjei99** [MicrosoftDocs/windows-driver-docs#2888]
The "Cross-Certificate List" is out of date. The public keys in that section are all invalid now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04c19d51-a948-b3ff-65c2-d8c54291b42f
* Version Independent ID: b5654182-fdcb-72c0-e5ae-536992731e98
* Content: [Cross-Certificates for Kernel Mode Code Signing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/cross-certificates-for-kernel-mode-code-signing)
* Content Source: [windows-driver-docs-pr/install/cross-certificates-for-kernel-mode-code-signing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/cross-certificates-for-kernel-mode-code-signing.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @Tarjei99, I've removed the section that listed the expired certs.
