### ISSUE TITLE
Bug Check 0x3D: INTERRUPT_EXCEPTION_NOT_HANDLED documentation does not contain a description of the bug check code.

### ISSUE THREAD

**Issue by jdallma** [MicrosoftDocs/windows-driver-docs#2889]
This page does not provide useful information for determining the cause or circumstances of the crash beyond the name of the bug check code and recommendation to run !analyze.

A line or two similar to one of the following may help clarify the context of the crash so developers do not need to assume based on the name of the bug check code.  Note, I do not know if these descriptions are accurate, since I am just assuming based on the name of the bug check code.

"An exception occurred while handling an interrupt."  "An exception occurred at IRQL > DISPATCH_LEVEL."

It would also be useful to include steps to determine what type of exception occurred, if different than the suggestion to run !analyze.

I see Bug Check 0x3C, 0x42, and 0x43 also have the same "This bug check appears very infrequently." message in their documentation rather than a description of the issue that occurred, and there are likely others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c4748a-e828-a6ed-94ea-f25e877531a5
* Version Independent ID: 46d7a626-fef1-02e9-9dc7-a47f78ef536b
* Content: [Bug Check 0x3D INTERRUPT_EXCEPTION_NOT_HANDLED - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x3d--interrupt-exception-not-handled)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x3d--interrupt-exception-not-handled.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x3d--interrupt-exception-not-handled.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@jdallma - Thank you for pointing out the need for a description for this bug check. And although it is infrequent it does seem to be occurring with the current versions of Windows.  So I removed the note describing this bug check as infrequent. I have contacted the dev team to work with them to properly describe this bug check. 

If the dump contains enough information, !analyze will include the exception record.

```
EXCEPTION_RECORD:  fffff80510e789b8 -- (.exr 0xfffff80510e789b8)
ExceptionAddress: fffff8050b0cac3d
   ExceptionCode: c000001d (Illegal instruction)
  ExceptionFlags: 00000000
NumberParameters: 0
```

The excr contains the exception code, in this example "Illegal instruction".

Interrupt handling involves software trying to handle unexpected hardware behavior, so the moment of failure that the software sees can be incomplete or possibly corrupted, so they can be complex to debug. Looking at the state of the interrupt tables using the [!idt](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-idt) extension may be helpful to at least see who is working with interrupts at the point of failure if that area of memory is available in the dump.

For general information about interrupts, see [Introduction to Interrupt Service Routines]( https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-interrupt-service-routines).

Good luck in finding the source of this failure, and thanks for your interest in the bug check docs.
