### ISSUE TITLE
The Sample Code on This Page... HAS to Go

### ISSUE THREAD

**Issue by PeterGV** [MicrosoftDocs/windows-driver-docs#2894]
Hi Ted,

While I applaud the desire to provide a code sample that walks through and locates a capability, this particular code sample is... how should I best say this... "not the best".  Actually, OK: it's horrendous.

I would be happy to "donate" some sample code that's nicely formatted and that works, for a function usable from a WDF driver, that locates a given capability by ID (with the ID to locate passed-in as a parameter).  That could replace the example on this page.

Formatted, with error handling, and DbgPrints for errors... the function is about 100 lines long.

If you want it, I'll be happy to provide it.  If not, I won't be offended, I promise you.  But either way, you should really take this example of the page.  ;-)

Best,

Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0a490c-5642-3863-596f-a0e5d7ba9644
* Version Independent ID: f06461a3-83eb-7d2e-e3e7-dfcfd2e69fa8
* Content: [Accessing PCI Device Configuration Space - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/pci/accessing-pci-device-configuration-space)
* Content Source: [windows-driver-docs-pr/pci/accessing-pci-device-configuration-space.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/pci/accessing-pci-device-configuration-space.md)
* Product: **windows-hardware**
* Technology: **pci**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hey Peter, appreciate the suggestion.  I've removed the snippet that was on there - please feel free to open a PR with your suggested change.  Happy to take a look.
