### ISSUE TITLE
How about a link for getting this driver which is missing from my windows 10 installation...

### ISSUE THREAD

**Issue by got879** [MicrosoftDocs/windows-driver-docs#2899]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a741c2c3-ee16-97ea-94b0-10f0df8377b9
* Version Independent ID: b8acde13-4a58-4c39-7525-e175257a44de
* Content: [Overview of Remote NDIS (RNDIS) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/overview-of-remote-ndis--rndis-)
* Content Source: [windows-driver-docs-pr/network/overview-of-remote-ndis--rndis-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/overview-of-remote-ndis--rndis-.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks for opening this issue, @got879. Please see [Introduction to Remote NDIS (RNDIS)](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/remote-ndis--rndis-2) for more info on getting the driver. Please open a new issue if you have further questions. Thank you.
