### ISSUE TITLE
v.123

### ISSUE THREAD

**Issue by fai814** [MicrosoftDocs/windows-driver-docs#2901]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43093a96-c8de-3746-96cb-e7036c586540
* Version Independent ID: f8d2c11a-8b4d-9613-b706-0bc975494512
* Content: [INF BitReg Directive - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-bitreg-directive)
* Content Source: [windows-driver-docs-pr/install/inf-bitreg-directive.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-bitreg-directive.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Closing out due to lack of feedback, please reopen as needed
