### ISSUE TITLE
How to use GPIO Driver on windows 10

### ISSUE THREAD

**Issue by huguesdup** [MicrosoftDocs/windows-driver-docs#2902]
Hi folks,

I read the "Connecting a KMDF Driver to GPIO I/O Pins" article on the Microsoft's doc page, but I can't really apply it to my case since I don't understand the example of code given and can't have it to work on my side... I was wondering if I could explain my situation here and get some help please.

So I'm working on an Asrock SBC-230J board and I installed the Intel Serial IO driver for the board. I want to control the GPIO pins of the board with windows 10.
Here is the link to the board: https://www.asrockind.com/en-gb/SBC-230J

However, I don't know how to connect the driver to the GPIO ports of the board because I don't understand the code given in the article.

Do you guys think what I want to do is possible?

Thanks in advance for your help!

**Comment by tedhudek** [comment]
Hi @huguesdup,

Appreciate the feedback, and sorry to hear you're having trouble running this code on the Asrock board.

I'm actually not familiar with that hardware at all and think your best bet is to try posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [windows-hardware-wdk](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk.html)
* [OSR's NTDEV forum](https://community.osr.com/categories/ntdev)

Thanks for reaching out and best of luck with this issue.
