### ISSUE TITLE
Adding note regarding signed binaries within a submission package

### ISSUE THREAD

**Issue by jesweare** [MicrosoftDocs/windows-driver-docs#2903]
This page includes a recommendation to the likes of below:

>We strongly encourage you to include public driver symbols as part your HLK package. See Public Symbols and Private Symbols to learn how to create public symbols. See Step 8: Create a submission package to learn how to include symbols with your package. Note that any .pdb files in your submission will be removed before being published.

A similar passage can be seen in [Step 8: Create a submission package](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/getstarted/step-8-create-a-submission-package?source=docs).

Given the above, I want to suggest adding a similar type of note, regarding signatures on binaries included in the driver submission package.
Specifically, **a recommendation to remove code signatures, added to binaries only for testing purposes,** would help users avoid unexpected behavior in driver packages that have cleared the submission process.

Binaries that are under test, in most cases, would have a Code Signature embedded for them to install and load properly. However, such signatures are in most cases "test signatures". [Test Signing](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/test-signing) methods that are available do not meet production-level signature requirements (especially for Kernel-mode Code Signing policies).
Such binary files, included in a package submitted to the Hardware Dashboard, receive a WHQL signature upon submission completion. The new signature is "added"; it does not overwrite pre-existing signatures. 

If the user has not removed any pre-existing signatures before submission, the binary may likely end up with multiple embedded signatures in the form below.

- Primary signature: added by user, for testing purposes
- Secondary signature: added by Hardware Dashboard, as WHQL signature

More recent Windows OS Versions have the ability to recognize multiple Code Signatures embedded in a binary/PE file, and follow through with verification steps accordingly.
However, some older OSes (including those that are still under the support scope as of now) may not have the ability to take appropriate Code Signature verification steps.

As a result, even though the driver has a proper WHQL signature, Windows may fail to recognize it, and cause end users to encounter driver install-time (or load-time) problems.

[Signtool.exe](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe) has a `remove` command option that allows removal of existing signatures embedded in a binary. Advice of taking such an approach before submission would help users understand the appropriate action they can take, to provide a better end user experience.

```
>signtool.exe /?
Usage: signtool <command> [options]

  Valid commands:
    sign       --  Sign files using an embedded signature.
    timestamp  --  Timestamp previously-signed files.
    verify     --  Verify embedded or catalog signatures.
    catdb      --  Modify a catalog database.
    remove     --  Remove embedded signature(s) or reduce the size of an
                   embedded signed file.

For help on a specific command, enter "signtool <command> /?"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7135005c-e7aa-19a2-7cfe-5003696da66a
* Version Independent ID: dba3259f-cb98-c2ab-9c56-860a731310d9
* Content: [Hardware submissions - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-certification-submissions#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/hardware-certification-submissions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-certification-submissions.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @jesweare 

Thank you for this feedback. I've created a work item to add your suggestion to an update of this page.

Thanks!
 ~ *Mark*
