### ISSUE TITLE
Stop optional NDIS filter driver will lost network connection in window 2019

### ISSUE THREAD

**Issue by descartes123** [MicrosoftDocs/windows-driver-docs#2904]
Dear expert, 

My product met a problem about ndis driver, that is, we have a NDIS filter driver and it is installed as optional filter driver by setting **FilterRunType** entry to **0x00000002** in inf and following the official guide in msdn: https://docs.microsoft.com/en-us/windows-hardware/drivers/network/configuring-an-inf-file-for-a-modifying-filter-driver .
When stop the driver by sc stop <drivername> in window 2012 and previous OS, the network connection won't lost, but recently our product upgraded to window 2019, it will lost connection when stop it.
I didn't see msdn mention any difference about it for window 2019, I only found an article https://docs.microsoft.com/en-us/troubleshoot/windows-hardware/drivers/lwf-causse-90-second-delay, which said it will cause delay on network, but it didn't act as that in our window 2019, it just lost connection.

Do you know why this happened? or is there any way to not lost connection when stop the optional filter driver?

Thank in advance.

**Comment by tedhudek** [comment]
Hi @descartes123, 

Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive. Best of luck with this issue.

* [windows-hardware-wdk](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk.html)
* [OSR's NTDEV forum](https://community.osr.com/categories/ntdev)
