### ISSUE TITLE
Driver signing

### ISSUE THREAD

**Issue by bsbaixo** [MicrosoftDocs/windows-driver-docs#2905]
Hi we have acquired a new EV code signing certificate from Sectigo.
It appears the signing is being done correctly due to lack of errors and file properties being populated with our company info.
While trying to use/restart the PC it just hangs.
Sectigo told us to open an account on Microsoft Dev site, which I did, and upload the file to the site or download a cert from the MS site or something. It gets a little foggy from there. I couldn't find anything relative to our situation and the step by step I found here, for instance -> https://docs.microsoft.com/en-us/windows-hardware/drivers/install/signing-drivers-for-public-release--windows-vista-and-later- 
was all authored in 2017 while this new change is apparently just months old.

A step by step would be a real help in getting us back up and running.

Thanks a lot.

**Comment by tedhudek** [comment]
Hi @bsbaixo,

Thanks for reaching out.  Here are a few links that might be helpful:

- https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/register-for-the-hardware-program
- https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/create-a-new-hardware-submission

The "dashboard" table of contents for the above links has a lot of content about submitting your driver on Partner Center.

There is also this FAQ-style page with some caveats:

- https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates

All of these have been updated pretty recently.

If you still have trouble after that, I recommend posting in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [windows-hardware-wdk](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk.html)
* [OSR's NTDEV forum](https://community.osr.com/categories/ntdev)

Best of luck with this issue.
