### ISSUE TITLE
Thanks for the great article! we were trying to use this command to set MaxProcessNumber as 16, but the RssProcessorArray picks 26 RSS processors. Can I know why is there such inconsistency, shouldnt it set to 16 RSSProcessorArray? IS there some other way to set it to 16?

### ISSUE THREAD

**Issue by priypa** [MicrosoftDocs/windows-driver-docs#2906]
Thanks for the great article! we were trying to use this command to set MaxProcessNumber as 16, but the RssProcessorArray picks 26 RSS processors. Can I know why is there such inconsistency, shouldnt it set to 16 RSSProcessorArray? IS there some other way to set it to 16?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c296980a-96f4-7ddf-fa83-09a103409dcd
* Version Independent ID: 7cb812bb-3210-8b76-27c6-b97a548d0dc8
* Content: [Setting the Number of RSS Processors - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/setting-the-number-of-rss-processors)
* Content Source: [windows-driver-docs-pr/network/setting-the-number-of-rss-processors.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/setting-the-number-of-rss-processors.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @priypa, 
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation. 
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive. Best of luck with this issue.
* [windows-hardware-wdk](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk.html)
* [OSR's NTDEV forum](https://community.osr.com/categories/ntdev)
