### ISSUE TITLE
The link on 'power management support routines' does not lead to a right page for power management.

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs#2908]
The link on 'power management support routines' does not lead to a right page for power management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76b39533-ba11-2347-01a5-1d328c9c3a11
* Version Independent ID: 276a63f3-7a1b-261e-84d6-7281da7d8ab0
* Content: [System-Wide Overview of Power Management - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/system-wide-overview-of-power-management)
* Content Source: [windows-driver-docs-pr/kernel/system-wide-overview-of-power-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/system-wide-overview-of-power-management.md)
* Product: **windows-hardware**
* Technology: **kernel**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Fixed!  Thanks for letting us know @guliteb
