### ISSUE TITLE
usbd_queryusbcapability link is broken

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#2911]
The right link seems to be https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/usbdlib/nf-usbdlib-usbd_queryusbcapability. Existing link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf6d9f0-5535-1289-819f-e6d5dcf23259
* Version Independent ID: baf8f59b-1ec3-54ce-a419-8e4de05c4435
* Content: [How to send chained MDLs - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/how-to-send-chained-mdls)
* Content Source: [windows-driver-docs-pr/usbcon/how-to-send-chained-mdls.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/how-to-send-chained-mdls.md)
* Product: **windows-hardware**
* Technology: **usbcon**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @Shyamal-V,

Thank you for letting me know about this. I've updated the links.

 ~ *Mark*
