### ISSUE TITLE
What's the version identifier of the Windows Server 2019?

### ISSUE THREAD

**Issue by guofengtd** [MicrosoftDocs/windows-driver-docs#2913]
this is a question and need your help
in this doc, Server 2019 was not listed, and please give it an update

thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0afbc04b-349a-57ed-eeb0-3d2cd28e359c
* Version Independent ID: de61f684-31d7-2de5-d66c-a3319f5198d9
* Content: [Inf2Cat - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/inf2cat)
* Content Source: [windows-driver-docs-pr/devtest/inf2cat.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/inf2cat.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@guofengtd - Thanks for pointing out that this topic could be updated. I will contact our dev team and work on that. For your specific query, I believe that ServerRS5_X64 or ServerRS5_ARM64 are the appropriate flags to specify for Server 2019. For information on Server 2019 see: https://docs.microsoft.com/en-us/windows-insider/archive/new-in-rs5-server  

As another resource for questions such as OS version naming, your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. Good luck with your use of the Inf2Cat command.
