### ISSUE TITLE
Missing hidden-endpoint-bad picture on windows-hardware/drivers/audio/audio-endpoint-builder-algorithm

### ISSUE THREAD

**Issue by Kojoley** [MicrosoftDocs/windows-driver-docs#2915]
The picture reference seems to be ill-formed on this line https://github.com/MicrosoftDocs/windows-driver-docs/blame/staging/windows-driver-docs-pr/audio/audio-endpoint-builder-algorithm.md#L63

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab326026-874f-86b6-94ac-4ba365b730e5
* Version Independent ID: 0a0a842b-b8a6-8ae5-779f-98e7356e1618
* Content: [Audio Endpoint Builder Algorithm - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/audio-endpoint-builder-algorithm)
* Content Source: [windows-driver-docs-pr/audio/audio-endpoint-builder-algorithm.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/audio-endpoint-builder-algorithm.md)
* Product: **windows-hardware**
* Technology: **audio**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Kojoley - Sharp eye! Yes that alt text was malformed causing the image to not render. It is now fixed. Thanks for pointing this issue out.
