### ISSUE TITLE
Undefined Terms and Abbreviations

### ISSUE THREAD

**Issue by 5U8cVs** [MicrosoftDocs/windows-driver-docs#2916]
SoC is system on a chip.  This is a new technology (relatively speaking) in which pocket sized mainframes become possible.  Flashing as a verb apparently refers to the process of writing to read-mostly-memory.   
FFU has nothing to do with a common vulgarism.   Still not learned enough to know what it is.
When Microsoft writes for end user consumption I go away disappointed.   Always disappointed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e0bdcb1-7cc2-0a16-9511-c9df5369c16b
* Version Independent ID: 1de3fb10-9b27-e744-0219-fc8d6353f294
* Content: [Boot and UEFI - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/boot-and-uefi)
* Content Source: [windows-driver-docs-pr/bringup/boot-and-uefi.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/boot-and-uefi.md)
* Product: **windows-hardware**
* Technology: **bringup**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@5U8cVs, thanks for the feedback on the use of undefined terms and abbreviations.

The System on Chip (SoC) and Full Flash Update (FFU) acronyms have been expanded on first use and where appropriate in the topic.
