### ISSUE TITLE
The doc of building NDIS 6.7 and above version lack of NDIS_FILTER_CHARACTERISTICS_REVISION_2(3)  

### ISSUE THREAD

**Issue by descartes123** [MicrosoftDocs/windows-driver-docs#2938]
Hi, admin

Our product has a ndis filter driver which are recently upgraded to ndis 6.7 and 6.8, we followed the below doc to implement it:
**https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-ndis-6-70#implementing-an-ndis-670-driver
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-ndis-6-80#implementing-an-ndis-680-driver**

But our driver can't start successfully, the NdisFRegisterFilterDriver function always return **NDIS_STATUS_BAD_CHARACTERISTICS** (0xc0010005), we took many effort to resolve the issue, it was because the NDIS_FILTER_DRIVER_CHARACTERISTICS.Header.Revision must be **NDIS_FILTER_CHARACTERISTICS_REVISION_2** for 6.7 and **NDIS_FILTER_CHARACTERISTICS_REVISION_3** for 6.8, but the docs doesn't mention it at all, it result into many confusion in the development work.

Hope the doc to update to provide the detail information on ndis 6.7 and above version.

Thanks

**Comment by aviviano** [comment]
Hi @descartes123,
Thanks for sharing your experience. We have updated the intro pages for each NDIS minor version to include the header member changes for the characteristics structures: https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-ndis-6-83
