### ISSUE TITLE
WDTF requires target OS version of WDK on both host and target

### ISSUE THREAD

**Issue by IC-SteveP** [MicrosoftDocs/windows-driver-docs#2950]
The WDTF provisioning operation (Driver Test Configure Device) copies installers from the host to the target.  If the target OS does not match the host OS there is a very good chance (100% in my case) that one of the installers copied to the target (WDTF framework) will fail to install which will break Driver Test.  The failure is not reported during provisioning.  It only becomes apparent when attempting to deploy a driver for testing.

This undocumented requirement also means that targeting a down-level OS (i.e. target Server 2016 from host Win10 21H1) requires the host to install and use the VS version that supports the WDK required by the target (i.e.  Server 2016 requires WDK 1607 which requires VS2015).

Please update the docs.  This was a very frustrating and time-consuming thing to have to figure out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce050ea3-d61e-830c-3038-f725eb4c29e1
* Version Independent ID: eb7fc65e-bcfe-dc86-3f8c-336d20eb0c86
* Content: [Provision a computer for driver deployment and testing (WDK 10) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/provision-a-target-computer-wdk-8-1)
* Content Source: [windows-driver-docs-pr/gettingstarted/provision-a-target-computer-wdk-8-1.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/provision-a-target-computer-wdk-8-1.md)
* Product: **windows-hardware**
* Technology: **gettingstarted**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by DOMARS** [comment]
@IC-SteveP - Thanks for passing on your experience, and I'm contacting the dev team to see if we can provide version matching guidelines. And yes, as described in [When you provision a computer (WDK 8.1)](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/what-happens-when-you-provision-a-computer--wdk-8-1-) (that I added link to in the topic) various install programs are run to create the test environment during provisioning. 

If you are doing HLK driver testing, the recommendation would be to use  multiple virtual HLK (VHLK) installs to match the appropriate HLK client deploy, to the target system you are working to certify for. This correlation is shown in a table located in [Windows Hardware Lab Kit](https://docs.microsoft.com/en-us/windows-hardware/test/hlk/). 

Developing drivers for multiple versions of Windows is complex, and there are of course many combinations. For the best ideas on what approaches work well, for example with Windows Server, your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html) and the OSR forum - [OSR's ntdev List](https://community.osr.com/categories/ntdev). You can post your question there, and the community of developers usually give feedback fairly quickly. Good luck with your driver testing and development.

**Comment by IC-SteveP** [comment]
Thank you Don,

Please note that I did not report provisioning a target using WDK 8.1.   I'm provisioning a computer running Server 2016 which requires WDK 10.0 (1607).  If "(WDK 8.1)" is intended to imply "(WDK 8.1 or later)" please state that explicitly.

As you note, the HLK docs explicitly state that HLK requires the host to install the target's required HLK version.   WDTF is independent of HLK.   WDTF docs need to explicitly state WDTF requirements.

Please add relevant MS Q&A links to WDK doc pages i.e. don't make me guess what the correct tag might be.  My experience with MS Q&A for WDK issues is that it's like whistling in a hurricane i.e. unlikely to get noticed.

Regards,
    Steve

________________________________
