### ISSUE TITLE
about the firmware update display capsule payload.

### ISSUE THREAD

**Issue by ZuyingWo** [MicrosoftDocs/windows-driver-docs#2954]
Hello,
Is there a policy about the position of the capsule payload image?

Since if we want to output some message dynamically on the same screen, we need to consider how to prevent the conflict with your payload image handed off with this variable.

Looking for your feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca2c956b-1682-7c06-d68c-7c94da37007d
* Version Independent ID: 27245878-59d9-9018-3aee-327b5bc2abdd
* Content: [Boot screen components - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/boot-screen-components)
* Content Source: [windows-driver-docs-pr/bringup/boot-screen-components.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/boot-screen-components.md)
* Product: **windows-hardware**
* Technology: **bringup**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@ZuyingWo, thanks for reaching out to the Windows Driver Developer Documentation team. You may have success posting your question about positioning the capsule payload image in the following forums, where other driver developers and Microsoft engineers can be found. 

[Microsoft Q&A: Windows Hardware development](https://docs.microsoft.com/answers/topics/windows-hardware.html)

[OSR Developer Community](https://community.osr.com/)
