### ISSUE TITLE
C# Log.Comment example doesn't work

### ISSUE THREAD

**Issue by suncats** [MicrosoftDocs/windows-driver-docs#2962]
In https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/taef/wexlogger.md, the C# example doesn't work without first using WEX.Logging.Interop;

**Comment by DOMARS** [comment]
@suncats - Yes that would a good idea to include the required using statement in the code sample, as was done in the C++ sample, right above it. So I updated the topic to do that. Thanks for seeing this gap and filing this issue.
