### ISSUE TITLE
Missing documentation of windbg serial TCP transport

### ISSUE THREAD

**Issue by jcbottorff-ampere** [MicrosoftDocs/windows-driver-docs#2964]
The windbg transport option strings don't document the very useful serial debug over TCP port option:

windbg.exe -k com:ipport=5003,port=10.73.0.140

Many people will have serial to net TCP port servers connected to the physical serial port of a target system. If you don't know about this com:ipport option, you have to use some finicky TCP to virtual serial or TCP to named pipe bridge software. Virtualization software also sometimes exposes the VM's serial port as a TCP port too. Using the com:ipport direct transport is much simpler and more reliable in these debug scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706365b-827a-0bd2-5da5-7fd96f9658c2
* Version Independent ID: 204e1755-4f73-04e3-dff4-e1310e04d02c
* Content: [Live Kernel-Mode Debugging Using WinDbg - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/performing-kernel-mode-debugging-using-windbg)
* Content Source: [windows-driver-docs-pr/debugger/performing-kernel-mode-debugging-using-windbg.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/performing-kernel-mode-debugging-using-windbg.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@jcbottorff-ampere - Thanks for this PR. I have checked with the dev team and they are considering if this option is one that we want to document and widely support. I passed on your input about the value you found in your use case scenarios. If the dev team does decide to support this, I will document the options. I have created an internal work item for this, so closing this issue.
