### ISSUE TITLE
Discrepancy in Default (Client) value of *FlowControl

### ISSUE THREAD

**Issue by sandilyabhagi** [MicrosoftDocs/windows-driver-docs#2966]
<html>
<body>

*FlowControl | Flow Control | 0 (Server Default) | Tx & Rx Disabled
-- | -- | -- | --
  |   | 1 | Tx Enabled
  |   | 2 | Rx Enabled
  |   | 3 (Client Default) | Rx & Tx Enabled

</body>
</html>

The documentation mentions that *FlowControl for client is 3 but the HLK test is failing with this value.
NDI\Params\*FlowControl\Default is not "4" as expected!

Also, Test-NETHLK (NICStrictPropertyValidation) expects it to be 3.

Kindly correct the documentation with the right value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67de06a0-67a0-3be0-c5eb-ead719e58980
* Version Independent ID: 0f06dcb5-f777-40cb-d52f-d28787290a4e
* Content: [Enumeration Keywords - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/enumeration-keywords)
* Content Source: [windows-driver-docs-pr/network/enumeration-keywords.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/enumeration-keywords.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @sandilyabhagi, thanks for opening this issue. I passed along your comments to the feature team but haven't received a response. If you still have concerns you may try posting a question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) or the [OSR NTDEV](https://community.osr.com/categories/ntdev) forum.
