### ISSUE TITLE
hardware developer" legal agreement

### ISSUE THREAD

**Issue by gbholmanp** [MicrosoftDocs/windows-driver-docs#2971]
It would be useful to have links to the legal documents directly from this page.

(We would like to sign our driver,  but will need our legal team to review any agreements in advance)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2daf70ed-7391-5783-583b-fcd99f1c222a
* Version Independent ID: 679bd45d-d0fd-a192-4d26-0121594fa86a
* Content: [Register for the Hardware Program - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/register-for-the-hardware-program)
* Content Source: [windows-driver-docs-pr/dashboard/register-for-the-hardware-program.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/register-for-the-hardware-program.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @gbholmanp,

Thank you for this feedback. I've created a work item to add links to the legal documents to this page.

Best wishes,
 ~ *Mark*
