### ISSUE TITLE
R and RH oplocks can be granted for directories

### ISSUE THREAD

**Issue by maharmstone** [MicrosoftDocs/windows-driver-docs#2972]
This page needs updating - as per https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_request_oplock, R and RH oplocks can now be granted on directories.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1abb79eb-2db4-cbaa-0524-89acfe55c0f6
* Version Independent ID: c08bc550-6b9d-1b87-8861-220b001340f8
* Content: [Granting Oplocks - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/granting-oplocks)
* Content Source: [windows-driver-docs-pr/ifs/granting-oplocks.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/granting-oplocks.md)
* Product: **windows-hardware**
* Technology: **ifs**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for this issue, @maharmstone . I've removed the following sentence from the R and RH table sections: "If a directory, STATUS_INVALID_PARAMETER is returned."
