### ISSUE TITLE
External NIC referenced instead of internal upon close down

### ISSUE THREAD

**Issue by JustMrMak** [MicrosoftDocs/windows-driver-docs#2978]
External NIC referenced instead of internal upon close down.

Open has been amended to reflect internal but external has not I'm afraid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 760bcea0-f7f1-577a-e20c-94e4d4ef5b36
* Version Independent ID: 6f8a2c67-252c-d32f-77a5-493be8add12c
* Content: [Internal Network Adapters - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/internal-network-adapters)
* Content Source: [windows-driver-docs-pr/network/internal-network-adapters.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/internal-network-adapters.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks @JustMrMak for opening this issue. This page is now updated: https://docs.microsoft.com/en-us/windows-hardware/drivers/network/internal-network-adapters
