### ISSUE TITLE
cp2102usb to uart

### ISSUE THREAD

**Issue by vvalcev** [MicrosoftDocs/windows-driver-docs#2983]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98c3de9-19b4-de58-d7c2-4f8529d953e1
* Version Independent ID: 63b0b15a-13a2-0951-2e39-0467d5bbf030
* Content: [Installing Plug and Play Serial Ports and COM Ports - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/serports/installing-plug-and-play-serial-ports-and-com-ports)
* Content Source: [windows-driver-docs-pr/serports/installing-plug-and-play-serial-ports-and-com-ports.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/serports/installing-plug-and-play-serial-ports-and-com-ports.md)
* Product: **windows-hardware**
* Technology: **serports**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by tedhudek** [comment]
Closing out due to empty feedback.  Please reopen with info if still needed
