### ISSUE TITLE
FSFilter Virtualization appears to me missing from this list

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs#2984]
I'd never noticed before.  
Other pages reference this class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afebaad6-2922-904e-4b7b-7ad2d1970d7f
* Version Independent ID: 84d957e5-1fb8-3d63-29a1-093933056890
* Content: [File System Filter Driver Classes and Class GUIDs - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/file-system-filter-driver-classes-and-class-guids)
* Content Source: [windows-driver-docs-pr/ifs/file-system-filter-driver-classes-and-class-guids.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/file-system-filter-driver-classes-and-class-guids.md)
* Product: **windows-hardware**
* Technology: **ifs**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
I so appreciate your eye on the docs, @rodwiddowson ! Just added the missing FSFilter classes and class GUIDs to this page.
