### ISSUE TITLE
Question about Firmware Version Of SuperMutt V3.0

### ISSUE THREAD

**Issue by JiyoonHa84** [MicrosoftDocs/windows-driver-docs#2987]
Hello,
I've installed MUTT SW Package (Mutt2_96.msi), but I think that there is no latest firmware version.
Because when I tried firmware update (MuttUtil.exe -UpdateFirmware), always remain rev51
Could you tell me where can I download latest FW?
(Refer to version updates info, FW v55 must be included in version 2.9.5)

And I wonder about transfer mode.
I've bought SuperMuttV3.0 for test each transfer mode. (ex. Isochronous transfer)
But It seems only bulk mode operation.
Is Supermutt V3.0 support Isochronous transfer mode?
How can I switch mode to Isochronous? related to FW version?
 
Thanks.

*Firmware version refer to below CMD log

C:\USBTest\x64>MuttUtil.exe -UpdateFirmware
Looking for MUTT devices
List of devices before firmware update
       :    : HARDWARE ID                    :  PROBLEM CODE  : DRIVER
DEVICE :  0 : USB\VID_045E&PID_078F&REV_0051 :             0  : USBTCD
List of devices after firmware update
       :    : HARDWARE ID                    :  PROBLEM CODE  : DRIVER
DEVICE :  0 : USB\VID_045E&PID_078F&REV_0051 :             0  : USBTCD
Return value: 0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aa1d919-c2b7-eec7-f69d-1a0f3ebef4e5
* Version Independent ID: 39996cc8-d582-e578-93bf-9bbcb2cfdd38
* Content: [Tools in the MUTT software package - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/mutt-software-package)
* Content Source: [windows-driver-docs-pr/usbcon/mutt-software-package.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/mutt-software-package.md)
* Product: **windows-hardware**
* Technology: **usbcon**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hello @JiyoonHa84

Thanks for reaching out to our team. This particular mechanism is monitored by the men and women who write the driver documentation posted on doc.microsoft.com. Unfortunately, we don’t have the resources to help troubleshoot driver development issues sent our way.  
 
Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/). The other is the [OSR NTDEV forum](https://community.osr.com/categories/ntdev). You can post your question there, and like-minded developers usually give feedback fairly quickly. 
 
Again, thanks for reaching out. Best of luck with this issue. 
 ~ *Mark*
