### ISSUE TITLE
Explain 'Windows Certified'

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs#2992]
The page notes that "when a driver receives attestation signing, it is not Windows Certified." What are the consequences of this for the driver developer and, more importantly, for the end user? A little explanation about what "Windows Certified" means and is worth would be helpful in understanding whether attestation signing is the correct fit for a given circumstance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 175b6b9d-9fbf-08e3-74bc-f5158baed555
* Version Independent ID: 98a9d5e5-9aae-28bd-0cf8-07f49a0c7514
* Content: [Attestation signing a kernel driver for public release - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/attestation-signing-a-kernel-driver-for-public-release)
* Content Source: [windows-driver-docs-pr/dashboard/attestation-signing-a-kernel-driver-for-public-release.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/attestation-signing-a-kernel-driver-for-public-release.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @druske,

Thank you for your feedback on this page. I have added a paragraph at the top of the page to describe when using attestation signing is supported versus when to use the Windows HLK certification method. I hope this helps clarify the issue.

Thanks again!
 ~ *Mark*
