### ISSUE TITLE
Measure ID list table

### ISSUE THREAD

**Issue by sjeemb** [MicrosoftDocs/windows-driver-docs#2994]
Hi,

I've searched the Windows Docs site for the Measure ID table, but couldn't find anything related to it.
Just a few measure attribute examples for some cases.
Is the corresponding passing criteria for measure ID have a list table?

Thanks.
Ryan

**Comment by tedhudek** [comment]
Hi @sjeemb - I'm not familiar with measure IDs.  Can you give me some more info, like whether you're writing an app or a driver, and what technology you're working in (storage, display, networking, etc.)

**Comment by tedhudek** [comment]
Closing out due to lack of info, please reopen with details if still needed
