### ISSUE TITLE
Ne fonctionne pas sous Windows 2019/2022

### ISSUE THREAD

**Issue by GowaP** [MicrosoftDocs/windows-driver-docs#2998]
L'utilisation de "Bcdedit" ne fonctionne pas avec Windows 2022 Server pour désactiver la vérification de la signature numérique. Le "pilote" reste en erreur dans le gestionnaire de périphérique.
BcdEdit /set TESTSIGNING ON
BcdEdit /set nointegritychecks ON
BcdEdit /set loadoptions DISABLE_INTEGRITY_CHECKS

Quel est la nouvelle méthode pour WS2022 et W11 ?

État du périphérique : Windows ne peut pas vérifier la signature numérique des pilotes requis pour ce périphérique. Il est possible qu’une modification matérielle ou logicielle récente ait installé un fichier endommagé ou dont la signature est incorrecte, ou qu’il s’agisse d’un logiciel malveillant provenant d’une source inconnue. (Code 52) 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b098cc9-eff8-b24d-824c-99d038196d4c
* Version Independent ID: dce141c3-6962-236a-d418-9ee3b6d48779
* Content: [Loading Test Signed Code - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option)
* Content Source: [windows-driver-docs-pr/install/the-testsigning-boot-configuration-option.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/the-testsigning-boot-configuration-option.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @gowap, nothing has changed here in WS2022/Win11.  

Note that if you have Memory Integrity / HVCI enabled, you must test-sign the binary (using any self-created test cert). An unsigned binary is not supported.

If that does not apply, would it be possible for you to share the CI logs from `\Windows\System32\winevt\Logs\Microsoft-Windows-CodeIntegrity%4Operational.evtx`?

**Comment by tedhudek** [comment]
I added the caveat to https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option (see the second Note).  Hope this helps!

Thanks for the feedback :)
