### ISSUE TITLE
FSCTL_FIND_FILES_BY_SID: Names of members missing

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-driver-docs#3000]
In the documentation of FSCTL_FIND_FILES_BY_SID, these structure definitions display the types of the members but should display the names as well:

```C
typedef struct {
  DWORD  ;
  SID  ;
} FIND_BY_SID_DATA, *PFIND_BY_SID_DATA;
```

```C
typedef struct _FIND_BY_SID_OUTPUT {
  DWORD  ;
  DWORD  ;
  DWORD  ;
  WCHAR  [1];
} FIND_BY_SID_OUTPUT, *PFIND_BY_SID_OUTPUT;
```

This error is already present in the Markdown, not caused by the docs build process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4e3ba2-dc57-9ebe-331c-fa6b9b8a40c6
* Version Independent ID: f107e3a5-62a0-db57-b319-9f03a34920c4
* Content: [FSCTL_FIND_FILES_BY_SID control code - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/fsctl-find-files-by-sid)
* Content Source: [windows-driver-docs-pr/ifs/fsctl-find-files-by-sid.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/fsctl-find-files-by-sid.md)
* Product: **windows-hardware**
* Technology: **ifs**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for pointing this out, @KalleOlaviNiemitalo! I've updated the page to remove the embedded syntax blocks and instead link to the actual structure pages.
