### ISSUE TITLE
USB Audio 2.0 Driver

### ISSUE THREAD

**Issue by HHH0003** [MicrosoftDocs/windows-driver-docs#3001]
I have a Lenovo P620 with a Realtek ALC4050H codec.  The Realtek Driver is basically unusable since it goes into D2 power state after 10 seconds of idle time causing truncated audio when a call for audio is made. It also makes a popping noise when it basically turns off after 10 seconds.  The Windows USB Audio 2.0 works perfectly with this codec… although it doesn’t show correct jack information.  Instead of the Green colored jack information, it’s a black dot with no information.  I’m not sure if this information can be added using the registry editor?  Any assitance would be appreciated.

**Comment by DOMARS** [comment]
This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. 

You may also want to try the audio troubleshooter as it attempts to clean up configuration issues and look in the event log for related messages to gather more information.
https://support.microsoft.com/en-us/windows/fix-sound-problems-in-windows-10-73025246-b61c-40fb-671a-2535c7cd56c8
And check with Lenovo to see if they have integrated in a later realtek driver - https://support.lenovo.com/

Good luck with your use of the realtek audio driver issue.
