### ISSUE TITLE
Error in page instrucions

### ISSUE THREAD

**Issue by efraimN** [MicrosoftDocs/windows-driver-docs#3004]
[Enter feedback here]
Should say change to &lt; and not change to "<"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 880e65ab-4a83-5c10-cb07-dd1313ec9094
* Version Independent ID: cf9fd5ed-ab04-205a-8b9d-5244463878ac
* Content: [ProjectUpgradeTool - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/projectupgradetool)
* Content Source: [windows-driver-docs-pr/devtest/projectupgradetool.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/projectupgradetool.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@efraimN - Thanks for this PR, and having a sharp eye here! Our system was taking the & l t and rendering it as a > symbol. So the fix in Markdown, was to surround it in  `, so that it renders a literal code string. Thanks again and best of luck with your driver development work.
