### ISSUE TITLE
Visual Studio Community Compatibility

### ISSUE THREAD

**Issue by jnrbo** [MicrosoftDocs/windows-driver-docs#301]
I'm trying to follow the sample tutorial, but It's deprecated - some menus and options dosn't exist . 

I'm using:

```
Microsoft Visual Studio Community 2017 
Version 15.5.2
VisualStudio.15.Release/15.5.2+27130.2010
Microsoft .NET Framework
Version 4.7.02558
```

**Comment by tedhudek** [comment]
Hi @jnrbo what's the URL of the sample tutorial you were trying to follow, and is there a particular steps or set of steps where you found that the menus and options weren't available?

**Comment by jnrbo** [comment]
Hi @tedhudek 

I'm following this [tutorial](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/building-a-basic-v4-printer-driver).


All menus inside **Property Pages window** are deprecated!

Thank you!

**Comment by tedhudek** [comment]
Thanks @jnrbo I've assigned this issue to @barrygolden, who is out for the holidays, but can address this when he returns.  Apologies for the discrepancies, that's frustrating when you're trying to follow a tutorial.

**Comment by barrygolden** [comment]
Investigating issue with deprecated menus and options. Working with print driver devs to replicate.

**Comment by barrygolden** [comment]
@MFenelon, can you take a look at this issue?
