### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by MSK61** [MicrosoftDocs/windows-driver-docs#3011]
This page is missing a lot of information about how to use `bcdedit /set` command. Moreover it contains a lot of other irrelevant information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 714c21f8-cf12-3d98-f62a-cff0d326874e
* Version Independent ID: fc5eabc0-451e-1fe3-705b-d486c21cb334
* Content: [BCDEdit /set - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--set)
* Content Source: [windows-driver-docs-pr/devtest/bcdedit--set.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/bcdedit--set.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@MSK61 - Thanks for this input. We use input such as this to look at which topics we do additional work in. As the bcdedit command is used in many different scenarios, this top-level topic attempts to provide a summary of what bcdedit can do and then provide links to the sub-topics that provide additional information. For example, for configuring the debugger, there is a link to [BCDEdit /dbgsettings](https://docs.microsoft.com/windows-hardware/drivers/devtest/bcdedit--dbgsettings). As there is a wide set of related tasks, you might look in [BCDEdit Options Reference](https://docs.microsoft.com/windows-hardware/drivers/devtest/bcd-boot-options-reference) to see if that better suits your needs.
