### ISSUE TITLE
Is there any debug tool for portcls ?

### ISSUE THREAD

**Issue by XiaoPengliang** [MicrosoftDocs/windows-driver-docs#3017]
[Enter feedback here]
To help HW vendor to check issue relate audio and clarify is it cause by portcls, is there any tool we can use ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7bb782-28a4-f1f1-a0f1-d784803aa22b
* Version Independent ID: 9997ec15-188c-c561-0f7d-196f600afbc5
* Content: [Audio Port Class Functions - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/audio-port-class-functions)
* Content Source: [windows-driver-docs-pr/audio/audio-port-class-functions.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/audio-port-class-functions.md)
* Product: **windows-hardware**
* Technology: **audio**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@XiaoPengliang - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). 

I'm not aware of any tool specific to portcls, but I would recommend the use of the audio troubleshooter as described here: https://support.microsoft.com/en-us/windows/fix-sound-problems-in-windows-10-73025246-b61c-40fb-671a-2535c7cd56c8

If that doesn't work, things get more complicated, and traces and utilities could be explored (such as KSStudio) to gather information.  Of course, troubleshooting USB audio is different from a laptop with a built-in chip set. The process to gather logs and troubleshoot is discussed in this blog: https://matthewvaneerde.wordpress.com/tag/audio/

Good luck with your work related to portcls audio.
