### ISSUE TITLE
Inf section used in production Windows drivers and example drivers not defined in docs

### ISSUE THREAD

**Issue by jcbottorff-ampere** [MicrosoftDocs/windows-driver-docs#3019]
I see the INF section [DeviceInstall32] and the AddDevice directive are not documented in the MSFT docs. There are drivers included inbox (for example KDNIC630.inf) and in the github driver sample tree that use this. [DeviceInstall32] seems to be used with the AddDevice line, which is also not documented, to install root enumerated PnP drivers. Using [DeviceInstall32] with AddDevice allows installation with the standard OS tool "pnputil -a myDriver.inf". The example is in "https://github.com/microsoft/Windows-driver-samples/blob/master/general/SimpleMediaSource/SimpleMediaSourceDriver/SimpleMediaSourceDriver.inf"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9e5742-568d-2239-42b9-467d2d8b4630
* Version Independent ID: 7da8167f-35de-f6a8-f1f7-98e1f8a42bfa
* Content: [INF ClassInstall32 Section - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-classinstall32-section)
* Content Source: [windows-driver-docs-pr/install/inf-classinstall32-section.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-classinstall32-section.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @jcbottorff-ampere,

The [DeviceInstall32] section and AddDevice directive are meant to only be used by inbox INFs at this time. They should not be used in any of the samples and we will look into getting that cleaned up.  Appreciate the heads-up on this!
