### ISSUE TITLE
Typo in UMDF versions

### ISSUE THREAD

**Issue by brettw** [MicrosoftDocs/windows-driver-docs#3020]
The page has the sentence: "Writing a driver using UMDF version 1 requires using the COM programming model to write C++ code. While UMDF version 1 is based on the same conceptual driver programming model as KMDF".

"version 1" is indicated both times. The first one should be "2", as in "Writing a driver using UMDF version 2 requires using..." This is clarified in the next paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7195a081-81f1-5160-a078-d6044e005d65
* Version Independent ID: 9f07ab89-d297-ae95-4b4a-2cde15f4ea95
* Content: [Getting Started with UMDF - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/getting-started-with-umdf-version-2)
* Content Source: [windows-driver-docs-pr/wdf/getting-started-with-umdf-version-2.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/getting-started-with-umdf-version-2.md)
* Product: **windows-hardware**
* Technology: **wdf**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Wow Brett, great eye!  Thanks for the report.  I just pushed the fix -- should be on the live site in a few minutes.
