### ISSUE TITLE
How do I get hello world to display in the debugger? What fires the driver off?

### ISSUE THREAD

**Issue by squintz** [MicrosoftDocs/windows-driver-docs#3023]
I was successful going through this tutorial and have my driver deployed and installed and WinDBG breaking into the target machine. lm shows the KdmfHelloWorld.sys module exist but it does not appear to be loaded. What's the next step in actually seeing the KdPrintEx message in WinDBG? How do I get the kernel to create my "device?"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81568a12-c39e-a18f-8f33-c54545f14bac
* Version Independent ID: 73217b22-1795-b5d0-65cb-1984f38dc661
* Content: [Write a Hello World Windows Driver (KMDF) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-very-small-kmdf--driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-very-small-kmdf--driver.md)
* Product: **windows-hardware**
* Technology: **gettingstarted**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by DOMARS** [comment]
@squintz - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback pretty quickly.

As far as displaying information in the debugger, you will need to configure symbols to be able to traverse the driver stack. More detail is in this lab: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-  Getting the kernel debugger to connect to the remote PC is often the most difficult step, and it sounds like that is done. In section 6 of the lab, "Displaying Plug and Play device tree information" shows the use of the !devnode command that will provide some information about the devices and PDOs, etc. It also shows how to enable / disable the driver in the UI to force driver events. 

Developing drivers is pretty major effort, so you may also want to consider one of the books such as Developing Drivers with the Windows Driver Foundation, Inside Windows Debugging, and of course Windows Internals. 

Good luck with your driver development work.
