### ISSUE TITLE
!trueref is less in the "documentation" page

### ISSUE THREAD

**Issue by RobertoB74** [MicrosoftDocs/windows-driver-docs#3024]
[Enter feedback here]

don't be angry,
because just yesterday ... someone of your admin has write me ... highlight that my post weren't concerning about this
channel ... but i have used the 'feedback button' in a documentation page and it has redirect me to this forum ...

to make it quicly:
if you are interested about it ... the !trueref windbg command is less .... i have read it on a book and i have tryed and it's 
sure that is supported by 'WinDbg preview'

thanks and bye

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a818b121-53b3-c6a6-853a-2d9640912cc6
* Version Independent ID: 94c9600f-97aa-7a38-1423-ba76a9a32c42
* Content: [process (WinDbg) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-process#feedback)
* Content Source: [windows-driver-docs-pr/debugger/-process.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-process.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@RobertoB74 - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually will provide feedback.
