### ISSUE TITLE
Wrong URL link of the related topics

### ISSUE THREAD

**Issue by wcchou** [MicrosoftDocs/windows-driver-docs#3029]
Is the link of the first item of the *Related topics* wrong? I guess it should link to https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/ instead of https://docs.microsoft.com/en-us/windows-hardware/drivers/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1083ea-f286-8a19-ff44-2a7129fdf826
* Version Independent ID: df2b2c4e-f7fd-79c6-8b92-a775140f9519
* Content: [Architecture of USB host controller extension (UCX) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/get-started-with-host-controller-driver-development#feedback)
* Content Source: [windows-driver-docs-pr/usbcon/get-started-with-host-controller-driver-development.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/get-started-with-host-controller-driver-development.md)
* Product: **windows-hardware**
* Technology: **usbcon**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by tedhudek** [comment]
Thanks for the sharp eye, @wcchou, you are correct!  I have updated the link and it now goes to the top level page for USB.
