### ISSUE TITLE
Update 'SprtFtrs' Testing filter values for Windows 11

### ISSUE THREAD

**Issue by LHammondAritzia** [MicrosoftDocs/windows-driver-docs#3031]
[Can you please look at updating the 'SprtFtrs' Testing filter values for Windows 11, as they appear to be HEX now when you run the 'fltmc instances -v' command. Value example "0000000f".]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb725b8-9082-fd0e-c616-6e7477d1864d
* Version Independent ID: 5bb5bdde-fb2e-f99f-f59e-f3e0e0acbd57
* Content: [Windows Offloaded Data Transfers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/offloaded-data-transfers)
* Content Source: [windows-driver-docs-pr/ifs/offloaded-data-transfers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/offloaded-data-transfers.md)
* Product: **windows-hardware**
* Technology: **ifs**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@LHammondAritzia , I've changed the SprtFtrs values from decimal to hex!
