### ISSUE TITLE
Unnecessary backslashes

### ISSUE THREAD

**Issue by matwilli** [MicrosoftDocs/windows-driver-docs#3033]
Looks like there are unnecessary backslashes for this command "symchk /v c:\\sym\\MyApp.exe /s c:\\sym**".  Other sample commands on the page only have single backslashes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac689426-48f2-94f4-b2f1-d4936f162db0
* Version Independent ID: 6e2ca765-d0a2-1a69-a183-e43c6c3f85f4
* Content: [Using SymChk - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/using-symchk)
* Content Source: [windows-driver-docs-pr/debugger/using-symchk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/using-symchk.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by tedhudek** [comment]
Hey @matwilli, appreciate your sharp eye here.  I just removed the unnecessary backslashes from two code snippets on this page.  The changes should appear on the live site within 5-10 min.

Thanks for bringing this to our attention.
