### ISSUE TITLE
`<DbgEng.h>` API Windows version

### ISSUE THREAD

**Issue by AlexGuteniev** [MicrosoftDocs/windows-driver-docs#3034]
There are several interfaces in `<DbgEng.h>`, like `IDebugSymbols3`.

The documentation completely lacks information which interface is available in which Windows version or if there is a way to upgrade the available interface within the give Windows version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e6a98b4-00d4-7da8-9e06-f5cf09b8c82b
* Version Independent ID: 393f9394-559a-c0ba-cc67-77108f70f0ac
* Content: [Debugger Engine Introduction - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/introduction)
* Content Source: [windows-driver-docs-pr/debugger/introduction.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/introduction.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@AlexGuteniev - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly.

In general, most versions of the dbgeng interfaces will be available for use with supported versions of Windows, as these interfaces have been pretty stable over the last few years. To confirm which versions of the interface are available download the SDK for that version of Windows and examine the dbgeng.h header file. Good luck with your dbgeng development work.
