### ISSUE TITLE
HSA app & Internal devices

### ISSUE THREAD

**Issue by SmokeFrog981** [MicrosoftDocs/windows-driver-docs#3042]
Is there a way to enable the hardware feature for an internal device via extension INF if the user downloads the HSA app from the store and installs it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226ae215-917b-ba31-eb9c-4f4848ec7aa3
* Version Independent ID: fc54314b-ec74-589f-790b-81845cc53a8d
* Content: [Automatic installation for UWP device apps - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/auto-install-for-uwp-device-apps)
* Content Source: [windows-driver-docs-pr/devapps/auto-install-for-uwp-device-apps.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/auto-install-for-uwp-device-apps.md)
* Product: **windows-hardware**
* Technology: **devapps**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
Hi @SmokeFrog981,

Thanks for the question. No, a Store app can't trigger the installation of a driver package. It's actually the reverse -- typically, an extension INF has an AddSoftware directive that triggers the acquisition of an HSA from the Store.

Hope that helps!
