### ISSUE TITLE
Incomplete guidance on DefaultUninstall for INF file?

### ISSUE THREAD

**Issue by jeffbromberger** [MicrosoftDocs/windows-driver-docs#3044]
[The docs](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/creating-an-inf-file-for-a-minifilter-driver.md) indicate

"Starting with Windows 10 version 1903, the DefaultUninstall and DefaultUninstall.Services sections are prohibited [(with exception)](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/creating-a-primitive-driver#legacy-compatibility). These sections were optional in prior OS versions."

However, the official WDK minifilter sample INF files [still include these sections](https://github.com/microsoft/Windows-driver-samples/blob/master/filesys/miniFilter/swapBuffers/swapBuffers.inf).  Is this "prohibited" guidance referring to non-PNP, non-hardware "primitive" drivers only?  It's not clear how a file system minifilter's INF fits into all of this and what its requirements should be.

**Comment by tedhudek** [comment]
Relevant doc page is https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/creating-an-inf-file-for-a-minifilter-driver.

**Comment by lorihollasch** [comment]
Thanks for filing this issue, @jeffbromberger, and apologies for the confusion. The engineering team has an internal work item to update all minifilter sample INFs to reflect the INF changes for primitive drivers. The documentation is accurate on this page and on the linked [Creating a new primitive driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/creating-an-inf-file-for-a-minifilter-driver) page (I did update this page to add missing architecture decorations).

**Comment by jeffbromberger** [comment]
@lorihollasch thanks for the update.  One question, on the [Creating a primitive driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/creating-a-primitive-driver) page it has this:

> [DefaultInstall] sections must be architecture decorated, and no undecorated versions may be present.

> Correct: [DefaultInstall.amd64]

> Incorrect: [DefaultInstall]

[Elsewhere](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/creating-inf-files-for-multiple-platforms-and-operating-systems), however, the decoration is called out as "NTamd64", not simply "amd64".  Is this a typo?

**Comment by lorihollasch** [comment]
@jeffbromberger, another great catch. I've corrected the decoration - thanks!
