### ISSUE TITLE
Missing key detail

### ISSUE THREAD

**Issue by embermctillhawk** [MicrosoftDocs/windows-driver-docs#3045]
Windows 10 on ARM64 does not support x86 kernel-mode drivers.
It also does not support x86 user-mode drivers.
For clarity, it would be best if this article lists both, currently it only mentions kernel-mode drivers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da0acb6-3b62-3c4d-a40b-fadb3b438e8d
* Version Independent ID: 19a5ad0a-ee47-1834-694f-ee89882fa78d
* Content: [Building ARM64 Drivers with the WDK - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/building-arm64-drivers)
* Content Source: [windows-driver-docs-pr/develop/building-arm64-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/building-arm64-drivers.md)
* Product: **windows-hardware**
* Technology: **develop**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @embermctillhawk thanks for the feedback.  Great point - I just made the fix -- should appear on the live site within 10 minutes or so.  

Thanks again for caring about the docs :)
