### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by trmcnealy** [MicrosoftDocs/windows-driver-docs#3049]
So how do I go about actually creating the Virtual Miniport?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf044688-70f6-fb35-b787-dfc2eff1f256
* Version Independent ID: be66e130-a586-1270-6c9b-6a1fbd3e1563
* Content: [Overview of Storage Virtual Miniport Drivers - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/overview-of-storage-virtual-miniport-drivers)
* Content Source: [windows-driver-docs-pr/storage/overview-of-storage-virtual-miniport-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/overview-of-storage-virtual-miniport-drivers.md)
* Product: **windows-hardware**
* Technology: **storage**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@trmcnealy, this page is overview info only. You can find implementation details on [Implementing a Storport virtual miniport driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/initialization-of-storage-virtual-miniport-drivers). I can see why you missed it as that page was originally titled "Initialization". I updated the TOC and added a few more details.
