### ISSUE TITLE
What's the HLK step to cause creating a Universal package ?

### ISSUE THREAD

**Issue by meichunwu** [MicrosoftDocs/windows-driver-docs#3050]
When I submit a driver file to partner.microsoft.com, the error message shown "It looks like you submitted a Universal package, but a non Universal package is required.". After reviewing the .hlk file, found error caused by IsUniversal="True" in PackageInfo.xml under driverfile\hck\data. Could you provide suggestion what's the HLK step  to cause creating a Universal package before creating .hlk package ?   
![Screenshot (1271)](https://user-images.githubusercontent.com/55374679/155866566-85e8b743-7104-44db-b3d0-cf4cc69fb2c3.png)

**Comment by mhopkins-msft** [comment]
Hi @meichunwu,

Thanks for reaching out to our team. This particular mechanism is monitored by the men and women who write the driver documentation posted on doc.microsoft.com. Unfortunately, we don’t have the resources to help troubleshoot driver development issues sent our way.  
 
Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/). The other is the [OSR NTDEV forum](https://community.osr.com/categories/ntdev). You can post your question there, and like-minded developers usually give feedback fairly quickly. 
 
Again, thanks for reaching out. Best of luck with this issue. 
 ~ *Mark*
