### ISSUE TITLE
NET_BUFFER_LIST structure is explained very poorly.

### ISSUE THREAD

**Issue by henrikalmeida** [MicrosoftDocs/windows-driver-docs#3051]
This page:

https://docs.microsoft.com/en-us/windows-hardware/drivers/network/net-buffer-list-structure

Is very poorly written and just explains very basic stuff such as members of a struct. This structure is used by literally every network driver, thus this leads to loads of poorly written drivers. 

There is no explanation at all of what this structure represents? 

For example we know that a NET_‌BUFFER represent a packet, a very important question that is unexplained here is that what do the NET_‌BUFFER structures that an NET_‌BUFFER_LIST is representing have in common? do they have the same (srcIP srcPort, dstIP, dstPort), or what? **AND what about in case of non IP packets**? And does a multiple NET_BUFFERs inside an NET_‌BUFFER_LIST only happens in case of send? 

And what about a chain of NET_‌BUFFER_LIST that are linked together which is used in NDIS receive/send functions? Do these NET_BUFFER_LIST structures that are linked/chained together required to have anything in common?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c15f902-aead-0dcd-0ac5-fe74b27a7067
* Version Independent ID: f7c64496-469d-3801-79d1-3e9895ad3ecf
* Content: [NET_BUFFER_LIST Structure - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/net-buffer-list-structure)
* Content Source: [windows-driver-docs-pr/network/net-buffer-list-structure.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/net-buffer-list-structure.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @henrikalmeida, You are correct that the [NET_BUFFER_LIST Structure](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/net-buffer-list-structure) just discusses the basics of the structure. For answers to the questions your are asking, please see pages further down in the menu on the left, such as [Transferring Network Data](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/send-and-receive-operations) and [Transferring Network Data with Ethernet](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/ethernet-send-and-receive-operations).
