### ISSUE TITLE
Can I use ethernet or serial port to do remote debugging on WOA system?

### ISSUE THREAD

**Issue by HCHuang1971** [MicrosoftDocs/windows-driver-docs#3052]
Can I use ethernet or serial port to do remote debugging on WOA system?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 285cb5be-ed6f-aa62-79b3-c00ab1841eb2
* Version Independent ID: 7fc06c4a-3faa-69a1-1fdf-997bb4e1f166
* Content: [Setting Up Kernel-Mode Debugging over USB EEM on an ARM device using KDNET - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-kernel-mode-debugging-over-usb-eem-arm-kdnet)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-kernel-mode-debugging-over-usb-eem-arm-kdnet.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-kernel-mode-debugging-over-usb-eem-arm-kdnet.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@HCHuang1971 - Thanks for reaching out to our team. This particular mechanism is monitored by the men and women who write the driver documentation posted on doc.microsoft.com. Unfortunately, we don’t have the resources to provide support on the use of the debugger.

Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/). The other is the [OSR NTDEV forum](https://community.osr.com/categories/ntdev). You can post your question there, and like-minded developers usually give feedback fairly quickly.

Again, thanks for reaching out. Best of luck with this issue.
