### ISSUE TITLE
`!handle -1` not working

### ISSUE THREAD

**Issue by SamZhangQingChuan** [MicrosoftDocs/windows-driver-docs#3053]
Has `!handle -1` been deprecated? It doesn't work on my machine.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/8025859/156288918-1ba2926b-9f43-4ec2-91d1-41af00fa8444.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be98bdb-5da9-5ec6-873f-1fcc2fa44d5a
* Version Independent ID: 0098d700-6d00-02ea-6217-2893852d1e4f
* Content: [handle (WinDbg) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-handle)
* Content Source: [windows-driver-docs-pr/debugger/-handle.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-handle.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@SamZhangQingChuan - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 
Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly.

The !handle docs show that these bit mask options are used with out a dash, so you might try something like ` !handle 1 0`. Good luck with your issue.
