### ISSUE TITLE
The documentation refers to deprecated functions (NdisGetHypervisorInfo)

### ISSUE THREAD

**Issue by DanGoldbergMellanox** [MicrosoftDocs/windows-driver-docs#3055]
Hi,

This page refers to "NdisGetHypervisorInfo" function which is deprecated.
Please update the instructions to an up-to-date interface that should be used to check if it's a hypervisor or a VM.

Thanks,
Dan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a70887-dbc1-2f73-dcc5-08051abde221
* Version Independent ID: 60c7b530-1200-77c1-108d-99106d100817
* Content: [Initializing a VF Miniport Driver - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/initializing-a-vf-miniport-driver)
* Content Source: [windows-driver-docs-pr/network/initializing-a-vf-miniport-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/initializing-a-vf-miniport-driver.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks for opening this issue @DanGoldbergMellanox. I haven't heard back from the development team on whether there is a replacement for NdisGetHypervisorInfo. 

Please follow the instructions on [NdisGetHypervisorInfo](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/nf-ndis-ndisgethypervisorinfo): 
Drivers should instead follow a hypervisor's instructions to query hypervisor presence and capabilities. For example, Hyper-V's instructions are documented in the [Top-Level Functional Specification](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/tlfs).

Please open a new issue if you have further questions. You can also try posting your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) or the OSR [NTDEV forum](https://community.osr.com/categories/ntdev).

Thank you.
