### ISSUE TITLE
how is this going to be worked around for windows 11?

### ISSUE THREAD

**Issue by Yocobicus** [MicrosoftDocs/windows-driver-docs#3056]
[Enter feedback here]
how is this going to be worked around for windows 11? Since windows 11 needs these features to function?
"you may need to temporarily suspend Windows security features such as BitLocker and Secure Boot on the test PC."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccedc354-3446-6927-e83d-331c2f24f81f
* Version Independent ID: b2b523dc-1a11-c39b-0466-6bc35410181f
* Content: [Setting Up Kernel-Mode Debugging of a Virtual Machine Manually using a Virtual COM Port - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/attaching-to-a-virtual-machine--kernel-mode-)
* Content Source: [windows-driver-docs-pr/debugger/attaching-to-a-virtual-machine--kernel-mode-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/attaching-to-a-virtual-machine--kernel-mode-.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Yocobicus - Thanks for reaching out to our team. This particular mechanism is monitored by the men and women who write the driver documentation posted on doc.microsoft.com. Unfortunately, we don’t have the resources to help troubleshoot debugger development issues sent our way. In general, the goal is to temporarily disable these important features and then restore their use after debugging is complete on the target system. 
Your best bet for further questions, is to use one of the forums where other driver developers and Microsoft engineers can be found, such as [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/). You can post your question there, and like-minded developers usually give feedback fairly quickly.
Again, thanks for reaching out. Best of luck with this issue.
