### ISSUE TITLE
Instructions for downloading CodeQL are incorrect.

### ISSUE THREAD

**Issue by ergins23** [MicrosoftDocs/windows-driver-docs#3057]
The instructions state the following

> Download version **2.4.6** of the zip file if you are certifying a driver for the Windows Hardware Compatibility Program in 2021. For example for 64 bit Windows "codeql-win64.zip".

However the instructions on the github page for Windows-Driver-Developer-Supplemental-Tools (https://github.com/microsoft/Windows-Driver-Developer-Supplemental-Tools) state that the vresion should be 2.6.3.

> The main branch of this repo currently uses **[version 2.6.3 of the CodeQL CLI]**(https://github.com/github/codeql-cli-binaries/releases/tag/v2.6.3) and [version lgtm/1.29.0 of the CodeQL queries](https://github.com/github/codeql/releases/tag/lgtm%2Fv1.29.0). When using this repo to certify a driver, please use the appropriate sub-branch for the Windows release in question:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5660df59-18ee-441d-afc7-023da97a7da5
* Version Independent ID: 1e1c4d4d-7c4b-6af2-64f2-d51162a8992f
* Content: [CodeQL and the Static Tools Logo Test - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/static-tools-and-codeql)
* Content Source: [windows-driver-docs-pr/devtest/static-tools-and-codeql.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/static-tools-and-codeql.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ergins23 - Thanks for filing this issue, and this page had fallen behind the latest version information, which is available on the on the Windows-Driver-Developer-Supplemental-Tools (https://github.com/microsoft/Windows-Driver-Developer-Supplemental-Tools) as you mentioned. I checked with the developers, and we updated the directions here, to defer to that location, for the specifics on versioning, for the different use case scenarios. Thanks again for filing this issue and your interest in these important code security tools.
