### ISSUE TITLE
Levels not implemented for this platform

### ISSUE THREAD

**Issue by ctgucool** [MicrosoftDocs/windows-driver-docs#3058]
[Enter feedback here]
6: kd> !pte fffff806`4edd0000 
Levels not implemented for this platform

why it shows "Levels not implemented for this platform"
![image](https://user-images.githubusercontent.com/10549552/157788479-2f85f935-1e87-448e-a434-ae0954b5c5fb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c82454a6-31d6-0cd6-cdd0-f0cea6cea692
* Version Independent ID: 4ffb471c-91cc-5d06-93af-b8ec7c79dc3d
* Content: [pte (WinDbg) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-pte)
* Content Source: [windows-driver-docs-pr/debugger/-pte.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-pte.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ctgucool - Thanks for reaching out to our team. This particular mechanism is monitored by the men and women who write the driver documentation posted on doc.microsoft.com. Unfortunately, we don’t have the resources to help troubleshoot debugger development issues sent our way. In general, different processors may use multiple levels, or sets of PTE tables. For a complete description of PTE refer to Windows Internals - https://docs.microsoft.com/sysinternals/resources/windows-internals 
Your best bet for further questions, is to use one of the forums where other driver developers and Microsoft engineers can be found, such as Microsoft [Q&A](https://docs.microsoft.com/en-us/answers/products/). You can post your question there, and like-minded developers usually give feedback fairly quickly.
Again, thanks for reaching out. Best of luck with this issue.
