### ISSUE TITLE
The index title is not updated

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-driver-docs#3059]
![image](https://user-images.githubusercontent.com/39818609/157807462-1b93bb75-8f9b-4bcc-bcb8-f2b4d6154b56.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27a0ed90-dff4-f356-1853-de669b0d1540
* Version Independent ID: d846c2ad-9b05-8e61-45f0-19e50734f0f3
* Content: [Bluetooth version and profile support in Windows 11 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bluetooth/general-bluetooth-support-in-windows)
* Content Source: [windows-driver-docs-pr/bluetooth/general-bluetooth-support-in-windows.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bluetooth/general-bluetooth-support-in-windows.md)
* Product: **windows-hardware**
* Technology: **bluetooth**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @guliteb

Thank you for catching this! I've updated the TOC to fix the problem. I appreciate your help in making our docs better.

 ~ *Mark*
