### ISSUE TITLE
Table displaying incorrectly 

### ISSUE THREAD

**Issue by jamesxr23** [MicrosoftDocs/windows-driver-docs#3061]
The section for x86 flags should be displaying as a table- it is not (tested on chrome for iOS and macOS)

screenshots included 
![DA6BE03A-5026-498C-85D8-0F4C615F87FE](https://user-images.githubusercontent.com/98563429/157866393-53915d5d-8dd9-4d9e-a749-6a1c9eb4d107.png)
![9B111C47-6601-40FC-86D7-D937BBF30EE2](https://user-images.githubusercontent.com/98563429/157866404-fb58957b-d351-418a-a8cc-85493edb76a7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e381bf54-8ee1-404e-7c2e-68787eec6277
* Version Independent ID: 2717adc6-7e06-81de-6cb2-4a9c289edee1
* Content: [x86 Architecture - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/x86-architecture)
* Content Source: [windows-driver-docs-pr/debugger/x86-architecture.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/x86-architecture.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@jamesxr23 - Thanks for this issue. The table was not in a good state, so I recreated it and it now renders as it should.

If you ever feel inspired, you are welcome to submit a PR with fixes for something like this.

Thanks again for seeing this rendering problem and filing this issue.
