### ISSUE TITLE
Threading and Synch level for DxgkDdiCheckMultiPlaneOverlaySupport3 and related DDIs

### ISSUE THREAD

**Issue by saumyajyoti-mukherjee** [MicrosoftDocs/windows-driver-docs#3062]
[Enter feedback here]
Can you please add the level for DxgkDdiCheckMultiPlaneOverlaySupport3 and other CheckMPO related DDIs to this section? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbcb53fd-dfce-2444-c5a1-a4dab6d7f82b
* Version Independent ID: fcf91ea8-3dab-5b1c-00c2-bcea0eaabc18
* Content: [Threading and Synchronization Second Level - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/threading-and-synchronization-second-level)
* Content Source: [windows-driver-docs-pr/display/threading-and-synchronization-second-level.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/threading-and-synchronization-second-level.md)
* Product: **windows-hardware**
* Technology: **display**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@saumyajyoti-mukherjee, sorry for the slow response. The engineering team indicated the CheckMPO DDIs are considered [synchronization level 0](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/threading-and-synchronization-zero-level), so I've added them to that page.
