### ISSUE TITLE
Dead links in the AVStream docs

### ISSUE THREAD

**Issue by WubbaLubba** [MicrosoftDocs/windows-driver-docs#3065]
All the links for the Ks* functions and structures are dead, I also cannot find a working URLs for those items

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

 ID: 51c77433-e354-ec04-7cb5-12f123decacc
* Version Independent ID: 75a66828-0799-2c03-aee4-49e9b17d58b3
* Content: [AVStream Descriptors - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/avstream-descriptors)
* Content Source: [windows-driver-docs-pr/stream/avstream-descriptors.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/stream/avstream-descriptors.md)
* Product: **windows-hardware**
* Technology: **stream**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by tedhudek** [comment]
@wubbalubba thank you so much for reporting this.  Your report helped us track down a bug.  The content is restored now.
