### ISSUE TITLE
Verify multiple XML files.

### ISSUE THREAD

**Issue by trailfrenzy** [MicrosoftDocs/windows-driver-docs#3066]
[Enter feedback here]
How can TAEF be used to have a single test used multiple times with different XML files of my own format used for test?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 093ec1bc-a06f-caf8-612d-282ff95f3c05
* Version Independent ID: 8b44bfc3-362b-45c7-afc7-7f3982e6f0c0
* Content: [Data Driven Testing - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/taef/data-driven-testing)
* Content Source: [windows-driver-docs-pr/taef/data-driven-testing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/taef/data-driven-testing.md)
* Product: **windows-hardware**
* Technology: **taef**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@trailfrenzy - Thanks for reaching out to our team. This particular mechanism is monitored by the men and women who write the driver documentation posted on doc.microsoft.com. Unfortunately, we don’t have the resources to help troubleshoot test development issues sent our way.  

The topic, Simple Data Driven Test Example - https://docs.microsoft.com/en-us/windows-hardware/drivers/taef/simple-data-driven-test-example, describes an XML file that contains  data parameters for  data driven tests to consume, but that may not be exactly what you are after.

Your best bet for further questions, is to use one of the forums where other driver developers and Microsoft engineers can be found, such as Microsoft Q&A - https://docs.microsoft.com/en-us/answers/products/.

You can post your question there, and like-minded developers usually give feedback fairly quickly. Again, thanks for reaching out. Best of luck with this issue.
