### ISSUE TITLE
Please define NFC Acronym on first use

### ISSUE THREAD

**Issue by terryclancy** [MicrosoftDocs/windows-driver-docs#3078]
Please define NFC Acronym on first use

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cfc0bc8-e738-1954-20ea-dfddee3ccf74
* Version Independent ID: 39a2a02d-2c7c-3add-ba9f-0e49f29ac3f9
* Content: [NFC device drivers in Windows 10 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/nfc/what-s-new-in-nfc-device-drivers)
* Content Source: [windows-driver-docs-pr/nfc/what-s-new-in-nfc-device-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/nfc/what-s-new-in-nfc-device-drivers.md)
* Product: **windows-hardware**
* Technology: **nfc**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by mhopkins-msft** [comment]
Hi @terryclancy,

Thank you for reporting this issue. I've updated the topic to include the definition of NFC.

Thanks for helping to make our docs better!

 ~ *Mark*
