### ISSUE TITLE
upload a CAB package fail when I submit a new hardware

### ISSUE THREAD

**Issue by zyc0327** [MicrosoftDocs/windows-driver-docs#3080]
upload a CAB package fail when I submit a new hardware
![image](https://user-images.githubusercontent.com/38720296/160326743-523e62f5-aa85-4392-b9bf-7fc83bf7d949.png)

[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8cd895eb-8256-6ab7-532e-e7a8b20687f9
* Version Independent ID: 0c154e77-bb5f-5756-a6ed-a79afded39b3
* Content: [合作伙伴中心常见问题解答 - Windows drivers](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/dashboard/hardware-dashboard-faq)
* Content Source: [windows-driver-docs-pr/dashboard/hardware-dashboard-faq.yml](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-dashboard-faq.yml)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by mhopkins-msft** [comment]
Hi @zyc0327

Thanks for reaching out to our team. This particular mechanism is monitored by the men and women who write the driver documentation posted on doc.microsoft.com. Unfortunately, we don’t have the resources to help troubleshoot driver development issues sent our way.  
 
Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/). The other is the [OSR NTDEV forum](https://community.osr.com/categories/ntdev). You can post your question there, and like-minded developers usually give feedback fairly quickly. 

See the [Support from Microsoft](https://docs.microsoft.com/partner-center/support-from-microsoft) article for more support options for Partner Center. 
 
Again, thanks for reaching out. Best of luck with this issue. 
 
 ~ *Mark*
