### ISSUE TITLE
how can i get the afdkd extension?

### ISSUE THREAD

**Issue by AllenLu55** [MicrosoftDocs/windows-driver-docs#3081]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9137a562-85b3-1f71-e6c8-7a7f8a9e3ede
* Version Independent ID: 24e08394-a5ce-eb65-a24f-11847e69aef0
* Content: [Bug Check 0x156 WINSOCK_DETECTED_HUNG_CLOSESOCKET_LIVEDUMP - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x156--winsock-detected-hung-closesocket-livedump)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x156--winsock-detected-hung-closesocket-livedump.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x156--winsock-detected-hung-closesocket-livedump.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@AllenLu55 - Thanks for this issue. I added a note to mention that the debugger extensions mentioned for parameter one is only available to hardware partners. An alternative to that tool could be to use the NDIS kernel extension, for example the !ndiskd.protocols command as well as a traffic trace tool on the network the machine in question is connected to examine traffic in the timeframe leading up to the dump, if you are able to predict when the live dump occurs in your environment.  Good luck in solving your winsock live dump.
