### ISSUE TITLE
I don't know what "DCHU" stands for

### ISSUE THREAD

**Issue by rahul-ramadas** [MicrosoftDocs/windows-driver-docs#309]
The term "DCHU" is used in multiple places but I have no idea what it stands for. There isn't a single place on docs.microsoft.com where the abbreviation is expanded.

**Comment by tedhudek** [comment]
Thanks @rahul-ramadas for the tip. https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/getting-started-with-universal-drivers is where we lay out the 4 principles, but you are correct that we didn't actually spell out the acronym.  I've added a sentence to the page, right below the 4 bullet points, that should be live momentarily.
