### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by tcostin** [MicrosoftDocs/windows-driver-docs#3100]
Missing subcode 0x6000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de955911-dfbf-33b3-778a-767a5a578a0d
* Version Independent ID: 23fb5cbd-5f7d-f7ca-1622-5885020966c2
* Content: [Bug Check 0x1A MEMORY_MANAGEMENT - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x1a--memory-management)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@tcostin - Thanks for passing on that you are seeing a sub code  0x6000 for Bug Check 0x1A: MEMORY_MANAGEMENT
I have opened an internal work item to track this work, so closing this issue for now. We use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, we use data to work on updates for the most common error codes that impact the largest number of users. 

As you may be aware, much of memory failure troubleshooting is directed at finding and fixing, what is typically either a failed hardware memory component or a kernel mode driver that is not properly managing memory. The common tools are the Windows memory test and Driver Verifier. You may have success posting the specifics of your bug check issue in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html)

Thank you for your interest in improving our stop code docs, and good luck troubleshooting this memory error.
