### ISSUE TITLE
Windows Version List is incomplete

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs#3108]
While it'd be great if everyone moved to recent OS versions, the reality is that computers used in factory automation often run older builds that must still be supported. The Windows Version List given for inf2cat.exe omits older versions beyond a certain point, such as Server8_x64. Note that some examples on the same page make use of some of these "missing" version options.

The documentation for inf2cat.exe should be complete for developers, listing _all_ valid options; it is not the right place to push users to adopt newer Windows versions, however desirable that may be. Perhaps obsolete versions could be marked in the table by a footnote if necessary, but please include the full set of valid options for those of us required to support older OS versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0afbc04b-349a-57ed-eeb0-3d2cd28e359c
* Version Independent ID: de61f684-31d7-2de5-d66c-a3319f5198d9
* Content: [Inf2Cat - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/inf2cat)
* Content Source: [windows-driver-docs-pr/devtest/inf2cat.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/inf2cat.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@druske – Thanks for providing this input on adding additional information for non supported versions of Windows and pointing out that the samples are showing very old versions of Windows. The samples have been updated to show current versions of Windows. One option to consider is downloading a previous version of the WDK and checking the older “CHM” file that was previously distributed with the WDK. It should provide older OS version information. Information on downloading previous versions of the SDK and WDK is described in [Other WDK downloads](https://docs.microsoft.com/windows-hardware/drivers/other-wdk-downloads). You can also check to see if the command line help of the utility displays older Windows versions.

Thanks again for providing this input, and good luck with your use of Inf2Cat.
