### ISSUE TITLE
Microsoft MBIM voice extensions

### ISSUE THREAD

**Issue by aleksander0m** [MicrosoftDocs/windows-driver-docs#3111]
How come NITZ reporting is part of the "voice extensions"? Looks like they're completely orthogonal.

Also, the NITZ command is 10; is there any public document where all the other ids in the same service are defined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c15916-4538-8f39-d4e8-cca774d391b4
* Version Independent ID: 9b570f61-1355-9751-c77f-10435e24b718
* Content: [MB NITZ support - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/mb-nitz-support)
* Content Source: [windows-driver-docs-pr/network/mb-nitz-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/mb-nitz-support.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @aleksander0m. Voice services are no longer applicable in Windows. MBIM_CID_NITZ ended up being part of the UUID_VOICEEXTENSIONS service group for legacy reasons. We don't have public documentation that lists all CIDs belonging to each service.
Thanks for your question.
