### ISSUE TITLE
Conversion of KMDF(String Code) into UMDF 

### ISSUE THREAD

**Issue by RanjaniN-10** [MicrosoftDocs/windows-driver-docs#3113]
Hello,
          I have created the KMDF project to print the string and built it, I am about to convert this KMDF project to UMDF version . These are the procedures I have followed : 
1) Created the UMDF v2 , empty project in Visual Studio.
2) Copied the source and header file of KMDF and pasted it in UMDF v2.
3) While Building the solution I got errors regarding header files
4) After excluding the header shows new errors.

Attached the KMDF code and Converted UMDFV2 code for reference

#include "ntddk.h"

VOID Unload(IN PDRIVER_OBJECT DriverObject)
{
	DbgPrint("Driver unload \r\n");
}

NTSTATUS DriverEntry(IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
{
	UNICODE_STRING string = RTL_CONSTANT_STRING(L"HELLO DRIVER \r\n");
	//ANSI_STRING
	DriverObject->DriverUnload = Unload;
	DbgPrint("Hello world\r\n");
	DbgPrint("%wZ",&string);
	return STATUS_SUCCESS;
}

Converted UMDF code as below

#include "ntddk.h"
#include <windows.h>
#include <wdf.h>

VOID Unload(IN PDRIVER_OBJECT DriverObject)
{
	DbgPrint("Driver unload \r\n");
}

`NTSTATUS` DriverEntry(IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
{
	UNICODE_STRING string = RTL_CONSTANT_STRING(L"HELLO DRIVER \r\n");
	//ANSI_STRING
	DriverObject->DriverUnload = Unload;
	DbgPrint("Hello world\r\n");
	DbgPrint("%wZ",&string);
	return STATUS_SUCCESS;
`}`
Errors images are:
![UMDF_KMDF_1](https://user-images.githubusercontent.com/60179845/165449369-1cafff22-61f6-42d4-852c-a64c9d8fa8db.PNG)

After excluding the #include"ntddk.h" from the UMDF Code, could see the below errors:
![UMDF_KMDF](https://user-images.githubusercontent.com/60179845/165448619-0fc1a3db-2ed1-4b78-a109-917c50dd6a59.PNG)

Questions:
1)Should I add the ntddk.h header into the code?
2)If so, how to rectify the errors
3)If not, could you suggest with some usermode print statements

Thanks in advance
Ranjani N

**Comment by wm1** [comment]
`DECLARE_CONST_UNICODE_STRING`
