### ISSUE TITLE
Emphasize Latest CodeQL May Not Work With MS Queries

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs#3119]
Step 2 under "Download, install, and test CodeQL" does state "Refer to Windows Driver Developer Supplemental Tools for the latest information on the current version of the CodeQL tools."

Unfortunately, on the first attempt I glossed over that and downloaded the _current_ version of the CodeQL tools (2.9.0) from the linked CodeQL download page, which turned out to create a database too new for Microsoft's QL libraries. On the second attempt, I downloaded the version the version suggested on Microsoft's GitHub page for the Windows-Driver-Developer-Supplemental-Tools, 2.6.3... ah, but that's the README.md on the main branch, so that had the same issue. Finally, I switched to the WHCP_21H2 branch, where I learned that the version needed was 2.4.6.

You might save someone else a bit of time if the aforementioned step 2 said something like "Refer to Windows Driver Developer Supplemental Tools for the version of the CodeQL tools required for use with the desired branch of Microsoft's QL libraries (see the section "Clone the repository to access the driver-specific queries" below for a table that shows the available branches). Using a different version may result in a database incompatible with these libraries."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5660df59-18ee-441d-afc7-023da97a7da5
* Version Independent ID: 1e1c4d4d-7c4b-6af2-64f2-d51162a8992f
* Content: [CodeQL and the Static Tools Logo Test - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/static-tools-and-codeql)
* Content Source: [windows-driver-docs-pr/devtest/static-tools-and-codeql.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/static-tools-and-codeql.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by mhopkins-msft** [comment]
Hi @druske 

Thank you for bringing this to our attention. And thank you for sharing your experience.

I've updated the topic with your suggestions. The update should be published later today.

I appreciate your help with making our docs better!

 ~ *Mark*
