### ISSUE TITLE
"Specifying Binding Interfaces" page doesn't mention that NDIS LWF drivers cannot attach to an adapter that has only a nolower in its LowerRange.

### ISSUE THREAD

**Issue by MichaelVinc** [MicrosoftDocs/windows-driver-docs#3122]
Hi,

The "Specifying Binding Interfaces" page needs to mention that NDIS LWF drivers cannot attach to adapters that have nolower in their LowerRange of their INF file. Also it should mention other similar edge cases and limitations with the INF file of LWF drivers.
For example, it should also mention that NDIS LWF drivers are not allowed to have ndis5 in their lowerrange, or they are not allowed to have nolower in their FilterMediaTypes, and any other unsupported scenarios should be mentioned. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e508fac-9ca7-4405-c7a9-b98d34d74577
* Version Independent ID: 5f2c667d-a19b-b0af-3ce9-5ae61c7242ae
* Content: [Specifying Binding Interfaces - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/specifying-binding-interfaces)
* Content Source: [windows-driver-docs-pr/network/specifying-binding-interfaces.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/specifying-binding-interfaces.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @MichaelVinc,
Thanks for opening this issue. We've updated https://docs.microsoft.com/en-us/windows-hardware/drivers/network/specifying-binding-interfaces with the following note:
NDIS LWF drivers can't attach to adapters that have nolower in their LowerRange of their INF file. NDIS LWF drivers aren't allowed to have nolower in their FilterMediaTypes.
