### ISSUE TITLE
RtlInitUnicodeString(&sddlString, L"D:P(A;;GA;;;BA)(A;;GA;;;SY)(A;;GA;;;UD)"); status = WdfDeviceInitAssignSDDLString(DeviceInit, &sddlString);

### ISSUE THREAD

**Issue by AbbyMick** [MicrosoftDocs/windows-driver-docs#3123]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d66bf3e-c7a4-a87d-b848-33d56b3f31bc
* Version Independent ID: f1a750be-293c-158b-f583-ae848f98aa26
* Content: [Controlling Device Access - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/controlling-device-access)
* Content Source: [windows-driver-docs-pr/wdf/controlling-device-access.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/controlling-device-access.md)
* Product: **windows-hardware**
* Technology: **wdf**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Closing out due to lack of actionable feedback, please re-open with details if still needed - thank you!
