### ISSUE TITLE
TraceView no located at "tools\<Platform> subdirectory"

### ISSUE THREAD

**Issue by GF-Huang** [MicrosoftDocs/windows-driver-docs#3124]
https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/traceview.md

![image](https://user-images.githubusercontent.com/4510984/167016972-8f40a371-fd6e-422f-9a6a-d4aef8af9469.png)

![image](https://user-images.githubusercontent.com/4510984/167016896-4d8903ab-90e8-40ea-af59-5c3897221d40.png)

## And the WDK folder has no `tools` folder.

![image](https://user-images.githubusercontent.com/4510984/167017070-a4d919a8-51c5-4199-ab88-888c4d02fe78.png)

**Comment by DOMARS** [comment]
@GF-Huang - Thanks for passing on what you are seeing with the lack of the "tools" directory. I looked on three PCs where I have the WDK installed and the TraceView utility, was located in the tools directory. Perhaps there is an issue with the installation of the WDK in your environment.  It is important to note that the installation and use of the WDK requires the installation of the SDK as well as Visual Studio. These pre-requisites are described in [Download the Windows Driver Kit (WDK)](https://docs.microsoft.com/windows-hardware/drivers/download-the-wdk). 

For further troubleshooting of your setup, your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. Good luck with your use of the TraceView utility.

**Comment by GF-Huang** [comment]
I'm install WDK in a VM for testing, so I have not install VS in it.
