### ISSUE TITLE
Dead link in Virtual HID guide.

### ISSUE THREAD

**Issue by tyush** [MicrosoftDocs/windows-driver-docs#3125]
Hello,

In the related topics section of this article, there is a link labeled 'Human Interface Device". Clicking this link however redirects to the documentation homepage. I believe it is supposed to [this page](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/_hid/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88f27d9f-121d-b3f5-1671-73eb319f680e
* Version Independent ID: 0c61c804-1f2b-e62f-8d45-3322404905d3
* Content: [Write a HID source driver by using Virtual HID Framework (VHF) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/virtual-hid-framework--vhf-)
* Content Source: [windows-driver-docs-pr/hid/virtual-hid-framework--vhf-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/virtual-hid-framework--vhf-.md)
* Product: **windows-hardware**
* Technology: **hid**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thank you for your pull request.
