### ISSUE TITLE
Stated location of boot loader appears to be incorrect

### ISSUE THREAD

**Issue by Cogit8r** [MicrosoftDocs/windows-driver-docs#3126]
Document says "The boot loaders reside in the root directory of each Windows partition", whereas on my machine[^1] they[^2] reside at \Windows\system32.

[^1]:Win 10 32-bit | Win 10 64-bit | Win 7 multi-boot installation
[^2]:winload.exe in each case

As a noob troubleshooting boot issues and seeking to fully appreciate what's going on under the hood, anything that casts doubt is problematic, even though in this case I'm (reasonably) sure I know what was meant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bdfd88b-a990-ca6d-f6fa-ade70cfef2ec
* Version Independent ID: ebdf6525-b5cf-7151-fccd-7e187c049ac0
* Content: [Overview of Boot Options in Windows - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-options-in-windows)
* Content Source: [windows-driver-docs-pr/devtest/boot-options-in-windows.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/boot-options-in-windows.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Cogit8r - I updated this topic to reflect the changes in current day Windows. In addition to secure boot, the other big change is the growth of UEFI. For the complete story, see the latest version of "Windows Internals" - https://docs.microsoft.com/sysinternals/resources/windows-internals. Thanks for pointing this issue out and good luck with your explorations of the Windows OS.
