### ISSUE TITLE
VHLK download links are missing from docs..

### ISSUE THREAD

**Issue by LusKrew** [MicrosoftDocs/windows-driver-docs#3131]
The download links for VHLK are missing here:

https://docs.microsoft.com/en-us/windows-hardware/test/hlk/

Where are the download links?

**Comment by DOMARS** [comment]
@LusKrew - Thanks for reporting this. We are investigating this broken link.

**Comment by DOMARS** [comment]
@LusKrew - The links have been updated and should once again work as expected. Thanks again for reporting this issue!
