### ISSUE TITLE
You should remove "Sectigo (formerly Comodo) EV code signing certificate" from this page.

### ISSUE THREAD

**Issue by arbs-io** [MicrosoftDocs/windows-driver-docs#3133]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d3f097-d81b-66c2-4835-d63758687d34
* Version Independent ID: fe9d1cdd-966e-89b5-c66b-60531b0ec655
* Content: [Get a code signing certificate - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate)
* Content Source: [windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-a-code-signing-certificate.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by arbs-io** [comment]
I am unimpressed with the service. Support staff do not call back, and mails are not received when promised. Communication has been recorded, and I would like someone with some seniority to get involved. I would like sectigo to either reimburse funds or process the order and provide the certification, seeking legal action as the only alternative. This is very worrying that Microsoft are advocating this service.

**Comment by anaharris-ms** [comment]
@arbs-io I am so sorry you are experiencing this.  Let me check in to find someone who can help you. I will make sure your request gets through.

**Comment by anaharris-ms** [comment]
@arbs-io I am so sorry you are experiencing this.  We are currently doing a re-write of the doc set, and are updating our list. That company is no longer on it. Is there anything else I can help you with?

**Comment by arbs-io** [comment]
> @arbs-io I am so sorry you are experiencing this.  We are currently doing a re-write of the doc set, and are updating our list. That company is no longer on it. Is there anything else I can help you with?

Many thanks. I would not like others to be in the same situation. It would be great if Microsoft could issue code sign certs

**Comment by anaharris-ms** [comment]
#
