### ISSUE TITLE
ETA for WDK Visual Studio 2022?

### ISSUE THREAD

**Issue by svnscha** [MicrosoftDocs/windows-driver-docs#3136]
Hi team,

is there any ETA for a release of WDK using Visual Studio 2022?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **whats-new-and-downloads**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi Sven, you can actually do this now with the WIP (Windows Insider Preview) WDK.  See https://docs.microsoft.com/en-us/windows-hardware/drivers/installing-preview-versions-wdk for more info.  Hope this helps!
