### ISSUE TITLE
Version please

### ISSUE THREAD

**Issue by rogerbuckthal** [MicrosoftDocs/windows-driver-docs#3143]
[Enter feedback here]

What versions of Windows support these features?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa7357ae-898c-6d3e-c5b8-245bbc405ec3
* Version Independent ID: 41c7119e-28c4-ebc4-4a53-879bfde6ee09
* Content: [Fast Roaming with 802.11k, 802.11v, and 802.11r - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/fast-roaming-with-802-11k--802-11v--and-802-11r)
* Content Source: [windows-driver-docs-pr/network/fast-roaming-with-802-11k--802-11v--and-802-11r.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/fast-roaming-with-802-11k--802-11v--and-802-11r.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @rogerbuckthal,
Thanks for opening this issue. Unfortunately I haven't heard back from the development team on what Windows versions support fast roaming. 

You can try posting your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) or the OSR [NTDEV forum](https://community.osr.com/categories/ntdev). If you do find out version information, please let me know and I'll update this document.

Thank you.
