### ISSUE TITLE
Example fix only suited to Windows 10+

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs#3145]
Warning C30029's advice to use non-executable memory is excellent, but the example given on the page uses an API that is only available in Windows 10 or later. Advice on addressing this issue for drivers that must be compatible with earlier OS versions would be appreciated here: should the warning simply be suppressed, or is there another strategy that can be used to provide a mapping to non-executable memory prior to Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdbcb5a3-69e2-aa09-7311-cdc7dce8c04a
* Version Independent ID: cb040cf8-4b38-7cfe-7918-c08ca0cddc16
* Content: [C30029 warning - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/30029-memory-allocating-function-requests-executable-memory?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C30029)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue)
* Content Source: [windows-driver-docs-pr/devtest/30029-memory-allocating-function-requests-executable-memory.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/30029-memory-allocating-function-requests-executable-memory.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 

I don't know a way to duplicate this functionality with previous versions of Windows, but it would seem that it should be possible. There may be a way to check the memory to see if it is execute, but you would need to do that carefully. Perhaps something like the [ProbeForWrite function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-probeforwrite), although that seems to check user mode memory. There may be some related information in [NX Pool Compatibility Issues](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/nx-pool-compatibility-issues), although that is for pool memory.

Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly.
