### ISSUE TITLE
Are x86 and ARM kernel mode libraries really unavailable?

### ISSUE THREAD

**Issue by defrag257** [MicrosoftDocs/windows-driver-docs#3147]
The doc said that:

> The WDK comes from the same code base as Windows 11. Now that codebase only supports x64 and ARM64, the x86 and ARM kernel mode libraries are no longer produced. As a consequence there is not a natural way to provide a WDK that could build an x86/ARM driver.

However, in WDK 10.0.22621.1, x86 and ARM kernel mode libraries are still there. x86 and ARM targets are only blocked by &lt;Error&gt; tags in WindowsDriver.Common.targets. So the statement above definitely lies. So when would x86 and ARM kernel mode libraries be actually removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f2707a-07c4-dc75-8982-d4685ab6321e
* Version Independent ID: 21f2707a-07c4-dc75-8982-d4685ab6321e
* Content: [Windows 11, version 22H2 Support Matrix - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdk22h2-supportmatrix#feedback)
* Content Source: [windows-driver-docs-pr/wdk22h2-SupportMatrix.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdk22h2-SupportMatrix.md)
* Product: **windows-hardware**
* Technology: **whats-new-and-downloads**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @defrag257, sorry for the confusing info that was on the page referenced in the Document Details block above.  We've since removed that article and redirected it to the freshly updated https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk.  I invite you to take a look at the latter article and let us know if anything is still unclear.
