### ISSUE TITLE
Typo "&lt;Path&gt;"→"\<Path\>"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-driver-docs#3148]
Typo "&lt;Path&gt;"→"\<Path\>"
https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/toc.yml
https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/the-process-cannot-access-the-file---path---because-it-is-being-used-b

![the-process-cannot-access-the-file---path---because-it-is-being-used-b_e](https://user-images.githubusercontent.com/40815708/170910789-4d0d48e9-21d4-46cb-aed2-79c277bd5cd5.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad5a9cee-f564-9d14-7b62-83af4e5f38db
* Version Independent ID: f3d01737-54d5-6bf7-a1d1-7369339261bd
* Content: [Process cannot access file Path because it is being used by another process - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/the-process-cannot-access-the-file---path---because-it-is-being-used-b)
* Content Source: [windows-driver-docs-pr/devtest/the-process-cannot-access-the-file---path---because-it-is-being-used-b.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/the-process-cannot-access-the-file---path---because-it-is-being-used-b.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by tedhudek** [comment]
Thanks, Hiroshi, for reporting this, and for the PR.  This will be fixed within a few minutes at https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/the-process-cannot-access-the-file---path---because-it-is-being-used-b.
