### ISSUE TITLE
AssignmentSetOverride usage example

### ISSUE THREAD

**Issue by msudhakargit** [MicrosoftDocs/windows-driver-docs#3152]
[Enter feedback here]
It will be helpful to list an example on how to use "AssignmentSetOverride" in the INF.
An example in what endianness the values are listed (whether the values are listed left to right or otherwise)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63a9c4b1-f36a-e0ca-6951-7f6bd4228b43
* Version Independent ID: b5c0fac6-b184-b553-9f0b-0bb6f06caec4
* Content: [Interrupt Affinity - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/interrupt-affinity-and-priority)
* Content Source: [windows-driver-docs-pr/kernel/interrupt-affinity-and-priority.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/interrupt-affinity-and-priority.md)
* Product: **windows-hardware**
* Technology: **kernel**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @msudhakargit thanks for the feedback and apologies for the delay.

I've updated the second bullet point on https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/interrupt-affinity-and-priority to address your questions.  Hope this helps, and thanks again for your interest in the docs.

**Comment by msudhakargit** [comment]
Thanks Ted!
