### ISSUE TITLE
Do we need to re-test our base driver while including Extension INF? 

### ISSUE THREAD

**Issue by jbirdd1** [MicrosoftDocs/windows-driver-docs#3156]
I am writing from Intel regarding the Microsoft article that you contributed to, “Working with Extension INFs in the Partner Center”. 
[Working with Extension INFs in the Windows Hardware Dashboard - Windows drivers | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/submit-dashboard-extension-inf-files#submitting-and-publishing-extension-infs)

We are having a little trouble fully understanding this first step.
![image](https://user-images.githubusercontent.com/5588379/171747194-86fcdc72-7d79-4a3c-944a-e7fefbd7bc68.png)

I have run a HLK test certification on our newest Intel VROC driver, but we realized that we need to include an Extension INF with the driver package, which we have never done before. We already have passing HLK results for our base driver, but not with the Extension INF. 

Do we need to re-test our base driver including the Extension INF? Or, can we submit our driver and Extension INF to the Partner Center with our original base driver HLK test results (not including Extension INF while testing)? 

Thanks for your clarification,

Jessica Morton

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0a9a8d-f361-42ac-e2b5-a261cc8bf866
* Version Independent ID: e32caa38-e43b-c607-9bdc-b07bba983e14
* Content: [Working with Extension INFs in the Windows Hardware Dashboard - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/submit-dashboard-extension-inf-files#submitting-and-publishing-extension-infs)
* Content Source: [windows-driver-docs-pr/dashboard/submit-dashboard-extension-inf-files.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/submit-dashboard-extension-inf-files.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
@jbirdd1 Hi Jessica,

You'll need to test with your INF Extension and then remove the extension and just include the base driver for submission. So, you will need to retest  base driver with INF extension.
