### ISSUE TITLE
DPFLTR_MASK incorrect level

### ISSUE THREAD

**Issue by wintertims** [MicrosoftDocs/windows-driver-docs#3160]
The DPFLTR_MASK in the C++ snippet under the "Choosing the Correct Level" header is missing a zero in its hex representation.
![image](https://user-images.githubusercontent.com/51859987/172197390-3ad1ce60-e7c8-498c-b482-c6b6477fa905.png)

See the following link for context: https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/shared/dpfilter.h
In the link, the mask is set to the following:
![image](https://user-images.githubusercontent.com/51859987/172197513-a4639922-8792-484a-9049-5b825de8d249.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 208ae17f-4683-b616-cf19-144d51ad2e03
* Version Independent ID: 1658d2fa-00e0-b66a-8029-bda15b7ffb42
* Content: [Reading and Filtering Debugging Messages - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/reading-and-filtering-debugging-messages)
* Content Source: [windows-driver-docs-pr/debugger/reading-and-filtering-debugging-messages.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/reading-and-filtering-debugging-messages.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@wintertims - Thanks for the sharp eye, and it is indeed missing a zero to end up as 0x8000 0000. I updated the topic to fix this issue.  Good luck with your programming and use of the debugger!
