### ISSUE TITLE
"WinRT WiFiDirect class" need a way(API) to retrieve the publisher's AutoGO's SSID

### ISSUE THREAD

**Issue by yanfangliu-google** [MicrosoftDocs/windows-driver-docs#3162]
I am building a WIFIDirect APP with WinRT in C++. I can start an Auto GO(not legacy softAP mode) without problem and I can see the SSID by doing WIFI Scan with my phone. I want send this Auto GO's SSID to another device through BT or BLE(not just by eyes), but I can't find an API to query this local Auto GO's SSID. I wonder if this API is exist in WRT or not. If yes, what it is. If not, is there any plan MS will provide it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f123dfa-22cf-e183-1bbf-5ae9f5c5f3f3
* Version Independent ID: fe306b23-cf52-6a5b-1b05-b4bbe48505c1
* Content: [Wi-Fi Direct - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/partnerapps/wi-fi-direct)
* Content Source: [windows-driver-docs-pr/partnerapps/wi-fi-direct.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/partnerapps/wi-fi-direct.md)
* Product: **windows-hardware**
* Technology: **partnerapps**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
Thanks for filing this issue, @yanfangliu-google. The guidance you received from @stevewhims under the duplicate issue you filed in the winrt-api repo (https://github.com/MicrosoftDocs/winrt-api/issues/2235) is correct. I see already made an entry on the Microsoft Q & A site: 

https://docs.microsoft.com/en-us/answers/questions/885084/34wi-fi-direct-sample34-need-a-wayapi-to-retrieve.html

I'll close this issue as you have already engaged the community on Microsoft Q & A.
