### ISSUE TITLE
ECP Structure links pointing to old pages

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs#3165]
hey Lori!
AFAICS the following links point to the wrong place.
* NETWORK_APP_INSTANCE_ECP_CONTEXT
* NETWORK_OPEN_ECP_CONTEXT
* NETWORK_OPEN_ECP_CONTEXT_V0
* NFS_OPEN_ECP_CONTEXT
* PREFETCH_OPEN_ECP_CONTEXT
* SRV_OPEN_ECP_CONTEXT
* OPEN_REPARSE_LIST 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fe6d7e0-23be-145b-ee34-b92df88b3f29
* Version Independent ID: 63d4bdd3-6a36-15bf-2318-3340f295fb7d
* Content: [System-defined ECPs - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/system-defined-ecps)
* Content Source: [windows-driver-docs-pr/ifs/system-defined-ecps.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/system-defined-ecps.md)
* Product: **windows-hardware**
* Technology: **ifs**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi @rodwiddowson - I finally got around to updating this page to link to the current (and not "Previous Versions") ref pages. Thanks for reporting this. Have a great weekend!
