### ISSUE TITLE
HLK- Bluetooth Audio test

### ISSUE THREAD

**Issue by Tommy632070** [MicrosoftDocs/windows-driver-docs#3167]
Beause of 2435 RN52 Audio-Capable Radio Sled is not supply in furture , Can "Model 2435 BM62 Audio-Capable Radio Sled" replace "Model 2435 RN52 Audio-Capable Radio Sled" for folloing HLK tests?
[Enter feedback here]

<html>
<body>

Bluetooth - Audio - Check Sideband DDI
Bluetooth - Audio - Check Supported Codecs
Bluetooth - Audio - Offload path used
Bluetooth - Audio - Power cycle the sink device while playing music tone with A2DP offload
Bluetooth - Audio - Short constant music tone with A2DP offload
Bluetooth - Audio - Sink decrease music volume with A2DP offload
Bluetooth - Audio - Sink device disconnects and reconnects while playing music tone with A2DP offload
Bluetooth - Audio - Sink increase music volume with A2DP offload
Bluetooth - Audio - Source decrease music volume with A2DP offload
Bluetooth - Audio - Source device toggles music tone with A2DP offload
Bluetooth - Audio - Source increase music volume with A2DP offload
Bluetooth - Audio - Source radio disabled and re-enabled while playing music tone with A2DP offload
Bluetooth - Audio - Voice interrupt music with A2DP offload

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4c11ab-a434-e11c-6a24-02bad70af781
* Version Independent ID: 67879e43-296b-dc99-6aca-5413060db7d5
* Content: [Microsoft Bluetooth Test Platform supported hardware - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/bluetooth/testing-btp-hw)
* Content Source: [windows-driver-docs-pr/bluetooth/testing-BTP-hw.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bluetooth/testing-BTP-hw.md)
* Product: **windows-hardware**
* Technology: **bluetooth**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @Tommy632070,

Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive. 

- [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) 
- [OSR NTDEV forum](https://community.osr.com/categories/ntdev) 
 
Again, thanks for reaching out. Best of luck with this issue.

 ~ *Mark*
