### ISSUE TITLE
`Top-Level Collections Opened by Windows for System Use` table

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/windows-driver-docs#3172]
`Top-Level Collections Opened by Windows for System Use` table should be merged with [HID Clients Supported in Windows](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/hid-architecture#hid-clients-supported-in-windows) table since current version of `Top-Level Collections Opened by Windows for System Use` looks outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0abe5be4-090b-3b56-3f3a-7a72064aa78b
* Version Independent ID: a3bc0463-9079-8b1a-f643-b257b68b3438
* Content: [Top-Level Collections Opened by Windows for System Use - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/top-level-collections-opened-by-windows-for-system-use)
* Content Source: [windows-driver-docs-pr/hid/top-level-collections-opened-by-windows-for-system-use.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/top-level-collections-opened-by-windows-for-system-use.md)
* Product: **windows-hardware**
* Technology: **hid**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @DJm00n,

Thank you for this suggestion. I've created a work item to investigate combining these tables. Thanks, as always, for helping make our docs better!

 ~ *Mark*
