### ISSUE TITLE
Remarks section references a non-existent topic in Application Verifier help

### ISSUE THREAD

**Issue by cpowers534at** [MicrosoftDocs/windows-driver-docs#3178]
The remarks section says, "see "Setting Up a Debugger for Application Verifier" in the Application Verifier documentation."

However, the online Application Verifier documentation does not appear to have this material.  An online search for the phrase "Setting Up a Debugger for Application Verifier" will only return the reference in this document.  The App Verifier docs do not appear to have this content (checked here - https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/application-verifier ) even though it seems to be relevant as I was looking to resolve exactly the problem identified in the remarks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c88257d2-444f-9d2c-73e0-a120bcdbfbe1
* Version Independent ID: 3ebf16c7-7a23-0d52-c746-ed267162e3b6
* Content: [avrf (WinDbg) - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-avrf)
* Content Source: [windows-driver-docs-pr/debugger/-avrf.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-avrf.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@cpowers534at - Thanks for pointing this out, I updated the topic as some of the names of some of the docs sections have changed. As we have moved the CHM to online topics, I also added links to the primary new online topic related to debugger use.  Good luck with your use of AppVerif, and thanks again for filing this issue.
