### ISSUE TITLE
Please fix UDF - we are desperate!

### ISSUE THREAD

**Issue by dociouss** [MicrosoftDocs/windows-driver-docs#3181]
PLEASE fix Win 10/11 UDF file system compatibilty. You have broken partmgr.sys 6 months ago and it is a HUGE problem.

https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware/udf-windows-10-20h2-21h2-cfast-20-udf-arri-media/d8e6d013-91ac-4994-a8e2-537e25262846?messageId=56970643-82b1-4417-bb2d-9686d7293ff0

https://forum.arri.com/viewtopic.php?f=33&t=1445

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6291e57b-ab61-3dd1-8791-0ad796025093
* Version Independent ID: 0220be60-93d2-89ad-813c-dff09d33bdf4
* Content: [Bug Check 0x9B UDFS_FILE_SYSTEM - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x9b--udfs-file-system)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x9b--udfs-file-system.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x9b--udfs-file-system.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. To provide input on Windows, see this support article on the use of the feedback tool.  https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332
