### ISSUE TITLE
inproc option not working

### ISSUE THREAD

**Issue by 0xhellord** [MicrosoftDocs/windows-driver-docs#3184]
"Inproc:  Allow using an inproc Exdi-Server."
--
In fact, windbg (10.0.22000.194) can't understand this options when used with -kx edxi: args.

Is it a bug? Or by design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c2b03e3-2c9b-1b11-f55c-fae5f6e657ed
* Version Independent ID: 0c2b03e3-2c9b-1b11-f55c-fae5f6e657ed
* Content: [Configuring the EXDI Debugger Transport - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/configuring-the-exdi-debugger-transport)
* Content Source: [windows-driver-docs-pr/debugger/configuring-the-exdi-debugger-transport.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/configuring-the-exdi-debugger-transport.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 

From what I can tell, inproc should work with EXDI. If you don’t believe that to be the case, you could consider filing an issue here.

https://github.com/microsoftfeedback/WinDbg-Feedback/issues?q=is%3Aissue+is%3Aopen+exdi

I have mainly used the Powershell script to work with EXDI, so exploring using it would be one option, if this is an issue related to parsing of the command line parameter. Another idea would be trying both the current WinDbg preview, as well as the classic debugger, as there can be differences in their parameter processing.

To validate the Inproc functionality, and setting it up in a specific scenario, could be quite complex, from what I know about EXDI.  As the debugger in EXDI mode has very little knowledge of things like threads and processes as it would with a normal kernel debugger connection. So locating and setting a breakpoint to end up in the correct context to be where you want to be, is complex. Typically, you end up in a random Windows memory process when you break in with EXDI. Use of the search memory command might allow you to find a unique signature and determine how to find your way forward, but this too is complex, with modern Windows memory usage.  

For specific guidance, your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the OSR debugger forum. 
https://community.osr.com/categories/windbg  
There may be Intel or other hardware debugger vendor forums that have more expertise in raw memory debugging.  

Thanks for passing on what you are seeing with in process debugging and EXDI, and I will update the docs with any additional information on restrictions / limitations of inproc, or command line syntax recommendations I locate in the future.
