### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by computeronix** [MicrosoftDocs/windows-driver-docs#319]
On page https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/building-a-driver.md

CTRPP link points to https://perf.ctrpp  which currently does not resolve

I am not sure where this should point to, if that page is incorrect, but ran across this and wanted to point it out

**Comment by tedhudek** [comment]
Thanks @computeronix this is now fixed on https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/building-a-driver
