### ISSUE TITLE
How to Set _NT_SYMBOL_PATH

### ISSUE THREAD

**Issue by bsfinkel** [MicrosoftDocs/windows-driver-docs#3190]
I  have had some BSODs in Win 10 21H2.  I am running WinDbg, and I need to know how to download the symbols and then set the environmental variable _NT_SYMBOL_PATH.  This web page and its associated pages do not give this basic info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee388ff3-b1a4-1100-6026-bfc6c0ca72e8
* Version Independent ID: 3fae1e70-4d43-6a72-2d49-db00a0607fbc
* Content: [Setting Symbol and Executable Image Paths in WinDbg - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-symbol-and-source-paths-in-windbg)
* Content Source: [windows-driver-docs-pr/debugger/setting-symbol-and-source-paths-in-windbg.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-symbol-and-source-paths-in-windbg.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@bsfinkel - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 

Working with the kernel debugger and symbols has some complexity associated with it as there are multiple ways to set the symbols path. The main symbols page – [Symbols for Windows debugging](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symbols) offers this tip:

*Symbols can be loaded automatically using the .symfix (Set Symbol Store Path) command, as long as you have access to the internet while your debugger is running. Then use the .reload (Reload Module) command to load the symbols.*

For a walkthrough of setting the symbol path and working with the debugger, see [Debug Windows Drivers - Step by Step Lab (Echo Kernel-Mode)]( https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-).

For specific guidance, your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly.
