### ISSUE TITLE
Typo: my -> by

### ISSUE THREAD

**Issue by duanqn** [MicrosoftDocs/windows-driver-docs#3198]
The second paragraph in "Cause" section:

> This can happen because a NULL pointer dereferenced​ or a random incorrect address was accessed. This in turn can be caused my memory being freed prematurely​, or data structure corruption.

Here "caused my" should be "caused by".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19eb27e-40b0-c765-d826-8b9962e4c1e6
* Version Independent ID: f9231818-2d1d-be08-7ce2-92b97edd5613
* Content: [Bug Check 0x3B SYSTEM_SERVICE_EXCEPTION - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x3b--system-service-exception)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x3b--system-service-exception.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x3b--system-service-exception.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by tedhudek** [comment]
Thanks Qingnan, this is now fixed.  FYI if you see anything you want to fix in the future, you can also submit a pull request.  To do that, start by clicking the Edit button in the upper right of the page on docs.microsoft.com.
