### ISSUE TITLE
Please document `FsRtlKernelFsControlFile`

### ISSUE THREAD

**Issue by gabriellandau** [MicrosoftDocs/windows-driver-docs#3203]
Hello.  Microsoft [documentation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/kernel-extended-attributes#querying-update-sequence-number-journal-information) states that `FsRtlKernelFsControlFile` has been exported for public use, however there are no docs for it: https://github.com/MicrosoftDocs/windows-driver-docs/blob/5be2ff8200f7212f7100b1ea47c0c0bbe1ef60c3/windows-driver-docs-pr/ifs/kernel-extended-attributes.md?plain=1#L44

Could you please document it?  [Here](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/ntifs/nf-ntifs-fsrtlsetkerneleafile.md) is documentation for a related function, if you are looking for people who can do this.

While someone from that team is writing docs, it would be incredible if they could also please document `FsRtlQueryInformationFile`.

Stretch goal: Please document other `FsRtl` functions that are `PFILE_OBJECT` variants of `HANDLE`-based `Zw` functions.  Because it's [not always possible](https://community.osr.com/discussion/comment/246806/#Comment_246806) to create handles, these `FsRtl` functions are more reliable.

**Comment by gabriellandau** [comment]
Hrm.  I just realized that there's a separate repo for the DDI.  Should we move this to https://github.com/MicrosoftDocs/windows-driver-docs-ddi/issues?

**Comment by lorihollasch** [comment]
Hey @gabriellandau, thanks for reporting the missing pages. I just filed MicrosoftDocs/windows-driver-docs-ddi#1335 and cross-referenced this issue. Regarding your stretch goal: can you enumerate the other missing FsRtl functions?

**Comment by lorihollasch** [comment]
@gabriellandau, I've published pages for FsRtlKernelFsControlFile and FsRtlQueryInformationFile. Feel free to open a new issue with explicit list of other missing pages in [https://github.com/MicrosoftDocs/windows-driver-docs-ddi](https://github.com/MicrosoftDocs/windows-driver-docs-ddi)!

**Comment by gabriellandau** [comment]
Wow that was fast.  Thank you!

> Regarding your stretch goal: can you enumerate the other missing FsRtl functions?

Sorry, enumerating other undocumented FsRtl functions is in my backlog, but I have more-pressing tasks.  The two you just documented are the only ones I need at the moment.  Honestly I wasn't expecting any movement on this for at least a few months :)

If/when the need arises for more docs, I will be sure to file a bug in https://github.com/MicrosoftDocs/windows-driver-docs-ddi.  Thanks again @lorihollasch!
