### ISSUE TITLE
Link to JavaScript Debugger Scripting is missing / invalid

### ISSUE THREAD

**Issue by bialpio** [MicrosoftDocs/windows-driver-docs#3216]
The page describes scripting windbg using JavaScript. The last sentence in section [Using JavaScript to Extend the Capabilities of the Debugger](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-engine-and-extension-apis#using-javascript-to-extend-the-capabilities-of-the-debugger)) attempts to link to another page, but the link is invalid / missing. Based on web search, the link should point to https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/javascript-debugger-scripting.

Quote from the section (formatted as code so that GH markdown formatting doesn't interfere):
`For more information, see [JavaScript Debugger Scripting] (javascript-debugger-scripting.md).`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f40b90fc-2b24-c5d7-833c-6463ddfc5c57
* Version Independent ID: 6f9f9f84-5bc1-2e44-323a-181f4d0b1f0d
* Content: [Debugger Programming Extension APIs - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-engine-and-extension-apis)
* Content Source: [windows-driver-docs-pr/debugger/debugger-engine-and-extension-apis.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugger-engine-and-extension-apis.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@bialpio - Thanks for pointing out this broken link. It looks like a carriage return somehow ended up in the link. In any event, the link is fixed, and that will make this topic more useful for the next reader. Thanks again for filing this issue.
