### ISSUE TITLE
Netmon and Message Analyser is no longer available, Xperf shows no USB traces - Is there a replacement?

### ISSUE THREAD

**Issue by Donovand4** [MicrosoftDocs/windows-driver-docs#3219]
Hi All,
Netmon and message analyser was deprecated. Are there any replacements? Xperf unfortunately does not show any USB events in Windows 11 using the documented traces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5215605-0c7b-69fc-491d-bc4cce6f5eb7
* Version Independent ID: 419fdb45-42cb-c20f-6e2e-4047e6e41552
* Content: [Debugging USB device issues by using ETW events - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/best-practices--debugging-usb-device-problems)
* Content Source: [windows-driver-docs-pr/usbcon/best-practices--debugging-usb-device-problems.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/best-practices--debugging-usb-device-problems.md)
* Product: **windows-hardware**
* Technology: **usbcon**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @Donovand4,

Thank you for reaching out to us regarding a replacement for Netmon or Microsoft Message Analyzer. The following post on the Message Analyzer Blog recommends using a third-party network monitoring tool, such as Wireshark.

https://docs.microsoft.com/en-us/openspecs/blog/ms-winintbloglp/dd98b93c-0a75-4eb0-b92e-e760c502394f

I hope this helps.

Take care,
 ~ *Mark*
