### ISSUE TITLE
can not find provisioning tool: EnableUefiSbTest.exe from the WDK.

### ISSUE THREAD

**Issue by AnnLai7** [MicrosoftDocs/windows-driver-docs#3221]
Good day.
Could not find this provisioning tool: EnableUefiSbTest.exe after installed WDK.
Would you please kindly advise where can I get this tool?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0333999a-9689-42e4-e4c2-8e1dea13b149
* Version Independent ID: 0333999a-9689-42e4-e4c2-8e1dea13b149
* Content: [How to test drivers with Secure Boot enabled - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/preproduction-driver-signing-and-install)
* Content Source: [windows-driver-docs-pr/install/preproduction-driver-signing-and-install.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/preproduction-driver-signing-and-install.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by anaharris-ms** [comment]
Thanks for you question.  We will update the documentation to provide this information. In the meantime:

The .exe tool is located within the Windows Kits folder > tools > {arch} > SecureBoot > EnableSB. The default location during installation setup is C:\Program Files (x86)\Windows Kits\10\tools\{arch}\SecureBoot\EnableSB. Arch can be one of {am64, x86, arm, arm64}. 

The policies are located under the same SecureBoot directory > Policies (C:\Program Files (x86)\Windows Kits\10\tools\{arch}\SecureBoot\Policies). 

I hope this helps,
