### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mcspohrer** [MicrosoftDocs/windows-driver-docs#3229]
Additional members might include interface data and pointers to additional structures or routines that **anther** driver can call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7adb0e0b-0ab1-94b6-c643-286348588433
* Version Independent ID: b02d2738-9f80-b91b-b362-aa47b4757eac
* Content: [Using Driver-Defined Interfaces - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/using-driver-defined-interfaces)
* Content Source: [windows-driver-docs-pr/wdf/using-driver-defined-interfaces.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/using-driver-defined-interfaces.md)
* Product: **windows-hardware**
* Technology: **wdf**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @mcspohrer appreciate the feedback.  I just pushed a fix, should be live in a few minutes.

In the future note you can open a PR if you discover more issues like this. To get started just click Edit from the page on the Docs site, then Edit again from the GitHub page.
