### ISSUE TITLE
Deprecated  - Samples not found

### ISSUE THREAD

**Issue by jnrbo** [MicrosoftDocs/windows-driver-docs#323]
Some docs are deprecated, for example, the drivers - Sample GPD Files article says that **Samples are located in the \src\print\mini subdirectory of the directory tree that contains the WDK**  

Article: [Sample GPD Files](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/sample-gpd-files)

I believe that the folder is [this one](https://github.com/Microsoft/Windows-driver-samples/tree/master/print/XPSDrvSmpl) but i'm not sure;

**Comment by barrygolden** [comment]
Added a list of print samples on GitHub to the [Sample GPD Files ](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/sample-gpd-files) topic that illustrate the use of GPD files, including:

-   [OEM printer customization plug-in samples](https://go.microsoft.com/fwlink/?linkid=862105)
-   [Print auto-configuration sample](http://go.microsoft.com/fwlink/p/?LinkId=617938)
-   [USB host-based print driver sample](http://go.microsoft.com/fwlink/p/?LinkId=617947)
-   [XPS rasterization filter service sample](http://go.microsoft.com/fwlink/p/?LinkId=617951)
-   [XPSDrv driver and filter sample](http://go.microsoft.com/fwlink/p/?LinkId=617950)
