### ISSUE TITLE
how can I create a connetion of pp2p which using c/c++ on windows?

### ISSUE THREAD

**Issue by GitSoftwareNow** [MicrosoftDocs/windows-driver-docs#3240]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2dbc342-5e8a-1686-cb4d-c41cce743011
* Version Independent ID: 2ec5bb36-6bb8-96f8-a610-d0788b708667
* Content: [NDISWAN Overview - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/ndiswan-overview)
* Content Source: [windows-driver-docs-pr/network/ndiswan-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/ndiswan-overview.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by tedhudek** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team.  You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

* [windows-hardware-wdk](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk.html)
* [OSR's NTDEV forum](https://community.osr.com/categories/ntdev)
