### ISSUE TITLE
Hyperlink error

### ISSUE THREAD

**Issue by Siliva-li** [MicrosoftDocs/windows-driver-docs#3246]
[Enter feedback here]

"Power Management for Network Devices"  Hyperlink error, It will go to address (https://developer.microsoft.com/zh-cn/windows/hardware/)
[Power Management for Network Devices](https://go.microsoft.com/fwlink/p/?linkid=9945)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bbc7ada-6164-e3d7-6a22-37cf93a370d6
* Version Independent ID: e937b012-a3ac-c1e8-8394-d5731e01ff37
* Content: [About Network Wake-Up Events - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/network-wake-up-events#feedback)
* Content Source: [windows-driver-docs-pr/network/network-wake-up-events.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/network-wake-up-events.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @Siliva-li,
Thanks for opening this issue. The topic link you mention has been deprecated, so we removed the link. 
For updated info, please see the pages under the following sections:
[Power Management (NDIS 6.30)](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/power-management--ndis-6-30-) 
[NDIS Power Management Overview](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/ndis-power-management-overview)
