### ISSUE TITLE
Need to remove usbdeview from recommendations list. Old, unmaintained, not updated to recognize USB 3.1, 3.2, 4.0, Thunderbolt 3/4

### ISSUE THREAD

**Issue by cmccane** [MicrosoftDocs/windows-driver-docs#3249]
Need to remove usbdeview from recommendations list. Old, unmaintained, not updated to recognize USB 3.1, 3.2, 4.0, Thunderbolt 3/4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94f202cf-716f-b82b-1eba-31e4226cbb4f
* Version Independent ID: c8ee74d1-b7f8-4807-b36f-1071ee68a30a
* Content: [USBView in Windows - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/usbview)
* Content Source: [windows-driver-docs-pr/debugger/usbview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/usbview.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@cmccane - Thanks for this input on USBView not understanding the latest feature of the newer USB technologies. I added a note to the topic about this and that highlights the use of alternatives, such as DeviceManager to display additional information from later versions of USB. The note points to the list of IOCTLs that USBView uses. As sometimes you just need basic information about which hub your device is connected to, even without being updated, USBView is still usable in those situations. For more advanced work, USB driver developers tend to use specific hardware, for example the MUTT tool described in [Overview of Microsoft USB Test Tool (MUTT) devices](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/microsoft-usb-test-tool--mutt--devices). Or domain specific tools, such as the [HID Descriptor Tool](https://www.usb.org/document-library/hid-descriptor-tool) and the other tools provided by usb.org. There are also various third party programs and protocol analyzers available. Thanks again for providing this input on USBView, and good luck with your USB debugging work.
