### ISSUE TITLE
Missing documentation for RSS indirection table setting

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs#326]
Hi,

The [OID_GEN_RECEIVE_SCALE_CAPABILITIES](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-receive-scale-capabilities) documentation misses any description of the set operaton, which is valid according to https://docs.microsoft.com/en-us/windows-hardware/drivers/network/rss-configuration .

**Comment by I-gor-C** [comment]
Looks like I confused OID_GEN_RECEIVE_SCALE_PARAMETERS with OID_GEN_RECEIVE_SCALE_CAPABILITIES.

**Comment by duncanmacmichael** [comment]
No worries @I-gor-C , thanks for keeping an eye out!
