### ISSUE TITLE
Special user-mode APC not listed in Types of APCs

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-driver-docs#3262]
The [QueueUserAPC2](https://docs.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-queueuserapc2) function in Win32 can queue a special user-mode APC:

> Special user-mode APCs always execute, even if the target thread is not in an alertable state. 

That contradicts the statement in the "Types of APCs" article:

> User APCs run strictly in user mode and only when the current thread is in an alertable wait state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3889b6c4-d727-7712-6341-0dbd18fd36db
* Version Independent ID: bb31da4d-2c60-ef92-a2cd-8b6b4ddfbf14
* Content: [Types of APCs - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/types-of-apcs)
* Content Source: [windows-driver-docs-pr/kernel/types-of-apcs.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/types-of-apcs.md)
* Product: **windows-hardware**
* Technology: **kernel**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks Kalle, this is an interesting one.  I'm not an expert here, but I note that the paragraph on the Win32 page continues to say:

> Special user-mode APCs always execute, even if the target thread is not in an alertable state. For example, if the target thread is currently executing user-mode code, or if the target thread is currently performing an alertable wait, the target thread will be interrupted immediately for APC execution. If the target thread is executing a system call, or performing a non-alertable wait, the APC will be executed after the system call or non-alertable wait finishes (the wait is not interrupted).

Could the last sentence address the point on the kernel doc page?  Maybe the solution is to edit the Win32 page so that the first sentence says "will eventually execute but may be delayed if the target thread is not in an alertable state"

It sounds like it is guaranteed to run, just not necessarily right away.

**Comment by tedhudek** [comment]
Thanks, that seems plausible.  What doc change are you proposing?

**Comment by tedhudek** [comment]
Hi Kalle,

Thanks for summarizing the changes, and also for reviewing the other pages that you determined did not need updates.

The updates are now live on https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/types-of-apcs and https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/waits-and-apcs.

You can see the changes in ba6af516a71618dcd297028afec887a47f69d902.

Let me know if you see anything that you think we should change - and again, thanks for helping improve the docs!

Ted
