### ISSUE TITLE
If driver's device returns STATUS_UNSUCCESSFUL for  IRP_MN_QUERY_STOP_DEVICE

### ISSUE THREAD

**Issue by vivekkumars** [MicrosoftDocs/windows-driver-docs#3264]
[Enter feedback here]
The [page ](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/stopping-a-device-to-rebalance-resources) does not explain OS behavior if the driver's device returns STATUS_UNSSUCCESSFUL for  IRP_MN_QUERY_STOP_DEVICE.
Could you please add the expected behavior if the device returns STATUS_UNSSUCCESSFUL for  IRP_MN_QUERY_STOP_DEVICE?
How would OS perform resource rebalancing in this case?
Would it perform remove device operation?

Thanks
Vivek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82b15210-edf0-e2dc-5fb0-f8cb096e50b8
* Version Independent ID: 4cdba4f1-b7a6-d774-8347-859b932343c2
* Content: [Stopping a Device to Rebalance Resources - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/stopping-a-device-to-rebalance-resources)
* Content Source: [windows-driver-docs-pr/kernel/stopping-a-device-to-rebalance-resources.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/stopping-a-device-to-rebalance-resources.md)
* Product: **windows-hardware**
* Technology: **kernel**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi Vivek, sorry this took a while.  I just pushed an update to the page, you'll see a link to the commit in this PR soon and the fix will appear on the live page within 5-10 minutes.  Thanks for the report.
