### ISSUE TITLE
Debug 3236370568 

### ISSUE THREAD

**Issue by Vgapachecovgapacheco** [MicrosoftDocs/windows-driver-docs#3266]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4e4e08c-f56d-93b8-074d-e076ece21ce1
* Version Independent ID: c11a85db-a85f-0e18-5365-5c2f84ffc3c8
* Content: [ACPI Debugging - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/acpi-debugging)
* Content Source: [windows-driver-docs-pr/debugger/acpi-debugging.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/acpi-debugging.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
I don't see any feedback on this debugger documentation topic, so closing this issue. Thanks for your interest in our documentation.
