### ISSUE TITLE
WinDbg Preview - What's New page needs changelog updates and maybe a roadmap

### ISSUE THREAD

**Issue by nebulous999** [MicrosoftDocs/windows-driver-docs#3269]
The https://aka.ms/windbgwhatsnew page referenced in the description for WinDbg Preview in the Microsoft Store is there, but its changelog is not up to date.

As of today, the latest released version is **1.2206.19001.0**, but the latest version listed at https://aka.ms/windbgwhatsnew is **1.2107.13001.0**, which was released more than a year ago.  The changelog under the WinDbg Preview - What's New page page should be brought up to date with the latest release.

It would also be great if there were a general roadmap published for WinDbg Preview, so that the public has at least some idea of what changes are planned for it down the road.  WinDbg Preview is a great app, so hopefully there are plans to bring it out of preview some day, making it part of the Debugging Tools for Windows or Visual Studio.  It can often be difficult to access Microsoft Store apps in a corporate environment, especially in cases where Group Policy prevents employees from using the Microsoft Store, or developers are working on an isolated network without full Internet access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f37511-2b94-77e3-f8fb-a6a96dc15294
* Version Independent ID: 1d3a0c53-7b13-ff96-14dc-3bfa7acce718
* Content: [WinDbg Preview - What's New - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-what-is-new-preview)
* Content Source: [windows-driver-docs-pr/debugger/windbg-what-is-new-preview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/windbg-what-is-new-preview.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@nebulous999 - Thanks for this input on the what is new and updates to the change log for WinDbg Preview. I will pass this on to the product team, and I appreciate the input.  You may also consider filing product input on the WinDbg Preview feedback GitHub:  

http://aka.ms/dexex 

The suggestion for shipping WinDbg Preview outside of the store has been a popular one: 

[Ship WinDbg Preview outside of the Windows Store](https://github.com/microsoftfeedback/WinDbg-Feedback/issues/19)

The idea is that WinDbg Preview would be available in the form of an MSIX, and some of the comments on that issue relate to providing feedback on the packaging method.

You could also consider creating an issue on the idea of the product road map and planned enhancements. Some of the issues in the  Windbg Preview feedback GitHub are for suggested product enhancements, such as [UI for conditional breakpoints](https://github.com/microsoftfeedback/WinDbg-Feedback/issues/66). But of course, not every suggestion ends up on the product road map.
  
Thanks again for reaching out to the Windows Driver Developer Documentation team and providing this helpful feedback.
