### ISSUE TITLE
missing parameter

### ISSUE THREAD

**Issue by rhinotastic** [MicrosoftDocs/windows-driver-docs#3275]
The parameter 0x37 is not listed

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5923959-0f58-55fb-0c93-24b548539195
* Version Independent ID: 7e7c7000-8477-bfc8-4b28-2332074ec945
* Content: [Bug Check 0x10E VIDEO_MEMORY_MANAGEMENT_INTERNAL - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x10e---video-memory-management-internal)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x10e---video-memory-management-internal.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x10e---video-memory-management-internal.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@rhinotastic - Thanks for filing this issue and pointing out that there were missing parameters for this bug check. I expanded the list to include the addition parameters, including 0x37. Thanks again for this issue and good luck with your bug check troubleshooting.
