### ISSUE TITLE
TruncateMemory value has typo, is invalid hex number

### ISSUE THREAD

**Issue by NeilSandlin** [MicrosoftDocs/windows-driver-docs#3279]
The example given for executing a truncate memory command is currently:

bcdedit /set {18b123cd-2bf6-11db-bfae-00e018e2b8db} truncatememory Ox40000000

... where the first character of the hex number is the letter "O", and not the number zero as required. This command fails to execute.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b8e80b1-789d-942c-d2ea-f7b3af8df312
* Version Independent ID: b93ffbfc-b7a2-5f23-c5aa-0b56eea5b7a9
* Content: [Boot Parameters to Manipulate Memory - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-parameters-to-manipulate-memory)
* Content Source: [windows-driver-docs-pr/devtest/boot-parameters-to-manipulate-memory.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/boot-parameters-to-manipulate-memory.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@NeilSandlin - Thanks for seeing this error and filing an issue. It can be pretty annoying to track down why a copied command doesn't work. Should be fixed now, but let me know if I missed any of the occurrences of truncatememory with this issue.
