### ISSUE TITLE
TruncateMemory value has typo, is invalid hex number (part 2)

### ISSUE THREAD

**Issue by NeilSandlin** [MicrosoftDocs/windows-driver-docs#3280]
The example given for executing a truncate memory command is currently:

bcdedit /set {18b123cd-2bf6-11db-bfae-00e018e2b8db} truncatememory Ox40000000

... where the first character of the hex number is the letter "O", and not the number zero as required. This command fails to execute.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 714c21f8-cf12-3d98-f62a-cff0d326874e
* Version Independent ID: fc5eabc0-451e-1fe3-705b-d486c21cb334
* Content: [BCDEdit /set - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--set)
* Content Source: [windows-driver-docs-pr/devtest/bcdedit--set.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/bcdedit--set.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@NeilSandlin - Thanks for seeing this error and filing an issue. It can be pretty annoying to track down why a copied command doesn't work. Should be fixed now, but let me know if I missed any of the occurrences of truncatememory with this issue.
