### ISSUE TITLE
cant submit driver to sign

### ISSUE THREAD

**Issue by Archar123** [MicrosoftDocs/windows-driver-docs#3283]
Please Help Me:

We want to visit  [https://partner.microsoft.com/dashboard/hardware/Search]  use account [wei.zhao@mihoyo.onmicrosoft.com]
but show Deactivated, error info:

CorrelationID: 3cc3acef-4837-44ba-9ba9-42fdeaec39f9
Correlation Vector: eQjuPdU6iUyYKhFn.2
Date: 28 9月 2022 09:49:00 +00:00

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Version Independent ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Content: [Get support for Partner Center dashboard issues - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support#feedback)
* Content Source: [windows-driver-docs-pr/dashboard/hardware-submission-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-support.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
This appears to be an account issue. Please contact [Support](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support#technical-support-issues).
