### ISSUE TITLE
"Within the _ADR namespace"

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#3284]
Is it really accurate to state that the methods associated with PLDR must be "within the _ADR namespace"? Should it say "under the Device scope" instead?

"The ACPI firmware can define a PowerResource that implements the _RST method, and all devices that are affected by this reset method can refer to this PowerResource through a _PRR object defined u**nder their Device scope**.

**The device can declare a _PR3 object**. In this case, the ACPI driver will use D3cold power cycling to perform the reset, and reset dependencies between devices will be determined from the _PR3 object."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10ea54c7-7351-f265-eb95-d188544a2ced
* Version Independent ID: 99a7dd95-5ae7-4a61-0297-e4c6958ddbb1
* Content: [Bluetooth Radio Reset and Recovery - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/bluetooth/bluetooth-radio-error-recovery)
* Content Source: [windows-driver-docs-pr/bluetooth/bluetooth-radio-error-recovery.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bluetooth/bluetooth-radio-error-recovery.md)
* Product: **windows-hardware**
* Technology: **bluetooth**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @Shyamal-V,

I've updated this topic to be in line with the kernel topics it references. Thank you for helping make the docs better!

 ~ *Mark*
