### ISSUE TITLE
which wdk to install for windows-10-21h2 ?

### ISSUE THREAD

**Issue by AgeWise** [MicrosoftDocs/windows-driver-docs#3287]
https://stackoverflow.com/questions/73501935/which-wdk-to-install-for-windows-10-21h2

**Comment by 5ryde** [comment]
my nvidia gou id not showing

**Comment by 5ryde** [comment]
gpu

**Comment by tedhudek** [comment]
Thanks @AgeWise for the feedback.  I have just updated the table at https://learn.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads#step-2-install-the-wdk to include several Windows versions that were previously missing, including Windows 10, version 21H2.

Hope this helps!
