### ISSUE TITLE
Changing the MinimumStepPercentage  has no effect on Surface Studio PC

### ISSUE THREAD

**Issue by gagarine** [MicrosoftDocs/windows-driver-docs#3289]
By default on a Surface Studio the brightness controls key change the luminosity by 10 point. I want to change it to 1 point (like the volume key).

I tried to set `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\`*Monitor*`\Parameters\MinimumStepPercentage`  to 00000001 but this has no effect.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a138f9a6-8db1-6ed3-2612-65878d47d278
* Version Independent ID: 8b8d1bb9-afa6-df99-e56a-37e5bf5413ea
* Content: [Supporting Brightness Controls on Integrated Display Panels - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/display/supporting-brightness-controls-on-integrated-display-panels)
* Content Source: [windows-driver-docs-pr/display/supporting-brightness-controls-on-integrated-display-panels.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/supporting-brightness-controls-on-integrated-display-panels.md)
* Product: **windows-hardware**
* Technology: **display**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@gagarine , thanks for the issue. Only IHVs and OEMs could set the registry key cited on this page, and it was only valid on Windows Vista and Windows 7. I've updated the page accordingly. You can try asking your question on [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/products/) (if you search for "Surface brightness", you'll see some posts that might already answer your question).
