### ISSUE TITLE
Wrong Information regarding Parity Flag

### ISSUE THREAD

**Issue by RandomGuyOnTheInternet1234** [MicrosoftDocs/windows-driver-docs#3293]
The information on the parity flag is incorrect. If pf=0 then it is parity odd, and if pf=1 then it is parity even.

For example,
XOR AL, AL
OR AL, 2  ;(binary representation 00000010) yields pf=0 because there is only one bit set (and therefore it's parity odd).

XOR AL, AL
XOR AL, 3 ;(00000011) yields pf=1 because two bits are set (and therefore it's parity even).

This mistake also extends into the Windows debuggers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e381bf54-8ee1-404e-7c2e-68787eec6277
* Version Independent ID: 2717adc6-7e06-81de-6cb2-4a9c289edee1
* Content: [x86 Architecture - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/x86-architecture)
* Content Source: [windows-driver-docs-pr/debugger/x86-architecture.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/x86-architecture.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@RandomGuyOnTheInternet1234 - Thanks for seeing this error and filing this issue. I updated the topic to align with the Intel programming documentation, that also is reflected in the Parity Flag Wiki page - https://en.wikipedia.org/wiki/Parity_flag  

If you see issues in WinDbg you can use this git repo to communicate those to the dev team.

http://aka.ms/dexex 

As you did above, showing how to reproduce the specific problem in the smallest possible number of steps, is most helpful. Thanks again.
