### ISSUE TITLE
fix Dtrace install instructions, provide automated tool to complete steps

### ISSUE THREAD

**Issue by jpfreyen** [MicrosoftDocs/windows-driver-docs#3294]
![Screen Shot 2022-10-12 at 5 34 22 PM](https://user-images.githubusercontent.com/10945795/195472418-1031fb55-4fa5-49b2-a114-cfd954e898f0.png)

picture is worth a 1000 words
[Enter feedback here]

if u want to enable people to use your stuff, make it easy to install without these extra steps:

_Select the Complete install.
 _Important
Before using bcdedit to change boot information you may need to temporarily suspend Windows security features such as Patchguard, BitLocker and Secure Boot on the test PC. Re-enable these security features when testing is complete and appropriately manage the test PC, when the security features are disabled.
Enable DTrace on the machine using the bcdedit command.
cmd_

_Copy
bcdedit /set dtrace ON
When you update to a new Windows Insider build you will need to set the dtrace bcdedit option again.__

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98821045-8daa-85c6-37d0-001de9c1f79b
* Version Independent ID: 1956cfe8-6650-62c7-2388-584af7de2d96
* Content: [DTrace on Windows - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/dtrace)
* Content Source: [windows-driver-docs-pr/devtest/dtrace.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/dtrace.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@jpfreyen - Thanks for providing this input on the ease of use of the DTrace installer. The issues here focus on the documentation, but there is a Github site for DTrace where you can file this type of product input. If it is filed there, the product team will see your input.

https://github.com/microsoft/DTrace-on-Windows/issues

Thanks for your interest in the DTrace tool, and good luck with your Windows tracing.
