### ISSUE TITLE
Repeated steps under "Create and build a driver"

### ISSUE THREAD

**Issue by 3Dken** [MicrosoftDocs/windows-driver-docs#3298]
Steps 11, 12 and 13 seem to be repetitions of previous steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ebf2732-040f-8496-4583-11d341a25dbb
* Version Independent ID: c685bd0a-8f1a-9697-2ae9-425023ef8a47
* Content: [Write a Universal Windows driver (KMDF) based on a template - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-kmdf-driver-based-on-a-template?source=recommendations)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-kmdf-driver-based-on-a-template.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-kmdf-driver-based-on-a-template.md)
* Product: **windows-hardware**
* Technology: **gettingstarted**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by mhopkins-msft** [comment]
Hi @3Dken,

Thanks for bringing this to our attention. I've updated the page to remove the duplicate steps. The updated page should be published later today.

Thanks for helping us improve the docs!
 ~ *Mark*
