### ISSUE TITLE
Kernel debugging enabled by default?

### ISSUE THREAD

**Issue by nonbiologicalpet** [MicrosoftDocs/windows-driver-docs#3300]
This article explains how to enable or disable kernel debugging but doesn't include the default state of the value or the default state of kernel debugging if the value isn't present. I've had a hard time finding this information in docs. Could it be added here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0274ca5c-54ae-5a5b-545b-c80457c1fb51
* Version Independent ID: fa2d6842-ca2e-2cdb-5432-6acc65b35090
* Content: [BCDEdit /debug - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--debug)
* Content Source: [windows-driver-docs-pr/devtest/bcdedit--debug.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/bcdedit--debug.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@nonbiologicalpet - Thanks for this input on determining the state of the debugger enablement in Windows. I added information that describes using the [BCDEdit /dbgsettings](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--dbgsettings) command to display the current debugger settings. You may want to also use the `bcdedit /enum` command to display additional information. For an example of using these commands, one resource is the kernel echo driver tutorial - [Debug Windows Drivers - Step by Step Lab (Echo Kernel-Mode)](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-). Good luck with getting setup for kernel debugging and thanks again for providing this input.
