### ISSUE TITLE
idd_umdf_arch content is not correctly

### ISSUE THREAD

**Issue by javametro** [MicrosoftDocs/windows-driver-docs#3301]
page url: https://learn.microsoft.com/en-us/windows-hardware/drivers/display/indirect-display-driver-model-overview
file: images/idd_umdf_arch.png

the windows kernel graphics subsystem module name is DxgKrnl.sys not the pictured file name DxgKrnl.dll

my os version: 19044
![idd_umdf_arch](https://user-images.githubusercontent.com/8576736/196348424-e3ab6de1-8334-48c2-bf54-7ba0f5a0af90.png)

**Comment by lorihollasch** [comment]
Thanks for reporting this, @javametro - great catch! I've updated the diagram.
