### ISSUE TITLE
What about vs 2022 17.3? Does it support driver debugging?

### ISSUE THREAD

**Issue by terraslate** [MicrosoftDocs/windows-driver-docs#3303]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5930505f-6810-b2a2-86b5-3c678aae7f89
* Version Independent ID: 28315cf8-f06f-23ad-2088-9d51d08efe0d
* Content: [Download the Windows Driver Kit (WDK) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)
* Content Source: [windows-driver-docs-pr/download-the-wdk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md)
* Product: **windows-hardware**
* Technology: **whats-new-and-downloads**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @terraslate, thanks for the question and apologies for the delay.

This issue also affects VS 17.3.  I have updated https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk to reflect this.
