### ISSUE TITLE
Cloned system does not load sdbus- and sdstor-kerneldrivers

### ISSUE THREAD

**Issue by mailueberfalln** [MicrosoftDocs/windows-driver-docs#3306]
Please help me to fix this boot problem...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 755da3ab-b26a-d4f4-cdc8-c1b90f827535
* Version Independent ID: a4b04d8a-0cdc-0770-e5ab-01294ba5f066
* Content: [Bug Check 0x7B INACCESSIBLE_BOOT_DEVICE - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x7b--inaccessible-boot-device)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x7b--inaccessible-boot-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x7b--inaccessible-boot-device.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@mailueberfalln - This particular channel is monitored by the men and women who write the driver documentation posted on docs.microsoft.com/drivers. Though we'd like to, we don’t have the resources to provide support for specific scenarios. 

Your best bet is to use one of the forums where other driver developers and Microsoft engineers can be found. For example, the [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html). You can post your question there, and the community of developers usually give feedback fairly quickly. 

As the [Bug Check 0x7B INACCESSIBLE_BOOT_DEVICE - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x7b--inaccessible-boot-device) happens very early in the boot process, they can be very difficult to diagnosis. If you believe the hardware is functional, then seeing if you can extract a dump file may provide limited information. If you happen to be familiar with the kernel debugger, attaching a debugger and enabling boot debugging may provide clues but can be pretty difficult to configure.  Validating that the storage hardware supports Windows and the installation media works on different hardware may help narrow down the problem area.
