### ISSUE TITLE
UMDF V1 Docs

### ISSUE THREAD

**Issue by supperpiccle** [MicrosoftDocs/windows-driver-docs#3309]
I believe the instructions here for developing a usb driver using UMDF is for V1 instead of V2.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9e0ea0f-9b50-9b10-e159-b8841d61b65f
* Version Independent ID: 9e7f8cfd-1b54-0450-666b-02598fbf600c
* Content: [USB client driver code structure (UMDF) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/understanding-the-umdf-template-code-for-usb)
* Content Source: [windows-driver-docs-pr/usbcon/understanding-the-umdf-template-code-for-usb.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/understanding-the-umdf-template-code-for-usb.md)
* Product: **windows-hardware**
* Technology: **usbcon**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @supperpiccle,

Thank you for bringing this to my attention. I've created a work item to update this topic to us V2. I've added the work item to our content backlog.

Thank you for helping make the docs better!

 ~ *Mark*
