### ISSUE TITLE
user mode vs kernel mode:  software PROCESS or hardware PROCESSOR

### ISSUE THREAD

**Issue by jeffreyb0923** [MicrosoftDocs/windows-driver-docs#3310]
... in the second paragraph under "User mode," should the sentence, "A **processor** running in user mode ...," instead say "A **process** running in user mode ..." ? ... to distinguish a HARDware PROCESSOR from an ephemeral, transient collection of bit states otherwise known as a PROCESS ?  

Two misplaced letters can cause much confusion.  

Please know that I appreciate Microsoft's documentation VERY MUCH ! ! ! - it REALLY helps !

Sincerely yours,

JeffreyB

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a00526dc-0f04-4927-7e18-c07fd69ab9d5
* Version Independent ID: d87a7326-2a07-1eff-64c4-afcd8446c791
* Content: [User mode and kernel mode - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/user-mode-and-kernel-mode)
* Content Source: [windows-driver-docs-pr/gettingstarted/user-mode-and-kernel-mode.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/user-mode-and-kernel-mode.md)
* Product: **windows-hardware**
* Technology: **gettingstarted**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @jeffreyb0923. Thanks very much for letting us know about this issue. Yes, this should be "process". I've updated the article. Note: If you are looking for more info on the Windows OS, check out https://learn.microsoft.com/en-us/sysinternals/resources/windows-internals.

Glad to hear our documentation is helpful to you! 
Thanks again.
