### ISSUE TITLE
byte size of the field "Capabilities"

### ISSUE THREAD

**Issue by huangyechen** [MicrosoftDocs/windows-driver-docs#3314]
The size of the field "Capabilities" is 1 byte, but its description said that it should contain 2 bytes(Byte 0 – CAPABILITIES0 (0, 0x10) and Byte 1 – CAPABILITIES1 (0, 0x11). So what's the correct value?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b18cc48-caf5-cca0-1755-4c9c7e157364
* Version Independent ID: bda4b071-14e8-cf46-9226-ed315905848d
* Content: [Get NVDIMM-N Identification (Function Index 1) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/storage/get-nvdimm-n-identification--function-index-1-#feedback)
* Content Source: [windows-driver-docs-pr/storage/get-nvdimm-n-identification--function-index-1-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/get-nvdimm-n-identification--function-index-1-.md)
* Product: **windows-hardware**
* Technology: **storage**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for the issue, @huangyechen! I've updated the page to reflect 2 bytes per the spec (along with fixing a few other issues).
