### ISSUE TITLE
Corrupted tables

### ISSUE THREAD

**Issue by emuzychenko** [MicrosoftDocs/windows-driver-docs#3315]
Two tables are OK, but two others are just a plain text not organized into tables.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f65482df-ada5-2c80-0e7a-eda61546a1d2
* Version Independent ID: 869ded10-2185-378e-054b-f865065c6b7e
* Content: [Topology Pins - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/topology-pins)
* Content Source: [windows-driver-docs-pr/audio/topology-pins.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/topology-pins.md)
* Product: **windows-hardware**
* Technology: **audio**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@emuzychenko - Yes, thanks for reporting this issue with the text for the two tables. Somewhere along the table formatting fell out of this topic. I added it back in and that should help other readers, who had encountered these unorganized text strings. Thanks again!
