### ISSUE TITLE
Control GUIDs and Message GUIDs

### ISSUE THREAD

**Issue by wmmc88** [MicrosoftDocs/windows-driver-docs#3316]
> Each [trace provider](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/trace-provider) defines a control GUID that uniquely identifies the provider.

> A message GUID, or decode GUID, is a GUID assigned to the trace messages from a particular provider.

After I read these two statements, I assume it implies that there's a 1:1 mapping between control guids and message guids. Is that the case? If so, the documentation doesn't identify why there are two seperate guids exist. If its not the case, the documentation should clarify its wording.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e733907a-c70f-0f80-b317-f50fa1ba52dd
* Version Independent ID: 125ab56f-bba1-7f7d-8f17-59cd53ad41d6
* Content: [Message GUID - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/message-guid)
* Content Source: [windows-driver-docs-pr/devtest/message-guid.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/message-guid.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@wmmc88 - Thanks for this issue. I updated the topic to avoid the repeated use of the word "provider" as I see how that is confusing. The message GUID is used to create a mapping back to a formatting file. A class of trace provider types, for example all temperature sensors, might use the same type of message formatting, and the same Message GUID. The Control GUID is used to group and route messages. For example, multiple drivers from a single vendor, can be part of a single trace provider by specifying the same control GUID. So together, the two GUIDs provide a lot of flexibility to group and decode sets of trace messages and are two different things. Thanks for your interest in the driver trace docs.
