### ISSUE TITLE
Missing quotes in the BCDEdit Documentation

### ISSUE THREAD

**Issue by IndoProg** [MicrosoftDocs/windows-driver-docs#3320]
The documentation of BCDEdit omits quotes around the ID.
This leads to following error message:

`The delete command specified is not valid.
Run "bcdedit /?" for command line assistance.
The parameter is incorrect.`

Please add the double quotes to documentation so users can avoid this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2e888de-16af-86ce-3844-b55b519aea27
* Version Independent ID: 97cbb0fb-8c60-afe6-5170-0bfcc75a8613
* Content: [Adding Boot Entries - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/adding-boot-entries)
* Content Source: [windows-driver-docs-pr/devtest/adding-boot-entries.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/adding-boot-entries.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@IndoProg - The directions describe opening a command prompt, but for those that work with PowerShell I added this text: 

Note

If you are using [Windows PowerShell](https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/), you must use quotes around the boot entry identifier, for example: "{49916baf-0e08-11db-9af4-000bdbd316a0}" or "{current}". 

As you describe, this is an issue when referencing the boot ID GUID with PowerShell. Good luck with your use of BCDEdit.
