### ISSUE TITLE
when publishToWindows10s how do i chose the security measures and driver requirements with API

### ISSUE THREAD

**Issue by HaraldWang** [MicrosoftDocs/windows-driver-docs#3325]
[Enter feedback here]
when i use this API:https://manage.devcenter.microsoft.com/v2.0/my/hardware/products/{productID}/submissions/{submissionId}/shippingLabels
to create a shippinglabel, and this label support windows 10s. when i operater it in website, it must checked with the two option:
![image](https://user-images.githubusercontent.com/46599197/201065472-ab89f98c-2001-4b21-ba7c-4b6621f12ae3.png)

but when i use API to achieve these two option , i have only find the first one like that:
![image](https://user-images.githubusercontent.com/46599197/201065980-6a9e0b42-7a1c-4a8d-8688-bd59d08bf9d8.png)
 
and the second checkbox appears when the first one is checked. and i can not find the second one with API accomplish.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b72ba40-cd97-6f54-ec86-b7369b5db3de
* Version Independent ID: c52a67f0-9e83-9bb3-7811-4355e719d9a2
* Content: [Create a new shipping label - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/create-a-new-shipping-label)
* Content Source: [windows-driver-docs-pr/dashboard/create-a-new-shipping-label.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/create-a-new-shipping-label.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
Hi @HaraldWang: 

Just a few questions to help address your issue:

1 - Are you unable to publish at all due to this issue?
2 - Is there another issue you are having because you cannot access these two fields via the API?

Any more information on how this is impacting you will be of help!

Thanks!

**Comment by anaharris-ms** [comment]
Closing out due to inactivity.  Please reopen if still needed.  Thanks for reaching out!
