### ISSUE TITLE
Add IdenTrust Commercial CA 1 as Code Signing Supporting CA

### ISSUE THREAD

**Issue by mschambach** [MicrosoftDocs/windows-driver-docs#3326]
[Can you please provide details on how can we Add IdenTrust as CA supporting Code Signing Certificates?
mschambach@identrust.com  Thanks]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04c19d51-a948-b3ff-65c2-d8c54291b42f
* Version Independent ID: b5654182-fdcb-72c0-e5ae-536992731e98
* Content: [Cross-Certificates for Kernel Mode Code Signing - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/cross-certificates-for-kernel-mode-code-signing)
* Content Source: [windows-driver-docs-pr/install/cross-certificates-for-kernel-mode-code-signing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/cross-certificates-for-kernel-mode-code-signing.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi Marco, thanks for the question, apologies it took a while to get back to you.

To clarify, are you wanting IdenTrust to be able to issue kernel signing certificates for Windows? This program is now deprecated; signing through HDC is the only way to sign drivers to be trusted on Windows.

**Comment by tedhudek** [comment]
Closing out -- let me know if you had something different in mind and we can re-evaluate.

**Comment by mschambach** [comment]
Agreed. Thank you!
