### ISSUE TITLE
Unclear description

### ISSUE THREAD

**Issue by jasonchou519** [MicrosoftDocs/windows-driver-docs#3339]
[Enter feedback here]
"SR-IOV allows a device, such as a network adapter, to separate access to 'its' resources among various PCIe hardware functions. "

What does "its" means here, network adapter or SR-IOV ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19b1f1a3-dd47-4d16-c9db-f52009fcf8ff
* Version Independent ID: 3e95c1d5-b5e7-2928-7e6a-3e725e18b061
* Content: [Overview of Single Root I/O Virtualization (SR-IOV) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/overview-of-single-root-i-o-virtualization--sr-iov-)
* Content Source: [windows-driver-docs-pr/network/overview-of-single-root-i-o-virtualization--sr-iov-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/overview-of-single-root-i-o-virtualization--sr-iov-.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @jasonchou519, 
Thanks for opening this issue. "Its" refers to "a device, such as a network adapter". 
From https://learn.microsoft.com/en-us/windows-hardware/drivers/network/single-root-i-o-virtualization--sr-iov-: 
The SR-IOV specification from PCI-SIG defines the extensions to the PCI Express (PCIe) specification suite that enable multiple virtual machines (VMs) to share the same PCIe physical hardware resources. This section describes the NDIS SR-IOV interface and describes the techniques for writing an NDIS miniport driver for an SR-IOV capable network adapter that implements the PCIe SR-IOV specification.
If you have further questions or comments, please feel free to open a new GitHub issue.
Thanks again.
