### ISSUE TITLE
Clarification needed on MBIM_CID_MS_UICC_ACCESS_BINARY when NumberOfBytes = 0

### ISSUE THREAD

**Issue by aleksander0m** [MicrosoftDocs/windows-driver-docs#3340]
The MBIM_CID_MS_UICC_ACCESS_BINARY documentation says for the "NumberOfBytes" field the following:

> The number of bytes to be read. For example, a client driver could use this function to read a transparent (binary) file that is larger than 256 bytes, although the maximum amount that can be read or written in a single UICC operation is 256 bytes per the [ETSI TS 102 221 technical specification](https://go.microsoft.com/fwlink/p/?linkid=864594). It is the function's responsibility to split this into multiple APDUs and send back the result in a single response.

The problem is that it is not defined what should happen when NumberOfBytes = 0 in a request, and I have now seen different manufacturers do different things.

Some manufacturers will treat NumberOfBytes = 0 in the same way as P3=0 in the AT+CRSM=176,XXX,P1,P2,P3 operation, and therefore the read operation will return as many bytes as the SIM file being read has. In other words, the user doesn't need to know the exact file size (doesn't need to run MBIM_CID_MS_UICC_FILE_STATUS before issuing a MBIM_CID_MS_UICC_ACCESS_BINARY).

Some other manufacturers will treat NumberOfBytes = 0 as undefined behavior, and the amount of data returned by the read operation may even differ in two consecutive MBIM_CID_MS_UICC_ACCESS_BINARY calls. These manufacturers require the user to request for the exact file size (a MBIM_CID_MS_UICC_FILE_STATUS is therefore required before issuing a MBIM_CID_MS_UICC_ACCESS_BINARY).

An explicit clarification in the document of what the expected behavior is when NumberOfBytes = 0 in a MBIM_CID_MS_UICC_ACCESS_BINARY request would be helpful.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c31681f0-c52b-a074-af00-b63d0ba7c52d
* Version Independent ID: 4b4a4655-afed-9320-a98b-574dceefd742
* Content: [MB UICC application and file system access - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/mb-uicc-application-and-file-system-access)
* Content Source: [windows-driver-docs-pr/network/mb-uicc-application-and-file-system-access.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/mb-uicc-application-and-file-system-access.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @aleksander0m, 
Thank you so much for opening this issue regarding the case where NumberOfBytes = 0 in a request of MBIM_CID_MS_UICC_ACCESS_BINARY. After reviewing the documentation and Windows’ implementation, we agree with you that there is ambiguity in this case. 
The OS implements it in the same way as your first suggestion: “the read operation will return as many bytes as the SIM file being read has”. On the other hand, we worked with major cellular modem IHVs/manufactures when defining and implementing this CID. We have not heard any complaints from them. Testing and co-engineering with them have not turned up any misinterpretation yet. 
You mentioned that “some other manufacturers will treat NumberOfBytes = 0 as undefined behavior”. Can you tell us which manufacturers they are? We'd like to contact them directly to clarify, find out if they have upcoming releases, and whether they have executed and passed HLKs.

**Comment by aleksander0m** [comment]
> The OS implements it in the same way as your first suggestion: “the read operation will return as many bytes as the SIM file being read has”. On the other hand, we worked with major cellular modem IHVs/manufactures when defining and implementing this CID. We have not heard any complaints from them. Testing and co-engineering with them have not turned up any misinterpretation yet.

Thanks for confirming.

> You mentioned that “some other manufacturers will treat NumberOfBytes = 0 as undefined behavior”. Can you tell us which manufacturers they are? We'd like to contact them directly to clarify, find out if they have upcoming releases, and whether they have executed and passed HLKs.

I'll ask them to talk to Microsoft directly, thanks.

**Comment by zackfbc** [comment]
hi aviviano,

I checked our module has passed HLK included Win6_4.MB.GSM.Data.TestUiccAppAccess which will test MBIM_CID_MS_UICC_ACCESS_BINARY.
It seems MSFT admits it is fine to return 256 bytes data when OS does not set the read size. Furthermore MSFT has removed related HLK test of this MBIM in 22h2 OS version
![HLKgetEIDpass](https://user-images.githubusercontent.com/121547929/209792623-f3497217-8d0b-4466-b40f-348ea76effbb.jpg)

Could you help to confirm what's the expectation of MSFT ?

Thanks

**Comment by aviviano** [comment]
Hi @zackfbc,
Please clarify your comment: "**It seems MSFT admits it is fine** to return 256 bytes data when OS does not set the read size." Is your comment purely based on the reply to this thread, or is it from somewhere else? Instead of replying to this thread, you can email Sam on the development team with your response: shtang@microsoft.com
Thanks,
Amy

**Comment by zackfbc** [comment]
Hi @aviviano 

From the screenshot of the HLK test of Win6_4.MB.GSM.Data.TestUiccAppAccess, you could observe that modem returned 256 bytes of GID value and HLK verified it as pass. This is what I said "It seems MSFT admits it is fine..." .

Also I find Win6_4.MB.GSM.Data.TestUiccAppAccess is removed in 22H2 HLK test cases . Does it mean MSFT will not continue to optimize the definition of the related MBIM CID  ?

Thanks
Zack

**Comment by aviviano** [comment]
Hi @zackfbc, 
Thanks again for reaching out to the Windows Driver Developer Documentation team. Your questions regarding HLK tests and features go beyond documentation, and you'll need to contact a Microsoft developer for further help. Please email Sam: [shtang@microsoft.com](mailto:shtang@microsoft.com)
Thank you.
