### ISSUE TITLE
提交一个新的驱动验证，界面改为公司审核状态为挂起

### ISSUE THREAD

**Issue by fanl0227** [MicrosoftDocs/windows-driver-docs#3343]
如何解决？请回电13611048220，着急

帐户详细信息
帐户类型:公司
审核状态 挂起 了解详细信息
发布者 ID
卖家 ID:70747830
用户 ID:135956120

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Version Independent ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Content: [Get support for Partner Center dashboard issues - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support)
* Content Source: [windows-driver-docs-pr/dashboard/hardware-submission-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-support.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by tedhudek** [comment]
Sorry, we can only help with issues in English.
