### ISSUE TITLE
USB ETW and Power Management, needs additional informatio

### ISSUE THREAD

**Issue by TrailLessTravelled** [MicrosoftDocs/windows-driver-docs#3345]
[Enter feedback here]
I'm reading this page "USB ETW and Power Management", and was hoping to learn about USB and power management.  The page says "You can use USB ETW to examine USB devices and their drivers to validate whether they successfully go into selective suspend.", however missing from the document is this information.  There is a reference to the PowerCfg utility, but the utility documentation does not describe how to examine USB devices and their drivers, and neither does this article.  It would so so useful if an article reports that the PowerCfg utility can perform a function, if it gave some actionable information -- perhaps an example.  Otherwise, the reader, me, is left hanging with nothing other than the suggestion that I should go figure it out.

Please provide information for how to perform the stated functions listed in the article, it would be a big help.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 806c7138-93ba-9645-b903-f4935a3bcc30
* Version Independent ID: fa2f143a-9097-f9f4-2083-9f5cb62fdedf
* Content: [USB ETW and Power Management - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-etw-and-power-management)
* Content Source: [windows-driver-docs-pr/usbcon/usb-etw-and-power-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-etw-and-power-management.md)
* Product: **windows-hardware**
* Technology: **usbcon**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @TrailLessTravelled,

Thank you for your feedback on this article. I agree that it could have more detail about how to generate a power efficiency report. I've added an example of using the **/energy** switch to generate the report, as well as a link to a Microsoft Support article with more specific details. The updates should be published later today. I hope this helps.

Thank you for helping make the docs better!
 ~ *Mark*
