### ISSUE TITLE
Broken Channel 9 link

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#3349]
Link to "To watch a video that discusses the benefits of using NetAdapterCx, see the [Network Adapter Class Extension: Overview](https://learn.microsoft.com/en-us/teamblog/LearnTVAnnouncement) video on Channel 9." is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd35b88f-1f7d-c5fd-7193-8a02f608fc0f
* Version Independent ID: 6c75908e-24e3-4dbf-158d-8a0b6ceb0205
* Content: [Network Adapter WDF Class Extension (NetAdapterCx) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/netcx/)
* Content Source: [windows-driver-docs-pr/netcx/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/netcx/index.md)
* Product: **windows-hardware**
* Technology: **netcx**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @Shyamal-V,
We are aware of this issue and are working on restoring the video asap. In the meantime, you can view it via the Wayback Machine: [NetAdapter Extension for WDF, Part 1: Overview](https://web.archive.org/web/2020/https://channel9.msdn.com/Blogs/WinHEC/netadapterextensions1)
Thanks for opening this issue.
