### ISSUE TITLE
Inconsistent reference

### ISSUE THREAD

**Issue by mikepal2** [MicrosoftDocs/windows-driver-docs#3356]
This documentation page references DbgHelp Interface (https://learn.microsoft.com/en-us/windows/win32/debug/dbghelp-functions) but SymbolServerXxx functions are not documented there.

https://github.com/MicrosoftDocs/windows-driver-docs/blob/2fcdf46a86a17ba5782b2d893de60b005ea7539f/windows-driver-docs-pr/debugger/symbol-server-api.md?plain=1#L12

**Comment by DOMARS** [comment]
@mikepal2 - Thanks for this issue, this page was in need of some updates and it now no longer references those older APIs. In addition to changing the local DLL to acquire remote symbols from a server, I also added some links to other related options that are available, for example to change the server hosting using custom symbol servers. Other options on the server side, are the use of SymStore accessed via SymProxy to create custom symbol hosting. Good luck with your API work, and thanks for helping to improve the debugger API docs.
