### ISSUE TITLE
 ..\Services\Serial registry key is not specific enough, where is it?

### ISSUE THREAD

**Issue by ambanmba** [MicrosoftDocs/windows-driver-docs#3360]
[Enter feedback here]

 ..\Services\Serial registry key is not specific enough, where is it?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f610266-350e-bfa8-ba1f-d467f0f5088f
* Version Independent ID: e899e0d1-7969-646f-898a-04d063f41631
* Content: [Registry Settings for the Serial Service - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/serports/registry-settings-for-the-serial-service)
* Content Source: [windows-driver-docs-pr/serports/registry-settings-for-the-serial-service.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/serports/registry-settings-for-the-serial-service.md)
* Product: **windows-hardware**
* Technology: **serports**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ambanmba - My understanding is that with different versions of Windows, the exact location of the Services key may vary, but typically it ends up under HKLM. I added a link to [Registry Trees for Devices and Drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/overview-of-registry-trees-and-keys), that provides more information about the services key. I typically use search in regedit to locate registry keys to check their values, but avoid updating them directly using regedit. For these settings for traditional (non-USB) serial ports, I would also check and see if the control panel UI is available in device manager properties. The UI may provide beneficial range checking for the values that is not provided when editing them directly in the registry. If this is an add in PCI serial port card, I would also check if the vendor provided INF file would allow customization of these values during installation.
