### ISSUE TITLE
Why is the PDB required in the CAB package

### ISSUE THREAD

**Issue by alcosml** [MicrosoftDocs/windows-driver-docs#3372]
Why is it required to include the .pdb file in the .cab file for submission to Microsoft for hardware signing? The doc says it is used for debugging but the sample .ddf does not include it; also why would it be required in the submission? Is it because the driver .pdb is also uploaded to the MS public symbol server?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 674c6417-5a69-8fd5-be62-e4e06ba465be
* Version Independent ID: 674c6417-5a69-8fd5-be62-e4e06ba465be
* Content: [Attestation sign Windows 10+ drivers - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-attestation)
* Content Source: [windows-driver-docs-pr/dashboard/code-signing-attestation.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/code-signing-attestation.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
Hi @alcosml,

The .pdb is required because the symbols are loaded into a private server at MSFT which is then used by the automated crash analysis tools.

Hope that answers your question!
