### ISSUE TITLE
Fix values on "Keyboard Identifiers and Input Method Editors for Windows" page

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/windows-driver-docs#3388]
Some values on page [Keyboard Identifiers and Input Method Editors for Windows](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values) looks wrong:
Bulgarian `0x0030402` -> `0x0030402`
India `0x000004009` -> `0x00004009`

Please consider changing the keyboard identifier format to string format since it is used by [LoadKeyboardLayout](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadkeyboardlayoutw) and [GetKeyboardLayoutName](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardlayoutnamew) APIs.

Also list looks a bit outdated. Here is what I got on my Windows 10 21H2 19044.2486 with [this simple tool](https://gist.github.com/DJm00n/fa6d71a188289c200b5f92d83b5cf0a3):

| Keyboard                                     | Keyboard identifier (hexadecimal) |
|----------------------------------------------|-----------------------------------|
| ADLaM                                        | 0x00140c00                        |
| Albanian                                     | 0x0000041c                        |
| Arabic (101)                                 | 0x00000401                        |
| Arabic (102)                                 | 0x00010401                        |
| Arabic (102) AZERTY                          | 0x00020401                        |
| Armenian Eastern (Legacy)                    | 0x0000042b                        |
| Armenian Phonetic                            | 0x0002042b                        |
| Armenian Typewriter                          | 0x0003042b                        |
| Armenian Western (Legacy)                    | 0x0001042b                        |
| Assamese - INSCRIPT                          | 0x0000044d                        |
| Azerbaijani (Standard)                       | 0x0001042c                        |
| Azerbaijani Cyrillic                         | 0x0000082c                        |
| Azerbaijani Latin                            | 0x0000042c                        |
| Bangla                                       | 0x00000445                        |
| Bangla - INSCRIPT                            | 0x00020445                        |
| Bangla - INSCRIPT (Legacy)                   | 0x00010445                        |
| Bashkir                                      | 0x0000046d                        |
| Belarusian                                   | 0x00000423                        |
| Belgian (Comma)                              | 0x0001080c                        |
| Belgian (Period)                             | 0x00000813                        |
| Belgian French                               | 0x0000080c                        |
| Bosnian (Cyrillic)                           | 0x0000201a                        |
| Buginese                                     | 0x000b0c00                        |
| Bulgarian                                    | 0x00030402                        |
| Bulgarian (Latin)                            | 0x00010402                        |
| Bulgarian (Phonetic Traditional)             | 0x00040402                        |
| Bulgarian (Phonetic)                         | 0x00020402                        |
| Bulgarian (Typewriter)                       | 0x00000402                        |
| Canadian French                              | 0x00001009                        |
| Canadian French (Legacy)                     | 0x00000c0c                        |
| Canadian Multilingual Standard               | 0x00011009                        |
| Central Atlas Tamazight                      | 0x0000085f                        |
| Central Kurdish                              | 0x00000492                        |
| Cherokee Nation                              | 0x0000045c                        |
| Cherokee Phonetic                            | 0x0001045c                        |
| Chinese (Simplified) - US                    | 0x00000804                        |
| Chinese (Simplified, Singapore) - US         | 0x00001004                        |
| Chinese (Traditional) - US                   | 0x00000404                        |
| Chinese (Traditional, Hong Kong S.A.R.) - US | 0x00000c04                        |
| Chinese (Traditional, Macao S.A.R.) - US     | 0x00001404                        |
| Czech                                        | 0x00000405                        |
| Czech (QWERTY)                               | 0x00010405                        |
| Czech Programmers                            | 0x00020405                        |
| Danish                                       | 0x00000406                        |
| Devanagari - INSCRIPT                        | 0x00000439                        |
| Divehi Phonetic                              | 0x00000465                        |
| Divehi Typewriter                            | 0x00010465                        |
| Dutch                                        | 0x00000413                        |
| Dzongkha                                     | 0x00000C51                        |
| English (India)                              | 0x00004009                        |
| Estonian                                     | 0x00000425                        |
| Faeroese                                     | 0x00000438                        |
| Finnish                                      | 0x0000040b                        |
| Finnish with Sami                            | 0x0001083b                        |
| French                                       | 0x0000040c                        |
| Futhark                                      | 0x00120c00                        |
| Georgian (Ergonomic)                         | 0x00020437                        |
| Georgian (Legacy)                            | 0x00000437                        |
| Georgian (MES)                               | 0x00030437                        |
| Georgian (Old Alphabets)                     | 0x00040437                        |
| Georgian (QWERTY)                            | 0x00010437                        |
| German                                       | 0x00000407                        |
| German (IBM)                                 | 0x00010407                        |
| Gothic                                       | 0x000c0c00                        |
| Greek                                        | 0x00000408                        |
| Greek (220)                                  | 0x00010408                        |
| Greek (220) Latin                            | 0x00030408                        |
| Greek (319)                                  | 0x00020408                        |
| Greek (319) Latin                            | 0x00040408                        |
| Greek Latin                                  | 0x00050408                        |
| Greek Polytonic                              | 0x00060408                        |
| Greenlandic                                  | 0x0000046f                        |
| Guarani                                      | 0x00000474                        |
| Gujarati                                     | 0x00000447                        |
| Hausa                                        | 0x00000468                        |
| Hawaiian                                     | 0x00000475                        |
| Hebrew                                       | 0x0000040d                        |
| Hebrew (Standard)                            | 0x0002040d                        |
| Hindi Traditional                            | 0x00010439                        |
| Hungarian                                    | 0x0000040e                        |
| Hungarian 101-key                            | 0x0001040e                        |
| Icelandic                                    | 0x0000040f                        |
| Igbo                                         | 0x00000470                        |
| Inuktitut - Latin                            | 0x0000085d                        |
| Inuktitut - Naqittaut                        | 0x0001045d                        |
| Irish                                        | 0x00001809                        |
| Italian                                      | 0x00000410                        |
| Italian (142)                                | 0x00010410                        |
| Japanese                                     | 0x00000411                        |
| Javanese                                     | 0x00110c00                        |
| Kannada                                      | 0x0000044b                        |
| Kazakh                                       | 0x0000043f                        |
| Khmer                                        | 0x00000453                        |
| Khmer (NIDA)                                 | 0x00010453                        |
| Korean                                       | 0x00000412                        |
| Kyrgyz Cyrillic                              | 0x00000440                        |
| Lao                                          | 0x00000454                        |
| Latin American                               | 0x0000080a                        |
| Latvian                                      | 0x00000426                        |
| Latvian (QWERTY)                             | 0x00010426                        |
| Latvian (Standard)                           | 0x00020426                        |
| Lisu (Basic)                                 | 0x00070c00                        |
| Lisu (Standard)                              | 0x00080c00                        |
| Lithuanian                                   | 0x00010427                        |
| Lithuanian IBM                               | 0x00000427                        |
| Lithuanian Standard                          | 0x00020427                        |
| Luxembourgish                                | 0x0000046e                        |
| Macedonian (North Macedonia)                 | 0x0000042f                        |
| Macedonian (North Macedonia) - Standard      | 0x0001042f                        |
| Malayalam                                    | 0x0000044c                        |
| Maltese 47-Key                               | 0x0000043a                        |
| Maltese 48-Key                               | 0x0001043a                        |
| Maori                                        | 0x00000481                        |
| Marathi                                      | 0x0000044e                        |
| Mongolian (Mongolian Script)                 | 0x00000850                        |
| Mongolian Cyrillic                           | 0x00000450                        |
| Myanmar (Phonetic order)                     | 0x00010c00                        |
| Myanmar (Visual order)                       | 0x00130c00                        |
| Nepali                                       | 0x00000461                        |
| New Tai Lue                                  | 0x00020c00                        |
| Norwegian                                    | 0x00000414                        |
| Norwegian with Sami                          | 0x0000043b                        |
| N’Ko                                         | 0x00090c00                        |
| Odia                                         | 0x00000448                        |
| Ogham                                        | 0x00040c00                        |
| Ol Chiki                                     | 0x000d0c00                        |
| Old Italic                                   | 0x000f0c00                        |
| Osage                                        | 0x00150c00                        |
| Osmanya                                      | 0x000e0c00                        |
| Pashto (Afghanistan)                         | 0x00000463                        |
| Persian                                      | 0x00000429                        |
| Persian (Standard)                           | 0x00050429                        |
| Phags-pa                                     | 0x000a0c00                        |
| Polish (214)                                 | 0x00010415                        |
| Polish (Programmers)                         | 0x00000415                        |
| Portuguese                                   | 0x00000816                        |
| Portuguese (Brazil ABNT)                     | 0x00000416                        |
| Portuguese (Brazil ABNT2)                    | 0x00010416                        |
| Punjabi                                      | 0x00000446                        |
| Romanian (Legacy)                            | 0x00000418                        |
| Romanian (Programmers)                       | 0x00020418                        |
| Romanian (Standard)                          | 0x00010418                        |
| Russian                                      | 0x00000419                        |
| Russian (Typewriter)                         | 0x00010419                        |
| Russian - Mnemonic                           | 0x00020419                        |
| Sakha                                        | 0x00000485                        |
| Sami Extended Finland-Sweden                 | 0x0002083b                        |
| Sami Extended Norway                         | 0x0001043b                        |
| Scottish Gaelic                              | 0x00011809                        |
| Serbian (Cyrillic)                           | 0x00000c1a                        |
| Serbian (Latin)                              | 0x0000081a                        |
| Sesotho sa Leboa                             | 0x0000046c                        |
| Setswana                                     | 0x00000432                        |
| Sinhala                                      | 0x0000045b                        |
| Sinhala - Wij 9                              | 0x0001045b                        |
| Slovak                                       | 0x0000041b                        |
| Slovak (QWERTY)                              | 0x0001041b                        |
| Slovenian                                    | 0x00000424                        |
| Sora                                         | 0x00100c00                        |
| Sorbian Extended                             | 0x0001042e                        |
| Sorbian Standard                             | 0x0002042e                        |
| Sorbian Standard (Legacy)                    | 0x0000042e                        |
| Spanish                                      | 0x0000040a                        |
| Spanish Variation                            | 0x0001040a                        |
| Standard                                     | 0x0000041a                        |
| Swedish                                      | 0x0000041d                        |
| Swedish with Sami                            | 0x0000083b                        |
| Swiss French                                 | 0x0000100c                        |
| Swiss German                                 | 0x00000807                        |
| Syriac                                       | 0x0000045a                        |
| Syriac Phonetic                              | 0x0001045a                        |
| Tai Le                                       | 0x00030c00                        |
| Tajik                                        | 0x00000428                        |
| Tamil                                        | 0x00000449                        |
| Tamil 99                                     | 0x00020449                        |
| Tatar                                        | 0x00010444                        |
| Tatar (Legacy)                               | 0x00000444                        |
| Telugu                                       | 0x0000044a                        |
| Thai Kedmanee                                | 0x0000041e                        |
| Thai Kedmanee (non-ShiftLock)                | 0x0002041e                        |
| Thai Pattachote                              | 0x0001041e                        |
| Thai Pattachote (non-ShiftLock)              | 0x0003041e                        |
| Tibetan (PRC)                                | 0x00000451                        |
| Tibetan (PRC) - Updated                      | 0x00010451                        |
| Tifinagh (Basic)                             | 0x0000105f                        |
| Tifinagh (Extended)                          | 0x0001105f                        |
| Traditional Mongolian (Standard)             | 0x00010850                        |
| Turkish F                                    | 0x0001041f                        |
| Turkish Q                                    | 0x0000041f                        |
| Turkmen                                      | 0x00000442                        |
| US                                           | 0x00000409                        |
| US English Table for IBM Arabic 238_L        | 0x00050409                        |
| Ukrainian                                    | 0x00000422                        |
| Ukrainian (Enhanced)                         | 0x00020422                        |
| United Kingdom                               | 0x00000809                        |
| United Kingdom Extended                      | 0x00000452                        |
| United States-Dvorak                         | 0x00010409                        |
| United States-Dvorak for left hand           | 0x00030409                        |
| United States-Dvorak for right hand          | 0x00040409                        |
| United States-International                  | 0x00020409                        |
| Urdu                                         | 0x00000420                        |
| Uyghur                                       | 0x00010480                        |
| Uyghur (Legacy)                              | 0x00000480                        |
| Uzbek Cyrillic                               | 0x00000843                        |
| Vietnamese                                   | 0x0000042a                        |
| Wolof                                        | 0x00000488                        |
| Yoruba                                       | 0x0000046a                        |

See [diff with current version](https://www.diffchecker.com/n0ZkL2ZL/).

**Comment by mhopkins-msft** [comment]
Hi Dimitriy,

Thank you for reporting this, and for the handy tool you wrote! I was able to build and run the tool to verify your results.

FYI, instances of `layoutName` should be changed to `layoutDisplayName` in the `GetKeyboardLayoutDisplayName` function.

I'll keep this tool around for future use. I really appreciate your continued help improving the docs.

The doc page has been updated and should be published later today.

Thanks again!
 ~ *Mark*

**Comment by DJm00n** [comment]
>FYI, instances of layoutName should be changed to layoutDisplayName in the GetKeyboardLayoutDisplayName function.
oh, my bad. fixed it on gist.

>The doc page has been updated and should be published later today.
Thank you for a immediate feedback!
