### ISSUE TITLE
Error when executing commands in PowerShell

### ISSUE THREAD

**Issue by MadDenker** [MicrosoftDocs/windows-driver-docs#3392]
[Enter feedback here]
These commands, when entered into PowerShell, return an error:

```
At line:2 char:74
+ ...  trace -n usbtrace -p Microsoft-Windows-USB-USBXHCI (Default,PartialD ...
+                                                                 ~
Missing argument in parameter list.
At line:3 char:70
+ ... date trace -n usbtrace -p Microsoft-Windows-USB-UCX (Default,PartialD ...
+                                                                 ~
Missing argument in parameter list.
At line:4 char:74
+ ...  trace -n usbtrace -p Microsoft-Windows-USB-USBHUB3 (Default,PartialD ...
+                                                                 ~
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument


```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9064a690-442c-8ee0-0b29-34022148d9c9
* Version Independent ID: b7dc2f55-342b-d846-6617-b06fd9a35021
* Content: [How to capture a USB event trace with Logman - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/how-to-capture-a-usb-event-trace)
* Content Source: [windows-driver-docs-pr/usbcon/how-to-capture-a-usb-event-trace.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/how-to-capture-a-usb-event-trace.md)
* Product: **windows-hardware**
* Technology: **usbcon**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @MadDenker,

Thanks for reaching out to us.

This article uses the Windows command processor, **cmd**, as opposed to PowerShell. The first two steps in the instructions say:
_______________________________
1. Open a command-prompt window that has administrative privileges. To do so, select Start, type cmd in the search box, Select and hold (or right-click) cmd.exe, and then select Run as administrator.
2. In the command-prompt window, enter these commands to start a capture session:
...
_______________________________

When I run the commands from an elevated command prompt (aka "Run as administrator"), as the indicated in the article, they work as expected.

```console
Microsoft Windows [Version 10.0.22621.1105]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>logman create trace -n usbtrace -o %SystemRoot%\Tracing\usbtrace.etl -nb 128 640 -bs 128
The command completed successfully.

C:\Windows\System32>logman update trace -n usbtrace -p Microsoft-Windows-USB-USBXHCI (Default,PartialDataBusTrace)
The command completed successfully.

C:\Windows\System32>logman update trace -n usbtrace -p Microsoft-Windows-USB-UCX (Default,PartialDataBusTrace)
The command completed successfully.

C:\Windows\System32>logman update trace -n usbtrace -p Microsoft-Windows-USB-USBHUB3 (Default,PartialDataBusTrace)
The command completed successfully.

C:\Windows\System32>logman update trace -n usbtrace -p Microsoft-Windows-USB-USBPORT
The command completed successfully.

C:\Windows\System32>logman update trace -n usbtrace -p Microsoft-Windows-USB-USBHUB
The command completed successfully.

C:\Windows\System32>logman update trace -n usbtrace -p Microsoft-Windows-Kernel-IoTrace 0 2
The command completed successfully.

C:\Windows\System32>logman start -n usbtrace
The command completed successfully.

C:\Windows\System32>
```

Please use the Windows command processor to execute the commands in this article.

Thanks,
 ~ *Mark*
