### ISSUE TITLE
Table cells swapped in Boot screen components

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-driver-docs#3395]
In the "Boot screen components" article, there is a table that looks like this:

| BGRT | Firmware update display capsule | Reason |
|--|--|--|
| Pointer to Bitmap | Embedding the bitmap allows the capsule to be saved and restored in a single operation. | 0 |
| Does not contain video mode | Contains video mode | Done to avoid requiring the firmware to query video mode during UpdateCapsule call. |
| Contain a Status field | Does not contain a Status field | The Status field of the BGRT describes whether the image is currently displayed on the screen. This is not applicable to the firmware update display capsule. |

**The number 0 in the "Reason" column does not make sense.** I first thought that the table cells have been accidentally swapped, and that the table should be like this:

| BGRT | Firmware update display capsule | Reason |
|--|--|--|
| Pointer to Bitmap | 0 | Embedding the bitmap allows the capsule to be saved and restored in a single operation. |
| Does not contain video mode | Contains video mode | Done to avoid requiring the firmware to query video mode during UpdateCapsule call. |
| Contain a Status field | Does not contain a Status field | The Status field of the BGRT describes whether the image is currently displayed on the screen. This is not applicable to the firmware update display capsule. |

However, this would give the impression that Firmware update display capsule has a Pointer to Bitmap field whose value must be zero. AFAICT, Firmware update display capsule  does not have such a pointer field. I presume "Pointer to Bitmap" means the 64-bit "Image Address" field that is defined in [ACPI Specification 6.5 §5.2.23 Boot Graphics Resource Table (BGRT)](https://uefi.org/specs/ACPI/6.5/05_ACPI_Software_Programming_Model.html#boot-graphics-resource-table-bgrt). The "Reserved" field in Firmware update display capsule is only 8-bit and thus seems unlikely to be intended for possible future use as a pointer. Therefore, I think the table should say something like this:

| BGRT | Firmware update display capsule | Reason |
|--|--|--|
| Pointer to Bitmap | Embedded bitmap | Embedding the bitmap allows the capsule to be saved and restored in a single operation. |
| Does not contain video mode | Contains video mode | Done to avoid requiring the firmware to query video mode during UpdateCapsule call. |
| Contain a Status field | Does not contain a Status field | The Status field of the BGRT describes whether the image is currently displayed on the screen. This is not applicable to the firmware update display capsule. |

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca2c956b-1682-7c06-d68c-7c94da37007d
* Version Independent ID: 27245878-59d9-9018-3aee-327b5bc2abdd
* Content: [Boot screen components - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/bringup/boot-screen-components?source=recommendations)
* Content Source: [windows-driver-docs-pr/bringup/boot-screen-components.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/boot-screen-components.md)
* Product: **windows-hardware**
* Technology: **bringup**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@KalleOlaviNiemitalo, thanks for submitting a correction for the contents of the table. The topic has been updated per your recommended text.
