### ISSUE TITLE
The default keys changed on my machine.

### ISSUE THREAD

**Issue by centis** [MicrosoftDocs/windows-driver-docs#3399]
It looks like the combination on my machines is LSHIFT+RSHIFT+LMOUSE - which is a bit hard to type :)

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\kbdhid\crashdump
    Dump1Keys    REG_DWORD    0x11
    Dump2Key    REG_DWORD    0x1

I'm running the GA Win11.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b225392c-a057-a2b6-28be-a0939f4834ba
* Version Independent ID: d94f25da-8679-f2b0-ed24-4b40712bf695
* Content: [Forcing a system crash from the keyboard - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/forcing-a-system-crash-from-the-keyboard)
* Content Source: [windows-driver-docs-pr/debugger/forcing-a-system-crash-from-the-keyboard.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/forcing-a-system-crash-from-the-keyboard.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@centis - I guess those keys would be hard to accidently type, but agree that for most people and keyboards that is a difficult combination. Not sure if this feedback is more of an OS setting, but for Windows Debugger they have a GitHub site - http://aka.ms/dexex. For the OS, perhaps the regular feedback hub, described here- https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332
If there is anything else on this, perhaps you could follow up in work email, and we can brainstorm additional feedback ideas.
