### ISSUE TITLE
Clarify the section on recording host IP address for setting up KDNET with a VM

### ISSUE THREAD

**Issue by prayaas-a** [MicrosoftDocs/windows-driver-docs#3401]
One common rookie mistake when following the instructions on this page (that I have made repeatedly) is recording the IPv4 address from the wrong network adapter entry. On my host, I have a virtual ethernet switch named "Dbg". When I execute `ipconfig`, the last item on the list is: 

> **Ethernet adapter vEthernet (Default Switch (vEthernet (Dbg))):**
> 
>    Connection-specific DNS Suffix  . :
>    Link-local IPv6 Address . . . . . :
>    IPv4 Address. . . . . . . . . . . : 172.##.###.#
>    Subnet Mask . . . . . . . . . . . :
>    Default Gateway . . . . . . . . . :

that contains an IPv4 address on the internet (as opposed to the local network). The name, however, looks deceptively similar to the actual entry I'm looking for (that's a few pages up):

> **Ethernet adapter vEthernet (Dbg):**
> 
>    Connection-specific DNS Suffix  . :
>    Link-local IPv6 Address . . . . . :
>    IPv4 Address. . . . . . . . . . . : 192.168.0.239
>    Subnet Mask . . . . . . . . . . . :
>    Default Gateway . . . . . . . . . :

I'm not quite sure what's going on here with the first output - it looks like some sort of nested switch/bridge configuration. This confusion cost me some time trying to figure out why I couldn't ping the host from my VM or set up KDNET successfully with it.

Perhaps a "warning" label or note should be added in this section informing users that they may see multiple entries that _almost_ match, but that they should look for the string that's strictly "Ethernet adapter vEthernet (_<External_Switch_Name>_)".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9564a660-e978-17e0-b1ab-885eb9345046
* Version Independent ID: 97c67bc0-5e7d-01ff-f4ba-1c626820614c
* Content: [Setting Up Network Debugging of a Virtual Machine with KDNET - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-network-debugging-of-a-virtual-machine-host)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-network-debugging-of-a-virtual-machine-host.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-network-debugging-of-a-virtual-machine-host.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@prayaas-a - Yes, with virtual switches, tunneling and WiFi the list does get a bit long.  I added a tip to let others know that may be multiple entries with similar names and that you should be sure and locate the virtual switch that you created. Thanks for your interest in the debugger docs, and good luck with your VM debugging.
