### ISSUE TITLE
Audio/Visual Transmission with UDEs

### ISSUE THREAD

**Issue by jguy-mather** [MicrosoftDocs/windows-driver-docs#3402]
Does the following statement in the documentation indicate that audio/visual transmission is _not_ a supported capability of UDEs?

"In the implementation, the client driver must report whether it supports the requested capability. Certain capabilities are not supported by UDE such as static streams."

However, static streams and isochronous transfers seem to be referred to differently under the "Sending USB data transfers in USB client drivers" so it is not clear to me at the moment.

Any advice or assistance is appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9771a49-256b-7067-34e8-cdc0c24e4b5c
* Version Independent ID: 2648d38b-43ff-7b0a-14a4-baa34cead9fa
* Content: [Write a UDE client driver - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/writing-a-ude-client-driver)
* Content Source: [windows-driver-docs-pr/usbcon/writing-a-ude-client-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/writing-a-ude-client-driver.md)
* Product: **windows-hardware**
* Technology: **usbcon**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @jguy-mather 

Thanks for reaching out to the Windows driver developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation. 
 
Your best bet is to use one or both of the two really good forums where other driver developers and Microsoft engineers can be found. The first is the [NTDEV forum from OSR Online](https://community.osr.com/categories/ntdev). The other is the [Windows Q&A forums](https://learn.microsoft.com/en-us/answers/products/60/windows/).

You can post your question there, and like-minded developers usually give feedback fairly quickly.
 
Again, thanks for reaching out. Best of luck with this issue.

 ~ *Mark*
