### ISSUE TITLE
How to use Inproc option in EXDI

### ISSUE THREAD

**Issue by Zero-Tang** [MicrosoftDocs/windows-driver-docs#3410]
I added `Inproc` in configuring windbg command-line arguments
```
windbg.exe -v -kx exdi:CLSID={29f9906e-9dbe-4d4b-b0fb-6acf7fb6d014},Inproc
```
However, WinDbg says "The parameter is incorrect".
![image](https://user-images.githubusercontent.com/37060901/218487098-28cd7621-99a9-4206-93cc-04551651a3ea.png)
However, according to the [documentation](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/configuring-the-exdi-debugger-transport#exdi-windbg-load-parameters), this option should be available.
Am I using incorrect version of WinDbg?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c2b03e3-2c9b-1b11-f55c-fae5f6e657ed
* Version Independent ID: 0c2b03e3-2c9b-1b11-f55c-fae5f6e657ed
* Content: [Configuring the EXDI Debugger Transport - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/configuring-the-exdi-debugger-transport)
* Content Source: [windows-driver-docs-pr/debugger/configuring-the-exdi-debugger-transport.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/configuring-the-exdi-debugger-transport.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Zero-Tang - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation. You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. 

• [Hardware and Application Developers on Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-hardware-wdk-general.html)

As EXDI provides less information then KDNET connections, it can be challenging to configure. The target machine may not support Inproc or there may be other XML configuration information that is active depending on how you invoked the debugger.

If your target system is QEMU, there may be tracing on the target that you can configure to gather more information. 

https://www.qemu.org/docs/master/devel/tracing.html?highlight=debug

The .exdi command displays some information, but not sure if it would be possible to use it to determine if Inproc is supported on the target.

Good luck in hunting down why Inproc is not working in your environment. As EXDI provides less information then KDNET connections, it can be most challenging to configure.
