### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#3411]
Link to "[Configuring Object Reference Tracing](https://go.microsoft.com/fwlink/p/?linkid=153602)." is broken.

This appears to be the correct link - https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/configuring-object-reference-tracing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d908b64-8eb5-0f81-9dfb-c37531cf6fb2
* Version Independent ID: 67656bbc-ee43-1e23-9b4e-3a9303879523
* Content: [Object Reference Tracing with Tags - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/object-reference-tracing-with-tags?redirectedfrom=MSDN)
* Content Source: [windows-driver-docs-pr/kernel/object-reference-tracing-with-tags.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/object-reference-tracing-with-tags.md)
* Product: **windows-hardware**
* Technology: **kernel**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks Shyamal!  This is fixed now.
