### ISSUE TITLE
Update topic to address Server 2022

### ISSUE THREAD

**Issue by MSRobertD** [MicrosoftDocs/windows-driver-docs#3412]
At the topic of this topic, it calls out that Windows Server 2019 does not support Bluetooth out-of-box. In the related topic for Bluetooth support for earlier versions, it calls out that Windows Server 2016 also does not support Bluetooth out-of-box. Can these two topics be updated to address Windows Server 2022, and also the "evergreen" version of Windows Server (e.g. Microsoft Windows Server build 10.0.20348.1006)?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27a0ed90-dff4-f356-1853-de669b0d1540
* Version Independent ID: d846c2ad-9b05-8e61-45f0-19e50734f0f3
* Content: [Bluetooth version and profile support in Windows 11 - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/bluetooth/general-bluetooth-support-in-windows)
* Content Source: [windows-driver-docs-pr/bluetooth/general-bluetooth-support-in-windows.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bluetooth/general-bluetooth-support-in-windows.md)
* Product: **windows-hardware**
* Technology: **bluetooth**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @MSRobertD,

Thank you for contacting us. I've updated the topics to reflect that Bluetooth not supported by Windows Server out of the box. However, there may be drivers available from third-party IHVs.

Thanks for helping to make the docs better.

 ~ *Mark*
