### ISSUE TITLE
Broken links in Button reporting

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windows-driver-docs#3413]
At the bottom of the article, there are three links that don't work:

> **Note**  
> -   For full guidance and implementation for the Power button, see [Power Button Behaviors and implementation](https://learn.microsoft.com/en-us/collaborate/connect-redirect?DownloadID=47452).
> -   For Connected Standby guidance for buttons, see [Connected Standby Wake Sources](https://learn.microsoft.com/en-us/collaborate/connect-redirect?DownloadID=49891).
> -   For additional guidance on ACPI implementation, see [ACPI Design Guide](https://learn.microsoft.com/en-us/collaborate/connect-redirect?DownloadID=48755).

I don't know what "Power Button Behaviors and implementation" should point to.

For the last two, [Modern Standby wake sources](https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/modern-standby-wake-sources) and [ACPI design guide](https://learn.microsoft.com/en-us/windows-hardware/drivers/acpi/) may be the current equivalents.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f03919da-cafd-95df-107e-a7b8c227778f
* Version Independent ID: bfa59f04-ed25-86cd-c672-f4afebbe51c9
* Content: [Button reporting - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/gpiobtn/button-reporting)
* Content Source: [windows-driver-docs-pr/gpiobtn/button-reporting.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gpiobtn/button-reporting.md)
* Product: **windows-hardware**
* Technology: **gpiobtn**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @KalleOlaviNiemitalo thanks for the feedback.  I have updated the links in question.  The update should appear on the live site within a few minutes.  Thanks again for your interest in the docs!
