### ISSUE TITLE
Ambigous pages about GPUView command line paarameters

### ISSUE THREAD

**Issue by pbaykalov** [MicrosoftDocs/windows-driver-docs#3419]
https://learn.microsoft.com/en-us/windows-hardware/drivers/display/option-limit

https://learn.microsoft.com/en-us/windows-hardware/drivers/display/displaying-more-or-fewer-threads

These two pages clearly talk about different options yet the example of syntax is the same. Can you please clarify the difference?

**Comment by lorihollasch** [comment]
Great catch, @pbaykalov! I've removed the erroneous syntax from the thread level viewing page and have updated that page and the Option: Limit page to be clearer.
