### ISSUE TITLE
v4 Printer Driver template wizard instructions don't match VS 2017

### ISSUE THREAD

**Issue by sicklittlemonkey** [MicrosoftDocs/windows-driver-docs#342]
Instructions:
Add the Pipeline Config file to the driver package
...
3. Expand Driver Install, then click Package Files. Do the following in the right pane:
- Navigate to the project directory.

Me:
Where? You mean click <Edit...>? Clicking "..." on the path browser takes me to C:\Windows\System32, then browsing to my project gives a fully qualified path for the file, and nothing for the path. It seems to accept it if I re-format it to just the filename on the left (file field) and a relative path on the right (path field). Have I divined the intention? Obviously not, as I currently get:
error MSB3030: Could not copy the file "v4PrinterDriverCustomRenderingRenderFilter-PipelineConfig.xml" because it was not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227ceb38-396a-aa19-6304-be3df9b0ca08
* Version Independent ID: 2f34593f-aa20-384a-b1bb-c8a962ec4706
* [Content](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/building-a-basic-v4-printer-driver)
* [Content Source](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/building-a-basic-v4-printer-driver.md)
* Service: unspecified

**Comment by sicklittlemonkey** [comment]
Not sure whether to file separate issues for things on the same page, so I'll add here for now.

Instructions:
6. Add PrinterDriverID to the INF file
...
And then after the comma, paste the GUID that you copied in the preceding step. The completed [Standard.NT$ARCH$] section should look like the following:
"Fabrikam 1234"=DriverInstall, {GUID}
"Fabrikam 1234"=DriverInstall, USBPRINT\Fabrikam1234
"Fabrikam 1234"=DriverInstall, WSDPRINT\Fabrikam1234

Me:
Firstly, here these are shown as "...USBPRINT\Fabrikam1234", but in the previous step (5) as "...USBPRINT\\Fabrikam1234". Which is correct?
Also, after adding the actual GUID (from the Driver Files->Properties->Unique Identifier field) I now get the following compile error:
v4PrinterDriverCustomRendering.inf(17): error 8559: (DE22.23.8559) Required Pnp Bus enumerator is missing on HW PnpID '{<Actual GUID>}'.

**Comment by barrygolden** [comment]
Hi @sicklittlemonkey
Thanks for providing the detailed description of your experience using the [Building a Basic v4 Printer Driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/building-a-basic-v4-printer-driver) instructions in VS 2017. We've opened an internal task to investigate the issues you encountered. We'll work with the print driver devs to replicate these issues and update the topic as required.

**Comment by SterlingRunion** [comment]
I'm having issues too. Went thru the steps and the Wizard did not create a c++ project file.

**Comment by tanuj101** [comment]
@sicklittlemonkey what did you make of this link you mentioned regarding creating virtual printer driver?

**Comment by sicklittlemonkey** [comment]
@tanuj101 I haven't got back to that yet, but the documentation is sparse and confusing. Windows printing is a mess, and black magic. There's no printing blog anymore; I'm not sure where developers can get help. I wish I could say something more positive!
