### ISSUE TITLE
How to override SSDT tables

### ISSUE THREAD

**Issue by eshiva0** [MicrosoftDocs/windows-driver-docs#3420]
Is it possible to only override the SSDT table in windows? If I modify and compile SSDT file and place it into system32 folder with name “acpitabl.dat”, system doesn’t accept this. Whereas Linux supports SSDT override. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16299ebf-80ed-f09f-d0c0-4cda742f579e
* Version Independent ID: 8e45d880-93f8-4c85-81e6-b1d5dbe78ab6
* Content: [Generate ACPI tables by using AcpiGenFx - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/bringup/generate-acpi-tables-by-using-acpigenfx)
* Content Source: [windows-driver-docs-pr/bringup/generate-acpi-tables-by-using-acpigenfx.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/generate-acpi-tables-by-using-acpigenfx.md)
* Product: **windows-hardware**
* Technology: **bringup**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@eshiva0, thanks for reaching out to the Windows Driver Developer Documentation team. 

I would recommend posting your question about how to override SSDT tables in the following forums, where other driver developers and Microsoft engineers can be found. 

[Microsoft Q&A: Windows Hardware development](https://docs.microsoft.com/answers/topics/windows-hardware.html)

[OSR Developer Community](https://community.osr.com/)
