### ISSUE TITLE
UVC payload information or UVC control

### ISSUE THREAD

**Issue by MarkHung00** [MicrosoftDocs/windows-driver-docs#3432]
We would like to know if there is a suitable way to obtain the following UVC information or control when AMCap is turned on in Windows, such as DMFT/DirectShow or only in the Windows driver (KMDF):

- Digital window control
- Exposure min/max information 
- Still image payload information

**Comment by barrygolden** [comment]
@MarkHung00, thanks for reaching out to the Windows Driver Developer Documentation team.  Unfortunately, we are a small team and do not have the resources to provide technical support to individual driver developers. You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. 

[Microsoft Q&A: Windows Hardware development](https://docs.microsoft.com/answers/topics/windows-hardware.html)

[OSR Developer Community](https://community.osr.com/)
