### ISSUE TITLE
Link to Microsoft Store not working

### ISSUE THREAD

**Issue by DirkFedermann** [MicrosoftDocs/windows-driver-docs#3437]
In the file: [windows-driver-docs](https://github.com/MicrosoftDocs/windows-driver-docs)/[windows-driver-docs-pr](https://github.com/MicrosoftDocs/windows-driver-docs/tree/staging/windows-driver-docs-pr)/[debugger](https://github.com/MicrosoftDocs/windows-driver-docs/tree/staging/windows-driver-docs-pr/debugger)/debugger-download-tools.md
the link to download WinDbg Preview goes to a 503 site.
Link should be this: https://apps.microsoft.com/store/detail/windbg-preview/9PGJGD53TN86

**Comment by mhopkins-msft** [comment]
Hi @DirkFedermann,

Thank you for reporting this. I've updated the link. I appreciate your help making the docs better.

Thanks!
 ~ *Mark*
