### ISSUE TITLE
Update Path for Windows Driver Kit

### ISSUE THREAD

**Issue by briansaxbergMSFT** [MicrosoftDocs/windows-driver-docs#3439]
Step 4, substep D where the powershell path is this.

cd "C:\Program Files (x86)\Windows Kits\8.0\Tools\x86\Network Monitor Parsers\usb"
..\NplAutoProfile.ps1

With the new version if the Windows Driver Kit the path is now this.
cd "C:\Program Files (x86)\Windows Kits\10\Tools\10.0.22621.0\x86\Network Monitor Parsers\usb"
..\NplAutoProfile.ps1

**Comment by tedhudek** [comment]
Just pushed an update to https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/how-to-install-netmon-and-the-netmon-usb-parser, should be live soon.  Thanks for the report Brian!
