### ISSUE TITLE
Step 3 Is Incorrect

### ISSUE THREAD

**Issue by giantramen** [MicrosoftDocs/windows-driver-docs#3444]
Step 3 on this page https://learn.microsoft.com/en-us/windows-hardware/drivers/develop/building-arm64-drivers asks you to check boxes that are not in the newest versions. 
I think it should be updated to match the files listed on the arm website: https://developer.arm.com/documentation/102528/0100/Install-Visual-Studio

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8da0acb6-3b62-3c4d-a40b-fadb3b438e8d
* Version Independent ID: 19a5ad0a-ee47-1834-694f-ee89882fa78d
* Content: [Building Arm64 Drivers with the WDK - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/develop/building-arm64-drivers)
* Content Source: [windows-driver-docs-pr/develop/building-arm64-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/building-arm64-drivers.md)
* Product: **windows-hardware**
* Technology: **develop**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @giantramen,

Thanks so much for the report.  I've updated the page in question to list the components as they appear on the page you mentioned.
