### ISSUE TITLE
micropep vs pep

### ISSUE THREAD

**Issue by santino-wang-mtk** [MicrosoftDocs/windows-driver-docs#3447]
[Enter feedback here]
What's the meaning of micropep? uPEP?
Does it have special meaning compared to PEP?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b168f14f-59e0-9fe6-d600-6e06621e4b77
* Version Independent ID: 79f32da9-5815-a833-7683-50016bd272f3
* Content: [Device power management - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/bringup/device-power-management)
* Content Source: [windows-driver-docs-pr/bringup/device-power-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/device-power-management.md)
* Product: **windows-hardware**
* Technology: **bringup**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@santino-wang-mtk, thanks for reaching out to the Windows Driver Developer Documentation team.  

You may have success posting your question about microPEP vs. PEP in the following forums, where other driver developers and Microsoft engineers can be found. 

[Microsoft Q&A: Windows Hardware development](https://docs.microsoft.com/answers/topics/windows-hardware.html)

[OSR Developer Community](https://community.osr.com/)
