### ISSUE TITLE
First paragraph requires extra details, it is very confusing

### ISSUE THREAD

**Issue by asilverman** [MicrosoftDocs/windows-driver-docs#345]
I assume that this documentation is targeting beginner developers in the device and driver installation process. The first paragraph of this document starts off with a very convoluted and confusing sentence. I would have expected that the documentation explain in detail what is the definition of "components to install devices";. The word component is too general and lacks meaning in the context of the sentence. Here, an example of such a component is probably required for clarification.

Following, the paragraph continues with "system-provided device installation components" and "vendor-supplied components". What are the differences between these two?. Why aren't there any examples of teach would help to provide more context?

The use of the word component for everything just makes no sense didactically and causes frustration and confusion for the reader

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f8d703-33d8-7610-b6f7-54b6f376547f
* Version Independent ID: 60c1c334-3f12-5402-40fc-f4ebfee54675
* [Content](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/overview-of-device-and-driver-installation)
* [Content Source](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/overview-of-device-and-driver-installation.md)
* Service: unspecified

**Comment by tedhudek** [comment]
Hi @asilverman thanks for the feedback.  The sentence on components is referring to subsections below this page in the table of contents.  There are links to those pages in the link block on https://docs.microsoft.com/en-us/windows-hardware/drivers/install/overview-of-device-and-driver-installation, but I went ahead and added the same link up top in the first para.  That change will be live momentarily.
