### ISSUE TITLE
Both of the links to install WinDbg are broken

### ISSUE THREAD

**Issue by CarlosAg** [MicrosoftDocs/windows-driver-docs#3451]
Clicking the Link to Download WinDbg Preview from App Store gave me an error on unable to process response.
And also the Link to Install through the Windows SDK is broken as well, specifically the link to: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 162fe2fe-9216-f4c5-9f91-3df8776bb99e
* Version Independent ID: 013dbf6b-0790-9c11-24f4-dbf24d64401e
* Content: [Download Debugging Tools for Windows - WinDbg - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
* Content Source: [windows-driver-docs-pr/debugger/debugger-download-tools.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debugger-download-tools.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by mhopkins-msft** [comment]
Hi @CarlosAg,

I was unable to reproduce the issue with the Windows Store link. It worked great for me. Please make sure you are logged in to your Microsoft account before you try to install from the Store.

I did fix the links to the SDK download page. Thank you for your help in making the docs better!

 ~ *Mark*
