### ISSUE TITLE
The OID_GEN_SUPPORTED_PACKET_FILTERS page is not completely clear on whether it works in Vista and later

### ISSUE THREAD

**Issue by guyharris** [MicrosoftDocs/windows-driver-docs#3453]
The [OID_GEN_SUPPORTED_PACKET_FILTERS page](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-supported-packet-filters) in Windows Drivers/Driver Technologies/Network is not completely clear on whether that OID works in Vista and later.

The second paragraph at the top says:

> **Note**  This OID is not implemented in the Windows Vista and later versions of Windows operating system. For more information, see the Remarks section.

and the first paragraph for "Version Information" says:

> Windows Vista and later versions of Windows
> Supported.
> 
> NDIS 6.0 and later miniport drivers
> Not implemented. (See Remarks section.)

and the Remarks section says:

> Miniport drivers supply the supported packet filters during initialization.
> 
> To specify the supported packet filters, a miniport driver sets the **SupportedPacketFilters** member of the [**NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES**](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/ns-ndis-_ndis_miniport_adapter_general_attributes) structure and passes the structure to the [**NdisMSetMiniportAttributes**](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/nf-ndis-ndismsetminiportattributes) function.
> 
> NDIS passes the information to protocol drivers in the **SupportedPacketFilters** member of the [**NDIS_BIND_PARAMETERS**](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/ns-ndis-_ndis_bind_parameters) structure.
> 
> The values in **SupportedPacketFilters** are a bitwise OR of the filter type flags. For a list of the filter type flags, see the [**OID_GEN_CURRENT_PACKET_FILTER**](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-current-packet-filter) OID.

So does this mean that:

1. If, in Vista or later, you make a call to NDIS to request the value of `OID_GEN_SUPPORTED_PACKET_FILTERS`, the value provided by the NDIS miniport driver to NDIS in the `SupportedPacketFilters` member of the `NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES` structure it passes to `NdisMSetMiniportAttributes()` is what will be returned?
2. An NDIS 6.0 or later miniport driver will never be directly asked to provide or change the value of `OID_GEN_SUPPORTED_PACKET_FILTERS`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5caa4f89-bcd3-b499-2898-58760143e2f5
* Version Independent ID: ea3273b9-0b20-18db-7687-cb2d1712b2d6
* Content: [OID_GEN_SUPPORTED_PACKET_FILTERS - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-supported-packet-filters)
* Content Source: [windows-driver-docs-pr/network/oid-gen-supported-packet-filters.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/oid-gen-supported-packet-filters.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by jtippet** [comment]
`OID_GEN_SUPPORTED_PACKET_FILTERS` was never implemented in a shipping version of Windows. (As far as I know, it was temporarily available in a pre-release version of Windows Vista, but was removed before release.)

So the bottom line is that:
* Protocols and filters cannot query this OID
* Miniports do not need to respond to this OID

The functionality suggested by the OID is completely superseded by the `SupportedPacketFilters` fields in `NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES` and `NDIS_BIND_PARAMETERS`.

**Comment by guyharris** [comment]
> `OID_GEN_SUPPORTED_PACKET_FILTERS` was never implemented in a shipping version of Windows.

Then the page should probably say

>  **Note**  This OID is not implemented in any shipping version of the Windows operating system

and

> **Version Information**
> 
> Windows Vista and later versions of Windows
> Not supported.

(emphasis on the "Not").

**Comment by guyharris** [comment]
And [the NDIS_MINIPORT_ADAPTER_GENERAL_ATTRIBUTES structure page](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/ns-ndis-_ndis_miniport_adapter_general_attributes) should probably *not* say:

> `SupportedPacketFilters`
> 
> The packet filter flags for the miniport adapter. For more information, see [OID_GEN_SUPPORTED_PACKET_FILTERS](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-supported-packet-filters).

as 1) the `OID_GEN_SUPPORTED_PACKET_FILTERS` doesn't contain any information about that value and 2) that value can't be fetched or set using hat OID.

**Comment by guyharris** [comment]
[The page of NDIS 5 OIDs for "General Operational Characteristics"](https://learn.microsoft.com/en-us/previous-versions/windows/hardware/network/ff546512(v=vs.85)) doesn't include `OID_GEN_SUPPORTED_PACKET_FILTERS`, so I assume it's not supported by any *pre*-Vista OS versions, either.

**Comment by aviviano** [comment]
Hi @guyharris, 
We've removed the page for OID_GEN_SUPPORTED_PACKET_FILTERS since it never implemented in a shipping version of Windows. We've also removed references to the page. Thanks very much for pointing out this issue and helping us improve the docs.
