### ISSUE TITLE
"Porting NDIS miniport drivers to NetAdapterCx" misspells "IOCTL"

### ISSUE THREAD

**Issue by guyharris** [MicrosoftDocs/windows-driver-docs#3454]
[The "Porting NDIS miniport drivers to NetAdapterCx" page](https://learn.microsoft.com/en-us/windows-hardware/drivers/netcx/porting-ndis-miniport-drivers-to-netadaptercx) has a section on ioctls, the title of which is "Receiving I/O control codes (IOTCLs) from user mode".

That should probably be "IOCTLs", unless you're deliberately trying to spell it differently from the way it's spelled in UN\*Xes. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd8d1135-8e43-d2bd-4398-4b04cd727ea1
* Version Independent ID: 24d46a09-1175-b223-be59-a7317e925038
* Content: [Porting NDIS miniport drivers to NetAdapterCx - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/netcx/porting-ndis-miniport-drivers-to-netadaptercx)
* Content Source: [windows-driver-docs-pr/netcx/porting-ndis-miniport-drivers-to-netadaptercx.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/netcx/porting-ndis-miniport-drivers-to-netadaptercx.md)
* Product: **windows-hardware**
* Technology: **netcx**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
😆 
Thanks @guyharris, the fix will be live on the site soon.
