### ISSUE TITLE
needs to be updated? file->new project has no pane to the left nor does it have wdm when I search for it

### ISSUE THREAD

**Issue by mspohrer** [MicrosoftDocs/windows-driver-docs#3455]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 766e9c84-014d-eb38-2847-c413b7fc58b6
* Version Independent ID: ff9e768e-acb7-7abf-ee61-043507a46f80
* Content: [Creating a New Device Function Driver - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/develop/creating-a-new-driver)
* Content Source: [windows-driver-docs-pr/develop/creating-a-new-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/creating-a-new-driver.md)
* Product: **windows-hardware**
* Technology: **develop**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by mhopkins-msft** [comment]
Hi @mspohrer,

Thank you for reporting this. I've updated the article so the steps reflect the process using Visual Studio 2022. Please let me know if you have any further feedback. Thank you for helping make the docs better!

 ~ *Mark*
