### ISSUE TITLE
Add drivers needed to boot Windows following hardware change (not a Windows new install)

### ISSUE THREAD

**Issue by developer-controls** [MicrosoftDocs/windows-driver-docs#3461]
Searching for help to install drivers needed to launch Windows brought me to this page, which doesn't seem to address this. I do NOT want to reinstall Windows, just need to install a new driver so that Windows will boot with the RAID option active in the BIOS. Ironically, I can boot Windows if I turn off RAID in the BIOS, but then Windows doesn't detect the RAID hardware so won't let me install the drivers. Alternatively, if I turn RAID on in the BIOS, Windows sees it and complains that it can't boot because the needed drivers are not installed. A classic chicken and egg problem. So how do I install the RAID driver?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92a612bb-8d35-0684-933f-24217530f233
* Version Independent ID: 348a976d-951b-586c-6b70-4a38751cdfbc
* Content: [Install a boot-start driver - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/installing-a-boot-start-driver)
* Content Source: [windows-driver-docs-pr/install/installing-a-boot-start-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/installing-a-boot-start-driver.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @developer-controls, this is a little outside the scope of our docs, which are for IHVs and OEMs who write the drivers and pre-install them in OS images.  

I did try Bing AI with the question, and (among other things) it had this suggestion:

Leave RAID off in the BIOS and use Device Manager to update the RAID controller driver. Open Device Manager, expand Other devices, right-click on Raid controller or similar driver name and choose Update driver.

If that doesn't work I'd recommend the driver forums.  The community there is quite responsive. Best of luck with this issue.

* [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/60/windows)
* [OSR's NTDEV forum](https://community.osr.com/categories/ntdev)
