### ISSUE TITLE
Value "0xa000" for parameter 1

### ISSUE THREAD

**Issue by duronald** [MicrosoftDocs/windows-driver-docs#3474]
Please provide information about the meaning of the value "0xa000" for parameter 1.
A dump file I've just analyzed had that value for the first parameter as well as the following information
FAILURE_BUCKET_ID:  0x119_a000_VIDSCH_RESET_HW_ENGINE_SUSPEND_dxgmms2!VidSchiResetHwEngine

STACK_TEXT:  
fffff981`3078e5c8 fffff803`94085685     : 00000000`00000119 00000000`0000a000 ffffdf8f`708a8000 00000000`0000018c : nt!KeBugCheckEx
fffff981`3078e5d0 fffff803`b9b75e58     : ffffdf8f`708aa002 ffffdf8f`62578ae0 ffffdf8f`62578ae8 ffffdf8f`62578af0 : watchdog!WdLogSingleEntry5+0x3b45
fffff981`3078e680 fffff803`b9c367c2     : ffffdf8f`7097b001 00000000`00000000 00000000`00000000 00000000`00000000 : dxgmms2!VidSchiResetHwEngine+0x3b8
fffff981`3078e830 fffff803`b9c0643b     : ffffdf8f`708aa000 00000000`00000000 00000000`00000000 00000000`00000000 : dxgmms2!VidSchiResetEngines+0xaa
fffff981`3078e880 fffff803`b9bd8c3f     : 00000000`00000000 00000000`00000000 00000000`00085fd3 00000000`00989680 : dxgmms2!VidSchiCheckHwProgress+0x2d7bb
fffff981`3078e900 fffff803`b9b3b669     : 00000000`00000000 ffffdf8f`708aa000 fffff981`3078ea39 00000000`00000000 : dxgmms2!VidSchiWaitForSchedulerEvents+0x37f
fffff981`3078e9d0 fffff803`b9be4a75     : ffffdf8f`759ea000 ffffdf8f`708aa000 ffffdf8f`759ea010 ffffdf8f`7088f050 : dxgmms2!VidSchiScheduleCommandToRun+0x309
fffff981`3078eaa0 fffff803`b9be49ea     : 00000000`00000000 fffff803`b9be4920 ffffdf8f`708aa000 00000000`00000080 : dxgmms2!VidSchiRun_PriorityTable+0x35
fffff981`3078eaf0 fffff803`7700dc67     : ffffdf8f`6ca7f080 fffff803`00000001 ffffdf8f`708aa000 006fe47f`b19bbdff : dxgmms2!VidSchiWorkerThread+0xca
fffff981`3078eb30 fffff803`77230854     : ffffad81`bc511180 ffffdf8f`6ca7f080 fffff803`7700dc10 00000000`00000000 : nt!PspSystemThreadStartup+0x57
fffff981`3078eb80 00000000`00000000     : fffff981`3078f000 fffff981`30788000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x34

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7917857b-97bc-efec-67ab-5e3af061524c
* Version Independent ID: 8c00d20e-9b21-7bb0-a041-220aca9d2487
* Content: [Bug check 0x119 VIDEO_SCHEDULER_INTERNAL_ERROR - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x119---video-scheduler-internal-error)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@duronald - Thanks for pointing out the need to document the value "0xa000" for parameter 1. I have added a short description of this error to the docs. One approach to this bug check (after making sure the video drivers and Windows are up to date), is to look for hardware memory errors. If the video card adapter has any diagnostics, run those to check for hardware and/or memory errors. Sometimes even the power supply or the PC's memory can cause video memory corruption. The use of Windows mem utils is described in https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/blue-screen-data
Thanks again for submitting this issue and good luck with your video card bug check error.
