### ISSUE TITLE
the /c flag does not exists in the latest versions of poolmon, but the documentation mentions it.

### ISSUE THREAD

**Issue by ccurtit** [MicrosoftDocs/windows-driver-docs#3475]
Here is what happens when I run poolmon /c
```
D:\Tools>poolmon.exe /c
Poolmon: unknown switch: c

```

Versoins infos :
![image](https://user-images.githubusercontent.com/127329759/235112295-f2fc0131-95e1-4351-ba88-c8608f917436.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f5a6493-4db5-8f3f-9225-326db228bfbc
* Version Independent ID: 59d43335-d46e-44ef-fa22-e0a96e250138
* Content: [PoolMon Examples - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/poolmon-examples)
* Content Source: [windows-driver-docs-pr/devtest/poolmon-examples.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/poolmon-examples.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ccurtit - Thanks for pointing out that the /c param is no longer available in poolmon. I confirmed that is no longer present and removed multiple references to it in the documentation.  Thanks for passing on what you were seeing, and helping to improve the docs for the users of poolmon.
