### ISSUE TITLE
Update link for WDK 8.1

### ISSUE THREAD

**Issue by meir555** [MicrosoftDocs/windows-driver-docs#3480]
Link for WDK 8.1 is missing, see here for a working link:
https://stackoverflow.com/questions/64623513/i-cant-find-a-download-for-the-windows-driver-kit-8-1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f5d6d55-cb35-6b9e-f8ca-e75f70826dc3
* Version Independent ID: 1d913516-b1e0-e872-c337-e30ed5dffce8
* Content: [Previous WDK versions and other downloads - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads)
* Content Source: [windows-driver-docs-pr/other-wdk-downloads.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/other-wdk-downloads.md)
* Product: **windows-hardware**
* Technology: **whats-new-and-downloads**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks @meir555, I appreciate your bringing the alternate links to our attention. While I'd love to include them in the docs for convenience, I don't have any way to verify that even the one on download.microsoft.com is SHA-2 signed, which is a requirement for the assets we list.  But it's great to know that it's in a prominent place where folks can find it via search if that's the route they want to take.
