### ISSUE TITLE
Missing parameter 1 value explanation for bug check 0x4E

### ISSUE THREAD

**Issue by christoskatsandris** [MicrosoftDocs/windows-driver-docs#3485]
There is no reference to the meaning of the bug check 0x4E PFN_LIST_CORRUPT parameters 2, 3, and 4, when parameter 1 has the value 0x6.

Example from the event log:

```
...
  <EventData>
    <Data Name="BugcheckCode">78</Data>
    <Data Name="BugcheckParameter1">0x6</Data>
    <Data Name="BugcheckParameter2">0x142364</Data>
    <Data Name="BugcheckParameter3">0xffffaa10c2ccb0a7</Data>
    <Data Name="BugcheckParameter4">0xa04000142364821</Data>
    ...
```

**Comment by DOMARS** [comment]
@christoskatsandris - Thanks for seeing this gap for param 1 value of 6 in the docs. I added it to the docs. It deals with the PTE and the prototype PTE not matching as they should. Can be a transient memory error induced on to the system, or like many memory errors, could be the beginning a memory component failure or the sign of other hardware failures that impact the use/integrity of memory. Good luck with your debugging and thanks again for filing this issue.
