### ISSUE TITLE
Important Note

### ISSUE THREAD

**Issue by McBibbers** [MicrosoftDocs/windows-driver-docs#3498]
[Enter feedback here]
This command does not work correctly from PowerShell.  You need to be in a "regular" command prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4e56d98-d380-e346-4ba3-d17f1596af86
* Version Independent ID: 2946df6a-59c0-335a-9a6a-5e9ceabaf13f
* Content: [Changing the Friendly Name of a Boot Entry - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/changing-the-friendly-name-of-a-boot-entry)
* Content Source: [windows-driver-docs-pr/devtest/changing-the-friendly-name-of-a-boot-entry.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/changing-the-friendly-name-of-a-boot-entry.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@McBibbers - Thanks for providing this input on the use of the command line utility bcdedit. And as more people use PowerShell as their default command shell, it is useful input. For now, the one note in the topic that describes how to use double quotes around the boot entry identifier - "{49916baf-0e08-11db-9af4-000bdbd316a0}" or "{current}" for PowerShell, I think will be OK. That said, I normally type cmd to open the classic command processor in PowerShell as that is what I'm most familiar with. Thanks again for this input, and good luck with your use of bcdedit to work with the boot record.
