### ISSUE TITLE
Introduction to Storport Minidrivers

### ISSUE THREAD

**Issue by SolihullRog2** [MicrosoftDocs/windows-driver-docs#3500]
The above is the title of a webpage.
It contains nothing like an introduction, or even a description.
You've wasted my time and my interest, but I've learnt one thing - which is "If I see the words 'Storport' or 'Minidriver' on my PC I will delete them".[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7f7489b-89e8-1316-c7ad-0855d5f6c299
* Version Independent ID: efd328fe-d215-9e1e-9ef9-07dd66c598aa
* Content: [Introduction to Storport Miniport Drivers - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/storage/storport-miniport-drivers)
* Content Source: [windows-driver-docs-pr/storage/storport-miniport-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/storport-miniport-drivers.md)
* Product: **windows-hardware**
* Technology: **storage**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Hi @SolihullRog2, most hardware vendors are aware of the port/miniport model, which is described on other pages in this section. That said, I agree that this page could provide some basic details and links so I updated it. Thanks for the issue. Hopefully you won't delete any drivers from your system! :)
