### ISSUE TITLE
Give some direct forum discussion links.

### ISSUE THREAD

**Issue by KrishnaB22** [MicrosoftDocs/windows-driver-docs#3503]
I want to know how to handle and would like to get exact discussion links regarding memory mapped files on https://community.osr.com/
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93e4a1c1-1dd7-df73-b998-ccd4ea1536b9
* Version Independent ID: 9df2a30d-c216-3e06-9478-7cba7a6a644f
* Content: [Memory Mapped Files in a File System Filter Driver - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/memory-mapped-files-in-a-file-system-filter-driver)
* Content Source: [windows-driver-docs-pr/ifs/memory-mapped-files-in-a-file-system-filter-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/memory-mapped-files-in-a-file-system-filter-driver.md)
* Product: **windows-hardware**
* Technology: **ifs**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@KrishnaB22, I've updated the page to include some references that should be helpful to you. There are hundreds of OSR posts pertaining to memory-mapped files/paging IO - hopefully you can find the guidance you are specifically looking for by using keywords in search.
