### ISSUE TITLE
Print Support App has shipped. "Intend to" no longer applies

### ISSUE THREAD

**Issue by DavidKanz** [MicrosoftDocs/windows-driver-docs#3510]
The Print Support App feature has shipped. I keep coming across "intend to" in some of the public documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d38003a1-8fba-7709-b130-57493ec9475b
* Version Independent ID: 67f50a05-3916-244c-9eb4-3a259e79bc6d
* Content: [Print support app design guide - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-design-guide)
* Content Source: [windows-driver-docs-pr/devapps/print-support-app-design-guide.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/print-support-app-design-guide.md)
* Product: **windows-hardware**
* Technology: **devapps**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@DavidKanz, thanks for filing this issue. The prerelease text and future tense have been removed from the PSA docs..
