### ISSUE TITLE
Not find the webpage  "Submit new hardware"

### ISSUE THREAD

**Issue by yinming-shenzhen** [MicrosoftDocs/windows-driver-docs#3512]
I could not find the webpage  "Submit new hardware", Could you give the link? thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9288fd9-bb24-631a-b6f8-6b2f5313fd17
* Version Independent ID: a9288fd9-bb24-631a-b6f8-6b2f5313fd17
* Content: [Create a new hardware submission - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-create)
* Content Source: [windows-driver-docs-pr/dashboard/hardware-submission-create.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-create.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
Hi @yinming-shenzhen,

Sorry you are having trouble. Hopefully, the following screenshot helps!

![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/61602255/afd6ad67-7aeb-4f26-a969-221c57cf595c)

**Comment by yinming-shenzhen** [comment]
Hi, anaharris-ms, Thanks for your comment.

I have met a problem when do windows driver certificate. 

![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/7309329/168af407-d77e-4cdd-ba33-68854d59c42d)

The EV certificate is purchased by our company by the legal way and I am sure the EV is owned only by us. But Why the website tell me the EV  certifate has already been registered? Could you help me to check? Thank you very much.

**Comment by anaharris-ms** [comment]
Hi @yinming-shenzhen ,

Please contact customer support [here](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support#technical-support-issues) for cert submission issues.
