### ISSUE TITLE
Bluetooth Mesh

### ISSUE THREAD

**Issue by brazierd** [MicrosoftDocs/windows-driver-docs#353]
Hi

Is support for Bluetooth Mesh (https://www.bluetooth.com/bluetooth-technology/topology-options/le-mesh) planned?  We have a use case where an IoT Core device is a gateway for low power devices, though it would be appropriate to Windows in general.

Regards 

David 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8496691a-3bd6-503e-014f-94426d94d3e8
* Version Independent ID: 37997d09-0746-e388-d4a5-418d5ac34ef4
* Content: [Bluetooth Low Energy Overview | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/bluetooth/bluetooth-low-energy-overview)
* Content Source: [windows-driver-docs-pr/bluetooth/bluetooth-low-energy-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bluetooth/bluetooth-low-energy-overview.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello David

Thanks for the query. In the current release, we do not support Bluetooth Mesh. Do keep an eye on our  [BT profile support tracker ](https://docs.microsoft.com/en-us/windows-hardware/drivers/bluetooth/general-bluetooth-support-in-windows) or [feature update](https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/bluetooth) pages for the most up-to-date info about what's new in Bluetooth. 

-PageWriter
