### ISSUE TITLE
How to find the symproxy.dll

### ISSUE THREAD

**Issue by lindexi** [MicrosoftDocs/windows-driver-docs#354]
As this document that I cant find the symproxy.dll,symsrv.dll and I never find any way to say where they are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cca664-53c7-ee65-5975-3d7a8e56bb07
* Version Independent ID: 2b130c88-3228-1ea1-c57a-20469cc6525b
* Content: [Installing SymProxy | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/installing-symproxy)
* Content Source: [windows-driver-docs-pr/debugger/installing-symproxy.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/installing-symproxy.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
This information is in the topic that describes where to locate symproxy.dll and symsrv.dll.

The SymProxy files are included in the Debuggers directory of the Windows Driver Kit. For example this is the location of the 64 bit files for Windows 10 kit. C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symproxy.

To install SymProxy on the server, copy symproxy.dll, symsrv.dll and symproxy.man to %WINDIR%\system32\inetsrv.
