### ISSUE TITLE
The Download Visual Studio Enterprise and Professional had their URL switch

### ISSUE THREAD

**Issue by eacc3525** [MicrosoftDocs/windows-driver-docs#355]
"Download Visual Studio Enterprise 2017" URL is Professional and "Download Visual Studio Professional 2017" URL is Enterprise. I would not touch the URL and just change the descriptions to keep an order of functionality in the Visual Studio packages.

**Comment by EliotSeattle** [comment]
Oops! Thank you, @eacc3525 for pointing this out. I've made the change in the source. It should be live today. Appreciate the heads up.
