### ISSUE TITLE
The description for dump folder size of silent exit process monitor is incorrect

### ISSUE THREAD

**Issue by kemats** [MicrosoftDocs/windows-driver-docs#3552]
The description for dump folder size of silent exit process monitor below is incorrect.

> https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/registry-entries-for-silent-process-exit#dump-folder-size
> The value that you enter for Dump folder size is stored in the MaximumNumberOfDumpFiles registry entry.
> By default, there is no limit to the number of dump files that can be written.

The actual key name is MaxNumberOfDumpFiles and the silent process exit dump folder default size is 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c3da798-613b-320b-c1ec-96480ac476a2
* Version Independent ID: 25de8f2c-f2b9-671d-2ba9-703962214826
* Content: [Monitoring Silent Process Exit - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/registry-entries-for-silent-process-exit)
* Content Source: [windows-driver-docs-pr/debugger/registry-entries-for-silent-process-exit.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/registry-entries-for-silent-process-exit.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@kemats - Thanks very much for this issue. I validated the correction that you provided, and updated the topic to use  MaxNumberOfDumpFiles with a default number of ten files. I'm glad that future users will have correct information. Thanks for caring about the docs!
