### ISSUE TITLE
EWDK setup scripts only work with 'drive letter' paths.

### ISSUE THREAD

**Issue by HollisTech** [MicrosoftDocs/windows-driver-docs#3555]
The setup scripts will fail if the path is a SMB path. This is unfortunate for build servers.  It at least should be noted in the doc page.

**Comment by tedhudek** [comment]
Hi @HollisTech thanks for the suggestion.  Do you have specific wording you'd like to recommend?  I'm not immediately familiar with the issue.

**Comment by HollisTech** [comment]
By 'smb path' I mean a network share path like "\\server-name\EWDK" instead of, for example: "F:\EWDK".

**Comment by tedhudek** [comment]
Hi @HollisTech,

Are you saying that mapping the network drive doesn't work with the EWDK setup scripts?  For example: `net use * \\server-name\EWDK` should result in the system assigning a drive letter that is not in use.  Then use that new drive letter to run the EWDK scripts.

**Comment by HollisTech** [comment]
Hi @tedhudek 
Sure, one can always mount iso's with drive letters. However that is a manual step and not particularly great to have to do in, for example, a build script. SMB paths are ubiquitous these days and are much easier to use in many environments. While this 'feature' is a bug in the EWDK setup scripts, and should be fixed, the docs ought to point out the (discovered) requirement that the EWDK has to be accessed through a mounted  volume.

**Comment by tedhudek** [comment]
Thanks @HollisTech!

I just added this caveat to step 1 of https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-windows-11-version-22h2-updated-may-2023-ewdk-with-visual-studio-build-tools.
