### ISSUE TITLE
Looking for files

### ISSUE THREAD

**Issue by ImAbdollahzadeh** [MicrosoftDocs/windows-driver-docs#356]
Is there a way I can find those files referenced in this article from Windows Driver Kit (WDK) through the Windows 7 edition (Version 7600)?

I don't have this version of WDK on my computer, but would like to have a look at the sample mirror driver files including mirror.inf.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ccfb830-7821-ef84-96d0-d2c0318e65e1
* Version Independent ID: e40c1bbc-0411-ea87-58e6-25d53db93b3f
* Content: [Mirror Drivers | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/mirror-drivers)
* Content Source: [windows-driver-docs-pr/display/mirror-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/mirror-drivers.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @ImAbdollahzadeh. Windows 7 and earlier samples and documentation were included in the Windows Driver Kit (WDK) or Driver Development Kit (DDK). You can start the download for the Windows 7.1 WDK at https://www.microsoft.com/download/confirmation.aspx?id=11800. Hope this helps.
