### ISSUE TITLE
Volume in dB

### ISSUE THREAD

**Issue by Benni48kHz** [MicrosoftDocs/windows-driver-docs#3561]
Hi,
as I work in a recording studio with Windows computers, I often notice that it would be very useful to be able to display the system volume in dB. 
Also, setting the step size (e.g. 1; 3; 6 and 10dB steps) by additionally holding down the Ctrl key would be nice to have.
Kind regards
Benni

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8a38021-98c1-f7a4-50d1-231230d460d0
* Version Independent ID: 1d277dd0-454f-7069-2763-2bf4797417ad
* Content: [Default Audio Volume Settings - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/audio/default-audio-volume-settings)
* Content Source: [windows-driver-docs-pr/audio/default-audio-volume-settings.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/default-audio-volume-settings.md)
* Product: **windows-hardware**
* Technology: **audio**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Benni48kHz - This is an interesting idea, and you may want to consider filing Windows feedback for this possible feature.  This article describes how to do that using the feedback hub.

https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332

We use these git issues as a feedback mechanism for requests about the documentation. 

As you may be aware, there are various type of dB measures (https://en.wikipedia.org/wiki/Decibel). In audio I normally think of the generated sound pressure measure. The challenge there is that with for example external speakers with an amp, Windows doesn't typically have knowledge of physical volume button on standard PC speakers.  So there could be a challenge there. Also the Windows partners and PC makers often do extensive customization, so aligning the setting values could be a challenge.

I checked with a co-worker/musician, and he was not aware of any third-party tools setting or visualizing the system audio level in dB.  He mentioned a digital audio workstation (DAW) and said that these apps usually use an ASIO driver to interface with the audio hardware (AKA, audio interface). And that the level is set within the DAW app and with a knob on the audio interface. So, in that case the Windows system level isn’t involved.

In any event, you may wish to consider filing Windows product feedback as described above. Thanks for your interest in improving the Windows audio experience.
