### ISSUE TITLE
Missing syntax highlighting for TraceLogging code example

### ISSUE THREAD

**Issue by CarePackage17** [MicrosoftDocs/windows-driver-docs#3566]
The code example does not have syntax highlighting, making it harder to read.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43bd2be3-d344-5125-af89-c8d92920af97
* Version Independent ID: fcc2e952-1ac6-797c-b0b5-874cd55abb35
* Content: [TraceLogging Examples - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/tracelogging-examples)
* Content Source: [windows-driver-docs-pr/devtest/tracelogging-examples.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/tracelogging-examples.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@CarePackage17 - Thanks for this issue pointing out that the code sample was missing the cpp code formatting information. That is added and the code is now easier to read. Thanks for caring about the docs and pointing out this docs issue!
