### ISSUE TITLE
Link to "Identifiers for Audio Devices" is broken

### ISSUE THREAD

**Issue by Sumit-Nbase2** [MicrosoftDocs/windows-driver-docs#3567]
[Enter feedback here]

Hello Microsoft, 

This is a feedback for the page in Description:
Link to "Identifiers for Audio Devices" is broken. 
[Identifiers for Audio Devices](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/identifiers-for-isapnp-devices) is tagged with ISAPNP Device Identifiers.

Please update the link for "Identifiers for Audio Devices". 

Thanks,
Sumit

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e29e581e-02a0-dab0-83db-25ae1ca1aebb
* Version Independent ID: 21141809-e821-8e58-dcf2-be1d1bb9be87
* Content: [Step 1 The New Device is Identified - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/step-1--the-new-device-is-identified)
* Content Source: [windows-driver-docs-pr/install/step-1--the-new-device-is-identified.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/step-1--the-new-device-is-identified.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by DOMARS** [comment]
@Sumit-Nbase2 - Thanks for seeing this error on my part and creating this helpful issue. The link is now fixed. Thanks for caring about the docs, and helping the next reader get to the proper audio topic!

**Comment by Sumit-Nbase2** [comment]
Most Welcome :)
