### ISSUE TITLE
nokia lumia 1520

### ISSUE THREAD

**Issue by amiratne** [MicrosoftDocs/windows-driver-docs#358]
Maigre mon appareil a jour

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d77677a1-6187-f77b-57ac-e67bb1f76fa2
* Version Independent ID: 8e9b5002-a835-bf3c-0ad1-c1313f2dfc84
* Content: [Driver Packages | Microsoft Docs](https://docs.microsoft.com/fr-fr/windows-hardware/drivers/install/driver-packages)
* Content Source: [windows-driver-docs-pr/install/driver-packages.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/driver-packages.md)
* Service: **unspecified**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi, thanks for contacting us, but I'm not sure what you're requesting.  Please re=open with specific feedback if you like.  Thanks!
