### ISSUE TITLE
References to BYTEs in DEVPROP_TYPE_SBYTE page

### ISSUE THREAD

**Issue by Rimpampa** [MicrosoftDocs/windows-driver-docs#3583]
The **Setting a Property of this Type** section refers to the `DEVPROP_TYPE_BYTE` type (instead of `DEVPROP_TYPE_SBYTE`).
Every occurrence of `BYTE` should be replaced with `SBYTE`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8c4d3f-23a2-54ee-488a-967b9aed5d76
* Version Independent ID: 233c99b0-b57d-212a-e995-7d01e40f9103
* Content: [DEVPROP_TYPE_SBYTE - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/devprop-type-sbyte)
* Content Source: [windows-driver-docs-pr/install/devprop-type-sbyte.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/devprop-type-sbyte.md)
* Product: **windows-hardware**
* Technology: **install**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hello Riccardo and thank you for the sharp eye.  I have corrected the instances of _BYTE on this page.  We appreciate your contacting us, and have a nice day!
