### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by rarndtjr** [MicrosoftDocs/windows-driver-docs#3584]
Need some examples and output.  Docs without examples and output just cause more confusion. Why not take a few min and provide meaningful examples of the command and expected output?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db41261a-2d84-e3cd-1bbc-5e3a2017dfc8
* Version Independent ID: c90582ea-486f-d068-3187-f9129f4c43d4
* Content: [.kframes (Set Stack Length) - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/-kframes--set-stack-length-)
* Content Source: [windows-driver-docs-pr/debugger/-kframes--set-stack-length-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-kframes--set-stack-length-.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@rarndtjr - Thanks for this input on providing input on examples for the use of the .kframes debugger command. I added example usage, showing checking, changing and overriding the kframes values. Good luck with your debugging work, and thanks for this suggestion.

**Comment by rarndtjr** [comment]
Thanks!
