### ISSUE TITLE
non-functioning email

### ISSUE THREAD

**Issue by DennisGlobal** [MicrosoftDocs/windows-driver-docs#3587]
The email adress: SAUEFI@microsoft.com doesnt seem to exist anymore.
please provide another working email or remove from the page please.

Page: Wi-Fi Support in Firmware

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5fb6392-e1c3-d784-7180-dc392bdfe4b8
* Version Independent ID: dfc9aced-7651-92e6-bd89-50a649102efd
* Content: [Wi-Fi support in firmware - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/bringup/wi-fi-support-in-firmware)
* Content Source: [windows-driver-docs-pr/bringup/wi-fi-support-in-firmware.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/wi-fi-support-in-firmware.md)
* Product: **windows-hardware**
* Technology: **bringup**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@DennisGlobal, thanks for pointing out the obsolete email link. It has been removed from the topic.
