### ISSUE TITLE
802.11r

### ISSUE THREAD

**Issue by ruderod** [MicrosoftDocs/windows-driver-docs#3588]
I have seen and questioned 802.11r support in Windows.  In researching this, I see that Intel proclaims that Windows 10 does not support 802.11r with WPA (passphrase).  The link is below.   So, Is this a true statement?   Does 802.11r support only work with certain security settings?

https://www.intel.com/content/www/us/en/support/articles/000021562/wireless.html
Thanks
Rod

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa7357ae-898c-6d3e-c5b8-245bbc405ec3
* Version Independent ID: 41c7119e-28c4-ebc4-4a53-879bfde6ee09
* Content: [Fast Roaming with 802.11k, 802.11v, and 802.11r - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/fast-roaming-with-802-11k--802-11v--and-802-11r)
* Content Source: [windows-driver-docs-pr/network/fast-roaming-with-802-11k--802-11v--and-802-11r.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/fast-roaming-with-802-11k--802-11v--and-802-11r.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Hi @ruderod, 
Thanks for your question. Yes, you are correct.
We only support 11r roaming (Fast Transition roaming) with WPA2/3-Enterprise, not WPA2/3-Personal.
WPA2/3-Enterprise uses Eap-based authentication, whereas WPA2/3-Personal uses passphrase/PSK-based authentication.
Note: We do not support 11r for WPA3-Enterprise-192 yet.
