### ISSUE TITLE
Wrong flag availability notes on PnPUtil Command Syntax page

### ISSUE THREAD

**Issue by ChristoWolf** [MicrosoftDocs/windows-driver-docs#3589]
Affectes [PnPUtil Command Syntax](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pnputil-command-syntax.md).

The tests were executed on Windows 10, version 1909 and upwards.

After a few tests, I found that a few flag availability notes are incorrect:
- For [`/enum-drivers`](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pnputil-command-syntax.md#enum-drivers) it says that the `/class` flag is only supported since Windows 11, version 21H2.
For me, this is not true, as I could use that flag with that command on machines with at least version 1909.
Haven't tried any lower versions yet.
- According to the docs, [`/enum-devices`](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/pnputil-command-syntax.md#enum-devices) supports the `/drivers` flag since version 1903, but it was not available for me in version 1909.

There might be more discrepancies, these are the ones that I found during some work.

**Comment by tedhudek** [comment]
Thanks @ChristoWolf for the report.  You are exactly right, there are some combinations of flags that came in different Windows versions so sometimes you can get seemingly odd results.  We are tracking internally and plan to publish more detailed flag information on this page soon.  I'm going to close this issue out for now, but I will try to notify you when the updates are live.  In the meantime, thanks again for caring about the docs!
