### ISSUE TITLE
Errors in Choosing a driver model

### ISSUE THREAD

**Issue by DonBurn** [MicrosoftDocs/windows-driver-docs#359]
You have Choosing a driver model for a file system driver and it then refers to File System Minifilter Drivers.  A minifilter is not a file system driver!   The link to minifilters should be under Choosing a driver model for a file system filter driver and the Choosing a driver model for a file system driver should point out the samples for file system drivers, perhaps with a warning that these are extremely advanced drivers, since Linux people have a simpler model, and get surprised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dcfd3e9-3d43-1140-cc8c-fe5f9e915a9d
* Version Independent ID: 4f665db9-d2bf-3720-f7a0-4176f796438a
* Content: [Choosing a driver model | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/choosing-a-driver-model#feedback)
* Content Source: [windows-driver-docs-pr/gettingstarted/choosing-a-driver-model.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/choosing-a-driver-model.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for the feedback, @DonBurn! Added a link for file system drivers and a warning that they can be complex. Should be live within 24 hours.
