### ISSUE TITLE
Abbr. Err

### ISSUE THREAD

**Issue by kingofforest666** [MicrosoftDocs/windows-driver-docs#3598]
L2TP is the abbreviation of Layer 2 Tunneling Protocol, Not Level 2 tunneling protocol.
![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/64643241/206feec8-c259-4269-be90-69f75843070b)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ac7dc50-a9c3-019d-ed49-561643e1aa39
* Version Independent ID: 6d6fa2ef-eac0-0c17-c073-bd41c6de5416
* Content: [AF_INET - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/af-inet)
* Content Source: [windows-driver-docs-pr/network/af-inet.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/af-inet.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thank you, @kingofforest666, for helping us improve the docs!
