### ISSUE TITLE
Error in specification: Force Ignore Version and Force Immediate Reset are swapped

### ISSUE THREAD

**Issue by hughsie** [MicrosoftDocs/windows-driver-docs#3599]
Hi all,

There's a mistake in [this specification](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/cfu/cfu-specification.md). `Table 5.2-3 FIRMWARE_UPDATE_OFFER Command` -- this uses `V` for `Force Ignore Version` in bit offset **15**, but the `Component Information Bits` text has it in bit offset **14**. Looking at the example headers showing the layout of:

      struct
      {
          UINT8 segmentNumber;
          UINT8 reserved0 : 6;
          UINT8 forceImmediateReset : 1;
          UINT8 forceIgnoreVersion : 1;
          UINT8 componentId;
          UINT8 token;
      } componentInfo;

I believe the diagram is correct, but the text is wrong. The `Force Immediate Reset` and `Force Ignore Version` sections are referring to the wrong bit offset.

**Comment by barrygolden** [comment]
@hughsie, thanks for filing an issue on the error you found in the [Component Firmware Update (CFU) protocol specification](https://learn.microsoft.com/windows-hardware/drivers/cfu/cfu-specification).

The Field and Description entries for Bit Offset rows 14 and 15 in **Table 5.2-3 FIRMWARE_UPDATE_OFFER Command - Component Information Bits** have been updated with the correct information (they were previously reversed as you indicated above).
