### ISSUE TITLE
Could you fix font error?

### ISSUE THREAD

**Issue by weignv** [MicrosoftDocs/windows-driver-docs#361]
Noticed that there are multiple arenâ€™t, which should be aren't. This error is shown in multiple web browsers and please take look at it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49099536-c363-e94d-ce10-44454344a8cd
* Version Independent ID: 4b143eee-1dd7-d523-dd2f-df506d592314
* Content: [Tile resources | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tile-resources)
* Content Source: [windows-driver-docs-pr/display/tile-resources.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/tile-resources.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @weignv. I got the instances in this topic. @tedhudek, can you scan for other occurrences and  log a bug to me?

**Comment by EliotSeattle** [comment]
The fix is in a commit for 22 files. Will update when this goes live.

**Comment by EliotSeattle** [comment]
These were merged to master. Thanks, @weignv, for pointing this out.

**Comment by weignv** [comment]
Thanks for fixing it.
