### ISSUE TITLE
Can't add new certificate

### ISSUE THREAD

**Issue by jbc22** [MicrosoftDocs/windows-driver-docs#3610]
Problem:

When following the steps to add a New Certificate to the organization, it fails with a message of "We encountered a problem processing the file you uploaded. please ensure the file you sign and upload is the same file you downloaded."

The test SignableFile.bin passes signtool.com verify /pa and DigiCert's Certificate Utility verification.

![Screenshot 2023-08-04 093539](https://github.com/MicrosoftDocs/windows-driver-docs/assets/32294/b114b0c6-4a6a-4bbf-bcb8-ba7e6cd921b5)

I am using signtool v10.0.19041.685 with the arguments "/tr http://timestamp.digicert.com /fd sha256 /td sha256".

Chrome Version 115.0.5790.110 (Official Build) (64-bit) on Windows 11 Home 22621.1992.

I have tried using Edge on the same PC, as well as Chrome on MacOS.

Side problem:

I'm submitting this in case it's related. When trying to remove old certificates, it fails and presents an "[object][object]" message.
![Screenshot 2023-08-04 110308](https://github.com/MicrosoftDocs/windows-driver-docs/assets/32294/f30362a0-c188-48b7-bf12-8b21d99e77b1)

**Comment by tedhudek** [comment]
Hi @jbc22 would you happen to have the URL of the page with the steps you are referencing?

**Comment by jbc22** [comment]
@tedhudek @anaharris-ms the URL: https://partner.microsoft.com/en-us/dashboard/account/v3/managecertificates?redirectedBy=AFD . You can confirm that's the URL I'm using in the screenshot above.

That page is responsible for both the main problem (addition of certificates) and the side problem (removal of certificates).

**Comment by anaharris-ms** [comment]
Hi @jbc22 ,

Have you attempted to contact support from that page?

**Comment by jbc22** [comment]
@anaharris-ms I have, without much luck.

**Comment by jbc22** [comment]
@anaharris-ms @tedhudek I'm not sure where I can reach out for help on this. Any guidance in the right direction would be much appreciated!

**Comment by spatil-intel** [comment]
Can you try using SHA384 instead of SHA256 for the signature ? It seems like Microsoft updated partner center recently and seem to be rejecting SHA256 signatures.  They need to update their documentation : https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage

**Comment by spatil-intel** [comment]
We just got confirmation that Microsoft has fixed the issue of not accepting SHA256 signatures for SignableFile.bin. Looks like it is working again the way it used too. The issue with removal of certificates still remains though.
