### ISSUE TITLE
Any plan to support more SetFeature include vendor-specific ?

### ISSUE THREAD

**Issue by changhwankim** [MicrosoftDocs/windows-driver-docs#3616]
Current StorNVMe driver has partial support for Set Feature (obly HCTM). 

From https://learn.microsoft.com/en-us/windows/win32/fileio/working-with-nvme-devices, 
the driver support 'Pass-through mechanism' for vendor specific commands based on 'The Command Effects Log' , but for vendor-specific feature MS says 'The Command Effects Log is not yet granular enough to encompass vendor-specific Set-Features commands. For this reason, it is not yet possible to send vendor-specific Set-Features commands.' 

However, from NVMe 2.0 spec "5.16.1.18 Feature Indentifiers Supported and Effects Log (Log Identifier 12h)" has been introduced (In NVMe Base Specification). 

Is there any plan to support more SetFeature include vendor-specific features in StorNVMe driver based on above info ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40f20f63-14d2-cac3-fd82-4a4352918189
* Version Independent ID: addc1d08-2a90-d363-40c0-c8f83fe26699
* Content: [StorNVMe command set support - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/storage/stornvme-command-set-support)
* Content Source: [windows-driver-docs-pr/storage/stornvme-command-set-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/stornvme-command-set-support.md)
* Product: **windows-hardware**
* Technology: **storage**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
@changhwankim, I'm closing this issue since it's a product release question (that we can't answer) versus a documentation issue. We will update the NVMe pages are new features are released!
