### ISSUE TITLE
just wow just the tip of the iceberg 🧊 

### ISSUE THREAD

**Issue by SquirrelCode0** [MicrosoftDocs/windows-driver-docs#3617]
[Enter feedback here]

Drivers are indeed more complex than I thought 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09bf2768-65ed-dbbd-a5ce-e3cd5ab58aa6
* Version Independent ID: 1169dfa4-e2c0-62e4-0bfa-42bab3ed1ade
* Content: [What is a driver? - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/what-is-a-driver-)
* Content Source: [windows-driver-docs-pr/gettingstarted/what-is-a-driver-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/what-is-a-driver-.md)
* Product: **windows-hardware**
* Technology: **gettingstarted**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by rodwiddowson** [comment]
yup.  And its iterative.  even after 20 years "Drivers are more complex than I thought".  Files System drivers doubly so
