### ISSUE TITLE
Windbg info is wrong/misleading

### ISSUE THREAD

**Issue by dthaler** [MicrosoftDocs/windows-driver-docs#3618]
aka.ms/ttd does not point to aka.ms/windbg.  It only says "WinDbg version 1.0.13.0 and newer" with no link.  Specifically, the windbg in the Windows 10 kits installs version 10.0.22621.755.
And one would think v10 should be newer than v1. However the windbg in the kits does not support ttd, and the ttd page does not provide any link to where to get the lower numbered version of windbg.   Hence I think the ttd page needs to be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbe23f42-e182-5876-7324-1abc4338f9c5
* Version Independent ID: c5193b6f-c876-3e20-3ea7-53da98eb4b89
* Content: [Time Travel Debugging - Overview - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview?source=docs)
* Content Source: [windows-driver-docs-pr/debugger/time-travel-debugging-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/time-travel-debugging-overview.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@dthaler - As we have an email thread to explore possible solutions, I will close this docs issue. 

In addition to considering what we can do in the docs to be more helpful here, there may also be some product changes, such as version numbering. The debugger team has a public facing product issue site - http://aka.ms/dexex which goes to https://github.com/microsoftfeedback/WinDbg-Feedback/issues
I looked there and I didn't see anything on at least the versioning part of this. 

Thanks for this input, and for thinking about possible improvements to make the use and maintenace of the debugger easier.
