### ISSUE TITLE
AMD Radeon driver Update Iissue for Radeon 660M

### ISSUE THREAD

**Issue by admincyber-id** [MicrosoftDocs/windows-driver-docs#3619]
[Enter feedback here]
AMD driver update from microsoft make the screen stuck at maximum brightness

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Version Independent ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Content: [Get support for Partner Center dashboard issues - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support)
* Content Source: [windows-driver-docs-pr/dashboard/hardware-submission-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-support.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
Hi @admincyber-id,

This looks like it is a support issue, and not a documentation issue. Please follow the directions here: https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support#technical-support-issues to submit a support ticket.

Thank you.
