### ISSUE TITLE
Broken NdisMWriteConfigBlock links

### ISSUE THREAD

**Issue by AlvinTanMS** [MicrosoftDocs/windows-driver-docs#3622]
All links to NdisMWriteConfigBlock are instead going to NdisMReadConfigBlock.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86b70875-f837-e4a4-8440-1ea3cf831b12
* Version Independent ID: a2bd83e2-1f49-b7f5-f517-417a683ab4db
* Content: [Backchannel Communication from a VF Miniport Driver - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/network/backchannel-communication-from-a-vf-miniport-driver)
* Content Source: [windows-driver-docs-pr/network/backchannel-communication-from-a-vf-miniport-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/backchannel-communication-from-a-vf-miniport-driver.md)
* Product: **windows-hardware**
* Technology: **network**
* GitHub Login: @aviviano
* Microsoft Alias: **amvivian**

**Comment by aviviano** [comment]
Thanks for helping us improve the docs, @AlvinTanMS. I've updated the page and the fix will be live soon.
