### ISSUE TITLE
this is now in production ring

### ISSUE THREAD

**Issue by jeffstokes72** [MicrosoftDocs/windows-driver-docs#3628]
[Enter feedback here]

I see it in the UI on regular consumer channel for windows 11 pro 22621
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 225b43c6-8f82-62c7-44ff-77150157d4f5
* Version Independent ID: 225b43c6-8f82-62c7-44ff-77150157d4f5
* Content: [Task Manager live memory dump - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/task-manager-live-dump)
* Content Source: [windows-driver-docs-pr/debugger/task-manager-live-dump.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/task-manager-live-dump.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@jeffstokes72 - Thanks for pointing out that the live dump feature is now widely available. I updated the topic to mention the regular production build of Windows and link to the KB for that release - https://support.microsoft.com/en-us/topic/july-11-2023-kb5028185-os-build-22621-1992-605fa18f-bd49-41d8-80b1-245080e26c3d. Thanks for your help in improving the Windows driver docs!
