### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by Bhavanakoya** [MicrosoftDocs/windows-driver-docs#3630]
[Enter feedback here]

it was not updating
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Version Independent ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Content: [Get support for Partner Center dashboard issues - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support)
* Content Source: [windows-driver-docs-pr/dashboard/hardware-submission-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-support.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by tedhudek** [comment]
Not seeing any actionable feedback - please reopen with details as needed
