### ISSUE TITLE
Can driver that only have Win 11 22H2 HLK expand to Win 11 21H2?

### ISSUE THREAD

**Issue by youngLabau** [MicrosoftDocs/windows-driver-docs#3635]
We have a driver that only got the certification for Win11 22H2 HLK and has been published to Windows Update for 22H2
Can we expand this driver to 21H2 in Win 11 Windows Update?

Thanks a lot.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e888e07f-1323-59a9-2c2f-14e9f814f552
* Version Independent ID: de2aa427-004a-b1a8-270d-cf13d0c9ed91
* Content: [How to limit or expand a driver’s distribution based on Windows version - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/limit-driver-distribution)
* Content Source: [windows-driver-docs-pr/dashboard/limit-driver-distribution.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/limit-driver-distribution.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
Hi @youngLabau,

You'll need to open a ticket with the support team. They should be able to help you with your questions. To submit a ticket, follow the directions in [Submit support request](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support#technical-support-issues.)
