### ISSUE TITLE
Article is a stub

### ISSUE THREAD

**Issue by Drigax** [MicrosoftDocs/windows-driver-docs#364]
Some additional information such as sample logs, the formatting of log entries, and links to tools used for log viewing would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b59527c-6f99-59a1-d6e8-d5f38acca554
* Version Independent ID: d7c8d44e-8b7d-e974-3022-167d39405868
* Content: [Trace Log | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/trace-log)
* Content Source: [windows-driver-docs-pr/devtest/trace-log.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/trace-log.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @Drigax, fort he suggestions. The topic that this links to, **Trace Session** (https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/trace-session) contains more information about the log and its format, but I can see where there is room for the additional content, too. I'm logging a work item for this, and we'll weigh our ability to get to the changes based on our other priorities. If you want, you're welcome to submit content as a pull request, too.
All the best.
Eliot
