### ISSUE TITLE
Surface pro 7+ keypad mouse not working after today Surface - Firmware - 22.103.143.0 update.

### ISSUE THREAD

**Issue by bkyetukuri** [MicrosoftDocs/windows-driver-docs#3644]
[Enter feedback here]
Surface pro 7+ keypad mouse not working after today Surface - Firmware - 22.103.143.0 update.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Version Independent ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Content: [Get support for Partner Center dashboard issues - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support)
* Content Source: [windows-driver-docs-pr/dashboard/hardware-submission-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-support.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by tedhudek** [comment]
Sorry to hear about the problem @bkyetukuri.  This isn't the forum to report it however.  Best of luck!
