### ISSUE TITLE
What defines "FailStatus" Under "Compressed Store Manager error parameters"? (0x12b Stop Code)

### ISSUE THREAD

**Issue by Blobanium** [MicrosoftDocs/windows-driver-docs#3645]
[Enter feedback here]
So my pc crashed last night with 0x12b and after some investigating and some research, it seems to be that parameters three and four are not zero indicating a [Compressed Store Manager (CSM) Error.](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x12b---faulty-hardware-corrupted-page#compressed-store-manager-error-parameters) The first Parameter in the four parameters is "FailStatus - Indicates the type of failure". However, there isn't any reference table or any detail regarding this parameter at all. And also no luck with doing google searches as well.

My Request is to add more detail to what "FailStatus" defines. If there is an article that already defines what "FailStatus" is then there should be a link directing to that section within the article. If not, details regarding "FailStatus" should be added in the article like for example, `0x1` is x and `0x2` is y and so on. 

In the case of the first parameter on my crash, its `0xffffffffc00002c4`
 
If some things seem unclear let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ceedbb73-ac5a-74bd-5747-bff43f2b639b
* Version Independent ID: 4118fb85-66db-5598-0512-fa2315bd30c7
* Content: [Bug Check 0x12B FAULTY_HARDWARE_CORRUPTED_PAGE - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x12b---faulty-hardware-corrupted-page)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x12b---faulty-hardware-corrupted-page.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x12b---faulty-hardware-corrupted-page.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Blobanium - Thanks for this input on adding additional information on the fail status parameter one for compressed store manager memory errors, to the 0x12b bug check. We use input like this to guide future docs work. In this case, it does not appear that adding additional information on the type of failure would provide imediate help for the resolution of this bug code, but will consider adding additional information in the future, as doc team resources allow. Many of these memory compression failures are transitory, for example by a memory system component, power supply or environmental factor such as input voltage. If you see re-occuring memory compression errors, with a similar failure signature, this typically indicates a faling memory component.  In this case, using the Windows or vendor provided memory scan utilities can help locate a failing memory component, such as DRAM. Thermal, bus and power supply problems are more difficult to diagose. Reviewing the event log, for other errors proceding the bug check or noting the time of day may help provide additional information. For further investigation of your specific failure, you may wish to consult the forums, such as the one provided by OSR - [OSR's windbg List](https://community.osr.com/categories/windbg). Thanks for providing this input and good luck with resolving the issue with your PC.
