### ISSUE TITLE
PcRegisterSubdevice failed with STATUS_ALLOTTED_SPACE_EXCEEDED

### ISSUE THREAD

**Issue by SlimSnow** [MicrosoftDocs/windows-driver-docs#3656]
```[tasklist]
### Tasks
```

**Comment by tedhudek** [comment]
Sorry, can you provide more info about what you are requesting?

**Comment by SlimSnow** [comment]
Sorry,I shoud provide more info previously.
The situation is that I am a newer to windows kernel driver and I want to dynamic add subdevices  a pair of mic and speaker.I have a app to send custom IOCTL code to the driver ,and when driver receive the code will add a pair of subdevices.But when I want to add the sixth pair of subdevices the API PcRegisterSubdevice failed with STATUS_ALLOTTED_SPACE_EXCEEDED.I think i pass valid parameters to PcRegisterSubdevice.
![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/46469516/c4d5f82c-2483-4cc5-b5de-02a642d606e3)
![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/46469516/75af2575-e142-4100-8ba3-654851146e0f)
![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/46469516/fd44f5c1-c20d-4e64-9472-d13a8d789c15)
I am not sure is this issue caused by the subdevices name is the same,I wanna change the subdevices name, but like I said I am a newer to Windows kernel I do not faind a way to make subdevices name unique. Do you have any ideas?Thank you so muck and looking forward to your reply.

**Comment by tedhudek** [comment]
Hi @SlimSnow,

There could be a limit of 5.  Or you could try unique names. But I do not have specific knowledge in this area, so I am not sure how to do that.  I would recommend posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive. This repo is for documentation, so if you discover anything that you think we should add to the docs, feel free to let us know.

* [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions)
* [OSR's NTDEV forum](https://community.osr.com/categories/ntdev)
