### ISSUE TITLE
This has been broken for years

### ISSUE THREAD

**Issue by scheater5** [MicrosoftDocs/windows-driver-docs#3658]
This method of creating samba shares hasn't worked in months and is demonstrably broken on updated versions of Windows.  It just results in permission errors in situations where previously this method worked perfectly. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a1fd883-f81b-b48f-4c5e-70c1140db075
* Version Independent ID: 40dcc625-51c4-0985-d5a7-a73a58d4e748
* Content: [File share (SMB) symbol server - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/file-share--smb--symbol-server)
* Content Source: [windows-driver-docs-pr/debugger/file-share--smb--symbol-server.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/file-share--smb--symbol-server.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@scheater5 - Thanks for pointing out that the things have changed in Windows for setting up and configuring SMB shares. I have added a link to [https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3?tabs=server](https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3?tabs=server) to help alert other users that depending on the SKU and version of Windows, additional configuration is required to enable the desired version of SMB.  This tech community article provides some information about enabling SMB in SAMBA. https://techcommunity.microsoft.com/t5/storage-at-microsoft/smb1-product-clearinghouse/ba-p/426008 There are also some changes to disable the guest account, where in the past that account was used as a convenient way to allow easy access to shares.
