### ISSUE TITLE
Object manager routines link 

### ISSUE THREAD

**Issue by karolKiedrowski** [MicrosoftDocs/windows-driver-docs#3659]
Link to see object manager routines directs to the wrong page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88bcd162-235d-5e13-feab-f14a45c9d989
* Version Independent ID: 01c12121-3393-41a9-1c82-e5a9d97aaaf9
* Content: [Windows Kernel-Mode Object Manager - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/windows-kernel-mode-object-manager)
* Content Source: [windows-driver-docs-pr/kernel/windows-kernel-mode-object-manager.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/windows-kernel-mode-object-manager.md)
* Product: **windows-hardware**
* Technology: **kernel**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hey Karol thanks, I'm really glad you mentioned this.  The target page went away, so I have updated https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/windows-kernel-mode-object-manager with another way you can find these.

Another way to is clone https://github.com/MicrosoftDocs/windows-driver-docs-ddi and then in PowerShell run `gci -r -File nf*-ob*` .  You'll see there are currently a total of 23.

Hope this helps!
