### ISSUE TITLE
RSS availability in Windows Server 2012 R2

### ISSUE THREAD

**Issue by StefanoAmbrogi** [MicrosoftDocs/windows-driver-docs#366]
Is RSS available in Windows server 2012 R2? As per https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh997036(v%3dws.11) the availability of this feature is limited to Windows Server 2012 and previous release.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 915e4234-78ae-7326-f219-4ae7390f1307
* Version Independent ID: f4d10278-3352-8e26-d7d5-dcb52e93dd2b
* Content: [Introduction to Receive Side Scaling | Microsoft Docs](https://docs.microsoft.com/it-it/windows-hardware/drivers/network/introduction-to-receive-side-scaling)
* Content Source: [windows-driver-docs-pr/network/introduction-to-receive-side-scaling.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/introduction-to-receive-side-scaling.md)
* Service: **unspecified**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @StefanoAmbrogi , thanks for the question. RSS is a currently supported feature and is available in Windows Server 2012 R2 and Windows Server 2016. I believe that the Previous Versions document to which you linked discusses what was new for RSS in WS 2012, but it was not meant to convey that RSS was not supported past WS 2012. Sorry for the confusion.
