### ISSUE TITLE
i  dont know

### ISSUE THREAD

**Issue by Designstanic** [MicrosoftDocs/windows-driver-docs#3660]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Version Independent ID: 9c82359b-d6a0-4f42-a6e1-a5e83f1edfeb
* Content: [Get support for Partner Center dashboard issues - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support)
* Content Source: [windows-driver-docs-pr/dashboard/hardware-submission-support.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-support.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
Hi @Designstanic,

Did you forget to describe your issue? Please let me know what problem you are having so I can help.
