### ISSUE TITLE
Just wondering about `ValdateAgainstBaselineResource`

### ISSUE THREAD

**Issue by assarbad** [MicrosoftDocs/windows-driver-docs#3664]
Hi, is `ValdateAgainstBaselineResource` intentionally misspelled because it was an honest mistake and now cannot be fixed for compatibility reasons just like with the HTTP `Referer` header? ... or is it perhaps a mistake of the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 220bd4df-feac-cf06-8e8b-621b4b9615f5
* Version Independent ID: 946e20ec-11bb-1ecf-48b3-76a9fb47ce1d
* Content: [Message compiler task - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/message-compiler-task)
* Content Source: [windows-driver-docs-pr/devtest/message-compiler-task.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/message-compiler-task.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@assarbad - This is an error in the documentation that I corrected today. The misspelled validate does not match what is used in current day,  `WindowsDriver.Common.targets` which is MessageCompile.ValidateAgainstBaselineResource, the docs now reflect this spelling. Thanks for seeing this error and filing this issue!
