### ISSUE TITLE
Bugcheck 0x139 with the first parameter 0x3a

### ISSUE THREAD

**Issue by amirsaleh-alavi** [MicrosoftDocs/windows-driver-docs#3666]
Would it be possible to update the list of parameter 1 for bug check 0x139 to include 0x3a? I have encountered it in a Windows 11 VM, and not I'm not able to troubleshoot, cause of the lack of information I have.

**Comment by DOMARS** [comment]
@amirsaleh-alavi - Thanks for the input that we should add additional information on Bug Check 0x139. We use customer input like this, as well as data on how often the bug checks occur, to determine how we allocate our documentation team resources. As you may know, we provide general developer guidance in topics such as https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/blue-screen-data. Enabling driver verifier and having a debugger attached, may help provide more information on which driver is triggering this sub code. 

In general, if a specific driver continues to cause this stop code, the developer of that driver will need to update their code. If you don't have the source code, you can try updating the driver, if a newer version is available. 

We will use your input and other data, to determine if we can provide additional information on this stop code that is broadly applicable. Again, thanks for the input, and good luck with your issue.
