### ISSUE TITLE
Incorrect DigiCert link

### ISSUE THREAD

**Issue by Scaless** [MicrosoftDocs/windows-driver-docs#3668]
The 'DigiCert EV code signing certificate' link goes to the wrong page. It links to a document-signing certificate purchase instead of code-signing. The correct link should be: https://www.digicert.com/signing/code-signing-certificates

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 201e882f-799d-3ce0-6cd2-af4a5feb38f6
* Version Independent ID: 201e882f-799d-3ce0-6cd2-af4a5feb38f6
* Content: [Manage code signing certificates - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage)
* Content Source: [windows-driver-docs-pr/dashboard/code-signing-cert-manage.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/code-signing-cert-manage.md)
* Product: **windows-hardware**
* Technology: **dashboard**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
Thank you for noticing that, @Scaless. Fixed!
