### ISSUE TITLE
Good page but!

### ISSUE THREAD

**Issue by maitreyotta** [MicrosoftDocs/windows-driver-docs#367]
In X64 calling convention i want find more explanation of r10-r15 register, thank you for you already work. sorry for my bad english i am french...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc07ad07-7d1c-e42d-506d-de67e4a02494
* Version Independent ID: ed140094-1331-1502-6618-158307cd73f3
* Content: [x64 Architecture | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/x64-architecture)
* Content Source: [windows-driver-docs-pr/debugger/x64-architecture.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/x64-architecture.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@maitreyotta, thanks for this input. I added links in a new see also to these resources in a new see also section:
X86-64 Wikipedia
AMD 64 Developer Resources
Refer to these resources for more information about the registers.
