### ISSUE TITLE
no information about IRP_MJ_FILE_SYSTEM_CONTROL

### ISSUE THREAD

**Issue by karolKiedrowski** [MicrosoftDocs/windows-driver-docs#3674]
There is no information about IRP_MJ_FILE_SYSTEM_CONTROL in this neither previos section.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39d4c36b-872d-6454-0525-46876caaa912
* Version Independent ID: 381982c3-c5a9-4f38-2a42-3c935fd506fa
* Content: [Optional Dispatch Routines - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/optional-dispatch-routines)
* Content Source: [windows-driver-docs-pr/kernel/optional-dispatch-routines.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/optional-dispatch-routines.md)
* Product: **windows-hardware**
* Technology: **kernel**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Thanks for the feedback @karolKiedrowski.  Can you provide more detail on what specifically you are trying to accomplish?  I think that will enable me to help you better.

**Comment by karolKiedrowski** [comment]
I need an explanation about dispatch routine that is responsible for
processing of given irp message

czw., 12 paź 2023, 01:45 użytkownik Ted Hudek ***@***.***>
napisał:

**Comment by tedhudek** [comment]
What type of driver are you writing?  Is it by any chance a file system driver or a file system filter driver?

You could try asking https://www.bing.com/chat for sample code for a dispatch routine.  I just tried it, and it gave me starter code based on the documentation and sample code it found.

**Comment by tedhudek** [comment]
Closing out for now, please reopen if still needed.
