### ISSUE TITLE
CircularLog.cmd is missing

### ISSUE THREAD

**Issue by vandermerwewaj** [MicrosoftDocs/windows-driver-docs#3676]
[Enter feedback here]
The circularlog.cmd did not install into the gpuview folder as this page claims.
![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/98828977/8cc8fd95-d10f-4798-82d6-005efbbcc798)
![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/98828977/a083b2da-754c-44ea-af50-0236b05d0151)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58786850-1c1f-20d9-e61e-51e71a4f2550
* Version Independent ID: 58786850-1c1f-20d9-e61e-51e71a4f2550
* Content: [Generating a Trace for GPUView - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/display/generating-a-trace-for-gpuview)
* Content Source: [windows-driver-docs-pr/display/generating-a-trace-for-gpuview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/generating-a-trace-for-gpuview.md)
* Product: **windows-hardware**
* Technology: **display**
* GitHub Login: @lorihollasch
* Microsoft Alias: **loriwhip**

**Comment by lorihollasch** [comment]
Thanks for reporting this, @vandermerwewaj! Circularlog.cmd doesn't ship with GpuView so I've removed mention of it.
