### ISSUE TITLE
No mention of tools for test signing

### ISSUE THREAD

**Issue by naveensadashiviah** [MicrosoftDocs/windows-driver-docs#3678]
The page header says "Tools for Test Signing", however none of the tools mentioned seem to help in test signing or to create a test signature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7af8e08-a54a-45de-da0f-1bef75d025aa
* Version Independent ID: 4ef539e6-2ce8-bcd0-df42-76910cca364a
* Content: [Tools for Testing Drivers - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/tools-for-testing-drivers)
* Content Source: [windows-driver-docs-pr/devtest/tools-for-testing-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/tools-for-testing-drivers.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@naveensadashiviah - Thanks for this input on making the driver signing tools easier to find. I added a link on this page to [Additional Tools for Testing Drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/additional-driver-tools), which has a link to [Tools for Signing Drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/tools-for-signing-drivers)
Thanks for the input, and good luck with your driver development work.
