### ISSUE TITLE
Should be "registry value" not "registry key"

### ISSUE THREAD

**Issue by guyrleech** [MicrosoftDocs/windows-driver-docs#3679]
Should be "registry value" not "registry key" as PowerButtonBugcheck is a value (contained in a key)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1588a741-e5c7-bc74-4824-931a09d5c830
* Version Independent ID: 5e00f94e-fec0-5165-a35e-0f61abf0f2c8
* Content: [Forcing a System Crash with the Power Button - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/forcing-a-system-crash-with-the-power-button)
* Content Source: [windows-driver-docs-pr/debugger/forcing-a-system-crash-with-the-power-button.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/forcing-a-system-crash-with-the-power-button.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@guyrleech - Thanks for pointing this registry terminology mistake out, I updated the topic to refer to the registry value that is being set, in the example to 00000001:
`"PowerButtonBugcheck"=dword:00000001 `
Thanks for helping to improve the debugger docs!
