### ISSUE TITLE
Docs incorrect on allowed hybrid drivers SDV works on

### ISSUE THREAD

**Issue by jcbottorff** [MicrosoftDocs/windows-driver-docs#369]
The docs say: The driver does not combine driver models (for example, KMDF with WDM, or KMDF and NDIS). SDV does work with two way hybrid drivers, but not three way hybrids.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5fd6a7f-6aab-f9b0-e4ab-ea54383adc80
* Version Independent ID: b3bd9ec2-cc7e-98c6-b445-045f2ac4a481
* Content: [Determining if Static Driver Verifier supports your driver or library | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/determining-if-static-driver-verifier-supports-your-driver-or-library)
* Content Source: [windows-driver-docs-pr/devtest/determining-if-static-driver-verifier-supports-your-driver-or-library.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/determining-if-static-driver-verifier-supports-your-driver-or-library.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Don, can you take a look at this feedback for Static Driver Verifier and correct content if it's true?

**Comment by EliotSeattle** [comment]
@aahill please verify this request and add it if appropriate. Thanks, E.

**Comment by aahill** [comment]
Hi @jcbottorff , sorry for the delay on this; I've reached out to the SDV team, who plan to address this in an upcoming doc update. Thanks so much for letting us know about this.
