### ISSUE TITLE
What about other channels?

### ISSUE THREAD

**Issue by matlimatli** [MicrosoftDocs/windows-driver-docs#3701]
The sample project and the page only add events to the System channel, added to the provider with importChannel. It seems straightforward to change this and add a custom channel (`<channel chid="MyChan" name="SampleDriver/Admin" type="Admin" enabled="true" />`). However, this doesn't seem to work. Therefore it would be good if the page could either outline how this could be done, or alternatively specify that (and why) it is not possible.

Edit: The solution seems to be `isolation="System"`, alternatively Custom isolation and specifying the exact access settings. Just using `access=...` and allowing everything didn't seem to work. So this might be worth mentioning on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f93c1d9-ccc3-bc8a-14d9-7b23df2773c0
* Version Independent ID: 50326231-07f4-0f95-3dec-76fc49a75612
* Content: [Adding Event Tracing to Kernel-Mode Drivers - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/adding-event-tracing-to-kernel-mode-drivers)
* Content Source: [windows-driver-docs-pr/devtest/adding-event-tracing-to-kernel-mode-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/adding-event-tracing-to-kernel-mode-drivers.md)
* Product: **windows-hardware**
* Technology: **devtest**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@matlimatli - Thanks for this input on providing more information on custom channels on this docs page. I added a link to the channels topic - [Defining Channels](/windows/win32/wes/defining-channels). I think for most folks starting out, following one of the samples such as the [Eventdrv sample](https://learn.microsoft.com/en-us/samples/microsoft/windows-driver-samples/eventdrv/) without too much customization is a good first goal. Many users miss one of the steps that are required, so just getting the samples working as is, often a good first step - which is the goal of this topic. Further customization work would rely on the win32 topics such as [Writing an Instrumentation Manifest](https://learn.microsoft.com/en-us/windows/win32/wes/writing-an-instrumentation-manifest). In the future we can consider an expanded example, that provides more information on customization eventing options, of which there are many. 
We also look to the community, for customization examples, such as described in blogs: https://nasbench.medium.com/a-primer-on-event-tracing-for-windows-etw-997725c082bf
And in the more advanced driver samples, such as in DMF: https://github.com/microsoft/DMF/blob/master/Dmf/Documentation/Driver%20Module%20Framework.md#in-flight-recording-ifr-of-trace-messages-from-modules
Thanks again for this input, and good look with your driver development work.
