### ISSUE TITLE
Typo "sceanrio"

### ISSUE THREAD

**Issue by guyrleech** [MicrosoftDocs/windows-driver-docs#3705]
The word "scenario" is spelt incorrectly as "sceanrio"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b225392c-a057-a2b6-28be-a0939f4834ba
* Version Independent ID: d94f25da-8679-f2b0-ed24-4b40712bf695
* Content: [Forcing a system crash from the keyboard - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/forcing-a-system-crash-from-the-keyboard)
* Content Source: [windows-driver-docs-pr/debugger/forcing-a-system-crash-from-the-keyboard.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/forcing-a-system-crash-from-the-keyboard.md)
* Product: **windows-hardware**
* Technology: **debugger**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
Misspelling in the docs is not a good scenario, so this has been fixed.
