### ISSUE TITLE
Helpful videos, but ...

### ISSUE THREAD

**Issue by Marc-Albrecht** [MicrosoftDocs/windows-driver-docs#373]
... it would be even more helpful if you would omit the nerve-wracking background music (that is just too loud anyway). Remember that not everyone watching these videos is a native English speaker, so (almost) overpowering narration by computer-made music can be a real distraction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b034fd72-470b-76e3-e080-46cb688242db
* Version Independent ID: 3fde5448-65db-8332-2194-c3b301d0d4d5
* Content: [Capture and view USB traces with Microsoft Message Analyzer](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/capture-and-view-ing-usb-traces-with-microsoft-message-analyzer-)
* Content Source: [windows-driver-docs-pr/usbcon/capture-and-view-ing-usb-traces-with-microsoft-message-analyzer-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/capture-and-view-ing-usb-traces-with-microsoft-message-analyzer-.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @Marc-Albrecht.

Thanks for taking the time to provide feedback. I have passed this on to our video team. Appreciate the viewpoint an the music v. narration.

Eliot
