### ISSUE TITLE
Being asked for authentication

### ISSUE THREAD

**Issue by ManOnTheMountainTech** [MicrosoftDocs/windows-driver-docs#3738]
[Enter feedback here]
WinDbg asks for credentials when loading the source for WDF. The article states that the source will pop up without having to enter credentials.
![TFS credentials](https://github.com/MicrosoftDocs/windows-driver-docs/assets/25311999/9d6c45d1-aaea-4a8a-a1aa-1bbb5f0b889b)

"The server dev.azure.com is asking for your user name and password..." Please see the attached screen shot.

As there are private symbols, lines, and it is source indexed, then there are no secrets so the source might as well be distributed.

Here are the details for the WDF PDB so that maybe the corresponding source can be matched.
!lmi wdf01000.sys
Loaded Module Info: [wdf01000.sys] 
         Module: Wdf01000
   Base Address: fffff80062d80000
     Image Name: Wdf01000.sys
   Machine Type: 34404 (X64)
     Time Stamp: 20ca8670 (This is a reproducible build file hash, not a true timestamp)
           Size: c7000
       CheckSum: cab69
Characteristics: 22  
Debug Data Dirs: Type  Size     VA  Pointer
             CODEVIEW    25, 972d0,   972d0 RSDS - GUID: {C8B65AE1-3705-F231-9A30-79ED3B39AB03}
               Age: 1, Pdb: Wdf01000.pdb
                 POGO   404, 972f8,   972f8 [Data not mapped]
                REPRO    24, 9777c,   9777c Reproducible build
           DLLCHAR_EX     4, 977a0,   977a0 Extended DLL characteristics: 00000001
                                                 CET compatible
     Image Type: MEMORY   - Image read successfully from loaded memory.
    Symbol Type: PDB      - Symbols loaded successfully from image header.
                 C:\ProgramData\Dbg\sym\Wdf01000.pdb\C8B65AE13705F2319A3079ED3B39AB031\Wdf01000.pdb
       Compiler: C - front end [19.30 bld 30795] - back end [19.30 bld 30795]
    Load Report: private symbols & lines, source indexed 
                 C:\ProgramData\Dbg\sym\Wdf01000.pdb\C8B65AE13705F2319A3079ED3B39AB031\Wdf01000.pdb

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b231b5a-b4d3-12ee-4682-e66806dcafa6
* Version Independent ID: 70227f78-0710-18d8-4b68-61b1143cb625
* Content: [Video Debugging your driver with WDF source code - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/video--debugging-your-driver-with-wdf-source-code)
* Content Source: [windows-driver-docs-pr/wdf/video--debugging-your-driver-with-wdf-source-code.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/video--debugging-your-driver-with-wdf-source-code.md)
* Product: **windows-hardware**
* Technology: **wdf**
* GitHub Login: @tedhudek
* Microsoft Alias: **tedhudek**

**Comment by tedhudek** [comment]
Hi @ManOnTheMountainTech,

Thanks for the question.  You can still debug WDF with private symbols, but the source code won't match exactly. The video you reference on the docs site is still good information but does not 100% match the user experience anymore.

Hope that helps!
