### ISSUE TITLE
A link to where to download the tool would be useful.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/windows-driver-docs#374]
More useful than scouring the internet for it, anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c066ba05-c44b-60d2-0910-22de78448bc5
* Version Independent ID: 3aa09560-626c-874b-9f2c-363790c4987d
* Content: [SymStore](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symstore)
* Content Source: [windows-driver-docs-pr/debugger/symstore.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/symstore.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@StingyJack - The SymStore page (https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symstore) now has a link to the download page. Thanks for the input.
