### ISSUE TITLE
lockScreenCall throws exception in Windows 11

### ISSUE THREAD

**Issue by ErikApption** [MicrosoftDocs/windows-driver-docs#3743]
lockScreenCall capability in appxmanifest throws exception in Windows 11

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82735562-385b-1ac5-b0a5-1caa2b400d87
* Version Independent ID: dafdf1b8-d884-2074-7d25-ad387bcf7850
* Content: [Kiosk apps for assigned access Best practices - Windows drivers](https://learn.microsoft.com/en-us/windows-hardware/drivers/partnerapps/create-a-kiosk-app-for-assigned-access)
* Content Source: [windows-driver-docs-pr/partnerapps/create-a-kiosk-app-for-assigned-access.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/partnerapps/create-a-kiosk-app-for-assigned-access.md)
* Product: **windows-hardware**
* Technology: **partnerapps**
* GitHub Login: @barrygolden
* Microsoft Alias: **bagold**

**Comment by barrygolden** [comment]
@ErikApption, thanks for your feedback on this article.  

You may have success posting a question about lockScreenCall capability in appxmanifest throwing an exception in Windows 11 in the following forums, where other driver developers and Microsoft engineers can be found. 

[Microsoft Q&A: Windows Hardware development](https://docs.microsoft.com/answers/topics/windows-hardware.html)

[OSR Developer Community](https://community.osr.com/)
