### ISSUE TITLE
Customer feedback - The type of property PartitionStyle is wrong

### ISSUE THREAD

**Issue by vinixwu** [MicrosoftDocs/windows-driver-docs#3748]
### Type of issue

Outdated article

### Feedback

According to document, the type of property PartitionStyle is UInt16, but when I debug the PowerShell code that returned MSFT_Disk object of a MBR disk, I found that $disk.PartitionStyle -eq "mbr" is true, but $disk.PartitionStyle -eq 1 is false.

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/storage/msft-disk

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/msft-disk.md

### Author

@lorihollasch

**Comment by lorihollasch** [comment]
Thanks for the issue, @vinixwu. PartitionStyle is indeed a UInt16. PowerShell frequently maps property integer values to have more intelligible string names, which explains the results of your $disk.PartitionStyle checks. To see PS's mappings, run:
> (Get-Module Storage).ExportedTypeFiles
and look in the file it outputs (my output is: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Storage\Storage.types.ps1xml)

Search for PartitionStyle and you'll find:
    <ScriptProperty>
        <Name>PartitionStyle</Name>
        <GetScriptBlock>
          switch ($this.psBase.CimInstanceProperties["PartitionStyle"].Value)
          {
          0 { "RAW" }
          1 { "MBR" }
          2 { "GPT" }
          Default { "Unknown" }
          }
        </GetScriptBlock>
      </ScriptProperty>
