### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by JakobL-MSFT** [MicrosoftDocs/windows-driver-docs#3751]
### Type of issue

Sample code doesn't work

### Feedback

The "SDK 10.0.22621.2428 (released October 24, 2023)" is now installed by the VS install steps.  

The current text is as such out of date. 

If user tries to install SDK as outlined beneath, then the user will end up in a dead end (try it!)

Jakob

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/download-the-wdk.md

### Author

@tedhudek

**Comment by tedhudek** [comment]
Updates are now live.  Thanks again!
