### ISSUE TITLE
Customer feedback - indicator behavior in privacy mode

### ISSUE THREAD

**Issue by kakerulife** [MicrosoftDocs/windows-driver-docs#3759]
### Type of issue

Other (describe below)

### Feedback

Hi Barrygloden:
We are not physical shutter, and into privacy mode by hotkey,
I want to know when I enter privacy mode the indicator is always on (show a picture of a camera with a slash through it).
The indicator behavior is must or reference , Can be accepted the indicator behavior?
Does it violate HLK specification?

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/stream/camera-privacy-controls?source=docs

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/stream/camera-privacy-controls.md

### Author

@barrygolden

**Comment by barrygolden** [comment]
@kakerulife, thanks for reaching out to the Windows Driver Developer Documentation team.  

You may have success posting your question about indicator behavior in privacy mode in the following forum, where other driver developers and Microsoft engineers can be found. 

[Microsoft Q&A: Windows Hardware development](https://docs.microsoft.com/answers/topics/windows-hardware.html)
