### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by vin-max** [MicrosoftDocs/windows-driver-docs#3761]
### Type of issue

Typo

### Feedback

"use a" has been repeated twice in the following sentence:
A program can use a use a range of virtual addresses to access a memory buffer larger than the available physical memory. 

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/virtual-address-spaces

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/virtual-address-spaces.md

### Author

@aviviano

**Comment by aviviano** [comment]
Thanks for letting us know about this issue, @vin-max! The fix will be live on the site soon.
