### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by Sienna346** [MicrosoftDocs/windows-driver-docs#3765]
### Type of issue

Typo

### Feedback

My computer is give a error message I want to know to how to fix it

### Page URL

https://learn.microsoft.com/en-ca/windows-hardware/drivers/debugger/bug-check-code-reference2

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-code-reference2.md

### Author

@DOMARS

**Comment by DOMARS** [comment]
@Sienna346  thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we are a small team and do not have the resources to provide technical support to individual driver developers.

For blue screen issues, I would review this document.
(https://support.microsoft.com/en-US/windows/resolving-blue-screen-errors-in-windows-60b01860-58f2-be66-7516-5c45a66ae3c6)

And you may have success posting your question in the following forum.
https://learn.microsoft.com/en-us/answers/questions/

I hope you are able to resolve your computer error message.
