### ISSUE TITLE
Customer feedback -  iinstalling my test driver into a real target machine， but not need VS？

### ISSUE THREAD

**Issue by S16201512** [MicrosoftDocs/windows-driver-docs#3766]
### Type of issue

Typo

### Feedback

Customer feedback - Where can I find the method， just installing my test driver into a real target machine， but not need VS？ 

### Page URL

https://learn.microsoft.com/zh-cn/windows-hardware/drivers/develop/preparing-a-computer-for-manual-driver-deployment

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/preparing-a-computer-for-manual-driver-deployment.md

### Author

@tedhudek

**Comment by tedhudek** [comment]
Hi @S16201512, as an alternative to downloading Visual Studio, the SDK, and the WDK, you can try downloading the EWDK using the instructions at https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-enterprise-wdk-ewdk.  Hope this helps!
