### ISSUE TITLE
Prototype for NtCopyFileChunk is not provided

### ISSUE THREAD

**Issue by zodiacon** [MicrosoftDocs/windows-driver-docs#3767]
### Type of issue

Missing information

### Feedback

Prototype for NtCopyFileChunk is not provided, but the parameters are described.

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/nf-ntifs-ntcopyfilechunk

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/nf-ntifs-ntcopyfilechunk.md

### Author

@lorihollasch

**Comment by lorihollasch** [comment]
Thanks for reporting this, @zodiacon! The prototype is now on the page.
