### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by vin-max** [MicrosoftDocs/windows-driver-docs#3768]
### Type of issue

Typo

### Feedback

NumberOfIndirectionTableEntriesPerNonDefaultVPort should be renamed as NumberOfIndirectionTableEntriesPerNonDefaultPFVPort in the following paragraph, as there is no NumberOfIndirectionTableEntriesPerNonDefaultVPort field in the NDIS_NIC_SWITCH_CAPABILITIES structure.

_Miniport drivers should be prepared to handle at least as many indirection table entry move actions as they advertise in the [NDIS_NIC_SWITCH_CAPABILITIES](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddndis/ns-ntddndis-_ndis_nic_switch_capabilities) structure. This is defined in the **NumberOfIndirectionTableEntriesPerNonDefaultVPort** or NumberOfIndirectionTableEntriesForDefaultVPort member of that structure, or 128 in Native RSS mode._

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-rss-set-indirection-table-entries

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/oid-gen-rss-set-indirection-table-entries.md

### Author

@aviviano

**Comment by aviviano** [comment]
Thanks for catching this and opening an issue, @vin-max. The fix will be live on the site soon.
