### ISSUE TITLE
Regarding the topic "Promoting a Driver's StartType at Boot Depending on Boot Scenario" for USB4

### ISSUE THREAD

**Issue by GeorgeGTA** [MicrosoftDocs/windows-driver-docs#3769]
### Type of issue

Other (describe below)

### Feedback

In this topic [Specifying Driver Load Order | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/specifying-driver-load-order#using-bootflags-to-promote-a-drivers-starttype-at-boot-depending-on-boot-scenario) , it mentions we can use BootFlags to Promote a Driver's StartType at Boot Depending on Boot Scenario. Based on this instruction I managed to boot Windows 11(23H2) installed on a SSD through USB3.2 port on my Legion 5i Pro laptop.  I am trying to boot the same SSD through USB4 port on the same laptop but get BSOD "Inaccessible Boot Device“. The SSD can be identified by BIOS and can be selected from the BIOS boot option list. So for USB4, what a hexadecimal value should be specified for USB4 accordingly? 
I have tried almost everything I can find around for this issue, but nothing helps so far. Meanwhile, as a regular external disk the SSD itself works well on USB4 port  with no issue.
### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/install/specifying-driver-load-order#using-bootflags-to-promote-a-drivers-starttype-at-boot-depending-on-boot-scenario

### Content source URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/install/specifying-driver-load-order#using-bootflags-to-promote-a-drivers-starttype-at-boot-depending-on-boot-scenario

### Author

George
```[tasklist]
### Tasks
```

**Comment by GeorgeGTA** [comment]
Attache two screenshots for the information about the drivers installed which were caught after booting on USB3.2.
![Screenshot 2024-01-16 102239](https://github.com/MicrosoftDocs/windows-driver-docs/assets/42284212/faa09f9d-4dc7-40f9-a26a-eebf62ab1753)
![Screenshot 2024-01-16 102541](https://github.com/MicrosoftDocs/windows-driver-docs/assets/42284212/edf45369-71d5-4329-8471-735e78e46cb1)

**Comment by tedhudek** [comment]
Hi @GeorgeGTA thanks for the question.  Performing a Windows OS installation using a Thunderbolt/USB4 storage device or a USB3 drive behind USB4 dock is supported and should work fine.
                                                                                               
However, booting Windows from a portable Thunderbolt storage device is not supported.

Hope this helps and best of luck!
