### ISSUE TITLE
Troubleshoot BSOD error

### ISSUE THREAD

**Issue by jhon88duff** [MicrosoftDocs/windows-driver-docs#3772]
### Type of issue

Sample code doesn't work

### Feedback

Troubleshoot BSOD error

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/debuggercmds/debugger-commands

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debuggercmds/debugger-commands.md

### Author

@DOMARS

**Comment by tedhudek** [comment]
Not seeing actionable feedback, please reopen if still needed..
