### ISSUE TITLE
PDB file of ntoskrnl.exe not found.

### ISSUE THREAD

**Issue by BlackINT3** [MicrosoftDocs/windows-driver-docs#3774]
### Type of issue

Typo

### Feedback

A couple of ntoskrnl.exe pdb not found.

SYMSRV:  HTTPGET: /download/symbols/ntkrnlmp.pdb/135BAC7861AC20FDAAD3E289FC1C9EAF1/ntkrnlmp.pdb
SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
as follow:
[ntoskrnl-1.zip](https://github.com/MicrosoftDocs/windows-driver-docs/files/13936020/ntoskrnl-1.zip)

another one:
SYMSRV: HTTPGET: /download/symbols/ntkrnlmp.pdb/8994979D169BB90B3D71598837151C2D1/ntkrnlmp.pdb
SYMSRV: HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
as follow:
[ntoskrnl.zip](https://github.com/MicrosoftDocs/windows-driver-docs/files/13935592/ntoskrnl.zip)

The problem similar to #3735

appreciate for help. @DOMARS

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/verifying-symbols

### Content source URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/verifying-symbols

### Author

DOMARS

**Comment by DOMARS** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don't have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. 

[Microsoft Support Community](https://answers.microsoft.com/)

[OSR's windbg List](https://community.osr.com/categories/windbg)

This feedback mechanism is for requests about the documentation. Best of luck with this issue.
