### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by Stoner4real4ewer** [MicrosoftDocs/windows-driver-docs#3777]
### Type of issue

Typo

### Feedback

i would like the driver pls

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-ndis-6-0

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/introduction-to-ndis-6-0.md

### Author

@aviviano

**Comment by tedhudek** [comment]
Sorry, not seeing any actionable feedback on the docs here, please reopen if still needed.
