### ISSUE TITLE
HP Driver Printer Error  

### ISSUE THREAD

**Issue by JohnDinolfo** [MicrosoftDocs/windows-driver-docs#3778]
### Type of issue

Other (describe below)

### Feedback

I receive this error when trying to download and install a Driver for my HP Printer:  HP - Printer - 20.79.1.6692.
Please advise.  Thanks.

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-support.md

### Author

@anaharris-ms

**Comment by tedhudek** [comment]
Hi @JohnDinolfo, thanks for writing.

This documentation is for commercial driver developers and people who are deploying drivers. For consumer driver issues, your best bet is to look at the Microsoft Help topics that are on support.microsoft.com.

Sorry that I can’t offer you something more specific than that.  Best of luck with your issue.
