### ISSUE TITLE
the instruction for publishing and submission  Extension INF package is not clrear 

### ISSUE THREAD

**Issue by Morgan6006** [MicrosoftDocs/windows-driver-docs#3779]
### Type of issue

Other (describe below)

### Feedback

the instruction for publishing and submission Extension INF package is not clear. how do i :Using the same HLK results from above, select Package > Replace Driver" in extension INF package? if i directly open the results in HLK studio, i cannot see any driver package. 
<img width="960" alt="Weixin Image_20240119151912" src="https://github.com/MicrosoftDocs/windows-driver-docs/assets/157099000/450eddb4-045a-469b-9f7f-c99a83998752">

and replace driver option is not available. in our understanding, the replace driver option can only be available in DUA process.
![image](https://github.com/MicrosoftDocs/windows-driver-docs/assets/157099000/5a7b86ea-46aa-4599-83b7-81525a5da39c)
![Uploading Weixin Image_20240119151905.jpg…]()

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/submit-dashboard-extension-inf-files

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/submit-dashboard-extension-inf-files.md

### Author

@anaharris-ms

**Comment by anaharris-ms** [comment]
Hi @Morgan6006 ,

Thanks for reaching out. The best way to begin a resolution to your problem is to follow the steps in [Create a New Support Request](https://techcommunity.microsoft.com/t5/hardware-dev-center/update-create-a-new-support-request/ba-p/3921311).

Have a great day!
