### ISSUE TITLE
mf.sys does not support message based interrupts

### ISSUE THREAD

**Issue by jdezoeten** [MicrosoftDocs/windows-driver-docs#3781]
### Type of issue

Missing information

### Feedback

Passing Line Based interrupts to child devices works perfectly fine. However, when enabling MSI the mf.sys driver BSODs. I am using the following setting to enable MSI for my device:
```
HKR,Interrupt Management\MessageSignaledInterruptProperties,MSISupported,0x00010001,1
HKR,Interrupt Management\MessageSignaledInterruptProperties,MessageNumberLimit,0x00010001,8
```

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/multifunction/using-the-system-supplied-multifunction-bus-driver

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/multifunction/using-the-system-supplied-multifunction-bus-driver.md

### Author

@barrygolden

**Comment by barrygolden** [comment]
@jdezoeten, thanks for filing an issue with the Windows Driver Developer Documentation team.

I checked with a developer on the Kernel team here at Microsoft and he replied that "MF.sys is a legacy component in maintenance mode, provided inbox for compatibly purposes only. It was written before PCI message-signaled interrupts were invented, and it was never updated to support them."

So message-signaled interrupts (MSIs) are unsupported in MF.sys.

Also, please note that GitHub issues will be discontinued on this repo on March 20, 2024. See issue #3808 for more information.
