### ISSUE TITLE
Audio driver for Behringer XR-18 not working correctly

### ISSUE THREAD

**Issue by GlenWS** [MicrosoftDocs/windows-driver-docs#3782]
### Type of issue

Typo

### Feedback

I have an audio issue with my XR-18.  After no sound, I used the windows auto tech support and it/they updated the driver.  I then had audio back, but I only have 2 channels of USB audio.  I see check boxes to select other inputs and outputs, but am not allowed to check them.  When I try to update the drivers it says they are up to date. None of my DAW's work correctly now.
Windows10, x64, ver 19045.3930 / 16gb / 2.4ghz / i3 7100U / 2 core / 

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-support.md

### Author

@anaharris-ms

**Comment by tedhudek** [comment]
Hi @GlenWS,

This documentation is for commercial driver devs and people who are deploying drivers. For consumer driver issues, your best bet is to look at the Microsoft Help topics that are on support.microsoft.com.

Sorry that I can’t offer you something more specific than that.  Best of luck with your issue.
