### ISSUE TITLE
Customer feedback - Outdated Install Instructions for running DevFund tests via command line

### ISSUE THREAD

**Issue by wmmc88** [MicrosoftDocs/windows-driver-docs#3785]
### Type of issue

Outdated article

### Feedback

Step 3 references an msi that does not exist  in Ni WDK. I'm not sure at what point this changed, but I think these docs probably need to be updated to use the instructions provided at https://learn.microsoft.com/en-us/windows-hardware/drivers/wdtf/wdtf-runtime-library#manually-installing-wdtf-on-a-test-computer-alternative-method

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/run-devfund-tests-via-the-command-line

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/run-devfund-tests-via-the-command-line.md

### Author

@DOMARS

**Comment by DOMARS** [comment]
@wmmc88 - It is possible that the WDTF MSI was not present in version of the kits. I just installed both the regular released kit and the EWDK (Windows 11, version 22H2 EWDK (released October 24, 2023) with Visual Studio Buildtools 17.1.5) and I see ARM and X64 msi installers. So you might check that you are using the latest kit. Thanks for the passing on what you are seeing with the WDTF installers.
