### ISSUE TITLE
Customer feedback - pc suddenly blue issu show and auto restart

### ISSUE THREAD

**Issue by arafatomiteepti** [MicrosoftDocs/windows-driver-docs#3787]
### Type of issue

Typo

### Feedback

suddenly restart my pc this problem is blue issu i think

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/getting-started-with-windows-debugging

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/getting-started-with-windows-debugging.md

### Author

@DOMARS

**Comment by tedhudek** [comment]
Not seeing actionable feedback about the doc page here.  Please reopen if still needed.  Thanks!
