### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by KoYoGyi** [MicrosoftDocs/windows-driver-docs#3788]
### Type of issue

Typo

### Feedback

HANDLE procToken;
LUID luid;
TOKEN_PRIVILEGES tp;

OpenProcessToken(GetCurrentProcess(), TOKEN_ADJUST_PRIVILEGES | TOKEN_QUERY, &procToken);

LookupPrivilegeValue(NULL, SE_LOAD_DRIVER_NAME, &luid);

Tp.PrivilegeCount = 1;
Tp.privileges[0].Luid = luid;
Tp.Privileges[0].Attributes = SE_PRIVILEGE_ENABLED;

AdjustTokenPrivileges(procToken, FALSE, &tp, sizeof(TOKEN_PRIVILEGES), (PTOKEN_PRIVILEGES) NULL, (PDWORD)NULL)

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/install/driver-packages

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/driver-packages.md

### Author

@tedhudek

**Comment by tedhudek** [comment]
No actionable feedback, please reopen with details if still needed.
