### ISSUE TITLE
Troubleshooting procedures

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#379]
A section providing troubleshooting procedure for this bugcheck is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d21ffb80-ac65-c23f-2820-e346aa113503
* Version Independent ID: 1243e734-9c5d-10f5-cf94-253acd56c577
* Content: [Bug Check 0xAB SESSION_HAS_VALID_POOL_ON_EXIT](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xab--session-has-valid-pool-on-exit)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0xab--session-has-valid-pool-on-exit.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0xab--session-has-valid-pool-on-exit.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ LuigiBruno – Thanks for the input that we should add additional information on this Bug Check -0xAB as well as the input on Bug Check 0xEC. We will take a look and see if we can provide additional information on this stop code that is broadly applicable. In general, though, if a specific driver repeatedly causes a stop code, the developer of that driver must update their code. In this case, a dev will have to debug the driver source code to determine why there was an active pool on exit.

Again, thanks for the input, and best of luck with your issue.
