### ISSUE TITLE
Customer feedback - On Firmware Intallation Error

### ISSUE THREAD

**Issue by ColloNbn** [MicrosoftDocs/windows-driver-docs#3792]
### Type of issue

Typo

### Feedback

NA

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/hardware-submission-support.md

### Author

@anaharris-ms

**Comment by tedhudek** [comment]
No actionable feedback, please reopen if still needed
