### ISSUE TITLE
Step 7 information not accurate 

### ISSUE THREAD

**Issue by weijie8222** [MicrosoftDocs/windows-driver-docs#3794]
### Type of issue

Typo

### Feedback

In the Step 7, the first sentence says "In the Solution Explorer window, select and hold (or right-select) the KmdfHelloWorld project and choose Configuration Manager. ". 

This is not correct. One needs select and hold the "solution" rather than the "project": Only the solution has the option "Configuration Manager", the project doesn't. 

As this doc is targeting the programmer that is looking for the entry level information, I think it should be as accurate as possible: the reason is simple. Experienced programmer doesn't need to read it, and if they read it, they know where to get it, (for example, they may do that via toolbar on the Visual Studio IDE), but it would be really frustrating for the beginners because they will get lost totally in the Step 7.  

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-very-small-kmdf--driver.md

### Author

@aviviano

**Comment by aviviano** [comment]
Thanks very much @weijie8222 for letting us know about this documentation bug! The fix will be live on the site shortly.
