### ISSUE TITLE
Can DigiCert "Document Signing" certificate be used for driver signing?

### ISSUE THREAD

**Issue by forderud** [MicrosoftDocs/windows-driver-docs#3806]
### Type of issue

Other (describe below)

### Feedback

Seems to be related to #3668.

The DigiCert link on [Driver code signing requirements](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-reqs) points to a purchasing form for "Document Signing" certificates. DigiCert also sells "Code Signing" certificates at a higher price. I am therefore wondering if the "Document Signing" link is deliberate, since they're cheaper, or if the link should be updated?

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-reqs

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/code-signing-reqs.md?plain=1

### Author

anaharris-ms

**Comment by anaharris-ms** [comment]
@forderud

Thank you - I've updated the link to the correct page for code signing.
