### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jianghui3132749** [MicrosoftDocs/windows-driver-docs#3814]
### Type of issue

Typo

### Feedback

i want to regiest Hardware Developer, i click "Go to the Hardware Developer Program registration page", i can not find prerequisites page. please help me. thanks.

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-program-register

### Content source URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-program-register

### Author

 jianghui3132749

**Comment by anaharris-ms** [comment]
Hi @jianghui3132749, thank you so much bringing this to our attention. I've fixed the link, and things should be working now. Let me know if you need anything else.

#please-close

**Comment by jianghui3132749** [comment]
hi, i want to register windows Hardware Developer, which one is right?  "windows and xbox" or "bethesda partner program"?

![微软](https://github.com/MicrosoftDocs/windows-driver-docs/assets/39110030/7398dad5-7e8a-4dca-8430-0552ee8d8390)
https://partner.microsoft.com/en-us/dashboard/account/exp/enrollment/programselector/AppDev
https://learn.microsoft.com/zh-cn/windows-hardware/drivers/dashboard/hardware-program-register
