### ISSUE TITLE
Clicking on Hardware Developer Program Registration link just loops.

### ISSUE THREAD

**Issue by jjwwiodyne** [MicrosoftDocs/windows-driver-docs#3815]
### Type of issue

Other (describe below)

### Feedback

On this page:
https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-program-register

Clicking on the link (https://go.microsoft.com/fwlink/?LinkID=828002) for the "Hardware Developer Program registration page" just loops back to:
https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/

I'm logging in as an Office 365 Global Admin that is in Entra.

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-program-register

### Content source URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-program-register

### Author

anaharris-ms

**Comment by jianghui3132749** [comment]
you can try it again. i register windows Hardware Developer success.

**Comment by jianghui3132749** [comment]
but i have another question.
https://github.ink/MicrosoftDocs/windows-driver-docs/issues/3816#issue-2168121628

**Comment by jjwwiodyne** [comment]
Actually it redirects to the "Windows and Xbox program" now instead of Hardware.

**Comment by jianghui3132749** [comment]
yes，there is no option for hardware developer. 
hope microsoft technician help us。

**Comment by anaharris-ms** [comment]
I am closing this issue, as it is a duplicate of https://github.com/MicrosoftDocs/windows-driver-docs/issues/3812.

I will get back to you on this later in the day.
