### ISSUE TITLE
i want to register windows Hardware Developer,

### ISSUE THREAD

**Issue by jianghui3132749** [MicrosoftDocs/windows-driver-docs#3816]
### Type of issue

Typo

### Feedback

hi, i want to register windows Hardware Developer, which one is right? "windows and xbox" or "bethesda partner program"?
![微软](https://github.com/MicrosoftDocs/windows-driver-docs/assets/39110030/5d6ef341-8ce8-4fd9-9b17-a8165095fe17)

### Page URL

https://learn.microsoft.com/zh-cn/windows-hardware/drivers/dashboard/hardware-program-register

### Content source URL

https://partner.microsoft.com/en-us/dashboard/account/exp/enrollment/programselector/AppDev

### Author

 jianghui3132749

**Comment by anaharris-ms** [comment]
This is a duplicate issue. Please track https://github.com/MicrosoftDocs/windows-driver-docs/issues/3812.
