### ISSUE TITLE
Feedback hardware-program-register URL is wrong

### ISSUE THREAD

**Issue by GankLi** [MicrosoftDocs/windows-driver-docs#3819]
### Type of issue

Other (describe below)

### Feedback

<img width="876" alt="image" src="https://github.com/MicrosoftDocs/windows-driver-docs/assets/11990976/9d594727-8649-46f7-997e-b2c220268494">
1. Go to the [Hardware Developer Program registration](./index.yml).

### Page URL

https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-program-register

### Content source URL

https://github.com/MicrosoftDocs/windows-driver-docs/blob/b5a3e859933fe3618da6815807201fd423fd91ea/windows-driver-docs-pr/dashboard/hardware-program-register.md?plain=1

### Author

gank520@gmail.com

**Comment by anaharris-ms** [comment]
Hi @GankLi,

Please contact technical support for this issue. https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/hardware-submission-support#technical-support-issues
