### ISSUE TITLE
Related topics links are bad

### ISSUE THREAD

**Issue by peterwie** [MicrosoftDocs/windows-driver-docs#390]
The Kernel-Mode Driver Framework link goes to a general WDK page, not to the KMDF material

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dcfd3e9-3d43-1140-cc8c-fe5f9e915a9d
* Version Independent ID: 4f665db9-d2bf-3720-f7a0-4176f796438a
* Content: [Choosing a driver model](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/choosing-a-driver-model)
* Content Source: [windows-driver-docs-pr/gettingstarted/choosing-a-driver-model.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/choosing-a-driver-model.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for this, Peter. I've opened Bug 16565699, to track this work item.
