### ISSUE TITLE
Related topics link is invalid

### ISSUE THREAD

**Issue by peterwie** [MicrosoftDocs/windows-driver-docs#391]
The Kernel-Mode Driver Framework link on this page goes to the generic hardware page.  This is the second bad link I've found today.  My guess is that all of the KMDF links in this document set are stale or incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f307c67c-8d56-845a-9f0a-ba43af6004bf
* Version Independent ID: e4162ef0-9382-9d6a-4551-3d231d5c7f53
* Content: [KMDF as a generic driver pair model](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/kmdf-as-a-generic-pair-model)
* Content Source: [windows-driver-docs-pr/gettingstarted/kmdf-as-a-generic-pair-model.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/kmdf-as-a-generic-pair-model.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for this, Peter. I've opened Bug 16565699, to track this work item.
