### ISSUE TITLE
Probable bug in code snippet in this log post

### ISSUE THREAD

**Issue by aruntom55** [MicrosoftDocs/windows-driver-docs#395]
{
    ULONG index = 0;
    seq.List.Transfers[index] = SPB_TRANSFER_LIST_ENTRY_INIT_SIMPLE(
        SpbTransferDirectionToDevice,
        0,
        pWriteBuffer,
        writeBufferLength);

    seq.List.Transfers[index + 1] = SPB_TRANSFER_LIST_ENTRY_INIT_SIMPLE(
        SpbTransferDirectionFromDevice,
        0,
        pReadBuffer,
        readBufferLength);
}

the seq.List would be an point to be a list of two seq.list elements.

The seq.List.Transfers element in every seq.list is of size 1 and hence accessing 
seq.List.Transfers[1] is not correct. 

Looks like a bug. Please correct same

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb5615a-0e56-d3e4-6811-da881a97c5d7
* Version Independent ID: 8dae0647-a475-5d98-dab3-06e1d866ac4e
* Content: [Full-Duplex I/O Requests](https://docs.microsoft.com/en-us/windows-hardware/drivers/spb/full-duplex-i-o-requests#feedback)
* Content Source: [windows-driver-docs-pr/spb/full-duplex-i-o-requests.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/spb/full-duplex-i-o-requests.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello aruntom55,

As per the definition of SPB_TRANSFER_LIST_AND_ENTRIES in Spb.h, there only one List but there is enough space for 2 Transfers.

Thanks,

PageWriter
