### ISSUE TITLE
2018 - but docs talk about Win98?

### ISSUE THREAD

**Issue by Marc-Albrecht** [MicrosoftDocs/windows-driver-docs#396]
I am a bit puzzled: I was sent here through a "recent" installation of the windows driver development kit. Wanting to "learn more", as the installation tool put it, I clicked on the most probable links - and land on a page that tells me about what to use when developing for Windows 98 or XP. No word about what to use and where to go from here for Windows 10 ... 
Maybe this page - like most other MS dev pages I visited over the last 10 days - needs some overhaul?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59203767-df3c-d7d3-81aa-620b8d20fb0d
* Version Independent ID: 2eefae23-0d19-3df3-c91c-49f8661f9308
* Content: [Imaging device driver design guide](https://docs.microsoft.com/en-us/windows-hardware/drivers/image/)
* Content Source: [windows-driver-docs-pr/image/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/image/index.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
@Marc-Albrecht, thanks for reaching out to the Windows driver developer documentation team and filing an issue regarding legacy Windows OS versions regarding WIA and STI . We've filed an internal work item (18381906) to add more information about the current state of STI/TWAIN and WIA DDIs in a future documentation update.

If you have specific WIA or STI/TWAIN scenarios that you have concerns with that you'd like discuss with the image and scan driver developer community, we recommend that you visit the following forums, where other driver developers and Microsoft engineers can be found and can benefit from your knowledge and interest in this area. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)

Feel free to submit a pull request on the image driver docs to help us benefit from your knowledge and experience with this area of the WDK.
