### ISSUE TITLE
Page needs more details on "Download the provided signable file"

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/windows-driver-docs#402]
Step #3 in the "Registration steps" section says: "Download the provided signable file", but there is no link to do that download, and there is no prose saying where to go to download the "signable file".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2daf70ed-7391-5783-583b-fcd99f1c222a
* Version Independent ID: 679bd45d-d0fd-a192-4d26-0121594fa86a
* Content: [Register for the Hardware Program](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/register-for-the-hardware-program)
* Content Source: [windows-driver-docs-pr/dashboard/register-for-the-hardware-program.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/register-for-the-hardware-program.md)
* Service: **unspecified**
* GitHub Login: @aahill
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @fpl9000, apologies on the delay with this. A signable file is provided to you in the "sign and upload" portion of the registration process. I've updated the wording to clarify this - it should be visible within 24 hours. Thanks for bringing this to our attention!
