### ISSUE TITLE
Mention references wrt Kernel Mode Display-Only Driver (KMDOD)

### ISSUE THREAD

**Issue by vnvsrikanth** [MicrosoftDocs/windows-driver-docs#403]
Please mention references (structures and functions) wrt Kernel Mode Display-Only Driver (KMDOD).
Eg:
DxgkInitializeDisplayOnlyDriver  is the function to be called when it is KMDOD, instead of DxgkInitialize.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0bd42b-61a6-4448-5c48-fade01bf878c
* Version Independent ID: 6b242ed2-799d-8500-6039-ac8c294103e1
* Content: [DriverEntry of Display Miniport Driver function](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/driverentry-of-display-miniport-driver)
* Content Source: [windows-driver-docs-pr/display/driverentry-of-display-miniport-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/driverentry-of-display-miniport-driver.md)
* Service: **unspecified**
* GitHub Login: @mimisasouvanh
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
Thank you @vnvsrikanth for bringing this to our attention. I have update the topic to include information about kernel mode display-only (KMOD) DDIs: https://docs.microsoft.com/en-us/windows-hardware/drivers/display/driverentry-of-display-miniport-driver 
I am closing this issue. Feel free to open it back up or contribute if needed.
