### ISSUE TITLE
Getting rid of a linking error

### ISSUE THREAD

**Issue by lihas** [MicrosoftDocs/windows-driver-docs#410]
Also include initguid.h.
#include <initguid.h>.
Otherwise I was getting "unresolved external symbol _GUID_DEVINTERFACE_USB_DEVICE"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc07324f-bf4f-8857-2ea3-3539a586fb27
* Version Independent ID: 63179fd5-2bd5-ef2c-b180-419340116d29
* Content: [GUID_DEVINTERFACE_USB_DEVICE](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-devinterface-usb-device)
* Content Source: [windows-driver-docs-pr/install/guid-devinterface-usb-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/guid-devinterface-usb-device.md)
* Service: **unspecified**
* GitHub Login: @tedhudek

**Comment by tedhudek** [comment]
Thanks for the feedback, @lihas, are you suggesting that we add initguid.h to the Requirements section of this page?

**Comment by PageWriter-MSFT** [comment]
Thanks for pointing that out. I have added the header to the requirements section.

**Comment by gaborgsomogyi** [comment]
Oh man, saved me a lot of headaches :)
