### ISSUE TITLE
Resolution steps

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#411]
Missing suggested troubleshooting/resolution steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6700412d-d8a4-205a-84e2-363966271ab3
* Version Independent ID: 8674faac-f00d-f3c5-214a-0275b1b2ac88
* Content: [Bug Check 0xEC SESSION_HAS_VALID_SPECIAL_POOL_ON_EXIT](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xec--session-has-valid-special-pool-on-exit)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0xec--session-has-valid-special-pool-on-exit.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0xec--session-has-valid-special-pool-on-exit.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@ LuigiBruno – Thanks for the input that we should add additional information on Bug Check 0xEC. We will take a look and see if we can provide additional information on this stop code that is broadly applicable. In general, though, if a specific driver repeatedly causes a stop code, the developer of that driver must update their code. In this case, a dev will have to debug the driver to determine where that driver was holding memory when the session unload occurred.

Again, thanks for the input, and best of luck with your issue.
