### ISSUE TITLE
Device Configuration failed

### ISSUE THREAD

**Issue by liaowuping** [MicrosoftDocs/windows-driver-docs#414]
Installing necessary components...
Copying required files
    Task "Copying required files" completed successfully
Configuring WDK Remote User Account
    Task "Configuring WDK Remote User Account" completed successfully
Installing .NET Framework (possible reboot)
    Task "Installing .NET Framework (possible reboot)" completed successfully
Installing VC Redist (x64)
    Task "Installing VC Redist (x64)" completed successfully
Installing test automation (x86)
    Task "Installing test automation (x86)" completed successfully
Installing test automation (x64)
    Task "Installing test automation (x64)" completed successfully
Installing debuggers (x86)
    Task "Installing debuggers (x86)" completed successfully
Installing debuggers (x64)
    Task "Installing debuggers (x64)" completed successfully
Installing driver test framework
    Task "Installing driver test framework" completed successfully
Registering logging components
    Task "Registering logging components" completed successfully
Configuring TAEF test service to start automatically
    Task "Configuring TAEF test service to start automatically" completed successfully
Configuring kernel debugger settings (possible reboot)
    Task "Configuring kernel debugger settings (possible reboot)" completed successfully
Configuring computer settings (possible reboot)
    Task "Configuring computer settings (possible reboot)" completed successfully
Creating system restore point
    ERROR: Task "Creating system restore point" failed to complete successfully. Look at the logs in the driver test group explorer for more details on the failure.
Computer configuration log file://C:/Users/Silence/AppData/Roaming/Microsoft/WDKTestInfrastructure/ProvisioningLogs/Driver%20Test%20Computer%20Configuration%2020180404211822384.log
Failed installing components

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75819dbc-e20a-29f0-af02-5afc4628fd95
* Version Independent ID: fca932fe-08ba-a01c-30a7-2288342f6014
* Content: [Setting Up Kernel-Mode Debugging over a Network Cable in Visual Studio](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-in-visual-studio)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-in-visual-studio.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-in-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@liaowuping - not sure if this is your issue, but all of these Visual Studio deployment options are not supported after version  Windows 10, version 1507. This is mentioned in https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-kernel-mode-debugging-in-visual-studio. I will add an "Important" note to each of the sub topics as well.

**Comment by DOMARS** [comment]
@liaowuping - Thanks for your input. I added and "Important" note to each of the kernel debugging topics as well. "This feature is not available in Windows 10, version 1507 and later versions of the WDK."

**Comment by vikaspachisia** [comment]
This is the exact issue that I am facing "now".
How do I get the password for the WDK Remote User Account?

**Comment by Coldberg** [comment]
> @liaowuping - not sure if this is your issue, but all of these Visual Studio deployment options are not supported after version Windows 10, version 1507. This is mentioned in https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-kernel-mode-debugging-in-visual-studio. I will add an "Important" note to each of the sub topics as well.

Why is that ?! Why is Microsoft making an already hard job even harder?!
