### ISSUE TITLE
link is broken.

### ISSUE THREAD

**Issue by evgeniylevakhin** [MicrosoftDocs/windows-driver-docs#417]
link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8707ae7-74c9-9bd5-b317-e8b06d9836bb
* Version Independent ID: fd8d7bf6-89fa-9c33-5ca4-613141e0513b
* Content: [UserDump](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/userdump)
* Content Source: [windows-driver-docs-pr/debugger/userdump.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/userdump.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Thanks for finding this, @evgeniylevakhin . I've updated the link to the current support site (https://support.microsoft.com/en-us/help/241215/how-to-use-the-userdump-exe-tool-to-create-a-dump-file ) and added an extra reference to the .dump command, too. Changes should be live later today.
@DOMARS, FYI.
