### ISSUE TITLE
Please provide information on where to get these IDs.

### ISSUE THREAD

**Issue by pciids** [MicrosoftDocs/windows-driver-docs#422]
What is missing from this page are a few links to pages that tell you what IDs there are and what the IDs are for the devices on your development computer for example.
For the first, I would suggest a link to https://pci-ids.ucw.cz or perhaps its subpages "PCI devices" for the vendor and hardware IDs and "PCI device classes" for the base classes, subclasses and interfaces.
Regarding the second point, on Linux you can enter the command "sudo lspci -vvvnn" in a terminal to show the available hardware with its IDs. I'm not sure if an equivalent Windows command exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7bdd46-af6b-f97f-b9c7-36bdca5b7982
* Version Independent ID: 34d30100-55b1-7869-8c88-8da826825621
* Content: [Identifiers for PCI Devices](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/identifiers-for-pci-devices)
* Content Source: [windows-driver-docs-pr/install/identifiers-for-pci-devices.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/identifiers-for-pci-devices.md)
* Service: **unspecified**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @pciids I've added this info to the page.  Should be live in 10 minutes or so
