### ISSUE TITLE
wddm allocation questions

### ISSUE THREAD

**Issue by TerranWu** [MicrosoftDocs/windows-driver-docs#423]
In user mode driver before the pfnRenderCb action, i fill the command buffer and  patch-location list accordingly by setting the D3DDDI_ALLOCATIONLIST and D3DDDI_PATCHLOCATIONLIST. But in those data structures I don't see(set) any information about how large the allocation is? Then how the video memory manager knows to allocate the memory properly and send the patch information to kernel mode driver to patch the DMA buffer.

for example, the command format in the command buffer looks like bellow:
struct hw_command{
UINT gpu_command;
UINT addr0;
UINT addr1;
}
I use two D3DDDI_PATCHLOCATIONLIST for the command above, one for addr0 and another for addr1, and set the PatchOffset in the D3DDDI_PATCHLOCATIONLIST properly. 
I also assigned one D3DDDI_ALLOCATIONLIST for the two D3DDDI_PATCHLOCATIONLIST, but I don't see anywhere to set the size for addr0 and addr1 in D3DDDI_PATCHLOCATIONLIST, and how the video memory manager to allocate memory form the allocation referenced by D3DDDI_ALLOCATIONLIST to make sure that those memory range for the two addresses don't overlap. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b37210a7-e3ae-3d37-f713-075336e2be24
* Version Independent ID: 6afd5a1b-b80f-37c4-d3b7-5a3d5df309d2
* Content: [Submitting a Command Buffer](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/submitting-a-command-buffer)
* Content Source: [windows-driver-docs-pr/display/submitting-a-command-buffer.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/submitting-a-command-buffer.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
Hi @TerranWu 
Thank you for your question. The remarks section in PFND3DDDI_RENDERCB(https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/d3dumddi/nc-d3dumddi-pfnd3dddi_rendercb#remarks) talks about size allocation. I hope this helps.
Mimi
