### ISSUE TITLE
Where is gflags output written to?

### ISSUE THREAD

**Issue by sketch34** [MicrosoftDocs/windows-driver-docs#428]
I can't seem to find this information in any of the documentation? There appears to be no mention of where the output is located and what the output is from gflags.

A simple end-to-end round trip example / tutorial would do a lot to clarify things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a2a343-17bf-477c-4ec3-c1b3baf7528d
* Version Independent ID: 89340c44-adea-9d15-d60a-b2864d1dbc1b
* Content: [GFlags Commands](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags-commands)
* Content Source: [windows-driver-docs-pr/debugger/gflags-commands.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/gflags-commands.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@sketch34 – Thanks for the input on providing additional information on how to view gflag output. For an example of viewing gflag output using a debugger, see https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/example-12---using-page-heap-verification-to-find-a-bug
For a general tutorial on using the debugger see: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-
Thanks again for your input.
