### ISSUE TITLE
Driver promotion properties of New Shipping Label page.

### ISSUE THREAD

**Issue by armstrong-charles** [MicrosoftDocs/windows-driver-docs#429]
As in the documentation, there are three driver promotion options available. 
It is not an issue in the documentation, but i would like to get some clarification about this option - "Automatically deliver and install this driver on all applicable system" to promote your driver to Critical.

If i select this option for my driver update publishing, will it reflect in the 'Classification"  column of the Windows Update Catalog such as : Critical Update.
I have seen various drivers that are automatically downloaded and installed, but Classification column of the Windows Update Catalog does not appear to say "Critical Update".
Your insights will be appreciated. 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 531ef6ee-7a29-e6d0-56d6-e08a923b0aa4
* Version Independent ID: d00f4b65-2ae6-643f-d67a-c04f916a7058
* Content: [Publish a driver to Windows Update](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/publish-a-driver-to-windows-update)
* Content Source: [windows-driver-docs-pr/dashboard/publish-a-driver-to-windows-update.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/publish-a-driver-to-windows-update.md)
* Service: **unspecified**
* GitHub Login: @aahill
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @armstrong-charles, I looked into this and the driver metadata that determines if a driver is optional or critical isn't exposed in the Windows Update Catalog. Additionally, a driver's classification doesn't determine whether it's optional or critical - the classification is always "Drivers". The "Critical updates" classification is only relevant in regards to software updates. Hopefully that helps?

**Comment by armstrong-charles** [comment]
Hi @aahill thanks, it really helps. This is my understanding that 'Critical Updates' classification is only relevant in regards to software updates and classification of Driver update is always "Drivers" that comes from the metadata of the package, however, driver promotion option promotes the driver delivery, allowing how driver can be delivered to Windows Clients.

**Comment by aahill** [comment]
Glad to help, thanks for reaching out!
