### ISSUE TITLE
the second project - driver installation package is NOT created

### ISSUE THREAD

**Issue by serup** [MicrosoftDocs/windows-driver-docs#431]
driver installation package is NOT created by WDF - KMDF, only the KMDF driver part, perhaps you could add how this project is manually added

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: f09a03ab-3e37-3bcb-9727-b300ae82c15e
* Version Independent ID: b7142a24-32b2-166d-3427-b87a8c69c0e3
* Content: [Developing, Testing, and Deploying Drivers](https://docs.microsoft.com/da-dk/windows-hardware/drivers/develop/index)
* Content Source: [windows-driver-docs-pr/develop/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/index.md)
* Service: **unspecified**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Sorry for the delay @serup but you can try this page instead: https://docs.microsoft.com/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver
