### ISSUE TITLE
TraceView.exe location was changed in WDK build 16299.15.

### ISSUE THREAD

**Issue by wayyt** [MicrosoftDocs/windows-driver-docs#434]
By default, TraceView.exe is located in the tools\<Platform> subdirectory of the Windows Driver Kit (WDK), where <Platform> is either i386, amd64, arm or arm64. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7290b3e5-b335-114b-aacd-831b512c6960
* Version Independent ID: c2f55351-2ee5-7cdc-db9b-5330ee8b6791
* Content: [Preparing to Use TraceView](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/preparing-to-use-traceview)
* Content Source: [windows-driver-docs-pr/devtest/preparing-to-use-traceview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/preparing-to-use-traceview.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @wayyt

Fix is in and should be live shortly. Appreciate your vigilance!
