### ISSUE TITLE
CAT files appear in the diagram for multi-driver submission

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/windows-driver-docs#436]
The diagram for a multiple-driver submission shows CAT files, but the instructions on this page explicitly state "Catalog .CAT files are not required. Microsoft regenerates catalog files and replaces any catalog files that were submitted." It would be more accurate to leave out the CAT files from the diagram.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 175b6b9d-9fbf-08e3-74bc-f5158baed555
* Version Independent ID: 98a9d5e5-9aae-28bd-0cf8-07f49a0c7514
* Content: [Attestation signing a kernel driver for public release](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/attestation-signing-a-kernel-driver-for-public-release)
* Content Source: [windows-driver-docs-pr/dashboard/attestation-signing-a-kernel-driver-for-public-release.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/attestation-signing-a-kernel-driver-for-public-release.md)
* Service: **unspecified**
* GitHub Login: @aahill
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Thanks for the feedback @fpl9000, I think that's a good change.  I've gone ahead and removed the CAT files from the diagram - should be visible in a day or so. 

Thanks!
