### ISSUE TITLE
A typo and a broken link

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/windows-driver-docs#444]
The typo: The sentence that begins "when Secure Boot is on, ..." should start with a capital letter ("When ...").

The broken link: In the "See Also" section, the link "Digital Signatures for Kernel Modules on Windows" points to a non-existent page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb19d33-8f4c-f379-b645-938a746c5615
* Version Independent ID: 8efb9fb4-1e9a-1a8a-994b-450495449e15
* Content: [Driver Signing Policy](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/kernel-mode-code-signing-policy--windows-vista-and-later-)
* Content Source: [windows-driver-docs-pr/install/kernel-mode-code-signing-policy--windows-vista-and-later-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/kernel-mode-code-signing-policy--windows-vista-and-later-.md)
* Service: **unspecified**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @fpl9000 I've fixed both these issues.  Live site should update within 10 minutes.
