### ISSUE TITLE
Action Interface link is broken

### ISSUE THREAD

**Issue by shaboinkin** [MicrosoftDocs/windows-driver-docs#447]
Action Interfaces is supposed to link to https://msdn.microsoft.com/library/windows/hardware/ff538355. Instead, it redirects to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/index

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19da97b7-0f3f-48ca-3822-c1b710328e1c
* Version Independent ID: c643446d-930e-9ff3-b56e-53cfe5121ccc
* Content: [Controlling Targets](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdtf/controlling-targets)
* Content Source: [windows-driver-docs-pr/wdtf/controlling-targets.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdtf/controlling-targets.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Created the page, added it to the TOC, and fixed the link on this page. Thanks for catching this, @shaboinkin!!
