### ISSUE TITLE
Place file is obsolete and should not be used.

### ISSUE THREAD

**Issue by sahikon** [MicrosoftDocs/windows-driver-docs#453]
This article states "TMF files are created automatically during the build process when the trace provider is specified in a place file."
Article about "place files" has deprecation warning: "Place files are now obsolete and should not be used." (see https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/place-file-syntax).

Need better clarity on place file usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 186def44-6dc1-37d4-55a8-df4e3008ab5f
* Version Independent ID: 63b036c2-f96d-64d2-4675-fe12135d485d
* Content: [Trace Message Format File](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/trace-message-format-file)
* Content Source: [windows-driver-docs-pr/devtest/trace-message-format-file.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/trace-message-format-file.md)
* Service: **unspecified**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Changed the text to read: "You can create a TMF file by using Tracefmt and including the -i parameter, which directs Tracefmt to create a TMF file for Tracedrv. For more info, see Example 9: Creating a TMF file.
