### ISSUE TITLE
What does "Armed for wake" mean?

### ISSUE THREAD

**Issue by efalk** [MicrosoftDocs/windows-driver-docs#461]
There are a number of undefined terms on this page, but "Armed for wake" really had me confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaf34fc4-46dc-9997-3a9b-8240df843fc0
* Version Independent ID: d0e1c003-1133-d811-5c71-47ce6a3c68f7
* Content: [USB Selective Suspend](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-selective-suspend)
* Content Source: [windows-driver-docs-pr/usbcon/usb-selective-suspend.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-selective-suspend.md)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello Edward,

USB devices can respond to external wake signals while in Suspend state if the hardware supports the feature.  Here are some links that might be helpful:

[Remote Wakeup of USB Devices](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/remote-wakeup-of-usb-devices)
[Overview of Wait/Wake Operation](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/overview-of-wait-wake-operation)

I have added those links to the page. Should be updated soon.

Let us know if you have other questions. 

PageWriter
