### ISSUE TITLE
Source code typo

### ISSUE THREAD

**Issue by SerusDev** [MicrosoftDocs/windows-driver-docs#463]
// callout allocated data, contains original destination information
result = WSAIoctl(clientSock,
                  SIO_QUERY_WFP_CONNECTION_REDIRECT_CONTEXT,
                  redirectRecords, …);

"redirectRecords" should be replaced with "redirectContext".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a3e4808-0c6b-8848-6270-8f5e8b810223
* Version Independent ID: d38592f5-3ca4-3d2a-20fd-c8cfd28b58d6
* Content: [Using Bind or Connect Redirection](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/using-bind-or-connect-redirection)
* Content Source: [windows-driver-docs-pr/network/using-bind-or-connect-redirection.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/using-bind-or-connect-redirection.md)
* Service: **unspecified**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @SerusDev , good catch. I've corrected the typo and the change should be live soon. As another way to contribute, you can also use the "Edit" button in the upper right of the page and submit a PR that we can review and merge if you'd like. :) Thanks!
