### ISSUE TITLE
Does Universal Driver ( DCHU design principles)  requirement for HLK?

### ISSUE THREAD

**Issue by SonOfJesseAsSnekithan** [MicrosoftDocs/windows-driver-docs#464]
I understand the design principles and motivation behind the effort, design principles are very good, it make sense, it would truly make a driver as a universal driver that can run on any UWP supported platform as well as device manufacturer and and system builder can seamlessly work together for allowing future extend-ability .
I have few questions:
Does it apply to specific type of drivers or driver based on KMDF, WDM, or UMDF 2? [it is mentioned in Getting started guide: The driver binary can use KMDF, UMDF 2 or the Windows Driver Model (WDM).]
Do you think, ever such as printer driver can be a universal driver?  
I am not sure whether Windows print system is part of the OneCore?

Please provide some insights.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5fa76b-6c2e-8f5e-7e96-ceb1c726842b
* Version Independent ID: 48a29c52-9907-9b1a-1dc2-3365c2d021d0
* Content: [Getting Started with Universal Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/getting-started-with-universal-drivers)
* Content Source: [windows-driver-docs-pr/develop/getting-started-with-universal-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/getting-started-with-universal-drivers.md)
* Service: **unspecified**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Sorry for the delay on this one, @armstrong-charles.  Assigning this one to @barrygolden, who should be able to tell us if print drivers can be universal.

**Comment by armstrong-charles** [comment]
Any update on this?
Thanks

**Comment by Dark4Codrutz** [comment]
@barrygolden, I would like to know the answers on these topics as well as to further understand the possibilities of universal drivers.

**Comment by barrygolden** [comment]
Print drivers are not Universal drivers. To see examples of types of drivers that are Universal drivers, you can look at the driver samples on GitHub:

https://github.com/microsoft/Windows-driver-samples

If a driver sample is Universal, it will contain several `<DriverTargetPlatform>Universal</DriverTargetPlatform>` entries in the sample's .vcxproj file.
