### ISSUE TITLE
Link to "Bluetooth swift pair" does not work

### ISSUE THREAD

**Issue by pavel-a** [MicrosoftDocs/windows-driver-docs#465]
https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/components/bluetooth-swift-pair.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6c30c68-d0cb-7a62-f154-e6ab40c0119e
* Version Independent ID: 4dec63f5-fc8f-b8ea-117f-ddeed34bfc31
* Content: [What's new in driver development](https://docs.microsoft.com/en-us/windows-hardware/drivers/what-s-new-in-driver-development#bluetooth-1803)
* Content Source: [windows-driver-docs-pr/what-s-new-in-driver-development.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/what-s-new-in-driver-development.md)
* Service: **unspecified**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @pavel-a 

I fixed that. The correct link is https://docs.microsoft.com/en-us/windows-hardware/design/component-guidelines/bluetooth-swift-pair
