### ISSUE TITLE
ds, dS (Display String) page is easily confused for 'da' or 'du'

### ISSUE THREAD

**Issue by johndog** [MicrosoftDocs/windows-driver-docs#466]
If I'm looking for the command to 'display a string', the 'ds, dS' page is a prominent target.  It is way too easy to mistake it for the documentation for "display canonical string".  Perhaps "Display Kernel String" would clarify the purpose better.

The body actually mentions that one should use 'du' for Unicode strings, but doesn't mention 'da' for ASCII.  The omission makes the page look like an even better fit for someone that should be looking for 'da'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c9e19f-7b70-6ffe-97ae-6626756411f4
* Version Independent ID: 6757583f-a2cd-81e3-5add-c05c3c6bdede
* Content: [ds, dS (Display String)](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/ds--ds--display-string-)
* Content Source: [windows-driver-docs-pr/debugger/ds--ds--display-string-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/ds--ds--display-string-.md)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@johndog - Thanks for your input on adding additional information to disambiguate the various display string options. I added this text to the topic "Use the da command to display ASCII characters.", before the link to the da/du/etc. command.  As the second sentence indicates, the ds, dS commands do not display null-delimited character strings, but rather string structures.

The debugger command set is complex, and one goal of WinDbg Preview, is to allow for the visual browsing of variables and data. For example when symbols are available, you use the locals Windows to view variables with out using commands. See this link for more information -  https://review.docs.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-view-preview?branch=debugger-download#locals

Thanks again for your feedback and interest in the debugger documentation.
