### ISSUE TITLE
Help Index 1805

### ISSUE THREAD

**Issue by Bob123abc** [MicrosoftDocs/windows-driver-docs#470]
I do not see the Help Menu, Can You place a simple instruction in Windows 10 about how to  install a Help Index? An Even Grater Concern; Why was this not done on the Operating System Level like all of the other heavyweight apps and stuff that users are not allowed to remove. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 548c1f1e-14d7-43eb-5c8c-f33de17f5aa4
* Version Independent ID: c3113169-0b92-01b5-28af-6cd3865c29d6
* Content: [Help Index](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/help---index)
* Content Source: [https://cpubwin.visualstudio.com/_git/drivers?path=%2fwindows-driver-docs-pr%2fdebugger%2fhelp---index.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/drivers?path=%2fwindows-driver-docs-pr%2fdebugger%2fhelp---index.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@Bob123abc - The WinDbg help works as discussed in this topic. Windows Help is available by pressing F1 or typing tips into the search box on Windows 10.
