### ISSUE TITLE
Which i/o operations are acceptable to be registered by a minifilter?

### ISSUE THREAD

**Issue by nixomose** [MicrosoftDocs/windows-driver-docs#474]
I have found a number of pages that say this or something like it:
"The minifilter driver receives only those I/O operations for which it has registered a preoperation or postoperation callback routine."

Is there a list of what specific operations are allowed to be registered? I found some forum comments that imply that not every i/o request type is up for grabs in a minifilter. Is there an authoritative list of what is allowed and what is not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 457d9945-fef3-0805-507d-ae7778f00258
* Version Independent ID: 4f895b94-6bb1-2cf8-6c05-fc719e7343d9
* Content: [Writing Preoperation and Postoperation Callback Routines](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/writing-preoperation-and-postoperation-callback-routines)
* Content Source: [https://cpubwin.visualstudio.com/_git/drivers?path=%2fwindows-driver-docs-pr%2fifs%2fwriting-preoperation-and-postoperation-callback-routines.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/drivers?path=%2fwindows-driver-docs-pr%2fifs%2fwriting-preoperation-and-postoperation-callback-routines.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @nixomose, sorry for the delay. I'm taking this content over for Andrew temporarily. I'm not too familiar with this area, but you can find a list of I/O operations (and their parameters) in the [FLT_PARAMETERS](https://docs.microsoft.com/windows-hardware/drivers/ddi/content/fltkernel/ns-fltkernel-_flt_parameters) topic. Hopefully this helps; if you need more information, feel free to reopen this topic. I'll try to add an additional link on this topic to help make it more visible. Thanks!

**Comment by nixomose** [comment]
Okay I think that helped, based on that union structure list (in the FLT_PARAMETERES topic), I assume that's the entire list of what i/o operations a minifilter driver can receive.
I looked up IRP_MJ_READ and the parameter list include byte offset and length in the file, implying that all i/o requests are file based. I was hoping I could handle callbacks for block based i/o operations.
But unless you say otherwise, I guess I have to assume there is no block access callback available.
Thanks.

**Comment by nixomose** [comment]
no, I think scsi is one level too low (closer to the hardware than I'm talking about.) 
Basically I'm looking to make a driver that is kind of equivalent to the system restore shadow copy driver. A driver that has the ability to intercept reads and writes to the block drivers below them, with the magic of being a loadable and unloadable driver without needing to reboot. 
I was hoping a minifilter driver would be able to do this kind of thing, but apparently not.
Thanks for the info though, I appreciate the time you spared for me.
