### ISSUE TITLE
 FLT_PREOP_PENDING/FltCompletePendedOperation race

### ISSUE THREAD

**Issue by SylviaElse** [MicrosoftDocs/windows-driver-docs#475]
There is a potential race between the pre-opration routine returning FLT_PREOP_PENDING and the FltCompletePendingOperation being called, with the result that the latter routing may be called before per-operation routine returning. It appears that the Filter manager handles this situation, (and indeed, it's not clear that the Filter driver could do anything about it), but it needs to be stated that this situation is permitted, and is not an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72bd070a-7173-271d-effe-9a94e64983a3
* Version Independent ID: 70f5ba96-0267-2879-6e12-141c1365d10d
* Content: [Writing Preoperation Callback Routines](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/writing-preoperation-callback-routines)
* Content Source: [https://cpubwin.visualstudio.com/_git/drivers?path=%2fwindows-driver-docs-pr%2fifs%2fwriting-preoperation-callback-routines.md&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/_git/drivers?path=%2fwindows-driver-docs-pr%2fifs%2fwriting-preoperation-callback-routines.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @SylviaElse, sorry for the delay in getting to this. I've added this note to the topic, and it should be visible shortly. Thanks for this contribution!
