### ISSUE TITLE
[Question] Will the Dynamic Update overwrite a driver with CHID targeted?

### ISSUE THREAD

**Issue by JimWangQCI** [MicrosoftDocs/windows-driver-docs#477]
While a system upgrade OS, connect to network, the Dynamic Update driver will be installed.
However, I'd like to know if the system install a driver with CHID targeted, and upgrade OS to newer version, will the newer version of Dynamic Update driver (without CHID targeting) overwrite the driver on the system?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 531ef6ee-7a29-e6d0-56d6-e08a923b0aa4
* Version Independent ID: d00f4b65-2ae6-643f-d67a-c04f916a7058
* Content: [Publish a driver to Windows Update](https://docs.microsoft.com/zh-tw/windows-hardware/drivers/dashboard/publish-a-driver-to-windows-update)
* Content Source: [windows-driver-docs-pr/dashboard/publish-a-driver-to-windows-update.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/publish-a-driver-to-windows-update.md)
* Service: **windows-hardware**
* GitHub Login: @aahill
* Microsoft Alias: **windowsdriverdev**

**Comment by JimWangQCI** [comment]
Let me describe "the system install a driver with CHID targeted" clearly.
I want to mention here is that the system install a driver, and the driver also be published to Windows Update with CHID target, and it is an Optional Update.

**Comment by aahill** [comment]
Hi @JimWangQCI, thanks for reaching out. In answer to your question, if you have a newer version of a driver marked as *Optional Update*, it will only be installed to systems that don't have a driver already. If this driver was marked as *Critical Update*, it would overwrite it. 

This is assuming the driver doesn't require CHIDs to identify and be applied to the appropariate systems.

You can promote your drivers as *Critical Update* by specifying the appropriate checkboxes in your shipping label. Look at the "Driver Promotions" field under step four in the following article for a bit more info on that: [Publish a driver to Windows Update](https://docs.microsoft.com/windows-hardware/drivers/dashboard/publish-a-driver-to-windows-update).

I hope that helps answer your question!

**Comment by SillyKeith** [comment]
As of RS3 (1709), if there is an applicable, non-DU CHID targeted driver (of either Critical or Optional), it WILL block a DU non-CHID targeted driver.   

So, to answer your question-   No. the newer versioned DU driver (without CHID) would not come down because there is an applicable driver (with CHID) on WU.
