### ISSUE TITLE
How to find Driver Classes

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/windows-driver-docs#479]
[Enter feedback here]

Hi,

It is possible to confirm which driver class is used for a specific driver by something like : Read content of the INF file and find a line that tell my « Yes, this is the driver class xxxx ?

Why this question :

Due to some configuration, it’s almost necessary in enterprise to set a GPO to allow some non-administrators users to install drivers for specific classes, but it’s always easy to confirm the driver classe when this peripheral couldn’t be « classified » correctly… like a Multifunction (MFP) that include printer, scanner, USB card Reader, etc. in the same equipment.

P.S. : Your basic classes list is perfect ! But adding instruction for « Tell me which classes my driver use » could be very interesting !!!

Related to information on this page: https://docs.microsoft.com/en-us/windows-hardware/drivers/install/system-defined-device-setup-classes-available-to-vendors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c231a8b4-24a8-c339-8660-52a2b9d28226
* Version Independent ID: 093b0d00-46ae-b685-760c-c04e10b27595
* Content: [System-Defined Device Setup Classes Available to Vendors](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/system-defined-device-setup-classes-available-to-vendors)
* Content Source: [windows-driver-docs-pr/install/system-defined-device-setup-classes-available-to-vendors.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/system-defined-device-setup-classes-available-to-vendors.md)
* Service: **unspecified**
* GitHub Login: @tedhudek

**Comment by zlockard** [comment]
Can you clarify your question?  Are you looking to determine the class of an arbitrary INF, or are you looking to see what class a particular device was installed with?
