### ISSUE TITLE
Http route policy not working. 

### ISSUE THREAD

**Issue by hli88** [MicrosoftDocs/windows-driver-docs#480]
Hi, 
I follow the steps to connect to an additional APN end point on Win10. The APN name is provided by my network operator. 
I referenced this sample: https://code.msdn.microsoft.com/Connectivity-Manager-Sample-0c89b26f 
After adding the APN and adding the route policy, I use Windows.Web.Http.HttpClient to send RestFul api requests. But after checking the connection history on network operator's system. The data transaction still goes through the default APN in Windows Settings, not the one I configured. 
Any ideas about this? Or do I need additional configurations and dependence? 
Looking forward to your feedback. Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bb57675-1890-5529-2e52-be19aeabe221
* Version Independent ID: caee0f97-a9b4-fdf5-c3c2-f3474786e4d0
* Content: [Developing apps using multiple PDP contexts](https://docs.microsoft.com/en-us/windows-hardware/drivers/mobilebroadband/developing-apps-using-multiple-pdp-contexts)
* Content Source: [windows-driver-docs-pr/mobilebroadband/developing-apps-using-multiple-pdp-contexts.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/mobilebroadband/developing-apps-using-multiple-pdp-contexts.md)
* Service: **windows-hardware**
* GitHub Login: @aahill
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @hli88 , thanks for the question. As far as troubleshooting code goes, I found your question on the MSDN social forums and I think you're on the right track asking there. That was actually what I was going to recommend. :-) If you do get an answer and it contradicts the docs, please re-visit this thread with your findings and we'd be happy to update the docs accordingly.

Thanks again for your interest in the docs. Hope you can solve your issue.
