### ISSUE TITLE
Get an EV Code Signing Certificate. 

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/windows-driver-docs#495]
"Get an EV Code Signing Certificate. " link goes to / rather than an actual page with a list of CAs or how to get an EV Code Signing Certificate.  It's essentially STEP 1 of this whole submissino process...

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb19d33-8f4c-f379-b645-938a746c5615
* Version Independent ID: 8efb9fb4-1e9a-1a8a-994b-450495449e15
* Content: [Driver Signing Policy](https://docs.microsoft.com/en-gb/windows-hardware/drivers/install/kernel-mode-code-signing-policy--windows-vista-and-later-#feedback)
* Content Source: [windows-driver-docs-pr/install/kernel-mode-code-signing-policy--windows-vista-and-later-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/kernel-mode-code-signing-policy--windows-vista-and-later-.md)
* Service: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @OzBob for the catch. I've updated the link to point to https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate. Should be live within 24 hours.
