### ISSUE TITLE
Enabling IFR log for WDM driver

### ISSUE THREAD

**Issue by MarcinJanczara** [MicrosoftDocs/windows-driver-docs#498]
I tried to enable the IFR logging for WDM driver but it does not work.
Piece of my code in DriverEntry function looks as below and is almost the same as your example:

```
DriverEntry(
_In_ PDRIVER_OBJECT  DriverObject,
_In_ PUNICODE_STRING RegistryPath
)
{
	...
	
	NTSTATUS ntStatus;
	RECORDER_CONFIGURE_PARAMS recorderConfig;
	RECORDER_LOG_CREATE_PARAMS recorderCreate;
	RECORDER_LOG logHandle = NULL;
	
	WPP_INIT_TRACING(DriverObject, RegistryPath);
	
	if (WppRecorderIsDefaultLogAvailable())
	{
		TraceMsg(TRACE_LEVEL_ERROR, TRACE_DRIVER, "%!FUNC! Default log is available");
		RECORDER_CONFIGURE_PARAMS_INIT(&recorderConfig);
		WppRecorderConfigure(&recorderConfig);
		logHandle = WppRecorderLogGetDefault();
	}
	else
	{
		TraceMsg(TRACE_LEVEL_ERROR, TRACE_DRIVER, "%!FUNC! Default log is not available");
		RECORDER_CONFIGURE_PARAMS_INIT(&recorderConfig);
		recorderConfig.CreateDefaultLog = FALSE;
		recorderCreate.TotalBufferSize = 4 * 1024;
		RtlStringCbPrintfA(recorderCreate.LogIdentifier,
			RECORDER_LOG_IDENTIFIER_MAX_CHARS,
			"MyDriverLog");
		ntStatus = WppRecorderLogCreate(&recorderCreate, &logHandle);
	}

	ntStatus = WppRecorderLogCreate(&recorderCreate, &logHandle);
	if (!NT_SUCCESS(ntStatus))
	{
		TraceEvents(TRACE_LEVEL_ERROR, TRACE_DRIVER, "WppRecorderLogCreate failed %!STATUS!", ntStatus);
	}

	PrintEvents(logHandle, TRACE_LEVEL_ERROR, TRACE_DRIVER, "DriverEntry");
}
```

I configured all options accordance to your instruction but default log nor custom log were not created.
wmitrace shows the following message:
[2]0004.0008::05/15/2018-12:19:58.171 [Implementation]DriverEntry default log is not available
[2]0004.0008::05/15/2018-12:19:58.171 [Implementation]WppRecorderLogCreate failed 0xc000009a(STATUS_INSUFFICIENT_RESOURCES)

Does the IFR loging work for WDM drivers? Where should I look for a problem?

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: a71e4773-79fc-7733-464d-bfdca8823576
* Version Independent ID: a7cad97d-9b2e-4bb3-6f55-30ca5434505b
* Content: [Inflight Trace Recorder (IFR) for logging traces](https://docs.microsoft.com/pl-pl/windows-hardware/drivers/devtest/using-wpp-recorder)
* Content Source: [windows-driver-docs-pr/devtest/using-wpp-recorder.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/using-wpp-recorder.md)
* Service: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @MarcinJanczara.
I see that your question was answered in the [WDK forum](https://social.msdn.microsoft.com/Forums/vstudio/en-US/d1c8ae48-6eac-4131-a9a8-dfc3152965ca/enabling-ifr-log-for-wdm-driver?forum=wdk), so I am going to close this Issue. 
Thanks so much,
Eliot
