### ISSUE TITLE
Delete the driver software for this device checkbox is missing?

### ISSUE THREAD

**Issue by olavt** [MicrosoftDocs/windows-driver-docs#499]
I have the issue described here: https://www.gfisk.com/realtek-audio-driver-install-loop-windows-10/

The problem is that on my Windows 10 system there is no option named "Delete the driver software for this device".

Why is this option missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963a0877-81d6-57b1-2922-459c9077c76c
* Version Independent ID: 49998df1-e7fd-6ce7-eb49-aa9c37f13cd8
* Content: [Using Device Manager to Uninstall Devices and Driver Packages](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-device-manager-to-uninstall-devices-and-driver-packages)
* Content Source: [windows-driver-docs-pr/install/using-device-manager-to-uninstall-devices-and-driver-packages.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/using-device-manager-to-uninstall-devices-and-driver-packages.md)
* Service: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @olavt this is more a product question than a doc issue. I recommend trying [Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
or [ntdev forum](http://www.osronline.com/showlists.cfm?list=ntdev).

Best of luck with this issue!
