### ISSUE TITLE
Page doesn't have a link to Supported Ethernet NICs for Windows 10

### ISSUE THREAD

**Issue by peterwie** [MicrosoftDocs/windows-driver-docs#502]
Hi,

This page has links for network kernel debugging in Windows 8 and 8.1 but not a link to the Windows 10 documentation.

Also shouldn't those three pages (8, 8.1 and 10) be merged?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75819dbc-e20a-29f0-af02-5afc4628fd95
* Version Independent ID: fca932fe-08ba-a01c-30a7-2288342f6014
* Content: [Setting Up Kernel-Mode Debugging over a Network Cable in Visual Studio](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection-in-visual-studio)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-in-visual-studio.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection-in-visual-studio.md)
* Service: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@peterwie - This page now has a link to the Windows 10 supported adapter list. Thanks for the input.
