### ISSUE TITLE
Update text

### ISSUE THREAD

**Issue by Cest215** [MicrosoftDocs/windows-driver-docs#506]
Dear Microsoft,
     i want to modify the text "Please wait while we install a system update"
        (ex:"test XXX Capsule update" ).
      How can i rendered the text by the Windows bootloader? ?

Thanks
      

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca2c956b-1682-7c06-d68c-7c94da37007d
* Version Independent ID: 27245878-59d9-9018-3aee-327b5bc2abdd
* Content: [Boot screen components](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/boot-screen-components)
* Content Source: [windows-driver-docs-pr/bringup/boot-screen-components.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/boot-screen-components.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team.  Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
