### ISSUE TITLE
wia test

### ISSUE THREAD

**Issue by given73** [MicrosoftDocs/windows-driver-docs#507]
스캐너 제어

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f249dc34-425d-4553-6a3a-592d6f30a5a5
* Version Independent ID: e396a95c-d4d4-e99d-f999-4ebae2a17d4a
* Content: [32-Bit and 64-Bit WIA Interoperability](https://docs.microsoft.com/en-us/windows-hardware/drivers/image/32-bit-and-64-bit-wia-interoperability)
* Content Source: [windows-driver-docs-pr/image/32-bit-and-64-bit-wia-interoperability.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/image/32-bit-and-64-bit-wia-interoperability.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
Closing this issue, as we don't have enough information to address a specific question or comment regarding scanner controls.
