### ISSUE TITLE
FLT_PARAMETERS.AcquireForSectionSynchronization is not complete

### ISSUE THREAD

**Issue by 21street** [MicrosoftDocs/windows-driver-docs#508]
There's no OutputInformation field of type PFS_FILTER_SECTION_SYNC_OUTPUT in the AcquireForSectionSynchronization structure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20a64a62-c8b8-d3f7-942a-145b8d8907c9
* Version Independent ID: 3ecdda0f-ef9b-5bde-431e-81a7af013f64
* Content: [FLT\_PARAMETERS for IRP\_MJ\_ACQUIRE\_FOR\_SECTION\_SYNCHRONIZATION union](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/flt-parameters-for-irp-mj-acquire-for-section-synchronization)
* Content Source: [windows-driver-docs-pr/ifs/flt-parameters-for-irp-mj-acquire-for-section-synchronization.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/flt-parameters-for-irp-mj-acquire-for-section-synchronization.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by aahill** [comment]
Hi @21street , thanks for catching this. Looking at the function, you're right that the structure is missing. I've gone ahead and added it in, along with a short description. It should be visible shortly.

Thanks again!
