### ISSUE TITLE
Security & Quality Officer

### ISSUE THREAD

**Issue by JackHeeley** [MicrosoftDocs/windows-driver-docs#511]
Well collected set of solid advice useful links and evaluation tools here. For info: On this page the second Driver flow figure has a cut-and-paste typo: Two bubbles called "Handle read requests" (one is meant for 'write').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9ba8bf1-0603-9c63-fd54-c3a6ee061655
* Version Independent ID: f31972dc-1d5f-28b5-70c5-8f44df86175e
* Content: [Threat modeling for drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/driversecurity/threat-modeling-for-drivers#span-idcreateathreatmodelspanspan-idcreateathreatmodelspanspan-idcreateathreatmodelspancreate-threat-models-for-drivers)
* Content Source: [windows-driver-docs-pr/driversecurity/threat-modeling-for-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/driversecurity/threat-modeling-for-drivers.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@JackHeeley - Appreciate the kind words. The diagram is corrected so that IRP_MJ_WRITE is directed to a handle write requests bubble. Thanks for pointing this out.
