### ISSUE TITLE
Solid docs on RSS

### ISSUE THREAD

**Issue by jeffstokes72** [MicrosoftDocs/windows-driver-docs#513]
Thank you. This is really helpful when explaining DPC cpu consumption in large RSS implementations. Good on ya.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915e4234-78ae-7326-f219-4ae7390f1307
* Version Independent ID: f4d10278-3352-8e26-d7d5-dcb52e93dd2b
* Content: [Introduction to Receive Side Scaling](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-receive-side-scaling)
* Content Source: [windows-driver-docs-pr/network/introduction-to-receive-side-scaling.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/introduction-to-receive-side-scaling.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @jeffstokes72 , thanks for the kudos! We're glad the docs are helpful. :) Let us know if you have any other feedback.
