### ISSUE TITLE
. in front of SuiteMask in TargetOSVersion for Windows 10 > 1607 should not be optional

### ISSUE THREAD

**Issue by wind-rider** [MicrosoftDocs/windows-driver-docs#516]
In the article, the TargetOSVersion for Windows 10 > 1607 is defined as
```
nt[Architecture][.[OSMajorVersion][.[OSMinorVersion][.[ProductType][.SuiteMask][.[BuildNumber]]]]]
```

I read that as that if you want to target Windows 10.0 > build 17134, you should write `NT$ARCH$.10.0..17134`. However, that results in an error (the system not being able to find a suitable driver in the package).

The correct syntax should be `NT$ARCH$.10.0...17134`, and as such, TargetOSVersion should be
```
nt[Architecture][.[OSMajorVersion][.[OSMinorVersion][.[ProductType][.[SuiteMask][.[BuildNumber]]]]]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9445c977-9f8c-00c6-68fa-b575ab325fcf
* Version Independent ID: 58963a0b-6f4b-b6ee-f454-7e72e68d7bef
* Content: [INF Manufacturer Section](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-manufacturer-section)
* Content Source: [windows-driver-docs-pr/install/inf-manufacturer-section.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-manufacturer-section.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @wind-rider this is now fixed!  If you like, try submitting a PR next time.  You can just click **Edit** in the upper right of pages on docs.microsoft.com.
