### ISSUE TITLE
not a valid link..

### ISSUE THREAD

**Issue by Parihar07** [MicrosoftDocs/windows-driver-docs#522]
"Building a Driver" this pointing to https://docs.microsoft.com/en-us/windows-hardware/drivers/ which is not going to specific topic..!!!

where i can find proper link to configure Event Logging from driver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba986bf1-2f70-9c24-48bc-c45c8c6c21eb
* Version Independent ID: bcae4a5f-e457-e3ea-24b1-2d23b728c5fc
* Content: [Defining Custom Error Types](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/defining-custom-error-types)
* Content Source: [windows-driver-docs-pr/kernel/defining-custom-error-types.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/defining-custom-error-types.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks @Parihar07 and sorry for the confusion. The correct link is https://docs.microsoft.com/windows-hardware/drivers/develop/building-a-driver and the change in the link will be live on the site within 24 hours.
