### ISSUE TITLE
link not useful, ok, could be more useful

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs#525]
"... see Memory Allocation and Buffer Management..." link is essentially "go fish".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41838266-a165-d586-37d9-f42c2b9bcfca
* Version Independent ID: 047000a0-0695-27ab-c32a-05783d724530
* Content: [Windows Kernel-Mode Memory Manager](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/windows-kernel-mode-memory-manager)
* Content Source: [windows-driver-docs-pr/kernel/windows-kernel-mode-memory-manager.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/windows-kernel-mode-memory-manager.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @windows-driver-content

**Comment by EliotSeattle** [comment]
Thanks @BenWestbrook  
Edited the link to point to https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/_kernel/#memory-allocation-and-buffer-management. That's where we moved the old MSDN topic. Sorry for the confusion. Should be fixed on the live site within 24 hours.
