### ISSUE TITLE
"go fish" link

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs#530]
The link for "...Storport Driver Support Routines..." goes to the moral equivalent of "Go fish!".

I have not check any other links on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0125c7ed-3b8e-2f6e-f699-87f33a9b202b
* Version Independent ID: 4c02a853-8c10-8a9b-3893-692e7a006302
* Content: [Storage Miniport Drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/storage-miniport-drivers)
* Content Source: [windows-driver-docs-pr/storage/storage-miniport-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/storage-miniport-drivers.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @BenWestbrook sorry this one fell between the cracks. I just updated the set of links on that page, fix will be live momentarily
