### ISSUE TITLE
Pure Acks coalescing 

### ISSUE THREAD

**Issue by elenagurevich** [MicrosoftDocs/windows-driver-docs#531]
What is a reason do not coalesce pure ACK packets ?
The only information that is required for TCP processing is a number of arrived ACKs and cumulative acknowledgement number.
This information is enough for Reno/NewReno congestion algorithms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423a1055-ed86-1e17-f29e-d35436c0ac44
* Version Independent ID: 9c71623c-8217-00c8-2a7b-73bdffd8481c
* Content: [Rules for coalescing TCP/IP segments](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/rules-for-coalescing-tcp-ip-packets)
* Content Source: [windows-driver-docs-pr/network/rules-for-coalescing-tcp-ip-packets.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/rules-for-coalescing-tcp-ip-packets.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @elenagurevich , thanks for the question. Let me investigate this for you and see what I can find out.

**Comment by duncanmacmichael** [comment]
Hi @elenagurevich , thanks for your patience. After some discussion, the answer boils down to making sure that RSC doesn't impact Windows's TCP congestion control algorithms, both on the send and receive side. The details are internal-only, but at least we know why now. :) I'll go ahead and add a clarifying sentence to the page. Thanks for the question, and thanks for your interest in improving the docs.
