### ISSUE TITLE
Configration ?? :)

### ISSUE THREAD

**Issue by wolcotts** [MicrosoftDocs/windows-driver-docs#532]
Spelling: 'Configration of device objects'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6518fe85-2eae-ada0-f7ec-1d535f6be78f
* Version Independent ID: 6a90d069-c0b5-746b-041b-d2b7f7f6aabb
* Content: [Keyboard and mouse class drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/keyboard-and-mouse-class-drivers#configration-of-device-objects)
* Content Source: [windows-driver-docs-pr/hid/keyboard-and-mouse-class-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/keyboard-and-mouse-class-drivers.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @wolcotts, this is fixed, should be live later today. Please note you can submit a PR next time, if you like. To start, click the Edit button on pages on docs.microsoft.com
