### ISSUE TITLE
Need min version RS2 or greater

### ISSUE THREAD

**Issue by SoundersFan** [MicrosoftDocs/windows-driver-docs#535]
Your project file needs:
    <TargetPlatformMinVersion>10.0.15063.0</TargetPlatformMinVersion>
or higher for this to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d835c91-424a-a096-ea00-f1dd7c0bc0c4
* Version Independent ID: 1e73f683-6a1e-6794-8831-b6e6b170fa88
* Content: [Hardware Support App (HSA) Steps for App Developers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/hardware-support-app--hsa--steps-for-app-developers)
* Content Source: [windows-driver-docs-pr/devapps/hardware-support-app--hsa--steps-for-app-developers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devapps/hardware-support-app--hsa--steps-for-app-developers.md)
* Service: **unspecified**
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @SoundersFan I just added this to the page, should be live later today. In the future, feel free to open a PR if you like. To start, just click **Edit** in the upper right of any page on docs.microsoft.com
