### ISSUE TITLE
Where is GFLAGS.EXE?

### ISSUE THREAD

**Issue by jamers99** [MicrosoftDocs/windows-driver-docs#543]
Where specifically is gflags.exe located on my machine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a22663b1-a0d3-a1fc-9c75-5dfed8120cfe
* Version Independent ID: d0aa7acc-096b-9f25-8be0-b0057dd03c9a
* Content: [GFlags Overview](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags-overview)
* Content Source: [windows-driver-docs-pr/debugger/gflags-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/gflags-overview.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@jamers99 - I added "Where to get GFlags" information on the top level GFlags page:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags
I also added this link to the related sub pages.
For information on how to install and locate gflags.exe, see GFlags.
These additions should make GFlags easier to use for a wider set of users. Thanks for the input!
