### ISSUE TITLE
GUID_DEVINTERFACE_USB_HOST_CONTROLLER is undefined after including usbiodef.h.

### ISSUE THREAD

**Issue by R030t1** [MicrosoftDocs/windows-driver-docs#546]
Attempting to use the referenced identifier leads to:
```
Error	 LNK2001	unresolved external symbol GUID_DEVINTERFACE_USB_HOST_CONTROLLER	1	
```

An attempt was made to find altered project settings in the Windows driver examples USBView project but nothing stood out. It is possible to Ctrl+Click on the name to go to its definition. After browsing search results for low level device questions, it was noted various answers end up duplicating the GUID definitions locally.

The DEFINE_GUID macro does not seem to define a GUID based on the results of copying the `usbiodef.h` definition into my project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5462f622-961f-80a7-47f0-bcd028e30ae0
* Version Independent ID: 4a97231d-0b5d-521b-0c5d-1b1ecb2b8724
* Content: [GUID_DEVINTERFACE_USB_HOST_CONTROLLER](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-devinterface-usb-host-controller)
* Content Source: [windows-driver-docs-pr/install/guid-devinterface-usb-host-controller.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/guid-devinterface-usb-host-controller.md)
* GitHub Login: @tedhudek

**Comment by PageWriter-MSFT** [comment]
Hi @R030t1 

You need to include  initguid.h before including any header that has DEFINE_GUID. I have updated this topic and other USB GUID topics with this information. They should be live soon. Apologize for the inconvenience. 

Thanks!

Page Writer
