### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by denniskupec** [MicrosoftDocs/windows-driver-docs#548]
Links to DispatchCreate and DispatchCreateClose routines lead to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77adb1c5-e373-51b8-ed29-cb70efa37b02
* Version Independent ID: fa6f2ac7-1746-e71e-3e1d-9aeec8ae6112
* Content: [IRP_MJ_CREATE](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/irp-mj-create)
* Content Source: [windows-driver-docs-pr/kernel/irp-mj-create.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/irp-mj-create.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @denniskupec 
@PageWriter-MSFT the MSDN links are not redirecting. This occurs on at least https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/dispatchcreate--dispatchclose--and-dispatchcreateclose-routines and below, as well.

**Comment by PageWriter-MSFT** [comment]
Hello,

Thanks for reporting this broken links. These should now be fixed.

Page Writer
