### ISSUE TITLE
IOCTL_ATA_PASS_THROUGH_DIRECT

### ISSUE THREAD

**Issue by wanghao19901024** [MicrosoftDocs/windows-driver-docs#554]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4076dd23-433e-2ec1-789a-e70b2e447fb7
* Version Independent ID: c9a5dc47-62e4-bdb9-b28d-aa1d6d0c78d1
* Content: [IRP_MJ_DEVICE_CONTROL](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/irp-mj-device-control)
* Content Source: [windows-driver-docs-pr/kernel/irp-mj-device-control.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/irp-mj-device-control.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi, @wanghao19901024 
Was there a question or comment about this topic?
