### ISSUE TITLE
Chiropractor

### ISSUE THREAD

**Issue by missoulachiro** [MicrosoftDocs/windows-driver-docs#555]
ok

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 276f3657-1e22-7622-b615-b9c166c6ebaa
* Version Independent ID: 45cfbf7e-d95a-b7a0-7625-b1802c763312
* Content: [lmi](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-lmi)
* Content Source: [windows-driver-docs-pr/debugger/-lmi.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-lmi.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Hi @missoulachiro. My back has been fine lately. :-) Did you have a question or comment about this topic?
