### ISSUE TITLE
less than helpful "go fish" link

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs#561]
The link for "Storport Driver Support Routines" needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7f7489b-89e8-1316-c7ad-0855d5f6c299
* Version Independent ID: efd328fe-d215-9e1e-9ef9-07dd66c598aa
* Content: [Storport Miniport Drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/storport-miniport-drivers)
* Content Source: [windows-driver-docs-pr/storage/storport-miniport-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/storport-miniport-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Storport Miniport drivers and Storport driver routines now both fixed. Thanks, @BenWestbrook for your help.
