### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs#564]
"...Safe String Library Routines..." link goes to "go fish"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa98807-a935-7fe0-b885-6d3d87cd1729
* Version Independent ID: ff580c01-a9c8-886d-be29-cc01e0508740
* Content: [Windows Kernel-Mode Safe String Library](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/windows-kernel-mode-safe-string-library)
* Content Source: [windows-driver-docs-pr/kernel/windows-kernel-mode-safe-string-library.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/windows-kernel-mode-safe-string-library.md)
* GitHub Login: @windows-driver-content

**Comment by EliotSeattle** [comment]
Thanks, @BenWestbrook 
Added: for a list of all safe string library routines for the kernel, see [Safe String Functions for Unicode and ANSI Characters](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/_kernel/#safe-string-functions-for-unicode-and-ansi-characters) and [Safe String Functions for UNICODE_STRING Structures](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/_kernel/#safe-string-functions-for-unicodestring-structures).
