### ISSUE TITLE
AMIMI

### ISSUE THREAD

**Issue by AMIMI58** [MicrosoftDocs/windows-driver-docs#568]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9edea7cc-ef90-1912-6185-ebc68f590a88
* Version Independent ID: ea718ca7-72a4-17af-b264-0847821aaefc
* Content: [Personal Information Exchange (.pfx) Files](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/personal-information-exchange---pfx--files)
* Content Source: [windows-driver-docs-pr/install/personal-information-exchange---pfx--files.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/personal-information-exchange---pfx--files.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @AMIMI58 did you mean to leave feedback on this doc page?  Closing this out because it's empty but feel free to reopen if you did have something.
