### ISSUE TITLE
Wrong <i>documentation

### ISSUE THREAD

**Issue by shaharlux** [MicrosoftDocs/windows-driver-docs#574]
&lt;i&gt;underlined text&lt;/i&gt; should be &lt;u&gt;underlined text&lt;/u&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111d2757-e762-0c78-cb93-cb57067734cb
* Version Independent ID: 9310c5c7-ea2b-87ac-28c1-cca387264006
* Content: [Customizing Debugger Output Using DML](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/customizing-debugger-output-using-dml)
* Content Source: [windows-driver-docs-pr/debugger/customizing-debugger-output-using-dml.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/customizing-debugger-output-using-dml.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Oops. Fixed in the build. Should be live within 24 hours. Thanks for catching this, @shaharlux
