### ISSUE TITLE
List of Operating System Codes Incorrect

### ISSUE THREAD

**Issue by Scott1** [MicrosoftDocs/windows-driver-docs#581]
I think some of the codes listed in the "List of Operating System Codes" section might be incorrect.

I tried using Windows_v100_X86_* codes but getting an error back:

{
  "error": {
    "code": "invalidInput",
    "message": "Validation Failed.",
    "validationErrors": [
      {
        "target": "requestedSignatures",
        "message": "The OS code `WINDOWS_v100_X86_TH2_FULL` is invalid."
      },
      {
        "target": "requestedSignatures",
        "message": "The OS code `WINDOWS_v100_X86_RS1_FULL` is invalid."
      },
      {
        "target": "requestedSignatures",
        "message": "The OS code `WINDOWS_v100_X86_RS2_FULL` is invalid."
      },
      {
        "target": "requestedSignatures",
        "message": "The OS code `WINDOWS_v100_X86_RS3_FULL` is invalid."
      },
      {
        "target": "requestedSignatures",
        "message": "The OS code `WINDOWS_v100_X86_RS4_FULL` is invalid."
      }
    ]
  }
}

Looks like the X86 shouldn't be in there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c20769b-d969-a51a-4eb3-f9cc27875f28
* Version Independent ID: 853fe2a9-d654-98a3-7635-c30a450cdbdc
* Content: [Get product data](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-product-data#list-of-operating-system-codes)
* Content Source: [windows-driver-docs-pr/dashboard/get-product-data.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/get-product-data.md)
* Product: **windows-hardware**
* GitHub Login: @balapv
* Microsoft Alias: **balapv**

**Comment by aahill** [comment]
@Scott1, thanks for letting us know about this. I'll get the documentation updated soon. 

@balapv, @SillyKeith, do you know if we should remove these x86 entries?
