### ISSUE TITLE
The Code-Signing Best Practices website link is dead

### ISSUE THREAD

**Issue by Torgrimm** [MicrosoftDocs/windows-driver-docs#584]
http://go.microsoft.com/fwlink/p/?linkid=74265

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7659d22f-595a-6b02-566d-1325cf20d5cd
* Version Independent ID: 8dd845af-7408-99e7-20d0-331ad901c328
* Content: [Managing the Digital Signature or Code Signing Keys](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/managing-the-digital-signature-or-code-signing-keys)
* Content Source: [windows-driver-docs-pr/install/managing-the-digital-signature-or-code-signing-keys.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/managing-the-digital-signature-or-code-signing-keys.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @Torgrimm, sorry I was unable to find anything more recent.  That link used to go to http://download.microsoft.com/download/a/f/7/af7777e5-7dcd-4800-8a0a-b18336565f5b/best_practices.doc but that paper is from 2007.  So I removed the entire sentence.  If you have more questions about this, try the OSR forum at http://www.osronline.com/showlists.cfm?list=ntdev
