### ISSUE TITLE
Missing entry for 0x3030308

### ISSUE THREAD

**Issue by mcarbone** [MicrosoftDocs/windows-driver-docs#586]
Paremeter 1 0x3030308 for stop code 0x1a (MEMORY_MANAGEMENT) is not documented. I believe it applies to some types of memory regions that exceed a certain physical boundary.

**Comment by tedhudek** [comment]
Hi @mcarbone is this the page you're looking for?  https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x1a--memory-management

@domars fyi

**Comment by DOMARS** [comment]
Planning to consolidate the bug check 0x1A memory issues and get with the dev team this week.

**Comment by DOMARS** [comment]
@mcarbone - Information on the 0x03030308 parameter is now included in the topic. Thanks for the input on the stop code topics.
