### ISSUE TITLE
windbg.exe -I

### ISSUE THREAD

**Issue by sahikon** [MicrosoftDocs/windows-driver-docs#589]
The first appearance of "windbg.exe -I" happens long before the same command appears in monospaced font.
And "-I" (capital 'i') and "-l" (lower case 'L') cannot be easily distinguished.

I guess there are bunch of people like me who will not read till the end of the document and will misread the command.

I propose to change font of "windbg.exe -I" to be monospaced to minimize the risk of confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2892006d-13af-24e6-699f-ad5c2e7dc7a5
* Version Independent ID: 8fa52962-0050-1f7e-9664-d8a48c46d429
* Content: [Enabling Postmortem Debugging](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/enabling-postmortem-debugging)
* Content Source: [windows-driver-docs-pr/debugger/enabling-postmortem-debugging.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/enabling-postmortem-debugging.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@sahikon - I see what you are saying, the current text font is not doing a good job, so I updated the i/l references to a monospace command font, using the triple back tick markdown, literal text syntax. Changes should be live in 24-48 hours. Thanks for providing this input and improving the topic for others!
