### ISSUE TITLE
"PropPageExtensions" project doesn't exist in the drivers repository

### ISSUE THREAD

**Issue by justanotheranonymoususer** [MicrosoftDocs/windows-driver-docs#591]
https://github.com/Microsoft/Windows-driver-samples/tree/master/audio/sysvad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb10a40-2e9b-3808-20e2-86c829f94d17
* Version Independent ID: 1dfbc27f-f46f-21cf-bbe2-89010bdaf202
* Content: [Implementing Audio Processing Objects](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/implementing-audio-processing-objects)
* Content Source: [windows-driver-docs-pr/audio/implementing-audio-processing-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/implementing-audio-processing-objects.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@justanotheranonymoususer - Thanks for pointing this out. I have updated the topic to remove references to the prop page extensions. Updated topic should be live in 24 to 48 hours. Thanks again for this issue.
