### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by justanotheranonymoususer** [MicrosoftDocs/windows-driver-docs#593]
> The following INF file samples shows

`shows` should be `show`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb10a40-2e9b-3808-20e2-86c829f94d17
* Version Independent ID: 1dfbc27f-f46f-21cf-bbe2-89010bdaf202
* Content: [Implementing Audio Processing Objects](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/implementing-audio-processing-objects)
* Content Source: [windows-driver-docs-pr/audio/implementing-audio-processing-objects.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/implementing-audio-processing-objects.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks so much, @justanotheranonymoususer 
Please feel free--especially for fixes like this--to edit the source and commit the change yourself. That would be greatly appreciated! 
Thanks, Eliot
