### ISSUE TITLE
missed opportunity for helpful link

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs#595]
SRB_IO_CONTROL should probably link to a description of the structure. I believe the URL below might be suitable.

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddscsi/ns-ntddscsi-_srb_io_control

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f66e88e-fe5a-9016-d69a-bb49322f2030
* Version Independent ID: 7f9afa5d-f953-58f6-2d0a-b8c37939dc64
* Content: [Handling SRB_FUNCTION_IO_CONTROL](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/handling-srb-function-io-control)
* Content Source: [windows-driver-docs-pr/storage/handling-srb-function-io-control.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/handling-srb-function-io-control.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @BenWestbrook 
Added links to Handling 
SRB_FUNCTION_EXECUTE_SCSI 
and 
SRB_IO_CONTROL
Especially for suggestions like this, please feel free to make the edit and create a PR. Cheers, Eliot
