### ISSUE TITLE
maybe something is missing

### ISSUE THREAD

**Issue by BenWestbrook** [MicrosoftDocs/windows-driver-docs#601]
several items:

1) in VisualStudio2017 kernel debugging the dd command referenced above does not work unless the nt! prefix version is used.

2) in VisualStudio2017 kernel debugging the above referenced ed command simply does not work (command "ed" is not valid) - do the samples need updating?

3) in VisualStudio2017, following above instructions for bitmask setting for both DEFAULT and IHVDRIVER set to 0xFFFFFFFF (print anything I send you), reboot after registry changes, and then DbgPrintEx(DPFLTR_IHVDRIVER_Mask, DPFLTR_TRACE_LEVEL, "blah blah blah") ; does not result in any debug output.

4) honestly guys, DebugPrintf is supposed to be simple! It should just work without any magic incantations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a54c237f-c2ff-394e-5165-87abfcbfc153
* Version Independent ID: 1ba1fe5e-2ee2-70bd-643b-b420fe1e4ab5
* Content: [Reading and Filtering Debugging Messages](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/reading-and-filtering-debugging-messages)
* Content Source: [windows-driver-docs-pr/devtest/reading-and-filtering-debugging-messages.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/reading-and-filtering-debugging-messages.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@BenWestbrook - Kernel debugging is no longer supported in Visual Studio. We have added this text to the setup topics such as [Setting Up Kernel-Mode Debugging in Visual Studio](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-kernel-mode-debugging-in-visual-studio).

*Important
This feature is not available in Windows 10, version 1507 and later versions of the WDK.*

The recommended debugger would be WinDbg or the new UI available in WinDbg Preview [Debugging Using WinDbg Preview](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugging-using-windbg-preview).


In [Debug Universal Drivers - Step by Step Lab (Echo Kernel-Mode)](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-)  I describe how the ed nt!Kd_DEFAULT_MASK  0xFFFFFFFF command can be used to display additional debug message output. 

Thanks for your interest in our docs and good luck in your development efforts.
