### ISSUE TITLE
ExInitializeDriverRuntime 

### ISSUE THREAD

**Issue by AndreFo** [MicrosoftDocs/windows-driver-docs#607]
Article says "ExInitializeDriverRuntime ... can be called on Windows 8 and earlier versions of Windows." This does not seem to be correct. Should instead read like: "ExInitializeDriverRuntime ... can be called on Windows 8 and later versions of Windows."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30ed3997-1721-5972-8777-4dcb0ea6e532
* Version Independent ID: 061a2d78-fffd-890d-cedd-6ba530613082
* Content: [Single Binary Opt-In POOL_NX_OPTIN](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/single-binary-opt-in-pool-nx-optin)
* Content Source: [windows-driver-docs-pr/kernel/single-binary-opt-in-pool-nx-optin.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/single-binary-opt-in-pool-nx-optin.md)
* GitHub Login: @windows-driver-content

**Comment by EliotSeattle** [comment]
Thanks for pointing this out, @AndreFo 
@PageWriter-MSFT can you please see what's up with this? I can't make headway.

**Comment by PageWriter-MSFT** [comment]
Hi @AndreFo 

You are absolutely correct. **ExInitializeDriverRuntime** was introduced in Windows 8. I have updated the topic. Should be live soon.


Thanks for catching that!


Page Writer

Thanks for catching that.
