### ISSUE TITLE
Network Adapter Interface indices

### ISSUE THREAD

**Issue by Megatransect** [MicrosoftDocs/windows-driver-docs#609]
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/network-adapter-index-values

This article is very superficial and doesn't properly explain the meaning of the network adapter interface index and how it's used or the what the various values mean.    They appear in the output from Get-NetIPAddress.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90210df3-ddf4-246b-b1f8-b1db7e8e6c9a
* Version Independent ID: d209c296-1c67-05e7-d72e-69d018c3bec2
* Content: [Network Adapter Index Values](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/network-adapter-index-values)
* Content Source: [windows-driver-docs-pr/network/network-adapter-index-values.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/network-adapter-index-values.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @Megatransect for the feedback. Were there specific parts that you were looking for, or were you saying that just everything could be more detailed? Specifics will help us focus with prioritization.
@duncanmacmichael can you please consider this request for future work and create tasks as appropriate and time allows?

**Comment by Megatransect** [comment]
I have no specific requirements other than the general.    Network
Interface Index is skimmed over everywhere it seems.   Trying to find out
what it is led me to the page we are talking about where it is indeed again
skimmed over.

For example, in the past the exams for 70-741 referred to the adapters in a
list by the that index number.  Its not a  confusion about whether its
intended for developers or sysadmins but a lack of clarity in general in
the documentation.

You have the ::1/128 loopback with consistently the same index number 1 as
127.0.0.1/32 so it's not that closely related to the device driver but
implies then some kind of priority.

Could it be an ordering for binding for RDMA or NIC teaming?  Is it
something to do with the other index number as seen here:
$   Get-WmiObject win32_networkadapter | Select-Object name, index,
interfaceindex

So many questions that go nowhere in the docs.   Theres even a settable
index metric at the bottom of the advanced tcpip settings window.
(right  click adapter - properties -  ipv4 - advanced)    Is that the same
index?
It's not even clear why it appears in Get-NetIPAddress

It would be good if Network Adapter Index was documented a bit better than
it is for us enthusiasts.
Here seems like a good place?
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/network-adapter-index-values

**Comment by duncanmacmichael** [comment]
I see, thanks for the clarification. That makes sense. Let me ask the feature team what they think about the best way to elaborate on this, and see if this is the best doc page to do that.

**Comment by duncanmacmichael** [comment]
Okay @Megatransect , I've had a conversation with the network driver platform team and got some good information about network interfaces in general, including the interface index values. I'll create a new page for it since it's very general and wouldn't make sense here. That should be ready soon; I'll give you a link when it's done.

**Comment by duncanmacmichael** [comment]
Hi @Megatransect, here's an update for you. I wrote a new [Network Interfaces](https://docs.microsoft.com/windows/desktop/network-interfaces) topic in the Windows Desktop doc repo that provides a high-level overview of network interfaces on Windows. It's aimed at a developer audience, but it could be interesting for enthusiasts like yourself if you want to read about them. 

One thing to keep in mind is that things like **ifIndex** are defined in the RFC linked on the page, so we can't give exact details for the definitions and all the ways they're used. The takeaway is that network interfaces have identifiers that vary based on their properties, so APIs or cmdlets use different ones depending on that piece of code's needs. 

Hope this helps!
