### ISSUE TITLE
Link to Bluetooth Assigned Numbers is outdated 

### ISSUE THREAD

**Issue by sahikon** [MicrosoftDocs/windows-driver-docs#612]
New link is https://www.bluetooth.com/specifications/assigned-numbers/baseband

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa52ee84-78eb-85eb-55d0-9a2163f95799
* Version Independent ID: d81d2cfd-2f50-ccbd-ec6f-96d73897b8ed
* Content: [Bluetooth Registry Entries](https://docs.microsoft.com/en-us/windows-hardware/drivers/bluetooth/bluetooth-registry-entries)
* Content Source: [windows-driver-docs-pr/bluetooth/bluetooth-registry-entries.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bluetooth/bluetooth-registry-entries.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @sahikon 
Fixed in source. Should be live soon.
