### ISSUE TITLE
The link to the print schema spec is dead.

### ISSUE THREAD

**Issue by fielcabral** [MicrosoftDocs/windows-driver-docs#614]
The link to the print schema spec is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3892edf0-b328-760d-fb10-89ff64164c0d
* Version Independent ID: 05734c1b-9f00-d40b-9f0a-e34fd4b29dea
* Content: [Print schema references](https://docs.microsoft.com/en-us/windows-hardware/drivers/3dprint/print-schema-references)
* Content Source: [windows-driver-docs-pr/3dprint/print-schema-references.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/3dprint/print-schema-references.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
@fielcabral the link to the [Print Schema Specification](http://download.microsoft.com/download/d/e/c/deca6e6b-3e81-48e7-b7ef-6d92a547d03c/print-schema-spec-2-0.zip) download has been updated on the [Print schema references](https://docs.microsoft.com/en-us/windows-hardware/drivers/3dprint/print-schema-references) page.
