### ISSUE TITLE
RE: C++ for Kernel Mode Drivers: Pros and Cons 

### ISSUE THREAD

**Issue by sbfraser01** [MicrosoftDocs/windows-driver-docs#616]
Interesting whitepaper. I don't know how much of it is true now, but it's helping me get in the mindset of the driver developer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e755005-a187-149c-c4c4-423cedfe1b97
* Version Independent ID: 5db14ac5-b177-2ba7-17e4-da209902781e
* Content: [Portable](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/portable)
* Content Source: [windows-driver-docs-pr/kernel/portable.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/portable.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for your interest, @sbfraser01
It would be extremely helpful, Sean, if you could let us know--as you head down the driver dev path--which of our resources help (and why), which don't, if you find anything really great on another site, or even what you feel is missing. Cheers, Eliot
