### ISSUE TITLE
Inaccurate link for hardware key reference

### ISSUE THREAD

**Issue by broncopulse** [MicrosoftDocs/windows-driver-docs#617]
The link to the definition of the hardware key only leads to the WDK page. It needs to be fixed.
More accurate link: https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/introduction-to-registry-keys-for-drivers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8d1bbe-fc08-d3de-4dd7-c4a476f320ba
* Version Independent ID: 784b74f5-0dcd-9a19-bcb5-ff9708707e10
* Content: [INF DDInstall.HW Section](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-ddinstall-hw-section)
* Content Source: [windows-driver-docs-pr/install/inf-ddinstall-hw-section.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-ddinstall-hw-section.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @broncopulse
That link used to go to a glossary that no longer exists. That paragraph now ends with:
An HKR specification in such an add-registry-section specifies the device's hardware key, a device-specific registry subkey that contains information about the device. A hardware key is also called a device key. For more info, see [Registry Trees and Keys for Devices and Drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/registry-trees-and-keys). A driver package can add settings via an INF by using an HKR specification in an add-registry-section referenced by a DDInstall.HW section.

I've pushed the change and it should be live shortly.
