### ISSUE TITLE
Link to " guidelines for a Universal Audio Architecture (UAA)" not working

### ISSUE THREAD

**Issue by JBradon** [MicrosoftDocs/windows-driver-docs#619]
The link to "guidelines for a Universal Audio Architecture (UAA)" early on this document does not seem to be working.
I searched for this on google and found a recent webpage so think it has been moved since this page was published.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e944dc-d0eb-bc5b-2e28-688843a0033e
* Version Independent ID: 276bc720-bcab-5dd1-3c5b-94327af5183b
* Content: [Developing a WaveRT Miniport Driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/developing-a-wavert-miniport-driver#feedback)
* Content Source: [windows-driver-docs-pr/audio/developing-a-wavert-miniport-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/developing-a-wavert-miniport-driver.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@JBradon - Thanks for pointing this out. The fix has been checked in and should be live later today. Thanks again for contributing to the docs.
