### ISSUE TITLE
Document markup artefact?

### ISSUE THREAD

**Issue by skycommand** [MicrosoftDocs/windows-driver-docs#624]
There is a problem appearing in:
- This page
- All its subpages ("[Overview of the Boot.ini File](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/overview-of-the-boot-ini-file)", "[Editing the Boot.ini File](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/editing-the-boot-ini-file)" and "[Backing Up the Boot.ini File](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/backing-up-the-boot-ini-file)") 
- Several other pages ("[Boot Options in EFI NVRAM](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-options-in-efi-nvram)" and "[Overview of Boot Options in Windows](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-options-in-windows)") in this topic

The problem is: The phrase "`[!IMPORTANT]`" appears before one of the paragraphs at the top. This is, of course, far from good writership, but it suspect it is a markup element that didn't get rendered during the export to Microsoft Docs because the "`[!NOTE]`" markup seems to render perfectly in Microsoft Docs, forming a cyan note box, with an icon.

In another page, "[BCDEdit /set](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--set)", I can see a "`[!Caution]`" markup. I don't mean to frighten you, but right now, I am thinking "Just how many Microsoft Docs pages are affected by this type of markup failure?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878e393f-198a-6d44-978d-9896aa10455b
* Version Independent ID: e8b27656-fdf3-0a69-f40c-2908c0744acb
* Content: [Boot Options in a Boot.ini File](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-options-in-a-boot-ini-file)
* Content Source: [windows-driver-docs-pr/devtest/boot-options-in-a-boot-ini-file.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/boot-options-in-a-boot-ini-file.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @skycommand 
@barrygolden can you please fix these and look into whether we have a, gulp, global issue from migration?

**Comment by barrygolden** [comment]
@skycommand the malformed alert text instances you found have been fixed. We'll scan the driver docs for other occurrences of malformed alert text and script a fix as required. Thanks for filing the issue.

**Comment by EliotSeattle** [comment]
I think you're on safe ground saying that you contributed to the Microsoft Windows Drivers documentation. :)
Thanks so much!

**Comment by skycommand** [comment]
Oh! That's not what I meant. It was a joke...

Social decorum recommends resorting to a joke to counter tension or fear (in this case that of there being a global migration issue with far-reaching consequences) by making the affected people smile. I am not so petty as to tell anyone something like "I'm working with Microsoft" just because I wrote a comment. (Bah! Writing a comment! Kids do that! A lot!) Demonstrating such extreme degrees of hubris, I assumed, counts as joke. (Note to self: It was a failed joke.)

**Comment by EliotSeattle** [comment]
We don't joke here. 
Just kidding. :-)
