### ISSUE TITLE
King

### ISSUE THREAD

**Issue by kent11120** [MicrosoftDocs/windows-driver-docs#626]
My fine all my life is true. And fear. 

By lawyer Us with Citizen or King A
Rap

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb18307-ceb7-f8b3-c758-c6522ba4912a
* Version Independent ID: 75c43c5f-e059-05ce-75c6-dba165638fa8
* Content: [Identifiers for 1394 Devices](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/identifiers-for-1394-devices)
* Content Source: [windows-driver-docs-pr/install/identifiers-for-1394-devices.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/identifiers-for-1394-devices.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @kent11120 
I don't see a request regarding Identifiers for 1394 Devices, so I am closing this Issue.
