### ISSUE TITLE
Link dead

### ISSUE THREAD

**Issue by michab66** [MicrosoftDocs/windows-driver-docs#628]
1:
 this KB article

2:
How to use or to reference the Usbser.sys driver from universal serial bus (USB) modem .inf files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d53160-d39b-61f0-2cf7-44d618d29a21
* Version Independent ID: ca1946c2-ef7d-4f83-a564-c0e387c39845
* Content: [USB serial driver (Usbser.sys)](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-driver-installation-based-on-compatible-ids)
* Content Source: [windows-driver-docs-pr/usbcon/usb-driver-installation-based-on-compatible-ids.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/usb-driver-installation-based-on-compatible-ids.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
@michab66 thanks for catching that. The KB is now live again.

Page Writer
