### ISSUE TITLE
"Note: ....." comment of deprecated is confusing customer sensor driver developers

### ISSUE THREAD

**Issue by Ron-Hu** [MicrosoftDocs/windows-driver-docs#635]
To whom owns this documentation section.

We should remove this for the next year (if agreed to by developer Jocelyn Berrendonner).  Until the devs have a replacement that is on par with or better than this tool.  We should not confuse the driver writers externally to Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaa679ed-1f4f-30be-0990-2f3dcd400cd7
* Version Independent ID: 9b4d4c6c-6ff7-5f74-89c6-adbef29858a2
* Content: [Use the Sensors Diagnostic Tool to test your driver and device](https://docs.microsoft.com/en-us/windows-hardware/drivers/sensors/using-the-sensors-diagnostic-tool-to-test-your-driver-and-device#feedback)
* Content Source: [windows-driver-docs-pr/sensors/using-the-sensors-diagnostic-tool-to-test-your-driver-and-device.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/sensors/using-the-sensors-diagnostic-tool-to-test-your-driver-and-device.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @Ron-Hu 
@mimisasouvanh can you take this offline with Jocelyn, please?
