### ISSUE TITLE
download header files

### ISSUE THREAD

**Issue by Huihh** [MicrosoftDocs/windows-driver-docs#637]
Hi, 
    where can i download those header files related to hid development, etc. hidclass.h, hidpddi.h, hidpi.h, hidport.h, hidsdi.h, kbdmou.h, ntdd8042.h, sffprtcl.h, vhf.h,   Thank you very much

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36318bc-76cd-c372-d676-4a0c20b60dcf
* Version Independent ID: b02eaae7-3cb2-25d1-6dc4-d90e99385ebb
* Content: [HID drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/)
* Content Source: [windows-driver-docs-pr/hid/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/index.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Hello @Huihh 

These HID headers are available with the WDK. Please follow the instructions on this page: [Download the Windows Driver Kit (WDK)](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk)

Thanks

Page Writer
