### ISSUE TITLE
Registry Location

### ISSUE THREAD

**Issue by mickpletcher** [MicrosoftDocs/windows-driver-docs#638]
It would have been nice to have the exact registry locations defined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56db178-78e9-9564-e2d0-8d4dc5a0068d
* Version Independent ID: e31df79f-b30a-75f2-335c-637a9eeaca25
* Content: [Local Machine and Current User Certificate Stores](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/local-machine-and-current-user-certificate-stores)
* Content Source: [windows-driver-docs-pr/install/local-machine-and-current-user-certificate-stores.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/local-machine-and-current-user-certificate-stores.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @mickpletcher I've updated https://docs.microsoft.com/windows-hardware/drivers/install/local-machine-and-current-user-certificate-stores with a link to the info you requested.
