### ISSUE TITLE
Garbage in the end of the page

### ISSUE THREAD

**Issue by sahikon** [MicrosoftDocs/windows-driver-docs#648]
I mean the following two lines:
"�

�"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddd8d0d4-08cf-039d-25cd-5f32cd45797f
* Version Independent ID: 9d8e6ed9-ce8b-2e70-fac2-1b56017a34a4
* Content: [ACPI system description tables](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/acpi-system-description-tables)
* Content Source: [windows-driver-docs-pr/bringup/acpi-system-description-tables.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/acpi-system-description-tables.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
@sahikon thanks for catching this issue. The non-printing characters have been removed and the changes should be live soon.
