### ISSUE TITLE
Section 3 - broken bullet list

### ISSUE THREAD

**Issue by sahikon** [MicrosoftDocs/windows-driver-docs#651]
Bullet list is broken in the section number 3:

It should look something like:

The audio driver sets the parameters to IoSetDeviceInterfacePropertyData as follows: 
* The SymbolicLinkName is the string returned from IoRegisterDeviceInterface. 
* The remaining parameters depend on the specific property being set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a30427-fc71-0347-7754-073fe22ba2d7
* Version Independent ID: 19cd0d42-aeb7-7f8f-abd5-79c319f5f3e5
* Content: [Setting Properties and Registry Values](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/setting-properties-and-registry-values)
* Content Source: [windows-driver-docs-pr/audio/setting-properties-and-registry-values.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/setting-properties-and-registry-values.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Done. Thanks, @sahikon 
Should be live shortly.
Feel free to edit the content and submit a pull request for fixes. We get a bonus for each PR submitted. Just kidding, but you get the bonus of contributing directly to the docs!

**Comment by sahikon** [comment]
@EliotSeattle  - good to know, will try :-)
