### ISSUE TITLE
 hardware IDs link broken

### ISSUE THREAD

**Issue by LarryK348** [MicrosoftDocs/windows-driver-docs#658]
The link goes to generic WDK page, no information about hardware IDs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a362ee-a3b4-27ed-62c6-1d7154d773fc
* Version Independent ID: 1627ee5d-f1d1-bb0e-4edb-1751b026adef
* Content: [Installing HID clients](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/installing-hid-clients)
* Content Source: [windows-driver-docs-pr/hid/installing-hid-clients.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/installing-hid-clients.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @LarryK348 
I've changed it to point to https://docs.microsoft.com/en-us/windows-hardware/drivers/install/hardware-ids. Should be on the live site shortly.
