### ISSUE TITLE
Missing entry for parameter 1 = 0x1236

### ISSUE THREAD

**Issue by HeinziAT** [MicrosoftDocs/windows-driver-docs#660]
Parameter 1 can be 0x1236, but it is not listed in the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de955911-dfbf-33b3-778a-767a5a578a0d
* Version Independent ID: 23fb5cbd-5f7d-f7ca-1622-5885020966c2
* Content: [Bug Check 0x1A MEMORY_MANAGEMENT](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x1a--memory-management)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Thanks, @HeinziAT 
@DOMARS can you please look into this?

**Comment by DOMARS** [comment]
@HeinziAT - I'm checking with the dev team to see if we can document this. Thanks for the interest in improving our docs!

**Comment by DOMARS** [comment]
@HeinziAT - I worked with the dev team to add an entry for 0x1236. Thanks for the request and your interest in improving our docs!
