### ISSUE TITLE
Link to valid dirids

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs#661]
This page should link to https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-dirids.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e8c3a59-5b16-8ea6-2ec4-943436c84ced
* Version Independent ID: 7ce374ce-9ea9-1f49-a071-f34cbd3a6ba1
* Content: [INF DestinationDirs Section](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/inf-destinationdirs-section)
* Content Source: [windows-driver-docs-pr/install/inf-destinationdirs-section.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/inf-destinationdirs-section.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks @jakeoshins Added the link in the See Also section. Feel free to edit the pages and make a commit. Just make sure you change the branch name by at least one character.
