### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by jakeoshins** [MicrosoftDocs/windows-driver-docs#662]
Stampinf Properties for Driver Projects above doesn't take you to the page that it should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3560b558-abf7-0b79-2931-7b4af312bdd6
* Version Independent ID: cabf6ea4-cd79-50d3-7d38-650556980229
* Content: [Stampinf](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/stampinf)
* Content Source: [windows-driver-docs-pr/devtest/stampinf.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/stampinf.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks @jakeoshins  
The link now points to Stampinf Properties for Driver Projects (https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/stampinf-properties-for-driver-projects).
