### ISSUE TITLE
Still references VS2015. Update for VS2017

### ISSUE THREAD

**Issue by trgardos** [MicrosoftDocs/windows-driver-docs#665]
On this page it says you must use VS2015 but on the WDK download page it says you must use VS2017. The instructions need to be updated for VS2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287160ad-f2a5-789a-2d7d-ff336514c11e
* Version Independent ID: a138162d-2b80-725b-212b-277bae8f177d
* Content: [Write a Universal Windows driver (UMDF 2) based on a template](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-umdf-driver-based-on-a-template#feedback)
* Content Source: [windows-driver-docs-pr/gettingstarted/writing-a-umdf-driver-based-on-a-template.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/writing-a-umdf-driver-based-on-a-template.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks for the note @trgardos I've updated the page to link to the central VS/WDK download page.
