### ISSUE TITLE
Undocumented Universal APIs

### ISSUE THREAD

**Issue by shaharlux** [MicrosoftDocs/windows-driver-docs#666]
Driver writers are encourage not to use undocumented APIs for good reasons. Are APIs listed in UniversalDDIs.xml and are not documented (not in the WDK and not in MSDN) can be used? For example, PsGetProcessExitProcessCalled? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5fa76b-6c2e-8f5e-7e96-ceb1c726842b
* Version Independent ID: 48a29c52-9907-9b1a-1dc2-3365c2d021d0
* Content: [Getting Started with Universal Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/getting-started-with-universal-drivers)
* Content Source: [windows-driver-docs-pr/develop/getting-started-with-universal-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/develop/getting-started-with-universal-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @shaharlux
We recommend that you run the ApiValidator tool to determine if your driver is universal. This tool runs automatically when you build your driver in Visual Studio.
