### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by megaabite** [MicrosoftDocs/windows-driver-docs#669]
INF for OSR USB FX - 

%DiskName% is not defined

missing sections:

[USB_Install.Wdf]
KmdfService=WINUSB, WinUsb_Install

[WinUsb_Install]
KmdfLibraryVersion=1.11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd1c106b-9499-4f15-f479-92537b5e4bed
* Version Independent ID: a10bfa35-ff3e-b169-0314-750dc5a28794
* Content: [WinUSB (Winusb.sys) Installation](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/winusb-installation)
* Content Source: [windows-driver-docs-pr/usbcon/winusb-installation.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/winusb-installation.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by PageWriter-MSFT** [comment]
Thanks @megaabite for catching that! I have updated the section. It should be live soon.

Page Writer
