### ISSUE TITLE
why do I get high ISR count on sdbus.sys?

### ISSUE THREAD

**Issue by mailinglists35** [MicrosoftDocs/windows-driver-docs#672]
etl trace https://www.pastefile.com/jooDiv
system is sluggish

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4639a65e-5ec8-2935-37fd-7e8e636f8546
* Version Independent ID: 24511b4a-afe6-ca90-dfda-855203d60af5
* Content: [SD Bus Driver Design Guide](https://docs.microsoft.com/en-us/windows-hardware/drivers/sd/)
* Content Source: [windows-driver-docs-pr/sd/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/sd/index.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thank you for reaching out to us. Unfortunately, we do not have the capability to provide help with your project.
