### ISSUE TITLE
Sharks Cove Developer's Guide

### ISSUE THREAD

**Issue by psanyi** [MicrosoftDocs/windows-driver-docs#681]
The Sharks Cove board is a really nice board for learning device driver development.
From where we can get the Developer's Guide for this board? The http://sharkscove.org address points to something else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50af20ac-0cfc-91d2-c85a-9a8d2d3465d9
* Version Independent ID: aff2225c-b05a-0e2c-8c4e-2e5ff7e20c26
* Content: [Sharks Cove hardware development board](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/sharks-cove-hardware-development-board)
* Content Source: [windows-driver-docs-pr/gettingstarted/sharks-cove-hardware-development-board.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/sharks-cove-hardware-development-board.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @psanyi thanks for the feedback.  Turns out that board is no longer supported.  Per your feedback, I've updated the doc page with a warning up top and a link to the current list.
