### ISSUE TITLE
"build environment window"

### ISSUE THREAD

**Issue by HollisTech** [MicrosoftDocs/windows-driver-docs#682]
This is a stale reference to the legacy WDk build environment and should be replaced with "developers command prompt" - the visual studio command line environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c749cf2a-785e-652b-d6ba-bc98476c00d9
* Version Independent ID: f03dcf80-4148-7fd6-3ee7-6064d6dc94ac
* Content: [Using Kernel Mode Performance Counters](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/using-kernel-mode-performance-counters)
* Content Source: [windows-driver-docs-pr/devtest/using-kernel-mode-performance-counters.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/using-kernel-mode-performance-counters.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by billlattimer** [comment]
@HollisTech thank you for calling this out; we've updated the article.
