### ISSUE TITLE
Links Error

### ISSUE THREAD

**Issue by hsebs** [MicrosoftDocs/windows-driver-docs#684]
All linked pages is removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4861605c-fe5b-f9fd-8809-3d9ecdb00b08
* Version Independent ID: 62acd7c4-6fe1-e55f-3442-89661c5bbbbf
* Content: [Introduction to Storage Class Drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/introduction-to-storage-class-drivers)
* Content Source: [windows-driver-docs-pr/storage/introduction-to-storage-class-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/storage/introduction-to-storage-class-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by billlattimer** [comment]
Thank you, @hsebs - all links corrected.
