### ISSUE TITLE
process -1

### ISSUE THREAD

**Issue by lawabider** [MicrosoftDocs/windows-driver-docs#693]
-1 for the process (as in !process -1 0) is mentioned but I don't think it says that this gets the current process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a818b121-53b3-c6a6-853a-2d9640912cc6
* Version Independent ID: 94c9600f-97aa-7a38-1423-ba76a9a32c42
* Content: [process](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-process)
* Content Source: [windows-driver-docs-pr/debugger/-process.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-process.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@lawabider - Thanks for this suggestion, I added wording to indicate that -1 displays the current process.
