### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs#694]
First sentence should give the path as %WindowsSdkDir% , not %WindowSdkDir% (note the trailing "s" on "Windows").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0514abad-23d7-8062-8745-283986118fb7
* Version Independent ID: 9135b600-0c52-19fc-03c7-6539ee54d51c
* Content: [ChkINF Command Syntax](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/chkinf-command-syntax)
* Content Source: [windows-driver-docs-pr/devtest/chkinf-command-syntax.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/chkinf-command-syntax.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @druske 
Fixed in source. Should be live within 24 hours.
