### ISSUE TITLE
Add sample coding 

### ISSUE THREAD

**Issue by jecalderon** [MicrosoftDocs/windows-driver-docs#695]
Add a C++ sample code with applications of the UVC device

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b13c7cbe-1d48-bd93-74c3-ccdac6e5ca6a
* Version Independent ID: ce835058-cbd3-6850-6995-eb645a4659ef
* Content: [USB Video Class Driver Overview](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/usb-video-class-driver-overview)
* Content Source: [windows-driver-docs-pr/stream/usb-video-class-driver-overview.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/stream/usb-video-class-driver-overview.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team.

I would recommend that you open an issue in the [Windows-driver-samples](https://github.com/microsoft/Windows-driver-samples) requesting a USB Video Class (UVC) driver sample.

You may also have success posting your UVC driver questions in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
