### ISSUE TITLE
"Vhflkm.lib" should be "vhfkm.lib"

### ISSUE THREAD

**Issue by azyobuzin** [MicrosoftDocs/windows-driver-docs#697]
In "Header and library requirements" chapter, there is a sentence "2. Link to Vhflkm.lib, included in the WDK." It seems to be a typing mistake and it should be "vhfkm.lib".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 88f27d9f-121d-b3f5-1671-73eb319f680e
* Version Independent ID: 0c61c804-1f2b-e62f-8d45-3322404905d3
* Content: [Write a HID source driver by using Virtual HID Framework (VHF)](https://docs.microsoft.com/ja-jp/windows-hardware/drivers/hid/virtual-hid-framework--vhf-)
* Content Source: [windows-driver-docs-pr/hid/virtual-hid-framework--vhf-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/hid/virtual-hid-framework--vhf-.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @azyobuzin 
@PageWriter-MSFT added you for visibility only.
