### ISSUE TITLE
Updated information needed

### ISSUE THREAD

**Issue by rgough71** [MicrosoftDocs/windows-driver-docs#700]
The link to the website hosting the ACPI specification is outdated- it should be https://www.uefi.org/specifications. Also, the latest revision available is 6.2a.
The pointer to the Microsoft ASL compiler also only seems to support ACPI 5.0. Perhaps there is another link to a newer ASL compiler?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7122297c-fce9-4241-abfd-8066856649a2
* Version Independent ID: 33c8a364-df32-5cc7-2bc5-cb66cf70911c
* Content: [Acpi.sys The Windows ACPI Driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/acpi-driver)
* Content Source: [windows-driver-docs-pr/kernel/acpi-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/acpi-driver.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team with your comments about the ACPI specification version.

The topic been updated with a new section:

[Microsoft ACPI source language (ASL) compiler](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/acpi-driver#microsoft-acpi-source-language-asl-compiler)

Currently, version 5.0 of the Microsoft ACPI source language (ASL) compiler supports the features in the Advanced Configuration and Power Interface Specification, Revision 5.0 (ACPI 5.0 specification).

You can check the version in your WDK installation at the following location with this command:

C:\Program Files (x86)\Windows Kits\10\Tools\x86\ACPIVerify>asl.exe /?
The first three lines of the command output should return the supported ACPI specification, for example:

Microsoft ACPI Source Language Assembler Version 5.0.0NT
Copyright (c) 1996,2014 Microsoft Corporation
Compliant with the ACPI 5.0 Specification
