### ISSUE TITLE
Exported Driver Support Routines

### ISSUE THREAD

**Issue by abhijeet085** [MicrosoftDocs/windows-driver-docs#703]
Will PCI Controller Drivers are part of export drivers,like SCSI port drivers???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a00526dc-0f04-4927-7e18-c07fd69ab9d5
* Version Independent ID: d87a7326-2a07-1eff-64c4-afcd8446c791
* Content: [User mode and kernel mode](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/user-mode-and-kernel-mode)
* Content Source: [windows-driver-docs-pr/gettingstarted/user-mode-and-kernel-mode.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/user-mode-and-kernel-mode.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @abhijeet085 
Thanks for the question, but as of right now we do not have any plans to create a PCI export driver.
All the best.
Eliot
