### ISSUE TITLE
Override EDID for ALL monitors

### ISSUE THREAD

**Issue by danegraphics** [MicrosoftDocs/windows-driver-docs#704]
Is it possible to have Windows use a single override EDID for all possible displays?

By that I mean, if I disconnect windows from one screen and connect it to another completely different monitor, can I have Windows apply the override EDID to that new monitor as well?

**Comment by mimisasouvanh** [comment]
Hi @danegraphics 
Here is an article on how to override a monitor EDIDs with INF: https://docs.microsoft.com/en-us/windows-hardware/drivers/display/overriding-monitor-edids
I hope that helps!
