### ISSUE TITLE
Extraneous text in the article

### ISSUE THREAD

**Issue by emuzychenko** [MicrosoftDocs/windows-driver-docs#708]
Extraneous text: "Before sending the request, the client loads the structure with values that indicate the preferred base address for the register".

The KSAUDIO_PRESENTATION_POSITION link points to KSRTAUDIO_HWREGISTER page.

There are several doc pages derived from RT hardware register pages and having the same errors. I think it is reasonable to perform keyword search in entire database to fix all, not only reported pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f076f741-2ad2-0a9e-4456-130acdc86b22
* Version Independent ID: 67b22358-634a-28f2-387a-ef34b2587c10
* Content: [KSPROPERTY\_RTAUDIO\_PRESENTATION\_POSITION](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/ksproperty-rtaudio-presentation-position)
* Content Source: [windows-driver-docs-pr/audio/ksproperty-rtaudio-presentation-position.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/ksproperty-rtaudio-presentation-position.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
I searched and found one last incorrect structure description in the audio docs that is now corrected.

There is one KSPROP where the base register is actually set, so that reference to the base address for the register, remains. 

Changes should be live in a day or so.
