### ISSUE TITLE
Building a Basic v4 Printer Driver: build & install problems

### ISSUE THREAD

**Issue by sicklittlemonkey** [MicrosoftDocs/windows-driver-docs#710]
Major issue 1:
"follow the prompts in the Configure Devices wizard to set up a remote target computer"
Need more detail and or a link to other content here.
If you follow your nose it tries to setup a remote computer. (But you need to install stuff from the SDK on there.)
But that's for a kernel mode driver, right? Can we can debug a user mode print driver on the local machine?
I haven't got this to work yet.

Major issue 2:
"Type the name of the driver in the Optional Arguments field"
Which name of the driver? Which field does this match? In the Windows print driver list the names are like "Fabrikam 1234".
Or do you mean enter something like "MyV4PrintDriver" (without quotes)? If so, what is this matching to deploy the driver?
To the right of "Optional Arguments" there are two hyperlinks: "Devices" and "Printers".
Both hyperlinks go to a 404-type error page.
I haven't got this to work yet.

The following are other things I had to overcome to build the sample.
They may not relate directly to this documentation, but ideally a wizard-generated sample should "just work" out of the box.
Common pitfalls at least deserve notes or links to other documentation.

3. error MSB6004: The specified task executable location "\tracewpp.exe" is invalid.
Solution: Add the following to C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.Shared.Props
  &lt;PropertyGroup&gt;
    &lt;WDKBinRoot Condition="'$(WDKBinRoot)' == ''"&gt;$(WindowsSdkDir)bin&lt;/WDKBinRoot&gt;
    &lt;WDKBinRoot_x86&gt;$(WDKBinRoot)\x86&lt;/WDKBinRoot_x86&gt;
    &lt;WDKBinRoot_x64&gt;$(WDKBinRoot)\x64&lt;/WDKBinRoot_x64&gt;
  &lt;/PropertyGroup&gt;

4. 1&gt;tracewpp : error wpp: (FileFinder::FindOnPath) File defaultwpp.ini not found
Solution: Change the target Windows SDK version to 10.0.16299.0. The 2 others I have (including latest) cause the error above.

5. 1&gt;x64\Debug\inf2catOutput.log : Inf2Cat error -2: "Inf2Cat, signability test failed." Double click to see the tool output.
22.9.7: DriverVer set to a date in the future (postdated DriverVer not allowed) in MyV4PrintDriver\MyV4PrintDriver.inf.
Solution: Enable Inf2Cat Use Local Time in project settings. (Yes (/uselocaltime))
We don't all live in the US.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227ceb38-396a-aa19-6304-be3df9b0ca08
* Version Independent ID: 2f34593f-aa20-384a-b1bb-c8a962ec4706
* Content: [Building a Basic v4 Printer Driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/print/building-a-basic-v4-printer-driver)
* Content Source: [windows-driver-docs-pr/print/building-a-basic-v4-printer-driver.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/print/building-a-basic-v4-printer-driver.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tanuj101** [comment]
@sicklittlemonkey Were you able to develop the Virtual Printer Driver that you desired? Is the code available?

**Comment by sicklittlemonkey** [comment]
@tanuj101 I can't say much for commercial reasons, but as you can see, this documentation is not very helpful for beginners.

**Comment by tanuj101** [comment]
Ah okay thanks for responding :)

**Comment by barrygolden** [comment]
Adding the detailed feedback above to an internal work item to overhaul and update the **Building a Basic v4 Printer Driver** topic.
