### ISSUE TITLE
FwpStreamInjectAsync0 

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/windows-driver-docs#711]
FwpStreamInjectAsync0 是不是少写个s, 应该是：FwpsStreamInjectAsync0。 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: be60f1ba-c556-06ba-e5f7-b7993f988ee5
* Version Independent ID: 45593f0c-153a-1a2b-4fb7-112139aa3ca5
* Content: [Stream Inspection](https://docs.microsoft.com/zh-cn/windows-hardware/drivers/network/stream-inspection)
* Content Source: [windows-driver-docs-pr/network/stream-inspection.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/stream-inspection.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @kouzhudong , I think what you're saying is that there is a typo on the doc. I'll go ahead and fix that, so thanks for pointing it out. Please let us know if you have any other questions.
