### ISSUE TITLE
Please be specific about requirements for each OS

### ISSUE THREAD

**Issue by adc68** [MicrosoftDocs/windows-driver-docs#713]
For example, server 2012 and 2012 R2 are not mentioned, however it says "Windows Server does not load attestation signed drivers".  It's ambiguous whether this applies to Server 2016 only due to the preceding sentence.

What would be very useful is a table of each OS from Windows 7 onwards and Server from 2008 onwards with the requirements for each.  What would be even more useful is if Server WOULD load attestation signed drivers, at least for certain class of drivers (not hardware-related, e.g. NDIS LWF).  Any exceptions about requirements for different types of drivers need to be here.  We need to be able to find all signing requirements for all the platforms we need to support in one place.  At the moment the requirements seem to be spread over many web pages, and aren't always consistent with each other or unambiguous.  I can only imagine the pain this causes countless kernel driver devs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb19d33-8f4c-f379-b645-938a746c5615
* Version Independent ID: 8efb9fb4-1e9a-1a8a-994b-450495449e15
* Content: [Driver Signing Policy](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/kernel-mode-code-signing-policy--windows-vista-and-later-)
* Content Source: [windows-driver-docs-pr/install/kernel-mode-code-signing-policy--windows-vista-and-later-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/kernel-mode-code-signing-policy--windows-vista-and-later-.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks for the feedback @adc68 and apologies for the delay.  We've updated the page in question, hopefully it's a bit clearer now.
