### ISSUE TITLE
Missing entry for parameter 1 having value 

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#716]
Parameter 1 can be 0x0000003f, but it is not listed in the table.
A DMP file I've analyzed having such a value for the BCP1 parameter reported the following additional information
ADDITIONAL_DEBUG_TEXT:  Memory Manager detected corruption of a pagefile page while performing an in-page operation.
The data read from storage does not match the original data written.
This indicates the data was corrupted by the storage stack, or device hardware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de955911-dfbf-33b3-778a-767a5a578a0d
* Version Independent ID: 23fb5cbd-5f7d-f7ca-1622-5885020966c2
* Content: [Bug Check 0x1A MEMORY_MANAGEMENT](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x1a--memory-management)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x1a--memory-management.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - I'm checking with the dev team to see if we can document this. Thanks for the interest in improving our docs!

**Comment by DOMARS** [comment]
@LuigiBruno - I worked with the dev team to add an entry for 0x3f. Thanks for the request and your interest in improving our docs!
