### ISSUE TITLE
KSCAMERA_EXTENDEDPROP_OPTIMIZATIONHINT DDI does not document Windows 10 options.

### ISSUE THREAD

**Issue by JoelCorley** [MicrosoftDocs/windows-driver-docs#725]
In Windows 10 this DDI was extended to define 3 new bits:
KSCAMERA_EXTENDEDPROP_OPTIMIZATION_QUALITY
KSCAMERA_EXTENDEDPROP_OPTIMIZATION_LATENCY
KSCAMERA_EXTENDEDPROP_OPTIMIZATION_POWER

Valid combinations include 0, 1 or 2 of these flags along with either the PHOTO or VIDEO definition.  The flags ask that the driver try to optimize for one or two of these factors at the expense of the others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8aaffa5-c8d3-7664-344f-a079f3549d1d
* Version Independent ID: 0abd8f1c-be34-3635-30ba-f74efebb3688
* Content: [KSPROPERTY\_CAMERACONTROL\_EXTENDED\_OPTIMIZATIONHINT](https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/ksproperty-cameracontrol-extended-optimizationhint#feedback)
* Content Source: [windows-driver-docs-pr/stream/ksproperty-cameracontrol-extended-optimizationhint.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/stream/ksproperty-cameracontrol-extended-optimizationhint.md)
* Product: **windows-hardware**
* GitHub Login: @barrygolden
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @JoelCorley 
@barrygolden I believe that this bug's for you!

**Comment by barrygolden** [comment]
Moving this issue to an internal work item.
