### ISSUE TITLE
setting-up-a-network-debugging-connection: links to supported-ethernet-nics-for-network-kernel-debugging-in-windows<...>

### ISSUE THREAD

**Issue by kITerE** [MicrosoftDocs/windows-driver-docs#729]
Not applied formatting to links:

```
Setting Up the Target Computer


1.  Verify that the target computer has a supported network adapter. See these topics for more information.


    - [Supported Ethernet NICs for Network Kernel Debugging in Windows 8.1](supported-ethernet-nics-for-network-kernel-debugging-in-windows-8-1.md)

    - [Supported Ethernet NICs for Network Kernel Debugging in Windows 10](supported-ethernet-nics-for-network-kernel-debugging-in-windows-10.md)
```

Problem only for docs.microsoft.com (https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection#span-idsettingupthetargetcomputerspanspan-idsettingupthetargetcomputerspanspan-idsettingupthetargetcomputerspansetting-up-the-target-computer), github.com displays links correctly(https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection.md#setting-up-the-target-computer)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed06dd7d-eb22-42e1-a2ab-8bf436d3e231
* Version Independent ID: 2152b739-52bf-e743-2f6a-ae7a24cbaf27
* Content: [Setting Up KDNET Network Kernel Debugging Manually](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection#span-idsettingupthetargetcomputerspanspan-idsettingupthetargetcomputerspanspan-idsettingupthetargetcomputerspansetting-up-the-target-computer)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Thanks for pointing this out, @kITerE 
@DOMARS I think I made the correct fixes in the eliotdriver VSTS branch. Please review and if they look good, merge to master.

**Comment by DOMARS** [comment]
Assigning back to Eliot, as this fixes he has proposed look good.

**Comment by EliotSeattle** [comment]
Note to self: Close Git Issues that were completed 6 months prior. Ugh.
