### ISSUE TITLE
HTML tags present

### ISSUE THREAD

**Issue by MarcoPeretti** [MicrosoftDocs/windows-driver-docs#732]
The doc for ExAllocatePoolWithTag() shows HTML tags (3rd parameter).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c180ac23-5c48-8539-fecb-d344ff345315
* Version Independent ID: a3e9ca80-4809-2af5-6bc6-3511eebef351
* Content: [C30033](https://docs.microsoft.com/en-gb/windows-hardware/drivers/devtest/30033-executable-allocation-detected-with-pool-nx-optin)
* Content Source: [windows-driver-docs-pr/devtest/30033-executable-allocation-detected-with-pool-nx-optin.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/30033-executable-allocation-detected-with-pool-nx-optin.md)
* Product: **windows-hardware**
* GitHub Login: @aahill
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Oopsies. Looks like our migration script from XML to markdown was less than perfect. But this instance is fixed now. Thanks @MarcoPeretti for the catch. I'll create a task to search for more of these bad boys.
