### ISSUE TITLE
Explain what 'Args' is

### ISSUE THREAD

**Issue by jordanrh1** [MicrosoftDocs/windows-driver-docs#739]
Explain how to interpret the 'Args' output

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e5e090-b683-7af9-403a-7a4ea993c2b3
* Version Independent ID: 06f64a3c-e9a1-9fdd-3427-317f3b2db213
* Content: [irp extension command](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-irp#span-idddkirpdbgspanspan-idddkirpdbgspanparameters)
* Content Source: [windows-driver-docs-pr/debugger/-irp.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/-irp.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@jordanrh1 - Thanks for the input on adding additional information on the args for IRPs. As this becomes a complex topic, it is currently out of scope of the driver docs. We instead rely on outside books and resources. I added two that are helpful in working with IRPs to the topic.

- Developing Drivers with the Windows Driver Foundation Guy Smith and Penny Orwick
- Windows Internals by Mark E. Russinovich, David A. Solomon and Alex Ionescu

The driver development community also relies on vendors such as OSR who provide detailed information on driver internals, such as IRPs.

Thanks again for the input and thanks for your interest in improving our docs.
