### ISSUE TITLE
Add a link to the Windows SDK

### ISSUE THREAD

**Issue by RobertBernstein-MSFT** [MicrosoftDocs/windows-driver-docs#740]
Please add a link to the Microsoft Windows SDK or to https://msdn.microsoft.com/library/windows/desktop/ms679297, for example, in the sentence starting with "For complete documentation of this routine", above.  The user shouldn't have to manually search for this content.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86e93656-2366-2f56-0db4-6e1b96d8a21c
* Version Independent ID: aa9c59c0-3465-acb2-6127-f115991c531a
* Content: [Breaking Into the Debugger](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/breaking-into-the-debugger)
* Content Source: [windows-driver-docs-pr/debugger/breaking-into-the-debugger.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/breaking-into-the-debugger.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by EliotSeattle** [comment]
Thanks, @RobertBernstein-MSFT 
@DOMARS can you please add some beautiful reference links?

**Comment by DOMARS** [comment]
@RobertBernstein-MSFT - I added a link to the DebugBreak function, thanks for the suggestion.
Feel free to use the pencil on the topic to submit a PR for fixes like this in the future.
Thanks again for your interest in improving the docs.

**Comment by RobertBernstein** [comment]
Will do, @DOMARS .  Thanks!
