### ISSUE TITLE
Documentation wrong for Visual Studio 2017

### ISSUE THREAD

**Issue by LarryK348** [MicrosoftDocs/windows-driver-docs#742]
Step 1 (at least) is incorrect and should be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d8f973-bcf8-5af8-5a4f-f8fd9e62b411
* Version Independent ID: 258da38c-1e73-572f-a20d-a9354e3d9327
* Content: [How to write your first USB client driver (UMDF)](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/implement-driver-entry-for-a-usb-driver--umdf-)
* Content Source: [windows-driver-docs-pr/usbcon/implement-driver-entry-for-a-usb-driver--umdf-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/implement-driver-entry-for-a-usb-driver--umdf-.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @LarryK348 for spotting this. With >40,000 topics, we miss updating a couple here and there.
@PageWriter-MSFT can you scope out the work to get the steps correct for VS 2017? Maybe one of the other team members can help you out on this one. Thanks!

**Comment by duncanmacmichael** [comment]
Hi @LarryK348, apologies for the delay on this. I've updated this topic and its sibling KMDF topic for Visual Studio 2019; look for those changes shortly after I post this. Thanks for helping to improve the docs!
