### ISSUE TITLE
Guidance to use DIFx appears to contradict deprecation

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-driver-docs#743]
According to [this page](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/difx-guidelines), "Starting in Windows 10 Version 1607 (Redstone 1), the Driver Install Frameworks (DIFx) tools are no longer included in the WDK. Instead, we recommend providing your driver as a standalone package that doesn't require an installer, ideally through Windows Update."

This page says, "An installation application should use the DIFx tools if they provide the functionality that the installation application requires."

It would be helpful if documentation could be updated to provide an unambiguous and consistent direction for driver developers tasked with creating installers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ccc69b6-caab-763b-22d3-b3815eb4e54c
* Version Independent ID: 3b05505b-223b-31a5-74aa-b143d24c166d
* Content: [SetupAPI Functions that Simplify Driver Installation](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/setupapi-functions-that-simplify-driver-installation)
* Content Source: [windows-driver-docs-pr/install/setupapi-functions-that-simplify-driver-installation.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/setupapi-functions-that-simplify-driver-installation.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks for the feedback @druske I've removed the reference to Difx.  The update will be live momentarily
