### ISSUE TITLE
Test issue for networking

### ISSUE THREAD

**Issue by duncanmacmichael** [MicrosoftDocs/windows-driver-docs#748]
Test Testerson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15203e26-89c8-6899-1d87-489e250272b1
* Version Independent ID: 041fb44e-5a94-7a65-f4fc-ad0ef29cfbde
* Content: [Network Driver Design Guide](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/index)
* Content Source: [windows-driver-docs-pr/network/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/index.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @duncanmacmichael, thanks for opening this issue. @duncanmacmichael, can you take a look?
