### ISSUE TITLE
One more test issue

### ISSUE THREAD

**Issue by duncanmacmichael** [MicrosoftDocs/windows-driver-docs#749]
Testing in a third content area, please ignore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cbad219-645b-4478-e284-8136cb65f210
* Version Independent ID: b8628dca-0242-92c3-5830-b0c965c89438
* Content: [Universal Serial Bus (USB)](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/)
* Content Source: [windows-driver-docs-pr/usbcon/index.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/usbcon/index.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @duncanmacmichael, thanks for opening this issue. @PageWriter-MSFT, can you take a look?
