### ISSUE TITLE
Wrong kd command

### ISSUE THREAD

**Issue by csujedihy** [MicrosoftDocs/windows-driver-docs#758]
!ed nt!Kd_DEFAULT_MASK  0xFFFFFFFF
=&gt;
ed nt!Kd_DEFAULT_MASK  0xFFFFFFFF

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5abd01e-3c7e-11a8-a6c6-62bfba0ef8b6
* Version Independent ID: dceb81b3-b20f-91d1-85d0-fa68c762482b
* Content: [Debug Universal Drivers - Step-by-Step Lab (Echo Kernel Mode)](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-)
* Content Source: [windows-driver-docs-pr/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/debug-universal-drivers---step-by-step-lab--echo-kernel-mode-.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@csujedihy - Thanks for catching this. You may know that there is also a !ed extension command, but when I re-tested this step something seems to have changed with its behavior, so per your suggestion I changed it to use ed. I also added a step to display the memory using dd to confirm the flags is set. Thanks for your interest in improving the docs.
