### ISSUE TITLE
Update required for response body section in this doc

### ISSUE THREAD

**Issue by NileshMali1** [MicrosoftDocs/windows-driver-docs#840]
Hello,

The API returns empty response body with response code 202 (accepted). Would be good if API returns response body as { "commitStatus": "commitReceived" }.  Also, update the doc to reflect commitReceived instead of commitStarted if API gests modified to return commitStatus JSON.

Thanks,
NM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d4fba4-34f5-f000-fd4a-1acf9de277d0
* Version Independent ID: 638d0b07-faaa-1529-a6d5-3cd7a6b87838
* Content: [Commit a product submission](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/commit-a-product-submission)
* Content Source: [windows-driver-docs-pr/dashboard/commit-a-product-submission.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/dashboard/commit-a-product-submission.md)
* Product: **windows-hardware**
* GitHub Login: @balapv
* Microsoft Alias: **balapv**

**Comment by EliotSeattle** [comment]
Thanks, @NileshMali1, for filing this issue. I'll sync up with the product team and look into these.

**Comment by EliotSeattle** [comment]
Hi @NileshMali1. The product team has asked if you can supply the ProductIId & SubmissionId for the submission, as this could have a number of different causes. Feel free to send them to me at eliotgra @ microsoft . com if you're willing. Thank you.

**Comment by EliotSeattle** [comment]
Closing for lack of a response. If this is in error, @NileshMali1, please reopen. Thanks!
