### ISSUE TITLE
Broken Link to whitepaper

### ISSUE THREAD

**Issue by caseysmithrc** [MicrosoftDocs/windows-driver-docs#842]
The following link needs to be updated. the reference to  Digital Signatures for Kernel Modules on Systems Running Windows Vista =&gt;  http://go.microsoft.com/fwlink/p/?linkid=184997 no longer resolves.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ca4e93-a34c-abbc-0ebc-9b5195378b20
* Version Independent ID: f2e19c4f-44cf-e0d4-2143-1e2129c582c9
* Content: [Driver Signing](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/driver-signing)
* Content Source: [windows-driver-docs-pr/install/driver-signing.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/driver-signing.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks @caseysmithrc I've updated the link.  Updates should be live in a few minutes.
