### ISSUE TITLE
How do I get symchk?

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-driver-docs#843]
Where do I find it and how do download it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac689426-48f2-94f4-b2f1-d4936f162db0
* Version Independent ID: 6e2ca765-d0a2-1a69-a183-e43c6c3f85f4
* Content: [Using SymChk](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/using-symchk)
* Content Source: [windows-driver-docs-pr/debugger/using-symchk.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/using-symchk.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@dotMorten - symchk and the other debugger tools ship as part of the debugger. See this topic for information on that:

[Download Debugging Tools for Windows](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)

Once that is installed it is available in this directory for 64 bit Windows.

C:\Program Files (x86)\Windows Kits\10\Debuggers\x64

I will work to add this information to this topic.

**Comment by DOMARS** [comment]
@dotMorten - I added information on downloading symchk as part of the debugger tools to this topic.
Thanks for the input on this topic.

**Comment by Foadsf** [comment]
@DOMARS  still not clear how the `symchk` tool should b installed. I followed the [instructions](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools) on the page to install WinDbg from Microsoft Store. I have no clue where software is installed now, nor how to find the `symchk` executable!
