### ISSUE TITLE
Missing link to difficult to find "Microsoft Windows SDK documentation"

### ISSUE THREAD

**Issue by rodwiddowson** [MicrosoftDocs/windows-driver-docs#847]
"For more information about opportunistic locks and about the FSCTL_REQUEST_OPLOCK control code, see the Microsoft Windows SDK documentation." 

A hyperlink here might be useful since putting FSCTL_REQUEST_OPLOCK or "Microsoft Windows SDK documentation" into the search bar doesn't produce anything

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215a96fa-bb05-5ab7-962f-168b7db624be
* Version Independent ID: 45efd2a5-e340-f008-8590-86fec2ec81a7
* Content: [FSCTL\_REQUEST\_OPLOCK control code](https://docs.microsoft.com/en-gb/windows-hardware/drivers/ifs/fsctl-request-oplock)
* Content Source: [windows-driver-docs-pr/ifs/fsctl-request-oplock.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/ifs/fsctl-request-oplock.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for pointing this out, @rodwiddowson. I changed the paragraph to:

For more information about opportunistic locks, see [Opportunistic Locks](https://docs.microsoft.com/windows/desktop/FileIO/opportunistic-locks) in the Windows Desktop documentation. For more information about user mode OPLOCK controls, see [File Management Control Codes](https://docs.microsoft.com/windows/desktop/FileIO/file-management-control-codes) in the Windows Desktop documentation.
