### ISSUE TITLE
Tracking the Lock

### ISSUE THREAD

**Issue by TimTheITGuy** [MicrosoftDocs/windows-driver-docs#850]
How do we view what vendor software (PID/image path/service name/etc.) has locked the TWAIN/WIA drivers so we can manually terminate the process or take steps to prevent its launching?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781fa6d5-2787-118e-376d-5472e49546e2
* Version Independent ID: 8d186097-e566-0741-dbf2-1d93dbec6be1
* Content: [WIA-TWAIN Locking](https://docs.microsoft.com/en-us/windows-hardware/drivers/image/wia-twain-locking)
* Content Source: [windows-driver-docs-pr/image/wia-twain-locking.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/image/wia-twain-locking.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. You may have success posting your question about vendor software locking TWAIN/WIA drivers in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[Hardware and Application Developers on Q&A](https://docs.microsoft.com/answers/topics/windows-hardware-wdk-general.html)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
