### ISSUE TITLE
Section "Should You Always Write a WDM Driver?"

### ISSUE THREAD

**Issue by kyanha** [MicrosoftDocs/windows-driver-docs#852]
The information in this section appears to conflict with at least some of the information in "Choosing a Driver Model" at https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/choosing-a-driver-model (in the "Choosing a Driver Model for a Software Driver" section).  At this time, from what I can see from that other documentation, most kernel-mode drivers should be using KMDF unless they either need to be aware of PNP or power events and need access to information that KMDF doesn't provide, or if they need to use functionality that isn't available in the simpler KMDF interfaces.  If this is incorrect, then the documentation is apparently unclear; in any case, the content of the "Should You Always Write a WDM Driver?" needs to be overhauled to no longer refer to cross-platform source code compiling support for e.g. Windows 98 and ME (since there has been no commercial version of Windows built from the non-NT codebase since before Windows XP, which itself is no longer supported).

However, if I'm incorrect in what I'm given to understand is correct, please keep it the way it is [and maybe let me know so I don't make a fool of myself in the future? Thanks...].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba088928-98eb-72b4-45ad-e6da039e671c
* Version Independent ID: 26ffae7e-c9f7-e6a6-f661-cd58a7be7a04
* Content: [Introduction to WDM](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/introduction-to-wdm)
* Content Source: [windows-driver-docs-pr/kernel/introduction-to-wdm.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/introduction-to-wdm.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @kyanha thanks so much for the feedback, and my apologies that we didn't get to you until now.  That's great feedback about the Intro to WDM page.  I just revised the page to reflect the modern guidance.  As you correctly surmised, KMDF is the preferred way to go.

While I was looking at https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/choosing-a-driver-model per your mention, I also found a recurring typo that had been in there for several years.

All this should be live in the next hour or so.  Thanks again!
