### ISSUE TITLE
Display-Only Display Devices can use UMDF

### ISSUE THREAD

**Issue by GreenReaper** [MicrosoftDocs/windows-driver-docs#854]
"display drivers ... cannot be UMDF drivers." should be clarified to explain that it refers to "Full" display devices not "Display-Only" (per DXDiag Device Type) as DisplayLink USB-based displays (dlidusb.dll, dlidusb2.dll) are UMDF.

This is equivalent to or a subset of the "Indirect Display driver model" which states it is implemented via UMDF:
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/indirect-display-driver-model-overview

Miracast adapters also appear to be Display-Only Display Devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7146b538-4090-2c94-3c50-5fbdf672c24b
* Version Independent ID: 3a391651-2375-d4ea-099b-c0b96474b790
* Content: [Overview of UMDF](https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/overview-of-the-umdf)
* Content Source: [windows-driver-docs-pr/wdf/overview-of-the-umdf.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/wdf/overview-of-the-umdf.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
Hi @GreenReaper 

I have updated the Overview of UMDF topic with "File system drivers, display drivers (for full display devices, not display-only display devices), and print drivers cannot be UMDF drivers." in the second paragraph. This should show up in a couple of days. Thank you for your suggestion!

Best, 
Mimi
