### ISSUE TITLE
AcpiGenFx was built against the ".NETFramework,Version=v4.6" framework.

### ISSUE THREAD

**Issue by ChrisSchaller** [MicrosoftDocs/windows-driver-docs#856]
Please update the content to reflect that the current WDK requires .Net 4.6, or at least to mention that the target framework of your console project needs to match the framework that AcpiGenFx was compiled against. The wording in this document is just very strong suggesting that it will fail if you do not select 4.5 as the target.

This is the warning message when I run with 4.5 (yes it is obvious, but if you do not have warnings as errors enabled or you have warnings disabled it is easy to miss.)

The primary reference "AcpiGenFx" could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".	SSDTSample			

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16299ebf-80ed-f09f-d0c0-4cda742f579e
* Version Independent ID: 8e45d880-93f8-4c85-81e6-b1d5dbe78ab6
* Content: [Generate ACPI tables by using AcpiGenFx](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/generate-acpi-tables-by-using-acpigenfx)
* Content Source: [windows-driver-docs-pr/bringup/generate-acpi-tables-by-using-acpigenfx.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/bringup/generate-acpi-tables-by-using-acpigenfx.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @ChrisSchaller. @barrygolden, can you please rectify this as soon as you have time?  Thanks!

**Comment by barrygolden** [comment]
Adding the detailed feedback above to an internal work item to update the .NET Framework version in the **Generate ACPI tables by using AcpiGenFx** topic.
