### ISSUE TITLE
problem regarding Printing files to the WSD sample

### ISSUE THREAD

**Issue by tobgyeltashi** [MicrosoftDocs/windows-driver-docs#857]
Hello,

I’m having problem in printing files to the WSD sample. As per the procedure given in the guidelines, I installed the driver and sample app. I used 3D builder to built a model and wanted to print it. But I couldn’t find the files sent to the printer from the 3D builder gone to the C:\Windows\Temp folder which is suppose to be the zip files.

What will be the reason for not getting the zip files in C:\Windows\Temp folder?
Your support and guidance will be appreciated.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0093da-2900-67f1-8fd6-766772a72031
* Version Independent ID: 696c5cee-ad21-8d40-28b3-4aefae492878
* Content: [Print files to the WSD sample](https://docs.microsoft.com/en-us/windows-hardware/drivers/3dprint/print-files-to-the-wsd-sample)
* Content Source: [windows-driver-docs-pr/3dprint/print-files-to-the-wsd-sample.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/3dprint/print-files-to-the-wsd-sample.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. 

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
