### ISSUE TITLE
Install the driver on a Windows 10 machine

### ISSUE THREAD

**Issue by tobgyeltashi** [MicrosoftDocs/windows-driver-docs#859]
Hello, 
I am using Velleman K8200 compatible 3D printer. To install the print driver included in the 3D printing SDK, from where can I access to the driver's .inf file for the printer that I'm using to install the driver which is compatible to Velleman K8200 printer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd30df-2352-73f8-872c-867bec7b68c9
* Version Independent ID: 3043bc20-0c1a-3917-bb2d-8247586ac909
* Content: [Install the driver and sample app](https://docs.microsoft.com/en-us/windows-hardware/drivers/3dprint/install-the-driver-and-sample-app)
* Content Source: [windows-driver-docs-pr/3dprint/install-the-driver-and-sample-app.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/3dprint/install-the-driver-and-sample-app.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tobgyeltashi** [comment]
Hello,
I’m having a problem in printing files to the WSD sample. As per the procedure is given in the guidelines, I installed the driver and sample app. I used 3D builder to build a model and wanted to print it. But I couldn’t find the files sent to the printer from the 3D builder gone to the C:\Windows\Temp folder which is supposed to be the zip files. 
What could be the reason for not getting it right? Your support will be helpful.
Thank you

**Comment by barrygolden** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.

You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.

[MSDN Windows Hardware WDK and Driver Development forum](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)

[NTDEV forum at OSR Online](https://www.osronline.com/showlists.cfm?list=ntdev)
