### ISSUE TITLE
Broken links in content

### ISSUE THREAD

**Issue by niderost** [MicrosoftDocs/windows-driver-docs#864]
Links in this content are broken. E.g. the link "class installers", "co-installers" and "device installataion applications" link to pages on MSDN (https://msdn.microsoft.com/library/windows/hardware/ff556274, https://msdn.microsoft.com/library/windows/hardware/ff556277) that don't exist any longer. Instead they should link to pages on DOCS (https://docs.microsoft.com/en-us/windows-hardware/drivers/install/writing-a-co-installer, https://docs.microsoft.com/en-us/windows-hardware/drivers/install/writing-a-device-installation-application). Information about what a class installer is can be found here: https://msdn.microsoft.com/en-us/library/windows/hardware/ff554009.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d90183-dde8-39b2-4d0c-72f5e81d74a9
* Version Independent ID: f826c7db-2fcf-cbde-97b6-b3ec58cb0fa1
* Content: [SetupAPI](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/setupapi)
* Content Source: [windows-driver-docs-pr/install/setupapi.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/setupapi.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks for the suggestion, @niderost. I've updated the page and the changes will be live within the hour.  Please feel free to click **Edit** from pages on docs.ms next time if you would like to propose changes in a pull request.
