### ISSUE TITLE
"enumerator" doesn't go anywhere useful

### ISSUE THREAD

**Issue by kyanha** [MicrosoftDocs/windows-driver-docs#866]
The link to "enumerator" goes to the Windows Driver Kit root, not to the glossary.  This probably means that the glossary page isn't actually where this document has linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d12a22f-cf0a-53e1-e276-ac12ad5e0da9
* Version Independent ID: d42e71ea-3561-bbb3-5041-3d69136540fb
* Content: [Device Identification Strings](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-identification-strings)
* Content Source: [windows-driver-docs-pr/install/device-identification-strings.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/device-identification-strings.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @kyanha 
I added the definition from the retired glossary page. should be live later today.
