### ISSUE TITLE
Clearly explained

### ISSUE THREAD

**Issue by cengizIO** [MicrosoftDocs/windows-driver-docs#867]
Thanks for the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e17d9b3-9e6b-df00-e249-38a0cd5e1099
* Version Independent ID: 83d9bce2-8b16-812f-d587-61527d4eba50
* Content: [System Sleeping States](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/system-sleeping-states)
* Content Source: [windows-driver-docs-pr/kernel/system-sleeping-states.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/system-sleeping-states.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @cengizIO. Glad we could help!
