### ISSUE TITLE
pheap-buggy.* download

### ISSUE THREAD

**Issue by katdti** [MicrosoftDocs/windows-driver-docs#868]
Where can I download pheap-buggy.* so I could reproduce the streps described in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bce662c-3008-33e2-1c20-6e4cc7c3ccf9
* Version Independent ID: 0a88c1af-129e-cf79-acd1-8c14a81e4ce3
* Content: [Example 12 Using Page Heap Verification to Find a Bug](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/example-12---using-page-heap-verification-to-find-a-bug)
* Content Source: [windows-driver-docs-pr/debugger/example-12---using-page-heap-verification-to-find-a-bug.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/example-12---using-page-heap-verification-to-find-a-bug.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
The lab describes pheap-buggy as a "fictitious" application, so I don't think there is a download for it.

I did do some testing, and I think the code, would look something like this:
```cpp
// pheap-buggy.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <windows.h>
#include <string>


void CorruptAfterEnd()
{
                printf_s("Running code to cause a heap block error\n");
                PVOID BLOCK;
                PVOID Heap;
                Heap = HeapCreate(0, 0, 0);
                BLOCK = HeapAlloc (Heap,0,0x100);
                *((PCHAR)BLOCK + 0x100) = 0;
}

int main(int argc, char *argv[])
{
                if (argc > 1) 
                {
                                std::string arg1(argv[1]);
                                if (arg1 == "CorruptAfterEnd")
                                {
                                                CorruptAfterEnd();
                                }
                }
                printf_s("Type x and press enter cause exception to occur\n");
                char testChar =getchar();
                if (testChar == 'x')
                {
                                CorruptAfterEnd();
                }
                return 0;
}
````
A few notes on the lab flow. I belive that the this text:
```
===========================================================
VERIFIER STOP 00000008: pid 0xAA0: corrupted suffix pattern
```
 Indicates that in addition to the gflags being set as described, that Application Verifier was also enabled.

If you wish to replicate that exact output you would need to run appverif from a command window and enable basic application verification for the pheap-buggy app.

Good luck in your heap pool debugging and thanks for your interest in our documentation.
