### ISSUE TITLE
Table Numbers

### ISSUE THREAD

**Issue by SolarGranola** [MicrosoftDocs/windows-driver-docs#870]
In Table 1, the table title should say 1803 not 1809

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6c30c68-d0cb-7a62-f154-e6ab40c0119e
* Version Independent ID: 4dec63f5-fc8f-b8ea-117f-ddeed34bfc31
* Content: [What's new in driver development](https://docs.microsoft.com/en-us/windows-hardware/drivers/what-s-new-in-driver-development)
* Content Source: [windows-driver-docs-pr/what-s-new-in-driver-development.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/what-s-new-in-driver-development.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @SolarGranola for catching this. I made the fix in the source. Should be live later today.
