### ISSUE TITLE
Diagnostic quandary

### ISSUE THREAD

**Issue by markyoung143** [MicrosoftDocs/windows-driver-docs#879]
What does 1&08 mean? I want to decide it and other variants as I sometimes need to the associate a devicepath with a ctrl's PCI bus/dev/fund or to associate or find a drives slot or port. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c5c7b52-24c3-5eb2-bd5e-ebb639590c48
* Version Independent ID: c1670409-850f-86d0-03ad-18fe3997820b
* Content: [Device Instance ID](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/device-instance-ids)
* Content Source: [windows-driver-docs-pr/install/device-instance-ids.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/device-instance-ids.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Hi @markyoung143, this value is essentially random. If you need to find a specific bus location, you can query [DEVPKEY_Device_LocationInfo](https://docs.microsoft.com/windows-hardware/drivers/install/devpkey-device-locationinfo
) or [DEVPKEY_Device_LocationPaths](https://docs.microsoft.com/windows-hardware/drivers/install/devpkey-device-locationpaths).
