### ISSUE TITLE
Geo

### ISSUE THREAD

**Issue by gplayer123** [MicrosoftDocs/windows-driver-docs#880]
on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d77677a1-6187-f77b-57ac-e67bb1f76fa2
* Version Independent ID: 8e9b5002-a835-bf3c-0ad1-c1313f2dfc84
* Content: [Driver Packages](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/driver-packages)
* Content Source: [windows-driver-docs-pr/install/driver-packages.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/driver-packages.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Hi @gplayer123.
I don't see a doc issue reported here, so I'm going to close this issue. If you meant to type more than "on" or there's something else to report, please reopen this or create a new issue. Thanks!
