### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by thkaw** [MicrosoftDocs/windows-driver-docs#883]
Missing link in USB and Network devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4ed803f-575f-b513-b210-ab308cab3eed
* Version Independent ID: e4a318a0-1490-bc72-4228-1768cd9bed9e
* Content: [Device and Driver Technologies](https://docs.microsoft.com/en-us/windows-hardware/drivers/device-and-driver-technologies)
* Content Source: [windows-driver-docs-pr/device-and-driver-technologies.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/device-and-driver-technologies.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks for spotting this @thkaw, the fix will be live in a few minutes.
