### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by thkaw** [MicrosoftDocs/windows-driver-docs#884]
Missing link Device and driver technologies 
Is correct link @ https://docs.microsoft.com/en-us/windows-hardware/drivers/device-and-driver-technologies ?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 9dcfd3e9-3d43-1140-cc8c-fe5f9e915a9d
* Version Independent ID: 4f665db9-d2bf-3720-f7a0-4176f796438a
* Content: [Choosing a driver model](https://docs.microsoft.com/zh-tw/windows-hardware/drivers/gettingstarted/choosing-a-driver-model)
* Content Source: [windows-driver-docs-pr/gettingstarted/choosing-a-driver-model.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/gettingstarted/choosing-a-driver-model.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Fixed in source. Thanks, @thkaw!
