### ISSUE TITLE
NDIS_SRIOV_CAPABILITIES

### ISSUE THREAD

**Issue by robert1859** [MicrosoftDocs/windows-driver-docs#885]
Hi,
You mention that MaxNumVPorts and MaxNumVFs are members of NDIS_SRIOV_CAPABILITIES structure but I think that is not correct and bit misleading. Did you mean NDIS_NIC_SWITCH_CAPABILITIES?

Regards,
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e9e77cf-56e5-9eab-f449-e60ef2c97f0e
* Version Independent ID: 25e1df3b-8bab-d0e6-cb77-3ec4c2045025
* Content: [Nondefault Virtual Ports and VMQ](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/nondefault-virtual-ports-and-vmq)
* Content Source: [windows-driver-docs-pr/network/nondefault-virtual-ports-and-vmq.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/nondefault-virtual-ports-and-vmq.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @robert1859 , it looks like you're right. The preceding paragraph did talk about registering SR-IOV capabilities, but then the text switched tracks to talk about NDIS_NIC_SWITCH_CAPABILITIES members. I've corrected links to the correct structure and the changes should be live later today. Thanks for pointing this out!
