### ISSUE TITLE
Windows Real Time Scanner Driver

### ISSUE THREAD

**Issue by AkshayUsha** [MicrosoftDocs/windows-driver-docs#914]
Hello I want to Real Time Scanner Driver Source Code for Developing Any Buddy Help Me ?

**Comment by EliotSeattle** [comment]
Hi @AkshayUsha 
Can you please explain a little more. I am sorry, but I don't understand your request.

**Comment by AkshayUsha** [comment]
i want to real time antivirus scanning driver source code

**Comment by EliotSeattle** [comment]
After extensive enquiry, I am afraid I can only say that we don't currently have this.
