### ISSUE TITLE
NDIS 6.0 RSS

### ISSUE THREAD

**Issue by robert1859** [MicrosoftDocs/windows-driver-docs#920]
Hi,
If I would like to get more information about RSS is this link (attached under "NDIS 6.0 Receive Side Scaling") https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddndis/index 
correct? (well technically its correct but was it intended?) :)
Regards,
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647b070a-ef93-b0b6-6e92-6c0bcdad4678
* Version Independent ID: e1f927ce-e80a-7c77-7626-20b0b7bacf86
* Content: [Receive Side Scaling Support](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/receive-scaling)
* Content Source: [windows-driver-docs-pr/network/receive-scaling.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/receive-scaling.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @robert1859 , that was not actually the intention. :) It looks like that old MSDN link got redirected incorrectly at some point when we did a content migration a few months ago, so I'll go ahead and correct all instances of it to point to the correct page: [Receive Side Scaling](https://docs.microsoft.com/windows-hardware/drivers/network/ndis-receive-side-scaling2).

Thanks for finding this! The changes should be live later today.
