### ISSUE TITLE
Parameters, causes and troubleshooting missing

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#949]
Add the list of parameters (with their meanings), as well as the list of possible causes and the troubleshooting steps for this bug check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e536b98-6ad6-fc81-c207-d0f3cc14dcae
* Version Independent ID: 0d50f28d-a361-581b-1729-d160c54ee7df
* Content: [Bug Check 0x22 FILE_SYSTEM](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x22--file-system)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x22--file-system.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x22--file-system.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - I have opened an internal work item to track this work, so closing this issue for now.

As I have mentioned before, we use a process to prioritize the most frequent bug checks out of the hundreds that are currently defined. With our limited documentation team resources, it is likely that we will only be able to do this work for a small sub set of all of the possible stop codes.

Thank you for your interest in improving our stop code docs.
