### ISSUE TITLE
Incomplete info in 32- versus 64-bit pointers article

### ISSUE THREAD

**Issue by irinayat-MS** [MicrosoftDocs/windows-driver-docs#954]
Defining KDEXT_64BIT isn't enough to enable x64. Also EXT_API_VERSION should be defined to return EXT_API_VERSION_NUMBER64 (and, possibly, 6 or higher for the first two values). With the version EXT_API_VERSION_NUMBER (5 or below), it is hooking up 32 APIs (so ReadPointer would call ExtReadVirtualMemory32 rather than ExtReadVirtualMemory for x64 targets).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10c4110-e1ba-f013-6f06-e7e6b76e00be
* Version Independent ID: 65491855-088f-8d96-1cd9-e2145009675e
* Content: [32-Bit Pointers and 64-Bit Pointers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/32-bit-pointers-and-64-bit-pointers)
* Content Source: [windows-driver-docs-pr/debugger/32-bit-pointers-and-64-bit-pointers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/32-bit-pointers-and-64-bit-pointers.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@irinayat-MS - Thanks for sharing your experience with using wdbgexts.

As I look at the sample that ships with the debugger in ` C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\sdk\samples\exts`, it looks like this code is near the top of the dbgexts.h header:
```
// Define KDEXT_64BIT to make all wdbgexts APIs recognize 64 bit addresses
// It is recommended for extensions to use 64 bit headers from wdbgexts so
// the extensions could support 64 bit targets.
//
#define KDEXT_64BIT
#include <wdbgexts.h>
```
I don't  think this topic is trying to describe all of the includes that are required for a working sample. 

But I did add this text to point to the other topics that may also help, as well as promoting the sample code itself, which is where I would start:

For additional information on working with the 64 bit pointers see [Using the DECLARE_API Macro](using-the-declare-api-macro.md) and [Writing WdbgExts Extension Code](writing-wdbgexts-extension-code.md). In addition, examine the sample code that is included as part of the WDK.

Although these topics could certainly be improved, the main effort in Debugger automation docs is in expanding the new [Debugger Data Model C++ Overview](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/data-model-cpp-overview) as that is the (more complex) recommended interface using either JavaScript or C++.

Thanks again for the input and interest in our docs.
