### ISSUE TITLE
info is incomplete

### ISSUE THREAD

**Issue by daviddennisei** [MicrosoftDocs/windows-driver-docs#955]
I needed to add '/all' to your first example to get it to work. Also, the certfile needs to be '.cer' as the example showed. 'p7b' filed did not work, even though it does when the destination is currentUser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4990dff-7776-9e5e-36e0-7ca122e6b9cc
* Version Independent ID: 048b2cdf-c80b-59bf-4f8a-deb812585886
* Content: [Using CertMgr to Install Test Certificates on a Test Computer](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/using-certmgr-to-install-test-certificates-on-a-test-computer)
* Content Source: [windows-driver-docs-pr/install/using-certmgr-to-install-test-certificates-on-a-test-computer.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/install/using-certmgr-to-install-test-certificates-on-a-test-computer.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
Thanks for the suggestion @daviddennisei I've made this change. Will be live by the end of the day.
