### ISSUE TITLE
Inaccurate description of LSO completion

### ISSUE THREAD

**Issue by I-gor-C** [MicrosoftDocs/windows-driver-docs#956]
> Before a miniport driver completes the send of a large TCP packet that it has segmented into smaller packets by using LSO, the driver writes the number of TCP payload bytes that it sent in the segmented packets in the TcpPayload member of NDIS_TCP_LARGE_SEND_OFFLOAD_NET_BUFFER_LIST_INFO.

This is relevant to LSOv1 only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 813a24f1-06fd-85ee-a6cd-74566bac6cad
* Version Independent ID: 3b7c30bc-ec0f-0160-9010-d3a8b29fea05
* Content: [Accessing TCP/IP Offload NET_BUFFER_LIST Information](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/accessing-tcp-ip-offload-net-buffer-list-information)
* Content Source: [windows-driver-docs-pr/network/accessing-tcp-ip-offload-net-buffer-list-information.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/network/accessing-tcp-ip-offload-net-buffer-list-information.md)
* Product: **windows-hardware**
* GitHub Login: @tedhudek
* Microsoft Alias: **windowsdriverdev**

**Comment by duncanmacmichael** [comment]
Hi @I-gor-C, looks like you're correct. The actual [NDIS_TCP_LARGE_SEND_OFFLOAD_NET_BUFFER_LIST_INFO](https://docs.microsoft.com/windows-hardware/drivers/ddi/content/ndis/ns-ndis-_ndis_tcp_large_send_offload_net_buffer_list_info) page backs this up, too. Thanks for finding this! I'll make the change, and the updates should be live later today.
