### ISSUE TITLE
How to work when sound card is IN&OUT at the same time

### ISSUE THREAD

**Issue by alextsai-tainan** [MicrosoftDocs/windows-driver-docs#960]
How to modify the descriptor and let IN/OUT work at the same time?
This Driver can only work in the OUT+Feedback endpoint(explicit).
When modify the descriptor is OUT+IN(implicit), it cannot work.
When modify the descriptor is OUT+Feedback endpoint+IN, it can work, but no IN transaction of Feedback endpoint. So asynchronous incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc8e063-bf45-422a-5918-b5dafc707542
* Version Independent ID: af0056d7-cc8f-0e0b-e252-9a149b9a2530
* Content: [USB Audio 2.0 Drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/usb-2-0-audio-drivers)
* Content Source: [windows-driver-docs-pr/audio/usb-2-0-audio-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/audio/usb-2-0-audio-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **windowsdriverdev**

**Comment by DOMARS** [comment]
@alextsai-tainan - Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
•	[OSR's ntdev List](https://www.osronline.com/showlists.cfm?list=ntdev)
Again, thanks for reaching out. Best of luck with this issue.
