### ISSUE TITLE
Random symbols in code

### ISSUE THREAD

**Issue by Arush-Agarampur** [MicrosoftDocs/windows-driver-docs#961]
The code examples contain some random/garbled characters in them. For example, &#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24bd5a82-a8bf-e0ef-aa40-5bf57a3cdca4
* Version Independent ID: 7b108cb7-d99b-abd2-d6ae-2c6690051d36
* Content: [Local and Global MS-DOS Device Names - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/local-and-global-ms-dos-device-names)
* Content Source: [windows-driver-docs-pr/kernel/local-and-global-ms-dos-device-names.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/local-and-global-ms-dos-device-names.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks for catching that, @Arush-Agarampur. I made the fix in the source and it'll go live when we next update later today.
