### ISSUE TITLE
POINTER_32 defined incorrectly

### ISSUE THREAD

**Issue by PhilBarila** [MicrosoftDocs/windows-driver-docs#962]
Original text:
`typedef void * POINTER_32 PVOID32;`

This definition results in a 64-bit field on a 64-bit system.  Should probably be a UINT32 or other explicitly 32-bit definition:
`typedef UINT32 POINTER_32 PVOID32;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa43f5a-48c4-f7d9-6ba9-18dbfa6c25be
* Version Independent ID: 5aeb873f-f5bc-1dc7-30ac-7aca16a9ab8b
* Content: [Technique 2 Using IoIs32bitProcess - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/technique-2--using-iois32bitprocess)
* Content Source: [windows-driver-docs-pr/kernel/technique-2--using-iois32bitprocess.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/kernel/technique-2--using-iois32bitprocess.md)
* Product: **windows-hardware**
* GitHub Login: @windows-driver-content
* Microsoft Alias: **windowsdriverdev**

**Comment by tedhudek** [comment]
I just updated the page, fix will be live in a few moments.  Thanks for the suggestion, and apologies for the delay.
