### ISSUE TITLE
"Marked in bold"

### ISSUE THREAD

**Issue by Shyamal-V** [MicrosoftDocs/windows-driver-docs#966]
" Be aware that it is not important to define the actual value of the control GUID (marked in bold"

I don't see anything marked in bold in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3cc449a-d2bd-135f-d8b3-14413e947a83
* Version Independent ID: 36626d44-ca9f-43e5-ca16-4ba5b7e3f1cc
* Content: [How do I use WPP in static libraries - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/how-do-i-use-wpp-in-static-libraries-#feedback)
* Content Source: [windows-driver-docs-pr/devtest/how-do-i-use-wpp-in-static-libraries-.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/devtest/how-do-i-use-wpp-in-static-libraries-.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by EliotSeattle** [comment]
Thanks, @Shyamal-V 
Yep, that's an error. Nothing bold here. I removed the statement that there is something bold. I believe the statement was made to emphasize that you don't need the actual name for the control GUID in the call to the static .lib.
