### ISSUE TITLE
Additional resolution option

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#972]
If the startup recovery mechanism cannot fix the problem, could it be good executing an in-place upgrade of the operating system?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae887bf-3638-2247-2248-b136eae1be10
* Version Independent ID: 8f95cb71-9fc3-a2f0-8882-ac86acf414fb
* Content: [Bug Check 0xC0000218 STATUS_CANNOT_LOAD_REGISTRY_FILE - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xc0000218--status-cannot-load-registry-file)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0xc0000218--status-cannot-load-registry-file.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0xc0000218--status-cannot-load-registry-file.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - Many of the recovery options could work, for example if a restore point is available, going back to a restore point before the registry was corrupted would be one option. I'm not sure what parts of the registry an in place upgrade touches. If it writes over the damaged area of the registry that could help, but it would depend what area of the registry is damaged.   You might ask that question on the forums: 
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
Thank you for your interest in improving our stop code docs.
