### ISSUE TITLE
EDID page contains git merge conflicts.

### ISSUE THREAD

**Issue by smithcoin** [MicrosoftDocs/windows-driver-docs#980]
[This page](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/overriding-monitor-edids) is littered with git merge conflicts such as `<<<<<<< HEAD` and `>>>>>>> master`. 

The markdown wasn't generated properly either. For example:
```
```registry
=======
```cpp
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e79e97-9c23-a7a4-f7e9-748525022e9c
* Version Independent ID: ee067739-1ae0-4bd8-a206-4d36c31f17aa
* Content: [Overriding Monitor EDIDs with an INF - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/overriding-monitor-edids)
* Content Source: [windows-driver-docs-pr/display/overriding-monitor-edids.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/overriding-monitor-edids.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
@smithcoin Thank you for the issue! I've fixed the topic, and the fixes will be published by tomorrow.
