### ISSUE TITLE
Operation of KDNET during low power states is not documented.

### ISSUE THREAD

**Issue by serusako** [MicrosoftDocs/windows-driver-docs#981]
Operation of KDNET during low power states is not documented.  When using a compatible Ethernet controller and properly configuring kernel debugger over Ethernet, operation of KDNET during low power state is not documented. When target computer goes from S0 to S2 shall debugging connection stay? When target computer goes from S0 to S3 and than back to S0 shall debugging session over Ethenet break or stay?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed06dd7d-eb22-42e1-a2ab-8bf436d3e231
* Version Independent ID: 2152b739-52bf-e743-2f6a-ae7a24cbaf27
* Content: [Setting Up KDNET Network Kernel Debugging Manually - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-a-network-debugging-connection)
* Content Source: [windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/setting-up-a-network-debugging-connection.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@serusako - I don't if we can document the sleep/awake process across all adapters and PCs as the vendors have a good bit of flexibility in how they implement the power state transitions. If you think that the debugger should support a specific sleep awake set of transitions with specific adapters or as a general requirement, you can file product debugger feedback using the Windows Feedback Hub: 
http://aka.ms/dexex 

In general, the KDNET debugger connection does its best to re-establish connections with the target machine, if it is willing and able to communicate.
If you are working with a specific situation where the power states are not behaving as you think they should, you may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. 
•	[OSR's ntdev List](https://community.osr.com/categories/windbg)
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
The community there is quite responsive. Best of luck with this issue.
