### ISSUE TITLE
Value "0xa" for parameter 1

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/windows-driver-docs#991]
Please provide information about the meaning of the value "0xa" for parameter 1.
A dump file I've just analyzed had that value for the first parameter as well as the following information
FAILURE_BUCKET_ID:  0x119_A_DRIVER_REPORTED_INVALID_ABORTED_FENCE_dxgmms2!VidSchiResetEngine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7917857b-97bc-efec-67ab-5e3af061524c
* Version Independent ID: 8c00d20e-9b21-7bb0-a041-220aca9d2487
* Content: [Bug Check 0x119 VIDEO_SCHEDULER_INTERNAL_ERROR - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x119---video-scheduler-internal-error)
* Content Source: [windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/bug-check-0x119---video-scheduler-internal-error.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
@LuigiBruno - Thanks for this issue. The 0Xa parameter is described in the docs as *The driver has reported an invalid fence ID.*  These topics are written for the driver developer - in this case a display driver developer. You can read more about display fence IDs in the display driver documentation: https://docs.microsoft.com/en-us/windows-hardware/drivers/display/supplying-fence-identifiers 
With our limited documentation team resources we can only provide detailed information about a sub set of the most popular bug check codes.
