### ISSUE TITLE
Kernel driver debugging on Surface Go?

### ISSUE THREAD

**Issue by trgardos** [MicrosoftDocs/windows-driver-docs#992]
Surface Go only has WiFi and a USB C port. What's the recommended way to connect a debugger? I see that no USB ethernet adapters are in the supported list. Would a USB 3 crossover debugging cable and a USB-A to C adapter work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67e01ae1-4090-c201-aed8-3d416344db7f
* Version Independent ID: b0a983c8-1386-1ba9-7d62-ac3a8a09b0cf
* Content: [Supported Ethernet NICs for Network Kernel Debugging in Windows 10 - Windows drivers](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/supported-ethernet-nics-for-network-kernel-debugging-in-windows-10#feedback)
* Content Source: [windows-driver-docs-pr/debugger/supported-ethernet-nics-for-network-kernel-debugging-in-windows-10.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/debugger/supported-ethernet-nics-for-network-kernel-debugging-in-windows-10.md)
* Product: **windows-hardware**
* GitHub Login: @DOMARS
* Microsoft Alias: **domars**

**Comment by DOMARS** [comment]
Thanks for reaching out to the Windows Driver Developer Documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the driver documentation.
You may have success posting your question in the following forums, where other driver developers and Microsoft engineers can be found. The community there is quite responsive.
•	[Windows Hardware WDK and Driver Development](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/home?forum=wdk)
I have not debugged a Surface Go, but one additional option to explore, would be using a USB Ethernet adapter with the KDNET network debugging transport.
