### ISSUE TITLE
just  now i added to the registry

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#993]
i added  names in the windows 10 registry 

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrLevel"=dword:00000003
"TdrDelay"=dword:00000002
"TdrDdiDelay"=dword:00000005
"TdrTestMode"=dword:00000000
"TdrDebugMode"=dword:00000002
"TdrLimitTime"=dword:0000003c
"TdrLimitCount"=dword:00000005

do i keep with these  modified keys on windows 10 1803 64 bit ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652e03eb-a834-6c30-44c1-e9c917a94926
* Version Independent ID: bca54aa8-2da8-e389-aa74-f66bf3ab65ab
* Content: [TDR Registry Keys - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/display/tdr-registry-keys)
* Content Source: [windows-driver-docs-pr/display/tdr-registry-keys.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/tdr-registry-keys.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
Hello @RAJU2529 
Thank for raising this question. I will investigate it with the team and get back to you on Monday. Regards, Mimi

**Comment by mimisasouvanh** [comment]
Hi @RAJU2529 
The keys should be the same for Windows 10, version 1803 64 bit.
Thanks,
Mimi
