### ISSUE TITLE
thanks a lot 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#996]
great explanations.
All the best to the authors 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dba80576-7bdf-5b27-30ed-f33022e368af
* Version Independent ID: 3116e737-dbb3-2588-f003-45fee8619a3f
* Content: [GPU virtual memory in WDDM 2.0 - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/display/gpu-virtual-memory-in-wddm-2-0)
* Content Source: [windows-driver-docs-pr/display/gpu-virtual-memory-in-wddm-2-0.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/gpu-virtual-memory-in-wddm-2-0.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
@RAJU2529 Thank you for your feedback! 
Best,
Mimi
