### ISSUE TITLE
thanks for information 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#997]
yes I seen many.inf files, I observed those lines inside.inf file 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7924445-8edc-c398-3f95-3f1e905d4efd
* Version Independent ID: c3609591-99fc-0e53-72d3-4944977f659f
* Content: [Differentiating the SKU for Windows 7 Display Drivers - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/display/differentiating-the-sku-for-windows-7-display-drivers)
* Content Source: [windows-driver-docs-pr/display/differentiating-the-sku-for-windows-7-display-drivers.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/differentiating-the-sku-for-windows-7-display-drivers.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
@RAJU2529 I'm glad you found this article useful!
