### ISSUE TITLE
how to find driver 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#998]
How to find the .inf file which is compatible       to UEFI based compatible. Is there tool is available for finding 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c10d9612-0ae4-18df-3784-4b5ef137c89a
* Version Independent ID: fbcd186b-b4db-4fc9-dc87-0323d4d15554
* Content: [Plug and Play (PnP) in WDDM 1.2 and later - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/display/plug-and-play--pnp--start-and-stop-cases)
* Content Source: [windows-driver-docs-pr/display/plug-and-play--pnp--start-and-stop-cases.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/plug-and-play--pnp--start-and-stop-cases.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
Hi @RAJU2529 
I don't know of any tool that does that. However, I hope you find this article helpful: 
https://blogs.technet.microsoft.com/home_is_where_i_lay_my_head/2012/10/02/how-to-check-in-windows-if-you-are-using-uefi/
