### ISSUE TITLE
how to prevent GPU hangs 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-driver-docs#999]
Is there any registry settings to prevent gpu hangs , while playing games and while streaming videos on YouTube.

Thanks for the article 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 951d2b44-7ab6-4d7e-fe01-eb71a7136905
* Version Independent ID: f0d1f424-7740-1890-2603-150fe08a1b60
* Content: [Limiting Repetitive GPU Hangs and Recoveries - Windows drivers](https://docs.microsoft.com/en-in/windows-hardware/drivers/display/limiting-repetitive-gpu-hangs-and-recoveries)
* Content Source: [windows-driver-docs-pr/display/limiting-repetitive-gpu-hangs-and-recoveries.md](https://github.com/MicrosoftDocs/windows-driver-docs/blob/staging/windows-driver-docs-pr/display/limiting-repetitive-gpu-hangs-and-recoveries.md)
* Product: **windows-hardware**
* GitHub Login: @nabazan-microsoft
* Microsoft Alias: **windowsdriverdev**

**Comment by mimisasouvanh** [comment]
Hi @RAJU2529 
You can attempt to prevent gpu hangs by disabling some GPU features. Try: https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings
or https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys
Best,
Mimi
